### ISSUE TITLE
Error no route to host and timeout

### ISSUE THREAD

**Issue by TarekSalama** [rg3/youtube-dl#8363]
Hello,

I've been getting these errors recently.

"ERROR: Unable to download webpage: <urlopen error [Errno 65] No route to host> (caused by URLError(error(65, 'No route to host'),))"

and

"ERROR: Unable to download webpage: <urlopen error [Errno 60] Operation timed out> (caused by URLError(error(60, 'Operation timed out'),))"

Any idea what's causing them?

I can watch Youtube normally.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by TarekSalama** [comment]
Okay.

I tried to download this link by copying and pasting it into the batchvideos.txt I created

https://www.youtube.com/watch?v=WlYC8gDvutc

Here's the output
`Mac:~ tareksalama$ sudo youtube-dl
Password:
youtube-dl is up-to-date (2016.01.29)
[youtube] WlYC8gDvutc: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 65] No route to host> (caused by URLError(error(65, 'No route to host'),))
ERROR: u'\u2014V' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:—V" ) to search YouTube`

And here's the config file in case you need to look at it

`—V -U --no-overwrites --no-cache-dir --restrict-filenames --ignore-errors --batch-file /Volumes/GreenDisk/PSTUFF/Youtube/batchvideos.txt -o /Volumes/GreenDisk/PSTUFF/Youtube/downloads/%(uploader)s/%(title)s_%(uploader)s_%(id)s.%(ext)s
`

**Comment by TarekSalama** [comment]
I tried once more and I got this as well 

`ERROR: Unable to download webpage: <urlopen error [Errno 60] Operation timed out> (caused by URLError(error(60, 'Operation timed out'),))
ERROR: u'\u2014V' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:—V" ) to search YouTube`

**Comment by dstftw** [comment]
>`—V -U --no-overwrites --no-cache-dir --restrict-filenames --ignore-errors --batch-file /Volumes/GreenDisk/PSTUFF/Youtube/batchvideos.txt -o /Volumes/GreenDisk/PSTUFF/Youtube/downloads/%(uploader)s/%(title)s_%(uploader)s_%(id)s.%(ext)s
`

First character of your command `—V -U ...` is not a dash (`-`).

**Comment by TarekSalama** [comment]
Why did you close my issue?

Well I replaced it with a dash and I still got the same error.

By the way Youtube-dl has been working completely fine for me for months. I've been having those errors for the past few days.

**Comment by dstftw** [comment]
1. Re-read my post.
2. Post the [**full** output](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs) for command without `-V` and `-U`.

**Comment by TarekSalama** [comment]
Oh sorry. I misread the -V part.

Okay here's the output:
``[debug] System config: [u'-v', u'--no-overwrites', u'--no-cache-dir', u'--restrict-filenames', u'--ignore-errors', u'--batch-file', u'/Volumes/GreenDisk/PSTUFF/Youtube/batchvideos.txt', u'-o', u'/Volumes/GreenDisk/PSTUFF/Youtube/downloads/%(uploader)s/%(title)s_%(uploader)s_%(id)s.%(ext)s']
[debug] User config: []
[debug] Command-line args: []
[debug] Batch file urls: [u'https://www.youtube.com/watch?v=WlYC8gDvutc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.29
[debug] Python version 2.7.10 - Darwin-15.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[youtube] WlYC8gDvutc: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 60] Operation timed out> (caused by URLError(error(60, 'Operation timed out'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 352, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1904, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 830, in https_open
    req, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)``

**Comment by dstftw** [comment]
`Operation timed out` means an issue with your network connection. Are you using proxy in your browser? Add `--call-home` to command line and post the output.

**Comment by TarekSalama** [comment]
I'm not using any proxies or VPNs. I'm surprised tho since Youtube is working fine, actually better than it used to be.

Here's the output as you requested:

``[debug] System config: [u'-v', u'--call-home', u'--no-overwrites', u'--no-cache-dir', u'--restrict-filenames', u'--ignore-errors', u'--batch-file', u'/Volumes/GreenDisk/PSTUFF/Youtube/batchvideos.txt', u'-o', u'/Volumes/GreenDisk/PSTUFF/Youtube/downloads/%(uploader)s/%(title)s_%(uploader)s_%(id)s.%(ext)s']
[debug] User config: []
[debug] Command-line args: []
[debug] Batch file urls: [u'https://www.youtube.com/watch?v=WlYC8gDvutc']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.29
[debug] Python version 2.7.10 - Darwin-15.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[debug] Public IP address: 197.38.172.217
[youtube] WlYC8gDvutc: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 65] No route to host> (caused by URLError(error(65, 'No route to host'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 352, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1904, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 830, in https_open
    req, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)``

**Comment by dstftw** [comment]
Post the output of `curl https://www.youtube.com/watch?v=WlYC8gDvutc`.

**Comment by TarekSalama** [comment]
`The-Pentagon:~ tareksalama$ curl https://www.youtube.com/watch?v=WlYC8gDvutc
curl: (7) Failed to connect to www.youtube.com port 443: Operation timed out`

That's really surprising. I can view the video without any problems on Chrome. Any idea what could be causing it to get a timeout even though it loads fine in Chrome and pretty much Safari and on all of my mobile devices?

Thanks

**Comment by TarekSalama** [comment]
Okay. I tried connecting through a VPN and it worked all fine. I seriously have no idea what my ISP could be doing. I can watch Youtube videos at full speed yet I can't download them.
I know this my be way off the scope, but do you have any idea what may be going on?
Other than that, I'm really thankful for your help. I guess you can close the issue. Thanks again.

**Comment by dstftw** [comment]
You may be using for example some YouTube-unblock Chrome extension.

**Comment by TarekSalama** [comment]
Nope not at all. And I've tested it on my iPad and Nexus 5 as well. Works well.
