### ISSUE TITLE
Problem on streaming video from http://www.konserthusetplay.se

### ISSUE THREAD

**Issue by cyhojoey** [rg3/youtube-dl#8370]
Hi, 

I have a problem on streaming video from http://www.konserthusetplay.se
like this:
http://www.konserthusetplay.se/?m=IyQcMOEpmKqT91SVT5OP8Q

Although I can find a link inside its webpage, but it's a low quality video.
http://level3cdn.screen9.com/M/V/I/y/IyQcMOEpmKqT91SVT5OP8Q_medium_h264m.mp4?token=07fd4ae9b4ba13f37a79b"

I can choose 1080p option in the embedded player, but I cannot find the link.

Please add http://www.konserthusetplay.se into your list of supported sites,

**Comment by dstftw** [comment]
konserthusetplay will be supported in the next version.
