### ISSUE TITLE
 Can't login to my youtube account and download my private videos

### ISSUE THREAD

**Issue by TheMiziko** [rg3/youtube-dl#8375]
Hi ! so, I've tried to login with using -u, --username Username command, but after that, it asks me about the password, and I can't type anything.
Is there any way to plug in my youtube account ti yotuube-dl ?

**Comment by dstftw** [comment]
You can type it - it's just not displayed as you type it. Alteratively you can pass it in command line with `-p`.

**Comment by TheMiziko** [comment]
Now i get it, but it still says my login credentials are incorrect, what should I do ? where can I find ther login and password that it requires to login ? because it's not regular google account password and mail

**Comment by dstftw** [comment]
It's google account login/password, check you type them correctly.

**Comment by TheMiziko** [comment]
Okey, I fixed the problem, I just needed to use --no-check-certificate , the password and ID were corrent :) thanks for help :)
