### ISSUE TITLE
--convert-subtitles + --embed-subs should delete original subtitle file also

### ISSUE THREAD

**Issue by y** [rg3/youtube-dl#8382]
I'm using the recipe found [here](https://github.com/rg3/youtube-dl/issues/7909#issuecomment-165972287) to embed ttml subtitles:
`$ youtube-dl -v -f  hls-3216 --write-sub --sub-format ttml --convert-subtitles srt --embed-subs http://www.pbs.org/video/2365646371/`

The converted srt file is deleted after embedding, but the downloaded ttml file is left. It should be deleted also.

    $ youtube-dl --version
    2016.01.27

**Comment by jaimeMF** [comment]
It will work correctly in the next version, thanks for the report!
