### ISSUE TITLE
Adding genre?

### ISSUE THREAD

**Issue by xxsashixx** [rg3/youtube-dl#8384]
Hello!

Love your script! 

Would there be any chance on adding %genre to the list of support formats for id3tagging/metadata?

The video in question has Genre - Artist - Title and I would love it if I could do metadata from title with %genre

Thanks!

**Comment by dstftw** [comment]
Read [this](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient) and provide more context.

**Comment by xxsashixx** [comment]
So theres a bunch of videos that I would like to download with metadata

The video titles is as follows

Genre - Artist - Title

I am wanting to do something like this
youtube-dl -f 140 -o %(title)s.%(ext)s" urlhere --metadata-from-title "%(genre)s - %(artist)s - %(title)s"

however %genre isnt supported?

**Comment by dstftw** [comment]
1. Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).
2. How do you know it's "genre - artists - title" but not "artists - title - with - dashes"?

**Comment by xxsashixx** [comment]
1. https://www.youtube.com/watch?v=_o8kyhNqj9A
2. Because all the videos that have been uploaded are in that sequence Genre - Artist - Title

**Comment by dstftw** [comment]
None of these videos are in format "genre - artist - title" but "【genre】artist - title".

**Comment by xxsashixx** [comment]
However.. is there anyway to add %genre to the list of metadata format/options? 

I've been doing --restrict-filenames to not parse them

**Comment by dstftw** [comment]
This feature will be available in the next version via `--metadata-from-title '【%(genre)s】%(artist)s - %(track)s' --add-metadata`.
