### ISSUE TITLE
Vimeo (private video): "No known codec found"

### ISSUE THREAD

**Issue by JonasOlson** [rg3/youtube-dl#8385]
$ youtube-dl --verbose 'http://allofbach.com/en/bwv/bwv-582/detail/'
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['--verbose', 'http://allofbach.com/en/bwv/bwv-582/detail/']
    [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2014.08.05
    [debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
    [debug] Proxy map: {}
    [generic] detail: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] detail: Downloading webpage
    [generic] detail: Extracting information
    [vimeo] 104617074: Downloading webpage
    [vimeo] 104617074: Extracting information
    ERROR: No known codec found; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/vimeo.py", line 305, in _real_extract
        view_count = int(self._search_regex(r'UserPlays:(\d+)', webpage, 'view count'))
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 391, in _search_regex
        raise RegexNotFoundError(u'Unable to extract %s' % _name)
    RegexNotFoundError: Unable to extract view count; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 516, in extract_info
        ie_result = ie.extract(url)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 170, in extract
        return self._real_extract(url)
      File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/vimeo.py", line 348, in _real_extract
        raise ExtractorError('No known codec found')
    ExtractorError: No known codec found; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
