### ISSUE TITLE
How does youtube-dl work in case of sudden internet disconnection while a download is in progress?

### ISSUE THREAD

**Issue by zealfire** [rg3/youtube-dl#8387]
Firstly thanks for this wonderful repo. I had a question, in my college we are provided  an account using which we can do limited amount of downloading. So when that amount reaches obviously we are disconnected from internet. I wanted to know in that scenario how does youtube-dl works i.e when a download is in progress and we are disconnected?
Does it try to connect again as soon as net disconnects and has there been any amount of timeout limit kept?

**Comment by yan12125** [comment]
When the connection is down, youtube-dl fails with some error messages. For most websites, you can run the same command again to download the remaining part when the connection is available again. youtube-dl does not check for network connection automatically, and you'll have to run the commands manually.
