### ISSUE TITLE
ERROR: content too short

### ISSUE THREAD

**Issue by nteath** [rg3/youtube-dl#8388]
I am trying to download a youtube video and sometimes I get the following error:

0.0% of 369.24MiB at  1.26MiB/s ETA 04:52ERROR: content too short (expected 387171875 bytes and served 27375)

It seems random and when I retry it works fine and downloads the video correctly.

**Comment by dstftw** [comment]
This is usually either a YouTube server-side issue or an issue with your network connection. It has been discussed a lot, use search.
