### ISSUE TITLE
Downloading a video list from VIMEO:  HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by ogry** [rg3/youtube-dl#8390]
C:\Python27>youtube-dl -i -e https://vimeo.com/user10855174/videos --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-i', u'-e', u'https://vimeo.com/user10855174/videos', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.01.31
[debug] Python version 2.7.11 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 352, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 1904, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "c:\python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "c:\python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by Hrxn** [comment]
You could try to change your public IP Address.

Open the configuration panel of your router or modem, an reset the connection, or restart or reboot the device.

**Comment by dstftw** [comment]
Most likely you are blocked for overuse. Read [FAQ entry](https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required) on this issue.
