### ISSUE TITLE
New updates don't contain the DASH video & DASH audio format

### ISSUE THREAD

**Issue by EnginePod** [rg3/youtube-dl#8391]
I'm using the latest version of youtube-dl and the updates after the 15th of January (maybe even later, 15th was the latest I tried with) don't contain the (DASH video) or (DASH audio) in their _format_.

**Before the update: 480x360 (DASH video) - webm
After the update: 480x360 - webm**

These were really helpful because the DASH files solely contain either audio or video (not both) so it was easier to keep them separated.

I tried to use the newer version, but I kept getting frustrated because I couldn't tell the DASH files apart from the others so after downloading 1 hour videos (I have limited bandwidth and I believe that there are other users with the same issue) and only getting a 720p video without the sound, I reverted back to the update from the 15th which is a shame because now I'm missing out on the great new features.

**All I'm asking is that you please add the (DASH video) or (DASH audio) back to the _format_ so we can tell the audio, video and video+audio files apart, thanks guys.**

**Comment by yan12125** [comment]
Which URL are you trying?

**Comment by phihag** [comment]
Please review our [bug reporting guidelines](https://github.com/rg3/youtube-dl#bugs) and post the missing information. Without that information (firstly, the complete output of youtube-dl when called with `-v`) we can not help you. For what it's worth, works fine for me:

```
$ youtube-dl -F test:youtube
[TestURL] Test URL: http://www.youtube.com/watch?v=BaW_jenozKcj&t=1s&end=9
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading video info webpage
[youtube] BaW_jenozKc: Extracting video information
[youtube] BaW_jenozKc: Downloading DASH manifest
[youtube] BaW_jenozKc: Downloading DASH manifest
[info] Available formats for BaW_jenozKc:
format code  extension  resolution note
249          webm       audio only DASH audio   47k , opus @ 50k, 57.05KiB
250          webm       audio only DASH audio   66k , opus @ 70k, 79.56KiB
171          webm       audio only DASH audio   74k , vorbis@128k (44100Hz), 89.59KiB
140          m4a        audio only DASH audio  127k , m4a_dash container, mp4a.40.2@128k (44100Hz), 154.06KiB
251          webm       audio only DASH audio  155k , opus @160k, 186.27KiB
141          m4a        audio only DASH audio  255k , m4a_dash container, mp4a.40.2@256k (44100Hz), 308.59KiB
278          webm       256x144    DASH video   24k , webm container, vp9, 15fps, video only, 25.51KiB
242          webm       426x240    DASH video   27k , vp9, 30fps, video only, 32.52KiB
243          webm       640x360    DASH video   54k , vp9, 30fps, video only, 65.38KiB
160          mp4        256x144    DASH video  115k , avc1.4d400c, 15fps, video only, 135.08KiB
244          webm       854x480    DASH video  145k , vp9, 30fps, video only, 151.52KiB
133          mp4        426x240    DASH video  246k , avc1.4d4015, 30fps, video only, 294.27KiB
134          mp4        640x360    DASH video  294k , avc1.4d401e, 30fps, video only, 349.59KiB
247          webm       1280x720   DASH video  423k , vp9, 30fps, video only, 451.13KiB
135          mp4        854x480    DASH video  727k , avc1.4d401f, 30fps, video only, 849.41KiB
248          webm       1920x1080  DASH video  731k , vp9, 30fps, video only, 809.99KiB
136          mp4        1280x720   DASH video 1425k , avc1.4d401f, 30fps, video only, 1.60MiB
137          mp4        1920x1080  DASH video 1835k , avc1.640028, 30fps, video only, 2.11MiB
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
36           3gp        320x240    small , mp4v.20.3,  mp4a.40.2@ 32k
5            flv        400x240    small , h263, mp3  @ 64k
43           webm       640x360    medium , vp8.0,  vorbis@128k
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)
```

**Comment by EnginePod** [comment]
Thanks for your replies, I'll explain what's missing.

@yan12125 - any YouTube video
@phihag - while replying to your message I went back and took a close look at the arguments and output.  I found the issue and it was due to the command that I was running for a longtime and it seems as though the new update changed how _--youtube-skip-dash-manifest_ works as some of the format titles were hidden.  Either way, the problem was solved simply by removing _--youtube-skip-dash-manifest_ from the good old command that I've been using for a while to get my videos.

Sorry for wasting your time, again, the new update changed the behavior of command that I was using.

**Comment by yan12125** [comment]
Could you post the command you use and the output, as well as the difference between your expectation and the actual output, for both the latest version and the previously "working" version?

**Comment by EnginePod** [comment]
@yan12125, I just had __--youtube-skip-dash-manifest__ added and it didn't add the (DASH video) to the format, that's the only change, the rest is all the same.

**Comment by dstftw** [comment]
There were no changes for `--youtube-skip-dash-manifest` behavior lately. Last change related to `--youtube-skip-dash-manifest` dates half a year ago.
