### ISSUE TITLE
FOX.COM not working 

### ISSUE THREAD

**Issue by witmore1** [rg3/youtube-dl#8392]
Attempting to download Grease Live. Seems to be same exact issue with CBS.com seems to be redirecting to akamaihd.net and unable to read the file its send. 

url is http://www.fox.com/watch/613149763703/7763025408

witmore1@VM-Ubuntu:~$ youtube-dl http://www.fox.com/watch/613149763703/7763025408 -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.fox.com/watch/613149763703/7763025408', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.01
[debug] Python version 2.7.6 - Linux-3.19.0-25-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avprobe v12_dev0-2253-ge917563, ffmpeg N-77962-g4a3cf18, ffprobe N-77962-g4a3cf18
[debug] Proxy map: {}
[FOX] 613149763703: Downloading webpage
[ThePlatform] OVh1RDzIi8Z4: Downloading SMIL data
[ThePlatform] OVh1RDzIi8Z4: Downloading m3u8 information
[ThePlatform] OVh1RDzIi8Z4: Downloading m3u8 information
[ThePlatform] OVh1RDzIi8Z4: Downloading m3u8 information
[ThePlatform] OVh1RDzIi8Z4: Downloading m3u8 information
[ThePlatform] OVh1RDzIi8Z4: Downloading m3u8 information
[ThePlatform] OVh1RDzIi8Z4: Downloading m3u8 information
[ThePlatform] OVh1RDzIi8Z4: Downloading m3u8 information
[ThePlatform] OVh1RDzIi8Z4: Downloading m3u8 information
[ThePlatform] OVh1RDzIi8Z4: Downloading m3u8 information
[ThePlatform] OVh1RDzIi8Z4: Downloading m3u8 information
[ThePlatform] OVh1RDzIi8Z4: Downloading m3u8 information
[ThePlatform] OVh1RDzIi8Z4: Downloading m3u8 information
[ThePlatform] OVh1RDzIi8Z4: Downloading JSON metadata
[debug] Invoking downloader on u'https://fbchdvod-f.akamaihd.net/i/Fox.com/281/451/Grease_Live_HD_Clean_AUTH_movie_14543197940,88_2628,85_1928,83_1428,80_928,78_628,75_428,97_353,95_278,000.mp4.csmil/index_0_av.m3u8?null=&id=AgBFL4aEpf5yboONr1Zy%2fmcg78cC98RvI29Q%2fq6Q6As89gjpeuyd6CwQ28Tuf6a61QV74%2fYYyaTydA%3d%3d&hdntl=exp=1454432003~acl=%2fi%2fFox.com%2f281%2f451%2fGrease_Live_HD_Clean_AUTH_movie_14543197940*~data=hdntl~hmac=e7861a6d7f0386bdabe409d3cf0f8ce18f30f24a69124a05382962aeb70555a9'
[download] Destination: Grease - The Musical-613149763703.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: _alid_=wc1oOJaNf9eI38IHjgaDEQ==
' -i 'https://fbchdvod-f.akamaihd.net/i/Fox.com/281/451/Grease_Live_HD_Clean_AUTH_movie_14543197940,88_2628,85_1928,83_1428,80_928,78_628,75_428,97_353,95_278,000.mp4.csmil/index_0_av.m3u8?null=&id=AgBFL4aEpf5yboONr1Zy%2fmcg78cC98RvI29Q%2fq6Q6As89gjpeuyd6CwQ28Tuf6a61QV74%2fYYyaTydA%3d%3d&hdntl=exp=1454432003~acl=%2fi%2fFox.com%2f281%2f451%2fGrease_Live_HD_Clean_AUTH_movie_14543197940*~data=hdntl~hmac=e7861a6d7f0386bdabe409d3cf0f8ce18f30f24a69124a05382962aeb70555a9' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:Grease - The Musical-613149763703.mp4.part'
ffmpeg version N-77962-g4a3cf18 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --prefix=/home/witmore/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/witmore/ffmpeg_build/include --extra-ldflags=-L/home/witmore/ffmpeg_build/lib --bindir=/home/witmore/bin --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-openssl --enable-libvpx --enable-libopus
  libavutil      55. 14.100 / 55. 14.100
  libavcodec     57. 22.100 / 57. 22.100
  libavformat    57. 22.100 / 57. 22.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 25.100 /  6. 25.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
https://fbchdvod-f.akamaihd.net/i/Fox.com/281/451/Grease_Live_HD_Clean_AUTH_movie_14543197940,88_2628,85_1928,83_1428,80_928,78_628,75_428,97_353,95_278,000.mp4.csmil/index_0_av.m3u8?null=&id=AgBFL4aEpf5yboONr1Zy%2fmcg78cC98RvI29Q%2fq6Q6As89gjpeuyd6CwQ28Tuf6a61QV74%2fYYyaTydA%3d%3d&hdntl=exp=1454432003~acl=%2fi%2fFox.com%2f281%2f451%2fGrease_Live_HD_Clean_AUTH_movie_14543197940*~data=hdntl~hmac=e7861a6d7f0386bdabe409d3cf0f8ce18f30f24a69124a05382962aeb70555a9: Invalid data found when processing input

ERROR: ffmpeg exited with code 1
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 411, in main
    _real_main(argv)
  File "/usr/local/bin/youtube-dl/youtube_dl/__init__.py", line 401, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1690, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 677, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 747, in process_ie_result
    new_result, download=download, extra_info=extra_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1360, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1622, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1564, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 343, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 76, in real_download
    self.report_error('%s exited with code %d' % (ffpp.basename, retval))
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 156, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 541, in report_error
    self.trouble(error_message, tb)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 503, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by dstftw** [comment]
Duplicate of #8336.
