### ISSUE TITLE
[Bug] "No module named __future__" for py2exe builds

### ISSUE THREAD

**Issue by Tox86** [rg3/youtube-dl#8397]
![facebookbug](https://cloud.githubusercontent.com/assets/7013508/12736146/848041fa-c92c-11e5-8ded-6d7cebee1b42.PNG)

sorry my in is very limited.

**Comment by Hrxn** [comment]
Some infos please, like OS, Python, etc..

**Comment by Tox86** [comment]
Windows 10 64bits, python=none, my batch file for download:
@echo off
 
set downloads=C:\Users\user\Downloads
 
REM ---
 
echo.
echo.
echo.
echo This is a batch file that will use youtube-dl to download
echo a video from a live streaming site like YouTube and others.
echo.
echo.
set /p url="Paste the URL you want to download: "
 
if "%url%"=="" goto no_url
 
REM We need double '%' to escape them.
youtube-dl.exe %url% -i -w --restrict-filenames -o "%downloads%\%%(upload_date)s-%%(id)s-%%(title)s.%%(ext)s"
echo.
echo Finished!
goto end
 
:no_url
echo You didn't give me a URL
 
:end
echo ------------------------------
pause
exit

**Comment by Tox86** [comment]
Sorry test with CBS video and equal:
![problem](https://cloud.githubusercontent.com/assets/7013508/12737264/cafe9222-c935-11e5-9942-bc43123e52e1.PNG)

**Comment by Hrxn** [comment]
No Python installation? Well, that error msg says.. Okay, could be caused by py2exe, I don't know.

Please just try `youtube-dl.exe -v URL` from your cmd, or from a batch file, you get the idea..

**Comment by vxbinaca** [comment]
Try copying and pasting the test it's easier on the devs. Use ```--verbose``` so the problem can be examined.

**Comment by Tox86** [comment]
Ver. 2016.2.5.1 work fine.

**Comment by yan12125** [comment]
Possibly a duplicate of #2919. Do you  have Cyrillic characters in the path?

**Comment by vxbinaca** [comment]
@yan12125 none, all roman.

**Comment by yan12125** [comment]
As reported by @danfiscus at #9529, on 64-bit systems, put youtube-dl.exe in \Windows\Systems32 causes similar errors. Can anyone try https://github.com/rg3/youtube-dl/issues/3065#issuecomment-45716079?

**Comment by Hrxn** [comment]
This one?
> You can put youtube-dl into, say, C:\ytdl, and then add C:\ytdl to your PATH to be able to run youtube-dl from any directory again.

Why shouldn't this work?

**Comment by yan12125** [comment]
#3065 is a proposed solution. The one not working is \Windows\System32.

**Comment by Hrxn** [comment]
Yes...
Any subdir inside of `C:\` in the `PATH` works, as it should.

_System32_ is a special directory of the OS, I would not recommend to randomly put binaries in there, etc.
So what exactly is the issue?

**Comment by yan12125** [comment]
Some people _did_ put youtube-dl.exe in System32 and got errors. I guess @Tox86 is one of them, and I need his/her feedback before closing this issue.

**Comment by Hrxn** [comment]
Oh, okay. Sure..

Pinging @Tox86 
:wink:

**Comment by mpenkov** [comment]
It's been over 2 years and still no reply from @Tox86 , it may be suitable to close this ticket.
