### ISSUE TITLE
fox.com download

### ISSUE THREAD

**Issue by theklap** [rg3/youtube-dl#8400]
trying to download from fox.com get an error Error: No video formats found
video plays in browser for me

youtube-dl # ./youtube-dl "http://www.fox.com/watch/611263555709/7684274688" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.fox.com/watch/611263555709/7684274688', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.31
[debug] Python version 3.4.3 - Linux-4.3.3-x86_64-Intel-R-_Core-TM-2_Duo_CPU_E6550_@_2.33GHz-with-gentoo-2.2
[debug] exe versions: avconv 11.3, avprobe 11.3, rtmpdump 2.4
[debug] Proxy map: {}
[FOX] 611263555709: Downloading webpage
[ThePlatform] Evrb_EZaRtAs: Downloading SMIL data
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 313, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/theplatform.py", line 237, in _real_extract
    formats, subtitles = self._extract_theplatform_smil(smil_url, video_id)
  File "./youtube-dl/youtube_dl/extractor/theplatform.py", line 49, in _extract_theplatform_smil
    transform_rtmp_url=lambda streamer, src: (streamer, 'mp4:' + src))
  File "./youtube-dl/youtube_dl/extractor/common.py", line 1263, in _parse_smil_formats
    self._sort_formats(formats)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 826, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by theklap** [comment]
Sorry this looks like it needs a cable provider login to work.  I am assuming this is not supported yet.

**Comment by dstftw** [comment]
You can always workaround unsupported login with [cookies from your browser](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).
