### ISSUE TITLE
test_youtube_format_selection broken

### ISSUE THREAD

**Issue by anisse** [rg3/youtube-dl#8404]
commit a6c2c24479e5f4827ceb06f64d855329c0a6f593 breaks test_youtube_format_selection

This is the first bad commit, breaking test_youtube_format_selection. Maybe the test needs to be updated

**Comment by yan12125** [comment]
Thanks for pointing that out. Fixed in 1df41411968b52d7fd6d0f0d233ad760aa5e6368.
