### ISSUE TITLE
Is ilegal use this library in my own script?

### ISSUE THREAD

**Issue by fgvenegas** [rg3/youtube-dl#8412]
I apologize for my bad english, Im making a program to download music, and im using this library to download the videos, is that ilegal? can i get troubles with that? thanks

**Comment by Hrxn** [comment]
Well, no..
Using the program itself.
Not illegal.
The sites that are supported by the program.
Also not illegal.

Caveat: You live in a country with extremely stupid laws regarding Internet usage.

**Comment by jaimeMF** [comment]
You should ask a lawyer, we can't give legal advice.
