### ISSUE TITLE
Error 404 when trying to download subtitles from youtube videos

### ISSUE THREAD

**Issue by fturco** [rg3/youtube-dl#8415]
I'm trying to download subtitles from several YouTube videos, but I get the following error message:

```
$ ./youtube-dl --skip-download --write-sub --sub-lang en cpkRvc-sOKk
[youtube] cpkRvc-sOKk: Downloading webpage
[youtube] cpkRvc-sOKk: Downloading video info webpage
[youtube] cpkRvc-sOKk: Extracting video information
[youtube] cpkRvc-sOKk: Downloading DASH manifest
[youtube] cpkRvc-sOKk: Downloading DASH manifest
WARNING: Unable to download subtitle for "en": HTTP Error 404: Not Found
```

I'm using youtube-dl version 2016.02.01.

**Comment by hanguokai** [comment]
I encounter the same error. Two days ago, it's no this error. Maybe youtube made some changes for subtitles.

**Comment by Klaus1189** [comment]
If I go to http://de.savefrom.net/ and paste https://www.youtube.com/watch?v=cpkRvc-sOKk in it, I can still download the srt files when I click on dropdown list (green). 
Are you really sure there is no srt anymore?

**Comment by Klaus1189** [comment]
Forgot to tell you, that I already use the 2016.02.04 from today with new subtitle handling.

**Comment by jaimeMF** [comment]
The old method for getting the srt subtitles doesn't work, perhaps they just convert it from some of the other formats. With youtube-dl you can use `--convert-subs srt`.

If someone finds a way to directly get the srt subtitles from YouTube, feel free to share it.

**Comment by GoTop** [comment]
I upgrade to youtube-dl (2016.02.05.1), but still get this warning:

> WARNING: Unable to download subtitle for "en": HTTP Error 404: Not Found

**Comment by Klaus1189** [comment]
`--convert-subs srt` doesn't work for me. Can anybody please post a sample of how to use it?

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#bugs

**Comment by Klaus1189** [comment]
I try `youtube-dl --all-subs --skip-download --convert-subs srt https://www.youtube.com/watch?v=SUktj3SB6zY` but I only get the vtt subtitles

**Comment by dstftw** [comment]
**Read** the URL I've posted.

**Comment by Klaus1189** [comment]
OK, I use the latest version, I provided my syntax and `--convert-subs srt` doesn't work for me, I don't think it is a bug, I think I use it wrong, so I asked for help, so what I am doing wrong. Please help

**Comment by dstftw** [comment]
>**Please include the full output of youtube-dl when run with `-v`**, i.e. add `-v` flag to your command line, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v http://www.youtube.com/watch?v=BaW_jenozKcj
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```

**Comment by Klaus1189** [comment]
```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. Alle Rechte vorbehalten.

C:\...\youtube-dl>youtube-dl -v --all-subs --skip-download --convert-subs srt https://www.youtube.com/watch?v=SUktj3SB6zY
[debug] System config: []
[debug] User config: [u'-i', u'--proxy', u'']
[debug] Command-line args: [u'-v', u'--all-subs', u'--skip-download', u'--convert-subs', u'srt', u'https://www.youtube.com/watch?v=SUktj3SB6zY']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.02.10
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] SUktj3SB6zY: Downloading webpage
[youtube] SUktj3SB6zY: Downloading video info webpage
[youtube] SUktj3SB6zY: Extracting video information
[youtube] SUktj3SB6zY: Downloading MPD manifest
[info] Writing video subtitles to: Simon's Cat Logic - Love-SUktj3SB6zY.en-GB.vtt
[info] Writing video subtitles to: Simon's Cat Logic - Love-SUktj3SB6zY.ru.vtt
[info] Writing video subtitles to: Simon's Cat Logic - Love-SUktj3SB6zY.fr.vtt
[info] Writing video subtitles to: Simon's Cat Logic - Love-SUktj3SB6zY.pt-PT.vtt
[info] Writing video subtitles to: Simon's Cat Logic - Love-SUktj3SB6zY.it.vtt
[info] Writing video subtitles to: Simon's Cat Logic - Love-SUktj3SB6zY.de-DE.vtt
[info] Writing video subtitles to: Simon's Cat Logic - Love-SUktj3SB6zY.pl.vtt
```

**Comment by dstftw** [comment]
Remove `--skip-download` options. Postprocessors only run after download happens. This is known issue however I can't find the issue number.

**Comment by balrok** [comment]
I think the issue still exists. It is not about the postprocessor but about 404 on subtitle download.
Please try with: 
`./youtube-dl --write-sub --sub-lang en cpkRvc-sOKk`
As you can see I removed `--skip-download` but it still brings 
```
[youtube] cpkRvc-sOKk: Downloading webpage
[youtube] cpkRvc-sOKk: Downloading video info webpage
[youtube] cpkRvc-sOKk: Extracting video information
[youtube] cpkRvc-sOKk: Downloading DASH manifest
WARNING: Unable to download subtitle for "en": HTTP Error 404: Not Found
[download] The Story of Solutions-cpkRvc-sOKk.f136.mp4 has already been downloaded
[download] 100% of 67.28MiB
[download] Destination: The Story of Solutions-cpkRvc-sOKk.f141.m4a
[download] 100% of 16.63MiB in 00:21
[ffmpeg] Merging formats into "The Story of Solutions-cpkRvc-sOKk.mp4"
Deleting original file The Story of Solutions-cpkRvc-sOKk.f136.mp4 (pass -k to keep)
Deleting original file The Story of Solutions-cpkRvc-sOKk.f141.m4a (pass -k to keep)
```
I think the error is `WARNING: Unable to download subtitle for "en": HTTP Error 404: Not Found`
Tested with latest master branch.

Please have a look into this again.
