### ISSUE TITLE
youtube-dl is stop working today

### ISSUE THREAD

**Issue by kundanshrivastava** [rg3/youtube-dl#8424]
I have tried i many ways. few are here
/usr/bin/youtube-dl --write-sub --sub-lang en --skip-download https://www.youtube.com/watch?v=StbJIv49Aco
/usr/bin/youtube-dl --write-auto-sub --sub-lang en --skip-download https://www.youtube.com/watch?v=StbJIv49Aco
/usr/bin/youtube-dl --write-sub --skip-download https://www.youtube.com/watch?v=StbJIv49Aco
/usr/bin/youtube-dl --write-auto-sub --skip-download https://www.youtube.com/watch?v=StbJIv49Aco

even with -o (output dir also) but its not working,
I have updated youtube-dl 
Bellow is youtube-dl -v output

"[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.12.29
[debug] Python version 2.7.6 - Linux-3.13.0-24-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-77455-g4707497, ffprobe N-77455-g4707497
"
i also updated avconv to 11.3-6:11.3-1~trusty,

But this is the output i am getting .

[youtube] StbJIv49Aco: Downloading webpage
[youtube] StbJIv49Aco: Downloading video info webpage
[youtube] StbJIv49Aco: Extracting video information
[youtube] StbJIv49Aco: Downloading DASH manifest
[youtube] StbJIv49Aco: Downloading DASH manifest
WARNING: Unable to download subtitle for "en": HTTP Error 404: Not Found

Can Anyone help, Its really  urgent :-)

**Comment by remitamine** [comment]
downloading subtitles already fixed in master branch and will take effect in the next version(auto captions not fixed yet).
> Its really urgent.

for now add `--sub-format vtt` to the command.

**Comment by phihag** [comment]
You are using an outdated version of youtube-dl. See [our FAQ](https://yt-dl.org/update) on how to update to youtube-dl 2016.02.04 or newer. If the problem persists, please post the output you get with the current version.

**Comment by kundanshrivastava** [comment]
Thanks Guys for Instant reply and quick fix.
I have one question , Will it be possible that we will download srt file format with youtube-dl in future. Because now its not downloading transcript in srt format.

Thannks, Kundan

**Comment by jaimeMF** [comment]
Use `--convert-subs srt`, it requires ffmpeg. Keep in mind that. due to how the program currently works, it doesn't work with `--skip-download`.

**Comment by vondiplo** [comment]
any estimation as to when this would be fixed (including automatic captions) ?

**Comment by dstftw** [comment]
This is already fixed in master.

**Comment by vondiplo** [comment]
Wow that's incredible. Thanks! Just making sure - including automatic captions?

**Comment by phihag** [comment]
Automatic captions work fine for me in the current version of youtube-dl, 2016.02.09.
