### ISSUE TITLE
`--add-metadata` puts Youtube Descriptions in both Description and Comment Metadata

### ISSUE THREAD

**Issue by kriskropd** [rg3/youtube-dl#8430]
Like title suggests - `--add-metadata` appears to be including the description twice, once in the `Description:` and again in the `Comment:` Metadata. For lengthy Descriptions, this can be ugly...

**Comment by dstftw** [comment]
This is intentional, see #4847.

**Comment by kriskropd** [comment]
I think it should be expanded then. It's an ugly solution to assume everyone wants metadata stored like that when not everything operates like VLC.

`--metadata-as-description`
`--metadata-as-comment`

If someone wants both pieces of metadata filled, they can add both options or have a third option that simply keeps what `--add-metadata` does already. 

Also, don't just close an Issue and call it resolved because the issue was intentionally added before. The issue is still an issue.
