### ISSUE TITLE
arte.tv: Unable to extract iframe url 

### ISSUE THREAD

**Issue by del0rean** [rg3/youtube-dl#8432]
Seems that all (?) video downloads from popolar german/french arte TV channel are broken.
Using youtube-dl version 2016.02.04, I get the following error constantly on all video pages, even older ones that worked before.

ERROR: Unable to extract iframe url;

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.

**Comment by del0rean** [comment]
Should have better read the closed issues. Sorry to steal your time. :-/
