### ISSUE TITLE
Lynda.com

### ISSUE THREAD

**Issue by horusra** [rg3/youtube-dl#8434]
can you make it so that it numbers the videos per course order? for example:

001_welcome.mp4
002_letsgetstarted.mp4

otherwise, it would be all mixed up like:

letsgetstarted.mp4
welcome.mp4

And the order would be mixed up (first video wouldn't play first, and I would have to manually rename them all).

**Comment by dstftw** [comment]
1. Pass course URL instead of video URL.
2. Use `playlist_index` sequence in [output template](https://github.com/rg3/youtube-dl#output-template).

**Comment by horusra** [comment]
this is the url I'm using:

http://www.lynda.com/Alias-tutorials/Surfacing-F1-Wheel-Alias/173791-2.html

it still downloads the first video only. 

this link 404's:
http://www.lynda.com/Alias-tutorials/Surfacing-F1-Wheel-Alias/

am I pasting the wrong link?

**Comment by dstftw** [comment]
[Read carefully](https://github.com/rg3/youtube-dl#bugs).

**Comment by horusra** [comment]
`C:\Program Files\mpv>youtube-dl.exe -v --cookies "C:\Program Files\mpv\cookies.t
xt" --all-subs --embed-subs -f=bestvideo+bestaudio/best http://www.lynda.com/Rhi
no-tutorials/Rhino-5-Essential-Training/133324-2.html
[debug] System config: []
[debug] User config: [u'--output', u'I:\\! TV\\Lynda\\%(playlist_index)s_%(title
)s.%(ext)s', u'--cookies', u'C:\\Program Files\\mpv\\cookies.txt', u'--no-mtime'
, u'--embed-subs', u'--merge-output-format', u'mp4']
[debug] Command-line args: [u'-v', u'--cookies', u'C:\\Program Files\\mpv\\cooki
es.txt', u'--all-subs', u'--embed-subs', u'-f=bestvideo+bestaudio/best', u'http:
//www.lynda.com/Rhino-tutorials/Rhino-5-Essential-Training/133324-2.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.02.04
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-78304-g37db3e8
[debug] Proxy map: {}
[lynda:course] 133324: Downloading course JSON
[download] Downloading playlist: Rhino 5 Essential Training
[lynda:course] playlist Rhino 5 Essential Training: Collected 83 video ids (down
loading 83 of them)
[download] Downloading video 1 of 83
[lynda] 153876: Downloading video JSON
[lynda] 153876: Checking 1-540 video format URL
[lynda] 153876: Checking 1-720 video format URL
[lynda] 153876: Checking 1-360 video format URL
[lynda] 153876: Checking 0-540 video format URL
[lynda] 153876: Checking 0-720 video format URL
[lynda] 153876: Checking 0-360 video format URL
[lynda] 153876: Checking 2-540 video format URL
[lynda] 153876: Checking 2-720 video format URL
[lynda] 153876: Checking 2-360 video format URL
[info] Writing video subtitles to: I:\! TV\Lynda\01_Welcome.en.srt
[debug] Invoking downloader on u'http://files2.lynda.com/secure/courses/133324/V
BR_MP4h264_main_HD720/133324_00_01_WX30_welcome.mp4?c3.ri=3773852845394813461&ha
shval=1454643514_d73405b4b3b137b1aa9bfcb6c47a72ae'
[download] Destination: I:\! TV\Lynda\01_Welcome.mp4
[download] 100% of 5.54MiB in 00:00
[ffmpeg] Embedding subtitles in 'I:\! TV\Lynda\01_Welcome.mp4'
[debug] ffmpeg command line: ffmpeg -y -i 'file:I:\! TV\Lynda\01_Welcome.mp4' -i
 'file:I:\! TV\Lynda\01_Welcome.en.srt' -map 0 -c copy -map -0:s -c:s mov_text -
map 1:0 -metadata:s:s:0 language=eng 'file:I:\! TV\Lynda\01_Welcome.temp.mp4'
ERROR: Could not write header for output file #0 (incorrect codec parameters ?):
 Invalid argument
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1736, in post_process
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 351, in run
  File "youtube_dl\postprocessor\ffmpeg.pyo", line 155, in run_ffmpeg_multiple_f
iles
FFmpegPostProcessorError`

**Comment by horusra** [comment]
It seems the error only occurs if I enable to embed subtitles.
