### ISSUE TITLE
How to ignore exceptions caused while downloading multiple videos

### ISSUE THREAD

**Issue by ramadivyasri** [rg3/youtube-dl#8442]
I'm trying to develop a python script to download a bunch of youtube videos which are inputted from a csv file using the youtube-dl module. The script stops as the download fails for a single video. I need the script to continue downloading the next videos ignoring the videos that cannot be downloaded. Can some one please help me on how to handle this in python?

My python code has ignoreerrors option enabled: ydl_opts = {'ignoreerrors':True,'progress_hooks': [my_hook],'format': fmt,'writeinfojson':True,'logger': MyLogger()} with youtube_dl.YoutubeDL(ydl_opts) as ydl: ydl.download([URL]) 

But it is not able to bypass and program exits with below error message ERROR: VqzpEw69Tze: YouTube said: This video does not exist

**Comment by dstftw** [comment]
Post the full source and playlist URL.

**Comment by ramadivyasri** [comment]
I cannot post full source code as it is proprietary. 

ydl_opts = {'ignoreerros':True,'progress_hooks': [my_hook],'format': fmt,'writeinfojson':True,'logger': MyLogger()}
            with youtube_dl.YoutubeDL(ydl_opts) as ydl:
                ydl.download([URL])

The above is the heart of my code.
I'm inputting video id and format id from a csv file:
csv contains:

kfchvCyHmsc,18
vqzpEw69Tzc,22
cskYRDuZIes,22
lUtnas5ScSE,22
Lc-vINJmhNk,18

IF any of the above video does not exist, I need my code to continue downloading preceding videos. But as soon as a video is not found, the script terminates. how can I handle this?

**Comment by dstftw** [comment]
```
ydl_opts = {
    'ignoreerrors': True,
    'simulate': True,
}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download(['kfchvCyHmsc', 'VqzpEw69Tze', 'vqzpEw69Tzc'])
```
```
[youtube] kfchvCyHmsc: Downloading webpage
[youtube] kfchvCyHmsc: Downloading video info webpage
[youtube] kfchvCyHmsc: Extracting video information
[youtube] kfchvCyHmsc: Downloading DASH manifest
[youtube] kfchvCyHmsc: Downloading DASH manifest
[youtube] VqzpEw69Tze: Downloading webpage
[youtube] VqzpEw69Tze: Downloading video info webpage
ERROR: VqzpEw69Tze: YouTube said: This video does not exist.
[youtube] vqzpEw69Tzc: Downloading webpage
[youtube] vqzpEw69Tzc: Downloading video info webpage
[youtube] vqzpEw69Tzc: Extracting video information
[youtube] vqzpEw69Tzc: Downloading DASH manifest
[youtube] vqzpEw69Tzc: Downloading DASH manifest
```
Perfectly skips as expected. `ignoreerrors` only makes sense on multple video URLs or a playlist URL. If you run `download` on a single video URL then run it on each URL yourself. I don't know whether you do so or not since you are not willing to post the code.

**Comment by ramadivyasri** [comment]
Thank you @dstftw
