### ISSUE TITLE
Setting The Episode Download Number

### ISSUE THREAD

**Issue by Xonshiz** [rg3/youtube-dl#8447]
Let's say I want to download the range of specific episodes from crunchyroll. For example :- www.crunchyroll.com/cardcaptor-sakura

As you can see there are 2 sections, 1 for DUB and 1 for SUB.
How do I download Episode 1 - 30 from English Dub?

When I go with the following command, it will download all the 140 videos (Both sub and dub)

`youtube-dl "www.crunchyroll.com/cardcaptor-sakura" -f best[width=1280][height=720] -u username -p password`

Got anything for it? Yes, I have just updated my Youtube-DL.

**Comment by dstftw** [comment]
`--match-title "\(Dub\) Episode (?:\d|[12]\d|30) "`.
