### ISSUE TITLE
URL IP

### ISSUE THREAD

**Issue by mitguru007** [rg3/youtube-dl#8448]
Hello! brother
when i generate download link using youtube-dl then i see that the download link get variable ip=server main ip address. 
**generated using youtube-dl:**
r20---sn-ab5l6nee.**googlevideo.com**/videoplayback?signature=469E19A7EA1E91859520EADC44C4F6B7896ED943.DA67FE2AE617C74F5B0EC7F5D8C6C69019052AC2&id=o-ACOUb_0hL9Dfay0yYIxRRXSlcFcTqn1Z9sr3OUwrCINH&itag=22&fexp=9416126,9420452,9422596,9423661,9423662&mt=1454812007&mv=m&upn=x2Sm_Mt8_NI&ms=au**&ip=2604:a880:800:10::4aa:7001**&mm=31&mn=sn-ab5l6nee&dur=407.881&expire=1454833726&pl=48&sver=3&ratebypass=yes&sparams=dur,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,source,upn,expire&source=youtube&initcwndbps=12517500&key=yt6&lmt=1454327265676711&ipbits=0&mime=video/mp4&signature=&title=THE_SUBSTITUTE_TEACHER_EXPERIMENT!

but i see on another site (wapistandotinfo) the generate download link ip= google Search Engine Spider ip address 107.178.194.122 you can chek ip info on ip2location.com/demo
**generated from wapistandotinfo:**
r20---sn-vgqsen7e.**c.docs.google.com**/videoplayback?source=youtube&signature=DBD4D1213F3CA4ACAFCAC9F61CF0C1F6D8DCBE65.6E7692C595F2A6764C8D721C92519C2A7448FB91&upn=8oIjlttK_nU&ratebypass=yes&ipbits=0&lmt=1454327265676711&fexp=9416126,9419452,9420452,9420540,9421509,9422596,9422778,9423661,9423662,9424822,9425209,9425545,9425744,9427066,9427537,9427708,9427858,9428464&itag=22&sparams=dur,id,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,source,upn,expire&mm=31&**ip=107.178.194.122**&mn=sn-vgqsen7e&id=o-AP5-4ERJU7pAj6N0TytLalqXuMoNR0ZErXP3UureFG8Y&dur=407.881&mime=video/mp4&ms=au&mt=1454821013&pl=27&mv=m&expire=1454842683&key=yt6&sver=3&signature=&title=THE SUBSTITUTE TEACHER EXPERIME

1. Why this ip is different and how it possible generate download link using google search engine spider ip address?
2. why this different  c.docs.google.com ?

Thanks in advacne for help.

**Comment by dstftw** [comment]
1. It's an IP the request to YouTube came from. 107.178.194.122 belongs to Google Cloud range where this website is hosted apparently.
2. Ask YouTube why, youtube-dl does not generate this URL itself.
