### ISSUE TITLE
yotube-dl speed

### ISSUE THREAD

**Issue by mitguru007** [rg3/youtube-dl#8449]
How to increase youtube-dl json output response speed?

**Comment by dstftw** [comment]
You can't without loosing some data. But you can skip DASH manifest downloading with `--youtube-skip-dash-manifest`.

**Comment by mitguru007** [comment]
how to get only specific key value of json output and also skip DASH manifest?
"fulltitle", "url", "height", "ext"
not load any another key and value in json output when use display bellow command.
youtube-dl -j https://www.youtube.com/watch?v=ID

**Comment by dstftw** [comment]
Not possible. Use any JSON parser of choice.

**Comment by mitguru007** [comment]
how to get only specific key with value in json format and also skip DASH manifest?
ONLY load this: "fulltitle", "url", "height", "ext"
not load any another key and value in json output when use bellow command.
youtube-dl -j https://www.youtube.com/watch?v=ID 
- Thanks in advance

**Comment by mitguru007** [comment]
thanks so much for your help. 
please release in next version if possible.

**Comment by dstftw** [comment]
No, this does not make any sense. Just parse JSON.

**Comment by mitguru007** [comment]
ok brother, thanks
