### ISSUE TITLE
ERROR: Error in output template: unsupported format character 'C' (0x43) at index 86 (encoding: 'UTF-8')

### ISSUE THREAD

**Issue by tyrone-mt** [rg3/youtube-dl#8450]
Hi,

I am running the latest version of youtube-dl (youtube-dl is up-to-date (2016.02.05.1)).  Getting the following:

ERROR: Error in output template: unsupported format character 'C' (0x43) at index 86 (encoding: 'UTF-8')
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 582, in prepare_filename
    filename = tmpl % template_dict
ValueError: unsupported format character 'C' (0x43) at index 86

Kindly, could you please help.

**Comment by tedmx** [comment]
Hello tyrone-mt, can you provide command line with arguments which produced the error?

**Comment by tyrone-mt** [comment]
exec("/usr/local/bin/youtube-dl --proxy 'xxx.xxx.xxx.xxx:xxxx' --verbose $website_url/$video_url -o PATH/videos/$video_url.mp4;");

**Comment by tedmx** [comment]
Good, can you also tell the $website_url, $video_url, PATH values at the moment of call? Can be an issue with templating characters in "PATH/videos/$video_url.mp4" string.

**Comment by tyrone-mt** [comment]
It seems it's due some weird characters.  Can this be solved somehow please?

**url:** http://www.dailymotion.com/video/x3qohmh_all-go%CE%B1ls-hd-m%CE%BFnch%CE%B5ngl%CE%B1db%CE%B1ch-5-1-w%CE%B5rd%CE%B5r-br%CE%B5m%CE%B5n-05-02-2016-hd_sport

If you copy/paste that link to your browser you would see some weird characters part of the url.

Thanks in advance.

**Comment by dstftw** [comment]
Post the **full** output of youtube-dl when run [with `--verbose` option](https://github.com/rg3/youtube-dl/blob/master/README.md#bugs).

**Comment by tyrone-mt** [comment]
Downloaded http://www.xyz.com/videos/x3qojx3_0-3-kostas-mitroglou-b%CE%B5lenenses-v-b%CE%B5nfica-05-02-2016-hd_sport.mp4[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--proxy', u'107.182.143.26:3128', u'--verbose', u'http://www.dailymotion.com/video/x3qojfj_0-2-jon%CE%B1s-b%CE%B5lenenses-v-b%CE%B5nfica-05-02-2016-hd_sport', u'-o', u'server_path/videos/x3qojfj_0-2-jon%CE%B1s-b%CE%B5lenenses-v-b%CE%B5nfica-05-02-2016-hd_sport.mp4']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2016.02.05.1
[debug] Python version 2.6.6 - Linux-2.6.32-573.12.1.el6.x86_64-x86_64-with-centos-6.7-Final
[debug] exe versions: ffmpeg 1.1.5, ffprobe 1.1.5
[debug] Proxy map: {u'http': u'107.182.143.26:3128', u'https': u'107.182.143.26:3128'}
WARNING: Failed to download m3u8 information: <urlopen error [Errno 104] Connection reset by peer>
ERROR: Error in output template: unsupported format character 'C' (0x43) at index 86 (encoding: 'UTF-8')
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 582, in prepare_filename
    filename = tmpl % template_dict
ValueError: unsupported format character 'C' (0x43) at index 86

**Comment by dstftw** [comment]
Percent character `%` must start [output template sequence](https://github.com/rg3/youtube-dl#output-template). If you want to output percent literal itself you should double it `%%`.
