### ISSUE TITLE
Youtube-dl returns 404 when downloading subtitles

### ISSUE THREAD

**Issue by techno156** [rg3/youtube-dl#8452]
When attempting to download a video from youtube with the subtities (that were probably put up by the uploader), it gives me a 404 error, as shown below. 

800-004A :: ~ » youtube-dl -v --write-sub https://www.youtube.com/watch\?v\=TvLi5E22yCs
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--write-sub', 'https://www.youtube.com/watch?v=TvLi5E22yCs']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.09
[debug] Python version 3.5.1 - Linux-4.2.5-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] TvLi5E22yCs: Downloading webpage
[youtube] TvLi5E22yCs: Downloading video info webpage
[youtube] TvLi5E22yCs: Extracting video information
[youtube] TvLi5E22yCs: Downloading DASH manifest
[youtube] TvLi5E22yCs: Downloading DASH manifest
WARNING: Unable to download subtitle for "en": HTTP Error 404: Not Found
[debug] Invoking downloader on 'https://r3---sn-u2bpouxgoxu-hxaz.googlevideo.com/videoplayback?id=4ef2e2e44db6c82b&itag=136&source=youtube&requiressl=yes&pcm2cms=yes&mn=sn-u2bpouxgoxu-hxaz&mm=31&pl=24&mv=m&ms=au&ratebypass=yes&mime=video/mp4&gir=yes&clen=521804030&lmt=1445359225241373&dur=4914.466&upn=DtzP0ZGHTz4&signature=9912CBB491DAFF99E9B50573E9AF653A7AE188B4.614A8A14FCC8AA28758143863F844D018C9B5483&key=dg_yt0&fexp=9407169,9416074,9416126,9417205,9417701,9418200,9419452,9420452,9422596,9423661,9423662,9424773,9425428,9426471,9428032,9428334&sver=3&mt=1454837534&ip=14.201.37.16&ipbits=0&expire=1454859261&sparams=ip,ipbits,expire,id,itag,source,requiressl,pcm2cms,mn,mm,pl,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: [SUBBED] The Adventure of the Runaway Room - Dai Gyakuten Saiban (The Great Ace Attorney) #04-TvLi5E22yCs.f136.mp4
[download]   0.0% of 497.63MiB at 109.47KiB/s ETA 01:17:33

**Comment by jaimeMF** [comment]
It's already fixed, you have to [update youtube-dl](https://github.com/rg3/youtube-dl/blob/860db2d508f2a18c1b48adb9b1eddc753721bd47/README.md#how-do-i-update-youtube-dl)
