### ISSUE TITLE
fails to download valid youtube https://www.youtube.com/watch?v=tv1U3OSLAVk

### ISSUE THREAD

**Issue by jhb50** [rg3/youtube-dl#8455]
'C:\Users\John>"C:\Program Files\Serviio\lib\youtube-dl.exe" -v https://www.youtu
be.com/watch?v=tv1U3OSLAVk
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=tv1U3OSLAVk
']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.02.05.1
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-67331-g547fce9, ffprobe N-67331-g547fce9, rtmpdum
p 2.4
[debug] Proxy map: {}
[youtube] tv1U3OSLAVk: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILE
D] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SS
L: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
  File "youtube_dl\extractor\common.pyo", line 352, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1903, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 830, in https_open
  File "urllib2.pyo", line 1197, in do_open'

**Comment by dstftw** [comment]
Remove expired certificates: https://github.com/rg3/youtube-dl/issues/7309#issuecomment-172354527.
