### ISSUE TITLE
[SITE-SUPPORT Request] for www.streamable.com

### ISSUE THREAD

**Issue by abdhan** [rg3/youtube-dl#8467]
First of all thanks to everyone for this software.

I tried to make an extractor myself but could not figure out.

Example url: https://streamable.com/dnd1

They support downloads in two qualities: 

Low : https://cdn.streamable.com/video/mp4-mobile/dnd1.mp4

High: https://cdn.streamable.com/video/mp4/dnd1.mp4

The default extractor seems to work for this particular link but it gets only the High Quality version.

title is in `<h1> TITLE </h1>`

Any help is appreciated.

**Comment by yan12125** [comment]
Already supported in the latest version.
