### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Hunter-BT5** [rg3/youtube-dl#8471]
hunter-bt5@Aspire-7736 ~ $ sudo youtube-dl -cit "https://www.youtube.com/watch?v=DqAhNr88zP0&list=PLKYJKVhib-GmntR6oqWErsQh1CXSs5AX5"
[sudo] password for hunter-bt5: 
[youtube:playlist] Downloading playlist PLPLKYJKVhib-GmntR6oqWErsQh1CXSs5AX5 - add --no-playlist to just download video DqAhNr88zP0
[youtube:playlist] PLKYJKVhib-GmntR6oqWErsQh1CXSs5AX5: Downloading page #1
WARNING: [youtube:playlist] PLKYJKVhib-GmntR6oqWErsQh1CXSs5AX5: Playlist page is missing OpenGraph title, falling back ...
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
hunter-bt5@Aspire-7736 ~ $

**Comment by Hrxn** [comment]
> Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type youtube-dl -U to update.

youtube-dl --verbose

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
