### ISSUE TITLE
youtube geo restriction video

### ISSUE THREAD

**Issue by wdfsinap** [rg3/youtube-dl#8472]
I use your latest version of youtube-dl. but i can't download geo restriction video:

C:\>youtube-dl -v http://www.youtube.com/watch?v=DDWKuo3gXMQ
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=DDWKuo3gXMQ']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.02.05
[debug] Python version 2.7.2 - Windows-post2008Server-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] DDWKuo3gXMQ: Downloading webpage
[youtube] DDWKuo3gXMQ: Downloading video info webpage
ERROR: DDWKuo3gXMQ: YouTube said: Unfortunately, this video is not available in your country because it could contain music, for which we could not agree on conditions of use with GEMA.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 313, in extract
    return self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\youtube.py", line 1160, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: DDWKuo3gXMQ: YouTube said: Unfortunately, this video is not available in your country because it could contain music, for which we could not agree on conditions of use with GEMA.

**Comment by anisse** [comment]
youtube-dl cannot bypass geo restrictions. Can you play the video in your browser ?

**Comment by wdfsinap** [comment]
I can't play the video in my browser. but i can play it with http://playit.pk/watch?v=DDWKuo3gXMQ
do you have any idea of how they did this?

**Comment by anisse** [comment]
playit.pk is a proxy. It seems it even provides a right click -> save video as (in Firefox). Please close this issue.

**Comment by wdfsinap** [comment]
sorry, but i want to know how to proxy such geo restricted videos.

**Comment by dstftw** [comment]
Use `--proxy`.
