### ISSUE TITLE
static output downloads garbage

### ISSUE THREAD

**Issue by rqhub** [rg3/youtube-dl#8477]
youtube-dl http://foo.bar -o "%(id)s.%(ext)s"
works fine

however, for some reason, these download 30 mb's that are unreadable 
youtube-dl http://foo.bar -o "video.%(ext)s"
youtube-dl http://foo.bar -o "video.mp4"

any clue ?

**Comment by dstftw** [comment]
[How to report bugs](https://github.com/rg3/youtube-dl#bugs).

**Comment by phihag** [comment]
http://foo.bar is not a valid URL. As @dstftw noted, please post the output you get when you run youtube-dl with the `-v` option.
