### ISSUE TITLE
Viddler Problem (403 error)

### ISSUE THREAD

**Issue by otteydw** [rg3/youtube-dl#8481]
I don't know if all of Viddler isn't working, or just the ones with a secret.  The following URL works for me in a browser, but gives an error in youtube-dl

youtube-dl http://www.viddler.com/v/17210802?secret=########
[Viddler] 17210802: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Running version 2016.02.09

**Comment by dstftw** [comment]
Works fine with all test videos. Post concrete URL with secret.

**Comment by dstftw** [comment]
Secret videos will be supported in the next version.

**Comment by dstftw** [comment]
Fixed in youtube-dl 2016.02.09.1.

**Comment by otteydw** [comment]
Great - 2016.02.09.1 worked.  Thanks!
