### ISSUE TITLE
Option -f bestaudio[ext=m4a] stopped working

### ISSUE THREAD

**Issue by nick-s-b** [rg3/youtube-dl#8482]
Hi all,

About two weeks ago, an option to tell yt-dl to download the best audio given a specific format, `-f bestaudio[ext=m4a]` for example,  stopped woking. For over a year, I've had and alias to youtube-dl to grab the highest quality m4a file that used option but that stopped working for some reason. Just using ``-f bestaudio` sucks because it sometimes grabs webm/opus stuff which I don't want (it's unsupported on everything and higher bitrate doesn't mean it's actually better quality).

Anyone know how to get this option back?

Thanks!

**Comment by phihag** [comment]
Please review [our bug reporting guidelines](https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md). Without the required information (namely the complete output of youtube-dl when called with `-v`), we cannot help you. In particular, *stopped working* could encompass everything from a faulty bit on disk/memory, a custom Python version, networking issues, youtube-dl extractor problems, YoutubeDL core problems with format selection, ffmpeg etc.

**Comment by nick-s-b** [comment]
Apologies @phihag 

>youtube-dl -v --no-playlist --no-mtime --youtube-skip-dash-manifest -f bestaudio\[ext=m4a\]   https://www.youtube.com/watch\?v\=Kzu6edOTu40
> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: [u'-v', u'--no-playlist', u'--no-mtime', u'--youtube-skip-dash-manifest', u'-f', u'bestaudio[ext=m4a]', u'https://www.youtube.com/watch?v=Kzu6edOTu40']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2016.02.09
> [debug] Python version 2.7.9 - Darwin-14.5.0-x86_64-i386-64bit
> [debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg N-69566-g692b226, ffprobe N-69566-g692b226, rtmpdump 2.4
> [debug] Proxy map: {}
> [youtube] Kzu6edOTu40: Downloading webpage
> [youtube] Kzu6edOTu40: Extracting video information
> ERROR: requested format not available
> Traceback (most recent call last):
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 677, in extract_info
>     return self.process_ie_result(ie_result, download, extra_info)
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
>     return self.process_video_result(ie_result, download=download)
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1352, in process_video_result
>     expected=True)
> ExtractorError: requested format not available
> 

I believe the problem is `--youtube-skip-dash-manifest`. I've removed it and now it works!
