### ISSUE TITLE
Download of playlist

### ISSUE THREAD

**Issue by fpandrade1** [rg3/youtube-dl#8483]
error when trying to download playlist on youtube.
command: youtube-dl -s https: //youtube.com/playlist?list = ......
or create a list and terminal type youtube-dl -a  list.... and appears the same error

[youtube:playlist] PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o: Downloading page #1
WARNING: [youtube:playlist] PLHz_AreHm4dlAnJ_jJtV29RFxnPHDuk9o: Playlist page is missing OpenGraph title, falling back ...
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by fpandrade1** [comment]
Version youtube-dl: 2016.01.27
Problem solved, i'm using youtube dl gui.
Thank's.
