### ISSUE TITLE
error when downloading with www.arte.tv

### ISSUE THREAD

**Issue by christianappino** [rg3/youtube-dl#8484]
A copy of a terminal in Ubuntu 14.04 :

$ youtube-dl http://www.arte.tv/guide/fr/006222-019-A/chez-le-forgeron?autoplay=1
[arte.tv:+7] 006222-019-A: Downloading webpage
ERROR: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
