### ISSUE TITLE
Can't download from rtmp:// URLs

### ISSUE THREAD

**Issue by SamusAranX** [rg3/youtube-dl#8488]
This is more of a feature request than a bug report, but hear me out:
youtube-dl is already the one tool I use to download videos, so being able to just throw an RTMP URL at it would be nice.

**Comment by dstftw** [comment]
Bare rtmp URL is usually not enough. In any case why not just call rtmpdump?

**Comment by SamusAranX** [comment]
Mainly because I was on a computer running Windows and I had no clue where youtube-dl keeps it.
Also, I discovered that the particular site I was trying to download from will happily give me an HLS M3U8 file if I visit it with my iPhone's user agent, so I guess this issue just solved itself for me.

**Comment by Hrxn** [comment]
> Mainly because I was on a computer running Windows and I had no clue where youtube-dl keeps it.

?

Where youtube-dl keeps what?

rtmpdump is not part of youtube-dl..
