### ISSUE TITLE
Many videos fail at pbs.org - Unable to download JSON metadata: HTTP Error 404

### ISSUE THREAD

**Issue by AlmostRemember** [rg3/youtube-dl#8491]
In the past few days many videos at http://www.pbs.org/video started failing to download. They had been working fine before that. Certain videos still work but most are now failing. 

Fail:
http://www.pbs.org/video/2365530722
http://www.pbs.org/video/2365472415

Still work:
http://www.pbs.org/video/2365657898
http://www.pbs.org/video/2365245528

D:\Videos>youtube-dl --verbose http://www.pbs.org/video/2332168287
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.pbs.org/video/2332168287']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.02.05.1
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-72259-g0b9d636
[debug] Proxy map: {}
[pbs] 2332168287: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: NOT FOUND (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 352, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1903, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default

**Comment by dstftw** [comment]
Fixed in youtube-dl 2016.02.10.

**Comment by AlmostRemember** [comment]
Downloads are working again but I'm only getting the 360p version of the video. I was getting 720p before. I tried the "-f best" and "-f bestvideo+bestaudio/best" switches but the result was the same.
