### ISSUE TITLE
Site Support Request: screenjunkies.com

### ISSUE THREAD

**Issue by TingPing** [rg3/youtube-dl#8492]
Example URL: http://www.screenjunkies.com/video/best-quentin-tarantino-movie-2841915

**Comment by sudovijay** [comment]
Here's Embed URL - http://www.screenjunkies.com/embed/{video_ID}
Media Links are there in different qualities as a json. 
For eg - http://www.screenjunkies.com/embed/2841915

**Comment by TingPing** [comment]
I got the free videos working, I just can't figure out how to get cookies working on videos you need to log in for.
