### ISSUE TITLE
spaces in format code

### ISSUE THREAD

**Issue by Barnestos** [rg3/youtube-dl#8494]
Hello,
the mediathek of orf.at uses spaces an d brackets in the formatcode name...
format:
...
progressive-Q8C-sehr hoch (HD) mp4       unknown     (best)
...
how can i download a format with spaces and brackets in the name?

thank you,
Barnestos

**Comment by Delivator** [comment]
Did you try to use Quotation Marks?
"progressive-Q8C-sehr hoch"

**Comment by jaimeMF** [comment]
[At least post the url](https://github.com/rg3/youtube-dl/blob/8d0a2a2a4e3e930f9916a96d8ef7bf9c970be088/README.md#bugs) you are trying to download.

**Comment by Barnestos** [comment]
>>>>> command:

youtube-dl http://tvthek.orf.at/program/Overtime-Das-Eishockey-Magazin/8444017/Overtime-Das-Eishockey-Magazin-Folge-22/11930042
[ORF] 8444017: Downloading webpage
[ORF] 11943063: Testing for geoblocking
[download] Downloading playlist: 8444017
[ORF] playlist 8444017: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
ERROR: unable to download video data: HTTP Error 404: Not Found

>>> So, I looked at the formats :

[ORF] 11943063: Testing for geoblockingyoutube-dl -F http://tvthek.orf.at/program/Overtime-Das-Eishockey-Magazin/8444017/Overtime-Das-Eishockey-Magazin-Folge-22/11930042
[ORF] 8444017: Downloading webpage
[ORF] 11943063: Testing for geoblocking
[download] Downloading playlist: 8444017
[ORF] playlist 8444017: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[info] Available formats for 11943063:
format code                    extension resolution  note
hls-Q1A-niedrig                m3u8      unknown     (worst)
hls-Q4A-mittel                 m3u8      unknown
hls-Q8C-sehr hoch (HD)         m3u8      unknown
hds-Q1A-niedrig                f4m       unknown     (unsupported)
hds-Q4A-mittel                 f4m       unknown     (unsupported)
hds-Q6A-hoch                   f4m       unknown     (unsupported)
hds-Q8C-sehr hoch (HD)         f4m       unknown     (unsupported)
streaming-SMIL-hoch            mp4       unknown
streaming-Q1A-mittel           3gp       unknown
streaming-Q1A-niedrig          3gp       unknown
streaming-Q4A-mittel           mp4       unknown
streaming-Q4A-niedrig          mp4       unknown
streaming-Q6A-hoch             mp4       unknown
streaming-Q8C-sehr hoch (HD)   mp4       unknown
streaming-Q8C-sehr hoch (HD)   mp4       unknown
progressive-Q1A-niedrig        3gp       unknown
progressive-Q4A-mittel         mp4       unknown
progressive-Q6A-hoch           mp4       unknown
progressive-Q8C-sehr hoch (HD) mp4       unknown     (best)

>>>> Here are the spaces...
>>>> now with quotation marks:

youtube-dl -f "progressive-Q8C-sehr hoch (HD)" http://tvthek.orf.at/program/Overtime-Das-Eishockey-Magazin/8444017/Overtime-Das-Eishockey-Magazin-Folge-22/11930042
[ORF] 8444017: Downloading webpage
[ORF] 11943063: Testing for geoblocking
[download] Downloading playlist: 8444017
[ORF] playlist 8444017: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
ERROR: unable to download video data: HTTP Error 404: Not Found

>>>> now i'm using a format without spaces and '()' using quotation marks:

youtube-dl -f "progressive-Q6A-hoch" http://tvthek.orf.at/program/Overtime-Das-Eishockey-Magazin/8444017/Overtime-Das-Eishockey-Magazin-Folge-22/11930042
[ORF] 8444017: Downloading webpage
[ORF] 11943063: Testing for geoblocking
[download] Downloading playlist: 8444017
[ORF] playlist 8444017: Collected 1 video ids (downloading 1 of them)
[download] Downloading video #1 of 1
[download] Destination: Overtime - Das Eishockey Magazin - Folge 22-11943063.mp4
[download]   0.3% of 185.14MiB at 155.67KiB/s ETA 20:14^C
ERROR: Interrupted by user

>>> this is working - so is there a problem with spaces and brackets?

**Comment by dstftw** [comment]
Fixed in youtube-dl 2016.02.10.

**Comment by Barnestos** [comment]
thank you!

**Comment by Delivator** [comment]
You're welcome!
