### ISSUE TITLE
[Youku] Youku server reported error -201

### ISSUE THREAD

**Issue by aystroganov** [rg3/youtube-dl#8498]
Hi, I've faced an error while downloading a video from Youku. The output is as follows:

C:\WINDOWS\system32>youtube-dl --verbose http://v.youku.com/v_show/id_XMTM3NDYxMDk5Mg==.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://v.youku.com/v_show/id_XMTM3NDYxMDk5Mg==.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.02.09.1
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youku] XMTM3NDYxMDk5Mg: Downloading JSON metadata
ERROR: Youku server reported error -201: ????????,???<a href="%s" target="_blank"><font color="#22B8FE"><u>???</u></font></a>?; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\program files (x86)\python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "c:\program files (x86)\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 315, in extract
    return self._real_extract(url)
  File "c:\program files (x86)\python35-32\lib\site-packages\youtube_dl\extractor\youku.py", line 236, in _real_extract
    raise ExtractorError(msg)
youtube_dl.utils.ExtractorError: Youku server reported error -201: ????????,???<a href="%s" target="_blank"><font color="#22B8FE"><u>???</u></font></a>?; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thanks in advance,
Alex

**Comment by dstftw** [comment]
Can you watch it in browser in the first place?

**Comment by dstftw** [comment]
This video is private.
