### ISSUE TITLE
New Problems With video.pbs.org

### ISSUE THREAD

**Issue by wright546** [rg3/youtube-dl#8499]
I'm running into the same issue I did as #7565.  I commonly download PBS programs using youtube-dl and it usually works perfectly.  PBS must have changed something on their site because I started receiving errors yesterday.   I tested the URL in the below example in Chrome and verified that the video is actually there and plays successfully. I also updated to the most recent version of youtube-dl, 2016.02.09.1.  I'm using a  FreeBSD 10.2 machine with Python 2.7.9.

Please let me know if I should provide any other information.  Thank you!

 9:45am ~ >./youtube-dl --verbose -F http://www.pbs.org/video/2365656933/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-F', u'http://www.pbs.org/video/2365656933/']
[debug] Encodings: locale US-ASCII, fs US-ASCII, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2016.02.09.1
[debug] Python version 2.7.9 - FreeBSD-10.2-RELEASE-p11-amd64-64bit-ELF
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[pbs] 2365656933: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 404: NOT FOUND (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "./youtube-dl/youtube_dl/extractor/common.py", line 354, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1903, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.

**Comment by wright546** [comment]
Thank you!
