### ISSUE TITLE
Fast moving songs on any version, including on the latest one

### ISSUE THREAD

**Issue by greentrancer** [rg3/youtube-dl#8501]
Hi. I am using this plugin attached to SinusBot for TeamSpeak and sometimes, for some songs, the beats per minute (if I am correct) get increased very much. Usually all the songs are played accordingly, however, for this one - https://www.youtube.com/watch?v=nw5Mc5bpq-A - everything is messed up.

Would you be able to tell where and what the problem is? THank you.

**Comment by dstftw** [comment]
[How to report bugs](https://github.com/rg3/youtube-dl#bugs).
