### ISSUE TITLE
Blocked in : Downloading MPD manifest

### ISSUE THREAD

**Issue by randinfo** [rg3/youtube-dl#8502]
root@ns364096:/home/# youtube-dl -o '1yqfqsf1sY3sJqYt8Q.%(ext)s' -x "https://www.youtube.com/watch?v=LDobPMUSadI" --audio-format mp3 --restrict-filenames --force-ipv4 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-o', u'/home//1yqfqsf1sY3sJqYt8Q.%(ext)s', u'-x', u'https://www.youtube.com/watch?v=LDobPMUSadI', u'--audio-format', u'mp3', u'--restrict-filenames', u'--force-ipv4', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.10
[debug] Python version 2.7.6 - Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg N-77455-g4707497, ffprobe N-77455-g4707497, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] LDobPMUSadI: Downloading webpage
[youtube] LDobPMUSadI: Downloading video info webpage
[youtube] LDobPMUSadI: Extracting video information
[youtube] LDobPMUSadI: Downloading MPD manifest
[debug] Invoking downloader on u'https://r19---sn-5hnedn7k.googlevideo.com/videoplayback?sver=3&keepalive=yes&key=yt6&initcwndbps=1178750&clen=5936666&expire=1455155504&requiressl=yes&ms=au&itag=251&pl=24&mt=1455133687&dur=343.041&id=o-AOQ7CdQqGcjOz2yXH7QfdgEPN97Ji43ujw1ZqXGCdArf&mime=audio%2Fwebm&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&mn=sn-5hnedn7k&ip=91.121.183.150&mm=31&fexp=9408507%2C9416126%2C9417058%2C9418404%2C9419452%2C9420452%2C9420539%2C9422596%2C9423486%2C9423661%2C9423662%2C9423750%2C9425971%2C9426811%2C9427168%2C9428206&lmt=1446826752834884&ipbits=0&mv=m&gir=yes&nh=IgpwcjA0LmFtczE1Kgw4MC4yNDkuMjA5LjA&upn=KOK3HJNeYE8&signature=5AB5621FE76F3F8308643F8D4EFF2F16C96433D1.0F4A1A437EEF2BA331A65B264D6F2A828B5E421F&source=youtube&ratebypass=yes'

I'm updated

root@ns364096:/home/# youtube-dl -U
youtube-dl is up-to-date (2016.02.10)
root@ns364096:/home/lionp3/web/lion.pointmp3.com#

**Comment by yan12125** [comment]
I guess it's a network problem. Can you try again with [strace](https://sourceforge.net/projects/strace/)? For example:
```
strace -f youtube-dl -o '1yqfqsf1sY3sJqYt8Q.%(ext)s' -x "https://www.youtube.com/watch?v=LDobPMUSadI" --audio-format mp3 --restrict-filenames --force-ipv4 --verbose
```

**Comment by marmistrz** [comment]
Hi,
I've just experienced a similar problem. I was able to download the video successfully, without any problems. Now tried to download the audio - and I'm stuck.

Output from strace
```
write(1, "[youtube] bQFy7qzkNro: Downloadi"..., 48[youtube] bQFy7qzkNro: Downloading MPD manifest
) = 48
open("/etc/hosts", O_RDONLY|O_CLOEXEC)  = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=207, ...}) = 0
read(3, "#\n# /etc/hosts: static lookup ta"..., 4096) = 207
read(3, "", 4096)                       = 0
close(3)                                = 0
socket(AF_INET, SOCK_DGRAM|SOCK_NONBLOCK, IPPROTO_IP) = 3
connect(3, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.1.1")}, 16) = 0
poll([{fd=3, events=POLLOUT}], 1, 0)    = 1 ([{fd=3, revents=POLLOUT}])
sendmmsg(3, [{msg_hdr={msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="C\311\1\0\0\1\0\0\0\0\0\0\10manifest\vgooglevide"..., iov_len=42}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_TRUNC|MSG_EOR|MSG_WAITALL|MSG_SYN|MSG_RST|MSG_MORE|0x1620010}, msg_len=42}, {msg_hdr={msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\351L\1\0\0\1\0\0\0\0\0\0\10manifest\vgooglevide"..., iov_len=42}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, msg_len=42}], 2, MSG_NOSIGNAL) = 2
poll([{fd=3, events=POLLIN}], 1, 5000)  = 1 ([{fd=3, revents=POLLIN}])
ioctl(3, FIONREAD, [58])                = 0
recvfrom(3, "C\311\201\0\0\1\0\1\0\0\0\0\10manifest\vgooglevide"..., 2048, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.1.1")}, [28->16]) = 58
poll([{fd=3, events=POLLIN}], 1, 4995)  = 1 ([{fd=3, revents=POLLIN}])
ioctl(3, FIONREAD, [42])                = 0
recvfrom(3, "\351L\201\0\0\1\0\1\0\0\0\0\10manifest\vgooglevide"..., 65536, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.1.1")}, [28->16]) = 42
close(3)                                = 0
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 3
ioctl(3, FIONBIO, [1])                  = 0
connect(3, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("42.0.20.80")}, 16) = -1 EINPROGRESS (Operation now in progress)
poll([{fd=3, events=POLLOUT|POLLERR}], 1, 600000
```

**Comment by yan12125** [comment]
When fetching MPD manifests, youtube-dl tries to connect to ```manifest.googlevideo.com```. On your device this host name maps to 42.0.20.80. According to GeoIP, this IP is in China:
```
$ geoiplookup 42.0.20.80
GeoIP Country Edition: CN, China
```
However, AFAIK Google is blocked in China. I don't think Google will put their servers in China. Your DNS server (192.168.1.1) may be broken or polluted. Please check it.

Closing as no response from the original poster (@randinfo) for a long time. More discussions are still welcome
