### ISSUE TITLE
Feature request: Search for other versions

### ISSUE THREAD

**Issue by lordloh** [rg3/youtube-dl#8503]
I was about to report a bug, but discovered that I had two versions of youtube-dl.  One was installed a long time ago using - 

> sudo curl https://yt-dl.org/downloads/2016.02.10/youtube-dl -o /usr/local/bin/youtube-dl
> sudo chmod a+rx /usr/local/bin/youtube-dl

and the other was installed using 

> sudo pip install --upgrade youtube_dl

`which youtube` showed me that I was using the old version.

It would be good to have youtube-dl look into common paths to see if there is another verision - old / new installed and give user a warning. If this is too much to do on each run, this should atleast happen if there is a bug / error.

A web check to see if a newer version exist (on error) would save a lot of debugging and redundant bug reports.

**Comment by dstftw** [comment]
Managing different versions of youtube-dl is your responsibility not youtube-dl's. youtube-dl can't know all the possible common path your particular package manager may use.
