### ISSUE TITLE
Rate limit for RTMP

### ISSUE THREAD

**Issue by kotofond** [rg3/youtube-dl#8509]
Hi,

I've noticed that --rate-limit option doesn't seem to work for downloads via protocols like 'rtmp' and 'f4m'. Unfortunately I haven't had a chance to dig into the code so I was wondering if you know whether there's an easy way to fix this?
May this rate limit not be applied because youtube-dl internally invokes other tools (ffmpeg, rtmpdump) to download files or parts of files and those tools don't have an option to limit download speed? if so would it be possible to use trickle https://packages.debian.org/wheezy/net/trickle or another bandwidth app to apply rate limit?

Thanks

**Comment by dstftw** [comment]
`--rate-limit` works just fine for f4m and all another native downloader implementations.
For rtmp `rtmpdump` is used that does not support bandwidth limitation.
Don't know about `trickie` have a try.
