### ISSUE TITLE
error occoured downloading the playlist

### ISSUE THREAD

**Issue by nirajlekhak** [rg3/youtube-dl#8514]
debug] System config: []
debug] User config: []
debug] Command-line args: [u'-v', u'-f', u'18', u'https://www.youtube.com/watch?v=qIULMnbH2-o&list=PL6gx4Cwl9DGBPw1sFodruZUPheWVKchlM', u'--playlist-start', u'1', u'--playlist-end',
u'14']
debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
debug] youtube-dl version 2015.04.17
debug] Python version 2.7.8 - Windows-8-6.2.9200
debug] exe versions: none
debug] Proxy map: {}
youtube:playlist] Downloading playlist PL6gx4Cwl9DGBPw1sFodruZUPheWVKchlM - add --no-playlist to just download video qIULMnbH2-o
youtube:playlist] PL6gx4Cwl9DGBPw1sFodruZUPheWVKchlM: Downloading webpage
RROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtub
-dl with the --verbose flag and include its complete output.
raceback (most recent call last):
 File "youtube_dl\YoutubeDL.pyo", line 651, in extract_info
 File "youtube_dl\extractor\common.pyo", line 275, in extract
 File "youtube_dl\extractor\youtube.pyo", line 1355, in _real_extract
 File "youtube_dl\extractor\youtube.pyo", line 1329, in _extract_playlist
 File "youtube_dl\extractor\common.pyo", line 567, in _html_search_regex
 File "youtube_dl\extractor\common.pyo", line 557, in _search_regex
egexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure t
 call youtube-dl with the --verbose flag and include its complete output.

**Comment by Klaus1189** [comment]
I can download the playlist.
Try `https://www.youtube.com/playlist?list=PL6gx4Cwl9DGBPw1sFodruZUPheWVKchlM`

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
