### ISSUE TITLE
Duplicates in archive file?

### ISSUE THREAD

**Issue by IamC8** [rg3/youtube-dl#8516]
Hi. I just looked at my archive file and it is full of duplicates?
Why are id's reinserted when they are supposed to be skipped?

Is this a feature or a bug?
Regards
IamC8

Small example:
youtube VBBzaIgBeyc
youtube VBBzaIgBeyc
youtube jTHa51mMn4Y
youtube jTHa51mMn4Y
youtube 38MVMsmyAcw
youtube 38MVMsmyAcw
youtube v_389JxG_2I
youtube v_389JxG_2I
youtube oLsK_-RQO8A
youtube oLsK_-RQO8A
youtube XHhrz1V3WqA
youtube XHhrz1V3WqA
youtube 7dH7-TI8kOQ
youtube 7dH7-TI8kOQ
youtube dJcxMy0CtG4
youtube dJcxMy0CtG4
youtube ru3T4fEjGKw
youtube ru3T4fEjGKw
youtube Xfu6avMELRE
youtube Xfu6avMELRE
youtube c-le2j8iS-A
youtube c-le2j8iS-A
youtube qwHOplDGUt4
youtube CcAQ36O-b5E
youtube qwHOplDGUt4
youtube geefVAF3XNI
youtube geefVAF3XNI
youtube xJVMp8ptRVE
youtube xJVMp8ptRVE
youtube e0LRFJghO0E
youtube ut7AGJBD-kY

**Comment by dstftw** [comment]
Read [this](https://github.com/rg3/youtube-dl#bugs) and provide complete steps to reproduce this behavior.

**Comment by IamC8** [comment]
Yes that was what happend. Tnx
