### ISSUE TITLE
XHamsterEmbed is broken

### ISSUE THREAD

**Issue by l29ah** [rg3/youtube-dl#8519]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-c', u'--verbose', u'http://justporno.tv/1/1242513/kinky_blowjob_and_needle_piercing_of_brutal_bondage_babe']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.10
[debug] Python version 2.7.11 - Linux-4.2.5-grsec+-x86_64-Intel-R-_Core-TM-_i7_CPU_L_620_@_2.00GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {}
[generic] kinky_blowjob_and_needle_piercing_of_brutal_bondage_babe: Requesting header
WARNING: Falling back on generic information extractor.
[generic] kinky_blowjob_and_needle_piercing_of_brutal_bondage_babe: Downloading webpage
[generic] kinky_blowjob_and_needle_piercing_of_brutal_bondage_babe: Extracting information
[download] Downloading playlist: Kinky blowjob and needle piercing of brutal bondage babe | justporno.tv
[generic] playlist Kinky blowjob and needle piercing of brutal bondage babe | justporno.tv: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[XHamsterEmbed] 2957341: Downloading webpage
ERROR: Unable to extract xhamster url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 315, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/xhamster.py", line 173, in _real_extract
    webpage, 'xhamster url')
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 610, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract xhamster url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
>THIS VIDEO WAS DELETE
