### ISSUE TITLE
how to download all the available subtitles of the video when only provide the video playlist

### ISSUE THREAD

**Issue by wangdongming007** [rg3/youtube-dl#8523]
I try to use the command :  
`youtube-dl.exe https://www.youtube.com/playlistlist=PLjbUi5mgii6AGJW3La3BpEXe27n8v3biT  --all-subs`
but only download the video 

someone can tell me how to download the video and the Subtitle  in a playlistlist

THX!!!

**Comment by dstftw** [comment]
Videos in this playlist don't contain any subtitles by automatic captions, use `--write-auto-sub` to download them.

**Comment by wangdongming007** [comment]
@dstftw  thanks for your kind.

I use your command but it still can't work .
print a message like that :
`WARNING: video doesn't have subtitles`

this course   `https://www.youtube.com/playlistlist=PLjbUi5mgii6AGJW3La3BpEXe27n8v3biT`  do have the  en subtitles.

Is there any other way to download the subtitles of the  Convex Optimization course?
