### ISSUE TITLE
Apple Trailers not getting the video url sometimes

### ISSUE THREAD

**Issue by Peterede** [rg3/youtube-dl#8524]
For the URL http://movietrailers.apple.com/trailers/focus_features/kuboandthetwostrings/ the video url is not found.

**Comment by yan12125** [comment]
Such URLs will be recognized in the next version. However, youtube-dl is currently broken for Apple trailers. See #8422 for more information. I leave this ticket open until #8422 is resolved.

**Comment by yan12125** [comment]
It's working now - Apple trailers are fixed.

**Comment by teebu** [comment]
is this related? http://apptrailers.itunes.apple.com/apple-assets-us-std-000001/PurpleVideo118/v4/63/d0/34/63d034c5-b681-1227-6c14-951c8ebdd999/P49537982_default.m3u8 is missing url in the json.

**Comment by yan12125** [comment]
@teebu Sorry, what do you mean?

**Comment by teebu** [comment]
when i try to dump json on that m3u8, it doesnt have the `url` field in the info.

**Comment by yan12125** [comment]
This m3u8 uses video-only and audio-only formats, so there's no single ```url```. You can check urls from the ```requested_formats``` field.

**Comment by teebu** [comment]
So what you're saging:

```
youtube-dl.exe -F  http://apptrailers.itunes.apple.com/apple-assets-us-std-000001/PurpleVideo118/v4/63/d0/34/63d034c5-b681-1227-6c14-951c8ebdd999/P49537982_default.m3u8

youtube-dl.exe -j -f 3371  http://apptrailers.itunes.apple.com/apple-assets-us-std-000001/PurpleVideo118/v4/63/d0/34/63d034c5-b681-1227-6c14-951c8ebdd999/P49537982_default.m3u8
```

But when I try to do:

```
youtube-dl.exe -j -f best  http://apptrailers.itunes.apple.com/apple-assets-us-std-000001/PurpleVideo118/v4/63/d0/34/63d034c5-b681-1227-6c14-951c8ebdd999/P49537982_default.m3u8
ERROR: requested format not available
```

**Comment by yan12125** [comment]
```best``` means the best video+audio format, while there are only video-only and audio-only formats in this m3u8.

**Comment by teebu** [comment]
How do I auto select best? It looks like that 3371 mp4 also has audio in it.

**Comment by yan12125** [comment]
> How do I auto select best?

Using ```mp4``` as a fallback does not always work. Not every video has a format called "mp4". (A format called mp4 != a format with file extension mp4) You can use ```-f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]'```. If you don't care about file extensions, you can use ```-f bestvideo+bestaudio/best```. Note that ```bestvideo+bestaudio/best``` is the current default.

> It looks like that 3371 mp4 also has audio in it.

No, format 3371 has only one video stream.
