### ISSUE TITLE
Tags support

### ISSUE THREAD

**Issue by kiwixz** [rg3/youtube-dl#8526]
It would be great if youtube-dl could support ID3v2 tags (especially when downloading audio files).
It could set the title, author and even embed the thumbnail ?

**Comment by blha303** [comment]
Audio downloaded from youtube is either m4a or webm, so it's not ID3 tags. Regardless, IMO you don't need to handle these features in the downloading tool, I'd suggest using [mutagen](https://pypi.python.org/pypi/mutagen) to add the tags yourself.

**Comment by kiwixz** [comment]
Yeah I'm wrong, it is not ID3 but something similar. I can and will probably do the tagging afterwards but it is such a waste...

**Comment by blha303** [comment]
I implemented tag support via youtube-dl after requesting it a little while back (#7862), https://github.com/blha303/getsong/blob/v2.0.1/getsong/getsong.py#L102-L117

**Comment by dstftw** [comment]
```
--embed-thumbnail                Embed thumbnail in the audio as cover art
--add-metadata                   Write metadata to the video file
```
