### ISSUE TITLE
Direct download links on website UI

### ISSUE THREAD

**Issue by ladislavczech** [rg3/youtube-dl#8527]
Hi guys, I need your help. I need downloader to my website. I do not want to download videos on my server. How I can provide on youtube-dl direct links to my site users? I have a web UI on my web, but system downloading videos to my server. I want every user to download videos directly to each PC. not on my server. thank you very much for help :-)

**Comment by hemratna** [comment]
@ladislavczech  Hi, 
Even I am also looking for some solution, But NOT ABLE TO FIND IT.

But as you can see http://en.savefrom.net/#url=http://youtube.com/watch?v=iWaFAIRWsA4&utm_source=youtube.com&utm_medium=short_domains&utm_campaign=ssyoutube.com is doing the same thing.

If anybody know how to implement this, It is really great help.

**Comment by kidol** [comment]
Call youtube-dl like this:

>youtube-dl -j URL

It will output json string (it will NOT download). Look at this json string. It contains "formats" key which contains all the direct url's and further informations about the format (like resolution: 720p etc...).

**Comment by dstftw** [comment]
Use `-g` option to extract final download URL. However this [won't work in some cases](https://github.com/rg3/youtube-dl#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-webbrowser).

**Comment by hemratna** [comment]
@kidol  Thank for your reply.
As you suggest -j dump json, But when some once click on that link it will open in browser(Chrome).
But I need to force download video to client side as you can  http://en.savefrom.net/#url=http://youtube.com/watch?v=iWaFAIRWsA4&utm_source=youtube.com&utm_medium=short_domains&utm_campaign=ssyoutube.co (http://i.imgur.com/PyO1cTJ.jpg)

I can write code in php to force download, But Is there any way from where I can get direct url to download.

**Comment by kidol** [comment]
In case of YouTube, you can append "&title=something" to force the download.
