### ISSUE TITLE
Cyrillic letters in youtube video names are ignored when naming downloaded files

### ISSUE THREAD

**Issue by Nick-Triller** [rg3/youtube-dl#8528]
Running "youtube-dl -x --audio-format mp3 https://www.youtube.com/watch?v=i7ZZvwkFNhM" creates a file that is named "  -   -i7ZZvwkFNhM.mp3". 

The file should have the name "Энди Картрайт - Приход глухого кота-i7ZZvwkFNhM.mp3".

**Comment by dstftw** [comment]
[How to report bugs](https://github.com/rg3/youtube-dl#bugs).
