### ISSUE TITLE
Won't download SRT format subtitles (auto captions), always fall back to vtt format

### ISSUE THREAD

**Issue by zeroxia** [rg3/youtube-dl#8532]
youtube-dl version: 2016.02.10
System: Windows 10
Test URL:
https://www.youtube.com/watch?v=h7WtYrZ3b2c

--list-subs shows there is "en" lang, "srt" format available, but download with these options:
--write-auto-sub --write-sub --sub-lang en --sub-format ass/srt/best
will only get .vtt files.

**Comment by dstftw** [comment]
There is no srt on Youtube anymore.
