### ISSUE TITLE
Unable to download MPD manifest for vevo videos

### ISSUE THREAD

**Issue by 0xABC** [rg3/youtube-dl#8533]
If I disable the `use_cipher_signature` check then I get the manifest URL, but then I get this:
`WARNING: [youtube] UxxajLWwzqY: Skipping DASH manifest: ExtractorError(u'Failed to download MPD manifest: HTTP Error 403: Forbidden (caused by HTTPError());`

I believe this is new behaviour. Previously I have been able to get the manifest for vevo videos.

**Comment by dstftw** [comment]
Previously link to non ciphered mpd was served within the webpage.

**Comment by 0xABC** [comment]
Thanks for the confirmation @dstftw . Isn’t this still an “issue” though? Any idea how we can get the mpd?

**Comment by 0xABC** [comment]
I guess this is a duplicate of #8511

**Comment by dstftw** [comment]
There is already an open issue for that.
