### ISSUE TITLE
how to get json and use it in the same time ? 

### ISSUE THREAD

**Issue by abdulsalam1** [rg3/youtube-dl#8535]
hi , i'm working on s project and i get confused from something 
when i have a  long playlist it take a time to have all the json information 
the time depending to the number of videos inside the playlist 
i saw this website he is working with ajax 
http://youtubemultidownloader.com/list.php

i think he use    youtube-dl too 
try to use any long playlist like this (600 video)
https://www.youtube.com/playlist?list=PL6BA2D5208E8EF161

and all the information came immediately 
any idea how that is possible in youtube-dl  please ? 

my server is ubuntu and i'm working on php

**Comment by dstftw** [comment]
1. `--flat-playlist` to extract list of videos.
2. Extract each video separately.

**Comment by abdulsalam1** [comment]
i didn't  understand any thing from those what is the idea from it please ? i just get 

```
> [download] Downloading video 1 of 11
> [download] Downloading video 2 of 11
> [download] Downloading video 3 of 11
> [download] Downloading video 4 of 11
> [download] Downloading video 5 of 11
> [download] Downloading video 6 of 11
> [download] Downloading video 7 of 11
> [download] Downloading video 8 of 11
> [download] Downloading video 9 of 11
> [download] Downloading video 10 of 11
> [download] Downloading video 11 of 11
```

**Comment by dstftw** [comment]
Use it in combine with `-j` obviously or whatever you use.
