### ISSUE TITLE
Missing high-quality videos from PBS.

### ISSUE THREAD

**Issue by tari** [rg3/youtube-dl#8538]
Mentioned as a follow-up in #8491, high-quality (720p) videos are not detected on PBS. It looks like there is now another possible location for metadata, at `http://player.pbs.org/widget/partnerplayer/<video-id>/`

---

Example: http://www.pbs.org/wgbh/nova/body/memory-hackers.html which has a video ID of 2365663085.

Current detected video info page is http://player.pbs.org/portalplayer/2365663085/ where the best available quality from `recommended_encoding` is 800k (360p).
From examining requests made by the web player, http://player.pbs.org/widget/partnerplayer/2365663085/ includes the same encoding options as well as 2500k (720p).

**Comment by StevenDTX** [comment]
Just to add a note...

When downloading from http://www.pbs.org/video/2365641075/, youtube-dl.exe grabs http://ga.video.cdn.pbs.org/videos/frontline/f22fb24c-7ed7-417a-a9f1-dda254eb67e3/217995/hd-1080p-mezzanine-16x9/f028c608_00003404v3-16x9-hls-800k.m3u8 when http://ga.video.cdn.pbs.org/videos/frontline/f22fb24c-7ed7-417a-a9f1-dda254eb67e3/217995/hd-1080p-mezzanine-16x9/f028c608_00003404v3-16x9-hls-2500k.m3u8 is available.

**Comment by StevenDTX** [comment]
Thank you!! Thank you!!
