### ISSUE TITLE
[Taobao.com Video] Add new extractor 

### ISSUE THREAD

**Issue by kashu** [rg3/youtube-dl#8540]
Taobao.com is the largest shopping online platform from China.
Could you add an extractor support for this site?

The video link looks like as following example:
http://vodcdn.video.taobao.com/player/ugc/tb_ugc_pieces_core_player_loader.swf?version=1.0.20150330&showplayinglogo=true&logoposition=right&vid=18943548&uid=2223786851&p=2&t=3&rid=&random=6666

https://sy.taobao.com/serviceDetail.htm?spm=0.0.0.0.lrQa9e&serviceCode=FW_GOODS-1900311&tracelog=&scm=&ppath=

Here is the main page:
http://video.taobao.com/

Thank you.

**Comment by scriptburn** [comment]
any updates on this feature?

**Comment by yan12125** [comment]
Both video links are dead. Please open new issues if there are still unsupported Taobao videos.
