### ISSUE TITLE
count number of videos inside the playlist 

### ISSUE THREAD

**Issue by abdulsalam1** [rg3/youtube-dl#8544]
Hi , 
i need to know is it possible to get the number of videos inside playlist without -J JSON output ? ? 

i don't need to use json because it take a time to load everything 
i need a command that give me the length immediately

**Comment by dstftw** [comment]
I've already [answered](https://github.com/rg3/youtube-dl/issues/8535#issuecomment-183511819) how to get playlist without loading "everything".

**Comment by abdulsalam1** [comment]
your answer is working with  -J to get the json data  

it take a time to load 
but i need something immediately

**Comment by dstftw** [comment]
It's not possible to get the number of videos without going through all the pages of the playlist.
