### ISSUE TITLE
Combine --match-title with -o %(title)s-%(id)s-%(uploader).%(ext)s

### ISSUE THREAD

**Issue by hereinmyhead** [rg3/youtube-dl#8545]

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient

**Comment by hereinmyhead** [comment]
I want to combine --match title with -o but I get this in response:
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: using output template conflicts with using title, video ID or auto number

My code is youtube-dl -o %(title)s-%(id)s-%(uploader).%(ext)s' --match-title test -f best -citw ytuser:username

Is it not possible to use -o and --match-title at the same time?
I want to download Youtube videos from a specific user with a specific text in the title and I want the youtube users name to be in the filename. I can't make it to work.

**Comment by dstftw** [comment]
It's not about the `--match-title` but `-t`, remove this option. Read [this](https://github.com/rg3/youtube-dl#do-i-always-have-to-pass--citw) as well.

**Comment by hereinmyhead** [comment]
Thank you so very much!
