### ISSUE TITLE
download playlist according to the video 

### ISSUE THREAD

**Issue by omarzen** [rg3/youtube-dl#8555]
Hi 
I have this link 

`https://www.youtube.com/watch?v=yyDUC1LUXSU&list=RDyyDUC1LUXSU#t=3`

and i need to download the playlist of it  , according to this link 
what i did is this but it didn't work 

`>  youtube-dl --yes-playlist       --flat-playlist -J https://www.youtube.com/watch?v=yyDUC1LUXSU&list=RDyyDUC1LUXSU#t=3
`

**Comment by dstftw** [comment]
What do you mean by "download the playlist of it"? Read [this](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient) **carefully**.

**Comment by omarzen** [comment]
in general i'm using this command 

`youtube-dl   --flat-playlist -J https://www.youtube.com/playlist?list=PLh6vppUwmWEMdp04u-tYABoDmgn9AX12n ` and i'm getting a json data from this command 

and the real problem is when i wrote this 
`> youtube-dl --yes-playlist --flat-playlist -J https://www.youtube.com/watch?v=yyDUC1LUXSU&list=RDyyDUC1LUXSU#t=3 
` 
i didn't get any information like my previous example

**Comment by dstftw** [comment]
>Read [this](https://github.com/rg3/youtube-dl#bugs) **carefully** and provide required information.

**Comment by omarzen** [comment]
```

root@MyServer:~# youtube-dl  -J -v https://www.youtube.com/watch?v=yyDUC1LUXSU&list=RDyyDUC1LUXSU --yes-playlist
[13] 30287
--yes-playlist: command not found
root@MyServer:~# [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-J', u'-v', u'https://www.youtube.com/watch?v=yyDUC1LUXSU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.6 - Linux-3.13.0-71-generic-x86_64-with-Ubuntu-14.04-trusty

```

and the server stopped it did not complete

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
