### ISSUE TITLE
[myvideo] Fix extraction

### ISSUE THREAD

**Issue by dstftw** [rg3/youtube-dl#8557]
MyVideo now uses kolibri player similarly to [ProSiebenSat.1 Digital](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/prosiebensat1.py).
Kolibri player related code should be generalized if possible.
Note to collaborators: if somebody decides to work on this issue don't forget to self-assign.

Example URLs:
http://www.myvideo.de/themen/infotainment/videos/web-videos-des-tages
http://www.myvideo.de/musik/shawn-mendes/stitches-video-m-11950627
http://www.myvideo.de/serien/made-in-chelsea/staffel-4/folge-12-season-party-m-12051266
http://www.myvideo.de/filme/cristiano-ronaldo-feet-m-11870130

**Comment by TRox1972** [comment]
None of the example URLs work anymore
