### ISSUE TITLE
Got server HTTP error. Retrying

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#856]
For the most part...BRILLIANT!!!

Today came across a Youtube that YouTube-DL doesn't seem to like:
http://www.youtube.com/watch?v=16x2hG8TngU

C:>YouTube-dl.py http://www.youtube.com/watch?v=16x2hG8TngU
[youtube] Setting language
[youtube] 16x2hG8TngU: Downloading video webpage
[youtube] 16x2hG8TngU: Downloading video info webpage
[youtube] 16x2hG8TngU: Extracting video information
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries

Thanks in advance...

**Comment by EvanCarroll** [comment]
Getting this error with `2016.09.11.1` able to reproduce it with 

> youtube-dl -x --yes-playlist "https://www.youtube.com/playlist?list=PLkUw04f_uT1WM9u6leuCgozKXV9Er2Y0D"

Getting the error after 10 video downloads,

```
[download] Destination: JayKode - Kurura-sUwRn4kNGNA.webm
[download] 100% of 4.21MiB in 00:00
[ffmpeg] Destination: JayKode - Kurura-sUwRn4kNGNA.opus
Deleting original file JayKode - Kurura-sUwRn4kNGNA.webm (pass -k to keep)
[download] Downloading video 82 of 92
[youtube] mb2s7oNiD40: Downloading webpage
[youtube] mb2s7oNiD40: Downloading video info webpage
[youtube] mb2s7oNiD40: Extracting video information
[youtube] mb2s7oNiD40: Downloading MPD manifest
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries

```

**Comment by JatraMaya** [comment]
I get this error with 2018.10.05, and able to reproduce it with:
`youtube-dl https://www.youtube.com/watch?v=BVbdZ1133JU` and `youtube-dl -f "bestvideo [height <= 720] + bestaudio/best [height <= 480]" https://www.youtube.com/watch?v=BVbdZ1133JU`

here is the log: 
```
[youtube] BVbdZ1133JU: Downloading webpage
[youtube] BVbdZ1133JU: Downloading video info webpage
[youtube] BVbdZ1133JU: Downloading MPD manifest
[youtube] BVbdZ1133JU: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://r4---sn-uigxxi0ujipnvo-02be.googlevideo.com/videoplayback/id/0556dd675d77dc95/itag/136/source/yt_otf/requiressl/yes/mm/31,29/initcwndbps/95000/mv/m/ms/au,rdu/pcm2cms/yes/pl/24/ei/ZdHCW9CUAsPOoQOl1rFI/mn/sn-uigxxi0ujipnvo-02be,sn-npoeen7r/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1533545432567235/fvip/6/mt/1539494152/disable_polymer/true/ip/202.67.37.30/ipbits/0/expire/1539515845/sparams/ip,ipbits,expire,id,itag,source,requiressl,mm,initcwndbps,mv,ms,pcm2cms,pl,ei,mn,ratebypass,mime,otfp,otf,lmt/signature/298FC4D9506F77E17397F3CD6DBA71FCFA88AAE1.0D53FECC9B824CF194284F99487B76254DB9BCB6/key/dg_yt0/'
[dashsegments] Total fragments: 85
[download] Destination: Complete React Tutorial (& Redux) #9 - Intro to Forms-BVbdZ1133JU.f136.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
```
Thankfully I'm able to download the video with this format `youtube-dl -f 18 https://www.youtube.com/watch?v=BVbdZ1133JU` as sugessted by [jaimeMF](https://github.com/jaimeMF)

**Comment by erikschmidt3001** [comment]
Had the same problem today:

$ youtube-dl https://www.youtube.com/watch?v=UO3TwqRtRr4
[youtube] UO3TwqRtRr4: Downloading webpage
[youtube] UO3TwqRtRr4: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[dashsegments] Total fragments: 219
[download] Destination: Miraculous  Staffel 3, Folge 23  Falsches Spiel  FHD-UO3TwqRtRr4.f137.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
ERROR: giving up after 10 fragment retries

Adding -f 18 allowed me to download, though.

**Comment by antdude** [comment]
Me too right now:

My friend's Fedora v31 on his FIOS:
$ youtube-dl -v https://www.youtube.com/watch?v=j01L69Zz0nM
[debug] System config: ['--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=j01L69Zz0nM']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.7.7 (CPython) - Linux-5.5.11-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] j01L69Zz0nM: Downloading webpage
[youtube] j01L69Zz0nM: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1590303191/ei/d8XJXuffJciskgank5KYDQ/ip/2001%3A470%3Ac%3Af7a%3A%3A2/id/8f4d4bebd673d273/source/youtube/requiressl/yes/playback_host/r5---sn-a5meknek.googlevideo.com/mh/gK/mm/31%2C29/mn/sn-a5meknek%2Csn-a5msen76/ms/au%2Crdu/mv/m/mvi/4/pl/46/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1086250/vprv/1/mt/1590281493/fvip/5/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRgIhAOfn8rVXmqIWk1-iLibQwIZwfPIkV13z1XDEsdhHqoyQAiEAlzz1bf7tgTZqcWGoJTDpJ0ChRfw4_zpRIOxf-FZbnjM%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgVrdBdKSXUh5fiTZ--7t0J3LB4bpe0HEv99zbqMjc11wCIDdjG3JS0fLysb6HcJNaBP0NtjXZntpg3hR0HcWIMhLs'
[dashsegments] Total fragments: 30
[download] Destination: Heavy Metal Gamer Presents - A Shitload of Goombas-j01L69Zz0nM.f299.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
ERROR: giving up after 10 fragment retries
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ant/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/dash.py", line 75, in real_download
    self.report_error('giving up after %s fragment retries' % fragment_retries)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 587, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())


My decade old Debian Jessie v8 box with cable:
$ youtube-dl -v https://www.youtube.com/watch?v=j01L69Zz0nM
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/watch?v=j01L69Zz0nM']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.2 (CPython) - Linux-3.16.0-10-amd64-x86_64-with-debian-8.11
[debug] exe versions: ffmpeg 3.2.10-1, ffprobe 3.2.10-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] j01L69Zz0nM: Downloading webpage
[youtube] j01L69Zz0nM: Downloading MPD manifest
[debug] Default format spec: bestvideo+bestaudio/best
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1590303198/ei/fsXJXtjqCdGOkwaGvLzQBQ/ip/45.50.15.139/id/8f4d4bebd673d273/source/youtube/requiressl/yes/playback_host/r5---sn-a5meknek.googlevideo.com/mh/gK/mm/31%2C29/mn/sn-a5meknek%2Csn-a5msen76/ms/au%2Crdu/mv/m/mvi/4/pl/15/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1677500/vprv/1/mt/1590281493/fvip/5/keepalive/yes/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRgIhANjLFP0TLuNvYgYCkkMf4PB0qOvUi5IqZZ2nyLd_3ZeqAiEAl3344R2bojXpfqBB4JJwYN7x802UoHObkbnoftZ5OiI%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgB1cEkmidVOiAWZyc0hNlIQokiNWLUvNgxytbxDyQPkcCIQC7c4VTrprlLkDx4MLsIm0hCrmzCKJYEYxgUWftv_F-2Q%3D%3D'
[dashsegments] Total fragments: 30
[download] Destination: Heavy Metal Gamer Presents - A Shitload of Goombas-j01L69Zz0nM.f299.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10)...
ERROR: giving up after 10 fragment retries
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ant/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2019, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/dash.py", line 75, in real_download
    self.report_error('giving up after %s fragment retries' % fragment_retries)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/common.py", line 165, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 587, in trouble
tb_data = traceback.format_list(traceback.extract_stack())
