### ISSUE TITLE
Some links stopped playing

### ISSUE THREAD

**Issue by abrasdev** [rg3/youtube-dl#8567]
Some links are not playing anymore. I'm running youtube-dl on my server and I always used this video (7L-Rwxoc2jU) as a test. Youtube-dl returns a link successfully, but it stays stuck in an empty page.

**Comment by jaimeMF** [comment]
[You haven't post the required info](https://github.com/rg3/youtube-dl/blob/8d0a2a2a4e3e930f9916a96d8ef7bf9c970be088/README.md#bugs), we can't help you without it.

In case you are having problems with using the url from youtube-dl in other computer, you should read [this](https://github.com/rg3/youtube-dl/blob/8d0a2a2a4e3e930f9916a96d8ef7bf9c970be088/README.md#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-webbrowser).
