### ISSUE TITLE
[iQiyi] Support VIP videos

### ISSUE THREAD

**Issue by yan12125** [rg3/youtube-dl#8569]
(Original posted at https://github.com/rg3/youtube-dl/issues/8019#issuecomment-183695269)

An example: http://www.iqiyi.com/v_19rrny4w8w.html. Credentials can be found in #8019.

To watch this video, both a VIP account and a China proxy are necessary.

**Comment by yan12125** [comment]
@N1CEyk iQiyi login support is implemented and will  be included in the next version.

**Comment by N1CEyk** [comment]
Thank you very much!!!

2016-02-20 20:02 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:
