### ISSUE TITLE
youtube-dl is prioritizing youtube embeds in comment threads over first party jwplayer video

### ISSUE THREAD

**Issue by alexbobp** [rg3/youtube-dl#8570]
Normally youtube-dl works great on rooster teeth pages.
For example:

> youtube-dl http://roosterteeth.com/episode/rwby-season-3-volume-3-chapter-11

works normally and downloads season 3 chapter 11, using the generic extractor.

> youtube-dl http://roosterteeth.com/episode/rwby-season-3-volume-3-chapter-12-end-of-the-beginning

downloads season 2, chapter 7, using the youtube extractor!  What is happening?  Someone linked that episode via youtube in the comments thread, the rooster teeth cms turns it into an embed, and for some reason youtube-dl is picking that up instead of the main page video.  I also tried with --force-generic-extractor and it had no impact, the wrong video is still downloaded and seemingly the youtube extractor is still used.

I am not sure the best solution.  Detecting and excluding comment sections... prioritizing content higher up on the page... prioritizing jwplayer embeds over remote site embeds... detecting and downloading all videos even if they don't use the same extractor... all seem like options to consider.  My personal preference would be to consider a jwplayer embed to be more likely to be first class content than a youtube embed.

**Comment by yan12125** [comment]
Similar to #5587.

**Comment by alexbobp** [comment]
@yan12125 I don't agree with treating this as a duplicate.  The issue you linked talks about one specific approach, but it's been 9 months that the ticket has been ignored with no progress.  You could at least comment on some of the other approaches I suggested.  My favorite would be to prioritize jwplayer over 3rd party embeds, and surely that's a much easier change.
