### ISSUE TITLE
Error spam while downloading Periscope

### ISSUE THREAD

**Issue by gaussey** [rg3/youtube-dl#8571]
My console is getting Invalid DTS and invalid timestamp errors while downloading from Periscope (live) to the point where I can't see the name of the stream downloading. I suspect those errors are coming from ffmpeg. The captured files are fine, I just want to quieten the output, I've tried sending youtube-dl  -i and -q with no effect.

**Comment by yan12125** [comment]
Please [post the full verbose log with ```-v```](https://github.com/rg3/youtube-dl#bugs).

**Comment by gaussey** [comment]
>C:\ffmpeg>youtube-dl -v https://www.periscope.tv/w/1ypJdWnvAVvGW -o "testgh.mp4"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.periscope.tv/w/1ypJdWnvAVvGW', u'-o', u'testgh.mp4']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-69060-gcd960c8, ffprobe N-69060-gcd960c8, rtmpdump 2.4
[debug] Proxy map: {}
[Periscope] 1ypJdWnvAVvGW: Downloading JSON metadata
[Periscope] 1ypJdWnvAVvGW: Downloading JSON metadata
[debug] Invoking downloader on u'https://periscope-prod-us-east-1.global.ssl.fastly.net/ifffeef7a/liveorigin/6etTvA8F0Op_EesDB8YJYcs6ljUCn6QkGhlsfJMoZVo8WUs6VWIWjMaWbG8eqiLWpaIWKTSS7M6stjuf8oTupA==/playlist.m3u8?t=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJBbGxvd2VkUHJvdG9jb2xzIjpbImhscyJdLCJCcm9hZGNhc3RJZCI6IjF5cEpkV252QVZ2R1ciLCJHcmFudFR5cGUiOiJyZWFkIiwiR3JhbnRlZEF0IjowLCJHcmFudGVkVG8iOiJQ

**Comment by gaussey** [comment]
>VUJMSUMifQ.AfF9Q2PLJlLSfYiR85WlZ_AAQst9flQtFYRc5cl3Yi8'
[download] Destination: testgh.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)
' -i 'https://periscope-prod-us-east-1.global.ssl.fastly.net/ifffeef7a/liveorigin/6etTvA8F0Op_EesDB8YJYcs6ljUCn6QkGhlsfJMoZVo8WUs6VWIWjMaWbG8eqiLWpaIWKTSS7M6stjuf8oTupA==/playlist.m3u8?t=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJBbGxvd2VkUHJvdG9jb2xzIjpbImhscyJdLCJCcm9hZGNhc3RJZCI6IjF5cEpkV252QVZ2R1ciLCJHcmFudFR5cGUiOiJyZWFkIiwiR3JhbnRlZEF0IjowLCJHcmFudGVkVG8iOiJQVUJMSUMifQ.AfF9Q2PLJlLSfYiR85WlZ_AAQst9flQtFYRc5cl3Yi8' -c copy -f mp4 -bsf:a aac_adtstoasc file:testgh.mp4.part
ffmpeg version N-69060-gcd960c8 Copyright (c) 2000-2015 the FFmpeg developers
  built on Jan 14 2015 22:13

**Comment by gaussey** [comment]
>:45 with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
  libavutil      54. 16.100 / 54. 16.100
  libavcodec     56. 20.100 / 56. 20.100
  libavformat    56. 18.101 / 56. 18.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5.

**Comment by gaussey** [comment]
7.101 /  5.  7.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[mpegts @ 0000000006482700] Invalid timestamps stream=1, pts=135283950, dts=135287640, size=382
[mpegts @ 0000000006482700] Invalid timestamps stream=1, pts=135291510, dts=135295200, size=519
[mpegts @ 0000000006482700] Invalid timestamps stream=1, pts=135298980, dts=135302670, size=622
[mpegts @ 0000000006482700] Invalid timestamps stream=1, pts=135306450, dts=135310140, size=538
[mpegts @ 0000000006482700] Invalid timestamps stream=1, pts=135314010, dts=135317700, size=753
[mpegts @ 0000000006482700] Invalid timestamps stream=1, pts=135321480, dts=135325170, size=712
[mpegts @ 0000000006482700] Invalid timestamps stream=1, pts=135328950, dts=135332640, size=454
[mpegts @ 0000000006482700] Invalid timestamps stream=1, pts=135336420, dts=135340110, size=567
[mpegts @ 0000000006482700] Invalid timestamps stream=1, pts=135343980, dts=135347670, size=598
[m

**Comment by gaussey** [comment]
>pegts @ 0000000006482700] Invalid timestamps stream=1, pts=135351450, dts=135355140, size=562
[hls,applehttp @ 0000000004c4d340] Invalid timestamps stream=1, pts=135283950, dts=135287640, size=382
[hls,applehttp @ 0000000004c4d340] Invalid timestamps stream=1, pts=135291510, dts=135295200, size=519
[hls,applehttp @ 0000000004c4d340] Invalid timestamps stream=1, pts=135298980, dts=135302670, size=622
[hls,applehttp @ 0000000004c4d340] Invalid timestamps stream=1, pts=135306450, dts=135310140, size=538
[hls,applehttp @ 0000000004c4d340] Invalid timestamps stream=1, pts=135314010, dts=135317700, size=753
[hls,applehttp @ 0000000004c4d340] Invalid timestamps stream=1, pts=135321480, dts=135325170, size=712
[hls,applehttp @ 0000000004c4d340] Invalid timestamps stream=1, pts=135328950, dts=135332640, size=454
[hls,applehttp @ 0000000004c4d340] Invalid timestamps stream=1, pts=135336420, dts=135340110, size=567
[hls,applehttp @ 0000000004c4d340] Invalid timestamps stream=1, pts=135343980, dts=135347670, si

**Comment by gaussey** [comment]
ze=598
[hls,applehttp @ 0000000004c4d340] Invalid timestamps stream=1, pts=135351450, dts=135355140, size=562        
Input #0, hls,applehttp, from 'https://periscope-prod-us-east-1.global.ssl.fastly.net/ifffeef7a/liveorigin/6etTvA8F0Op_EesDB8YJYcs6ljUCn6QkGhlsfJMoZVo8WUs6VWIWjMaWbG8eqiLWpaIWKTSS7M6stjuf8oTupA==/playlist.m3u8?t=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJBbGxvd2VkUHJvdG9jb2xzIjpbImhscyJdLCJCcm9hZGNhc3RJZCI6IjF5cEpkV252QVZ2R1ciLCJHcmFudFR5cGUiOiJyZWFkIiwiR3JhbnRlZEF0IjowLCJHcmFudGVkVG8iOiJQVUJMSUMifQ.AfF9Q2PLJlLSfYiR85WlZ_AAQst9flQtFYRc5cl3Yi8':
  Duration: N/A, start: 1503.072878, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 349044
    Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 349044
    Stream #0:1: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 320x568, 24 tbr, 90k tbn, 180k tbc
    Metadata:
      variant_bitrate : 349044
    Stream #0:2: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, mo

**Comment by gaussey** [comment]
no, 32 kb/s
    Metadata:
      variant_bitrate : 349044
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 00000000066af020] Invalid DTS: 11081 PTS: 7391 in output stream 0:0, replacing by guess
[mp4 @ 00000000066af020] Invalid DTS: 18641 PTS: 14951 in output stream 0:0, replacing by guess
[mp4 @ 00000000066af020] Invalid DTS: 26111 PTS: 22421 in output stream 0:0, replacing by guess
[mp4 @ 00000000066af020] Invalid DTS: 33581 PTS: 29891 in output stream 0:0, replacing by guess
[mp4 @ 00000000066af020] Invalid DTS: 41141 PTS: 37451 in output stream 0:0, replacing by guess
[mp4 @ 00000000066af020] Invalid DTS: 48611 PTS: 44921 in output stream 0:0, replacing by guess
[mp4 @ 00000000066af020] Invalid DTS: 56081 PTS: 52391 in output stream 0:0, replacing by guess
[mp4 @ 00000000066af020] Invalid DTS: 63551 PTS: 59861 in output stream 0:0, replacing by guess
[mp4 @ 00000000066af020] Invalid DTS: 71111 PTS: 67421 in output stream 0:0, r

**Comment by gaussey** [comment]
and it repeats until interrupted.

**Comment by yan12125** [comment]
Sorry but such errors are caused by problematic files served by Periscope, while it's a good idea to supress errors from ffmpeg with ```-q```. Is it OK for you?

**Comment by gaussey** [comment]
I've tried adding -q to the youtube-dl parameters and it has no effect, is there a way of setting ffmpeg to always use -q?

**Comment by yan12125** [comment]
This is not implemented yet.

**Comment by Vrihub** [comment]
> is there a way of setting ffmpeg to always use -q

Yes, you can add this option to your youtube-dl command line: 
    `--external-downloader-args '-loglevel 16'`
so youtube-dl will pass `-loglevel 16` to ffmpeg: this will suppress ffmpeg warnings often caused by periscope streams.

You can find more information on -loglevel in the ffmpeg man page.

**Comment by gaussey** [comment]
Thanks, that works perfectly, quotes need to be full (on Windows at least).
