### ISSUE TITLE
Can I download the videos from vevo in .ts format?

### ISSUE THREAD

**Issue by jigab0o** [rg3/youtube-dl#8591]
For example http://www.vevo.com/watch/aliz%C3%A9e/Tendre-reve/FRUV71400357

when I open it in Chrome and pick "developer tools" and "network" I can see that the streams are in .ts format:

http://hls-aws.vevo.com/v3/hls/2014/10/FRUV71400357/0b84b56e-5dcd-4823-b7a0-67f6dd27897f/5200/fruv71400357_5200k_1920x1080_h264_5200_aac_128_14.ts

Is it possible to download this file?

**Comment by dstftw** [comment]
This .ts is only a single segment of the complete media represented by a m3u8 playlist. All these files are downloaded and combined to a single file with mp4 extension. So, under the hood these .ts's are actually downloaded.
