### ISSUE TITLE
Only download descriptions

### ISSUE THREAD

**Issue by airatin** [rg3/youtube-dl#8593]
I downloaded a youtube channel but forgot to download the descriptions for the videos! I now know that to download the descriptions we include --write-description in the command, but I don't see how I can download *only* the descriptions, seeing as I'd rather not download GBs worth of videos all over again just for the descriptions. So, how can I *just* download the descriptions from each video in a channel? Thank you!

**Comment by dstftw** [comment]
Use `--skip-download`.
