### ISSUE TITLE
Youtube link with parameters fails

### ISSUE THREAD

**Issue by asgh** [rg3/youtube-dl#8594]
This link fails: https://www.youtube.com/watch?v=bCNU9TrbiRk&index=1&list=WL

If you remove the two parameters at the end it works.

I don't expect it to download the whole watch later list, just the single video.

**Comment by dstftw** [comment]
This kind of URLs will be recognized in the next version. Note that you have to provide `--no-playlist` if you want to download only single video when both playlist and video part are presented in URL at the same time.
