### ISSUE TITLE
Arte +7 not supported

### ISSUE THREAD

**Issue by ypnos-web** [rg3/youtube-dl#8596]
Hello,

I would like to download the following  video:
http://www.arte.tv/guide/de/061700-000-A/maidan-die-kunst-und-die-revolution

youtube-dl --verbose output:

> [debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.arte.tv/guide/de/061700-000-A/maidan-die-kunst-und-die-revolution']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.09
[debug] Python version 3.5.1 - Linux-4.3.3-3-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 2.8.5, ffprobe 2.8.5, rtmpdump 2.4
[debug] Proxy map: {}
[arte.tv:+7] 061700-000-A: Downloading webpage
**ERROR: Unable to extract iframe url**; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 312, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/arte.py", line 83, in _real_extract
    return self._extract_from_webpage(webpage, video_id, lang)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/arte.py", line 98, in _extract_from_webpage
    webpage, 'iframe url', group='url')
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 616, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 607, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract iframe url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

So I went through the HTML myself to find this URL:
https://api.arte.tv/api/player/v1/oembed/de/061700-000-A?platform=ARTEPLUS7&autostart=1&fluid=1

(in this element: `<div arte_vp_config="arte_tvguide" arte_vp_lang="de_DE" arte_vp_url_oembed="https://api.arte.tv/api/player/v1/oembed/de/061700-000-A?platform=ARTEPLUS7&amp;autostart=1&amp;fluid=1" class="video-container"></div>`)

If you open in in the browser you see it is JSON that contains the `<iframe>`. If you run youtube-dl on that URL, it will download it as a file.

This is the iframe URL however:
http://www.arte.tv/arte_vp/index.php?json_url=https%3A%2F%2Fapi.arte.tv%2Fapi%2Fplayer%2Fv1%2Fconfig%2Fde%2F061700-000-A%3Fplatform%3DARTEPLUS7%26autostart%3D1&amp;lang=de_DE&amp;config=arte_tvguide

If you open it in the browser the video starts playing.
youtube-dl --verbose gives:

> [generic] index.php?json_url=https://api.arte: Requesting header
WARNING: Falling back on generic information extractor.
[generic] index.php?json_url=https://api.arte: Downloading webpage
[generic] index.php?json_url=https://api.arte: Extracting information
ERROR: Unsupported URL: http://www.arte.tv/arte_vp/index.php?json_url=https%3A%2F%2Fapi.arte.tv%2Fapi%2Fplayer%2Fv1%2Fconfig%2Fde%2F061700-000-A%3Fplatform%3DARTEPLUS7%26autostart%3D1&amp;lang=de_DE&amp;config=arte_tvguide
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 665, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 312, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/generic.py", line 1908, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.arte.tv/arte_vp/index.php?json_url=https%3A%2F%2Fapi.arte.tv%2Fapi%2Fplayer%2Fv1%2Fconfig%2Fde%2F061700-000-A%3Fplatform%3DARTEPLUS7%26autostart%3D1&amp;lang=de_DE&amp;config=arte_tvguide

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
