### ISSUE TITLE
Whitelisting IP for youtube-dl

### ISSUE THREAD

**Issue by nadermx** [rg3/youtube-dl#8598]
Is there any way to send our server key with the request of the ip when scraping with youtube-dl?  If not is it normally enough to just put the ip in the whitelist for the youtube data api?  I still randomly keep getting 429's and from the gists I have seen that this is due to too many requests, but I have the ip in the youtube api data whitelist.  So not sure if I am missing something.

**Comment by dstftw** [comment]
What do you mean by *our server key*? youtube-dl does not use any kind of youtube APIs apart from those used by a webplayer.

**Comment by nadermx** [comment]
Sorry, meant youtube's api key in their console.  So what I am understanding is if I am hitting the 429 request error even if i white list the IP in google's console that wont solve the problem.  I have to run my requests through proxies then?

**Comment by dstftw** [comment]
Well, I have no idea what privileges whitelisted IP in google's console offers and whether it also affects web requests or not but youtube-dl does not use any official youtube APIs on purpose. You can specify different IP with `--source-address` if you have any or use `--proxy` or torify/socksify/whatever.
