### ISSUE TITLE
youtube-dl should also resume downloads specified with -x

### ISSUE THREAD

**Issue by pie3636** [rg3/youtube-dl#8608]
If I want to download a playlist of, say, 100 videos, and I use the following command :

`youtube-dl -citwx --audio-format mp3 --audio-quality 320K`

The `-c` option does nothing when used in conjunction to `-x`, unless I couple it with `-k`.

So it means that I have to download the 100 videos if I want to be able to resume the transfer, which my hard drive can't handle.

What should happen is that when using `-c`, it also checks for existing mp3 files with the same name as each video, and skip them in that case. This way, each video would only be downloaded once and deleted shortly after.

**Comment by dstftw** [comment]
Use `--download-archive` for that.
