### ISSUE TITLE
Add support for teamtreehouse.com

### ISSUE THREAD

**Issue by behrangsa** [rg3/youtube-dl#8609]
Example URL: `https://teamtreehouse.com/tracks/ios-development-with-swift-20`

If parsed, it can lead to a page such as `https://teamtreehouse.com/library/swift-20-basics/an-introduction-to-swift-programming/what-is-swift` and from there, `youtube-dl` can at least download the `webm` version of the video.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by behrangsa** [comment]
https://teamtreehouse.com/tracks/ios-development-with-swift-20
