### ISSUE TITLE
Video selection based on video duration

### ISSUE THREAD

**Issue by xavier83** [rg3/youtube-dl#862]
Currently there is an option to download videos based on their filesizes but not based on the duration of the video. I would be great to have an option that filters videos that pass the given duration constraints.

**Comment by jaimeMF** [comment]
Since youtube-dl 2015.02.10.2 (the relevant commit is 347de4931cb3e496fb7b1dfb0314c213f44cce6b) you can use the `--match-filter` options, for example if you want to only download videos longer than 1 minute you can use `--match-filter 'duration > 60'`
