### ISSUE TITLE
Not renaming files for new downloads, thinks its already downloaded if trying to download different --format

### ISSUE THREAD

**Issue by vibrasphere** [rg3/youtube-dl#8623]
E.g. downloaded file-format1 file.
Tried to download another file-format1 file.
Says it's already downloaded.
Rename the previously downloaded file.
Retry
Downloads another format file under same title as the previous one that needed to be renamed.
So file-format1+file-format2 doesn't work? It download's only ffile-format1.

**Comment by dstftw** [comment]
This is expected behavior, specify [output template](https://github.com/rg3/youtube-dl#output-template) with `%(format_id)s`.
