### ISSUE TITLE
Lynda JSON Metadata Eroor

### ISSUE THREAD

**Issue by VortekDesign** [rg3/youtube-dl#8627]
Hey, 
I am a total noob but here is my bug report.
Please help me as fast as possible before my trial account expires!
I want to download multiple lynda courses to view offline!

skymint@Skymint ~/Downloads/lynda-download $ youtube-dl -v --cookies cookies.txt http://www.lynda.com/Pro-Tools-tutorials/Pro-Tools-12-Essential-Training/385356-2.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--cookies', u'cookies.txt', u'http://www.lynda.com/Pro-Tools-tutorials/Pro-Tools-12-Essential-Training/385356-2.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.13
[debug] Python version 2.7.6 - Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6
[debug] Proxy map: {}
[lynda:course] 385356: Downloading course JSON
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 354, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1905, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

Thanks guys you are awesome please fix the issue or if it is none help me to fix my problem!
Thumbs up!

**Comment by dstftw** [comment]
[Read closely](https://github.com/rg3/youtube-dl#how-do-i-pass-cookies-to-youtube-dl).
>`HTTP Error 400: Bad Request` when using --cookies is a good sign of invalid newline format
