### ISSUE TITLE
Soundcloud downloads are wav, even if mp3 is specified

### ISSUE THREAD

**Issue by groovinator** [rg3/youtube-dl#8631]
For instance:

```
youtube-dl --audio-format mp3 https://soundcloud.com/mycelium_music/spore-session-vol-13-emog-12-3
[soundcloud] mycelium_music/spore-session-vol-13-emog-12-3: Resolving id
[soundcloud] mycelium_music/spore-session-vol-13-emog-12-3: Downloading info JSON
[soundcloud] 123028713: Downloading track url
[soundcloud] 123028713: Checking download video format URL
[soundcloud] 123028713: Checking http_mp3_128_url video format URL
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[download] Destination: Spore Session Vol. 13 - Emog [12-3-2013]-123028713.wav
```
I'm not sure whether this is because there isn't an mp3 available? If not, rather than downloading the wav, youtube-dl should probably suggest an alternative format. The user probably doesn't want to hammer soundcloud with a giant unecessary wav download!

**Comment by dstftw** [comment]
youtube-dl downloads best available quality by default. You have to [explicitly tell](https://github.com/rg3/youtube-dl#format-selection) it not to download wav if you don't want it.

**Comment by groovinator** [comment]
@dstftw if you look at the command line I used, I actually attempted to do that with the `--audio-format` flag, which was the first thing I found by searching for "mp3" in the man page.  Why doesn't `--audio-format x` imply `--format x` for audio-only downloads?

**Comment by dstftw** [comment]
Because these are different options. `--audio-format` a postprocessing option that is only used with `--extract-audio` to specify settings of audio stream to be extracted from downloaded format (wav in this case). `--format` is an option to specify formats to download.
