### ISSUE TITLE
.fla instead of .mp4

### ISSUE THREAD

**Issue by mitchpitch** [rg3/youtube-dl#8633]
After updating youtube-dl downloads .fla files instead of .mp4 from public German TV:
Example:

Source:
http://www.zdf.de/ZDFmediathek/beitrag/video/2666762/Operation-Naked
MP4: http://nrodl.zdf.de/none/zdf/16/02/160209_operation_naked_ps_opn_1456k_p13v12.mp4

Output:
youtube-dl http://www.zdf.de/ZDFmediathek/beitrag/video/2666762/Operation-Naked
[ZDF] 2666762: Downloading video info
[ZDF] 2666762: Downloading SMIL file
[ZDF] 2666762: Downloading f4m manifest
[ZDF] 2666762: Downloading m3u8 information
[download] Destination: Operation Naked-2666762.flv

**Comment by dstftw** [comment]
rtmp has higher bitrate according to metadata. youtube-dl downloads best available quality by default. You have to [explicitly tell](https://github.com/rg3/youtube-dl#format-selection) youtube-dl to download mp4 if you want mp4.
