### ISSUE TITLE
dl from youtube produces webm file that mplayer and vlc cannot play 

### ISSUE THREAD

**Issue by johnstumbles** [rg3/youtube-dl#8635]
With latest youtube-dl I downloaded this video: https://www.youtube.com/watch?v=BpOJgRWTbjU

mplayer says:

$ mplayer Frankie\ And\ Johnnie\ \[youtube\ BpOJgRWTbjU\].webm 
MPlayer2 2.0-701-gd4c5b7f-2ubuntu2 (C) 2000-2012 MPlayer Team
Cannot open file '/home/john/.mplayer/input.conf': No such file or directory
Failed to open /home/john/.mplayer/input.conf.
Cannot open file '/etc/mplayer/input.conf': No such file or directory
Failed to open /etc/mplayer/input.conf.

Playing Frankie And Johnnie [youtube BpOJgRWTbjU].webm.
[mkv] Unknown/unsupported CodecID (V_VP9) or missing/bad CodecPrivate
[mkv] data (track 1).
[mkv] Track ID 1: video (V_VP9), -vid 0
[mkv] Unknown/unsupported audio codec ID 'A_OPUS' for track 2 or missing/faulty
[mkv] private codec data.
[mkv] Track ID 2: audio (A_OPUS), -aid 0, -alang eng
[mkv] No video track found/wanted.
Detected file format: Matroska
No stream found.

Exiting... (End of file)

vlc says:

$ vlc Frankie\ And\ Johnnie\ \[youtube\ BpOJgRWTbjU\].webm 
VLC media player 2.1.6 Rincewind (revision 2.1.6-0-gea01d28)
[0x719118] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[0x7f6174c01918] mkv demux error: unknown codec id=`A_OPUS'
[0x7f6174c0d658] main decoder error: no suitable decoder module for fourcc `VP90'. VLC probably does not support this sound or video format.
[0x7f6174c0d658] main decoder error: no suitable decoder module for fourcc `undf'. VLC probably does not support this sound or video format.
Bus::open: Can not get ibus-daemon's address. 
IBusInputContext::createInputContext: no connection to ibus-daemon 

This is what youtube-dl says:

$ youtube-dl -v https://www.youtube.com/watch?v=BpOJgRWTbjU
[debug] System config: []
[debug] User config: [u'--output', u'%(title)s [%(extractor)s %(id)s].%(ext)s']
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=BpOJgRWTbjU']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.6 - Linux-3.13.0-77-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] BpOJgRWTbjU: Downloading webpage
[youtube] BpOJgRWTbjU: Downloading video info webpage
[youtube] BpOJgRWTbjU: Extracting video information
[youtube] BpOJgRWTbjU: Downloading MPD manifest
[debug] Invoking downloader on u'https://r2---sn-8pgbpohxqp5-aig6.googlevideo.com/videoplayback?id=o-AA4z_Snr9VMx1ugbUSPnm4uulbbSrpCkOE_vI9Z7I8yh&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&sver=3&initcwndbps=2733750&ip=82.21.208.93&dur=335.969&fexp=9410705%2C9412913%2C9416126%2C9418201%2C9419451%2C9420452%2C9421733%2C9422433%2C9422596%2C9423661%2C9423662%2C9425731%2C9426414%2C9426658%2C9426857%2C9427714%2C9428427%2C9429304&ms=au&mt=1456154326&mv=m&source=youtube&clen=11279889&mn=sn-8pgbpohxqp5-aig6&upn=xszq7cckxAk&mm=31&lmt=1455652891213374&signature=C2539F0F9B9C184D01707D43B80FF79969267396.9E77ACCB07C55FAA4B7975E89BC48A0E6DA87DFF&mime=video%2Fwebm&itag=243&key=yt6&ipbits=0&requiressl=yes&keepalive=yes&pl=22&pcm2cms=yes&gir=yes&expire=1456175997&ratebypass=yes'
[download] Destination: Frankie And Johnnie [youtube BpOJgRWTbjU].f243.webm
[download] 100% of 10.76MiB in 00:02
[debug] Invoking downloader on u'https://r2---sn-8pgbpohxqp5-aig6.googlevideo.com/videoplayback?id=o-AA4z_Snr9VMx1ugbUSPnm4uulbbSrpCkOE_vI9Z7I8yh&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&sver=3&initcwndbps=2733750&ip=82.21.208.93&dur=336.041&fexp=9410705%2C9412913%2C9416126%2C9418201%2C9419451%2C9420452%2C9421733%2C9422433%2C9422596%2C9423661%2C9423662%2C9425731%2C9426414%2C9426658%2C9426857%2C9427714%2C9428427%2C9429304&ms=au&mt=1456154326&mv=m&source=youtube&clen=6411102&mn=sn-8pgbpohxqp5-aig6&upn=xszq7cckxAk&mm=31&lmt=1455652701291333&signature=B2B781F08FB9C48CE61C773CD9AFDE1E1B88E275.8963F06F915669136B9FB72791995102534A4BB5&mime=audio%2Fwebm&itag=251&key=yt6&ipbits=0&requiressl=yes&keepalive=yes&pl=22&pcm2cms=yes&gir=yes&expire=1456175997&ratebypass=yes'
[download] Destination: Frankie And Johnnie [youtube BpOJgRWTbjU].f251.webm
[download] 100% of 6.11MiB in 00:01
[ffmpeg] Merging formats into "Frankie And Johnnie [youtube BpOJgRWTbjU].webm"
[debug] ffmpeg command line: avconv -y -i 'file:Frankie And Johnnie [youtube BpOJgRWTbjU].f243.webm' -i 'file:Frankie And Johnnie [youtube BpOJgRWTbjU].f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Frankie And Johnnie [youtube BpOJgRWTbjU].temp.webm'
Deleting original file Frankie And Johnnie [youtube BpOJgRWTbjU].f243.webm (pass -k to keep)
Deleting original file Frankie And Johnnie [youtube BpOJgRWTbjU].f251.webm (pass -k to keep)

**Comment by johnstumbles** [comment]
As a workaround -f mp4 produces a playable video.

**Comment by dstftw** [comment]
Produced file plays fine with mpv and latest vlc (2.2.2). Inability of your player to play particular formats is not a problem of youtube-dl.

**Comment by johnstumbles** [comment]
OK I guess the webm file uses features not available with my distro (trusty 14.04.4 LTS)
$ uname -a
Linux nova 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Thanks for the mention of mpv - I hadn't come across that. Although the default version on Trusty (0.3.4 (C) 2000-2013) is obviously not up to playing it, but I guess that's a Ubuntu issue :-(

Anyway thanks for your prompt reply, and your work on this invaluable tool.

$ mpv Frankie\ And\ Johnnie\ \[youtube\ BpOJgRWTbjU\].webm 
Creating config file: /home/john/.mpv/config
Playing: Frankie And Johnnie [youtube BpOJgRWTbjU].webm
Detected file format: Matroska
[stream] Video (+) --vid=1 (vp9)
[stream] Audio (+) --aid=1 --alang=eng (*) (opus)
Failed to open VDPAU backend libvdpau_r600.so: cannot open shared object file: No such file or directory
[vo/vdpau] Error when calling vdp_device_create_x11: 1
Failed to initialize a video decoder for codec 'vp9'.
Video: no video
Video: no video
Selected audio codec: libopus Opus [lavc:libopus]
AO: [pulse] 48000Hz stereo 2ch s16
A: 00:00:27 / 00:05:36 (8%)


Exiting... (Quit)
