### ISSUE TITLE
Facebook Mobile link download

### ISSUE THREAD

**Issue by Drizzlez** [rg3/youtube-dl#8638]
Downloading this kind of **Mobile **Facebook links do not work: 
[https://m.facebook.com/story.php?story_fbid=368678973302573&id=101604320010041
](url)
Normal Facebook links are downloading fine. please have a look.

Output:

My prompt>./youtube-dl --version
2016.02.22

My prompt>./youtube-dl https://m.facebook.com/story.php?story_fbid=1035862816472149&id=116132035111903
[1] 8731
My prompt>[generic] story: Requesting header
WARNING: Falling back on generic information extractor.
[generic] story: Downloading webpage
[generic] story: Extracting information
ERROR: Unsupported URL: https://m.facebook.com/story.php?story_fbid=1035862816472149

[1]+  Exit 1                  ./youtube-dl https://m.facebook.com/story.php?story_fbid=1035862816472149

**Comment by yan12125** [comment]
Thanks for the report. Such URLs will be supported in the next version. Note that you need to enclose URLs in single or double quotes. See [this FAQ entry](https://github.com/rg3/youtube-dl/#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for more information.
