### ISSUE TITLE
Adult Swim: Authenticated videos lack requires JSON

### ISSUE THREAD

**Issue by Zenexer** [rg3/youtube-dl#8640]
This seems to be a failure of a test case that has been marked as "skipped" due to the authentication requirement.  The error indicates that youtube-dl should still work with authentication.

Trying to run:

``` bash
youtube-dl http://www.adultswim.com/videos/rick-and-morty/pilot/ --cookies cookies -F --user-agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36' --verbose --print-traffic
```

Here's the relevant JSON from the page.  Note that I'm logged in with my cable provider and actively streaming. I've tried refreshing the page; I don't get the authentication prompt again.  youtube-dl expects either a `stream` or `clips` property, neither of which are present.

``` json
{
    "ott_expiration_date": "",
    "episode_number": "1",
    "blurb": "",
    "ott_launch_date": 1443039240,
    "type": "episode",
    "season_number": "1",
    "duration": 1325,
    "title": "Pilot",
    "cma_id": "1166637",
    "launch_date": 1455080400,
    "tv_rating": "tv-14-dlsv",
    "vma_id": "8a250ba14280caae01428fe0b3d80091",
    "views": 2061102,
    "description": "Rick moves in with his daughter's family and establishes himself as a bad influence on his grandson, Morty. ",
    "expiration_date": 1458100799,
    "images": [
        {
            "height": "300",
            "name": "legacy",
            "width": "400",
            "url": "http://i.cdn.turner.com/asfix/repository//8a250ba13f865824013fc9db8b6b0400/thumbnail_8234390180613999969.jpg"
        },
        {
            "height": "608",
            "name": "main",
            "width": "1080",
            "url": "http://i.cdn.turner.com/adultswim/big/video/episode-thumbs-16x9/rickandmorty_cc_001_pt2_v83js-02.jpg"
        }
    ],
    "slug": "pilot",
    "auth": true,
    "id": "rQxZvXQ4ROaSOqq-or2Mow",
    "version": 848339,
    "identifier": "EP 1",
    "contentType": "TVE",
    "videoPlaybackID": "1166637",
    "collectionSlug": "rick-and-morty",
    "linkURL": "/videos/rick-and-morty/pilot/",
    "fbCommentMetadata": {
        "associatedURL": "http://video.adultswim.com/rick-and-morty/pilot.html"
    }
}
```

Here's the output:

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.adultswim.com/videos/rick-and-morty/pilot/', u'--cookies', u'cookies', u'-F', u'--user-agent', u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36', u'--verbose', u'--print-traffic']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.10 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0, ffprobe 3.0, rtmpdump 2.4
[debug] Proxy map: {}
[AdultSwim] pilot: Downloading webpage
send: u'GET /videos/rick-and-morty/pilot/ HTTP/1.1\r\nHost: www.adultswim.com\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nConnection: close\r\nCookie: aduprevpage_pn=adu%3Av%3A%2Fvideos%2Frick-and-morty%2Fpilot%2F; CG=nil:[redacted]:[redacted]; mvpd_name=Verizon_HBA; s_ppv=30; s_cc=true; s_sq=%5B%5BB%5D%5D; aslegalnotification=true; s_fid=[redacted]-[redacted]\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Tue, 23 Feb 2016 01:40:24 GMT
header: Content-Type: text/html
header: Transfer-Encoding: chunked
header: Connection: close
header: Vary: Accept-Encoding
header: Set-Cookie: CG=nil:[redacted]:[redacted]; path=/
header: X-Cache-Status: HIT
header: Content-Encoding: gzip
ERROR: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adultswim.py", line 148, in _real_extract
    expected=True)
ExtractorError: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.
```

Here's the contents of `cookies`:

```
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file!  Do not edit.

.adultswim.com  TRUE    /   FALSE   1519349099  CG  nil:[redacted]:[redacted]
.adultswim.com  TRUE    /   FALSE   1519349099  aduprevpage_pn  adu%3Av%3A%2Fvideos%2Frick-and-morty%2Fpilot%2F
.adultswim.com  TRUE    /   FALSE   1519349099  aslegalnotification true
.adultswim.com  TRUE    /   FALSE   1519349099  mvpd_name   Verizon_HBA
.adultswim.com  TRUE    /   FALSE   1519349099  s_cc    true
.adultswim.com  TRUE    /   FALSE   1519349099  s_fid  [redacted]-[redacted]
.adultswim.com  TRUE    /   FALSE   1519349099  s_ppv   30
.adultswim.com  TRUE    /   FALSE   1519349099  s_sq    %5B%5BB%5D%5D
```

Note that I've edited the cookie file a bit because the generator I was using wasn't working all that well, but you can see above that all the cookies are being sent.

**Comment by dstftw** [comment]
This was just an assumption it may work with authenticated cookies. No one of the core developers has cable provider account. So you have to provide account credentials/valid cookies to one of the core developers to get this fixed (if it's possible at all).

**Comment by Zenexer** [comment]
Will-do.  Let me know where I should send the info.  Alternatively, I may have time to add support myself, but not this week.

**Comment by Pikanet128** [comment]
ok i did a little messing around with capturing the streams from my iphone while useing the app
this is the m3u8 file we need

http://apple-secure.cdn.turner.com/adultswim/big/secure/tve/2016-02/ASOE1002221600064421_HLS/ASOE1002221600064421_iphone_vod.m3u8?hdnea=expires%3D1457223852%7Eaccess%3D%2Fadultswim%2Fbig%2Fsecure%2Ftve%2F2016-02%2FASOE1002221600064421_HLS%2F*%7Emd5%3Dcb365b965ec2800fdc58c49502865d6f
this is dimension w ep 1 by the way

cmd output

>youtube-dl http://apple-secure.cdn.turner.com/adultswim/big/secure/tve/2016-02/
ASOE1002221600064421_HLS/ASOE1002221600064421_iphone_vod.m3u8?hdnea=expires%3D14
57224644%7Eaccess%3D%2Fadultswim%2Fbig%2Fsecure%2Ftve%2F2016-02%2FASOE1002221600
064421_HLS%2F*%7Emd5%3Dfdd9ffe6cf1005f3110a78d531f0cd89 --verbos
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://apple-secure.cdn.turner.com/adultswim/big/s
ecure/tve/2016-02/ASOE1002221600064421_HLS/ASOE1002221600064421_iphone_vod.m3u8?
hdnea=expires%3D1457224644%7Eaccess%3D%2Fadultswim%2Fbig%2Fsecure%2Ftve%2F2016-0
2%2FASOE1002221600064421_HLS%2F*%7Emd5%3Dfdd9ffe6cf1005f3110a78d531f0cd89', u'--
verbos']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-65916-g9e8ab36, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://127.0.0.1:8888', 'https': 'https://127.0.0.1
:8888'}
[generic] ASOE1002221600064421_iphone_vod: Requesting header
[generic] ASOE1002221600064421_iphone_vod: Downloading m3u8 information
[debug] Invoking downloader on u'http://apple-secure.cdn.turner.com/adultswim/bi
g/secure/tve/2016-02/ASOE1002221600064421_HLS/ASOE1002221600064421_Layer6_vod.m3
u8'
[download] Destination: ASOE1002221600064421_iphone_vod-ASOE1002221600064421_iph
one_vod.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Language: en-us,en;q=0.5

Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0
 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: hdnea2=expires=1457310802~access=/adultswim/big/secure/tve/2016-02/ASOE1
002221600064421_HLS/*~md5=c830ff04682be14b1f18c894eac669a3
' -i http://apple-secure.cdn.turner.com/adultswim/big/secure/tve/2016-02/ASOE100
2221600064421_HLS/ASOE1002221600064421_Layer6_vod.m3u8 -c copy -f mp4 -bsf:a aac
_adtstoasc file:ASOE1002221600064421_iphone_vod-ASOE1002221600064421_iphone_vod.
mp4.part
ffmpeg version N-65916-g9e8ab36 Copyright (c) 2000-2014 the FFmpeg developers
  built on Aug 26 2014 22:02:10 with gcc 4.8.3 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-lib
modplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrw
b --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinge
r --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --en
able-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis
 --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-
libx265 --enable-libxavs --enable-libxvid --enable-decklink --enable-zlib
  libavutil      54.  7.100 / 54.  7.100
  libavcodec     56.  0.101 / 56.  0.101
  libavformat    56.  3.100 / 56.  3.100
  libavdevice    56.  0.100 / 56.  0.100
  libavfilter     5.  0.103 /  5.  0.103
  libswscale      3.  0.100 /  3.  0.100
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  0.100 / 53.  0.100
[http @ 028ef480] HTTP error 403 Forbidden
http://apple-secure.cdn.turner.com/adultswim/big/secure/tve/2016-02/ASOE10022216
00064421_HLS/ASOE1002221600064421_Layer6_vod.m3u8: Input/output error


ERROR: ffmpeg exited with code 1
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 411, in main
  File "youtube_dl\__init__.pyo", line 401, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1692, in download
  File "youtube_dl\YoutubeDL.pyo", line 677, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 722, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1362, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1624, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1566, in dl
  File "youtube_dl\downloader\common.pyo", line 343, in download
  File "youtube_dl\downloader\hls.pyo", line 79, in real_download
  File "youtube_dl\downloader\common.pyo", line 156, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 541, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 503, in trouble


>youtube-dl http://apple-secure.cdn.turner.com/adultswim/big/secure/tve/2016-02/
ASOE1002221600064421_HLS/ASOE1002221600064421_Layer6_vod.m3u8?hdnea=expires%3D14
57224644%7Eaccess%3D%2Fadultswim%2Fbig%2Fsecure%2Ftve%2F2016-02%2FASOE1002221600
064421_HLS%2F*%7Emd5%3Dfdd9ffe6cf1005f3110a78d531f0cd89 --verbos
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://apple-secure.cdn.turner.com/adultswim/big/s
ecure/tve/2016-02/ASOE1002221600064421_HLS/ASOE1002221600064421_Layer6_vod.m3u8?
hdnea=expires%3D1457224644%7Eaccess%3D%2Fadultswim%2Fbig%2Fsecure%2Ftve%2F2016-0
2%2FASOE1002221600064421_HLS%2F*%7Emd5%3Dfdd9ffe6cf1005f3110a78d531f0cd89', u'--
verbos']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-65916-g9e8ab36, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://127.0.0.1:8888', 'https': 'https://127.0.0.1
:8888'}
[generic] ASOE1002221600064421_Layer6_vod: Requesting header
[generic] ASOE1002221600064421_Layer6_vod: Downloading m3u8 information
[debug] Invoking downloader on u'http://apple-secure.cdn.turner.com/adultswim/bi
g/secure/tve/2016-02/ASOE1002221600064421_HLS/ASOE1002221600064421_Layer6_vod.m3
u8?hdnea=expires%3D1457224644%7Eaccess%3D%2Fadultswim%2Fbig%2Fsecure%2Ftve%2F201
6-02%2FASOE1002221600064421_HLS%2F*%7Emd5%3Dfdd9ffe6cf1005f3110a78d531f0cd89'
[download] Destination: ASOE1002221600064421_Layer6_vod-ASOE1002221600064421_Lay
er6_vod.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Language: en-us,en;q=0.5

Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0
 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: hdnea2=expires=1457310818~access=/adultswim/big/secure/tve/2016-02/ASOE1
002221600064421_HLS/*~md5=ac9c4a1ca709d4cb77d78b112a63a666
' -i 'http://apple-secure.cdn.turner.com/adultswim/big/secure/tve/2016-02/ASOE10
02221600064421_HLS/ASOE1002221600064421_Layer6_vod.m3u8?hdnea=expires%3D14572246
44%7Eaccess%3D%2Fadultswim%2Fbig%2Fsecure%2Ftve%2F2016-02%2FASOE1002221600064421
_HLS%2F*%7Emd5%3Dfdd9ffe6cf1005f3110a78d531f0cd89' -c copy -f mp4 -bsf:a aac_adt
stoasc file:ASOE1002221600064421_Layer6_vod-ASOE1002221600064421_Layer6_vod.mp4.
part
ffmpeg version N-65916-g9e8ab36 Copyright (c) 2000-2014 the FFmpeg developers
  built on Aug 26 2014 22:02:10 with gcc 4.8.3 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
le-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-lib
modplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrw
b --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinge
r --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --en
able-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis
 --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-
libx265 --enable-libxavs --enable-libxvid --enable-decklink --enable-zlib
  libavutil      54.  7.100 / 54.  7.100
  libavcodec     56.  0.101 / 56.  0.101
  libavformat    56.  3.100 / 56.  3.100
  libavdevice    56.  0.100 / 56.  0.100
  libavfilter     5.  0.103 /  5.  0.103
  libswscale      3.  0.100 /  3.  0.100
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  0.100 / 53.  0.100
[http @ 0294eec0] HTTP error 403 Forbidden
Unable to open key file http://apple-secure.cdn.turner.com/adultswim/big/secure/
tve/2016-02/ASOE1002221600064421_HLS/keybeb3a7ab1c6c4d209491b2e02750c703-0.key
[http @ 0294ed00] HTTP error 403 Forbidden
[crypto @ 0294ec00] Unable to open input
[hls,applehttp @ 0294f880] Failed to open segment of playlist 0
[hls,applehttp @ 0294f880] Error when loading first segment 'http://apple-secure
.cdn.turner.com/adultswim/big/secure/tve/2016-02/ASOE1002221600064421_HLS/ASOE10
02221600064421_Layer6/13812_Period1/segment0.ts'
http://apple-secure.cdn.turner.com/adultswim/big/secure/tve/2016-02/ASOE10022216
00064421_HLS/ASOE1002221600064421_Layer6_vod.m3u8?hdnea=expires%3D1457224644%7Ea
ccess%3D%2Fadultswim%2Fbig%2Fsecure%2Ftve%2F2016-02%2FASOE1002221600064421_HLS%2
F*%7Emd5%3Dfdd9ffe6cf1005f3110a78d531f0cd89: Input/output error


ERROR: ffmpeg exited with code 1
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 411, in main
  File "youtube_dl\__init__.pyo", line 401, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1692, in download
  File "youtube_dl\YoutubeDL.pyo", line 677, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 722, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1362, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1624, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1566, in dl
  File "youtube_dl\downloader\common.pyo", line 343, in download
  File "youtube_dl\downloader\hls.pyo", line 79, in real_download
  File "youtube_dl\downloader\common.pyo", line 156, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 541, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 503, in trouble


>youtube-dl http://apple-secure.cdn.turner.com/adultswim/big/secure/tve/2016-02/
ASOE1002221600064421_HLS/ASOE1002221600064421_Layer6/13812_Period1/segment0.ts?h
dnea=expires%3D1457224644%7Eaccess%3D%2Fadultswim%2Fbig%2Fsecure%2Ftve%2F2016-02
%2FASOE1002221600064421_HLS%2F*%7Emd5%3Dfdd9ffe6cf1005f3110a78d531f0cd89 --verbo
s
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://apple-secure.cdn.turner.com/adultswim/big/s
ecure/tve/2016-02/ASOE1002221600064421_HLS/ASOE1002221600064421_Layer6/13812_Per
iod1/segment0.ts?hdnea=expires%3D1457224644%7Eaccess%3D%2Fadultswim%2Fbig%2Fsecu
re%2Ftve%2F2016-02%2FASOE1002221600064421_HLS%2F*%7Emd5%3Dfdd9ffe6cf1005f3110a78
d531f0cd89', u'--verbos']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-65916-g9e8ab36, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://127.0.0.1:8888', 'https': 'https://127.0.0.1
:8888'}
[generic] segment0: Requesting header
[debug] Invoking downloader on u'http://apple-secure.cdn.turner.com/adultswim/bi
g/secure/tve/2016-02/ASOE1002221600064421_HLS/ASOE1002221600064421_Layer6/13812_
Period1/segment0.ts?hdnea=expires%3D1457224644%7Eaccess%3D%2Fadultswim%2Fbig%2Fs
ecure%2Ftve%2F2016-02%2FASOE1002221600064421_HLS%2F*%7Emd5%3Dfdd9ffe6cf1005f3110
a78d531f0cd89'
[download] Destination: segment0-segment0.ts
[download] 100% of 2.18MiB in 01:06

>youtube-dl http://apple-secure.cdn.turner.com/adultswim/big/secure/tve/2016-02/
ASOE1002221600064421_HLS/keybeb3a7ab1c6c4d209491b2e02750c703-0.key?hdnea=expires
%3D1457224644%7Eaccess%3D%2Fadultswim%2Fbig%2Fsecure%2Ftve%2F2016-02%2FASOE10022
21600064421_HLS%2F*%7Emd5%3Dfdd9ffe6cf1005f3110a78d531f0cd89 --verbos
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://apple-secure.cdn.turner.com/adultswim/big/s
ecure/tve/2016-02/ASOE1002221600064421_HLS/keybeb3a7ab1c6c4d209491b2e02750c703-0
.key?hdnea=expires%3D1457224644%7Eaccess%3D%2Fadultswim%2Fbig%2Fsecure%2Ftve%2F2
016-02%2FASOE1002221600064421_HLS%2F*%7Emd5%3Dfdd9ffe6cf1005f3110a78d531f0cd89',
 u'--verbos']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-65916-g9e8ab36, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://127.0.0.1:8888', 'https': 'https://127.0.0.1
:8888'}
[generic] keybeb3a7ab1c6c4d209491b2e02750c703-0: Requesting header
WARNING: Falling back on generic information extractor.
[generic] keybeb3a7ab1c6c4d209491b2e02750c703-0: Downloading webpage
WARNING: URL could be a direct video link, returning it as such.
[debug] Invoking downloader on u'http://apple-secure.cdn.turner.com/adultswim/bi
g/secure/tve/2016-02/ASOE1002221600064421_HLS/keybeb3a7ab1c6c4d209491b2e02750c70
3-0.key?hdnea=expires%3D1457224644%7Eaccess%3D%2Fadultswim%2Fbig%2Fsecure%2Ftve%
2F2016-02%2FASOE1002221600064421_HLS%2F*%7Emd5%3Dfdd9ffe6cf1005f3110a78d531f0cd8
9'
[download] Destination: keybeb3a7ab1c6c4d209491b2e02750c703-0-keybeb3a7ab1c6c4d2
09491b2e02750c703-0.key
[download] 100% of 16.00B in 00:00

end cmd

so it looks like it needs the auth string appended to each file in the m3u8 to work

here are the m3u8 files and the ts and key from the above cmd session
[files.zip](https://github.com/rg3/youtube-dl/files/160110/files.zip)
