### ISSUE TITLE
fail to download youtube mix

### ISSUE THREAD

**Issue by sovos** [rg3/youtube-dl#8645]
hello, my youtube-dl is up to date

`youtube-dl is up-to-date (2016.02.22)`

but when I try to download a youtube mix the process stops after the first song

> youtube-dl --extract-audio --audio-format mp3 --autonumber-size 2 --max-downloads 99 -o "%(autonumber)s-%(title)s.%(ext)s" https://www.youtube.com/watch?v=OMOGaugKpzs&list=RDOMOGaugKpzs
> [2] 8293
> $ [youtube] OMOGaugKpzs: Downloading webpage
> [youtube] OMOGaugKpzs: Downloading video info webpage
> [youtube] OMOGaugKpzs: Extracting video information
> [download] Destination: 01-The Police - Every Breath You Take.webm
> [download] 100% of 3.61MiB in 00:03
> [ffmpeg] Destination: 01-The Police - Every Breath You Take.mp3
> Deleting original file 01-The Police - Every Breath You Take.webm (pass -k to keep)

and then it freezes

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
