### ISSUE TITLE
[SiteSupport Request] nonktube.com

### ISSUE THREAD

**Issue by klikevil-al** [rg3/youtube-dl#8647]
WARNING: NSFW

Would like to see a couple of sites have support added actually

nonktube.com 
hardsextube.com

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by klikevil-al** [comment]
www.nonktube.com/video/2516/time-stop-in-japanese-classroom

Bash rendition of an example download for nonk tube
`nonktube () 
{ 
    declare NONK='146.71.97.42';
    if [[ $# -lt 1 ]] || [[ $1 =~ /.?-h/ ]]; then
        echo "usage: ${FUNCNAME[0]} <url>";
    else
        toparse=$@;
        if [[ $1 =~ "-a" ]]; then
            declare name=$(echo ${toparse} | cut -d/ -f6);
            echo ${toparse} | grep --colour=auto -Poi 'video[/](.*?)[/]' | awk -F\/ '{print "axel -n 8 -a -o '$name'.flv http://146.71.97.42:9999/flv/"$2".flv"}';
        else
            echo ${toparse} | grep --colour=auto -Poi 'video[/](.*?)[/]' | awk -F\/ '{print "wget http://146.71.97.42:9999/flv/"$2".flv"}';
        fi;
    fi
}
`

**Comment by klikevil-al** [comment]
bump >.>
