### ISSUE TITLE
 m3u8 download detected but ffmpeg or avconv could not be found. Please install one.

### ISSUE THREAD

**Issue by greencopper** [rg3/youtube-dl#8650]
If I list the available vidoes I get:

```
HLS-meta     mp4        multiple   Quality selection URL
HDS-561      flv        unknown     561k
HLS-561      mp4        640x360     561k , avc1.66.30,  mp4a.40.2
HDS-1124     flv        unknown    1124k
HLS-1124     mp4        854x480    1124k , avc1.640029,  mp4a.40.2
HDS-2197     flv        unknown    2197k 
HLS-2197     mp4        854x480    2197k , avc1.640029,  mp4a.40.2 (best)
```

Then no matter which I try to fetch I get:

```
ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please install one.
```

The downloading is being done on a non-media box for later streaming locally, hence no ffmpeg, avconv or similar is installed.

Why is it not possible to simply download any longer without using ffmpeg or avconv? It is not an option on a box with a light CPU!

**Comment by greencopper** [comment]
Also the download in fragments part is a pain!

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.
