### ISSUE TITLE
Getting "ERROR:libpostproc", but resulting m4a seems to play fine.

### ISSUE THREAD

**Issue by sunk818** [rg3/youtube-dl#8663]
c:\>youtube-dl -f 140 https://www.youtube.com/watch?v=MxpLlNHAjRI
```
[youtube] MxpLlNHAjRI: Downloading webpage
[youtube] MxpLlNHAjRI: Downloading video info webpage
[youtube] MxpLlNHAjRI: Extracting video information
[youtube] MxpLlNHAjRI: Downloading MPD manifest
[download] Destination: Jurassic 5 - In The House (Nightmares on Wax Remix)-MxpLlNHAjRI.m4a
[download] 100% of 4.41MiB in 00:00
[ffmpeg] Correcting container in "Jurassic 5 - In The House (Nightmares on Wax Remix)-MxpLlNHAjRI.m4a"
ERROR:   libpostproc    54.  0.100 / 54.  0.100
```

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by sunk818** [comment]
Seems to be fine now. Maybe it was a YouTube glitch.

C:\>youtube-dl -v -f 140 https://www.youtube.com/watch?v=MxpLlNHAjRI
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'140', u'https://www.youtube.com/watch?v=MxpLlNHAjRI']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] MxpLlNHAjRI: Downloading webpage
[youtube] MxpLlNHAjRI: Downloading video info webpage
[youtube] MxpLlNHAjRI: Extracting video information
[youtube] MxpLlNHAjRI: Downloading MPD manifest
[debug] Invoking downloader on u'https://r16---sn-a5m7lnek.googlevideo.com/videoplayback?id=331a4b94d1c08d12&itag=140&source=youtube&requiressl=yes&mv=m&pl=16&ms=au&mn=sn-a5m7lnek&mm=31&gcr=us&nh=IgpwcjAxLmxheDAyKgkxMjcuMC4wLjE&ratebypass=yes&mime=au
dio/mp4&gir=yes&clen=4621794&lmt=1402035907270002&dur=287.834&mt=1456430986&signature=0B5E43D92FBFBCCF8A0321231E0A842589EDA512.31BA79CED5EFD535DB618EE9B7E8E33B477F997F&sver=3&fexp=9413278,9416126,9416903,9420452,9421339,9421501,9422596,9423341,942366
1,9423662,9426047,9426657,9427110,9428650,9429232,9429610&upn=7YC4DmzyxFo&key=dg_yt0&ip=153.10.242.1&ipbits=0&expire=1456452705&sparams=ip,ipbits,expire,id,itag,source,requiressl,mv,pl,ms,mn,mm,gcr,nh,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Jurassic 5 - In The House (Nightmares on Wax Remix)-MxpLlNHAjRI.m4a
[download] 100% of 4.41MiB in 00:00
[ffmpeg] Correcting container in "Jurassic 5 - In The House (Nightmares on Wax Remix)-MxpLlNHAjRI.m4a"
[debug] ffmpeg command line: ffmpeg -y -i 'file:Jurassic 5 - In The House (Nightmares on Wax Remix)-MxpLlNHAjRI.m4a' -c copy -f mp4 'file:Jurassic 5 - In The House (Nightmares on Wax Remix)-MxpLlNHAjRI.temp.m4a'
