### ISSUE TITLE
Would like to add extended attributes to saved file

### ISSUE THREAD

**Issue by sgargbugreporter** [rg3/youtube-dl#8668]
Hi,

I want to add extended attributes (for example discussed in https://www.freedesktop.org/wiki/CommonExtendedAttributes/) to the downloaded file. I see that there is an option "xattr_set_filesize" available.

Can someone point me to where I can add extended attributes to the downloaded file. I am primarily looking to store the source URL and other metadata as extended attributes.

Thanks.

**Comment by sgargbugreporter** [comment]
There is an error in the extended attributes code in the youtube_dl/downloader/http.py file.

Patch attached.
[http.py.patch.txt](https://github.com/rg3/youtube-dl/files/147795/http.py.patch.txt)

**Comment by sgargbugreporter** [comment]
I have added extended attributes code in youtube_dl/YoutubeDL.py. Patch attached.

This is in the post_process() function. Any better place to put it?

Thanks.
[YoutubeDL.py.patch.txt](https://github.com/rg3/youtube-dl/files/147798/YoutubeDL.py.patch.txt)

**Comment by yan12125** [comment]
Sorry for the late response. Looks like the two patches point to different problems.

For ```http.py.patch.txt```: Could you create a pull request and describe what's the problem you have encountered before this patch? From your patch I guess you've got a similar problem as #5498 - you need to use python-pyxattr 0.5.0 or above for youtube-dl.

For ```YoutubeDL.py.patch.txt```: There are already some attributes defined in ```xattr_mapping``` of [```xattrpp.py```](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/postprocessor/xattrpp.py). Add more attributes there. These attributes are not written by default. Use ```--xattr``` to enable them.

**Comment by sgargbugreporter** [comment]
Regarding version ox xattr, I am using xattr. Details below:

Metadata-Version: 1.1
Name: xattr
Version: 0.7.9
Summary: Python wrapper for extended filesystem attributes
Home-page: http://github.com/xattr/xattr
Author: Bob Ippolito
Author-email: bob@redivi.com
License: MIT License

**Comment by yan12125** [comment]
Is there any error message? Please post the command with ```-v``` and all outputs.

**Comment by sgargbugreporter** [comment]
I have the patched version. I was using xattr and had to do the patching. Have just installed "python-pyxattr 0.5.5-2", and uninstalled xattr. It works with my patched version. We rebuild a fresh (non-patched) version and test again.

**Comment by yan12125** [comment]
I've rewritten some xattr related codes in youtube-dl. Some changes are quite similar to your proposed patches, so I bet all problems are solved. Feel free to leave comments if there are still issues.
