### ISSUE TITLE
on what criteria the progress hook function is called while downloading a video using youtube-dl

### ISSUE THREAD

**Issue by ramadivyasri** [rg3/youtube-dl#8669]
I'm trying to figure out how the hook file reports the status of an ongoing video download using youtube-dl. Can someone please help me understand on how the progress hook is generated or called while downloading a video using youtube-dl

**Comment by dstftw** [comment]
Progress can be delivered into hooks when new portion of data has been downloaded, the download has finished or an error has occured. Actual hook delivery and it's frequency depends on the downloader.
