### ISSUE TITLE
Pluralsight - HTTP Error 403: Forbidden (caused by HTTPError());

### ISSUE THREAD

**Issue by maestrofx** [rg3/youtube-dl#8670]
I've been digging some issues related to this problem.

case#1:
**youtube-dl** works well on my laptop (trusty machine). But, due to pluralsight banned account and has been discussed here #6090, I run the script remotely by adding param --sleep-interval 300, so it will finish without waiting to.

case#2:
I run youtube-dl through my vps (digitalOcean). But after trying with some droplets, it doesn't work as well as my laptop.

I am curious, is this problem caused by dependencies in the machines or something missing?

This error [1] is always same for some droplets.

[1] error

> [pluralsight:course] go-build-distributed-applications: Downloading course JSON
> ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 355, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1905, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/usr/local/lib/python2.7/urllib2.py", line 410, in open
>     response = meth(req, response)
>   File "/usr/local/lib/python2.7/urllib2.py", line 523, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/local/lib/python2.7/urllib2.py", line 448, in error
>     return self._call_chain(*args)
>   File "/usr/local/lib/python2.7/urllib2.py", line 382, in _call_chain
>     result = func(*args)
>   File "/usr/local/lib/python2.7/urllib2.py", line 531, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
>

**Comment by dstftw** [comment]
Can you watch it in browser via vps?

**Comment by maestrofx** [comment]
Hi, @dstftw,

The VPS is terminal-based, no GUI. I have no try to play it with command line.

But, the youtube-dl is working well for udemy or youtube source. Problem only for Pluralsight.

Thanks

**Comment by dstftw** [comment]
You can setup proxy/vpn/ssh tunnel/whatever to test from remote machine.
Persistent 403 is most likely a result of banned account/IP.

**Comment by maestrofx** [comment]
Yes, it works well via VPN too. I try to execute youtube-dl via terminal with my laptop with VPN to my remote machine.
But, I got the error as described above only when I execute youtube-dl via remote machine.

Anyone have the same problem with me?

**Comment by dstftw** [comment]
It does not matter whether it works in your browser via some random vpn. It does matter whether it works in your browser when your vps is running a vpn server (or any other kind of proxying software) and you're connected via it.

**Comment by maestrofx** [comment]
@dstftw, yes, I mean I run vpn server on that remote machine and connect my laptop through it, not random vpn.

**Comment by dstftw** [comment]
Can you watch it **in browser** when you are connected via vpn running on your vps?

**Comment by maestrofx** [comment]
Yes, no problem with it.

**Comment by dstftw** [comment]
When are via vpn which IP is shown here http://yt-dl.org/ip? Also add `-v --call-home` to youtube-dl command and post log.

**Comment by maestrofx** [comment]
do you mean I post my ip public here?

**Comment by maestrofx** [comment]
oh, wait, there is latest version 2016.03.1 and I am trying.

**Comment by dstftw** [comment]
If you are not willing to post IP check whether it matches with one from youtube-dl log and post log without the IP.

**Comment by maestrofx** [comment]
Hi again, @dstftw and all to experience this problem,
Sorry it's too long to update.

After playing with some vps hosted in Digital Ocean and another cloud provider I have, I can determine that the problem is an issue Digital Ocean blocked Pluralsight's access due to their administrative rules.


Thanks
