### ISSUE TITLE
Skip videos while downloading

### ISSUE THREAD

**Issue by gdeward** [rg3/youtube-dl#8673]
I'm trying to download a large playlist of a Pluralsight course and have been interrupted half way through.  How can I start the download at a certain entry (ie video 100 of 200)?

**Comment by gdeward** [comment]
Disregard.  It appears the tool is intelligent enough to skip videos which have already been downloaded.  Deleting the interrupted file and issuing the same download command allowed me to continue where I left off.

**Comment by remitamine** [comment]
```
--playlist-start NUMBER          Playlist video to start at (default is 1)
```
you can find all the options in https://github.com/rg3/youtube-dl#options.

**Comment by gdeward** [comment]
Outstanding!  So glad you took the time to reply.  Thanks, @remitamine !  :)
