### ISSUE TITLE
Perhaps I'm Paranoid - Mint Hacked + /boot/initrd.img

### ISSUE THREAD

**Issue by rfengineer** [rg3/youtube-dl#8674]
Perhaps I'm just a wee bit paranoid, but given the recent mint hack, and given that I use mint 
almost exclusively, I'm paying closer attention to things. 

Today, I downloaded youtube-dl from the normal repository, and it stuck me oddly that a 
program designed to download videos would need to make changes to the way the 
machine boots.

Is this normal?  It may be mundane, but frankly I don't know.

----- snip -----
After this operation, 1,106 kB of additional disk space will be used.
Setting up base-files (7.2ubuntu5.4) ...

Configuration file '/etc/lsb-release'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** lsb-release (Y/I/N/O/D/Z) [default=N] ? y
Installing new version of config file /etc/lsb-release ...
Installing new version of config file /etc/os-release ...
Processing triggers for mintsystem (7.9.7+1) ...
Processing triggers for plymouth-theme-ubuntu-text (0.8.8-0ubuntu17.1) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for initramfs-tools (0.103ubuntu4.2) ...

update-initramfs: Generating /boot/initrd.img-3.13.0-37-generic        <<<----------------Note Here 

Selecting previously unselected package youtube-dl.
(Reading database ... 231191 files and directories currently installed.)
Preparing to unpack .../youtube-dl_2014.02.17-1_all.deb ...
Unpacking youtube-dl (2014.02.17-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up youtube-dl (2014.02.17-1) ...

----- snip -----

**Comment by dstftw** [comment]
What was the command?

**Comment by phihag** [comment]
A previous installation was interrupted, so `apt-get` is resuming it. Note `Processing triggers for mintsystem (7.9.7+1) ...`, which is one of the packages getting interrupted. Therefore, this is a normal artifact of package installation, and completely unrelated to youtube-dl.

Note that the youtube-dl version is heavily outdated though - for instance, you won't be able to download music videos on YouTube. See [our FAQ](https://yt-dl.org/update) for ways to update.
