### ISSUE TITLE
Error on select best quality for imdb

### ISSUE THREAD

**Issue by Arnaud69** [rg3/youtube-dl#8677]
Hello,
today i've an error on automatic choice for best quality :

youtube-dl -F http://www.imdb.com/video/imdb/vi1692448025
[imdb] 1692448025: Downloading webpage
[imdb] 1692448025: Downloading player page
[imdb] 1692448025: Downloading info for SD format
[imdb] 1692448025: Downloading info for 1080p HD format
[info] Available formats for 1692448025:
format code  extension  resolution note
auto         m3u8       unknown
1080p        mp4        unknown
SD           mp4        unknown    (best)

Version :
/youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.3 - Linux-2.6.38.2-grsec-xxxx-grs-ipv6-64-x86_64-with-debian-7.9
[debug] exe versions: ffmpeg N-48916-g856452c-static, ffprobe N-48916-g856452c-static, rtmpdump 2.4
[debug] Proxy map: {}

Best quality should be 1080p, it downloaded SD.

Many thx
Arnaud

**Comment by dstftw** [comment]
This issue has been fixed and fix will be incorporated in the next version of youtube-dl.

**Comment by Arnaud69** [comment]
Closed in 5 minutes ! You're the best !
Thank you
