### ISSUE TITLE
youtube-dl use with php

### ISSUE THREAD

**Issue by trname** [rg3/youtube-dl#8679]
hello
i want use youtube-dl with php but i cant do
im use this codes

         $url = 'https://www.youtube.com/watch?v=UyI4v5sxT54';
		$template = '/var/www/html/ytdl/' .
					'videos/%(id)s.%(ext)s';
		$string = ('youtube-dl --output=' . escapeshellarg($template) . ' ' . escapeshellarg($url));

		$descriptorspec = array(
		   0 => array("pipe", "r"),  // stdin
		   1 => array("pipe", "w"),  // stdout
		   2 => array("pipe", "w"),  // stderr
		);
		$process = proc_open($string, $descriptorspec, $pipes);
		$stdout = stream_get_contents($pipes[1]);
		fclose($pipes[1]);
		$stderr = stream_get_contents($pipes[2]);
		fclose($pipes[2]);
		$ret = proc_close($process);
		echo json_encode(array('status' => $ret, 'errors' => $stderr,
							   'url_orginal'=>$url, 'output' => $stdout,
							   'command' => $string));
but this codes returns [http://prntscr.com/a8l77k](http://prntscr.com/a8l77k) 
please help me, sorry for my bad english

**Comment by dstftw** [comment]
Have you installed youtube-dl at all? What's the output of `which youtube-dl`?

**Comment by trname** [comment]
i installed youtube-dl, already i download videos with youtube-dl on shell but i want to use this with php
Output: [http://prntscr.com/a8la5v](http://prntscr.com/a8la5v)

**Comment by dstftw** [comment]
Specify full path to youtube-dl in script.

**Comment by trname** [comment]
like this
`/usr/local/bin/youtube-dl --output='/var/www/html/ytdl/videos/%(id)s.%(ext)s' 'https://www.youtube.com/watch?v=UyI4v5sxT54'`

**Comment by trname** [comment]
dstftw thank you very much!, you are hero :+1:
