### ISSUE TITLE
Can’t Change Download Location

### ISSUE THREAD

**Issue by RedSoxFan04** [rg3/youtube-dl#8681]
I made sure to follow the instructions, but youtube-dl isn’t downloading videos to the location I specified. It creates a whole new directory in my user folder and puts the downloaded videos there. This is the command I used: ` -o “/user/Jfblagden/Movies/youtube-dl/%(title)s-%.%(ext)s”` The other problem is that it puts “-%(ext)s” at the end of the video’s name instead of the file extension, which in this case should be “.mp4”. Is this a bug, or is my syntax wrong?

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by RedSoxFan04** [comment]
Here’s the output: ‘''[youtube] N4_3ci9jvis: Downloading webpage
[youtube] N4_3ci9jvis: Downloading video info webpage
[youtube] N4_3ci9jvis: Extracting video information
[youtube] N4_3ci9jvis: Downloading MPD manifest
[download] Destination: “/user/Jfblagden/Movies/youtube-dl/Bring Back MST3K, Part 4 - Joel Shares A Few More Details-%(ext)s”
[download]  21.0% of 18.73MiB at 355.73KiB/s ETA 00:42’''

**Comment by dstftw** [comment]
Read my post **closely**.

**Comment by RedSoxFan04** [comment]
‘''[debug] System config: []
[debug] User config: [u'-o', u'\u201c/user/Jfblagden/Movies/youtube-dl/%(title)s-%.%(ext)s\u201d']
[debug] Command-line args: [u'-v', u'[youtube]', u'N4_3ci9jvis:', u'Downloading', u'webpage']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.8 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: u'[youtube]' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:[youtube]" ) to search YouTube
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1204, in _real_extract
    % (url, url), expected=True)
ExtractorError: u'[youtube]' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:[youtube]" ) to search YouTube

Joshs-MacBook-Pro:~ jfblagden$ [youtube] N4_3ci9jvis: Downloading video info webpage
-bash: [youtube]: command not found
Joshs-MacBook-Pro:~ jfblagden$ [youtube] N4_3ci9jvis: Extracting video information
-bash: [youtube]: command not found
Joshs-MacBook-Pro:~ jfblagden$ [youtube] N4_3ci9jvis: Downloading MPD manifest
-bash: [youtube]: command not found
Joshs-MacBook-Pro:~ jfblagden$ [download] Destination: “/user/Jfblagden/Movies/youtube-dl/Bring Back MST3K, Part 4 - Joel Shares A Few More Details-%(ext)s”
-bash: syntax error near unexpected token `('
Joshs-MacBook-Pro:~ jfblagden$ [download]  21.0% of 18.73MiB at 355.73KiB/s ETA 00:42
-bash: [download]: command not found’''

**Comment by dstftw** [comment]
1. You must use proper quotes: preferably single `'` or maybe double `"` but not `“` or `”`.
2. What is the purpose of the second `%` in `%(title)s-%.%(ext)s`? Either remove it or replace with `%%` if you want output percent literal.

**Comment by RedSoxFan04** [comment]
I copied that section directly from the instructions. I just took out the id and what I thought were its delimiters.

**Comment by RedSoxFan04** [comment]
I took out the second ‘%’, but I still get a similar result; the video is put in the same folder, though it finally shows the right extension.

**Comment by dstftw** [comment]
Post the full output with latest command.

**Comment by RedSoxFan04** [comment]
```
[debug] System config: []
[debug] User config: [u'-o', u'\u201c/user/jfblagden/Movies/youtube-dl/%(title)s-.%(ext)s\u201d’]
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=HN3uXrgNpvw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.8 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] HN3uXrgNpvw: Downloading webpage
[youtube] HN3uXrgNpvw: Downloading video information webpage
[youtube] HN3uXrgNpvw: Extracting video information
[youtube] HN3uXrgNpvw: Downloading MPD manifest
[debug] Invoking downloader on u'https://r7---sn-mv-ab5z.googlevideo.com/videoplayback?sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&requiressl=yes&lmt=1450850208486653&initcwndbps=607500&key=yt6&fexp=9416126%2C9420452%2C9422526%2C9422596%2C9423661%2C9423662%2C9423845%2C9424129%2C9424879%2C9426471%2C9426722%2C9427363%2C9427391%2C9427773%2C9427799%2C9427958%2C9429231&sver=3&signature=DDCDDFB4024EC3BECE3B3AFD5D46BBE1304ABFDD.719E83C66105F01FEC1C1F478D4E61C6C78D3854&ipbits=0&expire=1456613741&upn=zl44rEqqgt0&itag=22&mime=video%2Fmp4&dur=41.099&ms=au&id=o-AFQyYSgY3jJC4zjcYEU3bnF79PkMh4GDK0MoVkPdiv5a&pl=19&mv=m&mt=1456592052&ratebypass=yes&ip=70.215.6.126&mn=sn-mv-ab5z&mm=31&source=youtube’
[download] Destination: “/user/jfblagden/Movies/youtube-dl/MST3K - The Beatniks - DVD Menu-.mp4”
[download] 100% of 6.03MiB in 00:10
```

**Comment by dstftw** [comment]
Do you read my posts at all?
>1. You must use **proper quotes**: preferably **single `'`** or maybe double `"` but not `“` or `”`.

**Comment by RedSoxFan04** [comment]
I changed the triple quotes to single quotes. Is that better?
