### ISSUE TITLE
Can’t Download Videos to Existing Folder

### ISSUE THREAD

**Issue by RedSoxFan04** [rg3/youtube-dl#8683]
When I specify a path in my configuration file, youtube-dl doesn’t put downloaded videos in the path I specified. Rather, it _creates its own path in my user folder_, which isn’t what I want. I’m trying to have the videos downloaded to my “youtube-dl” folder, which is in my “Movies” folder. How do I make youtube-dl put downloaded videos in my “youtube-dl” folder?

**Comment by dstftw** [comment]
I've already [answered to this question](https://github.com/rg3/youtube-dl/issues/8681).

**Comment by RedSoxFan04** [comment]
Not really. All you did was criticize my use of quotes.

**Comment by dstftw** [comment]
Because it does not work due to **your wrong quotes**.

**Comment by RedSoxFan04** [comment]
What didn’t work?

**Comment by dstftw** [comment]
It does not recognize path template properly due to inconsistent quotes.

**Comment by RedSoxFan04** [comment]
You’re talking about my configuration file. I thought you were talking about my use of quotes on GitHub.

**Comment by RedSoxFan04** [comment]
When I change the double quotes in my configuration file, I get this `[debug] System config: []
[debug] User config: [u'\u2014o', u'\u2018\u2019\u2019/User/jfblagden/Movies/youtube-dl/%(title)s-.%(ext)s\u2019\u2019\u2019']
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=ECcFGszb-Mo']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.8 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: u'\u2014o' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:—o" ) to search YouTube
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1204, in _real_extract
    % (url, url), expected=True)
ExtractorError: u'\u2014o' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:\u2014o" ) to search YouTube`

The same thing happens when I use triple quotes.

**Comment by dstftw** [comment]
Post the command you are running.

**Comment by RedSoxFan04** [comment]
Here’s the command I’m running: `youtube-dl -v https://www.youtube.com/watch?v=Mi_nLFDPMuw`

And here’s what I currently have in my configuration file: `-- “/User/jfblagden/Movies/youtube-dl/%(title)s-.%(ext)s”
`

**Comment by dstftw** [comment]
Correct configuration file (just **copy-paste** to yours):
```
-o '/User/jfblagden/Movies/youtube-dl/%(title)s.%(ext)s'
```

**Comment by RedSoxFan04** [comment]
Here’s what I got when I used that: `Joshs-MacBook-Pro:~ jfblagden$ youtube-dl -v https://www.youtube.com/watch?v=Mi_nLFDPMuw
[debug] System config: []
[debug] User config: [u'-o', u'/User/jfblagden/Movies/youtube-dl/%(title)s.%(ext)s']
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=Mi_nLFDPMuw']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.8 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] Mi_nLFDPMuw: Downloading webpage
[youtube] Mi_nLFDPMuw: Downloading video info webpage
[youtube] Mi_nLFDPMuw: Extracting video information
[youtube] Mi_nLFDPMuw: Downloading MPD manifest
ERROR: unable to create directory [Errno 13] Permission denied: '/User'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1477, in process_info
    os.makedirs(dn)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/User'
`

**Comment by dstftw** [comment]
What's the output of `echo $HOME`?

**Comment by RedSoxFan04** [comment]
`/Users/jfblagden`

**Comment by dstftw** [comment]
It's User**s** not User correct your path in template. Or even simply replace with:
```
-o '~/Movies/youtube-dl/%(title)s.%(ext)s'
```

**Comment by RedSoxFan04** [comment]
That worked! Now it’s downloading videos to the right place and with the right extension. 

Thank you!

**Comment by dstftw** [comment]
Just for my info, where the hell you get `--` from into your config file?

**Comment by RedSoxFan04** [comment]
I got it from the Configuration section of the youtube-dl GitHub page. 
![screen shot 2016-02-27 at 2 54 47 pm](https://cloud.githubusercontent.com/assets/13876066/13375310/c01e79c4-dd69-11e5-8cf8-f2819d8a7516.jpg)

**Comment by dstftw** [comment]
There is no such example (with space after `--`) in example section.

**Comment by RedSoxFan04** [comment]
![screen shot 2016-02-27 at 3 49 12 pm](https://cloud.githubusercontent.com/assets/13876066/13375348/6a9d6108-dd6a-11e5-8cfc-6aacfff80737.jpg)

**Comment by RedSoxFan04** [comment]
Because I saw the double dash there, I thought that you had to use double dashes in the configuration file and `-o` in Terminal. I didn’t understand that you use `-o` in both.

**Comment by dstftw** [comment]
How come a space after double dash? There is no such spaces in the example.

**Comment by RedSoxFan04** [comment]
I’m not sure how I made that mistake.

**Comment by dstftw** [comment]
Is it [more clear](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration) now?

**Comment by RedSoxFan04** [comment]
Yeah, it is. Now I know to use “-o” instead of  double quotes, and also that I need to make sure that “users” is plural instead of singular.

**Comment by kwolk** [comment]
I found that I had to put the configuration file (which should end in ".conf" but I don't see this detail in the notes) in the $Home folder. All the time I was putting it into the "~/.config/" directory, having to create a folder named "youtube-dl/config".

I think you should update your instructions on this, unless I am mistaken?

**Comment by yan12125** [comment]
> which should end in ".conf" but I don't see this detail in the notes

Instructions updated in 899d2bea63f34e85967a93da3c9c2835c3e9bfd4. The [configuration files](https://github.com/rg3/youtube-dl/blob/master/README.md#configuration) section should be clear now.
