### ISSUE TITLE
want you to add a site

### ISSUE THREAD

**Issue by githubuserromi** [rg3/youtube-dl#8685]
I want you to add a site.
http://ero-video.net/
http://asg.to/

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by githubuserromi** [comment]
http://ero-video.net/movie/?mcd=W0vvQMZ2meoNcRp9
http://asg.to/contentsPage.html?mcd=hnM1PyroxI0N3CGs

**Comment by dstftw** [comment]
First video looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.
Second video does not exist.
If you are going to provide non copyright infringing links create a separate site support request issues **per site**.
