### ISSUE TITLE
[Site Support Request] Thumbzilla.com

### ISSUE THREAD

**Issue by Hrxn** [rg3/youtube-dl#8696]
Hey, I just noticed, a famous site is still missing:

https://www.thumbzilla.com/ [NSFW]

Part of the Pornhub Network, so I would assume the extractor should be pretty similar. Or maybe basically the same..

For those who remember, Thumbzilla was one of the early big TGP sites, back then, in the early days of the Internet ;)

Some example links I just picked, all NSFW, obviously.

https://www.thumbzilla.com/video/ph56c38f95398f8/slobber-damage-cute-teen-on-hookup-hotshot

https://www.thumbzilla.com/video/ph56c4961105a88/amateur-teen

https://www.thumbzilla.com/video/ph56ae29c08b6b9/sara-luvv-and-karlee-grey-tries-mandingo-s-bbc

https://www.thumbzilla.com/video/1686615479/orgasming-in-full-deepthroat

**Comment by dstftw** [comment]
Provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by Hrxn** [comment]
I just picked these from the frontpage of thumbzilla.com, which one do you think violates any copyrights?

As said before, Thumbzilla is part of the Pornhub Network: 
https://en.wikipedia.org/wiki/MindGeek#Pornhub_NETWORK

The most important sites, including Pornhub itself, obviously, are already supported by youtube-dl, so I don't see what is different in this case?

**Comment by dstftw** [comment]
All provided example URLs contain logos/website of the owner that are not related to thumbzilla. All other extractors have example URLs without such watermarks and can be treated with high confidence as user generated content uploaded by user itself thus not violating any copyrights. Only some legacy extractors yet may have copyrighted example videos that should be replaced as well.

**Comment by Hrxn** [comment]
Yes, the example videos all have logos/watermarks.

The parent company of the parent company (Mindgeek, Pornhub) also owns production companies/studios. I suppose that's where the videos are from, it seems very likely.
I also don't think that many of those videos are the full-length production content, it's mostly less than 10 minutes, with some advertising at the end etc.

Nevertheless, I found some other example videos:

1.
https://www.thumbzilla.com/video/ph56c6114abd99a/horny-girlfriend-sex
(Quality setting only up to 480p)

2.
 https://www.thumbzilla.com/video/ph56d604b95fec8/amateur-gf-gives-lovely-blowjob-until-he-cums
(Quality setting up to 720p HD. Seems to be the highest, haven't found a vid that offers more)

**Comment by Hrxn** [comment]
Thank you very much, Sir!
