### ISSUE TITLE
Signature extraction failed

### ISSUE THREAD

**Issue by jpsouzamatos** [rg3/youtube-dl#8701]
I try download this video https://www.youtube.com/watch?v=wlRsvurx3UI but it happened 
![snapshot81](https://cloud.githubusercontent.com/assets/17548892/13398059/696172e4-dedb-11e5-8807-c4ff0360294f.png)

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
