### ISSUE TITLE
progresshook on fragment.py: Inconsistent behavior on total_bytes

### ISSUE THREAD

**Issue by zhuyifei1999** [rg3/youtube-dl#8711]
In [the documentation of progress_hooks](https://github.com/rg3/youtube-dl/blob/9fb556eef0c6e83594ca4a7fe4d924a6a2a43a60/youtube_dl/YoutubeDL.py#L223), it's said that that if total_bytes is unknown, the value would be None:
```
    progress_hooks:    A list of functions that get called on download
                       progress, with a dictionary with the entries
                       * status: One of "downloading", "error", or "finished".
                                 Check this first and ignore unknown values.
                       If status is one of "downloading", or "finished", the
                       following properties may also be present:
...
                       * total_bytes: Size of the whole file, None if unknown
```
However this is not the case for fragment.py, where the [key simply doesn't exist](https://github.com/rg3/youtube-dl/blob/9fb556eef0c6e83594ca4a7fe4d924a6a2a43a60/youtube_dl/downloader/fragment.py#L58):
```
        # This dict stores the download progress, it's updated by the progress
        # hook
        state = {
            'status': 'downloading',
            'downloaded_bytes': 0,
            'frag_index': 0,
            'frag_count': total_frags,
            'filename': ctx['filename'],
            'tmpfilename': ctx['tmpfilename'],
        }
```

This has caused downstream issues such as [KeyError: 'total_bytes'](https://github.com/Toollabs/video2commons/issues/8)

**Comment by dstftw** [comment]
>the following properties **may** also be present:

None of these fields are guaranteed to be present at all. `total_bytes` is unknown beforehand for fragment based content. `total_bytes_estimate` may be available for non live streams.

**Comment by zhuyifei1999** [comment]
It may be None for unknown values, as explained so in docs, or the documentation itself is not consistent with the behavior.

**Comment by dstftw** [comment]
It may be present or may not. If present it may contain a value or `None`. [Unless mentioned otherwise, None is equivalent to absence of information](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/common.py#L230).
