### ISSUE TITLE
[Feature Suggestion - twitch.tv] Enable Audio_Only format

### ISSUE THREAD

**Issue by simonics** [rg3/youtube-dl#8731]
Adding the request parameter `'allow_audio_only': 'true'` alongside the two instances of `'allow_source': 'true'` in the twitch extractor module appears to enable an `Audio_Only` format, which is regularly restricted to the twitch.tv mobile app.

After implementing this change, `youtube-dl -F twitch.tv/[channel]` on a random channel returns the following additional format summary:

    Audio_Only   mp4        audio only  128k , mp4a.40.2

Would this be worth adding in? I'd imagine that the format might be useful in low-bandwidth situations.

**Comment by buchno** [comment]
> Would this be worth adding in? I'd imagine that the format might be useful in low-bandwidth situations.

Would be great for the [music channels](http://www.twitch.tv/directory/game/Music).

**Comment by benjamincongdon** [comment]
Addressed in #8786.

**Comment by dstftw** [comment]
audio only formats will be supported in the next version.
