### ISSUE TITLE
Question : how to use --match-filter to exclude "Liked videos" and "Favorites" from a youtube channel

### ISSUE THREAD

**Issue by gillouche** [rg3/youtube-dl#8732]
Hi,

I  am trying to find a way to download all the playlists from a given channel without the Liked videos and Favorites playlist.

I tried several things but nothing pass the filter.

For example, here is one : 

youtube-dl https://www.youtube.com/user/makinggameswithben/playlists -i --match-filter "playlist_title != Liked videos & playlist_title != Favorites"

(I normally add -o to create a folder for each playlist but I don't think it is relevant here)

I tried to find the problem with a debugger on youtube_dl/utils.py in the function _match_one but "m" is always false, the code never goes into this block.

Any idea what I am doing wrong ?

Thanks !

**Comment by dstftw** [comment]
`--match-filter 'playlist_id != LLL5m1_llmeiAdZMo_ZanIvg & playlist_id != <favorites_playlist_id>'`.

**Comment by gillouche** [comment]
Hi,

this solution is not okay for me. I need this to be generic so ID is not valid.

I am creating a script to automatically download everything from several channels. Those channels are listed in a config file.

Is there a way to dynamically find those two IDs (liked videos and favorites). Basically, I call youtube-dl on each lines of my config files. Some channels have more than 20 playlists. It works if I add all my playlists without the liked videos but it takes time and I have to manually check the channels if new playlist have been added.

**Comment by dstftw** [comment]
If you'are writing a script the most logical way would be to collect all the playlist URLs and pass to youtube-dl only those you need.

**Comment by gillouche** [comment]
This doesn't work for my needs but it is fine, I'll find another way to prevent those two playlists to be downloaded.

Thanks.

**Comment by gillouche** [comment]
I did some changes which do what I need.

https://github.com/rg3/youtube-dl/pull/8736

Cheers.
