### ISSUE TITLE
[Error - Specific YouTube Video, Letterbox issue?] Format either not reporting right or not downloading right

### ISSUE THREAD

**Issue by srob650** [rg3/youtube-dl#8734]
Video in question: [https://www.youtube.com/watch?v=rI9tpK9S28g](https://www.youtube.com/watch?v=rI9tpK9S28g)

When running
```youtube-dl -F https://www.youtube.com/watch?v=rI9tpK9S28g```
It shows the "best" option as -f 22 720p.

When trying to download that format with
```youtube-dl -f 22 https://www.youtube.com/watch?v=rI9tpK9S28g```
I end up with a 1280x542 file.  I'm not sure if this is just improper reporting of the resolutions from YouTube, because there is actually a 1080p option in the YouTube player, but it doesn't show up as an option in youtube-dl.

The video is letterboxed on YouTube but not when it is downloaded with the above command so I'm not sure if that has anything to do with it.

Thanks for any insights!

**Comment by dstftw** [comment]
These resolutions are reported by YouTube.
1080p does show up in youtube-dl:
```
248          webm       1920x814   DASH video 2226k , vp9, 24fps, video only, 12.77MiB
137          mp4        1920x814   DASH video 3621k , avc1.640028, 24fps, video only, 23.36MiB
```
To download best available quality you don't need to specify any format. You must have ffmpeg/avconv installed though.

**Comment by srob650** [comment]
I know I don't need to specify, and I do have ffmpeg installed.  If you try to download that video the letterboxing goes away.  Is this something I can work around somehow?

**Comment by remitamine** [comment]
> When running
youtube-dl -F https://www.youtube.com/watch?v=rI9tpK9S28g
It shows the "best" option as -f 22 720p.

When trying to download that format with
youtube-dl -f 22 https://www.youtube.com/watch?v=rI9tpK9S28g
I end up with a 1280x542 file.

it will be fixed in the next version:
```
python2 __main__.py -F https://www.youtube.com/watch?v=rI9tpK9S28g
[youtube] rI9tpK9S28g: Downloading webpage
[youtube] rI9tpK9S28g: Downloading video info webpage
[youtube] rI9tpK9S28g: Extracting video information
WARNING: video doesn't have subtitles
[youtube] rI9tpK9S28g: Downloading MPD manifest
[info] Available formats for rI9tpK9S28g:
format code  extension  resolution note
249          webm       audio only DASH audio   51k , opus @ 50k, 464.68KiB
250          webm       audio only DASH audio   68k , opus @ 70k, 589.49KiB
171          webm       audio only DASH audio  124k , vorbis@128k (44100Hz), 1.10MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k (44100Hz), 1.16MiB
251          webm       audio only DASH audio  139k , opus @160k, 1.15MiB
278          webm       256x108    DASH video   78k , webm container, vp9, 12fps, video only, 636.87KiB
160          mp4        256x108    DASH video  110k , avc1.42c00c, 12fps, video only, 997.13KiB
242          webm       426x180    DASH video  226k , vp9, 24fps, video only, 1.36MiB
133          mp4        426x180    DASH video  247k , avc1.4d400d, 24fps, video only, 2.19MiB
243          webm       640x272    DASH video  410k , vp9, 24fps, video only, 2.31MiB
134          mp4        640x272    DASH video  571k , avc1.4d4015, 24fps, video only, 2.99MiB
244          webm       854x362    DASH video  722k , vp9, 24fps, video only, 3.79MiB
135          mp4        854x362    DASH video 1101k , avc1.4d401e, 24fps, video only, 6.15MiB
247          webm       1280x542   DASH video 1275k , vp9, 24fps, video only, 6.88MiB
136          mp4        1280x542   DASH video 1961k , avc1.4d401f, 24fps, video only, 11.91MiB
248          webm       1920x814   DASH video 2226k , vp9, 24fps, video only, 12.77MiB
137          mp4        1920x814   DASH video 3621k , avc1.640028, 24fps, video only, 23.36MiB
36           3gp        320x136    small , mp4v.20.3,  mp4a.40.2
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
5            flv        426x180    small , h263, mp3  @ 64k
18           mp4        640x272    medium , avc1.42001E,  mp4a.40.2@ 96k
43           webm       640x360    medium , vp8.0,  vorbis@128k
22           mp4        1280x542   hd720 , avc1.64001F,  mp4a.40.2@192k (best)
```

**Comment by dstftw** [comment]
Letterboxing is most likely implemented by means of the YouTube player. If none of the formats provides a letterboxed video there is no way do so then.

**Comment by srob650** [comment]
> it will be fixed in the next version

By fixed it seems you are referring to the reporting of the resolution?

> If none of the formats provides a letterboxed video there is no way do so then.

Understood - perhaps I can do this with ffmpeg post-download, I'll look into that.

Thank you both!

**Comment by remitamine** [comment]
> By fixed it seems you are referring to the reporting of the resolution?

yes
