### ISSUE TITLE
Twitter ERROR: There's no video in this tweet

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#8737]
URL: https://twitter.com/BTNBrentYarina/status/705235433198714880
there is a video in this tweet, but YouTube-DL reports:
ERROR: There's no video in this tweet.; please report this issue ......

OUTPUT:
C:\>youtube-dl.py -v "https://twitter.com/BTNBrentYarina/status/7052354331987148
80"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://twitter.com/BTNBrentYarina/status/7
05235433198714880']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[twitter] 705235433198714880: Downloading webpage
ERROR: There's no video in this tweet.; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
Traceback (most recent call last):
  File "C:\youtube-dl.py\youtube_dl\YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\common.py", line 316, in extract
    return self._real_extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\twitter.py", line 237, in _real_ex
tract
    raise ExtractorError('There\'s no video in this tweet.')
ExtractorError: There's no video in this tweet.; please report this issue on htt
ps://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-d
l -U  to update. Be sure to call youtube-dl with the --verbose flag and include
its complete output.

Thanks
Ringo

**Comment by yan12125** [comment]
Thanks for the report. Such Twitter videos will be supported in the next version.
