### ISSUE TITLE
pluzz.francetv  ERROR: Unable to download XML

### ISSUE THREAD

**Issue by jlr25** [rg3/youtube-dl#8745]
~$ youtube-dl http://pluzz.francetv.fr/videos/no_offence_saison1_ep4_,136179743.html
[pluzz.francetv.fr] no_offence_saison1_ep4_,136179743: Downloading webpage
[pluzz.francetv.fr] 136179743: Downloading XML config
ERROR: Unable to download XML: HTTP Error 400: Bad Request; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
under Debian Jessie

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
