### ISSUE TITLE
The "--no-playlist" flag is ignored

### ISSUE THREAD

**Issue by epiraces** [rg3/youtube-dl#8746]
I see this issue when using as:
youtube-dl --no-playlist https://www.youtube.com/playlist?list=1234567890abcdefghhijklmnop

After running the above, I still see all videos are downloaded. I am using 2016.03.01.

**Comment by kidol** [comment]
That's not how it works. Option description:

>--no-playlist
>Download only the video, **if the URL refers to a video and a playlist.**

If you want to download only 1 video, whether playlist or not, you can use `--playlist-end 1`.

I don't think there is an option to fully ignore playlist url's. Do you need this?

**Comment by epiraces** [comment]
I see, my bad. Thanks for pointing that out. I think it could be an useful feature, specially for those of us integrating youtube-dl into larger applications. I'd be happy to take a stab if some direction was given. Feel free to close or re-tag. And again, thanks for clarifying this.

**Comment by epiraces** [comment]
Actually, I think this may be redundant as you are right that `--playlist-end 1` will do it. Please ignore the above comment. Thanks again!
