### ISSUE TITLE
Unable to download subtitles

### ISSUE THREAD

**Issue by eugenerod** [rg3/youtube-dl#8748]
<er> ~$ youtube-dl --verbose --write-sub https://youtu.be/3KIvQ1nUdIs
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--write-sub', 'https://youtu.be/3KIvQ1nUdIs']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.16.0-62-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[youtube] Setting language
[youtube] 3KIvQ1nUdIs: Downloading webpage
[youtube] 3KIvQ1nUdIs: Downloading video info webpage
[youtube] 3KIvQ1nUdIs: Extracting video information
WARNING: unable to download video subtitles for en-GB: Unable to download webpage: HTTP Error 404: Not Found; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
[download] Resuming download at byte 19727155
[download] Destination: La Commune (Paris, 1871) (Part 1_2) w_Subtitles inc. Bahasa Indonesia-3KIvQ1nUdIs.mp4

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
