### ISSUE TITLE
Unable to download videos from Udemy.

### ISSUE THREAD

**Issue by mkranthikmr** [rg3/youtube-dl#8753]
While trying to download videos from udemy. I get this error...

ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the late
st version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and incl
ude its complete output.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 316, in extract
    return self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\udemy.py", line 147, in _real_extract
    r'data-course-id=["\'](\d+)', webpage, 'course id')
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 611, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are u
sing the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.

Previously it was working fine...

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by mkranthikmr** [comment]
E:\Course\BDD> youtube-dl -u username@gmail.com -p password***** -v https://www.udemy.com/rubyonrails-bdd-rspec-capybara/learn/v4/content
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v', u'https://www.udemy.com/rubyonrails-bdd-rspec-c
apybara/learn/v4/content']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as username@gmail.com
[udemy:course] rubyonrails-bdd-rspec-capybara: Downloading webpage
[udemy:course] rubyonrails-bdd-rspec-capybara: Downloading course JSON
[udemy:course] 531360: Downloading course curriculum
[download] Downloading playlist: BDD with Ruby on Rails using RSpec 3 and Capybara
[udemy:course] playlist BDD with Ruby on Rails using RSpec 3 and Capybara: Collected 83 video ids (downloading 83 of the
m)
[download] Downloading video 1 of 83
[udemy] Downloading login popup
[udemy] 3431226: Downloading webpage
ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the late
st version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and incl
ude its complete output.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 316, in extract
    return self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\udemy.py", line 147, in _real_extract
    r'data-course-id=["\'](\d+)', webpage, 'course id')
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 611, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are u
sing the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.


Still i am having this issue... It was working properly till last version of udemy.. With the latest which was updated a day ago... I am having this issue...

**Comment by dstftw** [comment]
Post the output of `youtube-dl -u username@gmail.com -p password***** -v --dump-pages https://www.udemy.com/rubyonrails-bdd-rspec-capybara/learn/v4/content`.

**Comment by mkranthikmr** [comment]
R u sure...?? It is having 175+ pages of output.. even more than that... i am unable to save completely

**Comment by mkranthikmr** [comment]
It is 405 pages of output...

**Comment by mkranthikmr** [comment]
Check this... This is the error... 
RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug

**Comment by dstftw** [comment]
Post the output I've suggested. Without it it's impossible to debug the issue.

**Comment by mkranthikmr** [comment]
where can I post it? I cant attach a file here... And that big output is not sufficient in this box...

**Comment by mkranthikmr** [comment]
If you can provide your mail id I will send that document...

**Comment by dstftw** [comment]
Use any pastebin or fileshare.

**Comment by mkranthikmr** [comment]
https://onedrive.live.com/redir?resid=F7C9B05834A7FB3B!137&authkey=!AHay2WgAQih9ECU&ithint=file%2ctxt

**Comment by mkranthikmr** [comment]
Is that k or do need anything else?

**Comment by dstftw** [comment]
Does https://www.udemy.com/java-tutorial/ work for you?

**Comment by mkranthikmr** [comment]
No I am unable to download..

**Comment by dstftw** [comment]
Post verbose log.

**Comment by mkranthikmr** [comment]
PS E:\TestUdemy> youtube-dl -u username@gmail.com -p password***** -v https://www.udemy.com/java-tutorial/
learn/v4/content
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v', u'https://www.udemy.com/java-tutorial/learn/v4/
content']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as username@gmail.com
[udemy:course] java-tutorial: Downloading webpage
[udemy:course] java-tutorial: Downloading course JSON
[udemy:course] 24823: Downloading course curriculum
[download] Downloading playlist: Java Tutorial for Complete Beginners
[udemy:course] playlist Java Tutorial for Complete Beginners: Collected 70 video ids (downloading 70 of them)
[download] Downloading video 1 of 70
[udemy] Downloading login popup
[udemy] 172757: Downloading webpage
ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the late
st version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and incl
ude its complete output.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 316, in extract
    return self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\udemy.py", line 147, in _real_extract
    r'data-course-id=["\'](\d+)', webpage, 'course id')
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 611, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are u
sing the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.

**Comment by dstftw** [comment]
Looks like udemy serves you a webpage of different layout. What's your location?

**Comment by mkranthikmr** [comment]
India... Telanga... If you don't mind.. Can you share the link from where you can download?

**Comment by mkranthikmr** [comment]
* Telangana..

**Comment by dstftw** [comment]
Try using some proxy with `--proxy`.

**Comment by mkranthikmr** [comment]
Tried.. No use...

**Comment by dstftw** [comment]
Post verbose log.

**Comment by Cmakota** [comment]
PS C:\aulinha> youtube-dl -u login@hotmail.com -p pass**** -v --verbose "" https://www.udemy.com/curso-completo-desenvolvedor-android/learn
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v', u'--verbose', u'https://www.udemy.com/curso-com
pleto-desenvolvedor-android/learn']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.03.06
[debug] Python version 2.7.11 - Windows-7-6.1.7600-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as mafg_37271030@hotmail.com
[udemy:course] curso-completo-desenvolvedor-android: Downloading webpage
[udemy:course] curso-completo-desenvolvedor-android: Downloading course JSON
[udemy:course] 647736: Downloading course curriculum
[download] Downloading playlist: Curso Completo do Desenvolvedor Android M - Crie 10 Apps
[udemy:course] playlist Curso Completo do Desenvolvedor Android M - Crie 10 Apps: Collected 169 video ids (downloading 1
69 of them)
[download] Downloading video 1 of 169
[udemy] Downloading login popup
[udemy] 3858102: Downloading webpage
ERROR: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are using the late
st version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and incl
ude its complete output.
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 319, in extract
    return self._real_extract(url)
  File "c:\python27\lib\site-packages\youtube_dl\extractor\udemy.py", line 147, in _real_extract
    r'data-course-id=["\'](\d+)', webpage, 'course id')
  File "c:\python27\lib\site-packages\youtube_dl\extractor\common.py", line 614, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract course id; please report this issue on https://yt-dl.org/bug . Make sure you are u
sing the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.



would that be it? i'm getting the same error here

**Comment by quanhua92** [comment]
Just fix this issue in https://github.com/rg3/youtube-dl/pull/8868
