### ISSUE TITLE
Database for already-downloaded videos?

### ISSUE THREAD

**Issue by QwertAsdfYxcv** [rg3/youtube-dl#8755]
Hi,

I would suggest a database which - optionally - logs which videos have already been downloaded, and prevents them from being downloaded again.

Example: 

I download videos at work like:
youtube-dl -i -w "ytsearch100:funny-home-videos"
, watch them offline at home, delete them, and when I do the same next day, I would like to get only videos I have not seen before.

Thank you very much in advance!

**Comment by phihag** [comment]
You are describing the `--download-archive` option, which is already fully implemented.
