### ISSUE TITLE
Youtube-dl bug music.yandex.ru

### ISSUE THREAD

**Issue by koznov** [rg3/youtube-dl#8756]
Hello, i've trying to use some music from yandex music on Linux but i'm getting some issues:

On Win 8.1 with youtube-dl.exe (version 2016.03.01) - no issues:
`C:\Users\a.koznov\Downloads>youtube-dl.exe -v https://music.yandex.ru/album/1980
067
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://music.yandex.ru/album/1980067']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[yandexmusic:album] 1980067: Downloading album JSON
[download] Downloading playlist: Nirvana - With The Lights Out - Box Set (2011)
[yandexmusic:album] playlist Nirvana - With The Lights Out - Box Set (2011): Col
lected 23 video ids (downloading 23 of them)
[download] Downloading video 1 of 23
[yandexmusic:track] 555386: Downloading track JSON
[yandexmusic:track] 555386: Downloading track location JSON
[debug] Invoking downloader on u'http://s12f.storage.yandex.net/get-mp3/c37c5ec9
632b6546708bb196ef0a298a/00052d3a897f58ba/music/5/1/data-0.1:22077874384:4273840
?track-id=555386&from=service-10-track&similarities-experiment=default'
[download] Nirvana - Heartbreaker-555386.mp3 has already been downloaded
[download] 100% of 4.08MiB
[download] Downloading video 2 of 23
[yandexmusic:track] 17902550: Downloading track JSON
[yandexmusic:track] 17902550: Downloading track location JSON

ERROR: Interrupted by user`

On Ubuntu 14.04 with youtube-dl (version 2016.03.01) - this issue:
`root@jbots:/home/koznov# youtube-dl -v https://music.yandex.ru/album/1980067
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://music.yandex.ru/album/1980067']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.6 - Linux-3.13.0-32-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[yandexmusic:album] 1980067: Downloading album JSON
ERROR: 1980067: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 510, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 316, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/yandexmusic.py", line 103, in _real_extract
    album_id, 'Downloading album JSON')
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 504, in _download_json
    json_string, video_id, transform_source=transform_source, fatal=fatal)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 514, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: 1980067: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure
you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

Is there something to add into ticket to solve this problem?

Thanks!

**Comment by dstftw** [comment]
Post the output of `youtube-dl -v --dump-pages https://music.yandex.ru/album/1980067` from Ubuntu.

**Comment by koznov** [comment]
http://pastebin.com/hsy3cAJ8

**Comment by dstftw** [comment]
Post the output of `youtube-dl -v --call-home https://music.yandex.ru/album/1980067` from both Windows and Ubuntu hosts.

**Comment by koznov** [comment]
Windows:
http://pastebin.com/qJzU8ss5
Linux:
http://pastebin.com/0MACHG9S

**Comment by dstftw** [comment]
Your Ubuntu machine has non-RU IP that is blocked by Yandex, namely you get response `{"error":"Bad region"}`. Can you listen it in browser from Ubuntu box?

**Comment by koznov** [comment]
Oh, I cant - it is server version - i will try to move server to Russian location.

Thank you!
