### ISSUE TITLE
The biggest movie site in Poland

### ISSUE THREAD

**Issue by wojtulab** [rg3/youtube-dl#8760]
Hello,
Could you add support for http://www.cda.pl/ site?

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by wojtulab** [comment]
sure, please:
http://www.cda.pl/video/59013236?wersja=720p

**Comment by wojtulab** [comment]
wow, its working! :)
