### ISSUE TITLE
Multiple Videos in Queue?

### ISSUE THREAD

**Issue by RedSoxFan04** [rg3/youtube-dl#8761]
Is it possible to set up some sort of queue or is there some other means of specifying multiple videos without having to use multiple Terminal windows?

**Comment by jaimeMF** [comment]
You can pass more than one URL to youtube-dl: `youtube-dl 'http://www.youtube.com/watch?v=BaW_jenozKc' 'http://www.youtube.com/watch?v=UxxajLWwzqY'`. If that's not enough for you usercase, could you explain it with more detail?

**Comment by RedSoxFan04** [comment]
That’s simple enough. Thanks!
