### ISSUE TITLE
Download Youtube Playlist with Season-Episode Name for Plex

### ISSUE THREAD

**Issue by SkydiverFL** [rg3/youtube-dl#8762]
Is it possible to download all of the videos in a Youtube playlist while naming them in the`sXXXeYYY` format using the published date?  For example, one of the videos is named "How to Grow Fungus" and was published on February 15, 2016.  I would like to name the resulting file:

`MyList - s2016e0215 - How to Grow Fungus.mp4`

Thanks, in advance.

**Comment by gillouche** [comment]
Are the 's' of season and 'e' of episode really necessary ?

You can download the playlist and specify the output filenames with -o options.

You could do something like : 
youtube-dl youtube.com/playlist -o "%(playlist_title)s - %(upload_date)s - %(title)s"

**Comment by yan12125** [comment]
Thanks @gillouche. Just don't forget to add ```.%(ext)s```, or downloaded files won't have filename extensions.
If you want 's' and 'e', you need to write wrapper scripts. I'm closing this ticket as no response from the original poster for a long time. If you have a good reason to insert additional letters between year and month, feel free to post it here.
