### ISSUE TITLE
Subtitles not downloaded (has worked before)

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#8765]
Subtitles aren't downloaded by `youtube-dl` even though the program in fact has subtitles.

    data-subtitlesurl = "/programsubtitles/MYNT15000116AA"

This has worked before, or at least for other programs from the same site.

    ~/$ youtube-dl -v -c -i -f mp4 --convert-subtitles srt --hls-prefer-native -o "%(title)s.%(ext)s" https://tv.nrk.no/serie/skam/MYNT15000116/sesong-2/episode-1
    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: [u'-v', u'-c', u'-i', u'-f', u'mp4', u'--convert-subtitles', u'srt', u'--hls-prefer-native', u'-o', u'%(title)s.%(ext)s', u'https://tv.nrk.no/serie/skam/MYNT15000116/sesong-2/episode-1']
    [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
    [debug] youtube-dl version 2016.02.10
    [debug] Python version 2.7.11 - Darwin-15.3.0-x86_64-i386-64bit
    [debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
    [debug] Proxy map: {}
    [NRKTV] MYNT15000116: Downloading webpage
    [NRKTV] MYNT15000116: Downloading f4m manifest
    [NRKTV] MYNT15000116: Downloading m3u8 information
    [debug] Invoking downloader on u'http://nordond11b-f.akamaihd.net/i/wo/open/98/98bd8ef1775706f6c70303dfdbf4d1306ad80af7/4daf9f72-919b-4ee8-8e47-1657e64b72b4_,141,316,563,1266,2250,.mp4.csmil/index_4_av.m3u8?null='
    [hlsnative] Downloading m3u8 manifest
    [hlsnative] Total fragments: 156
    [download] Destination: Skam.mp4
    [download] 100% of 458.90MiB in 03:27
    [ffmpeg] There aren't any subtitles to convert
    ~/$

**Comment by dstftw** [comment]
You didn't specify `--write-sub`.
