### ISSUE TITLE
YouTube Audio Quality - Removed or Bug?

### ISSUE THREAD

**Issue by EnginePod** [rg3/youtube-dl#8769]
I sometimes save the audio version (M4A) of some YouTube videos as they work just as fine as the MP3 (without the hassle of converting them).
But I've noticed that the M4A with the highest bitrate 256 kbps is gone.

If I'm not mistaken the itag of the 256 kbps M4A was 141, but I can't find the 256 kbps version on any videos.
Has YouTube dropped the support for this format or is this a bug with youtube-dl?

**Comment by dstftw** [comment]
```
>youtube-dl http://www.youtube.com/watch?v=a9LDPn-MO4I -F
[youtube] a9LDPn-MO4I: Downloading webpage
[youtube] a9LDPn-MO4I: Downloading video info webpage
[youtube] a9LDPn-MO4I: Extracting video information
[youtube] a9LDPn-MO4I: Downloading MPD manifest
[youtube] a9LDPn-MO4I: Marking watched
[info] Available formats for a9LDPn-MO4I:
format code  extension  resolution note
...
141          m4a        audio only DASH audio  274k , m4a_dash container, mp4a.40.2@256k (44100Hz), 1.83MiB
...
```

**Comment by EnginePod** [comment]
Sure, that video has the format available, but it's a rare video.
Try it on a few music videos and you'll see that none of them have 141 available.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by EnginePod** [comment]
Take Gangnam Style for example: https://www.youtube.com/watch?v=9bZkp7q19f0
It's the same thing for all other music videos, try it yourself.

Also, please open the issue again, because there's something wrong/missing with either YouTube or youtube-dl.

**Comment by dstftw** [comment]
YouTube player itself uses 137+140 and 248+251 for this video. There may be some additional formats in mpd manifest but there is no known way to fetch manifests with ciphered signature.

**Comment by EnginePod** [comment]
Ah, that's interesting!
Do you mind sharing how you find out which audio formats YouTube's player uses?

Also, do you know where to find the URL to the ciphered manifest?
I might be able to find a solution which I can share with the community.

**Comment by dstftw** [comment]
Right click on player, statistics for sysadmins.
[Here](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1270-L1271).

**Comment by EnginePod** [comment]
Right, I never noticed that it showed the itags.

I'll take a look at the manifests.
There must be a way to decipher them.

Also, do you have any info on how the audio WebMs work?
My theory is that they might be the same quality as the 256 kbps M4A, but instead of having a constant bitrate it's a varying bitrate which gives an optimal file size and at the same time the same audio quality as 256 kbps M4A.

**Comment by dstftw** [comment]
This is very [possible](https://github.com/rg3/youtube-dl/issues/6018#issuecomment-114008839).

**Comment by Bl-rp** [comment]
This sudden audio quality drop happened for me suddenly about 3 days ago, from the highest m4a bitrate being 253 kbps to 125 kbps. Note that for many of these 125 kbps tracks, they are also the highest quality audio available, so there's doesn't appear to be a webm equivalent of the old 253 kbps m4a versions. I have several dozen examples if you want them.
