### ISSUE TITLE
Not downloading the entire playlist

### ISSUE THREAD

**Issue by jpalcantara** [rg3/youtube-dl#8772]
It will download the first video of the list and hangs for the rest.

[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=3fPlHjkDI9Q']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.6 - Linux-4.2.0-30-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 3fPlHjkDI9Q: Downloading webpage
[youtube] 3fPlHjkDI9Q: Downloading video info webpage
[youtube] 3fPlHjkDI9Q: Extracting video information
[youtube] 3fPlHjkDI9Q: Downloading MPD manifest

**Comment by dstftw** [comment]
https://www.youtube.com/watch?v=3fPlHjkDI9Q is a single video URL not a playlist.

**Comment by jpalcantara** [comment]
no worries it was not the issue!  issue resolved
