### ISSUE TITLE
Support for filmweb.no

### ISSUE THREAD

**Issue by forthrin** [rg3/youtube-dl#8773]
```
~/$ youtube-dl -v http://www.filmweb.no/trailere/article1264921.ece
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.filmweb.no/trailere/article1264921.ece']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.11 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.3, ffprobe 2.8.3, rtmpdump 2.4
[debug] Proxy map: {}
[generic] article1264921: Requesting header
WARNING: Falling back on generic information extractor.
[generic] article1264921: Downloading webpage
[generic] article1264921: Extracting information
ERROR: Unsupported URL: http://www.filmweb.no/trailere/article1264921.ece
```

**Comment by forthrin** [comment]
Any ETA on this?

**Comment by yan12125** [comment]
No. There are lots of new site requests, and few developers.

**Comment by TRox1972** [comment]
For developers: 23video embed

**Comment by forthrin** [comment]
How do you figure out how the URL to the actual video stream for a particular site are generated? By setting breakpoints in the browser console and stepping through the JavaScript code?

If your standard approach could be explained, maybe someone could help out.

**Comment by TRox1972** [comment]
@forthrin I've made [an extractor](https://github.com/rg3/youtube-dl/pull/10368) for the site. It's

**Comment by TRox1972** [comment]
@forthrin I've made [an extractor](https://github.com/rg3/youtube-dl/pull/10368) for the site. It's working, but needs improvement before it's ready to be merged.

**Comment by forthrin** [comment]
That's great news! Be sure to post commits to the release branch. Any comments on my question regarding discovering how the URL is generated?

**Comment by TRox1972** [comment]
@forthrin That depends on the site. A general approach for simple sites is to search the webpage or player page (search for `iframes`) for video-links or f4m- or m3u8-manifests. If the file hosting is done by another site, e.g. Kaltura, or 23video in this case, you often need only to extract the id of the video and delegate the rest of the extraction to the extractor for the other site. (Anonymous) APIs are also often valuable. In some cases, though, when the provider generates the URL through javascript and obfuscates it, you'll need to reverse engineer the relevant js code, but this is usually only the case of larger providers like [openload](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/openload.py).

[The extractor](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/vidbit.py) for vidbit.com is relatively simple if you know some Python, and may be a good starting point if you want to create an extractor of your own; also read the [developer instructions](https://github.com/rg3/youtube-dl#developer-instructions) if you're gonna do this.

**Comment by remitamine** [comment]
will be supported in the next version.
