### ISSUE TITLE
youtube-dl -g command returns 2 links

### ISSUE THREAD

**Issue by dspstudio** [rg3/youtube-dl#8775]
Hello,

I have 2 servers running youtube-dl latest version.
On the nr 1 server if I run youtube-dl -g US7lXq8Fxnw I get a link with the video and audio, all fine.
On the nr 2 server if I run the same command I'll get 2 links: first is the video and second the audio.

Can anyone tell me how can i get the direct link with video and audio?

Thanks

**Comment by dstftw** [comment]
First server has ffmpeg/avconv installed, you get `bestvideo` and `bestaudio` links, seconds does not you get `best` link. Use search: #8316.
