### ISSUE TITLE
Major issue downloading playlists from youtube

### ISSUE THREAD

**Issue by felipekaisersoft** [rg3/youtube-dl#8777]
I got an error downloading the following playlist: "https://www.youtube.com/watch?v=5wBTdfAkqGU&index=23&list=RDEML187WeTVyI-cwCYmbYpa8Q" error is in spoiler(copied from command line/lxterminal because the > operator didn't work)
Error log: 
[error.txt](https://github.com/rg3/youtube-dl/files/160034/error.txt)

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
