### ISSUE TITLE
request an upgrade

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#8781]
hi Sir
as you know pluralsight blocked account but i found best way and i tried
just need to add "save link" option in pluralsight it will generate all lectures download links and save in txt file then i it will download via idm without block account
just add this option 
-s, --save-links      Do not download but save links to a file
and its just save txt file with all lectures download url
here is nishad added this option in udemy and its working superb you can check
https://github.com/nishad/udemy-dl-windows

if you will add this option it will help evan many other sites also if you cant add in all sites then plz just add this option to pluralsight file 

thanks

**Comment by dstftw** [comment]
Use `-g` option to get the list of download links. However I doubt IDM will help you avoid ban.

**Comment by jaan143** [comment]
well i tried and its generate the links but not fast like nishad's udemy lectures saving links
but main problem is where he save generated links ? my download folder is empty but if i start download videos then its download in the same directory

**Comment by dstftw** [comment]
There is an **intentional** anti-throttle sleep interval between each call to ViewClip API without it you'll most likely get banned much sooner by pluralsight.
Generated links are printed to stdout. I you want to save them to file use redirection `> links.txt`.

**Comment by jaan143** [comment]
i dont understand how to use links.txt 
can you plz give me exact command like this 
youtube-dl --verbose https://app.pluralsight.com/library/courses/jest-mastering-react-testing/table-of-contents --get-url --username ******@live.com --password *******
where to use links.txt ?

thanks

**Comment by Hrxn** [comment]
Like this, at the end of the command line:
`youtube-dl --verbose https://app.pluralsight.com/library/courses/jest-mastering-react-testing/table-of-contents --get-url --username ***@live.com --password **** > links.txt`

**Comment by jaan143** [comment]
hi i got an error while using this command and its saving just few lectures url
here is details

PS C:\Users\HDNLUF037.WIN-IPDLDV1QL5B\downloads> youtube-dl --verbose https://app.pluralsight.com/library/courses/algori
thmics-introduction/table-of-contents --get-url --username kennyabroad@live.com --password skype123 > links.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'https://app.pluralsight.com/library/courses/algorithmics-introduction/table-of
-contents', '--get-url', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.02.09.1
[debug] Python version 3.4.3 - Windows-2012Server-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
WARNING: Unable to download webpage: HTTP Error 429:
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ve
rsion; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include i
ts complete output.
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 315, in extract
    return self._real_extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\pluralsight.py", line 226, in _real_extract
    self._sort_formats(formats)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 828, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure y
ou are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --
verbose flag and include its complete output.

PS C:\Users\HDNLUF037.WIN-IPDLDV1QL5B\downloads>
