### ISSUE TITLE
ESPN geo block

### ISSUE THREAD

**Issue by RingoTheDog** [rg3/youtube-dl#8784]
URL: http://espn.go.com/video/clip?id=14908808&ex_cid=espnapi_internal

From my location I can't view this video, so this may be expected behavior:

youtube-dl.py -v "http://espn.go.com/video/clip?id=14908808&ex_cid=espnapi_i
nternal"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://espn.go.com/video/clip?id=14908808&e
x_cid=espnapi_internal']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.03.01
[debug] Python version 2.7.11 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-71346-gdf4fca2
[debug] Proxy map: {}
[ESPN] clip?id=14908808&ex_cid=espnapi_internal: Downloading webpage
[ESPN] 14908808: Downloading webpage
[OoyalaExternal] 14908808: Downloading JSON metadata
[OoyalaExternal] 14908808: Downloading mp4 JSON
ERROR: OoyalaExternal said: unauthorized location
Traceback (most recent call last):
  File "C:\youtube-dl.py\youtube_dl\YoutubeDL.py", line 666, in extract_info
    ie_result = ie.extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\common.py", line 316, in extract
    return self._real_extract(url)
  File "C:\youtube-dl.py\youtube_dl\extractor\ooyala.py", line 174, in _real_ext
ract
    return self._extract(content_tree_url, video_id)
  File "C:\youtube-dl.py\youtube_dl\extractor\ooyala.py", line 78, in _extract
    self.IE_NAME, cur_auth_data['message']), expected=True)
ExtractorError: OoyalaExternal said: unauthorized location

**Comment by dstftw** [comment]
You can't download it if you can't watch in browser.

**Comment by RingoTheDog** [comment]
That is what I thought, but just curious.....how does the "Comedy Central" extractor work then?
my browser is geo-blocked from Comedy Central content, but YouTube-dl works 100%?

**Comment by dstftw** [comment]
Different platforms use different mechanisms to impose geo restriction. Some are flawed and possible to be worked around.
