### ISSUE TITLE
youtube-dl Terminates when trying to download a video blocked/deleted

### ISSUE THREAD

**Issue by dkl3** [rg3/youtube-dl#8788]
I'm aware some others have probably brought up this issue, but it's frustrating when I try and download a YouTube channel but then it terminates as soon as a video is blocked/deleted from a copyright strike.

I'll show you an instance (note that I'm on video 205):

[download] Downloading video 205 of 350
[youtube] W2vvSScOZhA: Downloading webpage
[youtube] W2vvSScOZhA: Downloading video info webpage
ERROR: W2vvSScOZhA: YouTube said: This video contains content from UMG, who has blocked it in your country on copyright grounds.
~/Desktop/

Would the developer be willing to repair this? It shouldn't be too hard to repair. I archive YouTube channels too, so this is an important issue for me to have fixed. I'm sure others would appreciate it as well.

Type 'youtube-dl https://www.youtube.com/watch?v=W2vvSScOZhA' to see for yourself.

**Comment by benjamincongdon** [comment]
I'd have to look at the implementation to be sure, but I imagine that Youtube won't serve you the video stream if the video is blocked in your country - just as if a creator had marked the video as private - so I don't think there's a flag you can check to allow the download to go through.

**Comment by dstftw** [comment]
This is expected behavior. Use `-i` to ignore errors.

**Comment by habibun** [comment]
it's working thanks @dstftw
