### ISSUE TITLE
Support for video.meta.ua

### ISSUE THREAD

**Issue by EnginePod** [rg3/youtube-dl#8789]
Please add support for meta.ua (big site in Ukraine).
Example video: http://video.meta.ua/5502115.video

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by EnginePod** [comment]
Good point, but this is for personal use and it's a big video site (just like YT) so there's all kinds of stuff on there.
I also updated the example video to something more suitable.
