### ISSUE TITLE
Site Support: dw.com

### ISSUE THREAD

**Issue by marvinhagemeister** [rg3/youtube-dl#8790]
Seems like they use a slightly modified jw-player as their video player.

Test URL:
http://www.dw.com/en/germanys-creative-spirits-peter-lindbergh/a-18994218

**Comment by remitamine** [comment]
i added support for video pages.
i don't have other examples on article pages that contain videos.
from the js code it looks like some videos has subtiles but i don't have examples.
so this is what is left:
[ ] audio pages
[ ] article pages that contain videos
[ ] videos with subtitles

**Comment by remitamine** [comment]
will be supported in the next version.

**Comment by marvinhagemeister** [comment]
Awesome! Thanks a lot!
