### ISSUE TITLE
how to get the videos which are similar to another one via youtube-dl 

### ISSUE THREAD

**Issue by badrsh** [rg3/youtube-dl#8795]
this is not an issues : it's just a question 
i'm working on a project and i need to know if  there is anyway to   get the similar of the videos via youtube-dl 
i searched alot but i couldn't find anything about it 
the only thing that i have now is 

youtube-dl -j https://www.youtube.com/results?search_query=how+to+create+android+app+in+android+studio&page=1
 this command gave me all the videos , playlist and everything appear on the page 1 .
also the same videos on different channel but not that what i need

**Comment by dstftw** [comment]
Use `youtube-dl ytsearch<number>"how to create android app in android studio"`, e.g. `youtube-dl ytsearch100:"how to create android app in android studio"`.
