### ISSUE TITLE
audioBoom site request

### ISSUE THREAD

**Issue by canamcy** [rg3/youtube-dl#8796]
It's possible to use the generic extractor by adding .mp3 to the url.

https://audioboom.com/boos/4233286-ai-safety-and-the-legacy-of-bletchley-park
dl url =>
https://audioboom.com/boos/4233286-ai-safety-and-the-legacy-of-bletchley-park.mp3

[generic] 4233286-ai-safety-and-the-legacy-of-bletchley-park: Requesting header
[redirect] Following redirect to https://d15mj6e6qmt1na.cloudfront.net/attachmen
ts/20081845/ai-safety-and-the-legacy-of-bletchley-park.mp3?audio_clip_id=4233286
&Expires=1457469549&Signature=cZ0sizg2bgY8eloGuohilrF4fMzgtzfleVaUnv81UChf1Ua0XL
X%7ECY0CoHrIJ-wVHB6bagg%7EdP%7E0SvTTqX20cUzMcLskDm3s66sJ1-Ntt5TSnFxo7RdSpUV7fxa4
vgR6VQQyybVPHIV9SNmdEcN3HW0ImXJ8axGJ8S4ce-q%7E4Lg24lO7UcmImyfzyh9Iw8nHSxb0KAyF5X
zDHktgdl9EEjO-ezQ4hWSSfHAAV33dLYVZooB2xvkVEtX0GdIbJ-YT0HM5kI-iGXD77ZVG-a5IoEYntX
IAH193QzVM3iF2CmQAXfbp%7EDeKcMQmA4wrjp0cXW5nTBjSjEH5MbaDDaFpWw__&Key-Pair-Id=APK
AJS5FX6XHKL62XLYQ
[generic] ai-safety-and-the-legacy-of-bletchley-park: Requesting header
[info] Available formats for ai-safety-and-the-legacy-of-bletchley-park:
format code  extension  resolution note
mpeg         mp3        audio only
..\..\..\yo0\M\yodl\youtube-dl\generic\ai-safety-and-the-legacy-of-bletchley-par
k-ai-safety-and-the-legacy-of-bletchley-park.mp3
[generic] 4233286-ai-safety-and-the-legacy-of-bletchley-park: Requesting header
[redirect] Following redirect to https://d15mj6e6qmt1na.cloudfront.net/attachmen
ts/20081845/ai-safety-and-the-legacy-of-bletchley-park.mp3?audio_clip_id=4233286
&Expires=1457469549&Signature=cZ0sizg2bgY8eloGuohilrF4fMzgtzfleVaUnv81UChf1Ua0XL
X%7ECY0CoHrIJ-wVHB6bagg%7EdP%7E0SvTTqX20cUzMcLskDm3s66sJ1-Ntt5TSnFxo7RdSpUV7fxa4
vgR6VQQyybVPHIV9SNmdEcN3HW0ImXJ8axGJ8S4ce-q%7E4Lg24lO7UcmImyfzyh9Iw8nHSxb0KAyF5X
zDHktgdl9EEjO-ezQ4hWSSfHAAV33dLYVZooB2xvkVEtX0GdIbJ-YT0HM5kI-iGXD77ZVG-a5IoEYntX
IAH193QzVM3iF2CmQAXfbp%7EDeKcMQmA4wrjp0cXW5nTBjSjEH5MbaDDaFpWw__&Key-Pair-Id=APK
AJS5FX6XHKL62XLYQ
[generic] ai-safety-and-the-legacy-of-bletchley-park: Requesting header
[debug] Invoking downloader on 'https://d15mj6e6qmt1na.cloudfront.net/attachment
s/20081845/ai-safety-and-the-legacy-of-bletchley-park.mp3?audio_clip_id=4233286&
Expires=1457469549&Signature=cZ0sizg2bgY8eloGuohilrF4fMzgtzfleVaUnv81UChf1Ua0XLX
%7ECY0CoHrIJ-wVHB6bagg%7EdP%7E0SvTTqX20cUzMcLskDm3s66sJ1-Ntt5TSnFxo7RdSpUV7fxa4v
gR6VQQyybVPHIV9SNmdEcN3HW0ImXJ8axGJ8S4ce-q%7E4Lg24lO7UcmImyfzyh9Iw8nHSxb0KAyF5Xz
DHktgdl9EEjO-ezQ4hWSSfHAAV33dLYVZooB2xvkVEtX0GdIbJ-YT0HM5kI-iGXD77ZVG-a5IoEYntXI
AH193QzVM3iF2CmQAXfbp%7EDeKcMQmA4wrjp0cXW5nTBjSjEH5MbaDDaFpWw__&Key-Pair-Id=APKA
JS5FX6XHKL62XLYQ'
[download] Destination: ..\..\..\youtube-dl\generic\ai-safety-and-the
-legacy-of-bletchley-park-ai-safety-and-the-legacy-of-bletchley-park.mp3
[download]  10.9% of 44.91MiB at 47.85KiB/s ETA 14:16

**Comment by rvanbekkum** [comment]
This site support-request seems to be taken care of in commit 61f317c24c040d051ec6652cb0d4c650c1fc0361.

**Comment by dstftw** [comment]
AudioBoom will be supported in the next version of youtube-dl.
