### ISSUE TITLE
Request support site: Viceland

### ISSUE THREAD

**Issue by pishposhmcgee** [rg3/youtube-dl#8799]
Viceland is a new channel from Vice. Website at https://www.viceland.com. Appears to use Uplynk, and may be encrypted, so it may not be possible.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by pishposhmcgee** [comment]
For example, https://www.viceland.com/en_us/video/gaycation-japan/568fdf623cd5b1ad4d43efeb?playlist=3

**Comment by GitHubsome** [comment]
I think this would be a cool addition.
It's currently rippable using Atresdownloader, Livestreamer or ffmpeg with the m3u8 so it shouldn't be hard to implement for "best open-source video downloader tool"

**Comment by TRox1972** [comment]
Videos seems to be geo-restricted to the US and requires login.

**Comment by TRox1972** [comment]
My bad: there are videos not geo restricted and that doesn't require login. It currently works by manually parsing m3u8-files to youtube-dl (fails with ffmpeg, btw; the streams are encrypted, it seems). As @pishposhmcgee mentions, the site uses upLynk, which also `extractor/crackle.py` does.

**Comment by ryansonshine** [comment]
I would also like to see viceland support added, I have an active membership although the site can be very buggy at times.
