### ISSUE TITLE
No audio after first download

### ISSUE THREAD

**Issue by schlingel** [rg3/youtube-dl#8800]
I have written a small ruby script which uses youtube-dl to download all videos of a specific playlist as mp3s and set the mp3 tags.

The problem is that after the first video the files do not have any audio. 

Youtube-dl is called as a system command like that:
```
youtube-dl --output \"#{file_name}\" --no-playlist --extract-audio --audio-format mp3 --audio-quality 0 \"#{url}\" 
```
This issue seems to be platform related. The script works on Linux but on my OSX 10.11.3 box the files have no audio.

My ffmpeg installation:
```
ffmpeg version 2.8.4 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 7.0.2 (clang-700.1.81)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.8.4 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```
My youtube-dl installation:
```
> youtube-dl --version
2016.03.06
```

The complete script is attached. (Requires ruby, ffmpeg and youtube-dl)

[yt_pl_grabber.zip](https://github.com/rg3/youtube-dl/files/164754/yt_pl_grabber.zip)

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by schlingel** [comment]
Should I open a new case or do you reopen it?

**Comment by dstftw** [comment]
You explicitly told youtube-dl not to download playlist thus you'll not have anything downloaded apart from the video LIcBlkncCMw.
>[youtube:playlist] Downloading just video LIcBlkncCMw because of --no-playlist

**Comment by schlingel** [comment]
That's right and that's what I want because the ruby script does a few things like ignoring private videos and setting id3 tags. It iterates over an object list, containing urls like the above and the title. (See attached ZIP file with ruby script for details)

But I don't see why that should cause youtube-dl to download a mp3 file without audio - which it does on my OSX box. Even if I execute youtube-dl directly in the terminal with the given command above it doesn't work - audio is missing for the file downloaded. 

Do I use to tool wrong?

**Comment by dstftw** [comment]
Private videos and any other that cause erros can be skipped with `-i`.
So does it work for the first video or does not work at all? Decide already.
You also should never hardcode the extension in output template but rather use `%(ext)s`.

**Comment by schlingel** [comment]
Sorry, thought you'd had read my description above: It depends. If I run the script the first time, the first download works. After that it doesn't.

Thanks for the pointer with the extension.

**Comment by Hrxn** [comment]
Your playlist, if you use it from your script, is just a file with URLs, correct?

Because then you could also try `youtube-dl --extract-audio --audio-format mp3 -a YourPlaylist`

`-a` or `--batch-file`

**Comment by dstftw** [comment]
You should clearly state your problem. From
>The problem is that after the first video the files do not have any audio.

it's impossible to decipher that you are passing bunch of video/playlist URLs in row but not misusing the behavior of a single playlist URL with `--no-playlist` (we just can't afford reading and deciphering the code of all the 3rdparty scripts written in all kinds of languages).
Anyway if this is due to hardcoded extension it should not work at all and should not be platform specific - ffmpeg is the same everywhere. YouTube does not serve mp3 so webm/m4a will be downloaded and conversion with ffmpeg will always take place and extension here is the key ffmpeg uses for it.

**Comment by schlingel** [comment]
Ah, that explains the issue. But I can't wrap my head around the clumsy interface. If I define the output file explicitly as a mp3 file, why should I use a wild card? 

That eases the internal handling for youtube-dl, but doesn't make much sense from a user point of view. I want to define the final output name, not the internal handling path of youtube-dl. 

And you're right. The player I used on Linux seems to parse the file headers and ignore the file extension. iTunes doesn't, apparently. 

Thanks for the grumpy help.

**Comment by dstftw** [comment]
Output template specifies the template for files that **will be downloaded** not files that will be created after postprocessing (i.e. audio extraction in your case). You've already specified `--audio-format` to be `mp3` and should not specify it anywhere else.
