### ISSUE TITLE
Site support: katch.me - persistant storage for periscope videos

### ISSUE THREAD

**Issue by uh-zuh** [rg3/youtube-dl#8809]
Example: https://katch.me/pavelkochkin/v/c4bd62ff-f462-3fbb-86ab-4e625b4b104c

**Comment by TRox1972** [comment]
Link doesn't work. Statement on the root page says

> Katch built a simple, frictionless way to save and discover Live mobile video online. Katch served decades of video to 1.3M users a month. Katch closed its doors on May 4th, 2016.

This should be closed.

**Comment by yan12125** [comment]
Thanks!
