### ISSUE TITLE
WARNING: Requested formats are incompatible for merge and will be merged into mkv

### ISSUE THREAD

**Issue by mipesom** [rg3/youtube-dl#8816]
Installed a fresh Ubuntu 15.10 two days ago. Added wepud8's youtube-dl repository as usual and now get this error on every 2nd video from YouTube. 
Just purged that version and installed from here. But the same happens.

**Comment by dstftw** [comment]
It's not an error it's a warning that is caused by opposite video-only and audio-only formats (e.g. webm+m4a) that can only be muxed in mkv.

**Comment by mipesom** [comment]
I'm not requesting to download video & audio separately. Just 'youtube-dl http:.....'
And since that never happened before it IS an error.

**Comment by dstftw** [comment]
If you don't want to download separate formats you have to explicitly specify formats to be `-f best`. However you won't get best overall quality most of the time since it only served by separate audio/video formats.

**Comment by mipesom** [comment]
That was NEVER before necessary, it always downloaded the 720p version without ANY trouble..

**Comment by dstftw** [comment]
Default behaviour has changed a year ago thus you had an outdated version all that time and had no ffmpeg installed.

**Comment by mipesom** [comment]
First is true, the latter not. But then, the old default was much better.

**Comment by mipesom** [comment]
Though, my youtube-dl version was up to date. Only old config files perhaps.

**Comment by dstftw** [comment]
I've already suggested how to enable the old behavior. The one of the youtube-l's main aim is to download best available quality media by default that is only possible with separate formats. If it does not fit your needs it does not mean this behavior is worse.

**Comment by ejoebstl** [comment]
The issue can be avoided by requesting formats which can be merged. For example the following for mp4:

```
-f "bestvideo[ext=mp4]+bestaudio[ext=m4a]"
```

More details [here](https://askubuntu.com/questions/806258/requested-formats-are-incompatible-for-merge).
