### ISSUE TITLE
youtube-dl --get-url (How to merge audio and video in one URL)

### ISSUE THREAD

**Issue by mrfabiolo** [rg3/youtube-dl#8818]
If I run this:
`youtube-dl -g "https://www.youtube.com/watch?v=fPXqHOpVV80"`

I get these two URLs:
`https://r6---sn-fpoq-8jxe.googlevideo.com/videoplayback?id=7cf5ea1cea5557cd&itag=298&source=youtube&requiressl=yes&pl=18&pcm2cms=yes&mn=sn-fpoq-8jxe&mm=31&mv=m&ms=au&ratebypass=yes&mime=video/mp4&gir=yes&clen=56101502&lmt=1426372388342192&dur=142.142&upn=18rtXFIYGeo&signature=7F7704EB118FC757DFFF7628500464A223B60DA1.97684008C71FDBB90996AE4EA1A2FB60A7041156&fexp=9405987,9416126,9416916,9419452,9420452,9422596,9423661,9423662,9424581,9426472,9427681,9428606,9428702,9429237,9429586,9429739,9430817,9431114,9431117,9431191,9431264&mt=1457633172&sver=3&key=dg_yt0&ip=151.51.97.56&ipbits=0&expire=1457654875&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,pcm2cms,mn,mm,mv,ms,ratebypass,mime,gir,clen,lmt,dur`
`https://r6---sn-fpoq-8jxe.googlevideo.com/videoplayback?id=7cf5ea1cea5557cd&itag=141&source=youtube&requiressl=yes&pl=18&pcm2cms=yes&mn=sn-fpoq-8jxe&mm=31&mv=m&ms=au&ratebypass=yes&mime=audio/mp4&gir=yes&clen=4534300&lmt=1426372034609648&dur=142.198&upn=18rtXFIYGeo&signature=046478CF06296370AAD9968FDA6A0E87FF006EFD.2FC8FDE42379FC6E9C45D69AD425BD38DCB0685E&fexp=9405987,9416126,9416916,9419452,9420452,9422596,9423661,9423662,9424581,9426472,9427681,9428606,9428702,9429237,9429586,9429739,9430817,9431114,9431117,9431191,9431264&mt=1457633172&sver=3&key=dg_yt0&ip=151.51.97.56&ipbits=0&expire=1457654875&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,pcm2cms,mn,mm,mv,ms,ratebypass,mime,gir,clen,lmt,dur`
The first is only video; the second is only audio.

I want only one URL video+audio. Because I wish run something like:
`omxplyaer "https://r6---url_of_video_and_audio_together_...etc..."`

With mplayer or mpv I know that there is an option to specify the audio file source:
`mpv "URL_of_video_only" -audiofile "URL_of_audio_only"`

But I want a solution with omxplayer.

**Comment by dstftw** [comment]
Use `-f best`.

**Comment by mrfabiolo** [comment]
xD, I didn't imagine it was that easy. Thank you.

**Comment by Hrxn** [comment]
FYI, `f -best`, while it may appear otherwise, does not give you the best quality available.

With regard to YouTube, `-f best` is limited to 720p in most cases, even if higher quality is available via DASH, like 1080p. But as you already discovered, DASH serves video and audio as separate streams.
