### ISSUE TITLE
torsocks youtube-dl ffmpeg....

### ISSUE THREAD

**Issue by 11992288** [rg3/youtube-dl#8828]
Hi, 

Sorry; I do not know if this is related to torsocks or to youtube-dl or to ffmpeg....

Operating system: Debian Squeeze testing, all up-to-date.
youtube-dl --version 2016.03.06

I can connect to youtube only via tor at a specific location, so I try something like that in a shellscript:

torsocks -i youtube-dl -i -c -R 5 -w "ytsearch99:funny cats" --restrict-filenames -f mp4 --download-archive done.txt

(Without the "-f mp4" this comes to a halt at "Downloading MPD manifest" when it tries to download the first video which is not a mp4, but with this parameter it downloads ...).

But every few minutes the whole PC comes to a total freeze, and even the mouse does not move anymore; after a minute or two it continues stutteringly.
I figured out that a task "ffmpeg -version" consumes all CPU (6-core-Xeon) and all Memory (64GB)...
When I de-install ffmpeg, it works fine, but I need ffmpeg for other reasons.

I also played around with many parameters like for example --hls-prefer-native or --prefer-avconv or adding </dev/null on the end of the command... did not change anything.
I tried it on another internet connection where I can access youtube without tor; with torsocks there is the same behavior: without torsocks, everything works fine as one would expect. So I think it is an issue of the combination of torsocks and youtube-dl and ffmpeg.

Any ideas how to solve this? Is there a possibility to tell youtube-dl not to use any postprocessors like ffmpeg or avconv or ffprobe or avprobe at all?

Thanks in advance!

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by 11992288** [comment]
Thanks for your answer; here we go:

First an attempt with installed ffmpeg - nothing gets downloaded, the process seems to get killed by the operating system;
then ffmpeg gets uninstalled; then the exactly same youtube-dl is called again, and all works fine...:

```
bla@bla:/bla$ sudo apt-get -y install ffmpeg
(..)
Installing ffmpeg (7:2.8.6-1+b1) ...

bla@bla:/bla$ torsocks -i youtube-dl -v -i -c -R 5 -w "ytsearch2:funny cats, short" --restrict-filenames -f mp4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-i', u'-c', u'-R', u'5', u'-w', u'ytsearch2:funny cats, short', u'--restrict-filenames', u'-f', u'mp4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.06
[debug] Python version 2.7.11+ - Linux-4.3.0-1-amd64-x86_64-with-debian-stretch-sid
Killed

bla@bla:/bla$ sudo apt-get -y remove ffmpeg
(..)
Removing ffmpeg (7:2.8.6-1+b1) ...

bla@bla:/bla$ torsocks -i youtube-dl -v -i -c -R 5 -w "ytsearch2:funny cats, short" --restrict-filenames -f mp4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-i', u'-c', u'-R', u'5', u'-w', u'ytsearch2:funny cats, short', u'--restrict-filenames', u'-f', u'mp4']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.06
[debug] Python version 2.7.11+ - Linux-4.3.0-1-amd64-x86_64-with-debian-stretch-sid
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:search] query "funny cats, short": Downloading page 1
[download] Downloading playlist: funny cats, short
[youtube:search] playlist funny cats, short: Collected 2 video ids (downloading 2 of them)
[download] Downloading video 1 of 2
[youtube] AKRHNXQZYEQ: Downloading webpage
[youtube] AKRHNXQZYEQ: Downloading video info webpage
[youtube] AKRHNXQZYEQ: Extracting video information
[youtube] AKRHNXQZYEQ: Downloading MPD manifest
[debug] Invoking downloader on u'https://r6---sn-f5f7ln7l.googlevideo.com/videoplayback?id=00a4473574196044&ip=77.247.181.165&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpcm2%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9406000%2C9407002%2C9407156%2C9408495%2C9416126%2C9420452%2C9422556%2C9422596%2C9423661%2C9423662%2C9424135%2C9424823%2C9428560%2C9428940%2C9429144%2C9429511%2C9430988&dur=224.583&pl=22&initcwndbps=1291250&ratebypass=yes&source=youtube&pcm2=no&requiressl=yes&nh=IgpwcjAyLmZyYTE2KgkxMjcuMC4wLjE&expire=1457739494&key=yt6&mime=video%2Fmp4&ipbits=0&sver=3&lmt=1441363296141857&itag=22&mv=m&mt=1457717672&ms=au&signature=AA219BBDE6DD6945BD1E510DE6AC8B67872603DA.C3A667930159D3465E0193AB84FC0485FCAF2064&mn=sn-f5f7ln7l&mm=31&upn=4X_XJm0Wnbc'
[download] Destination: Funny_Cats_Eating_Compilation_May_2015-AKRHNXQZYEQ.mp4
[download] 100% of 35.06MiB in 02:41
[download] Downloading video 2 of 2
[youtube] Wmz0wGx5sq8: Downloading webpage
[youtube] Wmz0wGx5sq8: Downloading video info webpage
[youtube] Wmz0wGx5sq8: Extracting video information
[youtube] Wmz0wGx5sq8: Downloading MPD manifest
[debug] Invoking downloader on u'https://r4---sn-f5f7ln7e.googlevideo.com/videoplayback?pcm2=no&mime=video%2Fmp4&nh=IgpwcjAyLmZyYTE2KgkxMjcuMC4wLjE&fexp=9406000%2C9407002%2C9407156%2C9408495%2C9416126%2C9420452%2C9422556%2C9422596%2C9423661%2C9423662%2C9424135%2C9424823%2C9428560%2C9428940%2C9429144%2C9429511%2C9430988&requiressl=yes&expire=1457739670&key=yt6&dur=160.705&source=youtube&lmt=1455348341350528&ratebypass=yes&mt=1457717844&initcwndbps=1137500&id=5a6cf4c06c79b2af&mn=sn-f5f7ln7e&mm=31&ip=77.247.181.165&ms=au&mv=m&pl=22&ipbits=0&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpcm2%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&signature=55E925BEA4FCA021415D4BFDF4B394795E7B6973.5DBAE5343F60584A3C5916473D7A5C5FF3794800&sver=3&upn=crarL3-kdhQ&itag=22'
[download] Destination: Cats_Saying_No_to_Bath_-_A_Funny_Cats_In_Water_Compilation-Wmz0wGx5sq8.mp4
[download] 100% of 29.01MiB in 03:14
[download] Finished downloading playlist: funny cats, short
bla@bla:/bla$
```

Here a screenshot that shows the insane RAM consumption of ffmpeg very shortly before the machine freezes again at the first of the above two attempts...: http://666kb.com/i/d74t7ylq9fl793fxb.gif
The 100% memory peaks where the machine totally freezes in fact are no peaks but sometimes are several minutes long; htop just doesnt see that...

**Comment by dstftw** [comment]
Post the output of each command:
```
avprobe -version
avconv -version
ffmpeg -version
ffprobe -version
```
