### ISSUE TITLE
--mark-watched isn't working anymore

### ISSUE THREAD

**Issue by coldwaterq** [rg3/youtube-dl#8830]
The first time I used it worked, but it hasn't worked since then.

I have attached the --verbose and --dump-pages logs. However I did remove some of the dumped pages from the log because they contained my email. If you need those pages I can email them to you I just didn't want them on here. 

[log.txt](https://github.com/rg3/youtube-dl/files/169745/zzzzzzz.txt)

Thanks for making this tool, and supporting it.

**Comment by coldwaterq** [comment]
The first time I used it I didn't have the user-agent switch set, but when it stopped working I set that to try and see if that would resolve it.

**Comment by dstftw** [comment]
It works fine at the moment. Can you check again?

**Comment by coldwaterq** [comment]
Just tested it again and it seems to be working for me now. I'll start
using it in my scripts. Thanks
