### ISSUE TITLE
Install on a shared Linux hosting?

### ISSUE THREAD

**Issue by haneef95** [rg3/youtube-dl#8832]
Hello,

Can this be installed in a shared Linux hosting?

Thanks,

**Comment by dstftw** [comment]
Why not?

**Comment by haneef95** [comment]
Hi,

I just don't know how to do this.

Basically, I have a shared linux web hosting which supports python. And basically, I want to be able to hot link youtube videos to players. For e.g.: http://yt.mydomain.com/ytdownloadscript.py?link=https://www.youtube.com/watch?v=1MEK0s7TkmU&res=720p & insert this URL on a media player like XBMC, WMplayer, VLC & play it straight away.

Thanks,

**Comment by haneef95** [comment]
can, someone reopen this issue please?

It just got closed for some reason.

**Comment by dstftw** [comment]
youtube-dl is not a web app. To run it as at web you'll need to write a web frontend for it or use any existing.
