### ISSUE TITLE
How to limit  download to specific extensions 

### ISSUE THREAD

**Issue by moiseyo** [rg3/youtube-dl#8837]
I'd like to  put in my  python code   restriction   to files with extensions mp4 and avi 

What option ot need to add  to  option dictionary

before line 

ydl = YoutubeDL(ydl_opts)

Thank you

**Comment by dstftw** [comment]
`'format': 'best[ext=mp4]/best[ext=avi]'`

**Comment by moiseyo** [comment]
My settings

ydl_opts['format']= ['best[ext=mp4]/best[ext=avi]']




Moisey O

moiseyoys@gmail.com
*[image: linkedinbutton] <https://www.linkedin.com/in/oysgeltm>*
The view changes only for the leading dog.

**Comment by yan12125** [comment]
It should be a string but not a list.
