### ISSUE TITLE
HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by petmue** [rg3/youtube-dl#8840]
Hi! Other videos like  ` youtube-dl https://www.youtube.com/watch?v=YqmE2m3oK3Y` work fine but the following won't downlad:

> 
$ youtube-dl --verbose https://www.youtube.com/watch?v=77ScJgcOhZ0
>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=77ScJgcOhZ0']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.06
[debug] Python version 2.7.10 - Linux-4.2.0-30-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1
[debug] Proxy map: {}
[youtube] 77ScJgcOhZ0: Downloading webpage
[youtube] 77ScJgcOhZ0: Downloading video info webpage
[youtube] 77ScJgcOhZ0: Extracting video information
[youtube] 77ScJgcOhZ0: Downloading MPD manifest
[debug] Invoking downloader on u'https://r1---sn-9nj-q0ne.googlevideo.com/videoplayback?id=efb49c26070e859d&itag=136&source=youtube&requiressl=yes&mm=31&mn=sn-9nj-q0ne&pl=16&mv=m&ms=au&ratebypass=yes&mime=video/mp4&gir=yes&clen=151651928&lmt=1431845766627657&dur=1066.098&fexp=9416126,9420452,9422596,9423661,9423662,9427903&upn=-mOq114No5Y&signature=8AD6B0D968DCB0776F140161993542CCB8F0C9B2.5F1334C5FC2253264F5382896785CCE70252E55E&key=dg_yt0&sver=3&mt=1457779958&ip=92.204.108.112&ipbits=0&expire=1457801730&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,pl,mv,ms,ratebypass,mime,gir,clen,lmt,dur'
[download] Got server HTTP error. Retrying (attempt 1 of 10)...
[download] Got server HTTP error. Retrying (attempt 2 of 10)...
[download] Got server HTTP error. Retrying (attempt 3 of 10)...
[download] Got server HTTP error. Retrying (attempt 4 of 10)...
[download] Got server HTTP error. Retrying (attempt 5 of 10)...
[download] Got server HTTP error. Retrying (attempt 6 of 10)...
[download] Got server HTTP error. Retrying (attempt 7 of 10)...
[download] Got server HTTP error. Retrying (attempt 8 of 10)...
[download] Got server HTTP error. Retrying (attempt 9 of 10)...
[download] Got server HTTP error. Retrying (attempt 10 of 10)...
ERROR: giving up after 10 retries
Traceback (most recent call last):
  File "/home/$user/.local/lib/python2.7/site-packages/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/home/$user/.local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1931, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 503: Service Unavailable

**Comment by dstftw** [comment]
This is usually an issue on YouTube side. You may want to download different formats with `-f`.
