### ISSUE TITLE
Not Needed

### ISSUE THREAD

**Issue by IsaiahPatton** [rg3/youtube-dl#8844]
this is not needed because of https://10youtube.com/

**Comment by yan12125** [comment]
If you're going to propose a "good" online YouTube downloader, I guess http://www.clipconverter.cc/ is a better choice. (It's the first item in a Google search.) It can download the 1080P version of https://www.youtube.com/watch?v=lqQg6PlCWgI while https://10youtube.com/ can't. And by the way, youtube-dl [handles 500+ other websites than YouTube](https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md).
