### ISSUE TITLE
IOError: [Errno 13] Permission denied: u'Burn Babylon Reggae Drum & Bass Mix by Nrdnk _ #8-ToBDWgaVnbs.m4a.part'

### ISSUE THREAD

**Issue by kaazle** [rg3/youtube-dl#8852]
Hello, I started receiving this error a few days ago "IOError: [Errno 13] Permission denied: u'Burn Babylon Reggae Drum & Bass Mix by Nrdnk _ #8-ToBDWgaVnbs.m4a.part'" I since then have updated to newest version and the problem persists. I only use youtube and mixcloud.

C:\Windows\System32>youtube-dl -x -c https://www.youtube.com/watch?v=ToBDWgaVnbs
[youtube] ToBDWgaVnbs: Downloading webpage
[youtube] ToBDWgaVnbs: Downloading video info webpage
[youtube] ToBDWgaVnbs: Extracting video information
[youtube] ToBDWgaVnbs: Downloading MPD manifest
ERROR: unable to open for writing: [Errno 13] Permission denied: u'Burn Babylon Reggae Drum & Bass Mix by Nrdnk _ #8 https://www.youtube.com/watch?v=ToBDWgaVnbsyoutube-dl -x -c -V https://www.youtube.com/watch?v=ToBDWgaVnbs
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: err https://www.youtube.com/watch?v=ToBDWgaVnbsyoutube-dl -x -c --verbose https://www.youtube.com/watch?v=ToBDWgaVnbs
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-x', u'-c', u'--verbose', u'https://www.youtube.com/watch?v=ToBDWgaVnbs']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2016.03.06
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77715-gfc703f5, ffprobe N-77715-gfc703f5
[debug] Proxy map: {}
[youtube] ToBDWgaVnbs: Downloading webpage
[youtube] ToBDWgaVnbs: Downloading video info webpage
[youtube] ToBDWgaVnbs: Extracting video information
[youtube] ToBDWgaVnbs: Downloading MPD manifest
[debug] Invoking downloader on u'https://r1---sn-uxa0n-txbe.googlevideo.com/videoplayback?id=4e80435a06959dbb&itag=141&source=youtube&requiressl=yes&mm=31&mn=sn-uxa0n-txbe&ms=au&mv=m&pl=44&ratebypass=yes&mime=audio/mp4&gir=yes&clen=142100235&lmt=1429006880836076&dur=4457.046&mt=1457903408&signature=68695D528E081A68B09164E679749FD9D1003CA6.687E91F65367ED85150E3FBDB2C7C17BF68045CE&key=dg_yt0&fexp=9414902,9416126,9420452,9422596,9423606,9423661,9423662,9424568,9425281,9425782,9425962,9426601,9427319,9428982&sver=3&upn=R8op_cM-UtA&ip=2001:56a:f295:a800:9486:b6c1:2f0b:ef1a&ipbits=0&expire=1457925057&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,pl,ratebypass,mime,gir,clen,lmt,dur'
ERROR: unable to open for writing: [Errno 13] Permission denied: u'Burn Babylon Reggae Drum & Bass Mix by Nrdnk _ #8-ToBDWgaVnbs.m4a.part'
Traceback (most recent call last):
  File "youtube_dl\downloader\http.pyo", line 172, in real_download
  File "youtube_dl\utils.pyo", line 309, in sanitize_open
IOError: [Errno 13] Permission denied: u'Burn Babylon Reggae Drum & Bass Mix by Nrdnk _ #8-ToBDWgaVnbs.m4a.part'

**Comment by dstftw** [comment]
You are trying to write to `C:\Windows\System32`. Your account is most likely has rights to do so. `cd` to a directory you have write access to.

**Comment by kaazle** [comment]
Thank you very much, I'm very new to the command line, still it was a dumb
over sight. Sorry and thanks again.
