### ISSUE TITLE
Request for GUI

### ISSUE THREAD

**Issue by Manuel4131** [rg3/youtube-dl#8856]
Hi, do you have wondered to use pyQT or PythonCard to do some GUI application. It could make this
application more awesome!

**Comment by dstftw** [comment]
Out of scope of youtube-dl. There are lots of 3rdparty UIs for youtube-dl.

**Comment by Manuel4131** [comment]
Then I just wonder to know how can I start to participate in this project. The issues are miscellaneous, where can I start. Frustrated.

**Comment by dstftw** [comment]
Right [here](https://github.com/rg3/youtube-dl#developer-instructions) and [here](https://github.com/rg3/youtube-dl/issues).
