### ISSUE TITLE
ERROR: Unsupported URL

### ISSUE THREAD

**Issue by isanketsaha** [rg3/youtube-dl#8887]
[generic] : Requesting header
WARNING: Falling back on generic information extractor.
[generic] : Downloading webpage
[generic] : Extracting information
ERROR: Unsupported URL: http://wixvi.cc/abigail-mac-a-domestic-dicking/; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.
