### ISSUE TITLE
Artist is not saved into metadata

### ISSUE THREAD

**Issue by porelli** [rg3/youtube-dl#8888]
> $ youtube-dl -xi --audio-format mp3 --metadata-from-title "%(artist)s - %(title)s" --add-metadata --xattrs "https://www.youtube.com/playlist?list=PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI"
> [youtube:playlist] PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI: Downloading webpage
> [download] Downloading playlist: Popular Music Videos
> [youtube:playlist] PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI: Downloading page #1
> [youtube:playlist] playlist Popular Music Videos: Downloading 200 videos
> [download] Downloading video 1 of 200
> [youtube] YQHsXMglC9A: Downloading webpage
> [youtube] YQHsXMglC9A: Downloading video info webpage
> [youtube] YQHsXMglC9A: Extracting video information
> [download] Adele - Hello-YQHsXMglC9A.webm has already been downloaded
> [download] 100% of 5.74MiB
> [fromtitle] parsed artist: Adele
> [fromtitle] parsed title: Hello
> [ffmpeg] Adding metadata to 'Adele - Hello-YQHsXMglC9A.webm'
> [ffmpeg] Destination: Adele - Hello-YQHsXMglC9A.mp3
> Deleting original file Adele - Hello-YQHsXMglC9A.webm (pass -k to keep)
> [metadata] Writing metadata to file's xattrs

> $ exiftool *mp3
> ExifTool Version Number         : 10.11
> File Name                       : Adele - Hello-YQHsXMglC9A.mp3
> Directory                       : .
> File Size                       : 4.9 MB
> File Modification Date/Time     : 2015:10:22 15:23:39+02:00
> File Access Date/Time           : 2015:10:22 15:23:39+02:00
> File Inode Change Date/Time     : 2016:03:17 23:29:09+01:00
> File Permissions                : rw-r--r--
> File Type                       : MP3
> File Type Extension             : mp3
> MIME Type                       : audio/mpeg
> MPEG Audio Version              : 1
> Audio Layer                     : 3
> Sample Rate                     : 48000
> Channel Mode                    : Stereo
> MS Stereo                       : Off
> Intensity Stereo                : Off
> Copyright Flag                  : False
> Original Media                  : False
> Emphasis                        : None
> VBR Frames                      : 15286
> VBR Bytes                       : 5134368
> ID3 Size                        : 49
> Title                           : Hello
> Encoder Settings                : Lavf56.1.0
> Audio Bitrate                   : 112 kbps
> Duration                        : 0:06:06 (approx)

**Comment by dstftw** [comment]
Not an youtube-dl issue: https://github.com/rg3/youtube-dl/issues/6587#issuecomment-131855936.
