### ISSUE TITLE
no more youtube-arte

### ISSUE THREAD

**Issue by josephtux** [rg3/youtube-dl#8897]
_Hello_
_My computer work with Debian stable : Jessie_

_I can no more dowload arte-tv:_

_message:_

$youtube-arte --verbose
http://www.arte.tv/guide/fr/048600-000-A/paganini-le-violoniste-du-diable?autoplay=1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose',
'http://www.arte.tv/guide/fr/048600-000-A/paganini-le-violoniste-du-diable?autoplay=1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.11.16
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: avconv 11.6-6, avprobe 11.6-6, rtmpdump 2.4
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[arte.tv:+7] 048600-000-A: Downloading webpage
**ERROR: Unable to extract json vp url; please report this issue on
https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and
include its complete output. Make sure you are using the latest version; type
youtube-dl -U  to update.**
Traceback (most recent call last):
File "/usr/local/bin/youtube-arte/youtube_dl/YoutubeDL.py", line 536, in
extract_info
ie_result = ie.extract(url)
File "/usr/local/bin/youtube-arte/youtube_dl/extractor/common.py",
line 199, in extract
return self._real_extract(url)
File "/usr/local/bin/youtube-arte/youtube_dl/extractor/arte.py",
line 77, in _real_extract
return self._extract_from_webpage(webpage, video_id, lang)
File
"/usr/local/bin/youtube-arte/youtube_dl/extractor/arte.py",
line 82, in _extract_from_webpage
webpage, 'json vp url')
File
"/usr/local/bin/youtube-arte/youtube_dl/extractor/common.py",
line 446, in _html_search_regex
res = self._search_regex(pattern, string, name,
default, fatal, flags, group)
File
"/usr/local/bin/youtube-arte/youtube_dl/extractor/common.py",
line 436, in _search_regex
raise RegexNotFoundError('Unable to
extract %s' % _name)
RegexNotFoundError: Unable to extract json
vp url; please report this issue on
https://yt-dl.org/bug . Be sure to call
youtube-dl with the --verbose flag and
include its complete output. Make sure you
are using the latest version; type
youtube-dl -U  to update

_Message:_

$youtube-dl -U
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.

_thank you_

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
