### ISSUE TITLE
Vevo HTTP Error 500

### ISSUE THREAD

**Issue by g8keepa** [rg3/youtube-dl#8900]
Vevo stopped working today, here was it spits out with any link (with --verbose):

youtube-dl --verbose http://www.vevo.com/watch/zedd/Candyman/USUV71600367
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.vevo.com/watch/zedd/Candyman/USUV71600367']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.9 - Darwin-13.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Vevo] USUV71600367: Downloading video info
ERROR: Unable to download info: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 365, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by g8keepa** [comment]
It seems like some newer ones work, but older ones spit that message.  So I'm guessing to try the link I was trying to gauge? http://www.vevo.com/watch/zedd/Candyman/USUV71600367

**Comment by g8keepa** [comment]
I don't think it's geo-restricted, I've tried different regions (with different content) and it still doesn't work.  (same message).  And my service is configured for youtube-dl

**Comment by dstftw** [comment]
It [does](https://en.wikipedia.org/wiki/Vevo#Availability).

**Comment by g8keepa** [comment]
But I can watch those links fine in any browser?  Even the ones local to me aren't working

**Comment by g8keepa** [comment]
It's not a geolocking issue, that Wikipedia article doesn't show any change to the service as of mid March 2016, not to mention that I'm not trying to get content outside of my region.

**Comment by videoguy-canada** [comment]
Hey guys, any update on this? I can pay someone to fix it.  Really need the downloader.  Let me know if anyone can help.

**Comment by goldensun87** [comment]
Any progress on this issue?

**Comment by videoguy-canada** [comment]
No, still doesn’t work L

 

Can you help?

**Comment by serpas** [comment]
Same problem.

It's not a geolocking issue!!!

**Comment by goldensun87** [comment]
I wish I could help, but I can't :( .

**Comment by g8keepa** [comment]
Thank you very much for resolving this. Sorry for the persistence about it before, just wanted to help resolve it.  Cheers.
