### ISSUE TITLE
cwtv.com doesn't work

### ISSUE THREAD

**Issue by olikami** [rg3/youtube-dl#8905]
According to http://rg3.github.io/youtube-dl/supportedsites.html CWTV is a supported site. 

However when I execute the following line, it returns me generic instead of CWTV and dowloads the thumbnail from cwtv.com:

    youtube-dl -v http://www.cwtv.com/shows/the-100/inside-the-100-thirteen/?play=479caa3c-546c-4871-911d-043d1fc826d3

Output:

    [debug] System config: []
    [debug] User config: []
    [debug] Command-line args: ['-v', 'http://www.cwtv.com/shows/the-100/inside-the-100-thirteen/?play=479caa3c-546c-4871-911d-043d1fc826d3']
    [debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
    [debug] youtube-dl version 2014.02.17
    [debug] Python version 2.7.6 - Linux-3.19.0-32-generic-i686-with-LinuxMint-17.3-rosa
    [debug] Proxy map: {}
    [generic] ?play=479caa3c-546c-4871-911d-043d1fc826d3: Requesting header
    WARNING: Falling back on generic information extractor.
    [generic] ?play=479caa3c-546c-4871-911d-043d1fc826d3: Downloading webpage
    [generic] ?play=479caa3c-546c-4871-911d-043d1fc826d3: Extracting information
    [download] Destination: The 100 Video - Inside The 100 - Thirteen _ Watch Online Free-The100-308-TermsAndConditions-3J5758-CW-Stereo_b17fbf868_CWtv_720x400.jpg
    [download] 100% of 59.21KiB in 00:00

Just as a note, I can stream the video, I just can't download it.

Is this because of copyright, or is it because cwtv.com changed there naming scheme? Can it be fixed? Thanks for any help.

**Comment by yan12125** [comment]
```
[debug] youtube-dl version 2014.02.17
```
You are using a very old version. The latest one is version 2016.03.18. Please update via [updating instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl)

**Comment by olikami** [comment]
I was using the version from the Linux package manager, but apparently they never updated. Will install directly then, thanks.

**Comment by wheels3321** [comment]
I am posting is update the CW don’t work with YouTube-dl no more if you try to down a show you will download a video but say is now 

This version of the app
is no longer supported
More info at: support.cwtv.com 
 I try the YouTube dL on my window 10 it doesn’t work
