### ISSUE TITLE
Anime on Demand: Language download option for streams with dub and sub 

### ISSUE THREAD

**Issue by Ninelpienel** [rg3/youtube-dl#8906]
Hello, when I want to download a stream from Anime on Demand with a dub and a sub version, I can only download the dub version. youtube-dl or the Anime on Demand plugin need an option to choose one of those streams. Example for a stream with dub and sub version: https://www.anime-on-demand.de/anime/39

Regards.

**Comment by dstftw** [comment]
This series is not free. You have to either provide account credentials or provide similar example URL available with free account.

**Comment by Ninelpienel** [comment]
https://www.anime-on-demand.de/anime/169

**Comment by Ninelpienel** [comment]
Okay, sorry, only premium member can watch streams with sub.

**Comment by dstftw** [comment]
Will be supported in the next version via [format selection](https://github.com/rg3/youtube-dl#format-selection).
