### ISSUE TITLE
Unable to download yourstreamlive.com's streaming videos...

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#8907]
Example:

$ youtube-dl -v http://yourstreamlive.com/events/338798
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://yourstreamlive.com/events/338798']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: ffmpeg 2.8.6-1, ffprobe 2.8.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 338798: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 338798: Downloading webpage
[generic] 338798: Extracting information
[debug] Invoking downloader on 'rtmp://storage7.yourstreamlive.com:1935/vod/mp4:3748/338798.mp4?user_agent=Mozilla/5.0+(X11;+Linux+x86_64;+rv:10.0)+Gecko/20150101+Firefox/44.0+(Chrome)'
[download] Destination: Whittier Area Community Church-44.mp4
[debug] rtmpdump command line: rtmpdump --verbose -r 'rtmp://storage7.yourstreamlive.com:1935/vod/mp4:3748/338798.mp4?user_agent=Mozilla/5.0+(X11;+Linux+x86_64;+rv:10.0)+Gecko/20150101+Firefox/44.0+(Chrome)' -o 'Whittier Area Community Church-44.mp4.part' --resume --skip 1
[rtmpdump] RTMPDump v2.4
[rtmpdump](c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : storage7.yourstreamlive.com
[rtmpdump] DEBUG: Parsed app     : vod/mp4:3748/338798.mp4?user_agent=Mozilla
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : storage7.yourstreamlive.com
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : 5.0+(X11;+Linux+x86_64;+rv:10.0)+Gecko/20150101+Firefox/44.0+(Chrome)
[rtmpdump] DEBUG: tcUrl    : rtmp://storage7.yourstreamlive.com:1935/vod/mp4:3748/338798.mp4?user_agent=Mozilla
[rtmpdump] DEBUG: app      : vod/mp4:3748/338798.mp4?user_agent=Mozilla
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[rtmpdump] RTMPDump v2.4
[rtmpdump](c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : storage7.yourstreamlive.com
[rtmpdump] DEBUG: Parsed app     : vod/mp4:3748/338798.mp4?user_agent=Mozilla
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Number of skipped key frames for resume: 1
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : storage7.yourstreamlive.com
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : 5.0+(X11;+Linux+x86_64;+rv:10.0)+Gecko/20150101+Firefox/44.0+(Chrome)
[rtmpdump] DEBUG: tcUrl    : rtmp://storage7.yourstreamlive.com:1935/vod/mp4:3748/338798.mp4?user_agent=Mozilla
[rtmpdump] DEBUG: app      : vod/mp4:3748/338798.mp4?user_agent=Mozilla
[rtmpdump] DEBUG: live     : no
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: Failed to get last keyframe.
[rtmpdump] DEBUG: Closing connection.

ERROR: rtmpdump exited with code 1
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ant/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/home/ant/bin/youtube-dl/youtube_dl/**init**.py", line 412, in main
    _real_main(argv)
  File "/home/ant/bin/youtube-dl/youtube_dl/__init__.py", line 402, in _real_main
    retcode = ydl.download(all_urls)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1719, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 679, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 724, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1365, in process_video_result
    self.process_info(new_info)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1627, in process_info
    success = dl(filename, info_dict)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1569, in dl
    return fd.download(name, info)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/common.py", line 344, in download
    return self.real_download(filename, info_dict)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/common.py", line 157, in report_error
    self.ydl.report_error(_args, *_kargs)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 543, in report_error
    self.trouble(error_message, tb)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 505, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

Thank you in advance. :)

**Comment by mpenkov** [comment]
This site appears down. http://yourstreamlive.com/events/338798 is a blank page. http://yourstreamlive.com/events is HTTP 404. http://yourstreamlive.com gives an admin login screen.

I think we may close this issue.

**Comment by antdude** [comment]
Yep, this web site seems to be dead/gone. Thanks anyways. :(
