### ISSUE TITLE
ARD Mediathek - download fail

### ISSUE THREAD

**Issue by ds2k5** [rg3/youtube-dl#8914]
Hello,

 ./youtube-dl --version
2016.03.18

./youtube-dl --verbose http://www.ardmediathek.de/tv/Reisen/Zu-Gast-in-Frankreich-Lyon-und-der-wild/hr-fernsehen/Video?bcastId=18910908&documentId=33426676
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.ardmediathek.de/tv/Reisen/Zu-Gast-in-Frankreich-Lyon-und-der-wild/hr-fernsehen/Video?bcastId=18910908']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[proxychains] DLL init: proxychains-ng 4.11
[debug] Python version 3.5.1 - Linux-4.4.5-1-MANJARO-x86_64-with-glibc2.3.4

nothing more happend

i have to use proxychains too, because no direct access to web
but with youtube for example it works.

**Comment by jaimeMF** [comment]
Since the url contains a `&`, you [must escape it](https://github.com/rg3/youtube-dl/blob/920d318d3cf70ee0b80cc67e7d3f85b5d45a20a7/README.md#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).
