### ISSUE TITLE
Downloading old & new video from CBS

### ISSUE THREAD

**Issue by spookyahell** [rg3/youtube-dl#8916]
Trying to download http://www.cbs.com/shows/supergirl/video/A0lquInjZ_k4vup_O4OAweMnPdRsnJAE/supergirl-solitude/ or any other "old" video clip. Leads to "http://once.unicornmedia.com/now/media/progressive/bb0b18ba-64f5-4b1b-a29f-0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/468fb310-a585-11e4-bfdb-005056837bc7/e3697f96-9aa1-43f2-9a63-f86a6640f26b/content.mp4", but that has 401 Unauthorized. But that is not all. On new videos youtube-dl downloads a m3u8 list instead of a video.
By the way Old: 18th of March and before; New:19th of March and after

**Comment by Raradra** [comment]
I have the same issue when trying to download the Late Show.

> C:\Users\Raradra\Documents>youtube-dl -v "http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/U6B47sA7bcL1OliOF9n_i6_llXVZLM6r/the-late-show-3-17-2016-william-h-macy-melissa-rauch-isaac-mizrahi-/"
> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: [u'-v', u'http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/U6B47sA7bcL1OliOF9n_i6_llXVZLM6r/the-late-show-3-17-2016-william-h-macy-melissa-rauch-isaac-mizrahi-/']
> [debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
> [debug] youtube-dl version 2016.03.18
> [debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
> [debug] exe versions: ffmpeg N-77883-gd7c75a5, rtmpdump 2.4
> [debug] Proxy map: {}
> [CBS] the-late-show-3-17-2016-william-h-macy-melissa-rauch-isaac-mizrahi-: Downloading webpage
> [ThePlatform] of9zYH1kUpJS: Downloading SMIL data
> [ThePlatform] of9zYH1kUpJS: Checking video URL
> [ThePlatform] 93677179-2d99-4ef4-9e17-fe70d49abfbf: Downloading m3u8 information
> [ThePlatform] of9zYH1kUpJS: Downloading JSON metadata
> [debug] Invoking downloader on u'http://once.unicornmedia.com/now/media/progressive/bb0b18ba-64f5-4b1b-a29f-0ac252f06b68/77a785f3-5188-4806-b788-0893a61634ed/468fb310-a585-11e4-bfdb-005056837bc7/93677179-2d99-4ef4-9e17-fe70d49abfbf/content.mp4'
> ERROR: unable to download video data: HTTP Error 401: Unauthorized
> Traceback (most recent call last):
>   File "youtube_dl\YoutubeDL.pyo", line 1627, in process_info
>   File "youtube_dl\YoutubeDL.pyo", line 1569, in dl
>   File "youtube_dl\downloader\common.pyo", line 344, in download
>   File "youtube_dl\downloader\http.pyo", line 58, in real_download
>   File "youtube_dl\YoutubeDL.pyo", line 1929, in urlopen
>   File "urllib2.pyo", line 437, in open
>   File "urllib2.pyo", line 550, in http_response
>   File "urllib2.pyo", line 475, in error
>   File "urllib2.pyo", line 409, in _call_chain
>   File "urllib2.pyo", line 558, in http_error_default
> HTTPError: HTTP Error 401: Unauthorized

**Comment by saapa** [comment]
See this issue: https://github.com/rg3/youtube-dl/issues/8893

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.
