### ISSUE TITLE
section folders

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#8917]
Hi Sir
i need little help
i want to download udemy course in thier section folders
ceruntly all videos download in main folder but there any way to create automatic section folders and every sectoin's lecture downloading to their folder ?

**Comment by dstftw** [comment]
Use [output template](https://github.com/rg3/youtube-dl#output-template-examples).

**Comment by jaan143** [comment]
plz can you explain me with exact command ?
i dont understand about this 
'~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s'

thank you

**Comment by Hrxn** [comment]
Like this:
```
# Download Udemy course keeping each chapter in separate directory under MyVideos directory in your home
$ youtube-dl -u user -p password -o '~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/java-tutorial/
```
Your example is missing the output option, `-o`

**Comment by jaan143** [comment]
yes got solved
one more Sir 
here is any command to download all files including pdf and txt files ?

thank you very very much

**Comment by Hrxn** [comment]
Well, not with youtube-dl.

Any resource/file that is linked directly can be downloaded with any common download manager though..

**Comment by jaan143** [comment]
i saw a guy download udemy whole course with every txt and pdf and exesice files in their section but he is using automatic script i don't know what trick he is using

anyway Thank you Sir

**Comment by jaan143** [comment]
hi Sir
can you plz add this option in lynda and pluralsight also ?
i tried in both sites but that command is not working in these two sites 
if you update it then it will very very helpfull for us

thank you

**Comment by anirudhamahale** [comment]
Just what I was looking for👍🏻,
Thanks alot.

**Comment by francyfre** [comment]
and for Pluralsight scool? how i can download structure also? 
somebody can answer with an EXAMPLE, please 
example call: https://app.pluralsight.com/library/courses/android-application-basics-understanding/table-of-contents

thankYouAlotttt

francesco
