### ISSUE TITLE
Safaribooksonline.com - ERROR: Unable to extract kaltura reference id

### ISSUE THREAD

**Issue by jeromeza** [rg3/youtube-dl#8927]
Hi,

It seems I can't download video's in a batch from their index page as before.

If I try and download from the below then it fails with the error as per below:
https://www.safaribooksonline.com/library/view/red-hat-certified/9780134429427/

I can however still download individual video's via their direct URL's though as per below:
https://www.safaribooksonline.com/library/view/red-hat-certified/9780134429427/part00.html

$ youtube-dl --version
2016.03.18

$ youtube-dl --verbose --username myuser --password mypass https://www.safaribooksonline.com/library/view/red-hat-certified/9780134429427/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'https://www.safaribooksonline.com/library/view/red-hat-certified/9780134429427/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.10 - Darwin-15.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[safari:course] Downloading login form
[safari:course] Logging in as myuser
[safari:course] Login successful
[safari:course] 9780134429427: Downloading course JSON
[download] Downloading playlist: Red Hat Certified System Administrator (RHCSA) and Red Hat Certified Engineer (RHCE) Library
[safari:course] playlist Red Hat Certified System Administrator (RHCSA) and Red Hat Certified Engineer (RHCE) Library: Collected 420 video ids (downloading 420 of them)
[download] Downloading video 1 of 420
[safari] 9780134429427/part00: Downloading webpage
ERROR: Unable to extract kaltura reference id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/safari.py", line 115, in _real_extract
    reference_id = self._search_regex(r'data-reference-id="([^"]+)"', webpage, 'kaltura reference id')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 621, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract kaltura reference id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.
