### ISSUE TITLE
undef.

### ISSUE THREAD

**Issue by bmike1** [rg3/youtube-dl#8928]
After I download some videos with youtube-dl I get errors when I open the downloaded product:

For the first: nothing plays with the following errors

No suitable decoder module:
VLC does not support the audio or video format "VP90". Unfortunately there is no way for you to fix this.
No suitable decoder module:
VLC does not support the audio or video format "undf". Unfortunately there is no way for you to fix this.

For another: the video plays but no sound comes out and the following error

No suitable decoder module:
VLC does not support the audio or video format "undf". Unfortunately there is no way for you to fix this.

Can someone help me? I just now tried to install browser-plugin-vlc to no avail.

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by bmike1** [comment]
$ youtube-dl --verbose -o IntroToGimp "
https://www.youtube.com/watch?v=JNoVb5k40sU&feature=em-subs_digest"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-o', u'IntroToGimp', u'
https://www.youtube.com/watch?v=JNoVb5k40sU&feature=em-subs_digest']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.23
[debug] Python version 2.7.6 -
Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: ffmpeg 2.7.2-1dhor, ffprobe 2.7.2-1dhor
[debug] Proxy map: {}
[youtube] JNoVb5k40sU: Downloading webpage
[youtube] JNoVb5k40sU: Downloading video info webpage
[youtube] JNoVb5k40sU: Extracting video information
[youtube] JNoVb5k40sU: Downloading DASH manifest
WARNING: Requested formats are incompatible for merge and will be merged
into mkv.
[debug] Invoking downloader on u'
https://r9---sn-5uaezned.googlevideo.com/videoplayback?id=24da156f9938d2c5&itag=264&source=youtube&requiressl=yes&mm=31&ms=au&mv=m&nh=IgpwcjAyLmF0bDIyKg43MC4xNjcuMTUwLjE5Mw&mn=sn-5uaezned&pl=19&ratebypass=yes&mime=video/mp4&gir=yes&clen=114526336&lmt=1458093310580770&dur=416.933&upn=squSK4Kft0k&signature=8DFA10EC02A14FD695C0E4121110F8608C960714.2777ED3793695D5BDAD04B60FB1A96C9A625E259&mt=1458604980&sver=3&key=dg_yt0&fexp=9407117,9407746,9416126,9418580,9419452,9420452,9422596,9423661,9423662,9425348,9427544,9427902,9428542,9429051,9429505,9429540,9431012,9431118,9431403,9432323&ip=174.70.75.173&ipbits=0&expire=1458626766&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,ms,mv,nh,mn,pl,ratebypass,mime,gir,clen,lmt,dur
'
[download] Destination: IntroToGimp.f264
[download] 100% of 109.22MiB in 00:15
[debug] Invoking downloader on u'
https://r9---sn-5uaezned.googlevideo.com/videoplayback?ipbits=0&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&lmt=1458103067199673&requiressl=yes&keepalive=yes&source=youtube&initcwndbps=788750&itag=251&pl=19&ip=174.70.75.173&mm=31&mn=sn-5uaezned&gir=yes&id=o-AEIu-EcABAOpoEevwKkmgCnW8Fv7aRbsNLzgB9Y7zZv1&signature=2AD44292E203ECF5A9C9026117AE5D2FF7C7E4B3.E2F248B2B3E92440219BE117100607858F608FB1&ms=au&mt=1458604980&mv=m&upn=DMwRigBmkpQ&key=yt6&mime=audio%2Fwebm&expire=1458626765&dur=416.941&clen=7369947&sver=3&fexp=9407117%2C9407746%2C9416126%2C9418580%2C9419452%2C9420452%2C9422596%2C9423661%2C9423662%2C9425348%2C9427544%2C9427902%2C9428542%2C9429051%2C9429505%2C9429540%2C9431012%2C9431118%2C9431403%2C9432323&nh=IgpwcjAyLmF0bDIyKg43MC4xNjcuMTUwLjE5Mw&ratebypass=yes
'
[download] Destination: IntroToGimp.f251
[download] 100% of 7.03MiB in 00:00
[ffmpeg] Merging formats into "IntroToGimp.mkv"
[debug] ffmpeg command line: ffmpeg -y -i file:IntroToGimp.f264 -i
file:IntroToGimp.f251 -c copy -map 0:v:0 -map 1:a:0
file:IntroToGimp.temp.mkv
Deleting original file IntroToGimp.f264 (pass -k to keep)
Deleting original file IntroToGimp.f251 (pass -k to keep)
bmike1@MikesBeast ~ $ youtube-dl --verbose -o Darktable-1-Getting-Started "
https://www.youtube.com/watch?v=IwoHkXqHTCc"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-o',
u'Darktable-1-Getting-Started', u'
https://www.youtube.com/watch?v=IwoHkXqHTCc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.23
[debug] Python version 2.7.6 -
Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: ffmpeg 2.7.2-1dhor, ffprobe 2.7.2-1dhor
[debug] Proxy map: {}
[youtube] IwoHkXqHTCc: Downloading webpage
[youtube] IwoHkXqHTCc: Downloading video info webpage
[youtube] IwoHkXqHTCc: Extracting video information
[youtube] IwoHkXqHTCc: Downloading DASH manifest
[debug] Invoking downloader on u'
https://r6---sn-5uaeznlz.googlevideo.com/videoplayback?id=230a07917a874c27&itag=271&source=youtube&requiressl=yes&mm=31&ms=au&mv=m&nh=IgpwcjAxLmF0bDIyKgkxMjcuMC4wLjE&mn=sn-5uaeznlz&pl=19&ratebypass=yes&mime=video/webm&gir=yes&clen=72936827&lmt=1457497578182827&dur=327.566&upn=f1jiKpVaF98&signature=7FDFCC4EBCB797C66B586229DDECDA80436F2173.686C59D962CEFB2D7FF3BEE0CF0113F867B681FC&mt=1458605133&sver=3&key=dg_yt0&fexp=9405969,9415425,9416126,9420452,9422596,9423661,9423662,9425348,9426679,9427902,9428012,9429566,9429821,9430003,9430844,9431012,9431439,9431583,9431671,9432486&ip=174.70.75.173&ipbits=0&expire=1458626803&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,ms,mv,nh,mn,pl,ratebypass,mime,gir,clen,lmt,dur
'
[download] Destination: Darktable-1-Getting-Started.f271
[download] 100% of 69.56MiB in 00:09
[debug] Invoking downloader on u'
https://r6---sn-5uaeznlz.googlevideo.com/videoplayback?mn=sn-5uaeznlz&mm=31&key=yt6&clen=5707390&signature=6556D90F6463EC2D6F5A5D1E89FC8F5065A7331F.BD5356CB3FA692D725D9C1D342E0A479E56FBCC3&ms=au&pl=19&mv=m&mt=1458605133&fexp=9405969%2C9415425%2C9416126%2C9420452%2C9422596%2C9423661%2C9423662%2C9425348%2C9426679%2C9427902%2C9428012%2C9429566%2C9429821%2C9430003%2C9430844%2C9431012%2C9431439%2C9431583%2C9431671%2C9432486&sver=3&gir=yes&nh=IgpwcjAxLmF0bDIyKgkxMjcuMC4wLjE&upn=x36ZMMGfTUg&mime=audio%2Fwebm&expire=1458626803&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ipbits=0&initcwndbps=827500&requiressl=yes&lmt=1457496514533777&itag=251&keepalive=yes&ip=174.70.75.173&dur=327.601&source=youtube&id=o-AHu8uii8tPbHyrL2JQzcZex9JF77JFHlPZyE7Pbr5s4U&ratebypass=yes
'
[download] Destination: Darktable-1-Getting-Started.f251
[download] 100% of 5.44MiB in 00:00
[ffmpeg] Merging formats into "Darktable-1-Getting-Started.webm"
[debug] ffmpeg command line: ffmpeg -y -i
file:Darktable-1-Getting-Started.f271 -i
file:Darktable-1-Getting-Started.f251 -c copy -map 0:v:0 -map 1:a:0
file:Darktable-1-Getting-Started.temp.webm
Deleting original file Darktable-1-Getting-Started.f271 (pass -k to keep)
Deleting original file Darktable-1-Getting-Started.f251 (pass -k to keep)
bmike1@MikesBeast ~ $


On Mon, Mar 21, 2016 at 7:38 PM, Sergey M. <notifications@github.com> wrote:

> Closed #8928 <https://github.com/rg3/youtube-dl/issues/8928>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rg3/youtube-dl/issues/8928#event-597946606>
>



-- 
:-)~MIKE~(-:

**Comment by dstftw** [comment]
Update VLC.

**Comment by bmike1** [comment]
I tried that earlier.

$ sudo apt-get install vlc
[sudo] password for bmike1:
Reading package lists... Done
Building dependency tree
Reading state information... Done
vlc is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
bmike1@MikesBeast ~ $ sudo apt-get install -u vlc
Reading package lists... Done
Building dependency tree
Reading state information... Done
vlc is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.


On Mon, Mar 21, 2016 at 8:11 PM, Sergey M. <notifications@github.com> wrote:

> Update VLC.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rg3/youtube-dl/issues/8928#issuecomment-199551208>
>



-- 
:-)~MIKE~(-:

**Comment by bmike1** [comment]
should I compile from source?

On Mon, Mar 21, 2016 at 8:16 PM, Michael <bmike1@gmail.com> wrote:

> I tried that earlier.
>
> $ sudo apt-get install vlc
> [sudo] password for bmike1:
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> vlc is already the newest version.
> 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
> bmike1@MikesBeast ~ $ sudo apt-get install -u vlc
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> vlc is already the newest version.
> 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
>
>
> On Mon, Mar 21, 2016 at 8:11 PM, Sergey M. <notifications@github.com>
> wrote:
>
>> Update VLC.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rg3/youtube-dl/issues/8928#issuecomment-199551208>
>>
>
>
>
> --
> :-)~MIKE~(-:
>



-- 
:-)~MIKE~(-:

**Comment by dstftw** [comment]
Or use ppa.

**Comment by bmike1** [comment]
I did a websearch for the ppa and the ppa I found says youtube-dl is the
newest version.

 $  sudo add-apt-repository ppa:nilarimogard/webupd8
You are about to add the following PPA to your system:
 The main Web Upd8 PPA maintained by: http://www.webupd8.org/

To add this PPA, simply paste this in a terminal:
sudo add-apt-repository ppa:nilarimogard/webupd8

Packages in this PPA: audacious, ap-hotspot, awn-applet-radio,
awn-applet-wm, calise, cmus, dockbarx, dockbarx-themes-extra,
dropbox-share, emerald, exaile, fbmessenger, gnome-subtitles,
gnome-window-applets, grsync, grive, gthumb, launchpad-getkeys, mc, mdm
(Mint Display Manager), minitunes, minitube, musique, notifyosdconfig,
nautilus-columns, powertop, ppa-purge, rosa-media-player, fixed
pulseaudio-equalizer, subtitleeditor, syncwall, umplayer, unity-reboot,
wimlib, youtube-dl, xfce4-dockbarx-plugin, xournal, yad, yarock and others.
Almost all packages are updated to their latest version.

For other (specialized) PPAs we maintain, see:
https://launchpad.net/~webupd8team
 More info: https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8
Press [ENTER] to continue or ctrl-c to cancel adding it

Executing: gpg --ignore-time-conflict --no-options --no-default-keyring
--homedir /tmp/tmp.I231pB95Rv --no-auto-check-trustdb --trust-model always
--keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg
--keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 4C9D234C
gpg: requesting key 4C9D234C from hkp server keyserver.ubuntu.com
gpg: key 4C9D234C: "Launchpad webupd8" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

 $  sudo apt-get install youtube-dl
Reading package lists... Done
Building dependency tree
Reading state information... Done
youtube-dl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.


On Mon, Mar 21, 2016 at 8:20 PM, Sergey M. <notifications@github.com> wrote:

> Or use ppa.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rg3/youtube-dl/issues/8928#issuecomment-199554395>
>



-- 
:-)~MIKE~(-:

**Comment by bmike1** [comment]
and yes, I did update before the install....

On Mon, Mar 21, 2016 at 8:35 PM, Michael <bmike1@gmail.com> wrote:

> I did a websearch for the ppa and the ppa I found says youtube-dl is the
> newest version.
>
>  $  sudo add-apt-repository ppa:nilarimogard/webupd8
> You are about to add the following PPA to your system:
>  The main Web Upd8 PPA maintained by: http://www.webupd8.org/
>
> To add this PPA, simply paste this in a terminal:
> sudo add-apt-repository ppa:nilarimogard/webupd8
>
> Packages in this PPA: audacious, ap-hotspot, awn-applet-radio,
> awn-applet-wm, calise, cmus, dockbarx, dockbarx-themes-extra,
> dropbox-share, emerald, exaile, fbmessenger, gnome-subtitles,
> gnome-window-applets, grsync, grive, gthumb, launchpad-getkeys, mc, mdm
> (Mint Display Manager), minitunes, minitube, musique, notifyosdconfig,
> nautilus-columns, powertop, ppa-purge, rosa-media-player, fixed
> pulseaudio-equalizer, subtitleeditor, syncwall, umplayer, unity-reboot,
> wimlib, youtube-dl, xfce4-dockbarx-plugin, xournal, yad, yarock and others.
> Almost all packages are updated to their latest version.
>
> For other (specialized) PPAs we maintain, see:
> https://launchpad.net/~webupd8team
>  More info: https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8
> Press [ENTER] to continue or ctrl-c to cancel adding it
>
> Executing: gpg --ignore-time-conflict --no-options --no-default-keyring
> --homedir /tmp/tmp.I231pB95Rv --no-auto-check-trustdb --trust-model always
> --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg
> --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 4C9D234C
> gpg: requesting key 4C9D234C from hkp server keyserver.ubuntu.com
> gpg: key 4C9D234C: "Launchpad webupd8" not changed
> gpg: Total number processed: 1
> gpg:              unchanged: 1
>
>  $  sudo apt-get install youtube-dl
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> youtube-dl is already the newest version.
> 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
>
>
> On Mon, Mar 21, 2016 at 8:20 PM, Sergey M. <notifications@github.com>
> wrote:
>
>> Or use ppa.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rg3/youtube-dl/issues/8928#issuecomment-199554395>
>>
>
>
>
> --
> :-)~MIKE~(-:
>



-- 
:-)~MIKE~(-:

**Comment by bmike1** [comment]
okay.... I installed the ppa for youtube-dl and the ppa for vlc. I update
both and the same thing as before.
the repositories I installed are:
 ppa:videolan/stable-daily
 ppa:nilarimogard/webupd8
I update the programs and:

$ vlc IntroToGimp.mkv
VLC media player 2.1.6 Rincewind (revision 2.1.6-0-gea01d28)
[0x1962118] main libvlc: Running vlc with the default interface. Use 'cvlc'
to use vlc without interface.
"sni-qt/12708" WARN  21:34:02.664 void
StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE
[0x7f3ba0c01878] mkv demux error: unknown codec id=`A_OPUS'
[0x7f3ba0d96578] main decoder error: no suitable decoder module for fourcc
`undf'. VLC probably does not support this sound or video format.
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
[0x7f3b88001248] main vout display error: Failed to resize display
bmike1@MikesBeast ~/Documents/Education/RileyBrandt/Website/Gimp $

$ vlc Darktable-1-Getting-Started.webm
VLC media player 2.1.6 Rincewind (revision 2.1.6-0-gea01d28)
[0x22e1118] main libvlc: Running vlc with the default interface. Use 'cvlc'
to use vlc without interface.
"sni-qt/12749" WARN  21:36:39.900 void
StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE
[0x7f7e2cc01858] mkv demux error: unknown codec id=`A_OPUS'
[0x7f7e2cc0bb18] main decoder error: no suitable decoder module for fourcc
`VP90'. VLC probably does not support this sound or video format.
[0x7f7e2cc0bb18] main decoder error: no suitable decoder module for fourcc
`undf'. VLC probably does not support this sound or video format.

I tried to recode one of the videos as an mp4 but:

 $ youtube-dl --verbose  --recode-video mp4 -o Darktable-1-Getting-Started "
https://www.youtube.com/watch?v=IwoHkXqHTCc"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--recode-video', u'mp4', u'-o',
u'Darktable-1-Getting-Started', u'
https://www.youtube.com/watch?v=IwoHkXqHTCc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.23
[debug] Python version 2.7.6 -
Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: ffmpeg 2.7.2-1dhor, ffprobe 2.7.2-1dhor
[debug] Proxy map: {}
[youtube] IwoHkXqHTCc: Downloading webpage
[youtube] IwoHkXqHTCc: Downloading video info webpage
[youtube] IwoHkXqHTCc: Extracting video information
[youtube] IwoHkXqHTCc: Downloading DASH manifest
[debug] Invoking downloader on u'
https://r6---sn-5uaeznlz.googlevideo.com/videoplayback?id=230a07917a874c27&itag=271&source=youtube&requiressl=yes&pl=19&nh=IgpwcjAxLmF0bDIyKgkxMjcuMC4wLjE&ms=au&mv=m&mm=31&mn=sn-5uaeznlz&ratebypass=yes&mime=video/webm&gir=yes&clen=72936827&lmt=1457497578182827&dur=327.566&fexp=9408490,9416126,9418356,9420452,9422596,9423661,9423662,9426788,9426963,9427902,9427915,9431012,9431438,9431549,9432180&sver=3&signature=5CCB8FD3292BD2ABC6BB15F8ED31900A3174E898.0272AFF36A0C358249BB2E35939CC707DBCAE91E&upn=KsURG0TvljA&key=dg_yt0&mt=1458612055&ip=174.70.75.173&ipbits=0&expire=1458633836&sparams=ip,ipbits,expire,id,itag,source,requiressl,pl,nh,ms,mv,mm,mn,ratebypass,mime,gir,clen,lmt,dur
'
[download] Resuming download at byte 29359104
[download] Destination: Darktable-1-Getting-Started.f271
[download] 100% of 69.56MiB in 00:05
[debug] Invoking downloader on u'
https://r6---sn-5uaeznlz.googlevideo.com/videoplayback?upn=5aiiytGCGfA&mm=31&mn=sn-5uaeznlz&signature=3D41F44AFC81D3F7ACAC101DBD4259357FBE25B6.199ED0D7BC96A3E051F9DACC95BAD3186FCF123C&ms=au&mt=1458612055&mv=m&itag=251&lmt=1457496514533777&sver=3&ipbits=0&mime=audio%2Fwebm&key=yt6&expire=1458633835&gir=yes&nh=IgpwcjAxLmF0bDIyKgkxMjcuMC4wLjE&requiressl=yes&source=youtube&initcwndbps=778750&pl=19&dur=327.601&fexp=9408490%2C9416126%2C9418356%2C9420452%2C9422596%2C9423661%2C9423662%2C9426788%2C9426963%2C9427902%2C9427915%2C9431012%2C9431438%2C9431549%2C9432180&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ip=174.70.75.173&clen=5707390&id=o-ACudTTQl4Gu0uBcz2LE30oRpvEi2v0ijC-rw9PSQCdad&keepalive=yes&ratebypass=yes
'
[download] Destination: Darktable-1-Getting-Started.f251
[download] 100% of 5.44MiB in 00:00
[ffmpeg] Merging formats into "Darktable-1-Getting-Started.webm"
[debug] ffmpeg command line: ffmpeg -y -i
file:Darktable-1-Getting-Started.f271 -i
file:Darktable-1-Getting-Started.f251 -c copy -map 0:v:0 -map 1:a:0
file:Darktable-1-Getting-Started.temp.webm
Deleting original file Darktable-1-Getting-Started.f271 (pass -k to keep)
Deleting original file Darktable-1-Getting-Started.f251 (pass -k to keep)
[ffmpeg] Converting video from webm to mp4, Destination:
Darktable-1-Getting-Started.mp4
[debug] ffmpeg command line: ffmpeg -y -i
file:Darktable-1-Getting-Started.webm file:Darktable-1-Getting-Started.mp4
ERROR: [aac @ 0xc97460] The encoder 'aac' is experimental but experimental
codecs are not enabled, add '-strict -2' if you want to use it.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1737, in
post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line
312, in run
    self.run_ffmpeg(path, outpath, options)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line
159, in run_ffmpeg
    self.run_ffmpeg_multiple_files([path], out_path, opts)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line
155, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError

bmike1@MikesBeast ~ $ youtube-dl --verbose  --recode-video mp4 -strict -2
-o Darktable-1-Getting-Started "https://www.youtube.com/watch?v=IwoHkXqHTCc"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--recode-video', u'mp4',
u'-strict', u'-2', u'-o', u'Darktable-1-Getting-Started', u'
https://www.youtube.com/watch?v=IwoHkXqHTCc']
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: invalid rate limit specified
bmike1@MikesBeast ~ $ youtube-dl --verbose  --recode-video mp4 u'-strict'
u'-2' -o Darktable-1-Getting-Started "
https://www.youtube.com/watch?v=IwoHkXqHTCc"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--recode-video', u'mp4',
u'u-strict', u'u-2', u'-o', u'Darktable-1-Getting-Started', u'
https://www.youtube.com/watch?v=IwoHkXqHTCc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.23
[debug] Python version 2.7.6 -
Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: ffmpeg 2.7.2-1dhor, ffprobe 2.7.2-1dhor
[debug] Proxy map: {}
ERROR: fixed output name but more than one file to download
bmike1@MikesBeast ~ $ youtube-dl --verbose  --recode-video mp4 '-strict -2'
-o Darktable-1-Getting-Started "https://www.youtube.com/watch?v=IwoHkXqHTCc"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--recode-video', u'mp4',
u'-strict -2', u'-o', u'Darktable-1-Getting-Started', u'
https://www.youtube.com/watch?v=IwoHkXqHTCc']
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: using output template conflicts with using title, video
ID or auto number
bmike1@MikesBeast ~ $


On Mon, Mar 21, 2016 at 8:48 PM, Michael <bmike1@gmail.com> wrote:

> and yes, I did update before the install....
>
> On Mon, Mar 21, 2016 at 8:35 PM, Michael <bmike1@gmail.com> wrote:
>
>> I did a websearch for the ppa and the ppa I found says youtube-dl is the
>> newest version.
>>
>>  $  sudo add-apt-repository ppa:nilarimogard/webupd8
>> You are about to add the following PPA to your system:
>>  The main Web Upd8 PPA maintained by: http://www.webupd8.org/
>>
>> To add this PPA, simply paste this in a terminal:
>> sudo add-apt-repository ppa:nilarimogard/webupd8
>>
>> Packages in this PPA: audacious, ap-hotspot, awn-applet-radio,
>> awn-applet-wm, calise, cmus, dockbarx, dockbarx-themes-extra,
>> dropbox-share, emerald, exaile, fbmessenger, gnome-subtitles,
>> gnome-window-applets, grsync, grive, gthumb, launchpad-getkeys, mc, mdm
>> (Mint Display Manager), minitunes, minitube, musique, notifyosdconfig,
>> nautilus-columns, powertop, ppa-purge, rosa-media-player, fixed
>> pulseaudio-equalizer, subtitleeditor, syncwall, umplayer, unity-reboot,
>> wimlib, youtube-dl, xfce4-dockbarx-plugin, xournal, yad, yarock and others.
>> Almost all packages are updated to their latest version.
>>
>> For other (specialized) PPAs we maintain, see:
>> https://launchpad.net/~webupd8team
>>  More info: https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8
>> Press [ENTER] to continue or ctrl-c to cancel adding it
>>
>> Executing: gpg --ignore-time-conflict --no-options --no-default-keyring
>> --homedir /tmp/tmp.I231pB95Rv --no-auto-check-trustdb --trust-model always
>> --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg
>> --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 4C9D234C
>> gpg: requesting key 4C9D234C from hkp server keyserver.ubuntu.com
>> gpg: key 4C9D234C: "Launchpad webupd8" not changed
>> gpg: Total number processed: 1
>> gpg:              unchanged: 1
>>
>>  $  sudo apt-get install youtube-dl
>> Reading package lists... Done
>> Building dependency tree
>> Reading state information... Done
>> youtube-dl is already the newest version.
>> 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
>>
>>
>> On Mon, Mar 21, 2016 at 8:20 PM, Sergey M. <notifications@github.com>
>> wrote:
>>
>>> Or use ppa.
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/rg3/youtube-dl/issues/8928#issuecomment-199554395>
>>>
>>
>>
>>
>> --
>> :-)~MIKE~(-:
>>
>
>
>
> --
> :-)~MIKE~(-:
>



-- 
:-)~MIKE~(-:

**Comment by dstftw** [comment]
You don't need ppa for youtube-dl. You need at least VLC 2.1.9.

**Comment by bmike1** [comment]
about says my version is 2.1.6

On Mon, Mar 21, 2016 at 11:11 PM, Sergey M. <notifications@github.com>
wrote:

> You don't need ppa for youtube-dl. You need at least VLC 2.1.9.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rg3/youtube-dl/issues/8928#issuecomment-199606851>
>



-- 
:-)~MIKE~(-:

**Comment by bmike1** [comment]
Found out how to do it! Add 'ppa:mc3man/trusty-media' then install 'vlc
vlc-plugin-*'.

On Tue, Mar 22, 2016 at 12:38 AM, Michael <bmike1@gmail.com> wrote:

> about says my version is 2.1.6
>
> On Mon, Mar 21, 2016 at 11:11 PM, Sergey M. <notifications@github.com>
> wrote:
>
>> You don't need ppa for youtube-dl. You need at least VLC 2.1.9.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rg3/youtube-dl/issues/8928#issuecomment-199606851>
>>
>
>
>
> --
> :-)~MIKE~(-:
>



-- 
:-)~MIKE~(-:
