### ISSUE TITLE
Site Request: thescene.com

### ISSUE THREAD

**Issue by himadri0327** [rg3/youtube-dl#8929]
https://thescene.com/watch/vogue/narciso-rodriguez-spring-2013-ready-to-wear?source=player_scene_logo

**Comment by jaimeMF** [comment]
It will be supported in the next version.

**Comment by Hrxn** [comment]
Thank you guys, good job!

**Comment by himadri0327** [comment]
Excellent work as always. Thank you jaimeMF.
