### ISSUE TITLE
Extracted Vidzi.tv links output m3u8 instead of mp4

### ISSUE THREAD

**Issue by RokuFan** [rg3/youtube-dl#8930]
When I run this command for vidzi.tv links:
youtube-dl.exe -g http://vidzi.tv/xxxxxxxxxxxx.html

I get the m3u8 source link:

http://93.120.27.92/hls/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/chunk.m3u8

Instead, can you output the link as an mp4 source instead?:

http://93.120.27.92/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/v.mp4

Thanks!

**Comment by dstftw** [comment]
`-f 1`.
