### ISSUE TITLE
HTTP Error 404: Not Found (caused by HTTPError())

### ISSUE THREAD

**Issue by Arrappathor** [rg3/youtube-dl#8935]
X@X-satellite:~/Videos$ youtube-dl --verbose http://www.ardmediathek.de/tv/Tatort/Zorn-Gottes-Video-tgl-ab-20-Uhr/Das-Erste/Video?bcastId=602916&documentId=34233908
[1] 1908
X@X-satellite:~/Videos$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.ardmediathek.de/tv/Tatort/Zorn-Gottes-Video-tgl-ab-20-Uhr/Das-Erste/Video?bcastId=602916']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.9 - Linux-3.16.0-4-686-pae-i686-with-debian-8.3
[debug] exe versions: avconv 11.6-6, avprobe 11.6-6
[debug] Proxy map: {}
[ARD:mediathek] Video: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 365, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

[1]+  Exit 1                  youtube-dl --verbose http://www.ardmediathek.de/tv/Tatort/Zorn-Gottes-Video-tgl-ab-20-Uhr/Das-Erste/Video?bcastId=602916
X@X-satellite:~/Videos$

**Comment by dstftw** [comment]
You have to either put the URL into quotes or manually escape all the special shell characters. Read [FAQ entry](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command) for details.

**Comment by Arrappathor** [comment]
My fault. I had it before my eyes.
Thank you!
t

-------- Ursprüngliche Nachricht --------
Von: "Sergey M." <notifications@github.com> 
Datum:22.03.2016  16:07  (GMT+01:00) 
An: rg3/youtube-dl <youtube-dl@noreply.github.com> 
Cc: Arrappathor <tobias.grampp@nefkom.net> 
Betreff: Re: [youtube-dl] HTTP Error 404: Not Found (caused by HTTPError())
  (#8935) 

You have to either put the URL into quotes or manually escape all the special shell characters. Read FAQ entry for details.
