### ISSUE TITLE
Re: Vevo (Geoblock)

### ISSUE THREAD

**Issue by g8keepa** [rg3/youtube-dl#8939]
The reason I'm posting this is because I've added notes and it seems that this issue is being written off as a geoblock which as you'll see below, is not the case.

My issue (#8900) is tagged as geoblocked.  I have disabled all workarounds and using a vanilla machine (have even bypassed my router). ** I can watch vevo links no problem**, but I get the HTTP error (as listed in 8900).  A wikipedia link was referenced, but doesn't apply to my situation as I'm in the region to watch and have used youtube-dl daily up until I posted the issue.  Nothing has changed on vevo's end (according to the wikipedia link).  In my region, I'm allowed to watch vevo.  The downloader is not functioning.

**Comment by dstftw** [comment]
geo-restricted tag means that provided example URL **is geo-restricted** not **it does not works due to geo-restriction** (in latter case issue'd just get closed, yours is open).
Stop duplicating issues.

**Comment by g8keepa** [comment]
The example URL isn't geo restricted on my end, perhaps trying a vevo link in the region where you are located, will yield the same result to help you move forward.  Sorry for the duplicate, however, again, it doesn't appear to be be geo restricted.

**Comment by dstftw** [comment]
**It does** on my end.

**Comment by g8keepa** [comment]
So you tried a vevo link on your end?  And it's showing geo-restriction?

**Comment by g8keepa** [comment]
(are you able to download anything from vevo)?

**Comment by dstftw** [comment]
I've already said it's georestricted on my end. Completely. As well as in all the countries not mentioned in wiki article.

**Comment by g8keepa** [comment]
I'm in Canada, it's not restricted here.  So what can I do to assist in helping to patch this app?  Because it's not downloading in ANY region (it's not geo, it's worldwide restricted from what you're suggesting).  Yet, it plays perfectly fine in the browser.

**Comment by g8keepa** [comment]
Send me alpha patches if you want, I'll gladly continually test this to help out.

**Comment by dstftw** [comment]
geo-restriction per se is blocking in **some locations** not worldwide. What is the point blocking from downloading worldwide from any location? This is nonsense.
Issue's tags are information for developers and should not even bother you in any way.

**Comment by g8keepa** [comment]
I understand the definition of geo-restriction.

So again, I ask, if it's blocked for some locations, and I'm allowed to watch the links in my region, how is it restricted for me to download?  As you stated above "What is the point blocking from downloading worldwide from any location?" ... That's the question I'm posing to you, you're right, it makes no sense (that's why I wonder why it's tagged as geoblocked).  No need to get upset, I'm just trying to give as much information about the issue to help, not start a fight.

**Comment by dstftw** [comment]
Do you even read my posts?
>geo-restricted tag means that provided example URL is geo-restricted not it does not works due to geo-restriction (in latter case issue'd just get closed, yours is open).
>Issue's tags are information for developers and should not even bother you in any way.

**Comment by g8keepa** [comment]
Why the sarcasm?  You're not reading my question.  So I'll try again and rephrase it:

You said clearly that it's georestricted on your end.  I offered to try on my end where vevo is not georestricted.  The tag doesn't bother me, HOWEVER (and please read this), if the tag is NOT the issue (as in, geoblocking is NOT being the problem), wouldn't it derail the ability to patch the issue?  I'm just trying to provide data to assist.  I can test in my region as again, I'm not georestricted.

**Comment by dstftw** [comment]
I'm well aware you are not georestricted. What are you trying to prove here? If it would derail the ability to patch it, your issue'd get **closed already** but it's not thus waiting for a fix and will get it when someone wants to do that.
