### ISSUE TITLE
Allow custom ffmpeg rtmp output

### ISSUE THREAD

**Issue by sneaky4oe** [rg3/youtube-dl#8940]
I want youtube-dl to push a youtube livestream via ffmpeg with rtmp module to custom rtmp url.

> D:\Programs\ffmpeg\bin>youtube-dl.exe --verbose -f best "https://www.youtube.com/watch?v=*VIDEO_NUMBER*" --no-part --encoding -c copy -f flv "rtmp://MY_SERVICE/MY_KEY_HERE"

I get an error "LookupError: unknown encoding: -c"

Is there a way to work it arond and force custom ffmpeg settings inside youtube-dl?

**Comment by dstftw** [comment]
That is not possible but you can extract stream URL with `youtube-dl -g ...` and then call ffmpeg yourself.

**Comment by sneaky4oe** [comment]
Ok, I managed to grab video only so far by:

> ffmpeg -i https://manifest.googlevideo.com/api/manifest/hls_playlist/id/YkuAziUi_50.410/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/itag%3D140/sgovp/itag%3D137/hls_chunk_host/r6---sn-jvhnu5g-bvwe.googlevideo.com/playlist_type/DVR/tx/962801/txs/962800,962801,962802/gcr/ru/mm/32/mn/sn-jvhnu5g-bvwe/ms/lv/mv/u/pcm2cms/yes/pl/20/dover/3/sver/3/fexp/9405973,9408497,9416126,9417157,9417703,9418223,9420452,9422596,9423348,9423661,9423662,9424135,9424336,9424489,9427902,9427959,9429245,9429739,9431012,9431047,9432583/upn/ZtSkTKEQdzo/mt/1458674497/ip/5.227.160.38/ipbits/0/expire/1458696677/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,playlist_type,tx,txs,gcr,mm,mn,ms,mv,pcm2cms,pl/signature/150C9CDC228A9022DFD9D58EFBBFC0BEF0A20690.46201CB6626D06602895FC3B06E22DB8F137AEB7/key/dg_yt0/playlist/index.m3u8 -c copy -bsf:a aac_adtstoasc -f flv rtmp://premium.cybergame.tv:1953/premium/sneaky4oe?key=MY_KEY_HERE

But there are two flaws - there's no audio, and it plays stream since the beginning of vsh 4 hours.
So, please help to enable audio and grab it from realtime, not past, please.

**Comment by sneaky4oe** [comment]
Found a solution:

> ffmpeg -i https://manifest.googlevideo.com/LONG_GOOGLE_URL/playlist/index.m3u8 -c copy -acodec aac -strict -2 -bsf:a aac_adtstoasc -f flv rtmp://MY_SERVICE/MY_KEY_HERE

Should manually encode to aac, but that seems to fix the issue. Thanks for help.

**Comment by dstftw** [comment]
`-acodec copy` should be enough.

**Comment by sneaky4oe** [comment]
Ok, I'll have to polish it later. Thank you for sending me to "-g". :-)

**Comment by sneaky4oe** [comment]
Tested it. -acodec copy doesn't work. But that doesn't matter either.
