### ISSUE TITLE
cbs.com not working

### ISSUE THREAD

**Issue by himadri0327** [rg3/youtube-dl#8947]
cbs.com not working

http://www.cbs.com/shows/the_price_is_right/video/UOUHoGVTfYukdfndZFGiFe_wJF2TDSZ7/the-price-is-right-3-21-2016/

**Comment by saapa** [comment]
Will be fixed in a upcoming release: https://github.com/rg3/youtube-dl/issues/8893

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.

**Comment by himadri0327** [comment]
You guys rock. Much appreciated.
