### ISSUE TITLE
can you help me find the config file on osx 10.11.4?

### ISSUE THREAD

**Issue by endaer** [rg3/youtube-dl#8950]
Hi,

can you please help me find the config file of youtube-dl on osx 10.11.4?

Thanks a million in advance

**Comment by jaimeMF** [comment]
You must write it with a text editor (like TextEdit, vim, emacs ...) and save it as `~/.config/youtube-dl/config`, you may need to create the folders. Most editors will expand the `~`, but you can replace it with `/Users/<username>` (example: `/Users/endaer`).

**Comment by endaer** [comment]
Erm... OSX does not allow me to create any folders with .config saying that the foldernames starting with a dot are restricted for system, no users can create such folders regardless of my access rights. :/
