### ISSUE TITLE
iPrima.cz - Unable to extract m3u8 url

### ISSUE THREAD

**Issue by DVD-CZ** [rg3/youtube-dl#8953]
$ youtube-dl -U
youtube-dl is up-to-date (2016.03.18)

youtube-dl -v http://play.iprima.cz/ohnivy-kure/ohnivy-kure-9 // This worked few days ago

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://play.iprima.cz/ohnivy-kure/ohnivy-kure-9']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.10 - Linux-4.4.5-200.fc22.i686+PAE-i686-with-fedora-22-Twenty_Two
[debug] exe versions: ffmpeg 2.6.8, ffprobe 2.6.8, rtmpdump 2.4
[debug] Proxy map: {}
[IPrima] ohnivy-kure-9: Downloading webpage
[IPrima] p164408: Downloading player
ERROR: Unable to extract m3u8 url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/iprima.py", line 46, in _real_extract
    m3u8_url = self._search_regex(r"'src': '([^']+\.m3u8)'", playerpage, 'm3u8 url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 621, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract m3u8 url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by PMoski** [comment]
I can confirm that, I have the same problem. Yesterday it worked.
