### ISSUE TITLE
On IGN youtube-dl directly on the .mp4 file does not work

### ISSUE THREAD

**Issue by lucascharrierpulpix** [rg3/youtube-dl#8965]
When doing : 
youtube-dl http://assets3.ign.com/videos/zencoder/2016/03/02/960/7d9b7ef1402046631b6e954a1a004d9c-1500000-1456932076.mp4 --verbose
The script seems to remain blocked on : 'Downloading webpage' 

but using the webpage where is the video, works fine:
youtube-dl http://www.ign.com/videos/2016/03/02/hitman-official-season-premiere-trailer 

Here is the following output with verbose for:
youtube-dl http://assets3.ign.com/videos/zencoder/2016/03/02/960/7d9b7ef1402046631b6e954a1a004d9c-1500000-1456932076.mp4 --verbose :

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://assets3.ign.com/videos/zencoder/2016/03/02/960/7d9b7ef1402046631b6e954a1a004d9c-1500000-1456932076.mp4', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Git HEAD: 0a9c4ec
[debug] Python version 2.7.10 - Darwin-15.0.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {}
[ign.com] 7d9b7ef1402046631b6e954a1a004d9c-1500000-1456932076.mp4: Downloading webpage

**Comment by rg3** [comment]
I believe it's not stuck. It may be downloading the actual video, which is 24 MB in size. It will probably try to interpret it as a webpage which to extract a video URL from. That will probably fail. In any case, if you have the final video URL, why use youtube-dl at all? curl or wget work fine.

**Comment by lucascharrierpulpix** [comment]
Actually the behavior was the same with the 'skip download' flag. But it seems to work now, may be it was due to the network on which I was. Well, thanks, I close the issue.
