### ISSUE TITLE
Can't download video from Metacafe

### ISSUE THREAD

**Issue by zettich** [rg3/youtube-dl#8973]
youtube-dl -v http://www.metacafe.com/watch/11419970/the-big-joker-painting/   
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.metacafe.com/watch/11419970/the-big-joker-painting/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.25
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
[debug] exe versions: ffmpeg 2.6.5, ffprobe 2.6.5, rtmpdump 2.4
[debug] Proxy map: {}
[metacafe] Retrieving disclaimer
[metacafe] Confirming age
[metacafe] 11419970: Downloading webpage
[metacafe] 11419970: Extracting information
ERROR: Unsupported video type; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/metacafe.py", line 218, in _real_extract
    raise ExtractorError('Unsupported video type')
ExtractorError: Unsupported video type; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by remitamine** [comment]
will be fixed in the next version.
