### ISSUE TITLE
API to get video's information

### ISSUE THREAD

**Issue by johnsmeeth** [rg3/youtube-dl#8987]
I am new to python. I want to get some information of video as title, size, url from my python code? How to? What API can i use? Please.
Many thanks

**Comment by sceext2** [comment]
Try `youtube-dl -j`

**Comment by yan12125** [comment]
Here's an example:
```Python
from __future__ import unicode_literals
import youtube_dl

ydl_opts = {}
with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    info_dict = ydl.extract_info(
        'http://www.youtube.com/watch?v=BaW_jenozKc', download=False)
    print(info_dict)
```

See https://github.com/rg3/youtube-dl#embedding-youtube-dl for more information.
