### ISSUE TITLE
Pluralsight cannot login - invalid username or password, even though are correct

### ISSUE THREAD

**Issue by fsacer** [rg3/youtube-dl#8994]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://app.pluralsight.com/library/courses/csharp-with
-jon-skeet/', u'--verbose', u'--username', u'PRIVATE', u'--password', u'PRIVATE']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2016.03.26
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] csharp-with-jon-skeet: Downloading course JSON
[pluralsight:course] csharp-with-jon-skeet: Downloading course data JSON
[download] Downloading playlist: Exploring C# 6 with Jon Skeet
[pluralsight:course] playlist Exploring C# 6 with Jon Skeet: Collected 45 video ids (
downloading 45 of them)
[download] Downloading video 1 of 45
[pluralsight] Downloading login page
[pluralsight] Logging in as fsacer
ERROR: Unable to login: Invalid user name or password
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 668, in extract_info
  File "youtube_dl\extractor\common.pyo", line 319, in extract
  File "youtube_dl\extractor\common.pyo", line 313, in initialize
  File "youtube_dl\extractor\pluralsight.pyo", line 54, in _real_initialize
  File "youtube_dl\extractor\pluralsight.pyo", line 89, in _login
ExtractorError: Unable to login: Invalid user name or password

'0' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dstftw** [comment]
You'll have to provide account credentials. I don't have an account currently.

**Comment by dstftw** [comment]
Authentication works fine for me with youtube-dl.
According to
>'0' is not recognized as an internal or external command, operable program or batch file.

I can assume your password contains an ampersand (namely it ends with `&0`) that [you neither escaped nor put the whole password in quotes](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).

**Comment by jnpwly** [comment]
I conversed with @dstftw, and, via the correct use of the correct credentials, confirmed that the latest version of YouTube-dl is indeed working correctly.

Note, if you have certain punctuation in your password, you may need to enclose it in quotes on the command line:
` --password "!FloobleFlooble!Flooble&Flooble"`

**Comment by fsacer** [comment]
That is indeed the case, this should be marked as solved, using qoutes fixed the isssue.

**Comment by chiragsoni2401** [comment]
Facing the same problem-**invalid username or password.** I have credentials that include '@' , '!' and '.' 
I am enclosing them in double quotes like this: "xxx@xxxx.XX"
