### ISSUE TITLE
Get video from Twitter suddenly stopped working.

### ISSUE THREAD

**Issue by luigifreitas** [rg3/youtube-dl#8996]
Before it was working with the same url but now is not.

`youtube-dl https://twitter.com/Filmdrunk/status/713801302971588609`
`[twitter] 713801302971588609: Downloading webpage
[twitter:card] 713801302971588609: Downloading webpage
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by drivfe** [comment]
Verbose output:

> C:\WINDOWS\system32>youtube-dl -v https://twitter.com/Filmdrunk/status/713801302971588609
> [debug] System config: []
> [debug] User config: [u'-o', u'C:/Users/****/yt-dls/%(title)s.%(ext)s', u'--no-mtime']
> [debug] Command-line args: [u'-v', u'https://twitter.com/Filmdrunk/status/713801302971588609']
> [debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
> [debug] youtube-dl version 2016.03.26
> [debug] Python version 2.7.10 - Windows-8-6.2.9200
> [debug] exe versions: ffmpeg N-75137-g2c1ec57, ffprobe N-75137-g2c1ec57
> [debug] Proxy map: {}
> [twitter] 713801302971588609: Downloading webpage
> [twitter:card] 713801302971588609: Downloading webpage
> ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "youtube_dl\YoutubeDL.pyo", line 668, in extract_info
>   File "youtube_dl\extractor\common.pyo", line 320, in extract
>   File "youtube_dl\extractor\twitter.pyo", line 161, in _real_extract
>   File "youtube_dl\extractor\common.pyo", line 839, in _sort_formats
> ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I believe the problem is [here](https://github.com/rg3/youtube-dl/blob/master/youtube_dl%2Fextractor%2Ftwitter.py#L96)

These links: http://twitter.com/i/videos/tweet/713801302971588609 do not have an iframe in them until you click play.

**Comment by yan12125** [comment]
Thanks for you all. New embedded Vine videos will be supported in the next version.
