### ISSUE TITLE
HTTP Error 500: Internal Server Error - Please Help

### ISSUE THREAD

**Issue by videoguy-canada** [rg3/youtube-dl#8997]
Can anybody fix this?  We've established it's not a geo-locking issue.  I'm willing to pay someone to fix it or figure it out. Here's the error

iMac2014:~ imac2014$ youtube-dl http://www.vevo.com/watch/USRV81600142
[Vevo] USRV81600142: Downloading video info
ERROR: Unable to download info: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
iMac2014:~ imac2014$ youtube-dl http://www.vevo.com/watch/USRV81600142 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.vevo.com/watch/USRV81600142', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.18
[debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Vevo] USRV81600142: Downloading video info
ERROR: Unable to download info: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 365, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
**Stop** duplicating issues. This is already fixed.

**Comment by videoguy-canada** [comment]
It is?   Where can I download the update?

**Comment by videoguy-canada** [comment]
Where can I download the update?

**Comment by dstftw** [comment]
From git master.

**Comment by videoguy-canada** [comment]
I’m new to this.  What is git master

 

Do you have an address?

Mark

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#developer-instructions

**Comment by videoguy-canada** [comment]
I need a binary cause I don’t  know how to compile.  I’m not a programmer

 

Thanks

**Comment by dstftw** [comment]
Then wait for next release. You don't need to compile anything though.

**Comment by videoguy-canada** [comment]
I updated to the latest, here's the error

**youtube-dl is up-to-date (2016.03.26)**

 youtube-dl --verbose http://www.vevo.com/watch/USSM21600522
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.vevo.com/watch/USSM21600522']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.26
[debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Vevo] USSM21600522: Downloading video info
ERROR: Unable to download info: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 365, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1929, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by dstftw** [comment]
You did not. It's not yet released as binary.

**Comment by videoguy-canada** [comment]
I dunno, I updated and it's not working.  Anything else I can do?

**Comment by dstftw** [comment]
>wait for next release

**Comment by videoguy-canada** [comment]
Do you know when that will be?  Is there a way to make this one work?  I'd rather not wait if I can make this one work.

Thanks

**Comment by dstftw** [comment]
I've already provided you will all the required info.

**Comment by videoguy-canada** [comment]
I've downloaded the new version using the -U

Shouldn't it just work now with the new link, or is there more to do?

**Comment by dstftw** [comment]
No, it's not. New version is **not yet released as binary**. I've already mentioned that.

**Comment by videoguy-canada** [comment]
Ok, so with the version I have, just wait and try it later?

**Comment by videoguy-canada** [comment]
I use it on terminal on mac.  Is there another version outside of the terminal version that I can use?

**Comment by phihag** [comment]
@videoguy-canada You are using more than a fair share of our support capacity without contributing anything yourself. Please **stop that** or we will have to block you from this support system. In particular, **never** open up duplicate issues (i.e. same issue content without any updates).

I believe your problem has been fixed in the just-released youtube-dl 2016.03.27, just like @dstftw said. See [our FAQ](https://yt-dl.org/update) if you have trouble updating.

**Comment by videoguy-canada** [comment]
No problem, my apologizes.  I did some reading and downloaded the windows version and it’s working there

 

Thank you for all your help

 

Appreciate it
