### ISSUE TITLE
Unable to download some IMDb's videos...

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#9000]
For an example with http://www.imdb.com/video/screenplay/vi2809377049 :

$ youtube-dl -v http://www.imdb.com/video/screenplay/vi2809377049
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.imdb.com/video/screenplay/vi2809377049']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.26
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: ffmpeg 2.8.6-1, ffprobe 2.8.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vi2809377049: Requesting header
WARNING: Could not send HEAD request to http://www.imdb.com/video/screenplay/vi2809377049: HTTP Error 405: Method Not Allowed
[generic] vi2809377049: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] vi2809377049: Extracting information
ERROR: Unsupported URL: http://www.imdb.com/video/screenplay/vi2809377049
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 668, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 320, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2003, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.imdb.com/video/screenplay/vi2809377049

Thank you in advance. :)

**Comment by antdude** [comment]
More:

http://www.imdb.com/video/screenplay/vi162791705
http://www.imdb.com/video/screenplay/vi397672729
http://www.imdb.com/video/screenplay/vi146014489


$ youtube-dl -v http://www.imdb.com/video/screenplay/vi162791705
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.imdb.com/video/screenplay/vi162791705']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.01
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.4
[debug] exe versions: ffmpeg 2.8.6-1, ffprobe 2.8.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] vi162791705: Requesting header
WARNING: Could not send HEAD request to http://www.imdb.com/video/screenplay/vi162791705: HTTP Error 405: Method Not Allowed
[generic] vi162791705: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] vi162791705: Extracting information
ERROR: Unsupported URL: http://www.imdb.com/video/screenplay/vi162791705
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 323, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2012, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.imdb.com/video/screenplay/vi162791705

**Comment by antdude** [comment]
http://www.imdb.com/video/screenplay/vi2646715417
http://www.imdb.com/video/screenplay/vi2663492633

**Comment by dstftw** [comment]
Fixed in f196508f7b872963d13bcff94c0105d743322f71.
