### ISSUE TITLE
Download facebook photo album?

### ISSUE THREAD

**Issue by johnsmeeth** [rg3/youtube-dl#9002]
Can i download a facebook photo album?

**Comment by Anthonyjmartin** [comment]
you can use this [https://chrome.google.com/webstore/detail/download-fb-album-mod/cgjnhhjpfcdhbhlcmmjppicjmgfkppok?utm_source=chrome-app-launcher-info-dialog](url)

**Comment by johnsmeeth** [comment]
@Anthonyjmartin your link broken (404)

**Comment by Anthonyjmartin** [comment]
Thats strange, well you can still search the chrome store for facebook photo download and you will find one.

**Comment by yan12125** [comment]
Currently youtube-dl's support policy does not include static pictures.

Related: #9337
