### ISSUE TITLE
Youtube-dl Geo-Locked

### ISSUE THREAD

**Issue by videoguy-canada** [rg3/youtube-dl#9004]
You guys, thanks for posting the update.  Got this geo-locked message

youtube-dl --verbose http://www.vevo.com/watch/tasha-holiday/Just-The-Way-You-Like-It/USUV70602102
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.vevo.com/watch/tasha-holiday/Just-The-Way-You-Like-It/USUV70602102']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Vevo] USUV70602102: Downloading video info
ERROR: Vevo said: People who live where you live aren't allowed to watch this video. Not because we don't luv ya, but because the owners have some restrictions. The good news, is there are tens of thousands of other videos to choose from...
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 321, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vevo.py", line 175, in _real_extract
    self.IE_NAME, response['statusMessage']), expected=True)
ExtractorError: Vevo said: People who live where you live aren't allowed to watch this video. Not because we don't luv ya, but because the owners have some restrictions. The good news, is there are tens of thousands of other videos to choose from...

**Comment by dstftw** [comment]
1. It's geo restricted. Can you watch it in browser?
2. Post the output of `youtube-dl -v --call-home --dump-pages http://www.vevo.com/watch/tasha-holiday/Just-The-Way-You-Like-It/USUV70602102`.

**Comment by videoguy-canada** [comment]
Yes I can...using DNSfor me, I can view, but not download.  I'm in Canada, using DNSforme, logged into U.K.  Can view but not download

youtube-dl -v --call-home --dump-pages http://www.vevo.com/watch/tasha-holiday/Just-The-Way-You-Like-It/USUV70602102
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--call-home', u'--dump-pages', u'http://www.vevo.com/watch/tasha-holiday/Just-The-Way-You-Like-It/USUV70602102']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.9 - Darwin-14.3.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Public IP address: 99.245.180.214
[Vevo] USUV70602102: Downloading video info
[Vevo] Dumping request to http://api.vevo.com/VideoService/AuthenticateVideo?isrc=USUV70602102
eyJ2aWRlbyI6bnVsbCwiZXJyb3JJbmZvIjp7Inl0aWQiOm51bGx9LCJpc0FwcHJvdmVkIjpmYWxzZSwiaXNNb25ldGl6YWJsZSI6ZmFsc2UsInN0YXR1c01lc3NhZ2UiOiJQZW9wbGUgd2hvIGxpdmUgd2hlcmUgeW91IGxpdmUgYXJlblx1MDAyN3QgYWxsb3dlZCB0byB3YXRjaCB0aGlzIHZpZGVvLiBOb3QgYmVjYXVzZSB3ZSBkb25cdTAwMjd0IGx1diB5YSwgYnV0IGJlY2F1c2UgdGhlIG93bmVycyBoYXZlIHNvbWUgcmVzdHJpY3Rpb25zLiBUaGUgZ29vZCBuZXdzLCBpcyB0aGVyZSBhcmUgdGVucyBvZiB0aG91c2FuZHMgb2Ygb3RoZXIgdmlkZW9zIHRvIGNob29zZSBmcm9tLi4uIiwic3RhdHVzRGV0YWlscyI6bnVsbCwic3RhdHVzQ29kZSI6NTAxLCJjb3VudHJ5Q29kZSI6IkNBIiwibGFuZ3VhZ2VDb2RlIjoiZW4tVVMifQ==
ERROR: Vevo said: People who live where you live aren't allowed to watch this video. Not because we don't luv ya, but because the owners have some restrictions. The good news, is there are tens of thousands of other videos to choose from...
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 321, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/vevo.py", line 175, in _real_extract
    self.IE_NAME, response['statusMessage']), expected=True)
ExtractorError: Vevo said: People who live where you live aren't allowed to watch this video. Not because we don't luv ya, but because the owners have some restrictions. The good news, is there are tens of thousands of other videos to choose from...

**Comment by dstftw** [comment]
Can you watch it in browser **without any kind of unblocking services**?

**Comment by videoguy-canada** [comment]
On youtube yes, Vevo no.  Not available for Canada on Vevo Canada, only available on Vevo U.K.

**Comment by dstftw** [comment]
Then it's not youtube-dl problem.
dns4me is probably does not spoof api.vevo.com IP for your.

**Comment by videoguy-canada** [comment]
The old version used to work, as long as I could view the video, I could grab it.  

No problem though, I appreciate your time

**Comment by dstftw** [comment]
What's the output of `nslookup www.vevo.com` and `nslookup api.vevo.com`?

**Comment by videoguy-canada** [comment]
nslookup www.vevo.com - Server:		104.152.208.88
Address:	104.152.208.88#53

Non-authoritative answer:
Name:	www.vevo.com
Address: 104.128.227.25

---------------------------------------
nslookup videoplayer.vevo.com
Server:		104.152.208.88
Address:	104.152.208.88#53

Non-authoritative answer:
Name:	videoplayer.vevo.com
Address: 104.128.227.76

---------------------------------------
nslookup cache.vevo.com
Server:		104.152.208.88
Address:	104.152.208.88#53

Non-authoritative answer:
cache.vevo.com	canonical name = cdn.vevo.com.edgesuite.net.
cdn.vevo.com.edgesuite.net	canonical name = a1250.g.akamai.net.
Name:	a1250.g.akamai.net
Address: 63.130.77.139
Name:	a1250.g.akamai.net
Address: 63.130.77.104

---------------------------------------
nslookup api.vevo.com
Server:		104.152.208.88
Address:	104.152.208.88#53

Non-authoritative answer:
api.vevo.com	canonical name = wildcard.vevo.com.edgekey.net.
wildcard.vevo.com.edgekey.net	canonical name = e2470.b.akamaiedge.net.
Name:	e2470.b.akamaiedge.net
Address: 23.76.122.44

**Comment by dstftw** [comment]
Yes, looks like dns4me does not spoof api.vevo.com. You can report this to them to get youtube-dl working in your case.

**Comment by videoguy-canada** [comment]
Thank you, will do
