### ISSUE TITLE
Error when trying to download YouTube-videos (SinusBot)

### ISSUE THREAD

**Issue by Hallol** [rg3/youtube-dl#9010]
When inserting a youtube-link to download in SinusBot, this message apperars:

> Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

I already have been looking everywhere, also here, but there were some commands I didn't know where to input, and since my english isn't the best, I had trouble reading the other comments.
I would be grateful if someone could explain the solution so that also a "noob" like me understands it! Thanks.

**Comment by dstftw** [comment]
Remove expired certificates: https://github.com/rg3/youtube-dl/issues/7309#issuecomment-172354527.
