### ISSUE TITLE
Cannot download subtitles in Raspberry pi version

### ISSUE THREAD

**Issue by edo44** [rg3/youtube-dl#9012]
Probably is due to the outdated version we still have in the repository, but is there a way to bypass this 404 error?

![mstsc_2016-03-28_15-44-47](https://cloud.githubusercontent.com/assets/13797216/14079399/b000985a-f4fd-11e5-885c-ff2841139c04.png)

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by edo44** [comment]
But that's the last version available in the repository...

**Comment by phihag** [comment]
@edo44 Have you actually read the FAQ entry @dstftw linked to? It explains in detail the situation you are in and possible options.

**Comment by edo44** [comment]
@phihag What? Like compiling everything from source on my own? Isn't there another way?

**Comment by dstftw** [comment]
@edo44 bother to read it already. There is even no single word on compiling.

**Comment by edo44** [comment]
Sorry, I didn't ctrl+f enough.

**Comment by dstftw** [comment]
Jeez. Ctrl+f what? I gave you exact link where to start reading.

**Comment by edo44** [comment]
@dstftw I didn't open it of course.
