### ISSUE TITLE
Skip already downloaded files; resume progress

### ISSUE THREAD

**Issue by nexxai** [rg3/youtube-dl#9016]
I don't know how difficult it would be to do this, but here goes...

I'm attempting to download all of the videos from a particular Vimeo channel.  I hit their internal rate limiter and so youtube-dl quit.  After a day or so, I went to run the tool again, but instead of picking up where it left off, it started from the beginning again, downloading videos it had already downloaded.

Is there a way for it to check if a file already exists in the folder with that name and skip that particular download if it does?

If it makes a difference, I'm using the latest Windows client (2016.03.27).

**Comment by dstftw** [comment]
It does by default.
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.
