### ISSUE TITLE
Trouble getting specific videos to download

### ISSUE THREAD

**Issue by keybounce** [rg3/youtube-dl#9020]
I am running into speed issues when downloading from Daily motion (takes more than 22 minutes to download a 22 minute video).

My attempt to deal with this? Download multiple files at once, in the background.
To do that, I tried to get the URL's from the individual files.

```
# Fetch three episode URL's as a test
keybounceMBP:Mlp michael$ youtube-dl --playlist-end 3 -g http://www.dailymotion.com/user/MLPFiMVideos/1
https://www.dailymotion.com/cdn/H264-848x480/video/x4084fl.mp4?auth=1459390611-2562-p541qh0n-87f5e7c75849dad5bb17738787d583f7
https://www.dailymotion.com/cdn/H264-848x480/video/x407ywo.mp4?auth=1459390619-2562-p58jnguq-cb7d9ec8c4093d5897f6dd6fafe0216b
https://www.dailymotion.com/cdn/H264-848x480/video/x3gfaow.mp4?auth=1459390627-2562-w92bt2zy-22a8bcf37a4eb65e60b2718212ba6c28

# Try to grab the first one
keybounceMBP:Mlp michael$ youtube-dl 'https://www.dailymotion.com/cdn/H264-848x480/video/x4084fl.mp4?auth=1459390611-2562-p541qh0n-87f5e7c75849dad5bb17738787d583f7'
[dailymotion:user] cdn: Downloading webpage
[download] Downloading playlist: cdn
[dailymotion:user] cdn: Downloading page 1
[dailymotion:user] playlist cdn: Downloading 8 videos
[download] Downloading video 1 of 8
[dailymotion] x40g88f: Downloading webpage
[dailymotion] x40g88f: Downloading m3u8 information
^C
ERROR: Interrupted by user
keybounceMBP:Mlp michael$ 
```

Note that even though it was given a single video URL, with the authorization cookie, it winds up downloading a generic page's playlist.

The goal was to do something like
youtube-dl -g | xargs -1 youtube-dl {} \& 
to download each file in the background, at the same time.

(Since that did not work, the next choice, obviously, is to let it run overnight :-).

**Comment by dstftw** [comment]
It's not intended to be used for final URLs this way - use regular downloader on the final URL.
