### ISSUE TITLE
youtube-dl (2016.03.27): Vimeo not downloading, HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by donglaiw** [rg3/youtube-dl#9026]
Dear youtube-dl:

I can download the original video from the vimeo website, but from youtube-dl I get the following errors.

Thanks for your help in advance !
D

A. verbose:
**`./youtube-dl -f Original https://vimeo.com/115617040 --verbose`**
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'Original', u'https://vimeo.com/115617040', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.11 - Linux-3.13.0-62-generic-x86_64-with-debian-jessie-sid
[debug] exe versions: ffmpeg N-63893-gc69defd, ffprobe N-63893-gc69defd
[debug] Proxy map: {}
[vimeo] 115617040: Downloading webpage
[vimeo] 115617040: Extracting information
[vimeo] 115617040: Downloading webpage
[vimeo] 115617040: Downloading JSON metadata
[vimeo] 115617040: Checking Original video URL
[vimeo] 115617040: Original video URL is invalid, skipping
[vimeo] 115617040: Downloading m3u8 information
ERROR: requested format not available
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 680, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 725, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1362, in process_video_result
    expected=True)
ExtractorError: requested format not available

B. print-traffic: (search for: "403 Forbidden") [[link found by youtube-dl]](https://vimeo.com//115617040/download?t=1459256316&v=321297610&s=c1ee93c89277eb2d53bbaa5aefeecebf7d3d6bf125b584280033def7a173223c)

`./youtube-dl -f Original https://vimeo.com/115617040 --print-traffic`
[vimeo] 115617040: Downloading webpage
send: u'GET /115617040 HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: vimeo.com\r\nReferer: https://vimeo.com/115617040\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Content-Type: text/html; charset=UTF-8
header: Expires: Tue, 29 Mar 2016 14:58:35 GMT
header: X-UA-Compatible: IE=edge
header: X-XSS-Protection: 1; mode=block
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: sameorigin
header: Strict-Transport-Security: max-age=15120000; includeSubDomains; preload
header: Content-Security-Policy-Report-Only: default-src https: data: blob: 'unsafe-inline' 'unsafe-eval'; report-uri /_csp
header: Content-Encoding: gzip
header: Via: 1.1 varnish
header: Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
header: X-Varnish-Cache: 1
header: X-VServer: dfvimeowebproxy1
header: Via: 1.1 varnish
header: Fastly-Debug-Digest: 36cbe8941d3ddd5420f7499d39af1fa186f776a099e6b09bc67c866bb96c8126
header: Content-Length: 23500
header: Accept-Ranges: bytes
header: Date: Tue, 29 Mar 2016 13:26:10 GMT
header: Via: 1.1 varnish
header: Age: 0
header: Connection: close
header: X-Served-By: cache-iad2126-IAD, cache-jfk1040-JFK
header: X-Cache: MISS, MISS
header: X-Cache-Hits: 0, 0
header: X-Timer: S1459257970.689249,VS0,VE49
header: Vary: User-Agent,Accept-Encoding
[vimeo] 115617040: Extracting information
[vimeo] 115617040: Downloading webpage
send: u'GET /video/115617040/config?autoplay=0&byline=0&collections=1&context=Vimeo%5CController%5CClipController.main_beta&default_to_hd=1&outro=beginning&portrait=0&title=0&watch_trailer=0&s=3643f706590dc1a6ff066f4747cd9e407c585c42_1459357115 HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: player.vimeo.com\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Content-Type: application/json
header: X-Xss-Protection: 1; mode=block
header: X-Content-Type-Options: nosniff
header: Content-Encoding: gzip
header: Strict-Transport-Security: max-age=15120000; includeSubDomains; preload
header: P3p: CP="This is not a P3P policy! See https://vimeo.com/privacy"
header: Expires: Wed, 30 03 2016 12:58:35 GMT
header: Via: 1.1 varnish
header: Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
header: X-Varnish-Cache: 1
header: X-VServer: dfvimeoplayproxy6
header: Via: 1.1 varnish
header: Fastly-Debug-Digest: 0bb305eb405b3dbd53a4270b640919b7c4fa566f9f53ea6582a0ba0a0e4e0db3
header: Content-Length: 2938
header: Accept-Ranges: bytes
header: Date: Tue, 29 Mar 2016 13:26:10 GMT
header: Via: 1.1 varnish
header: Age: 0
header: Connection: close
header: X-Served-By: cache-iad2139-IAD, cache-jfk1030-JFK
header: X-Cache: MISS, MISS
header: X-Cache-Hits: 0, 0
header: Vary: Origin, Accept-Encoding
[vimeo] 115617040: Downloading JSON metadata
send: u'GET /115617040?action=load_download_config HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: vimeo.com\r\nX-Requested-With: XMLHttpRequest\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Content-Type: application/json; charset=UTF-8
header: Expires: Wed, 30 Mar 2016 12:58:36 GMT
header: X-UA-Compatible: IE=edge
header: X-XSS-Protection: 1; mode=block
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: sameorigin
header: Strict-Transport-Security: max-age=15120000; includeSubDomains; preload
header: Content-Security-Policy-Report-Only: default-src https: data: blob: 'unsafe-inline' 'unsafe-eval'; report-uri /_csp
header: Content-Encoding: gzip
header: Via: 1.1 varnish
header: Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
header: X-Varnish-Cache: 1
header: X-VServer: dfvimeowebproxy1
header: Via: 1.1 varnish
header: Fastly-Debug-Digest: 5631038576ed0d3227f21d0fbe9732ee918ceb6c53468718c4bdf304755f5530
header: Content-Length: 488
header: Accept-Ranges: bytes
header: Date: Tue, 29 Mar 2016 13:26:10 GMT
header: Via: 1.1 varnish
header: Age: 0
header: Connection: close
header: X-Served-By: cache-iad2146-IAD, cache-jfk1045-JFK
header: X-Cache: MISS, MISS
header: X-Cache-Hits: 0, 0
header: X-Timer: S1459257970.864093,VS0,VE8
header: Vary: User-Agent,Accept-Encoding
[vimeo] 115617040: Checking Original video URL
send: u'GET /115617040/download?t=1459256316&v=321297610&s=c1ee93c89277eb2d53bbaa5aefeecebf7d3d6bf125b584280033def7a173223c HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: vimeo.com\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Server: nginx
header: Content-Type: text/html; charset=UTF-8
header: Expires: Tue, 29 Mar 2016 01:26:10 GMT
header: X-Frame-Options: sameorigin
header: Set-Cookie: vuid=2103976532.360187291; expires=Fri, 27-Mar-2026 13:26:10 GMT; path=/; domain=.vimeo.com; secure
header: Content-Encoding: gzip
header: Via: 1.1 varnish
header: Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
header: X-Varnish-Cache: 0
header: X-VServer: dfvimeowebproxy5
header: Via: 1.1 varnish
header: Fastly-Debug-Digest: 84f1d7020b1abe3f9cd908fc59cdf37e79da0149a89be2ccb379bb798c676d6a
header: Content-Length: 11042
header: Accept-Ranges: bytes
header: Date: Tue, 29 Mar 2016 13:26:11 GMT
header: Via: 1.1 varnish
header: Connection: close
header: X-Served-By: cache-iad2136-IAD, cache-jfk1046-JFK
header: X-Cache: MISS, MISS
header: X-Cache-Hits: 0, 0
header: X-Timer: S1459257970.906222,VS0,VE94
header: Vary: Accept-Encoding
[vimeo] 115617040: Original video URL is invalid, skipping
[vimeo] 115617040: Downloading m3u8 information
send: u'GET /1459265170-cff31b832a49e1e095cadd27f88de9568931e48b/01/3123/4/115617040/master.m3u8 HTTP/1.1\r\nAccept-Language: en-us,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nConnection: close\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nHost: 01-lvl3-hls.vimeocdn.com\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Tue, 29 Mar 2016 13:26:11 GMT
header: Content-Type: application/x-mpegURL
header: Content-Length: 225
header: Connection: close
header: Cache-Control: no-store
header: Pragma: no-cache
header: Accept-Ranges: bytes
header: Server: nginx
header: Vary: Accept-Encoding
header: Access-Control-Allow-Headers: *
header: Access-Control-Allow-Methods: GET, HEAD, OPTIONS
header: Access-Control-Allow-Origin: *
header: Access-Control-Expose-Headers: *
header: Content-Security-Policy: default-src 'self'; script-src 'self' https://f.vimeocdn.com; style-src 'self' https://f.vimeocdn.com; img-src 'self' https://i.vimeocdn.com https://f.vimeocdn.com
header: Fastly-Debug-Digest: 64a542a18b0f50cdeabf34cb365a61439af298a1a3929e0b4ca1f57a39116c16
header: P3P: CP="This is not a P3P policy! See https://vimeo.com/privacy"
header: Strict-Transport-Security: max-age=15120000; includeSubDomains; preload
header: X-Cache: MISS, MISS
header: X-Cache-Hits: 0, 0
header: X-Content-Type-Options: nosniff
header: X-Served-By: cache-iad2135-IAD, cache-jfk1044-JFK
header: X-Varnish-Cache: 0
header: X-VServer: dfvimeoplayproxy5
header: X-XSS-Protection: 1; mode=block
ERROR: requested format not available

**Comment by Hrxn** [comment]
Tried it without `-f Original`?

**Comment by donglaiw** [comment]
1. it works without -f Original, but I do need the original files

2. it finally works after I provide vimeo account infomation: with -u, -p
