### ISSUE TITLE
[youtube][bug][2016.03.27] bestvideo/bestaudio can vary on same link

### ISSUE THREAD

**Issue by dendon** [rg3/youtube-dl#9031]
Hey.

I recently noticed that a command like this:
youtube-dl -f 'bestvideo+bestaudio'
can vary on what formats get downloaded on the same link.

I can't provide any logs since it seems to be random when it occurs based on which dash manifest returned an error.

My guess is, it's related to this code segment.
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1629-L1664

The version is 2016.03.27.

**Comment by Hrxn** [comment]
FYI, you can do something like this:
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1629-L1664

It's a lot easier..

**Comment by dendon** [comment]
Didn't knew that, thanks.
Changed it.

**Comment by dstftw** [comment]
It may vary. YouTube doesn't roll out all the formats immediately when the video appears but instead formats appear as they format encoding finishes or some other criteria.

**Comment by dendon** [comment]
I might should have added, that I wasn't talking about new videos.
This problem occurred with videos which were uploaded more than a week ago.

**Comment by Hrxn** [comment]
It could be..

Anyway, if there is anything YouTube modifies when processing requests, it's on the server-side, I don't think that any script or tool or program running on the client can do something about it.
