### ISSUE TITLE
Cant download api&

### ISSUE THREAD

**Issue by klkuznetsov** [rg3/youtube-dl#9032]
klk@Microserver:/data/inp/Download$ youtube-dl -user xxxxx@gmail.com  -password +++++  -f 22 https://youtu.be/Ezc4HdLGxg4 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-user', 'xxxxx', '-password', 'xxxxx', '-f', '22', 'https://youtu.be/Ezc4HdLGxg4', '--verbose']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.19.0-28-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[youtube:search] query "xxxxxx@gmail.com": Downloading page 1
ERROR: Unable to download API page: HTTP Error 410: Gone; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 191, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1157, in urlopen
    return self._opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by phihag** [comment]
The options `--username` and `--password` must be preceded by double, not single dashes (also mind the `name` in `--username`). youtube-dl will then also then not show the password in the output. You just posted your password to the internet, please change it.

**Comment by dstftw** [comment]
You are also using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by klkuznetsov** [comment]
Updating helps me. Thanks
