### ISSUE TITLE
http://www.kuwo.cn

### ISSUE THREAD

**Issue by jiangjiangflies** [rg3/youtube-dl#9033]
Can you support this website？
http://www.kuwo.cn/yinyue/6340467?catalog=yueku2016

**Comment by dstftw** [comment]
Completely fill new issue template.

**Comment by yan12125** [comment]
Recent changes in kuwo.cn breaks youtube-dl.

**Comment by yan12125** [comment]
Kuwo.cn support is fixed and will be available in the next version.
