### ISSUE TITLE
Crunchyroll KeyError: u'url'

### ISSUE THREAD

**Issue by MartinWeingaertner** [rg3/youtube-dl#9034]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.03.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.exe "http://www.crunchyroll.com/myriad-colors-phantom-world/episode-13-the-eternal-phantom-world-691713" -u user -p password --write-sub --sub-lang enUS -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.crunchyroll.com/myriad-colors-phantom-world/episode-13-the-eternal-phantom-world-691713', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--write-sub', u'--sub-lang', u'enUS', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-76479-gc878082, ffprobe N-76479-gc878082, rtmpdump 2.4
[debug] Proxy map: {}
[Crunchyroll] Logging in
[Crunchyroll] 691713: Downloading webpage
[Crunchyroll] 691713: Downloading media info
[Crunchyroll] 691713: Downloading media info for 360p
[Crunchyroll] 691713: Downloading media info for 480p
[Crunchyroll] 691713: Downloading media info for 720p
[Crunchyroll] 691713: Downloading media info for 1080p
[Crunchyroll] 691713: Downloading subtitles for English (US)
[Crunchyroll] 691713: Downloading subtitles for Español
[Crunchyroll] 691713: Downloading subtitles for Español (España)
[Crunchyroll] 691713: Downloading subtitles for Français (France)
[Crunchyroll] 691713: Downloading subtitles for Português (Brasil)
[Crunchyroll] 691713: Downloading subtitles for ???????
[Crunchyroll] 691713: Downloading subtitles for Italiano
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 419, in main
  File "youtube_dl\__init__.pyo", line 409, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1724, in download
  File "youtube_dl\YoutubeDL.pyo", line 680, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 725, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1268, in process_video_result
KeyError: u'url'
```
---

### Description of your *issue*, suggested solution and other information

Above error occurs in version 2016.03.27 when trying to download ANY video on Crunchyroll (at least with the 5 or so I tested), not only the one example I have provided.
Please note that downloading works fine in version 2016.03.18, which is the one I had before I updated today. So this bug seems to have been introduced at some point between the 18th and the 27th.

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.
