### ISSUE TITLE
Timelines in fetched Subtitles are overlapping each other!

### ISSUE THREAD

**Issue by perpi** [rg3/youtube-dl#9038]
`youtube-dl --write-sub --write-auto-sub --sub-lang en youtube.com/watch?v=OVHE6C3XQy0`

The below snippet is a part of the subtitle of above link. As you see there' may duplicated lines. The main problem is that they overlap each other on boundaries time! It happens in both vtt and srt versions.

    00:00:01.000 --> 00:00:01.930 align:start position:0%
    
    
    <c.colorE5E5E5>greetings</c><c.colorCCCCCC><00:00:01.329><c> and</c><00:00:01.459><c> salutations</c><00:00:01.490><c> thanks</c></c>
    
    00:00:01.930 --> 00:00:02.330 align:start position:0%
 
    <c.colorE5E5E5>greetings</c><c.colorCCCCCC> and salutations thanks
    </c>
    
    00:00:02.330 --> 00:00:03.009 align:start position:0%
    
    <c.colorE5E5E5>greetings</c><c.colorCCCCCC> and salutations thanks</c>
    for<00:00:02.419><c> clicking</c><00:00:02.570><c> on</c><00:00:02.790><c> the</c><00:00:02.870><c> video</c><00:00:02.909><c> today</c>
    
    00:00:03.009 --> 00:00:03.409 align:start position:0%
    <c.colorE5E5E5>greetings</c><c.colorCCCCCC> and salutations thanks</c>
    for clicking on the video today
     
    
    00:00:03.409 --> 00:00:04.250 align:start position:0%
    <c.colorE5E5E5>greetings</c><c.colorCCCCCC> and salutations thanks</c>
    for clicking on the video today
    we're<00:00:03.679><c> going</c><00:00:03.709><c> to</c><00:00:03.870><c> take</c><00:00:03.990><c> a</c><00:00:04.130><c> look</c><00:00:04.250><c> at</c>
       
    00:00:04.250 --> 00:00:04.400 align:start position:0%
    for clicking on the video today
    we're going to take a look at
     
    
    00:00:04.400 --> 00:00:04.620 align:start position:0%
    for clicking on the video today
    we're going to take a look at
    the
    
    00:00:04.620 --> 00:00:05.020 align:start position:0%
    we're going to take a look at
    the
    
    
    00:00:05.020 --> 00:00:08.080 align:start position:0%
    we're going to take a look at
    the
    unity<c.colorCCCCCC><00:00:06.129><c> desktop</c></c><00:00:06.980><c> in</c><c.colorE5E5E5><00:00:07.080><c> a</c></c><c.colorCCCCCC><00:00:07.129><c> boon</c></c><c.colorE5E5E5><00:00:07.410><c> to</c></c><00:00:07.910><c> and</c>

    00:00:08.080 --> 00:00:08.480 align:start position:0%
    the
    unity<c.colorCCCCCC> desktop</c> in<c.colorE5E5E5> a</c><c.colorCCCCCC> boon</c><c.colorE5E5E5> to</c> and
    
    
    00:00:08.480 --> 00:00:09.500 align:start position:0%
    the
    unity<c.colorCCCCCC> desktop</c> in<c.colorE5E5E5> a</c><c.colorCCCCCC> boon</c><c.colorE5E5E5> to</c> and
    talk<00:00:08.639><c> about</c><00:00:08.760><c> some</c><c.colorCCCCCC><00:00:08.990><c> things</c><00:00:09.179><c> that</c><00:00:09.500><c> you</c></c>

As you see, each line is repeated twice and also is combined with the next line somehow!

---

## Please follow the guide below

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.03.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones #8869

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

**Comment by jaimeMF** [comment]
Unfortunately that's what YouTube provides, so it's a problem on their side. The ttml version doesn't seem to have this problem, you can use `--sub-format ttml --convert-subs vtt` to get the correct vtt file (note that the converter is not perfect, it may have some problem).

**Comment by ryancwalsh** [comment]
YouTube just exported captions with overlapping timings for me, too. I wonder why that would ever happen.

**Comment by Hitaro** [comment]
> `--sub-format ttml --convert-subs vtt`

This doesn't work anymore! Any other solution?

**Comment by saurabhshri** [comment]
@Hitaro did you find any other solution?

**Comment by nickaein** [comment]
@saurabhshri Downloading subtitle with **vtt** format fixed it for me.

**Comment by thisisramzi** [comment]
This fixed my subs for me: I edited the SRT file with overlapping timings. Uploaded it to YouTube and saved. Then went back to edit the subtitles on the video. So I clicked Edit. 

Got the questions pop-up if I want to overwrite. Clicked "overwrite".  

And then clicked "Publish edits". Now
![subs 0](https://user-images.githubusercontent.com/33258413/32228670-296f2604-be4f-11e7-8384-e5b57a0e281c.JPG)
![subs 1](https://user-images.githubusercontent.com/33258413/32228671-2985eb14-be4f-11e7-9c59-d24623199829.JPG)
![subs 3](https://user-images.githubusercontent.com/33258413/32228672-29a05954-be4f-11e7-981d-05129c348995.JPG)


 my subs are not showing  in the roll-up karaoke format.

**Comment by perpi** [comment]
> @thisisramzi wrote: This fixed my subs for me: I edited the SRT file with overlapping timings.

How did you edit it?

**Comment by thisisramzi** [comment]
Hi, I meant I edited the original .srt file, generated by YouTube in textedit or notepad, to adapt some mistakes.

**Comment by Hitaro** [comment]
@saurabhshri, nope. It downloads a messy unusable file generated by Youtube! The converter (`ttml --> vtt`) does not work unfortunately. I tried  for [this video](youtube.com/watch?v=gCAxGTt7nLg&index=1&list=PL9peWTxCcrBJ5lClC7-9wV0_AYF956Bqo) and let us now your result for fetching the subtitle.

**Comment by perpi** [comment]
A --> B
    C --> D
    E --> F
    G --> H

A solution can be swapping B and C, D and E, F and G. As it has been implemented by [downsub.com](http://downsub.com/?url=youtube.com%2Fwatch%3Fv%3DgCAxGTt7nLg) and [lilsubs.com](http://lilsubs.com).

**Comment by Geniusssmit** [comment]
This issue is still present. Is there a way around it? Like some settings in .conf file?

**Comment by dirkf** [comment]
Is [the ttml work-around](https://github.com/ytdl-org/youtube-dl/issues/9038#issuecomment-203955566) still valid?
