### ISSUE TITLE
Downloaded .flv file has jumping audio

### ISSUE THREAD

**Issue by Danyadd** [rg3/youtube-dl#9042]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.03.27*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.03.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.exe -v "http://www.rte.ie/player/it/show/centenary-30003958/10552342/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.rte.ie/player/it/show/centenary-30003958/10552342/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[rte] 10552342: Downloading webpage
[rte] 10552342: Downloading JSON metadata
[rte] 10552342: Downloading f4m manifest
[rte] 10552342: Downloading f4m manifest
[rte] 10552342: Downloading f4m manifest
[rte] 10552342: Downloading f4m manifest
[debug] Invoking downloader on u'http://cdn.rasset.ie/hds-vod/2016/0328/20160328_rteone-centenary_cl10552342_10552380_260_drm_/20160328_rteone-centenary_cl10552342_10552380_260_drm__2048k.mp
[f4m] Downloading f4m manifest
[f4m] Total fragments: 1268
[download] Destination: Watch Centenary  online-10552342.flv
[download] 100% of 1.23GiB in 17:33
<end of log>
```

---

---

### Description of your *issue*, suggested solution and other information

youtube-dl.exe "http://www.rte.ie/player/it/show/centenary-30003958/10552342/"

The resulting file .flv has an issue with audio.
The audio is perfecly fine on the website.
But if you play the .flv file using VLC the audio is jumping more or less every 2 seconds.
This issue is everywhere in the downloaded file.
I tried downloading all three versions of the file using -f 0-0 then -f 0-1 then -f 0-2 but the issue is still there.
Try for example to play at 11:30 you will notice that the audio is not constant. It is more evident when there is a high pitch instrument playing.

**Comment by yan12125** [comment]
Confirmed with VLC 2.2.2, while the same file plays well (no jumps in the audio stream) in mpv 0.16.0. You may want to report it to the VLC team.
