### ISSUE TITLE
udemy not downloading all lectures

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#9043]
Hi Sir 
new update have problem its not downloading all lectures of a course
i checked 3 courses and all have same issue only downloading less than 10 lectures only evan these courses have many video lectures more but not showing while downloading
PS C:\Users\vicky> youtube-dl --verbose -u ****@gmail.com -p **** -o '~/MyVideos/%(playlist)s/%(chapter_numbe
r)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/ultrasonic-testing/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '-o', '~/MyVideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s', 'https://www.udemy.com/ultrasonic-testing/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.27
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as *****@gmail.com
[udemy:course] ultrasonic-testing: Downloading webpage
[udemy:course] 380670: Downloading course curriculum
[download] Downloading playlist: Fundamentals of Ultrasonic Testing for Welding Inspectors
[udemy:course] playlist Fundamentals of Ultrasonic Testing for Welding Inspectors: Collected 7 video ids (downloading 7 of them)
[download] Downloading video 1 of 7
[udemy] Downloading login popup
[udemy] 3013404: Downloading webpage
[udemy] 3013404: Downloading lecture JSON
[debug] Invoking downloader on 'https://udemy-assets-on-demand.udemy.com/2015-10-27_20-37-40-1c34611d610fac57a4086c189ae5248b/WebHD_1080.mp4?nva=20160401034828&token=048bdd3eb6f9ed8590aa6'
[download] Destination: C:\Users\vicky\MyVideos\Fundamentals of Ultrasonic Testing for Welding Inspectors\NA - Introduction to the course\Introduction.mp4
[download]   6.5% of 45.03MiB at 369.73KiB/s ETA 01:56

**Comment by jaan143** [comment]
here is second course which have 100 lectures but showing only 8

PS C:\Users\HDNLUF037.WIN-IPDLDV1QL5B> youtube-dl --verbose -u *****@gmail.com -p ***** -o '~/MyVideos/%(playli
st)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s' https://www.udemy.com/job-interview-mastery/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '-o', '~/MyVideos/%(playlist)s/%(chapter_numb
er)s - %(chapter)s/%(title)s.%(ext)s', 'https://www.udemy.com/job-interview-mastery/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.03.26
[debug] Python version 3.4.3 - Windows-2012Server-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as *****@gmail.com
[udemy:course] job-interview-mastery: Downloading webpage
[udemy:course] 730594: Downloading course curriculum
[download] Downloading playlist: Job Interview Mastery + 50 Questions Demo And Get Hired!
[udemy:course] playlist Job Interview Mastery + 50 Questions Demo And Get Hired!: Collected 8 video ids (downloading 8 o
f them)
[download] Downloading video 1 of 8
[udemy] Downloading login popup
[udemy] 4760718: Downloading webpage
[udemy] 4760718: Downloading lecture JSON
[debug] Invoking downloader on 'https://udemy-assets-on-demand.udemy.com/2016-03-30_19-51-47-4516e9e7b382136d88ac79707fe
416fd/WebHD_1080.mp4?nva=20160401034103&token=0c6bda1b4a5210364c851'
[download] Destination: C:\Users\HDNLUF037.WIN-IPDLDV1QL5B\MyVideos\Job Interview Mastery + 50 Questions Demo And Get Hi
red!\NA - Introduction\Introduction And How To Get The Most Out Of The Course.mp4
[download] 100% of 117.17MiB in 05:54
[download] Downloading video 2 of 8
[udemy] 4633614: Downloading webpage
[udemy] 4633614: Downloading lecture JSON
[debug] Invoking downloader on 'https://udemy-assets-on-demand.udemy.com/2016-03-30_20-06-17-312e0bbc014218390fb62bb41fb
75d57/WebHD_1080.mp4?nva=20160401034659&token=0948dde0247ef5bbe39f6'
[download] Destination: C:\Users\HDNLUF037.WIN-IPDLDV1QL5B\MyVideos\Job Interview Mastery + 50 Questions Demo And Get Hi
red!\NA - Introduction\KEY--Prepare what you want to highlight.mp4
[download]  83.8% of 146.36MiB at 315.24KiB/s ETA 01:17

**Comment by dstftw** [comment]
Both courses are paid-only. You have to provide account credentials with these courses purchased.

**Comment by jaan143** [comment]
sins you update youtuble-dl main file of 1-4-2016
its working fine now and showing all lectures  
but sometime giving its giving error after download few lectures so then i run it again and then he download success missing lectures

and one more can you tell me what is exact format date ?
--date 1-4-2016 ?

**Comment by dstftw** [comment]
Read FAQ: https://github.com/rg3/youtube-dl#video-selection-1.
Open a new issue for another error.
