### ISSUE TITLE
Unable to download videos from udemy.. ERROR: Lecture 3544608 is not a video 

### ISSUE THREAD

**Issue by mkranthikmr** [rg3/youtube-dl#9050]
**verbose output:**
PS C:\Users\Mad\Downloads\BDD\Section 1 Introduction Up and running with Ruby on Rails 4.2 using cloud based IDE> yo
utube-dl -u username@gmail.com -p passsword****** --playlist-reverse https://www.udemy.com/rubyonrails-bdd-r
spec-capybara/learn/v4/content --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--playlist-reverse', 'https://www.udemy.com/rubyonrails-b
dd-rspec-capybara/learn/v4/content', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.01
[debug] Python version 3.4.2 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as username@gmail.com
[udemy:course] rubyonrails-bdd-rspec-capybara: Downloading webpage
[udemy:course] 531360: Downloading course curriculum
[download] Downloading playlist: BDD with Ruby on Rails using RSpec 3 and Capybara
[udemy:course] playlist BDD with Ruby on Rails using RSpec 3 and Capybara: Collected 103 video ids (downloading 103 of them)
[download] Downloading video 1 of 103
[udemy] Downloading login popup
[udemy] 3544608: Downloading webpage
[udemy] 3544608: Downloading lecture JSON
ERROR: Lecture 3544608 is not a video
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\common.py", line 323, in extract
    return self._real_extract(url)
  File "C:\Python34\lib\site-packages\youtube_dl\extractor\udemy.py", line 199, in _real_extract
    'Lecture %s is not a video' % lecture_id, expected=True)
youtube_dl.utils.ExtractorError: Lecture 3544608 is not a video

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.

**Comment by mkranthikmr** [comment]
Can you provide Fix id?

**Comment by dstftw** [comment]
03caa463e73c2ae2f666b85febf25ddb03f961ca

**Comment by mkranthikmr** [comment]
Thank you...:)
