### ISSUE TITLE
udemy playlist download stopped when lecture is a html page

### ISSUE THREAD

**Issue by ahiyo** [rg3/youtube-dl#9060]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.01**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -u user@mail.com -p private --verbose -o '~/Videos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s' https://www.udemy.com/the-complete-web-developer-course-2
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', '-o', '~/Videos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(playlist_index)s-%(title)s.%(ext)s', 'https://www.udemy.com/the-complete-web-developer-course-2']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.01
[debug] Python version 3.4.3 - Linux-3.16.0-38-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg N-78590-g5590ab4, ffprobe N-78590-g5590ab4
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as Private
[udemy:course] the-complete-web-developer-course-2: Downloading webpage
[udemy:course] 764164: Downloading course curriculum
[download] Downloading playlist: The Complete Web Developer Course 2.0
[udemy:course] playlist The Complete Web Developer Course 2.0: Collected 289 video ids (downloading 289 of them)
[download] Downloading video 1 of 289
[udemy] Downloading login popup
[udemy] 4720352: Downloading webpage
[udemy] 4720352: Downloading lecture JSON
[debug] Invoking downloader on 'https://udemy-assets-on-demand.udemy.com/2016-03-11_11-48-16-private'
.....CUT.....
[download] Downloading video 6 of 289
[udemy] 4566028: Downloading webpage
[udemy] 4566028: Downloading lecture JSON
ERROR: Lecture 4566028 is not a video
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/common.py", line 323, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python3.4/dist-packages/youtube_dl/extractor/udemy.py", line 199, in _real_extract
    'Lecture %s is not a video' % lecture_id, expected=True)
youtube_dl.utils.ExtractorError: Lecture 4566028 is not a video
```

Lecture 6 is a html page. Normally those are skipped. Ideally it would be great to save it as a pdf (maby out of the scope of this development.) I remain available for more log information if necessary.

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.
