### ISSUE TITLE
cannot download youtube subtitles into html format

### ISSUE THREAD

**Issue by vondiplo** [rg3/youtube-dl#9061]
please view the following command for download the subtitles of the this video - https://www.youtube.com/watch?v=SEyDminvr7Q:

youtube-dl https://www.youtube.com/watch?v=SEyDminvr7Q --skip-download --sub-lang=en --sub-lang=ttml --write-sub --write-auto-sub

How do I get my required format supported? Thank you

**Comment by jaimeMF** [comment]
It should be `--sub-format=ttml` not `--sub-lang`: `youtube-dl 'https://www.youtube.com/watch?v=SEyDminvr7Q' --skip-download --sub-lang=en --sub-format=ttml --write-sub --write-auto-sub` seems to work.
