### ISSUE TITLE
Please support zwearz.com

### ISSUE THREAD

**Issue by suntong** [rg3/youtube-dl#9062]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

> We couldn’t find any issues matching 'zwearz'

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please support http://zwearz.com/.

The generic information extractor is already good enough. Just the file is not properly named. 

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://zwearz.com/watch/9lWxNJF-ufM/electra-woman-dyna-girl-official-trailer-grace-helbig.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://zwearz.com/watch/9lWxNJF-ufM/electra-woman-dyna-girl-official-trailer-grace-helbig.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.01
[debug] Python version 2.7.9 - Linux-3.19.0-26-generic-x86_64-with-Ubuntu-15.04-vivid
[debug] exe versions: ffmpeg 2.7.2-1, ffprobe 2.7.2-1
[debug] Proxy map: {}
[generic] electra-woman-dyna-girl-official-trailer-grace-helbig: Requesting header
WARNING: Falling back on generic information extractor.
[generic] electra-woman-dyna-girl-official-trailer-grace-helbig: Downloading webpage
[generic] electra-woman-dyna-girl-official-trailer-grace-helbig: Extracting information
[debug] Invoking downloader on u'https://r2---sn-a8au-2ime.gvt1.com/videoplayback?mn=sn-a8au-2ime&fexp=9406819,9407116,9412857,9414900,9416126,9416891,9419277,9420452,9422596,9423662,9424580,9427266,9427902,9428399,9428422,9428654,9430829,9431859,9432582,9433183&mm=31&signature=E019F6A457812478510256AE03F83A6DF7C906C8.A0D212D352B1AC14BA03D96063D42E00F868FC43&key=yt6&id=o-ACl9JXp_vdzS8WevpTchzQ2FfwA5TwZ3E2ODIwEW8nsK&requiressl=yes&ip=162.255.116.91&pl=24&mv=u&dur=249.382&source=youtube&ms=au&mt=1459622810&lmt=1459322426100766&ipbits=0&ratebypass=yes&expire=1459645082&sparams=dur,id,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn,expire&upn=D1FcOA80CuE&sver=3&mime=video/mp4&itag=18'
[download] Destination: ELECTRA WOMAN & DYNA GIRL OFFICIAL TRAILER _ Grace Helbig - ZWearZ.com-mp4&itag=18.unknown_video
[download] 100% of 12.53MiB in 00:00

$ file ELECTRA\ WOMAN\ \&\ DYNA\ GIRL\ OFFICIAL\ TRAILER\ _\ Grace\ Helbig\ -\ ZWearZ.com-mp4\&itag\=18.unknown_video 
ELECTRA WOMAN & DYNA GIRL OFFICIAL TRAILER _ Grace Helbig - ZWearZ.com-mp4&itag=18.unknown_video: ISO Media, MP4 v2 [ISO 14496-14]

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://zwearz.com/watch/9lWxNJF-ufM/electra-woman-dyna-girl-official-trailer-grace-helbig.html
- Single video: all related videos under http://zwearz.com/watch/9lWxNJF-ufM/electra-woman-dyna-girl-official-trailer-grace-helbig.html
- Playlist: n.a.

---

### Description of your *issue*, suggested solution and other information

Again - Please support http://zwearz.com/.

The generic information extractor is already good enough. Just the file is not properly named. 

properly name the downloaded file is all that I can necessary now.

**Comment by suntong** [comment]
Properly name the downloaded file is all that I can _think_ necessary now.

Moreover, there is options to choose download 360p or 720p. Wasn't sure which version was downloaded, but it is **640x360**.

**Comment by Hrxn** [comment]
The page already has download links?

**Comment by suntong** [comment]
Yeah, as shown in http://zwearz.com/watch/9lWxNJF-ufM/electra-woman-dyna-girl-official-trailer-grace-helbig.html, but I never clicked it, assuming there are more steps involved.

**Comment by suntong** [comment]
Thanks a lot for the swift fix. I gave it a try, and found that the file name is not ideal. I.e., is it possible to remove the trailing "garbage"? For e.g.,

    youtube-dl -v http://zwearz.com/watch/9lWxNJF-ufM/electra-woman-dyna-girl-official-trailer-grace-helbig.html

will result in a file called "ELECTRA WOMAN & DYNA GIRL OFFICIAL TRAILER _ Grace Helbig**-9lWxNJF-ufM**.mkv". The bold part is not necessary. It begins with the folder name of the download url. Another example, 

    youtube-dl http://zwearz.com/watch/Cn30YySO9jA/.html

will result in a file ends with " **-Cn30YySO9jA**.mp4". 

Thanks

**Comment by suntong** [comment]
Hmm, a side question, without the fix, the video file can be downloaded in one shot -- the whole `.mp4` is downloaded as-is. 

After the fix, it goes through downloading video and audio separately, then uses `ffmpeg` to merge two files back as the `.mp4`. What's the advantage of such extra work? 

Thx

**Comment by Hrxn** [comment]
> Thanks a lot for the swift fix. I gave it a try, and found that the file name is not ideal. I.e., is it possible to remove the trailing "garbage"?

Well, that is not garbage, it's the video ID.
You can set your output like this: https://github.com/rg3/youtube-dl#output-template

For example
`youtube-dl -o '%(title)s.%(ext)s' $URL` gets you only title + file extension, without the id.

> After the fix, it goes through downloading video and audio separately, then uses ffmpeg to merge two files back as the .mp4. What's the advantage of such extra work?

That's because some sites, like YouTube, where the video from `zwearz.com` in this example is actually coming from, offer the best video and audio formats only as separate streams. They get both downloaded and merged into a single file automatically by youtube-dl.

**Comment by yan12125** [comment]
@suntong To get single .mp4 files use ```-f best[ext=mp4]```
