### ISSUE TITLE
youtube: ERROR: unable to download video data: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by desmondc-za** [rg3/youtube-dl#9064]
I run: youtube-dl -v -f 18 "https://www.youtube.com/watch?v=WxEO6NUnwAw"

I get:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'18', u'https://www.youtube.com/watch?v=WxEO6NUnwAw']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.01
[debug] Python version 2.7.8 - Linux-3.16.7-35-desktop-i686-with-SuSE-13.2-i586
[debug] exe versions: ffmpeg N-68684-g8706910, ffprobe N-68684-g8706910, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] WxEO6NUnwAw: Downloading webpage
[youtube] WxEO6NUnwAw: Downloading video info webpage
[youtube] WxEO6NUnwAw: Extracting video information
[youtube] WxEO6NUnwAw: Downloading MPD manifest
[debug] Invoking downloader on u'https://r1---sn-8vq5jvh15-2gte.googlevideo.com/videoplayback?dur=476.310&fexp=9406001%2C9415327%2C9416126%2C9416891%2C9420452%2C9422596%2C9423662%2C9427902%2C9428399%2C9429739%2C9429744%2C9429983%2C9430019%2C9431118%2C9431324%2C9432399%2C9432632&requiressl=yes&pl=18&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&signature=15063FEF0423218FE7C219588346C6D54FC2A95F.BA5748780A268E236A06DBB767FFF6442CC16E26&id=o-APQQuTiWufMui9komOCaeWvuRCK3Ttw_0AUdaTvxscO1&ms=au&mt=1459626941&mv=m&initcwndbps=13618750&mm=31&mn=sn-8vq5jvh15-2gte&ip=41.13.48.223&key=yt6&sver=3&source=youtube&ratebypass=yes&lmt=1422775369572690&upn=L5eSCvkM-hs&expire=1459648608&ipbits=0&itag=18&mime=video%2Fmp4'
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1633, in process_info
    success = dl(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1575, in dl
    return fd.download(name, info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1935, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 400: Bad Request

**Comment by desmondc-za** [comment]
Weird. It worked without the -f 18 switch. But I preferred lower quality version to conserve bandwidth.
Also, -F 18 listed...
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
...as available option.

On the youtube web frontend, I managed to view in 360p quality without error.

**Comment by yan12125** [comment]
```-f 18``` now works. Looks like a temporary YouTube server-side issue.
