### ISSUE TITLE
Youtube-dl can not download 1080P iqiyi video with golden VIP cookie

### ISSUE THREAD

**Issue by ckz1211** [rg3/youtube-dl#9065]
I have logged in iqiyi.com with golden VIP account, and I can see 1080P video in the iqiyi's website. However, youtube-dl can not download 1080P iqiyi video with golden VIP cookie which is exported from the browser.

**Comment by dstftw** [comment]
Completely fill in [new issue template](https://github.com/rg3/youtube-dl/issues/new).
