### ISSUE TITLE
 error: no such option: --embed-thumbnail??

### ISSUE THREAD

**Issue by NickWinston123** [rg3/youtube-dl#9066]
anthony@AnthonyUbuntu:~/Music$ youtube-dl https://soundcloud.com/dailybreed --embed-thumbnail --verbose
Usage: youtube-dl [options] url [url...]

youtube-dl: error: no such option: --embed-thumbnail
anthony@AnthonyUbuntu:~/Music$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'
[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-4.2.0-30-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
Usage: youtube-dl [options] url [url...]

youtube-dl: error: you must provide at least one URL
anthony@AnthonyUbuntu:~/Music$

Tried doing it the other way

anthony@AnthonyUbuntu:~/Music$ youtube-dl  --embed-thumbnail --verbose https://soundcloud.com/pastor-herbs/my-aesthetic
Usage: youtube-dl [options] url [url...]

youtube-dl: error: no such option: --embed-thumbnail
anthony@AnthonyUbuntu:~/Music$

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by NickWinston123** [comment]
@dstftw 
Thanks, downloaded zip and unpacked and now using the latest version.
would you know why this would be caused on every song?

"
WARNING: Unable to download thumbnail "https://i1.sndcdn.com/artworks-000156001424-eymhjg-t500x500.jpg": <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
"

[download] MUDDDD.mp3 has already been downloaded
[download] 100% of 2.26MiB
WARNING: Skipping embedding the thumbnail because the file is missing.
[download] Downloading video 6 of 497
[soundcloud] hollowxbeatz/swervin: Resolving id
[soundcloud] hollowxbeatz/swervin: Downloading info JSON
[soundcloud] 231331697: Downloading track url
[soundcloud] 231331697: Checking download video f
