### ISSUE TITLE
thevideo.me don't work

### ISSUE THREAD

**Issue by calvarr** [rg3/youtube-dl#9067]
youtube-dl -v http://thevideo.me/embed-9b9wgd790h01-700x430.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://thevideo.me/embed-9b9wgd790h01-700x430.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.09
[debug] Python version 3.5.1 - Linux-4.4.5-1-ARCH-i686-with-arch
[debug] exe versions: ffmpeg 3.0, ffprobe 3.0, rtmpdump 2.4
[debug] Proxy map: {}
[generic] embed-9b9wgd790h01-700x430: Requesting header
WARNING: Could not send HEAD request to http://thevideo.me/embed-9b9wgd790h01-700x430.html: HTTP Error 403: Forbidden
[generic] embed-9b9wgd790h01-700x430: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 351, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 1890, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by jaimeMF** [comment]
The site seems to mainly [host copyrighted content](https://www.google.com/transparencyreport/removals/copyright/domains/thevideo.me/) without permission, [youtube-dl doesn't support such sites](https://github.com/rg3/youtube-dl/blob/8d9dd3c34bd38b2545af95f8ef670b07ae1fb6ff/README.md#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).

**Comment by calvarr** [comment]
work two weeks ago...
