### ISSUE TITLE
Test duration – parallelize?

### ISSUE THREAD

**Issue by mk-pmb** [rg3/youtube-dl#9069]
I had another look at #8543 as I learned to fix some Unicode stream errors the other day. My current main obstacle is how long the tests run on Travis, no fun to make a PR and wait hours to see if it could be accepted. I could try and look into parallelizing the tests, like 20 at once, what would you think? (I'll ask first, since there was no reaction to said PR.)

Update: I'd also try and add some means to re-order the tests, so I could prioritize tests that made Travis fail last time. In the PR above, it looks like it crashed mainly due to a bug in nosetest, so if that one can be reproduced, all the other tests lapse and shouldn't delay that critical test.

**Comment by dstftw** [comment]
This is already [proposed](https://github.com/rg3/youtube-dl/pull/7267).
