### ISSUE TITLE
[novamov] Unable to extract filekey

### ISSUE THREAD

**Issue by kotofond** [rg3/youtube-dl#9070]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
```
C:\WINDOWS\system32>youtube-dl --verbose http://www.novamov.com/video/ebae8639bf098
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.novamov.com/video/ebae8639bf098']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.01
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: ffmpeg N-78358-g674cc26, ffprobe N-78358-g674cc26
[debug] Proxy map: {}
[novamov] ebae8639bf098: Downloading video page
[novamov] ebae8639bf098: Downloading continue to the video page
ERROR: Unable to extract filekey; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 323, in extract
    return self._real_extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\novamov.py", line 82, in _real_extract
    filekey = extract_filekey()
  File "c:\python35\lib\site-packages\youtube_dl\extractor\novamov.py", line 58, in extract_filekey
    self._FILEKEY_REGEX, webpage, 'filekey', default=default)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 627, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract filekey; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Provide example URL does not work in browser.

**Comment by kotofond** [comment]
When I open http://www.novamov.com/video/ebae8639bf098 in a browser I get redirected to http://www.auroravid.to/video/ebae8639bf098 which gives me 'Continue to the video' button. After clicking on it refreshes the page without changing the URL and finally shows the video.
Is it not the case for you?

**Comment by dstftw** [comment]
No, blank page after redirection.

**Comment by kotofond** [comment]
Here is a log with --dump-pages parameter.
[log.txt](https://github.com/rg3/youtube-dl/files/201335/log.txt)

Please let me know if you need anything else. Thanks much!
