### ISSUE TITLE
tnaflix.com changed URL

### ISSUE THREAD

**Issue by gineadai** [rg3/youtube-dl#9074]
It's now alpha.tnaflix.com and old url not working.

**Comment by MaZZly** [comment]
Am I missing something? Most URLs seem to be in the format of www.tnaflix.com/category/slug (which currently is not supported) and not in player.tnaflix.com or alpha.tnaflix.com (as stated above)

**Comment by yan12125** [comment]
Please list concrete URLs if there are problems. For me https://alpha.tnaflix.com/teen-porn/Educational-xxx-video/video6538 redirects to https://www.tnaflix.com/teen-porn/Educational-xxx-video/video6538, so both URL forms are supported by youtube-dl now.
