### ISSUE TITLE
[Udemy] AttributeError: 'NoneType' object has no attribute 'copy' error while downloading a course

### ISSUE THREAD

**Issue by LionelFernandez** [rg3/youtube-dl#9078]
I am downloading a course from Udemy using the command
C:\Users\Udemy>youtube-dl --verbose  -u 888888@gmail.com -p ******** --ignore-errors --cookies "C:\Users\Udemy\Videos\UdemyVideos\login.json" -o "Videos/udemyvideos/%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s" --ignore-errors --batch-file "C:\Users\Udemy\Videos\udemyVideos\MyURL.txt"

This happened with a number of courses

It is proceeding well; but at one of the lecture, I am facing an error and the scripts stops even though i put in the parameter --ignore-errors
[download] 100% of 158.15MiB
[download] Downloading video 206 of 246
[udemy] 2620026: Downloading webpage
[udemy] 2620026: Downloading lecture JSON
[debug] Invoking downloader on 'https://udemy-assets-on-demand.udemy.com/2015-08-16_17-14-17-0d251d1779602f4caf7053c206d62b1a/WebHD_1080.mp4?nva=
QQQQQQQQ&token=*88888888888888888
[download] Videos\udemyvideos\Ultimate Web Designer & Developer Course - Build 23 Projects!\27 - Career Development - How to Start Your Web Design _ Development Career\Freelancing - Should You Quit Your Job.mp4 has already been downloaded
[download] 100% of 13.97MiB
[download] Downloading video 207 of 246
[udemy] 2620022: Downloading webpage
[udemy] 2620022: Downloading lecture JSON
ERROR: Lecture 2620022 is not a video
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\common.py", line 323, in extract
    return self._real_extract(url)
  File "c:\python35\lib\site-packages\youtube_dl\extractor\udemy.py", line 199, in _real_extract
    'Lecture %s is not a video' % lecture_id, expected=True)
youtube_dl.utils.ExtractorError: Lecture 2620022 is not a video

ERROR: 'NoneType' object has no attribute 'copy'
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 680, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 840, in process_ie_result
    extra_info=extra)
  File "c:\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 744, in process_ie_result
    new_result = info.copy()
AttributeError: 'NoneType' object has no attribute 'copy' 

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.

**Comment by LionelFernandez** [comment]
Thanks for the update
