### ISSUE TITLE
Download non-video files from Udemy

### ISSUE THREAD

**Issue by 2ndg33r** [rg3/youtube-dl#9080]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.01**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

This is just a question about downloading non-video files from Udemy. On Udemy there are some lectures that are text only. I can download video files fine but when it gets to a part of "chapter" that is not a video the script quits with ERROR: Lecture xyz is not a video. Is there a workaround for this? I'm fine not actually downloading these so is there a way to say when it's not a video file skip it and continue to the next one?

---

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl. For now you enforce ignoring errors with `-i`.

**Comment by MaZZly** [comment]
I encountered the same problem with a video containing text-courses... When passing the -i flag it gets one step further and then fails on `ERROR: 'NoneType' object has no attribute 'copy'`
But if it'll get fixed on next release I can probably wait. ETA?
