### ISSUE TITLE
[ZDF] Mediathek Subtitle not loading

### ISSUE THREAD

**Issue by a-l-e-k** [rg3/youtube-dl#9081]
On selected TV programs you can choose a subtitle in the ZDF Mediathek. This subtitle is not recognized by youtube-dl and can not be saved.

In comparision the subtitle from ARD Mediathek is recognized and will be saved by the program. It is in the format "EBU-TT-D-Basic-DE". I have not found any information about the format ZDF is using.

youtube-dl.exe -s --list-subs http://www.zdf.de/ZDFmediathek/beitrag/video/2589704/Zum-Sterben-zu-frueh
[ZDF] 2589704: Downloading video info
[ZDF] 2589704: Downloading SMIL file
[ZDF] 2589704: Downloading f4m manifest
[ZDF] 2589704: Downloading m3u8 information
2589704 has no subtitles

**Comment by jaimeMF** [comment]
It will be supported in the next version.
