### ISSUE TITLE
ffmpeg/avconv settings to improve encoding of Twitch streams

### ISSUE THREAD

**Issue by alphapapa** [rg3/youtube-dl#9082]
I recently discovered that youtube-dl can process Twitch past-broadcast streams with ffmpeg/avconv, which is great.  However, with the encoding settings it uses, the resulting file does not allow players to seek or recognize the duration until after the video has been completely downloaded, because the MP4 file does not have fragmentation enabled.

But by using some additional encoding settings, the file can be played immediately, while it is being downloaded and muxed, and players can seek and recognize the increasing duration properly.  For example, it works perfectly in VLC 2.2.1.

Here's an example shell command:
```
avconv -i "$playlist_URL"  -vcodec copy -vf setpts=expr=PTS-STARTPTS -frag_size 1048576 -acodec copy -af asetpts=expr=PTS-STARTPTS "$output_filename.mp4"
```
This sets the video and audio streams to be copied directly without reencoding, uses the `setpts` video filter and the `asetpts` audio filter to synchronize the timestamps, and uses `-frag_size 1048576` to set a 1 MB fragment size in the MP4 container, which writes metadata for every 1 MB fragment, rather than writing it at the end of the file (which won't happen until the download is complete).

I just pulled from master and looked through `twitch.py` and `ffmpeg.py` but I couldn't find a way to set encoding options just for Twitch.  It might be fine to use these for all encoding, because it would probably benefit much more than just Twitch downloads, but I'll leave that decision to you.  :)

Thanks for your work on youtube-dl!

**Comment by dstftw** [comment]
What you request is achievable with `--hls-use-mpegts`.

**Comment by alphapapa** [comment]
Thanks for pointing that out, I wasn't aware of that.

That does seem to work well, however the options I mentioned here do have an advantage: VLC can recognize the increasing duration of the file as it plays it, and displays it in the progress bar.  Without the timestamping options, it always displays the duration as `00:00`.

So it might be helpful to add these encoding settings to the `--hls-use-mpegts` option.
