### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jaan143** [rg3/youtube-dl#9083]
hello Sir 
i need little help
can i download videos to load list of downloading links 
like this i generated all download links of full course so can i import that list and download alls?

http://vid.pluralsight.com/expiretime=1459820641/96ca9757bdc6597da750e489bc104866/clip-videos/nigel-poulton/red-hat-enterprise-linux-storage-fundamentals-m7/red-hat-enterprise-linux-storage-fundamentals-m7-04/1024x768mp4/20151208133220.mp4
http://vid.pluralsight.com/expiretime=1459820647/cec515858debe1c0a39a318c8ca29abc/clip-videos/nigel-poulton/red-hat-enterprise-linux-storage-fundamentals-m7/red-hat-enterprise-linux-storage-fundamentals-m7-05/1024x768mp4/20151208133220.mp4
http://vid.pluralsight.com/expiretime=1459820653/d0331c872449dbaeb46614e3ec193ec0/clip-videos/nigel-poulton/red-hat-enterprise-linux-storage-fundamentals-m7/red-hat-enterprise-linux-storage-fundamentals-m7-06/1024x768mp4/20151208133220.mp4

if its possible then plz tell me exact command of that
thanks very much

**Comment by dstftw** [comment]
This does not make any sense since final download links may expire by the time you will try download them.

**Comment by jaan143** [comment]
i know that links are expire after 5 minutes but actually problem is this i am generating that links and then downloading via IDM but via idm all files names are change to numbers like this 
54545487.mp4
54545487_2.mp4
54545487_3.mp4

but i want to download with their original title name

**Comment by dstftw** [comment]
If you want to download with original names use youtube-dl to download or any supported external downloader.

**Comment by jaan143** [comment]
Sir actually i want to download all new courses fast but if i am using youtube-dl then need to set time atleast 2 minuts after second lecture and also need to set speed but i am generating these links from youtube-dl and that trick is working fine without banned account
so can if you know any supported external downloader then plz tell me

thanks

**Comment by dstftw** [comment]
Read `--help` for list of external downloaders.

**Comment by jaan143** [comment]
yes there is wrote only this line
-h, --help                       Print this help text and exit
so i need to save txt file with this name help.txt ?
and where i can save that txt file and then youtube-dl will print this?
kindly give me full command with that if i save txt file in downloads folder

**Comment by dstftw** [comment]
```
    --external-downloader COMMAND    Use the specified external downloader.
                                     Currently supports
                                     aria2c,avconv,axel,curl,ffmpeg,httpie,wget
```

**Comment by jaan143** [comment]
it will like this
youtube-dl --verbose --external-downloader > link.txt

**Comment by dstftw** [comment]
You don't need to extract links, external downloader will be invoked for each link on download.

**Comment by jaan143** [comment]
ok but how external downloader will invoked ?
plz tell me full command including youtube-dl to end
i generate a list which is save in my download folder with this name link.txt

**Comment by jaan143** [comment]
hello sir i am waiting plz plz help me to solve this my big problem
just tell me full command

**Comment by jaan143** [comment]
i am trying these alls tricks but cant success :(

PS C:\Users\vicky\downloads> youtube-dl --verbose --external-downloader COMMAND link.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--external-downloader', 'COMMAND', 'link.txt']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.01
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: 'link.txt' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:link.txt" ) to search YouTube
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "c:\python34\lib\site-packages\youtube_dl\extractor\common.py", line 323, in extract
    return self._real_extract(url)
  File "c:\python34\lib\site-packages\youtube_dl\extractor\generic.py", line 1238, in _real_extract
    % (url, url), expected=True)
youtube_dl.utils.ExtractorError: 'link.txt' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:link.txt" ) to search YouTube

PS C:\Users\vicky\downloads> youtube-dl --verbose --external-downloader COMMAND links.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--external-downloader', 'COMMAND', 'links.txt']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.01
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: 'links.txt' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:links.txt" ) to search YouTube
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\youtube_dl\YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "c:\python34\lib\site-packages\youtube_dl\extractor\common.py", line 323, in extract
    return self._real_extract(url)
  File "c:\python34\lib\site-packages\youtube_dl\extractor\generic.py", line 1238, in _real_extract
    % (url, url), expected=True)
youtube_dl.utils.ExtractorError: 'links.txt' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:links.txt" ) to search YouTube

PS C:\Users\vicky\downloads> youtube-dl --verbose --external-downloader COMMAND > links.txt
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--external-downloader', 'COMMAND']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.04.01
[debug] Python version 3.4.3 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
PS C:\Users\vicky\downloads>

**Comment by linglung** [comment]
@jaan143 you don't specify the name of external downloader and it's argument. So base on your syntax, it must be something like this, for example: 
`youtube-dl --verbose --external-downloader aria2c  YOUR-URL `
