### ISSUE TITLE
alert handshake failure cant download image?

### ISSUE THREAD

**Issue by NickWinston123** [rg3/youtube-dl#9089]
I get this same type of error on every soundcloud song I try to download:
WARNING: Unable to download thumbnail "https://i1.sndcdn.com/artworks-000155544517-9ww49z-t500x500.jpg": <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL  

anthony@AnthonyUbuntu:~/Music$ youtube-dl https://soundcloud.com/slightbeats/dabs --embed-thumbnail -o "%(title)s.%(ext)s" -f mp3
[soundcloud] slightbeats/dabs: Resolving id
[soundcloud] slightbeats/dabs: Downloading info JSON
[soundcloud] 256394142: Downloading track url
[soundcloud] 256394142: Checking fallback video format URL
[soundcloud] 256394142: Checking http_mp3_128_url video format URL
[soundcloud] 256394142: Downloading thumbnail ...
WARNING: Unable to download thumbnail "https://i1.sndcdn.com/artworks-000155544517-9ww49z-t500x500.jpg": <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>

anthony@AnthonyUbuntu:~/Music$ youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.05
[debug] Python version 2.7.6 - Linux-4.2.0-30-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, rtmpdump 2.4
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

Also is there an option so that if it can't find an image for some reason it attaches an alternative image to the track so it doesn't stop it from downloading other tracks (when I download a playlist)

**Comment by NickWinston123** [comment]
Figured out it was a python version error but now its having trouble attaching the images to the files

it is saying the jpg is no there but it is

[soundcloud] loudlordbitch/new-tees-in-store-link-in-description-kush-krazy-4-dropping-on-420-squad: Resolving id
[soundcloud] loudlordbitch/new-tees-in-store-link-in-description-kush-krazy-4-dropping-on-420-squad: Downloading info JSON
[soundcloud] 257358307: Downloading track url
[soundcloud] 257358307: Checking fallback video format URL
[soundcloud] 257358307: Checking http_mp3_128_url video format URL
[soundcloud] 257358307: Downloading thumbnail ...
[soundcloud] 257358307: Writing thumbnail to: new tees in store (link in description) + Kush Krazy 4 dropping on 4_20 squad.jpg
[download] Destination: new tees in store (link in description) + Kush Krazy 4 dropping on 4_20 squad.mp3
[download] 100% of 1.88MiB in 00:00
[ffmpeg] Adding thumbnail to "new tees in store (link in description) + Kush Krazy 4 dropping on 4_20 squad.mp3"
ERROR: file:new tees in store (link in description) + Kush Krazy 4 dropping on 4_20 squad.jpg: No such file or directory

**Comment by yan12125** [comment]
Two issues:

1. ```alert handshake failure```: soundcloud's site i1.sndcdn.com requires at least Python 2.7.9 or Python 3.2. See #5366.
2. I guess you're using avconv, which is broken. Install ffmpeg and add ```--prefer-ffmpeg``` to youtube-dl. See #7238.
