### ISSUE TITLE
Option to always download a single media file

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#9096]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

It would be useful to have a way to specify that I want a single media file.
In some situations, I need to use `--get-url` to get the URL to a video (in order to use it in another tool) but youtube-dl detects a recent version of avconv so it outputs two separate URLs.
Would it be possible to have an option like `--prefer-single` that makes youtube-dl behave as if the avconv version is too old to mux separate files.

**Comment by yan12125** [comment]
```-f best``` should work.

**Comment by Rudloff** [comment]
Oh you're right, sorry I didn't see that.
