### ISSUE TITLE
beeg change api version to V6 1750

### ISSUE THREAD

**Issue by badproject** [rg3/youtube-dl#9100]
Video downloading but cannot be watching...

#youtube-dl -v 'http://beeg.com/5936679'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://beeg.com/5936679']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.6 - Linux-3.13.0-74-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-79139-gde1a0d4, ffprobe N-79139-gde1a0d4, rtmpdump 2.4
[debug] Proxy map: {}
[Beeg] 5936679: Downloading JSON metadata
[debug] Invoking downloader on u'https://video.beeg.com//key=-46WUei-C4WElcrKU9rkew%2Cend=1460029329%2Climit=1%2Cx=88.255.184.101/720p/5936679.mp4'
[download] Destination: Sexy brunette shows her friend why she loves her-5936679.mp4
[download] 100% of 923.48KiB in 00:17

**Comment by dstftw** [comment]
This is what beeg serves as 720p for this particular video. Other formats work fine. Watching in browser works since it uses 480p by default.
