### ISSUE TITLE
Audio not working on some youtube links, get "audio/x-unknown" error

### ISSUE THREAD

**Issue by priestc** [rg3/youtube-dl#9105]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

### Description of your *issue*, suggested solution and other information

I'm using Ubuntu. Sometimes when I download youtube links, it works perfectly. Sometims the video will apear to download, but when I try to play the video, there is no sound.

![error_msg](https://cloud.githubusercontent.com/assets/132586/14354999/603d542c-fc94-11e5-936b-aa8a81e95831.png)

That is an example of the error message that my media player gives me. When I try to play in another media player, it gives me a similar error. 

When I download the video, it seems to download the video part first, then the audio part, then it combines the two into a single file. This merging process appears to be broken. When I first started using youtube-dl it didn't used to do that. It used to download the file all in one piece and it worked pretty much 100% of the time. How can I re-enable the "download as one piece" mode?

Here are some examples of videos that are broken when I try to download them:

uibtdAez0gI
LFZlb5Sf0jY
0ZXGVaszR2I
1AlAVPTZ004

It seems that about 50% of the videos I download these day is broken this way.

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by priestc** [comment]
$ youtube-dl -v 1AlAVPTZ004
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'1AlAVPTZ004']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.05
[debug] Python version 2.7.6 - Linux-3.13.0-83-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] 1AlAVPTZ004: Downloading webpage
[youtube] 1AlAVPTZ004: Downloading video info webpage
[youtube] 1AlAVPTZ004: Extracting video information
[youtube] 1AlAVPTZ004: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://r17---sn-a5m7ln7d.googlevideo.com/videoplayback?id=d4094054f4d9d34e&itag=136&source=youtube&requiressl=yes&mm=31&mn=sn-a5m7ln7d&mv=u&ms=au&nh=IgpwcjA0LmxheDE2KgkxMjcuMC4wLjE&pl=23&ratebypass=yes&mime=video/mp4&gir=yes&clen=105308741&lmt=1394075667238679&dur=439.941&mt=1460066825&key=dg_yt0&upn=y2UiIVdlscI&signature=4AEA469D76BE73864A70C7BBBEEA1C6AA2F152FF.71C6B6A06C86BE20228D0181512E94D94E214679&sver=3&fexp=9406124,9410705,9416126,9416891,9420452,9422544,9422596,9423662,9426857,9426926,9427902,9428398,9428606,9428856,9429246,9429693,9430829,9431284,9433257,9433295,9433312,9433318,9433445,9433508&ip=72.215.186.147&ipbits=0&expire=1460088764&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,mv,ms,nh,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: 2012 Panini Cooperstown Baseball Blaster Box Break!-1AlAVPTZ004.f136.mp4
[download] 100% of 100.43MiB in 00:49
[debug] Invoking downloader on u'https://r17---sn-a5m7ln7d.googlevideo.com/videoplayback?dur=440.021&keepalive=yes&lmt=1426491942311678&fexp=9406124%2C9410705%2C9416126%2C9416891%2C9420452%2C9422544%2C9422596%2C9423662%2C9426857%2C9426926%2C9427902%2C9428398%2C9428606%2C9428856%2C9429246%2C9429693%2C9430829%2C9431284%2C9433257%2C9433295%2C9433312%2C9433318%2C9433445%2C9433508&nh=IgpwcjA0LmxheDE2KgkxMjcuMC4wLjE&expire=1460088764&sparams=clen%2Cdur%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&key=yt6&mime=audio%2Fwebm&requiressl=yes&sver=3&itag=251&pl=23&upn=CQmGxhxQ1K0&ipbits=0&mm=31&id=o-AHhDtcCd3q5Xv5TJXXxQnd4012G8OxOmP1sC3oD6hvRx&mn=sn-a5m7ln7d&clen=8304517&gir=yes&ms=au&mv=u&mt=1460066825&source=youtube&signature=55D2E9A19230F0183356715AB66F20C9727C890F.53B3BF179DFEBB32330A6177BF250A26E2105A6C&ip=72.215.186.147&ratebypass=yes'
[download] Destination: 2012 Panini Cooperstown Baseball Blaster Box Break!-1AlAVPTZ004.f251.webm
[download] 100% of 7.92MiB in 00:03
[ffmpeg] Merging formats into "2012 Panini Cooperstown Baseball Blaster Box Break!-1AlAVPTZ004.mkv"
[debug] ffmpeg command line: avconv -y -i 'file:2012 Panini Cooperstown Baseball Blaster Box Break!-1AlAVPTZ004.f136.mp4' -i 'file:2012 Panini Cooperstown Baseball Blaster Box Break!-1AlAVPTZ004.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:2012 Panini Cooperstown Baseball Blaster Box Break!-1AlAVPTZ004.temp.mkv'
Deleting original file 2012 Panini Cooperstown Baseball Blaster Box Break!-1AlAVPTZ004.f136.mp4 (pass -k to keep)
Deleting original file 2012 Panini Cooperstown Baseball Blaster Box Break!-1AlAVPTZ004.f251.webm (pass -k to keep)

**Comment by yan12125** [comment]
Both VLC 2.2.2 and mpv 0.16.0 work fine for me. Most like you need to install some additional softwares: https://www.google.com/#q=required+plugin+could+not+be+found
