### ISSUE TITLE
YouTube-DL hangs, times out when trying to download or retrieve direct URLs

### ISSUE THREAD

**Issue by github-user-123** [rg3/youtube-dl#9112]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

---

I tried to download a music video from YouTube last night that I wanted to extract the audio from (it's not a Vevo one or anything, actually an old song that someone just stuck lyrics onto) at here

https://www.youtube.com/watch?v=MBgQ5ZiphUs

It hangs at showing the Python version, which is 2.7.10, and then gives a timeout error. The same thing happened to me just now when I was trying to extract a URL from a Comedy Central Daily Show video. The log is included here:

```
C:\youtube-dl>youtube-dl --verbose -g http://thedailyshow.cc.com/videos/1q93jy/september-11--2001
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'-g', u'http://thedailyshow.cc.com/videos/1q93jy/september-11--2001']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-78335-g9ee4c89, ffprobe N-78335-g9ee4c89, rtmpdump 2.4
[debug] Proxy map: {'ftp': 'ftp://localhost:21320', 'http': 'http://localhost:21320', 'https': 'https://localhost:21320'}
ERROR: Unable to download webpage: timed out (caused by timeout('timed out',))
  File "youtube_dl\extractor\common.pyo", line 371, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1935, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 750, in http_open
  File "urllib2.pyo", line 1200, in do_open
  File "httplib.pyo", line 1132, in getresponse
  File "httplib.pyo", line 453, in begin
  File "httplib.pyo", line 409, in _read_status
  File "socket.pyo", line 480, in readline
```

The timeout error was the same with the YouTube video. What's going on? I've been able to download from YouTube and from Comedy Central plenty of times before. Is there any reason why youtube-dl would be hanging and then giving a timeout error with this new version? I can navigate to Comedy Central and YouTube themselves in my web browser, but can't download from them with youtube-dl. Any assistance you can provide would be greatly appreciated.

**Comment by dstftw** [comment]
Most likely this is due to your proxy.

**Comment by github-user-123** [comment]
I don't have a proxy, though. I'm in the U.S. on Verizon DSL 1.5m/768k, so I know it's not because of geo-blocking. I don't have a firewall program either.

How could youtube-dl be using a proxy if I don't have one, either on my system or in my normal web browser?

**Comment by dstftw** [comment]
You have.
>[debug] Proxy map: {'ftp': 'ftp://localhost:21320', 'http': 'http://localhost:21320', 'https': 'https://localhost:21320'}

Remove it from env variables.

**Comment by github-user-123** [comment]
OK, I found what was happening. I'm using Spybot Search & Destroy and for some reason it uses its own proxy as part of the Internet protection feature. Had no idea that it even had that as part of it. Thanks for pointing that out :)
