### ISSUE TITLE
Using --add-metadata  ?

### ISSUE THREAD

**Issue by NickWinston123** [rg3/youtube-dl#9113]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [xx ] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

How do I set the artist and album name, album, artist, etc. of a track if it can't find it?

I do use -o but it rarely finds the correct info for soundcloud tracks

youtube-dl https://soundcloud.com/slightbeats/bloodshed-ft-viggoo --embed-thumbnail -o "%(title)s.%(ext)s" -f mp3 --prefer-ffmpeg --verbose -i

**Comment by dstftw** [comment]
You can parse additional metadata from title with `--metadata-from-title`.

**Comment by NickWinston123** [comment]
@dstftw Ive tried this but it doesnt find the right information, is there no way to manually add the information through youtube-dl?

**Comment by yan12125** [comment]
Please provide more information, including your expectations.

**Comment by NickWinston123** [comment]
@yan12125 
Well for example I have something called ampache running on a local server

I use youtube-dl to download soundcloud user's tracks, then include the songs in ampache so I can listen to them locally. 

Youtube-dl does get the title of the song correct and the thumbnail, but if it can't find the artist then it doesn't set anything so I must manually set that in ampache, which takes a very long time and when I want to update / refresh the songs once I add more I have to redo the whole process

What I would like to be able to do is something like -o, but I want to set the artist or album name instead of it try to find it 

youtube-dl https://soundcloud.com/slightbeats/ --embed-thumbnail -o "%(title)s.%(ext)s" -f mp3 --prefer-ffmpeg --verbose -i  --set-artist "SLIGHT" --set-album "SLIGHT Collection"

**Comment by yan12125** [comment]
Does ampache read from extended attributes (https://github.com/rg3/youtube-dl/blob/536a55d/youtube_dl/postprocessor/xattrpp.py#L139-L147) or MP3's ID3 metadata? The latter is not implemented yet and already requested in #5957.
