### ISSUE TITLE
Lynda organization session has expired

### ISSUE THREAD

**Issue by Mgayar-sci** [rg3/youtube-dl#9118]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --cookies cookies.txt https://www.lynda.com/Unity-tutorials/Add-player-positions/427923/479695-4.html? --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--cookies', u'cookies.txt', u'https://www.lynda.com/Unity-tutorials/Add-player-positions/427923/479695-4.html?', u'--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[lynda] 479695: Downloading video JSON
ERROR: lynda returned error: Session has expired
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 669, in extract_info
  File "youtube_dl\extractor\common.pyo", line 323, in extract
  File "youtube_dl\extractor\lynda.pyo", line 124, in _real_extract
ExtractorError: lynda returned error: Session has expired
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

I'm having problems downloading videos from Lynda.com using my login cookies.txt file, it displays an error requiring me to use username and password which are not available in organization case

**Comment by dstftw** [comment]
Most likely your cookiefile has expired.
1. Can you watch it in browser?
2. How long ago have you exported your cookies? Re-export them and try again.
3. Post the output of `youtube-dl --dump-pages --print-traffic --cookies cookies.txt https://www.lynda.com/Unity-tutorials/Add-player-positions/427923/479695-4.html`.

**Comment by Mgayar-sci** [comment]
1. I can watch in browser.
2. 2 or 3 minutes
3. It worked for some time after I re-exported the cookies and it seems working for some time and I must re-export the cookies again.

Some cookies worked just fine and some other didn't.
