### ISSUE TITLE
[AlJazeera] [geoblocked] Proper video doesn't download

### ISSUE THREAD

**Issue by anovicecodemonkey** [rg3/youtube-dl#9127]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --verbose http://www.aljazeera.com/programmes/listeningpost/2016/04/panama-papers-media-censored-story-160409095509553.html[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.aljazeera.com/programmes/listeningpost/2016/04/panama-papers-media-censored-story-160409095509553.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 3.5.1 - Linux-4.4.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[AlJazeera] panama-papers-media-censored-story-160409095509553: Downloading webpage
[brightcove:new] 4838694274001: Downloading webpage
[brightcove:new] 4838694274001: Downloading JSON metadata
[brightcove:new] 4838694274001: Downloading m3u8 information
[debug] Invoking downloader on 'http://bc05.ajmn.me/665003303001/201604/3931/665003303001_4838653344001_20160409-PRG-E-LPO-Panama-4017257-copy.mp4'
[download] Panama Papers - Has the media censored the story - The Listening Post (Full)-4838694274001.mp4 has already been downloaded
[download] 100% of 99.29KiB

...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

youtube-dl appears to first detect correctly that AlJazeeraIE is needed but then swaps to brightcovenewIE downloading only a 99KB file.

**Comment by dstftw** [comment]
Works fine for me:
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.aljazeera.com/programmes/listeningpost/2016/04/panama-papers-media-censored-story-160409095509553.html', u'-v']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.04.06
[debug] Git HEAD: 6a801f4
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg 3.0, ffprobe N-77883-gd7c75a5, rtmpdump 2.4
[debug] Proxy map: {}
[AlJazeera] panama-papers-media-censored-story-160409095509553: Downloading webpage
[brightcove:new] 4838694274001: Downloading webpage
[brightcove:new] 4838694274001: Downloading JSON metadata
[brightcove:new] 4838694274001: Downloading m3u8 information
[debug] Invoking downloader on u'http://bc05.ajmn.me/665003303001/201604/3931/665003303001_4838653344001_20160409-PRG-E-LPO-Panama-4017257-copy.mp4'
[download] Resuming download at byte 272440453
[download] Destination: Panama Papers - Have the media censored the story - The Listening Post (Full)-4838694274001.mp4
[download]  61.0% of 1.01GiB at 10.08MiB/s ETA 00:39
ERROR: Interrupted by user
```

**Comment by anovicecodemonkey** [comment]
Thanks @dstftw. On further investigation it appears that the video downloaded is a short video explaining that the content is geoblocked in my location.

**Comment by anovicecodemonkey** [comment]
I still think it's worthwhile finding a way to detect a geoblock in this case and present a useful error (if that is indeed possible).

**Comment by dstftw** [comment]
With brief look I did not find any indication of geoblock.

**Comment by anovicecodemonkey** [comment]
OK. With --dump-pages, one of the pages was 4838694274001_https_-_edge.api.brightcove.com_playback_v1_accounts_665003303001_videos_4838694274001.dump

in there I found the URL http://bc05.ajmn.me/665003303001/201604/3931/665003303001_4838653344001_20160409-PRG-E-LPO-Pan"ama-4017257-copy.mp4

If I load that in my browser I am redirected to http://bc05.ajmn.me/665003303001/665003303001_2585446690001_GeoMessage.mp4

Hope that helps.
