### ISSUE TITLE
Lynda.com Login Error

### ISSUE THREAD

**Issue by frakman1** [rg3/youtube-dl#9129]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**
```
c:\Python27>youtube-dl  --version
2016.04.06
```

I have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] I've made sure I have the latest version of youtube-dl.
- [x] I've confirmed that I can view the video on a web browser 
- [x] Made sure to manually logout of lynda.com.
- [x] Made sure that a regular youtube video download works.

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
c:\Python27>youtube-dl -v -o lynda1.avi http://www.lynda.com/Mobile-Apps-tutorials/Convert-iOS-9-Apps-Apple-TV-Apps/457870-2.html -u my@email.com -p mypassword
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-o', u'lynda1.avi', u'http://www.lynda.com/Mobile-Apps-tutorials/Convert-iOS-9-Apps-Apple-TV-Apps/457870-2.html', u'-u', u'PRIVATE', u'-p', u'PRIVATE']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[lynda:course] Logging in as my@email.com
ERROR: Unable to login, incorrect username and/or password
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 669, in extract_info
  File "youtube_dl\extractor\common.pyo", line 322, in extract
  File "youtube_dl\extractor\common.pyo", line 316, in initialize
  File "youtube_dl\extractor\lynda.pyo", line 23, in _real_initialize
  File "youtube_dl\extractor\lynda.pyo", line 51, in _login
ExtractorError: Unable to login, incorrect username and/or password
```

Version:2016.04.06
Windows 7 -64bit

**Comment by dstftw** [comment]
Both single video and course downloading use the same code for authentication thus if the former does works for you and the latter does not you are most likely input incorrect login/password. Both authentications work fine for me. Also never hardcode video extension but rather use `%(ext)s`.

**Comment by frakman1** [comment]
I never said that single works and course doesn't. 
I said that I tested a regular Youtube video (NOT Lynda) with  the tool and that worked. 
Can you provide an example of how best to call this function then? 
I am positive the username/password are correct as I copied them directly from the browser page.

**Comment by dstftw** [comment]
In any case authentication works fine. Check login/password are [properly quoted/escaped](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command). Also it should be individual login, not organization login. For latter use `--cookies`.
