### ISSUE TITLE
TypeError exception on GDC Vault 2016 free videos

### ISSUE THREAD

**Issue by snarfed** [rg3/youtube-dl#9132]
thanks in advance!...

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v -C http://gdcvault.com/play/1023657/Escaping-the-Holodeck-Storytelling-and
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-C', u'http://gdcvault.com/play/1023657/Escaping-the-Holodeck-Storytelling-and']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Darwin-15.4.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6
[debug] Proxy map: {}
[debug] Public IP address: 67.169.95.105
[GDCVault] Escaping-the-Holodeck-Storytelling-and: Downloading webpage
WARNING: [GDCVault] It looks like http://www.gdcvault.com/play/1023657 requires a login. Try specifying a username and password and try again.
WARNING: [GDCVault] Could not login.
Traceback (most recent call last):
  File "/Users/ryan/local/bin/youtube-dl", line 11, in <module>
    sys.exit(main())
  File "/Users/ryan/local/lib/python2.7/site-packages/youtube_dl/__init__.py", line 419, in main
    _real_main(argv)
  File "/Users/ryan/local/lib/python2.7/site-packages/youtube_dl/__init__.py", line 409, in _real_main
    retcode = ydl.download(all_urls)
  File "/Users/ryan/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1725, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/Users/ryan/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "/Users/ryan/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 323, in extract
    return self._real_extract(url)
  File "/Users/ryan/local/lib/python2.7/site-packages/youtube_dl/extractor/gdcvault.py", line 184, in _real_extract
    xml_description_url = xml_root + 'xml/' + xml_name
TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'
```

### Description of your *issue*, suggested solution and other information

youtube-dl raises an exception when trying to download free 2016 GDC Vault videos like http://gdcvault.com/play/1023657/Escaping-the-Holodeck-Storytelling-and . evidently `xml_root` at `extractor/gdcvault.py:184` is assumed to be a string, but in this case is `None`.

the earlier log messages about needing a login are also suspicious, but may not be related.

the couple other currently open GDC Vault issues (#2673, #4170) are different bugs.

thanks in advance!

**Comment by jaimeMF** [comment]
Fixed with 3c6c7e7d7e5a7cbf87385bf3c649342c3ee4327d, it will be available in the next release. But thanks for reporting the issue!
