### ISSUE TITLE
[MinistryGrid] Not working anymore

### ISSUE THREAD

**Issue by gineadai** [rg3/youtube-dl#9140]
tt4g-2014-conference/the-gospel-by-numbers-4/the-gospel-by-numbers
`Unable to extract p_l_id;`

**Comment by yan12125** [comment]
Well seems all issues opened by @gineadai are now 404.

**Comment by yan12125** [comment]
Fixed in 8cb57bab8e98c667c13e1da22b96d97bc37cfe78.
