### ISSUE TITLE
[stanfordoc] unable to extract description

### ISSUE THREAD

**Issue by gineadai** [rg3/youtube-dl#9147]
http://openclassroom.stanford.edu/MainFolder/VideoPage.php?course=PracticalUnix&video=intro-environment&speed=100

**Comment by yan12125** [comment]
@remitamine Did you get the same error with 2016.04.06? It works fine for me.

**Comment by remitamine** [comment]
no i didn't see the error. i just opened it because the commit that made the issue closed is wrong.
i'm no sure if `text` element in the xml can be used as a description. if not than feel free to close it as invalid issue.
sorry for error, i should check the envirenment, read the issue carefully and test many times before making changes and additions to the code.

**Comment by yan12125** [comment]
@gineadai Please post the full verbose log if this error still occurs in version 2016.04.06.

**Comment by gineadai** [comment]
@yan12125 Error still occrurs in version 2016.04.13, i run --verbose and not found nothing useful, just my system info, on two different machines and operating systems.

**Comment by yan12125** [comment]
Please paste the output of the following command:
```
youtube-dl --verbose "http://openclassroom.stanford.edu/MainFolder/VideoPage.php?course=PracticalUnix&video=intro-environment&speed=100"
```

**Comment by gineadai** [comment]
`[debug] System config: []
[debug] User config: ['-4', '--prefer-free-formats', '--no-cache-dir', '--no-mtime', '--youtube-skip-dash-manifest']
[debug] Command-line args: ['--verbose', 'http://openclassroom.stanford.edu/MainFolder/VideoPage.php?course=PracticalUnix']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Python version 3.5.1+ - Linux-4.5.0-gnu.nonpae-i686-with-debian-stretch-sid
`

**Comment by gineadai** [comment]
```
[debug] System config: []
[debug] User config: ['-4', '--prefer-free-formats', '--no-cache-dir', '--no-mtime', '--youtube-skip-dash-manifest']
[debug] Command-line args: ['--verbose', 'http://openclassroom.stanford.edu/MainFolder/VideoPage.php?course=PracticalUnix']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Python version 3.5.1+ - Linux-4.5.0-gnu.nonpae-i686-with-debian-stretch-sid
```

**Comment by gineadai** [comment]
I understand problem,  link without "" not work.

**Comment by dstftw** [comment]
Of course [it won't work](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).

**Comment by gineadai** [comment]
Okey, then.  Now i will know. Sorry for trouble.
