### ISSUE TITLE
Add a "--match-description" option.

### ISSUE THREAD

**Issue by sebma** [rg3/youtube-dl#9149]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.04.06_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---
### Description of your _issue_, suggested solution and other information

Explanation of your _issue_ in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
## If work on your _issue_ required an account credentials please provide them or explain how one can obtain them.

Hi, can you add a `--match-description` option that searches for a string amongst the description of a video ?

Thanks.

**Comment by yan12125** [comment]
```--match-filter``` should be enough. Post more details if you have problems.

**Comment by sebma** [comment]
Hi, I agree but what would then be the equivalent of:

`--match-description myString`

**Comment by yan12125** [comment]
Could you give a concrete URL and your expectations?

**Comment by sebma** [comment]
Sure:

youtube-dl --match-description karambiri https://www.youtube.com/channel/UCFyNsaSkagjA-z-o6qf10nA/videos

**Comment by yan12125** [comment]
> containing the string karambiri in their description.

Currently only exact matching is implemented.

**Comment by phansen01** [comment]
Would something like (similar to how match_filter is made)...

```python

"""in utils.py"""
def match_desc_str(filter_str,dct):
    return all(dct.get('description').find(item) for item in filter_str.split('&'))

def match_desc_func(filter_str):
    def _match_desc(info_dict):
        if match_desc_str(filter_str,info_dict):
            return None
        else:
            return "error message goes here"
    return _match_desc

```

...and in YoutubeDL.py...

```python
"""in _match_entry"""
#...
#...
    if not incomplete:
        match_filter = self.params.get('match_filter')
        if match_filter is not None:
            ret = match_filter(info_dict)
            if ret is not None:
                return ret
        match_desc = self.params.get('match_desc')
        if match_filter is not None:
            ret = match_desc(info_dict)
            if ret is not None:
                return ret
        
        return None
```

...with the corresponding option added in options.py added work?

**Comment by yan12125** [comment]
Thanks phansen01 for the idea. A guideline in youtube-dl is don't add new options if a new feature can be implemented by improving existing options. As a result, this issue is actually the same as #9092. Please move there for further discussions.
