### ISSUE TITLE
Cannot download from YouTube

### ISSUE THREAD

**Issue by sunxvogy** [rg3/youtube-dl#9150]
C:\Users\Administrator\Desktop>youtube-dl0406 --no-cache-dir --no-check-certific
ate --no-playlist https://www.youtube.com/watch?v=7RMQksXpQSk -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--no-cache-dir', u'--no-check-certificate', u'--no
-playlist', u'https://www.youtube.com/watch?v=7RMQksXpQSk', u'-v']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] 7RMQksXpQSk: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 10053] > (caused by URL
Error(error(10053, ''),))
  File "youtube_dl\extractor\common.pyo", line 371, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1935, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 859, in https_open
  File "urllib2.pyo", line 1197, in do_open

**Comment by dstftw** [comment]
Most likely a connectivity problem. Can you watch it in browser without any kind of unblocking tools?

**Comment by sunxvogy** [comment]
Yes, I can watch videos in my Browser with no problem...

**Comment by yan12125** [comment]
Did you use any YouTube related or proxy/VPN browser extensions?

**Comment by sunxvogy** [comment]
YES, I used a VPN...

**Comment by yan12125** [comment]
Usually VPNs are applied to the whole system. If your VPN applies only to the browser, ask your VPN provider how to use it in other programs.
