### ISSUE TITLE
Soundcloud music downloader, post processing error

### ISSUE THREAD

**Issue by willyt1200** [rg3/youtube-dl#9151]
Hi, im trying to create a python code that I will enter a soundcloud link(Single song, artist, or playlist) and will download it for me.

It downloads the song correctly but as random numbers(186407146) link is https://soundcloud.com/tevin-beckles/no-role-modelz-yl-ft-jcole

Also when running the code I get many errors in which im too dumb to understand:
http://pastebin.com/Dava3j2j

If someone could help me resolve the ID issue and the errors that would be great.

Thanks

**Comment by willyt1200** [comment]
Also when trying to download a playlist it downloads the first song then fails...

**Comment by dstftw** [comment]
1. It clearly tells you in log:
>ffprobe or avprobe not found. Please install one.

2. Post the code of your script.

**Comment by willyt1200** [comment]
http://pastebin.com/MWP77rMa

**Comment by dstftw** [comment]
>It downloads the song correctly but as random numbers(186407146) 

That's exactly what you ask youtube-dl to do:
>'outtmpl': '%(id)s.%(ext)s'
