### ISSUE TITLE
ERROR: Unable to extract preview url; for some mixcloud urls

### ISSUE THREAD

**Issue by vaibhav1312** [rg3/youtube-dl#9156]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -g -v "https://www.mixcloud.com/JoeSoHeady/eminem-mix/"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-g', u'-v', u'https://www.mixcloud.com/JoeSoHeady/eminem-mix/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.6 - Linux-3.13.0-71-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to extract preview url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/vaibhav/public_html/downloadenv/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "/home/vaibhav/public_html/downloadenv/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 323, in extract
    return self._real_extract(url)
  File "/home/vaibhav/public_html/downloadenv/local/lib/python2.7/site-packages/youtube_dl/extractor/mixcloud.py", line 67, in _real_extract
    r'\s(?:data-preview-url|m-preview)="([^"]+)"', webpage, 'preview url')
  File "/home/vaibhav/public_html/downloadenv/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 627, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract preview url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

With the same version of youtube-dl i.e. 2016.04.06 running on Mac OS X, the issue does not occur but, on my server running Ubuntu 14.04, problem occurs.

Also the issue is with few urls of mixcloud, with some of the mixcloud urls youtube-dl works fine.

**Comment by dstftw** [comment]
Post the output of `youtube-dl --dump-pages https://www.mixcloud.com/JoeSoHeady/eminem-mix/`.

**Comment by vaibhav1312** [comment]
Output of command 
$ youtube-dl --dump-pages https://www.mixcloud.com/JoeSoHeady/eminem-mix/
is in the attached text file i.e output.txt
[output.txt](https://github.com/rg3/youtube-dl/files/213116/output.txt)

**Comment by dstftw** [comment]
>Sorry, this upload is unavailable in your country due to licensing restrictions
