### ISSUE TITLE
usage of "ETA" is ambiguous and non-standard, "time remaining" should be used

### ISSUE THREAD

**Issue by petfold** [rg3/youtube-dl#9160]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

this is trying to reopen issue 9072

(capitals here are not meant as shouting)
WHILE DOWNLOADING, YOUTUBE-DL GIVES FEEDBACK SUCH AS

[download] 35.1% of 576.20MiB at 360.25KiB/s ETA 17:42

IN THIS LINE, THE USE OF "ETA" IS INCORRECT. WHAT YOU WANT TO SAY IS THAT THE DOWNLOAD IS EXPECTED TO FINISH 17 MINUTES FROM NOW. ETA ALWAYS MEANS AN ABSOLUTE TIME (ESTIMATED TIME OF ARRIVAL). INSTEAD OF "ETA" IT SHOULD SAY "remaining time" OR "remaining". IT'S NOT ETA, PLEASE CHANGE THIS, THANKS.

Even if you close my ticket and even if you cite Bittorrent as using it, it is an incorrect usage. The term comes from aviation and I asked pilots who confirm this is only used with absolute time.
Look it is not essential for me that you don't make fools of yourselves. I am just trying to help you. But if you resist, I give up on you and your attitude. I will also submit a bug report to bittorrent, maybe they have more sense. Which bittorrent client did you mean?

The fact fact that I am right is clear from how in some applications both ETA and remaining time is displayed (e.g. Waze). In this case both are referred to correctly. I am really puzzled by why you insist confusing your users by using an incorrect, or at least ambiguous term.

**Comment by dstftw** [comment]
We are not pilots to strictly follow aviation terminology. Most of existing downloaders use ETA as time remaining and I see no point changing this wording. Needless to say this will break clients who parse progress and rely on this template.
