### ISSUE TITLE
Only attempt to download new soundcloud tracks?

### ISSUE THREAD

**Issue by NickWinston123** [rg3/youtube-dl#9161]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Is there a way to only attempt to download newer sound cloud tracks?

For instance, I have a crontab that runs a sh file every day, which downdownloads a specific users tacks (in attempt to auto update the folder )

This takes forever though, because it attempts to download every song (even the downloaded ones)
Is there a way for youtube-dl to keep a log of what has been downloaded and only attempt to download the newer tracks (ones not already downloaded)?

**Comment by dstftw** [comment]
`--download-archive`.

**Comment by NickWinston123** [comment]
@dstftw 
Thank you, do i just add --download-archive to the end of my usual command or do I need to make the file and do --download-archive file.txt?

**Comment by NickWinston123** [comment]
@dstftw nvm I think i got it
