### ISSUE TITLE
Unable to download JSON metadata for UDEMY

### ISSUE THREAD

**Issue by crouzilles** [rg3/youtube-dl#9166]
C:\Users\xbourgui>youtube-dl.exe --netrc --verbose "https://www.udemy.com/understand-nodejs/learn/v4/content"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--netrc', u'--verbose', u'https://www.udemy.com/understand-nodejs/learn/v4/content']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.02.22
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-79253-g8005b6d, ffprobe N-79253-g8005b6d
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as NoNeedToKnow;)
[udemy:course] understand-nodejs: Downloading webpage
[udemy:course] understand-nodejs: Downloading course JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: NOT FOUND (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 355, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1905, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
