### ISSUE TITLE
[ARD] Mediathek Subtitle format

### ISSUE THREAD

**Issue by a-l-e-k** [rg3/youtube-dl#9167]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) 
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues

- [x] Bug report (encountered problems with youtube-dl)

The subtitle in ARD Mediathek is ttml (EBU-TT-D-Basic-DE) but the downloaded file gets the extension srt. In post-processing you get this message:
```
[info] Writing video subtitles to: 34251192.de.srt
[ffmpeg] Converting subtitles
[ffmpeg] Subtitle file for srt is already in the requestedformat
```
When you try to convert the .srt named file to ass or vtt format you get this message:
```
[ffmpeg] Converting subtitles
ERROR: file: 34251192.de.srt: Invalid data found when processing input
```

**Comment by dstftw** [comment]
Carefully read the new issue template and provide all required data.
