### ISSUE TITLE
Popular uploads playlist gives "Unknown error" and unable to download

### ISSUE THREAD

**Issue by Dummy101** [rg3/youtube-dl#9170]
I'm unable to download an uploader's Popular Uploads playlist.
The link I'm trying to use:
https://www.youtube.com/watch?v=z-HKvYDTpoc&list=PUQ2F23CWMIS8xCW800MMF4A
The command I'm passing via terminal:
youtube-dl -c --verbose "https://www.youtube.com/watch?v=z-HKvYDTpoc&list=PUQ2F23CWMIS8xCW800MMF4A"

The log of errors:
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-c', u'--verbose', u'https://www.youtube.com/watch?v=z-HKvYDTpoc&list=PUQ2F23CWMIS8xCW800MMF4A']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-79277-g0c90b2e, ffprobe N-79277-g0c90b2e
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PUQ2F23CWMIS8xCW800MMF4A - add --no-playlist to just download video z-HKvYDTpoc
[youtube:playlist] PUQ2F23CWMIS8xCW800MMF4A: Downloading webpage
WARNING: [youtube:playlist] Youtube gives an alert message: Unknown error.
ERROR: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 669, in extract_info
  File "youtube_dl\extractor\common.pyo", line 323, in extract
  File "youtube_dl\extractor\youtube.pyo", line 1891, in _real_extract
  File "youtube_dl\extractor\youtube.pyo", line 1861, in _extract_playlist
  File "youtube_dl\extractor\common.pyo", line 636, in _html_search_regex
  File "youtube_dl\extractor\common.pyo", line 627, in _search_regex
RegexNotFoundError: Unable to extract title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Carefully read the new issue template and provide all requested information.

**Comment by Dummy101** [comment]
Yup, sorry about that. Editted accordingly.

**Comment by Dummy101** [comment]
Awesome, thanks. When might I expect the .exe to also be updated?

**Comment by dstftw** [comment]
No ETA.
