### ISSUE TITLE
The "--add-metadata" does not set the URL in the MP4 metadata

### ISSUE THREAD

**Issue by sebma** [rg3/youtube-dl#9172]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.06*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.
---
Hi,

The `--add-metadata` does not set the URL in the MP4 metadata:

```
youtube-dl -v --ignore-config -f18 --add-metadata --prefer-ffmpeg https://www.youtube.com/watch?v=PUYs3KoBFOc
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--ignore-config', u'-f18', u'--add-metadata', u'--prefer-ffmpeg', u'https://www.youtube.com/watch?v=PUYs3KoBFOc']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.05
[debug] Python version 2.7.8 - Linux-3.16.0-44-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 3.0.1-1, ffprobe 3.0.1-1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] PUYs3KoBFOc: Downloading webpage
[youtube] PUYs3KoBFOc: Downloading video info webpage
[youtube] PUYs3KoBFOc: Extracting video information
[youtube] PUYs3KoBFOc: Downloading MPD manifest
[debug] Invoking downloader on u'https://r4---sn-25ge7n76.googlevideo.com/videoplayback?signature=C930F7B110E213CDA797AC776669D7557468659F.2ECD3527EF19F3753B878F3350C578C1AFE407F6&sver=3&requiressl=yes&mt=1460492309&pl=21&dur=5526.743&lmt=1387500766085194&ip=128.78.236.200&ms=au&mv=m&source=youtube&id=o-AMQW0Bz8iKZoqba1jru8Pvj8GlMxtQ_wuzGm6ltMWxb_&mn=sn-25ge7n76&mm=31&key=yt6&expire=1460514012&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&upn=91icWEVKEC8&mime=video%2Fmp4&itag=18&ratebypass=yes&fexp=9405995%2C9416126%2C9416891%2C9420452%2C9422596%2C9423662%2C9424490%2C9426927%2C9427324%2C9427413%2C9427902%2C9428398%2C9429119%2C9429379%2C9430020%2C9430066%2C9431366%2C9432684%2C9433114%2C9433892&ipbits=0&nh=IgpwcjAxLnBhcjAxKgkxMjcuMC4wLjE&initcwndbps=913750'
[download] Resuming download at byte 247006371
[download] Destination: mamadou karambiri - Comment liberer la nouvelle creation prise en otage-PUYs3KoBFOc.mp4
[download] 100% of 272.28MiB in 00:21
[ffmpeg] Adding metadata to 'mamadou karambiri - Comment liberer la nouvelle creation prise en otage-PUYs3KoBFOc.mp4'
[debug] ffmpeg command line: ffmpeg -y -i 'file:mamadou karambiri - Comment liberer la nouvelle creation prise en otage-PUYs3KoBFOc.mp4' -c copy -metadata comment= -metadata description= -metadata artist=herveekis -metadata 'title=mamadou karambiri - Comment liberer la nouvelle creation prise en otage' -metadata date=20130716 -metadata 'purl=https://www.youtube.com/watch?v=PUYs3KoBFOc' 'file:mamadou karambiri - Comment liberer la nouvelle creation prise en otage-PUYs3KoBFOc.temp.mp4'

mp4info 'mamadou karambiri - Comment liberer la nouvelle creation prise en otage-PUYs3KoBFOc.mp4' | egrep -i "url|www|http"
echo $?
1
ffprobe 'mamadou karambiri - Comment liberer la nouvelle creation prise en otage-PUYs3KoBFOc.mp4' | egrep -i "url|www|http"
echo $?
1

```

**Comment by dstftw** [comment]
There is no URL field in mp4.
