### ISSUE TITLE
Downloading from tenplay fails with "forbidden by access policy"

### ISSUE THREAD

**Issue by MrPeach** [rg3/youtube-dl#9176]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.06**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

My initial download attempt:

youtube-dl -v --verbose http://tenplay.com.au/channel-eleven/angel-from-hell/season-2015/episode-7
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--verbose', u'http://tenplay.com.au/channel-eleven/angel-from-hell/season-2015/episode-7']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Windows-XP-5.1.2600-SP3
[debug] exe versions: ffmpeg N-70145-g721c916, ffprobe N-70145-g721c916, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://172.20.1.49:8080', u'https': 'http://172.20.1.49:8080'}
[generic] episode-7: Requesting header
WARNING: Falling back on generic information extractor.
[generic] episode-7: Downloading webpage
[generic] episode-7: Extracting information
[download] Downloading playlist: Angel From Hell - S1 Ep. 7 - Network Ten
[generic] playlist Angel From Hell - S1 Ep. 7 - Network Ten: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 4825514928001: Downloading webpage
[brightcove:new] 4825514928001: Downloading JSON metadata
ERROR: Access to this resource is forbidden by access policy.
Traceback (most recent call last):
  File "youtube_dl\extractor\brightcove.pyo", line 511, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 516, in _download_json
  File "youtube_dl\extractor\common.pyo", line 484, in _download_webpage
  File "youtube_dl\extractor\common.pyo", line 391, in _download_webpage_handle
  File "youtube_dl\extractor\common.pyo", line 380, in _request_webpage
ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 669, in extract_info
  File "youtube_dl\extractor\common.pyo", line 323, in extract
  File "youtube_dl\extractor\brightcove.pyo", line 516, in _real_extract
ExtractorError: Access to this resource is forbidden by access policy.

I also tried the following from a previous report of a tenplay issue that was recent resolved:

youtube-dl --verbose http://players.brightcove.net/2199827728001/4kPfcMUoe_default/index.html?videoId=4821193673001
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://players.brightcove.net/2199827728001/4kPfcMUoe_default/index.html?videoId=4821193673001']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[brightcove:new] 4821193673001: Downloading webpage
[brightcove:new] 4821193673001: Downloading JSON metadata
ERROR: Access to this resource is forbidden by access policy.
Traceback (most recent call last):
  File "youtube_dl\extractor\brightcove.pyo", line 511, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 516, in _download_json
  File "youtube_dl\extractor\common.pyo", line 484, in _download_webpage
  File "youtube_dl\extractor\common.pyo", line 391, in _download_webpage_handle
  File "youtube_dl\extractor\common.pyo", line 380, in _request_webpage
ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 669, in extract_info
  File "youtube_dl\extractor\common.pyo", line 323, in extract
  File "youtube_dl\extractor\brightcove.pyo", line 516, in _real_extract
ExtractorError: Access to this resource is forbidden by access policy.

**Comment by puncy** [comment]
works perfectly fine for me 

image - http://i.imgur.com/4nyTt1Q.png

**Comment by yan12125** [comment]
@MrPeach This video is georestricted. "Access to this resource is forbidden by access policy." may be confusing but have the same meaning.

**Comment by educationtry** [comment]
Allavsoft still works to download videos from tenplay, abc iview, etc
