### ISSUE TITLE
-bestaudio possible to choose m4a over webm?

### ISSUE THREAD

**Issue by sunk818** [rg3/youtube-dl#9187]
I'm using youtube-dl -f bestaudio to download stuff from YouTube.

I typically use -f 141 but on older videos or lower resolution videos, only -f 140 seems to be available. 

I tried using -bestaudio over -f 141 or -f 140, but it seems .webm is sometimes chosen instead of the preferred m4a (personal preference).

Is there syntax currently that let's me pick the best .m4a? I don't mind .webm, but my iPhone 6 doesn't support .webm audio playback on Dropbox but .m4a is supported natively.

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl#format-selection

**Comment by sunk818** [comment]
Sorry, I didn't know I could use `youtubel-dl -f m4a `
