### ISSUE TITLE
Arte 7 does not work for some videos

### ISSUE THREAD

**Issue by belvy** [rg3/youtube-dl#9189]
# Arte +7 (France) not working for some videos for one or 2 weeks:

example 1:
http://www.arte.tv/guide/fr/058000-001-A/our-girl-molly-une-femme-au-combat-1-7?autoplay=1

youtube-dl -v -f HTTP_MP4_EQ_3 http://www.arte.tv/guide/fr/058000-001-A/our-girl-molly-une-femme-au-combat-1-7?autoplay=1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'HTTP_MP4_EQ_3', u'http://www.arte.tv/guide/fr/058000-001-A/our-girl-molly-une-femme-au-combat-1-7?autoplay=1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Python version 2.7.10 - Linux-4.0.4-x86_64-with-glibc2.2.5
[debug] exe versions: none
[debug] Proxy map: {}
[arte.tv:+7] 058000-001-A: Downloading webpage
[arte.tv:+7] 058000-001-A: Downloading player page
[arte.tv:+7] 058000-001-A: Downloading JSON metadata
[arte.tv:+7] 058000-001-A: Checking HLS_XQ_2 video format URL
[arte.tv:+7] 058000-001-A: Checking HLS_XQ_3 video format URL
[arte.tv:+7] 058000-001-A: Checking HLS_XQ_1 video format URL
[arte.tv:+7] 058000-001-A: Checking HLS_SQ_3 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_EQ_8 video format URL
[arte.tv:+7] 058000-001-A: Checking HLS_SQ_1 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_SQ_3 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_SQ_2 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_SQ_1 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_EQ_1 video format URL
[arte.tv:+7] 058000-001-A: Checking HLS_XQ_8 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_EQ_3 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_EQ_2 video format URL
[arte.tv:+7] 058000-001-A: Checking HLS_SQ_8 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_MQ_1 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_MQ_3 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_MQ_2 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_MQ_8 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_HQ_2 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_HQ_3 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_HQ_1 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_HQ_8 video format URL
[arte.tv:+7] 058000-001-A: Checking HTTP_MP4_SQ_8 video format URL
[arte.tv:+7] 058000-001-A: Checking HLS_SQ_2 video format URL
[debug] Invoking downloader on u'http://arte.gl-systemhaus.de/am/tvguide/EUR_DE_FR/058000-001-A_EQ_2_VO-STF_02273543_MP4-1500_AMM-Tvguide.mp4'
[download] Resuming download at byte 805502

ERROR: Did not get any data blocks
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
    _real_main(argv)
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1730, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 727, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1376, in process_video_result
    self.process_info(new_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1638, in process_info
    success = dl(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1580, in dl
    return fd.download(name, info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 230, in real_download
    self.report_error('Did not get any data blocks')
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 161, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 545, in report_error
    self.trouble(error_message, tb)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 507, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

# Example 2: http://www.arte.tv/guide/fr/050321-000-A/les-drones-un-usage-controverse?autoplay=1

youtube-dl -f HTTP_MP4_EQ_1 http://www.arte.tv/guide/fr/050321-000-A/les-drones-un-usage-controverse?autoplay=1
[arte.tv:+7] 050321-000-A: Downloading webpage
[arte.tv:+7] 050321-000-A: Downloading player page
[arte.tv:+7] 050321-000-A: Downloading JSON metadata
[arte.tv:+7] 050321-000-A: Checking HLS_XQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_XQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_EQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_SQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_SQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_SQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_EQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_XQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_EQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_SQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_MQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_MQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_MQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_HQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_HQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_HQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_SQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_SQ_2 video format URL
[download] Destination: Les drones, un usage controversé-050321-000-A.mp4
[download]   0.2% of 538.72MiB at 701.07KiB/s ETA 13:05ERROR: content too short (expected 564892238 bytes and served 963542)
youtube-dl -f HTTP_MP4_EQ_1 http://www.arte.tv/guide/fr/050321-000-A/les-drones-un-usage-controverse?autoplay=1
[arte.tv:+7] 050321-000-A: Downloading webpage
[arte.tv:+7] 050321-000-A: Downloading player page
[arte.tv:+7] 050321-000-A: Downloading JSON metadata
[arte.tv:+7] 050321-000-A: Checking HLS_XQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_XQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_EQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_SQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_SQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_SQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_EQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_XQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_EQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_SQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_MQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_MQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_MQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_HQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_HQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_HQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_SQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_SQ_2 video format URL
[download] Resuming download at byte 963542

ERROR: Did not get any data blocks
youtube-dl -v -f HTTP_MP4_EQ_1 http://www.arte.tv/guide/fr/050321-000-A/les-drones-un-usage-controverse?autoplay=1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-f', u'HTTP_MP4_EQ_1', u'http://www.arte.tv/guide/fr/050321-000-A/les-drones-un-usage-controverse?autoplay=1']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Python version 2.7.10 - Linux-4.0.4-x86_64-with-glibc2.2.5
[debug] exe versions: none
[debug] Proxy map: {}
[arte.tv:+7] 050321-000-A: Downloading webpage
[arte.tv:+7] 050321-000-A: Downloading player page
[arte.tv:+7] 050321-000-A: Downloading JSON metadata
[arte.tv:+7] 050321-000-A: Checking HLS_XQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_XQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_EQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_SQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_SQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_SQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_EQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_XQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_EQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_SQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_MQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_MQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_MQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_HQ_2 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_HQ_1 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_HQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HTTP_MP4_SQ_8 video format URL
[arte.tv:+7] 050321-000-A: Checking HLS_SQ_2 video format URL
[debug] Invoking downloader on u'http://arte.gl-systemhaus.de/am/tvguide/EUR_DE_FR/050321-000-A_EQ_2_VF-STF_02275486_MP4-1500_AMM-Tvguide.mp4'
[download] Resuming download at byte 963542

ERROR: Did not get any data blocks
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 419, in main
    _real_main(argv)
  File "/usr/bin/youtube-dl/youtube_dl/__init__.py", line 409, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1730, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 727, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1376, in process_video_result
    self.process_info(new_info)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1638, in process_info
    success = dl(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1580, in dl
    return fd.download(name, info)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/bin/youtube-dl/youtube_dl/downloader/http.py", line 230, in real_download
    self.report_error('Did not get any data blocks')
  File "/usr/bin/youtube-dl/youtube_dl/downloader/common.py", line 161, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 545, in report_error
    self.trouble(error_message, tb)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 507, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by dstftw** [comment]
All provided links work fine for me. content too short error usually means an issue with your connection or server side error.
