### ISSUE TITLE
how to re-stream (using less disk as possibile)?

### ISSUE THREAD

**Issue by kintaro1981** [rg3/youtube-dl#9191]
I would like to re-stream a **downloading**.
Can you give me some hint?

Maybe using VLC piping it at the youtube-dl command?
Is it possibile to not download the whole video but simply re-stream it live using less disk space as possible?

Regards

**Comment by yan12125** [comment]
Do you mean #2124?

**Comment by kintaro1981** [comment]
yes! thank you, I searched but with "stream" too many issues came up! Thank you
