### ISSUE TITLE
Extend variables used with the -o flag to other flags 

### ISSUE THREAD

**Issue by TheSqrtMinus1** [rg3/youtube-dl#9201]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.13**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

Please allow the variables used with the -o flag (%(title)s , %(uploader)s , etc) to also be used with other flags such as
--write-description
--write-info-json
--write-annotations
--download-archive
&tc.

It would make my life a whole lot easier.

**Comment by dstftw** [comment]
Just parse JSON, we are not going to bloat the cli interface with all these commands.

**Comment by TheSqrtMinus1** [comment]
I have literally no idea how to do that

**Comment by deryni** [comment]
How would expanding the formatting support you already have to other output file arguments "bloat" the cli interface exactly?

**Comment by TheSqrtMinus1** [comment]
Bump.

**Comment by dstftw** [comment]
You should better describe your issue. None of
```
--write-description
--write-info-json
--write-annotations
```
receive any parameters so `-o` does not make any sense for them. I thought first your request is about adding `--write-upload` etc. Still adding template support for `--download-archive` is [bad idea](https://github.com/rg3/youtube-dl/issues/9185#issuecomment-210887708).

**Comment by TheSqrtMinus1** [comment]
My issue is that I'm downloading entire youtube channels to folders that are named via vars used with the -o flag. Since the --download-archive flag doesn't take any variables from the -o flag, I have to manually move them after the fact, which defeats the whole purpose of an automated script.
