### ISSUE TITLE
Support to http://www.stream2watch.co

### ISSUE THREAD

**Issue by M13SAI-25BK** [rg3/youtube-dl#9202]
live tv streaming:
AMC - http://www.stream2watch.co/live-now/live-tv/us/amc-live-stream
HBO - http://www.stream2watch.co/live-now/live-tv/us/hbo-live-stream

**Comment by yan12125** [comment]
Please provide at least one example URL. See https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient.

**Comment by dstftw** [comment]
youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free).
