### ISSUE TITLE
CBS.com videos don't work anymore

### ISSUE THREAD

**Issue by JohnnyW204** [rg3/youtube-dl#9208]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.13**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.13
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: ffmpeg N-74737-g1acd631, ffprobe N-74737-g1acd631
[debug] Proxy map: {}
...
<end of log>

So CBS.com videos don't work anymore.
I get something like this instead for every segment of the video:
[http @ 000000000543eb60] HTTP error 403 Forbidden
[crypto @ 0000000005354ae0] Unable to open resource: http://cbsios-vh.akamaihd.n
et/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_
Entertainment/2016/04/12/664529987818/CBS_SURVIVOR_3209_CONTENT_CIAN_vr_20M_8003
91_,3596,2596,1848,1248,848,548,298,158,000.mp4.csmil/segment1_0_av.ts?null=0&id
=AgAvEW9rotg7T8dFEVdwFFXxkeGyxrI0E657OO1K3Covwwb3VP05oNTRH4Ciq+fd3w3O6cjHQRKN0A%
3d%3d
[hls,applehttp @ 0000000002f49d00] Failed to open segment of playlist 0
[http @ 000000000549ac60] HTTP error 403 Forbidden
[crypto @ 000000000543eb60] Unable to open resource: http://cbsios-vh.akamaihd.n
et/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_
Entertainment/2016/04/12/664529987818/CBS_SURVIVOR_3209_CONTENT_CIAN_vr_20M_8003
91_,3596,2596,1848,1248,848,548,298,158,000.mp4.csmil/segment2_0_av.ts?null=0&id
=AgAvEW9rotg7T8dFEVdwFFXxkeGyxrI0E657OO1K3Covwwb3VP05oNTRH4Ciq+fd3w3O6cjHQRKN0A%
3d%3d

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by JohnnyW204** [comment]
I tried this:
http://www.cbs.com/shows/survivor/video/5B3F45FC-BCD4-00CF-3DD0-0C40860A256C/survivor-brains-vs-brawn-vs-beauty-it-s-psychological-warfare/

And this was the error message:
ERROR: ffmpeg exited with code 1
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 419, in main
  File "youtube_dl\__init__.pyo", line 409, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1730, in download
  File "youtube_dl\YoutubeDL.pyo", line 682, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 727, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1376, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1638, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1580, in dl
  File "youtube_dl\downloader\common.pyo", line 350, in download
  File "youtube_dl\downloader\external.pyo", line 42, in real_download
  File "youtube_dl\downloader\common.pyo", line 161, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 545, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 507, in trouble

**Comment by dstftw** [comment]
Update ffmpeg.

**Comment by JohnnyW204** [comment]
That worked. Thanks so much!
