### ISSUE TITLE
Downloading from nrk.no broken

### ISSUE THREAD

**Issue by trikinov** [rg3/youtube-dl#9209]
# youtube-dl https://tv.nrk.no/serie/vera/KOIF28002115/sesong-6/episode-1 
[NRKTV] KOIF28002115: Downloading webpage
[NRKTV] KOIF28002115: Downloading f4m manifest
[NRKTV] KOIF28002115: Downloading m3u8 information
WARNING: Your copy of avconv is outdated and unable to properly mux separate video and audio files, youtube-dl will download single file media. Update avconv to version 10-0 or newer to fix this.
[download] Destination: Vera-KOIF28002115.mp4
WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
avconv version 0.8.17-6:0.8.17-2, Copyright (c) 2000-2014 the Libav developers
  built on Mar  2 2016 22:53:14 with gcc 4.7.2
Unrecognized option 'headers'
Failed to set value 'Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: _alid_=7xTJhe3wFC5ayFXFG0IurQ==
' for option 'headers'

ERROR: ffmpeg exited with code 1

**Comment by dstftw** [comment]
>WARNING: Your copy of avconv is outdated, update avconv to version 10-0 or newer if you encounter any errors.
