### ISSUE TITLE
"Hidden" Vimeo Videos are an "Unsupported URL"

### ISSUE THREAD

**Issue by danfiscus** [rg3/youtube-dl#9229]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.13*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://vimeo.com/160743502/abd0e13fb4
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://vimeo.com/160743502/abd0e13fb4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.13
[debug] Python version 2.7.10 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.7.1, ffprobe 2.7.1
[debug] Proxy map: {}
[generic] abd0e13fb4: Requesting header
WARNING: Falling back on generic information extractor.
[generic] abd0e13fb4: Downloading webpage
[generic] abd0e13fb4: Extracting information
ERROR: Unsupported URL: https://vimeo.com/160743502/abd0e13fb4
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1360, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 279, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/usr/local/bin/youtube-dl/youtube_dl/compat.py", line 268, in _XML
    parser.feed(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 92, column 136
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 671, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2024, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://vimeo.com/160743502/abd0e13fb4
```

---

### Description of your *issue*, suggested solution and other information

I was attempting to download a video from Vimeo with an unusual URL (I believe it is hidden in some way only available to Pro users, as I was unable to find a privacy setting that resulted in a similar URL scheme when uploading a test video to my account. The URL is a valid video, and when you visit it it looks like a normal Vimeo player page, but `youtube-dl` doesn't recognize the URL scheme as valid for some reason.

**Comment by LeoLamCY** [comment]
After a quick look at the vimeo extractor, it seems to only match query strings like `/?param1=abc&param2=def` after the video `id` at the end and not an arbitrary string like `abd0e13fb4` in your link.
Either remove the string after the video `id` or the vimeo extractor will need to be updated to ignore non query strings if they don't serve any purpose.

**Comment by danfiscus** [comment]
@LeoLamCY The URL requires the second part of the string as well, so the extractor needs to be updated.
