### ISSUE TITLE
Wishlist: --download-missing 

### ISSUE THREAD

**Issue by etnoy** [rg3/youtube-dl#9234]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.13*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.13**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Description of your *issue*, suggested solution and other information

I am extremely grateful for youtube-dl and it integrates extremely well into my Plex setup that allows me to watch long YouTube playlists via offline Plex syncing on my devices. 

I have read the documentation and tried to work this feature out, but as far as I know, the following feature is not implemented: automatic downloading of missing playlist episodes.

The goal is to have youtube-dl being called from a cron script for each playlist that I am watching where I can make youtube-dl go through the playlist and download missing episodes (usually new episodes added at the end of the playlist). The script could then be called daily, which downloads episodes, and these episodes are then in turn synced by Plex to my mobile devices.

Strictly speaking, this feature already exists, but it hammers YouTube and appears to re-download the entire playlist. I believe that if I did this from cron, the excessive traffic would cause YT do block me in some way. Also, I am aware of --playlist-start, however I don't see a way to make a script know which number to give to youtube-dl.

The wish list is then
youtube-dl --download-missing <youtube playlist>

Please let me know if this can be done in some way already, or if already exists (but I can't find it). Thanks!

**Comment by yan12125** [comment]
```--download-archive``` should fit your need.

**Comment by etnoy** [comment]
Thanks for replying quickly. I was not aware of this usage of download-archive, it was not obvious from the documentation. Is there a quick way to append all existing video ID:s of my downloaded videos, or should I go ahead and call youtube-dl again on all playlists I've downloaded so far (>1000 videos)? Thanks again!

**Comment by yan12125** [comment]
> should I go ahead and call youtube-dl again on all playlists I've downloaded so far (>1000 videos)?

Unfortunately yes. You can also create an ```archive.txt``` manually. It's format is straightforward: 
```<site_name> <video_id>```.
```
youtube BaW_jenozKc
youtube UxxajLWwzqY
```

**Comment by etnoy** [comment]
Awesome, thanks. I'll probably generate the archive file from a shell script. Keep up the good work!

**Comment by etnoy** [comment]
For future googlers who find this page: I used the following command to download all video id:s of my playlist:

` youtube-dl --ignore-config -s --get-id <playlist> >> archive`

and then I used my favorite text editor (vim) to add `youtube` to the beginning of each line. Worked like a charm!
