### ISSUE TITLE
Add support for itv.com

### ISSUE THREAD

**Issue by cupof** [rg3/youtube-dl#9240]
any chance that you can add this to youtube-dl 

ITV Player (www.itv.com/itvplayer) 

the itv.py included works the same way as youtube-dl 

you input a url and it downloads the stream to the default directory with a auto filled file name and .flv ex

like this

itv.py http://www.itv.com/hub/marcella/2a4269a0002

or you can input a download directory  and give own file name

like this

itv.py -d /etc http://www.itv.com/hub/marcella/2a4269a0002 marcella.flv

all the working code for this is in the itv.py which i have included 

i have renamed the file to itv.txt for uploading
rename it to itv.py
thanks
[itv.txt](https://github.com/rg3/youtube-dl/files/224964/itv.txt)

Geo restricted to UK.

**Comment by cupof** [comment]
no account needed ???
just need the url

**Comment by dstftw** [comment]
>you dont need a account to get the url of the page

No. I'm redirected to sign in page when trying to playback.

**Comment by cupof** [comment]
why you want to play back on the site ??
just get the url like
http://www.itv.com/hub/marcella/2a4269a0002
this use it with youtube-dl

**Comment by dstftw** [comment]
How do we supposed to reverse engineer it and implement in youtube-dl without playing it in browser?

**Comment by yan12125** [comment]
I got the following error with itv.txt:
```
$ python itv.txt http://www.itv.com/hub/marcella/2a4269a0002
usage: itv.txt [-h] [-d DIR] [-s START] [-e END] [-p PROXY] [-r | -R]
               url [filename]
itv.txt: error: InvalidGeoRegion; The client is in a geographical region that does not have access to the content
```
(I'm in Taiwan.)
Maybe that's why a sign-in page pops up.

**Comment by cupof** [comment]
reverse engineer ??
i gave you the code in post 1
just edit that to suit youtube-dl 

if your outside the uk then use a proxy

**Comment by dstftw** [comment]
The code must be released under unlicense before it can be considered.

**Comment by cupof** [comment]
?? whats that mean

**Comment by dstftw** [comment]
It means exactly that: the author of this code must dedicate this code to public domain, see http://unlicense.org/. I'm locking this issue to prevent further offtopic.
