### ISSUE TITLE
site support - rtvs.sk

### ISSUE THREAD

**Issue by MiNH0** [rg3/youtube-dl#9242]
---
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.19**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl -v http://www.rtvs.sk/televizia/archiv/10390/92418
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.rtvs.sk/televizia/archiv/10390/92418']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2016.04.19
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 92418: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 92418: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 388, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1940, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default
...
<end of log>
```

---
- Single video: http://www.rtvs.sk/televizia/archiv/10390/92418
- Single video: http://www.rtvs.sk/televizia/archiv/9941/93158

---
### Description of your _issue_, suggested solution and other information

RTVS is national channel of Slovakia - providing news, self-produced documentary movies and entertainment shows.

Maybe code from this [tested and working] RTVS plugin for Kodi/XBMC, could make adding this site a little bit easier:
https://github.com/kodi-czsk/plugin.video.rtvs.sk

**Comment by MyloshB** [comment]
@dstftw:
I would inform you that extractor for Slovak TV (www.rtvs.sk) does not work in "fresh" version 2002.02.16.
Could you, please, look on this bug?
Thanks in advance, Mylosh B.

Log-messages are here:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-check-certificate', '--verbose', '--no-overwrites', '--restrict-filenames', '--output', 'D:\\Temp\\%(title)s_%(autonumber)s.%(ext)s', '--batch-file', 'C:\\Program Files (x86)\\YouTube-DL\\youtube-dl.lst']
[debug] Batch file urls: ['https://www.rtvs.sk/televizia/archiv/14822']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2020.02.16
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Proxy map: {}
[generic] 14822: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 14822: Downloading webpage
[generic] 14822: Extracting information
ERROR: Unsupported URL: https://www.rtvs.sk/televizia/archiv/14822
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpuz77jgzq\build\youtube_dl\extractor\generic.py", line 3350, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.rtvs.sk/televizia/archiv/14822
