### ISSUE TITLE
DRM Protected from ProSiebenSat1

### ISSUE THREAD

**Issue by spookyahell** [rg3/youtube-dl#9247]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

Okay, here is my question, especially for those who have worked on the prosiebensat1 extractor.
The way it fetches content is: Check for DRM Protection and then further steps to get to the f4m mainfest, but is it possible for Youtube-DL to get to a manifest link for those DRM protected videos that cannot be downloaded with Youtube-DL but can be downloaded with the AdobeHDS.php-Script?
I'm just curious. And unfortinatly, I couldn't figure out the way to manually create the neccesary client_id.

**Comment by dstftw** [comment]
That is not possible without modifying the source code. You can try commenting out [this code](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/prosiebensat1.py#L245-L246).

**Comment by spookyahell** [comment]
Never mind. Won't work. DRM is DRM for a reason.
