### ISSUE TITLE
Sundance TV

### ISSUE THREAD

**Issue by robwestbrook** [rg3/youtube-dl#9260]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.19**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
J:\>youtube-dl -o j:/Documents/Videos/HapAndLeonards01e01.mp4 --verbose http://w
ww.sundance.tv/watch-now/hap-and-leonard/4822029205001/savage-season
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-o', u'j:/Documents/Videos/HapAndLeonards01e01.mp4
', u'--verbose', u'http://www.sundance.tv/watch-now/hap-and-leonard/482202920500
1/savage-season']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.19
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-78559-g2e8ad2d, ffprobe N-78559-g2e8ad2d
[debug] Proxy map: {}
[generic] savage-season: Requesting header
WARNING: Falling back on generic information extractor.
[generic] savage-season: Downloading webpage
[generic] savage-season: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: Hap And Leonard - SundanceTV - Full Episodes
[generic] playlist Hap And Leonard - SundanceTV - Full Episodes: Collected 1 vid
eo ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] AQ~~,AAACVI9fAwk~,GDu5pYLuhvuRRf67Kor64Nizg7B6Zp82: Download
ing playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make
sure you are using the latest version; type  youtube-dl -U  to update. Be sure t
o call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 671, in extract_info
  File "youtube_dl\extractor\common.pyo", line 341, in extract
  File "youtube_dl\extractor\brightcove.pyo", line 265, in _real_extract
  File "youtube_dl\extractor\brightcove.pyo", line 302, in _get_playlist_info
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bu
g . Make sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete outp
ut.
<end of log>
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.sundance.tv/watch-now/hap-and-leonard/4822029205001/savage-season

---
### Description of your _issue_, suggested solution and other information

Would like to download TV series videos from sundancetv.com
Cable TV subscription required.

**Comment by Quaraxkad** [comment]
Just figured I would add that this site is part of AMC Networks, and could be done using the same extractor.
