### ISSUE TITLE
Can't DL from yahoo.com

### ISSUE THREAD

**Issue by zoof** [rg3/youtube-dl#9271]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://www.yahoo.com/music/livenation/event/galactic-2016
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.yahoo.com/music/livenation/event/galactic-2016']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.19
[debug] Python version 2.7.11 - Linux-4.4.0-0.bpo.1-amd64-x86_64-with-debian-8.4
[debug] exe versions: none
[debug] Proxy map: {}
[generic] galactic-2016: Requesting header
WARNING: Falling back on generic information extractor.
[generic] galactic-2016: Downloading webpage
[generic] galactic-2016: Extracting information
ERROR: Unsupported URL: https://www.yahoo.com/music/livenation/event/galactic-2016
Traceback (most recent call last):
  File "/home/tct/anaconda/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 1374, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/tct/anaconda/lib/python2.7/site-packages/youtube_dl/compat.py", line 279, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=etree.TreeBuilder(element_factory=_element_factory)))
  File "/home/tct/anaconda/lib/python2.7/site-packages/youtube_dl/compat.py", line 268, in _XML
    parser.feed(text)
  File "/home/tct/anaconda/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/home/tct/anaconda/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 78, column 111
Traceback (most recent call last):
  File "/home/tct/anaconda/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 671, in extract_info
    ie_result = ie.extract(url)
  File "/home/tct/anaconda/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/home/tct/anaconda/lib/python2.7/site-packages/youtube_dl/extractor/generic.py", line 2044, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.yahoo.com/music/livenation/event/galactic-2016
```

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

**Comment by yan12125** [comment]
Thanks for the report. Support for Yahoo.com is fixed.
