### ISSUE TITLE
[BUG]Some Youku video part1 will be downloaded a wrong video

### ISSUE THREAD

**Issue by 821938089** [rg3/youtube-dl#9275]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl_19 -v -a downloadurls.txt -F --no-part
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-a', u'downloadurls.txt', u'-F', u'--no-par
t']
[debug] Batch file urls: [u'http://v.youku.com/v_show/id_XOTUxMzg4NDMy.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.04.19
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[youku] XOTUxMzg4NDMy: Downloading JSON metadata
[download] Downloading playlist: 我的世界☆明月庄主☆车震猎杀☆杀人艺术Minecraft

[youku] playlist 我的世界☆明月庄主☆车震猎杀☆杀人艺术Minecraft: Collected 6 vi
deo ids (downloading 6 of them)
[download] Downloading video 1 of 6
[info] Available formats for XOTUxMzg4NDMy_part1:
format code  extension  resolution note
h5-0         mp4        unknown    25.23MiB
h4-0         flv        unknown    12.80MiB
h3-0         mp4        unknown    23.69MiB
h4-1         flv        unknown    28.31MiB
h4-2         flv        unknown    33.37MiB
h4-3         flv        unknown    525.67KiB
h3-1         mp4        unknown    498.09KiB
h5-1         mp4        unknown    487.46KiB
h4-4         flv        unknown    552.37KiB (best)
[download] Downloading video 2 of 6
[info] Available formats for XOTUxMzg4NDMy_part2:
format code  extension  resolution note
h4           flv        unknown    32.28MiB
[download] Downloading video 3 of 6
[info] Available formats for XOTUxMzg4NDMy_part3:
format code  extension  resolution note
h4           flv        unknown    26.69MiB
[download] Downloading video 4 of 6
[info] Available formats for XOTUxMzg4NDMy_part4:
format code  extension  resolution note
h4           flv        unknown    13.11MiB
[download] Downloading video 5 of 6
ERROR: No video formats found!; please report this issue on https://yt-dl.org/bu
g . Make sure you are using the latest version; type  youtube-dl -U  to update.
Be sure to call youtube-dl with the --verbose flag and include its complete outp
ut.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 682, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 842, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 727, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1295, in process_video_result
ExtractorError: No video formats found!
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

http://v.youku.com/v_show/id_XOTUxMzg4NDMy.html

---

### Description of your *issue*, suggested solution and other information

I use the -F to show all video formats, but I found part1 have 3 video is wrong (for example h4-3,h3-1, h5-1, h4-4 is wrong video),The video files are very small.
I often use the -f best to download ultra-clear video,This creates a big problem.

Another bug,When the video downloaded to part5,It reported an error :ERROR: No video formats found!
This bug only This bug only exists in this link :http://v.youku.com/v_show/id_XOTUxMzg4NDMy.html

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

**Comment by yan12125** [comment]
Thanks for the report. In the next version downloaded videos will match what appear in the web player.
