### ISSUE TITLE
Unable to download JSON metadata: HTTP Error

### ISSUE THREAD

**Issue by rutzor** [rg3/youtube-dl#9277]
I'm on the latest version. The issue only occurs when I attempt to embed the soundcloud thumbnails into the audio files.

When attempting to download a soundcloud playlist, I'm met with:

```
D:\Downloads>youtube-dl.exe --verbose --playlist-start 195 --embed-thumbnail -o
%(uploader)s-%(title)s "https://soundcloud.com/rutz/likes"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--playlist-start', u'195', u'--embed
-thumbnail', u'-o', u'%(uploader)s-%(title)s', u'https://soundcloud.com/rutz/lik
es']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.04.19
[debug] Python version 2.7.10 - Windows-7-6.1.7600
[debug] exe versions: none
[debug] Proxy map: {}
[soundcloud:user] rutz: Downloading user info
[soundcloud:user] rutz: Downloading track page 1
[soundcloud:user] rutz: Downloading track page 2
[soundcloud:user] rutz: Downloading track page 3
[soundcloud:user] rutz: Downloading track page 4
[soundcloud:user] rutz: Downloading track page 5
[soundcloud:user] rutz: Downloading track page 6
[soundcloud:user] rutz: Downloading track page 7
[soundcloud:user] rutz: Downloading track page 8
[soundcloud:user] rutz: Downloading track page 9
[soundcloud:user] rutz: Downloading track page 10
[soundcloud:user] rutz: Downloading track page 11
[soundcloud:user] rutz: Downloading track page 12
[soundcloud:user] rutz: Downloading track page 13
[soundcloud:user] rutz: Downloading track page 14
[soundcloud:user] rutz: Downloading track page 15
[soundcloud:user] rutz: Downloading track page 16
[soundcloud:user] rutz: Downloading track page 17
[download] Downloading playlist: rutz (Likes)
[soundcloud:user] playlist rutz (Likes): Collected 763 video ids (downloading 56
9 of them)
[download] Downloading video 1 of 569
[soundcloud] tobias/side-a-1: Resolving id
[soundcloud] tobias/side-a-1: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 504: Gateway Timeout (caused
 by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure
you are using the latest version; type  youtube-dl -U  to update. Be sure to cal
l youtube-dl with the --verbose flag and include its complete output.
  File "youtube_dl\extractor\common.pyo", line 388, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1940, in urlopen
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 469, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 656, in http_error_302
  File "urllib2.pyo", line 437, in open
  File "urllib2.pyo", line 550, in http_response
  File "urllib2.pyo", line 475, in error
  File "urllib2.pyo", line 409, in _call_chain
  File "urllib2.pyo", line 558, in http_error_default
```

**Comment by dstftw** [comment]
Works fine for me, looks like a temporary error.

**Comment by Elsha3r** [comment]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-c', 'https://soundcloud.com/quran-world/sets/mostafa-ismael-4', '--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.08.05
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.4
[debug] Proxy map: {}
[soundcloud:set] quran-world/sets/mostafa-ismael-4: Resolving id
[soundcloud:set] quran-world/sets/mostafa-ismael-4: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 203, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1231, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by formirthonly** [comment]
> > youtube-dl --version
> 2016.05.21.2
> 
> > youtube-dl --verbose -o '%(uploader)s - %(title)s.%(ext)s' https://soundcloud.com/user-816750376/first-day-out-mix-1-dirt
> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: [u'--verbose', u'-o', u'%(uploader)s - %(title)s.%(ext)s', u'https://soundcloud.com/user-816750376/first-day-out-mix-1-dirt']
> [debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
> [debug] youtube-dl version 2016.05.21.2
> [debug] Python version 2.7.11+ - Linux-4.5.4-040504-generic-x86_64-with-Ubuntu-16.04-xenial
> [debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
> [debug] Proxy map: {}
> [soundcloud] user-816750376/first-day-out-mix-1-dirt: Resolving id
> [soundcloud] user-816750376/first-day-out-mix-1-dirt: Downloading info JSON
> ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>   File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 388, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1946, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 435, in open
>     response = meth(req, response)
>   File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/usr/lib/python2.7/urllib2.py", line 473, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

It happens when downloading one or several at a time. I encountered this error with an older version 2016.02.22 and that gave me the same error.

**Comment by dstftw** [comment]
There is no such page https://soundcloud.com/user-816750376/first-day-out-mix-1-dirt.

**Comment by formirthonly** [comment]
My bad, I copied the URL(s) wrong. It works great!

**Comment by dstftw** [comment]
Closing since no response for a long time.
