### ISSUE TITLE
Fails to download some videos from DPlay

### ISSUE THREAD

**Issue by TRox1972** [rg3/youtube-dl#9282]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.19*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.19**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.dplay.no/adam-soker-eva/season-1-episode-1/']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.04.19
[debug] Python version 2.7.11 - Linux-2.6.32-042stab112.15-x86_64-with-debian-jessie-sid
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 11.2-6
[debug] Proxy map: {}
[DPlay] season-1-episode-1: Downloading webpage
[DPlay] 13823: Downloading JSON metadata
[DPlay] 13823: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[DPlay] 13823: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 671, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dplay.py", line 121, in _real_extract
    self._sort_formats(formats)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 862, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### Description of your *issue*, suggested solution and other information

Some videos, like the example provided, cannot be downloaded with youtube-dl, even though watchable from a web browser without login. The problem seems to have something with not being able to download the m3u8 manifest; it mostly fails downloading the f4m manifest from this website, but it still downloads the video.

**Comment by TRox1972** [comment]
Still not able to download the video when running as developer.

```
$ python -m youtube_dl -v http://www.dplay.no/adam-soker-eva/season-1-episode-1/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.dplay.no/adam-soker-eva/season-1-episode-1/']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.04.19
[debug] Git HEAD: e239413
[debug] Python version 2.7.10 - Linux-2.6.32-042stab112.15-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 11.2-6, avprobe 11.2-6, ffmpeg 11.2-6
[debug] Proxy map: {}
[DPlay] season-1-episode-1: Downloading webpage
[DPlay] 13823: Downloading JSON metadata
[DPlay] 13823: Downloading hls stream JSON
[DPlay] 13823: Downloading m3u8 information
[DPlay] 13823: Downloading hds stream JSON
[DPlay] 13823: Downloading f4m manifest
[debug] Invoking downloader on u'http://sbsvod01-vh.akamaihd.net/i/delivery/65/e0/65e0f048-e255-44bd-b263-612b3d74e9e8/NO549622_1_,10,2,60,40,6,15,25,00k.mp4.csmil/index_2_av.m3u8?null=0'
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "youtube_dl/YoutubeDL.py", line 1640, in process_info
    success = dl(filename, info_dict)
  File "youtube_dl/YoutubeDL.py", line 1582, in dl
    return fd.download(name, info)
  File "youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "youtube_dl/downloader/hls.py", line 23, in real_download
    manifest = self.ydl.urlopen(man_url).read()
  File "youtube_dl/YoutubeDL.py", line 1942, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
```

**Comment by dstftw** [comment]
Outdated git HEAD.

**Comment by TRox1972** [comment]
Sorry, didn't see that. Works fine now. 👍
