### ISSUE TITLE
Site support request : Flipagram.com

### ISSUE THREAD

**Issue by ersod** [rg3/youtube-dl#9283]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.19**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://flipagram.com/f/myrWjW9RJw
- Single video: https://flipagram.com/f/nyvTSJMKId

---

### Description of your *issue*, suggested solution and other information

Can you add support for website Flipagram at https://flipagram.com/ which is not supported ?

**Comment by dstftw** [comment]
Flipagram will be supported in the next version.
