### ISSUE TITLE
IQIYI downloading process improvement

### ISSUE THREAD

**Issue by ckckchen** [rg3/youtube-dl#9290]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.19**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### Description of your *issue*, suggested solution and other information
When I use youtube-dl to download video from IQIYI, the program is downloading all format information first, which is totally meaningless and wasting time. Even when I specify the format I want. Eg., When I use -f h1 in the command, Youtube-dl will get through all possible format, h6 h5 h3 h2 h1, and each format has couple segments. This wastes my time, and if my internet connection is poor. I'll easily get timeout or fail to download the video I want.
Can you improve the code to let youtube-dl  download the best quality format or download the format I required directly?

**Comment by yan12125** [comment]
Since Iqiyi changed their codes and youtube-dl gets fixed in 2644e911bebcace4fbac7ddd3ea8c71936b1b3e9, this problem is gone.
