### ISSUE TITLE
CC video Not Download

### ISSUE THREAD

**Issue by praburamWAPKA** [rg3/youtube-dl#9293]
Video Marked As  CC is not downloading with youtube-dl

**Comment by dstftw** [comment]
Carefully read new issue template and provide all requested info.

**Comment by praburamWAPKA** [comment]
where is new issue template please provide me direct link

**Comment by dstftw** [comment]
Where you just typed your first post.

**Comment by praburamWAPKA** [comment]
see youtube-dl https://www.youtube.com/watch?v=ZK4uGLpkAKk   this video is not downloading https://www.dropbox.com/s/p8opbroqyjeyint/Screenshot%202016-04-24%2012.20.28.png?dl=0
see this screenshot on top video which is marked as CC its not downloading with youtube-dl please give me correct command o download this type of video please help me :(

**Comment by yan12125** [comment]
Post the command you use and the results. And please paste texts but not screenshots. Don't forget to include ```-v``` in your commands. For example:
```
youtube-dl -v "https://www.youtube.com/watch?v=ZK4uGLpkAKk"
```
