### ISSUE TITLE
Help video not downloading on this URL

### ISSUE THREAD

**Issue by praburamWAPKA** [rg3/youtube-dl#9294]
see youtube-dl https://www.youtube.com/watch?v=ZK4uGLpkAKk this video is not downloading https://www.dropbox.com/s/p8opbroqyjeyint/Screenshot%202016-04-24%2012.20.28.png?dl=0
see this screenshot on top video which is marked as CC its not downloading with youtube-dl please give me correct command to download this type of video please help me :(

**Comment by dstftw** [comment]
Stop duplicating issues. I've already pointer out that you have to provide information requested in new issue template https://github.com/rg3/youtube-dl/issues/new.

**Comment by praburamWAPKA** [comment]
sorry no one replay me on old post help me
