### ISSUE TITLE
youtube-dl -g is not working url

### ISSUE THREAD

**Issue by praburamWAPKA** [rg3/youtube-dl#9296]
youtube-dl -g https://www.youtube.com/watch?v=ZK4uGLpkAKk
try that output direct url on browser it will show blank page and shows 403 forbiden but downloads Working like charm so its only the bug...... please solve this bug on next update

**Comment by jaimeMF** [comment]
Read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/2c21152ca7af4f96fccb225f161862046280a12a/README.md#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-webbrowser).

**Comment by praburamWAPKA** [comment]
I follow through this but only Some of the url is not work please help

**Comment by jaimeMF** [comment]
Since we just replicate what a browser does, we can only guarantee that url can be downloaded if you use the same cookies and the same connection. Of course there are some website where the url work from other connections, but for the rest there's nothing we can do.

**Comment by praburamWAPKA** [comment]
i saw one thing common that videos contains CC mark What it mean could you explain..??

**Comment by jaimeMF** [comment]
> i saw one thing common that videos contains CC mark What it mean could you explain..??

I guess it means [Closed Captions](https://en.wikipedia.org/wiki/Closed_captioning).

**Comment by praburamWAPKA** [comment]
yes that videos only wants  same cookies and ip for direct link for another users to download there is anyway to Pass machine cookie to user to download videos please
