### ISSUE TITLE
Stop [q] command no longer working for me?

### ISSUE THREAD

**Issue by yopalien** [rg3/youtube-dl#9297]
I'm running Windows 10 and the [q] command suddenly stopped working when it's in the process of downloading? Updated to the newest version of youtube-dl and ffmpeg. It seems like an odd bug that's probably my fault, but I didn't touch any settings after I updated yt-dl. Tried running the cmd in administrator and legacy mode, but no difference. Stumped, as I've been using youtube-dl for years.

**Comment by yan12125** [comment]
Since #8139 this is disabled. Simply hit Ctrl+C to interrupt.

**Comment by yan12125** [comment]
Also see #8252 for reasons not re-enable it.
