### ISSUE TITLE
(Error: Unable to decrypt signature, subkeys lengths 41.43 not supported)(and UnicodeEncodeError??)

### ISSUE THREAD

**Issue by LAP2008** [rg3/youtube-dl#930]
I saw the fix to download VEVO videos on another post here, so i tried it and it works for VEVO but when you try to download any youtube videos from this K-pop channel http://www.youtube.com/user/LOENENT I can't, i get a UnicodeEncodeError?

![6-25-2013 2-05-23 pm](https://f.cloud.github.com/assets/4824581/705760/7e22181c-dddc-11e2-9f26-3632fdbcd4e9.jpg)

**Comment by dstftw** [comment]
Not actual.
