### ISSUE TITLE
Bug on ceskatelevize

### ISSUE THREAD

**Issue by pointh** [rg3/youtube-dl#9301]
Hello,

today I received this error message. I run newest y-dl version on Ubuntu

youtube-dl --verbose http://www.ceskatelevize.cz/ivysilani/11008919268-pet-mrtvych-psu/215512121050001
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.ceskatelevize.cz/ivysilani/11008919268-pet-mrtvych-psu/215512121050001']
[debug] Encodings: locale 'UTF-8', fs 'UTF-8', out 'UTF-8', pref: 'UTF-8'

[debug] youtube-dl version 2014.02.17
[debug] Python version 2.7.6 - Linux-3.13.0-83-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] Proxy map: {}
[generic] 215512121050001: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 215512121050001: Downloading webpage
[generic] 215512121050001: Extracting information
ERROR: Unsupported URL: http://www.ceskatelevize.cz/ivysilani/11008919268-pet-mrtvych-psu/215512121050001; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 493, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 158, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/generic.py", line 380, in _real_extract
    raise ExtractorError('Unsupported URL: %s' % url)
ExtractorError: Unsupported URL: http://www.ceskatelevize.cz/ivysilani/11008919268-pet-mrtvych-psu/215512121050001; please report this issue on https://yt-dl.org/bug . Be sure to call youtube-dl with the --verbose flag and include its complete output. Make sure you are using the latest version; type  youtube-dl -U  to update.

Regards, pointh

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.
