### ISSUE TITLE
Type 2-step verification code for .netrc

### ISSUE THREAD

**Issue by hebrew878** [rg3/youtube-dl#9305]
i set youtube-dl to authenticate by .netrc file but it still asking me 2 step verification code  ? but i have not enabled 2 step auth for my gmail account. Is this normal ?

**Comment by Hrxn** [comment]
Well, no..

If you haven't activated 2FA in your Google account, .netcr should work as usual. You absolutely sure that 2 Factor auth is off?

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by hebrew878** [comment]
```
root@do1:~# youtube-dl 'http://www.youtube.com/watch?v=8g1jm0tHTU0&feature=player_embedded' -v -n
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.youtube.com/watch?v=8g1jm0tHTU0&feature=player_embedded', u'-v', u'-n']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.24
[debug] Python version 2.7.6 - Linux-3.13.0-79-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: ffmpeg N-79139-gde1a0d4, ffprobe N-79139-gde1a0d4
[debug] Proxy map: {}
[youtube] Downloading login page
[youtube] Logging in
Type 2-step verification code and press [Return]:

```

**Comment by dstftw** [comment]
What do you see here https://myaccount.google.com/security/signinoptions/two-step-verification in browser?

**Comment by hebrew878** [comment]
first i tried with **app password** so i had to enable to 2FA to generate one. but later understood that this won't work with app password so disabled 2FA but youtube-dl still want 2FA OTP interactively.
![2fa](https://cloud.githubusercontent.com/assets/2658040/14796102/49674de8-0b49-11e6-9eb8-9f7c7377adfe.png)

**Comment by hebrew878** [comment]
no longer having this issue after a system reboot.
thanks for the support.
