### ISSUE TITLE
Thumbnail-resolution too small, additional functionalities regarding thumbnails

### ISSUE THREAD

**Issue by scarline** [rg3/youtube-dl#9307]
Recently I downloaded a playlist on youtube and extracted the Audio. I used the following comandline:

`youtube-dl -t --audio-format mp3 --audio-quality 0  --embed-thumbnail --add-metadata -x  --metadata-from-title '%(artist)s - %(title)s'  --ignore-errors  https://www.youtube.com/playlist?list=PLIPoTusqlz4lqAeuWjibZgaJ1VItumklt`

The thumbnails are embedded correctly, but the resolution is too small. It stays behind the max resolution of the video. In fact, they are downloaded full-size as jpg, but they are not embedded as such in the mp3. This results in pixel-like covers. From my point of view it would be a cool idea to implement a setting for choosing the resolution with an option for a max. in quality. Additionally (this refers not directly to the issues) a functionality to link a music track with the official single or audio-cover with extracted meta-data would be perfect.

LOG:

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-t', u'--audio-format', u'best', u'--audio-quality', u'0', u'--embed-thumbnail', u'--add-metadata', u'-x', u'--metadata-from-title', u'%(artist)s - %(title)s', u'--ignore-errors', u'https://www.youtube.com/playlist?list=PLIPoTusqlz4lqAeuWjibZgaJ1VItumklt']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.24
[debug] Python version 2.7.10 - Linux-4.2.0-35-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PLIPoTusqlz4lqAeuWjibZgaJ1VItumklt: Downloading webpage
|DNS-request| www.youtube.com 

- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.24**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

**Comment by dstftw** [comment]
Thumbnails are embedded intact with exactly same resolution they have on web.
