### ISSUE TITLE
Cannot connect to YouTube

### ISSUE THREAD

**Issue by jeang35** [rg3/youtube-dl#9308]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.24**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

[debug] System config: []

[debug] User config: []

[debug] Command-line args: [u'--verbose', u'--restrict-filenames', u'-o', u'C:\\Users\\Jean\\AppData\\Local\\JTemp\\Temp/%(title)s.%(ext)s', u'http://r7---sn-25ge7nl7.googlevideo.com/videoplayback?dur=311.054&mt=1461587941&ms=au&ip=2.12.218.51&shardbypass=yes&fexp=9405348,9416126,9416891,9422596,9425362,9426927,9428398,9429854,9430027,9431012,9432206,9432360,9432411,9433045,9433096,9433261,9433273,9']

[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252

[debug] youtube-dl version 2016.04.24

[debug] Python version 2.7.10 - Windows-8-6.2.9200

[debug] exe versions: none

[debug] Proxy map: {}

[generic] videoplayback?dur=311.054&mt=1461587941&ms=au&ip=2.12.218: Requesting header

WARNING: Could not send HEAD request to http://r7---sn-25ge7nl7.googlevideo.com/videoplayback?dur=311.054&mt=1461587941&ms=au&ip=2.12.218.51&shardbypass=yes&fexp=9405348,9416126,9416891,9422596,9425362,9426927,9428398,9429854,9430027,9431012,9432206,9432360,9432411,9433045,9433096,9433261,9433273,9: HTTP Error 403: Forbidden

[generic] videoplayback?dur=311.054&mt=1461587941&ms=au&ip=2.12.218: Downloading webpage

ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

  File "youtube_dl\extractor\common.pyo", line 388, in _request_webpage

  File "youtube_dl\YoutubeDL.pyo", line 1942, in urlopen

  File "urllib2.pyo", line 437, in open

  File "urllib2.pyo", line 550, in http_response

  File "urllib2.pyo", line 475, in error

  File "urllib2.pyo", line 409, in _call_chain

  File "urllib2.pyo", line 558, in http_error_default

**Comment by yan12125** [comment]
Use YouTube URLs
```
youtube-dl -v "https://www.youtube.com/watch?v=XXX"
```
