### ISSUE TITLE
youtube-dl -g bug is detected [IMPORTANT FOR API's Users]

### ISSUE THREAD

**Issue by praburamWAPKA** [rg3/youtube-dl#9309]
According to template.....youtube-dl -g ......direct link works only on same cookies, same ip of that system...
 but i have found bug ..... even that link is didn't work on same system ... Mainly its not working on some videos which is marked as CC in youtube...... many users are struggling because many of them create api's based on this only .... But No one come forward to solve please see this bug...... i beg you please....
see below i have used wget command to check video direct link work or not in same system please Solve This.....

]# youtube-dl -g https://www.youtube.com/watch?v=ZK4uGLpkAK                                                                                        k
https://r1---sn-nx5e6n76.googlevideo.com/videoplayback?mt=1461589087&mv=u&sparam                                                                                        s=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm                                                                                        %2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ms=au&ip=x.x.xx.x.x                                                                                 &requiressl=yes&mm=31&mn=sn-nx5e6n76&id=o-AJ2FtlCUDChnBuPhYt9t01hf_uYg7aEci                                                                                        j-IB1xnkFS7&pl=26&source=youtube&upn=s1CAO1AV7RM&lmt=1458717216500830&fexp=94059                                                                                        66%2C9416126%2C9416891%2C9417380%2C9422596%2C9423347%2C9426926%2C9427322%2C94283                                                                                        98%2C9428770%2C9429161%2C9429245%2C9431012%2C9431530%2C9431684%2C9433096%2C94334                                                                                        25%2C9433680%2C9433729%2C9433947%2C9434001%2C9434040&keepalive=yes&nh=IgpwcjAxLn                                                                                        NlYTAzKgkxMjcuMC4wLjE&gir=yes&mime=video%2Fmp4&key=yt6&clen=117979870&itag=264&g                                                                                        cr=us&expire=1461610846&ipbits=0&dur=122.458&sver=3&signature=70BAFD2A3EB23E79B9                                                                                        BB050B64AB0E675E5ECCF6.C9EA3EE8073B1DA13B5FDFFF7D80F9EECF37D701&ratebypass=yes
https://r1---sn-nx5e6n76.googlevideo.com/videoplayback?mt=1461589087&mv=u&sparam                                                                                        s=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm                                                                                        %2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ms=au&ip=x.x.x.xx.x                                                                                       &requiressl=yes&mm=31&mn=sn-nx5e6n76&id=o-AJ2FtlCUDChnBuPhYt9t01hf_uYg7aEci                                                                                        j-IB1xnkFS7&pl=26&source=youtube&upn=s1CAO1AV7RM&lmt=1458463987532992&fexp=94059                                                                                        66%2C9416126%2C9416891%2C9417380%2C9422596%2C9423347%2C9426926%2C9427322%2C94283                                                                                        98%2C9428770%2C9429161%2C9429245%2C9431012%2C9431530%2C9431684%2C9433096%2C94334                                                                                        25%2C9433680%2C9433729%2C9433947%2C9434001%2C9434040&keepalive=yes&nh=IgpwcjAxLn                                                                                        NlYTAzKgkxMjcuMC4wLjE&gir=yes&mime=audio%2Fwebm&key=yt6&clen=2019746&itag=251&gc                                                                                        r=us&expire=1461610846&ipbits=0&dur=122.461&sver=3&signature=D655D5D0ED988A54505                                                                                        2E02BB4DA01415AF20486.6F839C775F9FD7E27EA30AD9D2A8235082BD8A71&ratebypass=yes
[root@free-20150919 ~]# ^C
[root@free-20150919 ~]# wget https://r1---sn-nx5e6n76.googlevideo.com/videoplayback?mt=1461589087&mv=u&sparam                                                                                        s=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm                                                                                        %2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ms=au&ip=x.x.x.x.x                                                                                        &requiressl=yes&mm=31&mn=sn-nx5e6n76&id=o-AJ2FtlCUDChnBuPhYt9t01hf_uYg7aEci                                                                                        j-IB1xnkFS7&pl=26&source=youtube&upn=s1CAO1AV7RM&lmt=1458463987532992&fexp=94059                                                                                        66%2C9416126%2C9416891%2C9417380%2C9422596%2C9423347%2C9426926%2C9427322%2C94283                                                                                        98%2C9428770%2C9429161%2C9429245%2C9431012%2C9431530%2C9431684%2C9433096%2C94334                                                                                        25%2C9433680%2C9433729%2C9433947%2C9434001%2C9434040&keepalive=yes&nh=IgpwcjAxLn                                                                                        NlYTAzKgkxMjcuMC4wLjE&gir=yes&mime=audio%2Fwebm&key=yt6&clen=2019746&itag=251&gc                                                                                        r=us&expire=1461610846&ipbits=0&dur=122.461&sver=3&signature=D655D5D0ED988A54505                                                                                        2E02BB4DA01415AF20486.6F839C775F9FD7E27EA30AD9D2A8235082BD8A71&ratebypass=yes
[1] 24113
[2] 24114
[3] 24115
[4] 24116
[5] 24117
[6] 24118
[7] 24119
[8] 24120
[9] 24121
[10] 24122
[11] 24123
[12] 24124
[13] 24125
[14] 24126
[15] 24127
[16] 24128
[17] 24129
[18] 24130
[19] 24131
[20] 24132
[21] 24133
[22] 24134
[23] 24135
[24] 24136
[25] 24137
[26] 24138
[27] 24139
[root@free-20150919 ~]# -bash: j-IB1xnkFS7: command not found
-bash: 66%2C9416126%2C9416891%2C9417380%2C9422596%2C9423347%2C9426926%2C9427322%2C94283: command not found
-bash: 17.35: command not found
-bash: NlYTAzKgkxMjcuMC4wLjE: command not found
-bash: sparam: command not found
--2016-04-25 09:01:12--  https://r1---sn-nx5e6n76.googlevideo.com/videoplayback?mt=1461589087
-bash: 2E02BB4DA01415AF20486.6F839C775F9FD7E27EA30AD9D2A8235082BD8A71: command not found
Can't open r=us
Resolving r1---sn-nx5e6n76.googlevideo.com... 173.194.152.39, 2607:f8b0:400a:12::7
Connecting to r1---sn-nx5e6n76.googlevideo.com|173.194.152.39|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-04-25 09:01:13 ERROR 403: Forbidden.

[1]   Exit 8                  wget https://r1---sn-nx5e6n76.googlevideo.com/videoplayback?mt=1461589087
[2]   Done                    mv=u
[3]   Exit 127                sparam s=clen%2Cdur%2Cgcr%2Cgir%2Cid%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm %2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire
[4]   Done                    ms=au
[5]   Exit 127                ip=X.X.X.XX
[6]   Done                    requiressl=yes
[7]   Done                    mm=31
[8]   Done                    mn=sn-nx5e6n76
[9]   Exit 127                id=o-AJ2FtlCUDChnBuPhYt9t01hf_uYg7aEci j-IB1xnkFS7
[10]   Done                    pl=26
[11]   Done                    source=youtube
[12]   Done                    upn=s1CAO1AV7RM
[13]   Done                    lmt=1458463987532992
[14]   Exit 127                fexp=94059 66%2C9416126%2C9416891%2C9417380%2C9422596%2C9423347%2C9426926%2C9427322%2C94283 98%2C9428770%2C9429161%2C9429245%2C9431012%2C9431530%2C9431684%2C9433096%2C94334 25%2C9433680%2C9433729%2C9433947%2C9434001%2C9434040
[15]   Done                    keepalive=yes
[16]   Exit 127                nh=IgpwcjAxLn NlYTAzKgkxMjcuMC4wLjE
[17]   Done                    gir=yes
[18]   Done                    mime=audio%2Fwebm
[19]   Done                    key=yt6
[20]   Done                    clen=2019746
[21]   Done                    itag=251
[22]   Done                    gc r=us
[23]   Done                    expire=1461610846
[24]   Done                    ipbits=0
[25]   Done                    dur=122.461
[26]-  Done                    sver=3
[27]+  Exit 127                signature=D655D5D0ED988A54505 2E02BB4DA01415AF20486.6F839C775F9FD7E27EA30AD9D2A8235082BD8A71

**Comment by dstftw** [comment]
[URLs must be put in quotes](https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).
