### ISSUE TITLE
[REQUEST] How To Pass cookies for Direct link parameter -g ??? 

### ISSUE THREAD

**Issue by praburamWAPKA** [rg3/youtube-dl#9310]
i want to give direct link for many users using youtube-dl -g  it is possible on php using api's??? if you are expert please help me please.......

**Comment by jaimeMF** [comment]
I've already told you in https://github.com/rg3/youtube-dl/issues/9296#issuecomment-213951648 and https://github.com/rg3/youtube-dl/issues/9296#issuecomment-213951970 that youtube-dl doesn't support that. If you find a method to do it, feel free to share it.

**Comment by praburamWAPKA** [comment]
which means no one know aboutt that??

**Comment by jaimeMF** [comment]
It means that in case someone knows how to do it, he hasn't shared it with us.

**Comment by dstftw** [comment]
There is a [workaround](https://github.com/rg3/youtube-dl/issues/9001#issuecomment-201991818) actually. Not sure how reliable is this in general but it worked in my cases.

**Comment by praburamWAPKA** [comment]
please share it if you know please :)

**Comment by praburamWAPKA** [comment]
Wow Thank You So Much Love u lots i have seach this from last 4 days without sleep thank you
