### ISSUE TITLE
[Malemotion] HTTP Error 500

### ISSUE THREAD

**Issue by gineadai** [rg3/youtube-dl#9311]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.24**
### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Site not work.

**Comment by gineadai** [comment]
And scivee.tv too.

**Comment by yan12125** [comment]
Sorry not seeing scivee.tv listed here. For sites that stops working but no news or announcements available, we may add something like  ```'skip': 'Not accessible from Travis CI server'```, as the case in ```VubeIE```.
