### ISSUE TITLE
[LiveLeak] Add thumbnail support

### ISSUE THREAD

**Issue by kidol** [rg3/youtube-dl#9312]
LiveLeak video pages provide an OpenGraph meta tag which could be utilized by the extractor.

Example:
http://www.liveleak.com/view?i=dcc_1461213982
`<meta property="og:image" content="https://cdn.liveleak.com/80281E/ll_a_u/thumbs/2016/Apr/25/2936a72f65ab_sf_10.jpg"/>`

**Comment by inondle** [comment]
Made  a pull request here: 
https://github.com/rg3/youtube-dl/pull/9400/

**Comment by yan12125** [comment]
As #9400 got merged, thumbnails on LiveLeak will be available in the next version. Thanks @inondle !

**Comment by kidol** [comment]
@inondle Yes thanks indeed.
