### ISSUE TITLE
[SnagFilmsEmbed] Site not working

### ISSUE THREAD

**Issue by gineadai** [rg3/youtube-dl#9314]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

**Comment by dstftw** [comment]
Works fine:
```
PS C:\Dev\youtube-dl\master> py -2 -m youtube_dl "http://embed.snagfilms.com/embed/player?filmId=74849a00-85a9-11e1-9660
-123139220831&w=500"
[SnagFilmsEmbed] 74849a00-85a9-11e1-9660-123139220831: Downloading webpage
[download] Destination: #whilewewatch-74849a00-85a9-11e1-9660-123139220831.mp4
[download]   0.3% of 678.07MiB at  2.65MiB/s ETA 04:15
ERROR: Interrupted by user
```

**Comment by gineadai** [comment]
My mistake. Please close this issue.
