### ISSUE TITLE
[SciVee] Site not working

### ISSUE THREAD

**Issue by gineadai** [rg3/youtube-dl#9315]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

**Comment by dstftw** [comment]
It's unclear whether it's closed/made private/whatever. Wikipedia still claims it's active. I also haven't found any official announcement or statement.

**Comment by gineadai** [comment]
According to this site down for at least for 3 months:
https://www.reddit.com/r/HelpMeFind/comments/41svmm
/help_me_find_a_video_from_a_defunct_website/?ref=search_posts

**Comment by azes** [comment]
It's been a year and site is still down, maybe remove it for good now?

**Comment by yan12125** [comment]
Good idea. Someone on Wikipedia believe it's down, too: https://en.wikipedia.org/w/index.php?title=SciVee&diff=prev&oldid=723161154. I've removed it in 892b47ab6. If it's up again we can add it back.
