### ISSUE TITLE
help required

### ISSUE THREAD

**Issue by siddht1** [rg3/youtube-dl#9319]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.24**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.04.24
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

i was downloading youtube audio from playlist file, but one of the youtube files have been deleted , so how to skip error file as the downloading has stopped.

youtube-dl https://www.youtube.com/playlist?list=LLJ6td3C9QlPO9O_J5dF4ZzA -f bestaudio
[youtube:playlist] LLJ6td3C9QlPO9O_J5dF4ZzA: Downloading webpage
[download] Downloading playlist: Liked videos
[youtube:playlist] LLJ6td3C9QlPO9O_J5dF4ZzA: Downloading page #1
[youtube:playlist] LLJ6td3C9QlPO9O_J5dF4ZzA: Downloading page #2
[youtube:playlist] LLJ6td3C9QlPO9O_J5dF4ZzA: Downloading page #3
[youtube:playlist] playlist Liked videos: Downloading 365 videos
[download] Downloading video 1 of 365
[youtube] e0RdHrx-NWk: Downloading webpage
[youtube] e0RdHrx-NWk: Downloading video info webpage
[youtube] e0RdHrx-NWk: Extracting video information
[youtube] e0RdHrx-NWk: Downloading MPD manifest
[download] Hellberg ft. Jessarae - Wasted Summer [Premiere]-e0RdHrx-NWk.webm has already been downloaded
[download] 100% of 4.07MiB
[download] Downloading video 2 of 365
[youtube] ROfp0z_hJxI: Downloading webpage
[youtube] ROfp0z_hJxI: Downloading video info webpage
[youtube] ROfp0z_hJxI: Extracting video information
[youtube] ROfp0z_hJxI: Downloading MPD manifest
[download] Au5 ft. Danyka Nadeau - Follow You (Rhythmics Remix) [Premiere]-ROfp0z_hJxI.m4a has already been downloaded
[download] 100% of 4.36MiB
[ffmpeg] Correcting container in "Au5 ft. Danyka Nadeau - Follow You (Rhythmics Remix) [Premiere]-ROfp0z_hJxI.m4a"
[download] Downloading video 3 of 365
[youtube] iOLC5_BozqA: Downloading webpage
[youtube] iOLC5_BozqA: Downloading video info webpage
[youtube] iOLC5_BozqA: Extracting video information
[youtube] iOLC5_BozqA: Downloading MPD manifest
[download] Au5 - Follow You ft. Danyka Nadeau (Ducked Ape Remix) [PREMIERE]-iOLC5_BozqA.webm has already been downloaded
[download] 100% of 4.23MiB
[download] Downloading video 4 of 365
[youtube] 05jd9fwGlSM: Downloading webpage
[youtube] 05jd9fwGlSM: Downloading video info webpage
[youtube] 05jd9fwGlSM: Extracting video information
[youtube] 05jd9fwGlSM: Downloading MPD manifest
[download] Au5 - Follow You (feat. Danyka Nadeau) (Fractal Chill Mix)-05jd9fwGlSM.m4a has already been downloaded
[download] 100% of 4.55MiB
[ffmpeg] Correcting container in "Au5 - Follow You (feat. Danyka Nadeau) (Fractal Chill Mix)-05jd9fwGlSM.m4a"
[download] Downloading video 5 of 365
[youtube] kdKzQ_15t6g: Downloading webpage
[youtube] kdKzQ_15t6g: Downloading video info webpage
[youtube] kdKzQ_15t6g: Extracting video information
[youtube] kdKzQ_15t6g: Downloading MPD manifest
[download] [Dubstep] Au5 - Follow You ft. Danyka Nadeau (Virtual Riot Remix)-kdKzQ_15t6g.webm has already been downloaded
[download] 100% of 3.76MiB
[download] Downloading video 6 of 365
[youtube] SNxbWOB2N-Q: Downloading webpage
[youtube] SNxbWOB2N-Q: Downloading video info webpage
[youtube] SNxbWOB2N-Q: Extracting video information
[youtube] SNxbWOB2N-Q: Downloading MPD manifest
[download] 【Drumstep】Au5 ft. Danyka Nadeau- Follow You (Rootkit Remix) [PREMIERE]-SNxbWOB2N-Q.webm has already been downloaded
[download] 100% of 3.12MiB
[download] Downloading video 7 of 365
[youtube] vLXS0EGwCZg: Downloading webpage
[youtube] vLXS0EGwCZg: Downloading video info webpage
[youtube] vLXS0EGwCZg: Extracting video information
[download] Haywyre - Smooth Criminal-vLXS0EGwCZg.webm has already been downloaded
[download] 100% of 3.98MiB
[download] Downloading video 8 of 365
[youtube] vnT4w2s0OT4: Downloading webpage
[youtube] vnT4w2s0OT4: Downloading video info webpage
[youtube] vnT4w2s0OT4: Extracting video information
[youtube] vnT4w2s0OT4: Downloading MPD manifest
[download] Arty ft. Angel Taylor - Up All Night [Exclusive] (Out Now)-vnT4w2s0OT4.webm has already been downloaded
[download] 100% of 4.15MiB
[download] Downloading video 9 of 365
[youtube] XU7G0ubXKAw: Downloading webpage
[youtube] XU7G0ubXKAw: Downloading video info webpage
[youtube] XU7G0ubXKAw: Extracting video information
[download] SCNDL- The Munsta (Aaron Jackson Remix)-XU7G0ubXKAw.webm has already been downloaded
[download] 100% of 4.07MiB
[download] Downloading video 10 of 365
[youtube] Zlce3BOQVDk: Downloading webpage
[youtube] Zlce3BOQVDk: Downloading video info webpage
[youtube] Zlce3BOQVDk: Extracting video information
[youtube] Zlce3BOQVDk: Downloading MPD manifest
[download] SCNDL - The Munsta (Nitro Fun Remix) [Premiere]-Zlce3BOQVDk.m4a has already been downloaded
[download] 100% of 3.09MiB
[ffmpeg] Correcting container in "SCNDL - The Munsta (Nitro Fun Remix) [Premiere]-Zlce3BOQVDk.m4a"
[download] Downloading video 11 of 365
[youtube] Pi8Q8UMzbCE: Downloading webpage
[youtube] Pi8Q8UMzbCE: Downloading video info webpage
[youtube] Pi8Q8UMzbCE: Extracting video information
[youtube] Pi8Q8UMzbCE: Downloading MPD manifest
[download] SCNDL - The Munsta (Aero Chord Remix) [PREMIERE]-Pi8Q8UMzbCE.webm has already been downloaded
[download] 100% of 3.22MiB
[download] Downloading video 12 of 365
[youtube] 9YdWeMzvcTE: Downloading webpage
[youtube] 9YdWeMzvcTE: Downloading video info webpage
ERROR: 9YdWeMzvcTE: YouTube said: This video has been removed for violating YouTube's Terms of Service.

**Comment by siddht1** [comment]
youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.24
[debug] Python version 2.7.6 - Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg N-79139-gde1a0d4, ffprobe N-79139-gde1a0d4
[debug] Proxy map: {}

**Comment by siddht1** [comment]
i just need to know how to skip errors in playlist

**Comment by dstftw** [comment]
`-i`.

**Comment by siddht1** [comment]
not understood

**Comment by Hrxn** [comment]
https://github.com/rg3/youtube-dl#options
