### ISSUE TITLE
[vlive] Unable to download live videos

### ISSUE THREAD

**Issue by Kagami** [rg3/youtube-dl#9321]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.04.24*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

(Note that this live might end when you check it.)

```
$ youtube-dl -v 'http://www.vlive.tv/video/7779/퇴근-저흰출근방송'
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.vlive.tv/video/7779/퇴근-저흰출근방송']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.24
[debug] Python version 3.4.3 - Linux-4.5.0-gentoo-x86_64-Intel-R-_Core-TM-_i7-3820_CPU_@_3.60GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg N-79272-gbd1dcaf, ffprobe N-79272-gbd1dcaf, rtmpdump 2.4
[debug] Proxy map: {}
[vlive] 7779: Downloading webpage
ERROR: Unable to extract long video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/kagami/.local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "/home/kagami/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/home/kagami/.local/bin/youtube-dl/youtube_dl/extractor/vlive.py", line 36, in _real_extract
    webpage, 'long video id')
  File "/home/kagami/.local/bin/youtube-dl/youtube_dl/extractor/common.py", line 644, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract long video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Live video: has the exact same type of URLs, just marked as live videos at the site; check fresh lives [here](http://www.vlive.tv/home)

---

### Description of your *issue*, suggested solution and other information

(Not sure which category is best suited for this issue, sorry.)

Lives are served with Flash through HLS streams, there is JSON with streams parameters at the code page:

```
vlive.tv.video.ajax.request.handler.init("7779", "{\"liveStatus\":\"LIVE\",\"resolutions\":[
{\"name\":\"audio\",\"width\":null,\"height\":null,\"cdnUrl\":\"http:\/\/vlive.hls.edgesuite.net\/kr002\/alow.stream\/playlist.m3u8?__gda__=1461682617_f30c9b77b4d56a116b0e436d36b7b1d1\",\"additionalProperties\":{}},
{\"name\":\"250\",\"width\":320,\"height\":184,\"cdnUrl\":\"http:\/\/vlive.hls.edgesuite.net\/kr002\/250.stream\/playlist.m3u8?__gda__=1461682617_5bd3a23663a5cd54dc204da558ff00e5\",\"additionalProperties\":{}},
{\"name\":\"400\",\"width\":640,\"height\":368,\"cdnUrl\":\"http:\/\/vlive.hls.edgesuite.net\/kr002\/400.stream\/playlist.m3u8?__gda__=1461682617_62f2ced6228651d617e7a7b9fff0da6a\",\"additionalProperties\":{}},
{\"name\":\"1200\",\"width\":640,\"height\":368,\"cdnUrl\":\"http:\/\/vlive.hls.edgesuite.net\/kr002\/1200.stream\/playlist.m3u8?__gda__=1461682617_88ce3b5362dc63e50439be087164e98b\",\"additionalProperties\":{}}
],\"additionalProperties\":{}}", "", "", "", "");
```

**Comment by yan12125** [comment]
The live show http://www.vlive.tv/video/7673/%EC%98%88%EB%8B%88%EC%99%80-%ED%95%A8%EA%BB%98-%EB%B4%84-%ED%8C%8C%ED%8B%B0-%EC%A6%90%EA%B8%B0%EA%B8%B0-Enjoy-the-party-with-Yenny-%EA%B0%80%EB%A1%9C%EC%88%98%EA%B8%B8 says it's coming on 4:30PM. Is it Korea Standard Time (UTC+9)?
And in which time of a day there are most live channels on vlive.tv?

**Comment by Kagami** [comment]
>Is it Korea Standard Time (UTC+9)?

Dates displayed on the site should be in your local time (depending on browser settings, maybe JavaScript, etc). This query (without `timezoneOffset` cookie) will return Korean Time (5:30PM in that case):

`curl -H 'Referer: http://www.vlive.tv/video/7673' 'http://www.vlive.tv/video/status?videoSeq=7673'`

>And in which time of a day there are most live channels on vlive.tv?

You can check schedule [here](http://www.vlive.tv/upcoming?d=20160428&i=2). I think the most busy hours are 09:00÷11:00 UTC.
