### ISSUE TITLE
-o option is broken

### ISSUE THREAD

**Issue by redsteakraw** [rg3/youtube-dl#9325]
All options passed to -o from a simple "%(title)s.%(ext)s" to - for standard out all return the 

> youtube-dl: error: using output template conflicts with using title, video ID or auto number

Error

version:

2016.04.19

system x86-64 Linux - Bash shell

**Comment by dstftw** [comment]
As clearly stated in error message `-t`, `--id` and `-A` can't be used with `-o`.

**Comment by redsteakraw** [comment]
@dstftw litterally anything passed to -o even all the examples in the documentation even the wiki don't work

> -o '%(uploader)s/ %(title)s-%(id)s.%(ext)s'

There is no example on the internet or in any documentation that does work if you have a simple one to try let me know.  but even without %(title)s it still returns an error if I pass it -o "foo.bar" it still gives the same error.  -o is broken for at least my version.  I don't use -t --id or -A when I use -o

**Comment by dstftw** [comment]
Post verbose output.

**Comment by redsteakraw** [comment]
> $ youtube-dl --verbose -o '%(uploader)s/ %(title)s-%(id)s.%(ext)s' https://www.youtube.com/watch?v=RkfLGB7Ft0A
[debug] System config: []
[debug] User config: [u'-t', u'--prefer-free-formats']
[debug] Command-line args: [u'--verbose', u'-o', u'%(uploader)s/ %(title)s-%(id)s.%(ext)s', u'https://www.youtube.com/watch?v=RkfLGB7Ft0A']
Usage: youtube-dl [OPTIONS] URL [URL...]
> 
> youtube-dl: error: using output template conflicts with using title, video ID or auto number

**Comment by redsteakraw** [comment]
$ youtube-dl --verbose -o '%(uploader)s/ %(title)s-%(id)s.%(ext)s' https://www.youtube.com/watch?v=RkfLGB7Ft0A
[debug] System config: []
[debug] User config: [u'-t', u'--prefer-free-formats']
[debug] Command-line args: [u'--verbose', u'-o', u'%(uploader)s/ %(title)s-%(id)s.%(ext)s', u'https://www.youtube.com/watch?v=RkfLGB7Ft0A']
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: using output template conflicts with using title, video ID or auto number

**Comment by dstftw** [comment]
>I don't use -t --id or -A when I use -o
>User config: [u'**-t**', u'--prefer-free-formats']

**Comment by redsteakraw** [comment]
sorry, I went into the config file and removed the -t

**Comment by krompus** [comment]
@redsteakraw Haha, nice video choice.
