### ISSUE TITLE
Please tell me how to get FileSize ??

### ISSUE THREAD

**Issue by praburamWAPKA** [rg3/youtube-dl#9330]
how to get video filesize in bytes using youtube-dl please give me some tips to get in php to write it :)

**Comment by dstftw** [comment]
Parse from `--dump-json`, each format dict may contain `filesize` field.

**Comment by praburamWAPKA** [comment]
no its not consists filesize please help me without using python could i get filesize

**Comment by dstftw** [comment]
As I've already emphasized it's not guaranteed to.

**Comment by praburamWAPKA** [comment]
then  anyother option suggestion please

**Comment by dstftw** [comment]
There is no other option apart from extracting it yourself from Content-Length header.

**Comment by praburamWAPKA** [comment]
ok thank you for your replay :)
