### ISSUE TITLE
Add support for urplay.se

### ISSUE THREAD

**Issue by 3pnan1yhpqtc3c9aoosharklaserscom** [rg3/youtube-dl#9332]
Example URL: http://urplay.se/program/193438-nordkoreas-fotbollshjaltar
Geo restricted to Sweden.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by herrschaftsseitn** [comment]
Hej! 
Just seen this issue. Exemplarily this video http://urplay.se/program/193438-nordkoreas-fotbollshjaltar
Would be nice!

**Comment by herrschaftsseitn** [comment]
Nice, thanks! Great work!
