### ISSUE TITLE
[linux] http://www.nbc.com/ (https protocol not found)

### ISSUE THREAD

**Issue by jiangjiangflies** [rg3/youtube-dl#9336]
http://www.nbc.com/nightly-news/video/nbc-nightly-news-apr-27-2016/3022231

https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
https://nbcmpx-vh.akamaihd.net/i/video/800/163/160419_3022231_NBC_Nightly_News__Apr_27__2016_mpx_,1696,1296,896,696,496,306,150,240,64,.mp4.csmil/index_0_av.m3u8?null=0&id=AgAXadVVYAYtXcQHIlfZXGDaUXPGOWI1UxJD6C%2ftAwPky5vLJe4WquVsFSin%2fAhTfuf+x+wYUd5CnA%3d%3d&hdntl=exp=1461934404~acl=%2fi%2fvideo%2f800%2f163%2f160419_3022231_NBC_Nightly_News__Apr_27__2016_mpx_*~data=hdntl~hmac=f8c4553f875b7b562939291150bd470bf916f091ce28e6ed465f26c29a745305: Protocol not found

ERROR: ffmpeg exited with code 1

**Comment by EnginePod** [comment]
It seems like your reply has the answer in it (note: "recompile FFmpeg with openssl").
Read this: http://stackoverflow.com/questions/31514949/ffmpeg-over-https-fails

**Comment by yan12125** [comment]
Thanks @EnginePod. Don't forget to enable HLS, too.
