### ISSUE TITLE
au.tv.yahoo.com - no longer able to download videos

### ISSUE THREAD

**Issue by Mike-Skinner** [rg3/youtube-dl#9345]
### Due Diligence
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.04.24**
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [x ] Site support request (request for fixing support for an _existing_ site)

---

**$ youtube-dl --verbose --proxy "" "https://au.tv.yahoo.com/plus7/sunrise-extra/-/watch/31470470/sunrise-episode-fri-29-apr/"**

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--proxy', u'', u'https://au.tv.yahoo.com/plus7/sunrise-extra/-/watch/31470470/sunrise-episode-fri-29-apr/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.24
[debug] Python version 2.7.10 - Linux-4.2.0-35-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: avconv 2.7.6-0ubuntu0.15.10.1, avprobe 2.7.6-0ubuntu0.15.10.1, ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1
[debug] Proxy map: {}
[Yahoo] sunrise-episode-fri: Downloading webpage
ERROR: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/yahoo.py", line 266, in _real_extract
    CONTENT_ID_REGEXES, webpage, 'content ID')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 644, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

### Description of the *issue*

Previously I have been able to download videos from the domain au.tv.yahoo.com - however in the past 2-3 weeks they have changed something on their site, and I can no longer download.

An example URL is [https://au.tv.yahoo.com/plus7/sunrise-extra/-/watch/31470470/sunrise-episode-fri-29-apr/]

I have also run youtube-dl with the **--dump-pages** parameter. The output can be downloaded from:

[https://u.pomf.is/wdsork.txt]

I understand you may not have access to a working Australian Proxy, so if you would like me to run youtube-dl --dump-pages for another URL, please let me know!

If it helps, with developer tools open in my browser I can see references to Brightcove and Akamai.

**Thanks and best wishes!**

**Comment by sergei-sh** [comment]
The similar problem with au.sports.yahoo.com. Most videos download, while some doe not:

youtube-dl -v https://au.sports.yahoo.com/afl/a/31480492/afl-steve-johnson-100m-penalty-luke-hodge-gws-giants/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://au.sports.yahoo.com/afl/a/31480492/afl-steve-johnson-100m-penalty-luke-hodge-gws-giants/']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.6 - Linux-3.19.0-32-generic-x86_64-with-LinuxMint-17.3-rosa
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[Yahoo] afl-steve-johnson: Downloading webpage
ERROR: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/serj/work/mirror0/virtual_env/local/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "/home/serj/work/mirror0/virtual_env/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/home/serj/work/mirror0/virtual_env/local/lib/python2.7/site-packages/youtube_dl/extractor/yahoo.py", line 266, in _real_extract
    CONTENT_ID_REGEXES, webpage, 'content ID')
  File "/home/serj/work/mirror0/virtual_env/local/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 644, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract content ID; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Mike-Skinner** [comment]
Thanks Sergei - it's good to know it's not just me.

**Comment by thegoodthings** [comment]
Can confirm this too, though it seems to be due to a regression rather than a site change.  I can still download with release 2016.04.19, but releases 2016.04.24+ won't work.

Of note, 2016.04.24 is using the Yahoo extractor, whereas 2016.04.19 and earlier used the Generic + Brightcove Legacy extractors instead.  Adding `--force-generic-extractor` to the command-line works around the issue.

**Comment by Mike-Skinner** [comment]
I can confirm that @thegoodthings suggestion of "--force-generic-extractor" works for URLs starting with "https://au.tv.yahoo.com"

Thanks for the work-around - it's appreciated. :-)
