### ISSUE TITLE
Liveleak video cannot get download url.

### ISSUE THREAD

**Issue by dspstudio** [rg3/youtube-dl#9350]
[roo@local ~]$ youtube-dl -g http://www.liveleak.com/view?i=dc0_1461466199
ERROR: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[roo@local ~]$ youtube-dl -g http://www.liveleak.com/view?i=dc0_1461466199 --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-g', u'http://www.liveleak.com/view?i=dc0_1461466199', u'--verbose']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.04.24
[debug] Python version 2.7.5 - Linux-2.6.32-042stab104.1-x86_64-with-centos-7.2.1511-Core
[debug] exe versions: avconv 10.1, avprobe 10.1
[debug] Proxy map: {}
ERROR: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/liveleak.py", line 87, in _real_extract
    webpage, 'embed URL')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 644, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract embed URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by EnginePod** [comment]
I checked the link and it seems like this isn't a standard liveleak video but instead an embedded Facebook video.
I copied the link to the embedded FB video and it downloaded nicely with youtube-dl.

Long story short, to solve this problem we need to add support for embedded Facebook videos.
