### ISSUE TITLE
Can‘t use my HTTP/HTTPS proxy download youtube video.

### ISSUE THREAD

**Issue by 821938089** [rg3/youtube-dl#9369]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v -a downloadurls.txt -f best --no-part --proxy 127.0.0.1:8087 -i
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-a', u'downloadurls.txt', u'-f', u'best', u
'--no-part', u'--proxy', u'127.0.0.1:8087', u'-i']
[debug] Batch file urls: [u'https://www.youtube.com/playlist?list=PL30419C17041A
76D9']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {u'http': u'127.0.0.1:8087', u'https': u'127.0.0.1:8087'}
[youtube:playlist] PL30419C17041A76D9: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILE
D] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SS
L: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
  File "youtube_dl\extractor\common.pyo", line 388, in _request_webpage
  File "youtube_dl\YoutubeDL.pyo", line 1942, in urlopen
  File "urllib2.pyo", line 431, in open
  File "urllib2.pyo", line 449, in _open
  File "urllib2.pyo", line 409, in _call_chain
  File "youtube_dl\utils.pyo", line 859, in https_open
  File "urllib2.pyo", line 1197, in do_open
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Playlist: https://www.youtube.com/playlist?list=PL30419C17041A76D9

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

This proxy Is a local proxy.
I use XX-Net to create a proxy.
XX-Net Github:https://github.com/XX-net/XX-Net
XX-Net English Home Page:
https://github.com/XX-net/XX-Net/wiki/English-Home-Page
When using https connection,XX-Net will send a SSL certificate,the SSL certificate come from itself,may be problem happen to here
I tested,not using https is no problem.
Proxy log report:ssl error: [SSL: TLSV1_ALERT_DECRYPT_ERROR] tlsv1 alert decrypt error (_ssl.c:590), create full domain cert for host:www.youtube.com

**Comment by yan12125** [comment]
You need to add ```--no-check-certificate``` to youtube-dl when using XX-net.
