### ISSUE TITLE
Vevo Links Not Working

### ISSUE THREAD

**Issue by goldensun87** [rg3/youtube-dl#9370]
I can pull up available formats with -F, but when I try to download one, the download cuts off before it can finish.

www.vevo.com/watch/INS171400764

C:\Users\Naved\Desktop>youtube-dl -fhls-akamai-5925 www.vevo.com/watch/INS171400764
WARNING: The url doesn't specify the protocol, trying with http
[Vevo] INS171400764: Downloading video info
[Vevo] INS171400764: Downloading SMIL file
WARNING: Unable to download SMIL file: HTTP Error 404: Not Found
[Vevo] INS171400764: Downloading akamai m3u8 information
[Vevo] INS171400764: Downloading level3 m3u8 information
[Vevo] INS171400764: Downloading amazon m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 25
[download] Destination: Mazhai Varum Video _ Naani, Nithya Menen-INS171400764.mp4
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 419, in main
  File "youtube_dl\__init__.pyo", line 409, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1732, in download
  File "youtube_dl\YoutubeDL.pyo", line 684, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 736, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 684, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 729, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1378, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1642, in process_info
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 2: ordinal not in range(128)

C:\Users\Naved\Desktop>youtube-dl -fhls-amazon-5925 www.vevo.com/watch/INS171400764
WARNING: The url doesn't specify the protocol, trying with http
[Vevo] INS171400764: Downloading video info
[Vevo] INS171400764: Downloading SMIL file
WARNING: Unable to download SMIL file: HTTP Error 404: Not Found
[Vevo] INS171400764: Downloading akamai m3u8 information
[Vevo] INS171400764: Downloading level3 m3u8 information
[Vevo] INS171400764: Downloading amazon m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 25
[download] Destination: Mazhai Varum Video _ Naani, Nithya Menen-INS171400764.mp4
[download]   7.4% of ~168.12MiB at  1.51MiB/s ETA 01:40      ERROR: content too short (expected 7040
224 bytes and served 5951064)

http://www.vevo.com/watch/carrie-underwood/Heartbeat-Behind-the-Scenes/GBE431500063

C:\Users\Naved\Desktop>youtube-dl -fhls-akamai-5584 http://www.vevo.com/watch/carrie-underwood/Heart
beat-Behind-the-Scenes/GBE431500063
[Vevo] GBE431500063: Downloading video info
[Vevo] Retrieving oauth token
[Vevo] GBE431500063: Downloading api video info
[Vevo] GBE431500063: Downloading video versions info
[Vevo] GBE431500063: Downloading amazon MPD information
[Vevo] GBE431500063: Downloading akamai MPD information
[Vevo] GBE431500063: Downloading amazon m3u8 information
[Vevo] GBE431500063: Downloading akamai m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 45
[download] Destination: Heartbeat - Behind the Scenes-GBE431500063.mp4
[download]   5.9% of ~132.79MiB at  1.25MiB/s ETA 01:44      ERROR: content too short (expected 3492
852 bytes and served 2409532)

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by dstftw** [comment]
`content too short` is usually an indication of a problem with your internet connection.
