### ISSUE TITLE
Python version 2.7.8 - Darwin-8.11.0-Power_Macintosh-powerpc-32bit can't update to youtube-dl **2016.05.01** from youtube-dl version 2016.04.24

### ISSUE THREAD

**Issue by gilles-c** [rg3/youtube-dl#9375]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

Description of my issue :
First :
# /usr/local/bin/youtube-dl -U --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-U', u'--verbose']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2016.04.24
[debug] Python version 2.7.8 - Darwin-8.11.0-Power_Macintosh-powerpc-32bit
[debug] exe versions: none
[debug] Proxy map: {}
Updating to version 2016.05.01 ...
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/update.py", line 151, in update_self
    urlh = opener.open(version['bin'][0])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 859, in https_open
    req, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>

ERROR: unable to download latest version

********
Second :
# wget https://yt-dl.org/latest/youtube-dl -O /usr/local/bin/youtube-dl
--2016-05-02 23:03:00--  https://yt-dl.org/latest/youtube-dl
Resolving yt-dl.org... 95.143.172.170
Connecting to yt-dl.org|95.143.172.170|:443... connected.
ERROR: cannot verify yt-dl.org's certificate, issued by `/C=BE/O=GlobalSign nv-sa/CN=AlphaSSL CA - SHA256 - G2':
  Unable to locally verify the issuer's authority.
ERROR: certificate common name `*.aries.uberspace.de' doesn't match requested host name `yt-dl.org'.
To connect to yt-dl.org insecurely, use `--no-check-certificate'.
*****
Third :
# wget --no-check-certificate https://yt-dl.org/latest/youtube-dl -O /usr/local/bin/youtube-dl
--2016-05-02 23:04:08--  https://yt-dl.org/latest/youtube-dl
Resolving yt-dl.org... 95.143.172.170
Connecting to yt-dl.org|95.143.172.170|:443... connected.
Unable to establish SSL connection.
su-4.3#

**Comment by yan12125** [comment]
Seems your SSL is totally broken. Did you change OpenSSL recently or other SSL libraries? And could you try with curl? See this [FAQ entry](https://github.com/rg3/youtube-dl#installation) for more information.

**Comment by gilles-c** [comment]
Maybe my OpenSSL is too old! 
After using wget as third in my previous post, /usr/local/bin/youtube-dl file was empty, nothing in it ! So I thought I must go again to 2016.04.24. So I have already used curl whithout -k options first :    
```
su-4.3# curl https://yt-dl.org/downloads/2016.04.24/youtube-dl -o /usr/local/bin/youtube-dl

curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). The default
 bundle is named curl-ca-bundle.crt; you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

```
and second with -k options :      
`#` ```
curl -k https://yt-dl.org/downloads/2016.04.24/youtube-dl -o /usr/local/bin/youtube-dl

curl: (35) Unknown SSL protocol error in connection to yt-dl.org:443 
su-4.3# wget --no-check-certificate https://yt-dl.org/downloads/2016.04.24/youtube-dl -O /usr/local/bin/youtube-dl
--2016-05-02 23:38:54--  https://yt-dl.org/downloads/2016.04.24/youtube-dl
Resolving yt-dl.org... 95.143.172.170
Connecting to yt-dl.org|95.143.172.170|:443... connected.
Unable to establish SSL connection.
su-4.3# exit

Then today I started the same computer this time on Linux debian 7.10 ( wheezy ) and updated youtube-dl to 2016.05.01 version and next i have copied this update on my Mac OS 10.4 powerpc and it is running now but I don't know if I will update the next update directly on Mac OS.

```

**Comment by yan12125** [comment]
From your log:

> ERROR: certificate common name*.aries.uberspace.de' doesn't match requested host name yt-dl.org

This indicates OpenSSL is too old. Connecting to https://yt-dl.org/ requires a new feature in OpenSSL called Server Name Indication (SNI). Only OpenSSL 0.9.8f or above supports it. [1] You can check the OpenSSL version via:
```
openssl version
```

[1] https://en.wikipedia.org/wiki/Server_Name_Indication

**Comment by gilles-c** [comment]
Thanks a lot for your explanations , my Openssl version is 0.9.7l.  I will close this topic, youtube-dl organisation can't update my openssl and it is not his goal. I yet will can turnaround this issue with Debian downloading of youtube-dl.
