### ISSUE TITLE
Can't download from BBC iPlayer

### ISSUE THREAD

**Issue by nyuszika7h** [rg3/youtube-dl#9380]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
>youtube-dl --verbose --write-sub "http://www.bbc.co.uk/iplayer/episode/b03b5kl2/wolfblood-series-2-1-leader-of-the-pack"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--write-sub', 'http://www.bbc.co.uk/iplayer/episode/b03b5kl2/wolfblood-series-2-1-leader-of-the-pack']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.05.01
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: ffmpeg N-79690-g78baa45, ffprobe N-79690-g78baa45
[debug] Proxy map: {}
[bbc.co.uk] b03b5kl2: Downloading video page
[bbc.co.uk] b03b5hp2: Downloading media selection XML
[bbc.co.uk] b03b5hp2: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b5hp2: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b5hp2: Downloading m3u8 information
WARNING: Failed to download m3u8 information: Remote end closed connection without response
[bbc.co.uk] b03b5hp2: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b5hp2: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
[bbc.co.uk] b03b5hp2: Downloading captions
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\program files\python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "c:\program files\python35\lib\site-packages\youtube_dl\extractor\common.py", line 341, in extract
    return self._real_extract(url)
  File "c:\program files\python35\lib\site-packages\youtube_dl\extractor\bbc.py", line 509, in _real_extract
    self._sort_formats(formats)
  File "c:\program files\python35\lib\site-packages\youtube_dl\extractor\common.py", line 862, in _sort_formats
    raise ExtractorError('No video formats found')
youtube_dl.utils.ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

I can watch videos fine (using Borderless Internet's DNS), but since recently, trying to download them with youtube-dl is giving a 403 error.

**Comment by dstftw** [comment]
Works fine with random UK proxy. Most likely they don't spoof DNS for hostnames where m3u8 playlists are stored (`cp401489-vh.akamaihd.net` and maybe others). Closing as not a youtube-dl issue.

**Comment by nyuszika7h** [comment]
Thanks for confirming that, I tried to ask a UK friend but they couldn't check at that time.
