### ISSUE TITLE
Question about youtube publication date and actual file timestamp

### ISSUE THREAD

**Issue by pprw** [rg3/youtube-dl#9386]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---
### Question ###

This is a question regarding youtube-dl and youtube, it is not a bug of youtube-dl.

I download videos from youtube using youtube-dl and I have some trouble to organize these videos on my computer. The reason is that date modification of files are neither the publication date nor the upload date by the channel author.

Here is an example: 

[This video](https://www.youtube.com/watch?v=EJqppbg7WKo) was published on Sep 10, 2015

I download it:

```
~$ youtube-dl -v --date 20150910 https://www.youtube.com/watch?v=EJqppbg7WKo[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--date', u'20150910', u'https://www.youtube.com/watch?v=EJqppbg7WKo']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.10 - Linux-4.2.0-35-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[youtube] EJqppbg7WKo: Downloading webpage
[youtube] EJqppbg7WKo: Downloading video info webpage
[youtube] EJqppbg7WKo: Extracting video information
[youtube] EJqppbg7WKo: Downloading MPD manifest
[debug] Invoking downloader on u'https://r1---sn-gxo5uxg-jqbe.googlevideo.com/videoplayback?expire=1462380219&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=video%2Fmp4&dur=529.298&itag=22&pl=19&source=youtube&requiressl=yes&fexp=9410706%2C9416126%2C9416891%2C9418751%2C9419451%2C9422596%2C9425352%2C9428398%2C9431012%2C9431045%2C9432564%2C9432583%2C9432684%2C9433096%2C9433425%2C9433946%2C9434289%2C9434344%2C9434510%2C9434601&lmt=1446984847946854&mm=31&mn=sn-gxo5uxg-jqbe&id=o-ACteetZ9aVH3H1MFgIMbyloLqgIFfqs6yGwRHZ8kNZJg&upn=IEuvL_l3QKA&ip=193.54.3.218&key=yt6&mt=1462358488&mv=m&ms=au&ipbits=0&initcwndbps=6202500&pcm2cms=yes&signature=A0C8A777E4D9A169A0135B6810B2A1F89CF93EF4.D8D3D451E3E3362A46508E0C5F11658B7F7175CC&sver=3&ratebypass=yes'
[download] Destination: Death by Selfie-EJqppbg7WKo.mp4
[download] 100% of 153.16MiB in 00:13
```

And I obtain a file edited on Nov 8, 2015:
```
$ ls -la Death\ by\ Selfie-EJqppbg7WKo.mp4 
-rw-rw-r-- 1 user user 160601568 nov.   8 13:14 Death by Selfie-EJqppbg7WKo.mp4
```

Therefore I cannot organize videos on my hard drive by publication or upload date.

Could someone explain to me this behavior? Is it a way to obtain a file with the date of upload or publication?

**Comment by dstftw** [comment]
Last modification date is set according to `Last-Modified` HTTP header. This behavior can be disabled with `--no-mtime` (modification time will be set according to current time).

**Comment by dsoprea** [comment]
I'm not sure that setting the modified-time produces much value. I downloaded one video and the mtime is exactly one year earlier than the date on the YouTube page. I downloaded another, and the mtime is set to now. Is the timestamp isn't intuitive, predictable, or what people otherwise expect it to be, then it seems useless and confusing.

This might just be my opinion, but I'm +1 for killing it.
