### ISSUE TITLE
Build with gmake < 4 broken: missing separator

### ISSUE THREAD

**Issue by jengelh** [rg3/youtube-dl#9387]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

When buliding under openSUSE 13.1 with (GNU) make-3.82, or SLES 11 with GNU make-3.81, the build fails:
```
[   33s] + /usr/bin/mkdir /home/abuild/rpmbuild/BUILDROOT/youtube-dl-2016.05.01-112.1.x86_64
[   33s] + cd youtube-dl
[   33s] + perl -i -pe '
[   33s]         s{^PREFIX\ \?=\ /usr/local}{PREFIX ?= /usr};
[   33s]         s{^BINDIR\ \?=\ \$\(PREFIX\)/bin}{BINDIR\ \?=\ /usr/bin};
[   33s]         s{^MANDIR\ \?=\ \$\(PREFIX\)/man}{MANDIR\ \?=\ /usr/share/man};
[   33s]         s{^SHAREDIR\ \?=\ \$\(PREFIX\)/share}{SHAREDIR\ \?=\ /usr/share};' Makefile
[   33s] + exit 0
[   33s] Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.3EufIx
[   33s] + umask 022
[   33s] + cd /home/abuild/rpmbuild/BUILD
[   33s] + cd youtube-dl
[   33s] + make DESTDIR=/home/abuild/rpmbuild/BUILDROOT/youtube-dl-2016.05.01-112.1.x86_64 install
[   33s] Makefile:15: *** missing separator.  Stop.
```
It appears that the `variable != value` syntax as introduced by commit 3ff63fb3657fee9e0c2df9d5bb96ae5827f257cc is not supported with make 3.x, but only 4.0 and up.

**Comment by jaimeMF** [comment]
I don't know of other way to make it compatible with BSD make, so we'll have to think something. Note that gmake 4.0 [was released in 2013](https://lists.gnu.org/archive/html/info-gnu/2013-10/msg00006.html), so it's not something really new.

**Comment by yan12125** [comment]
The following syntax:
```
SYSCONFDIR = $(shell if [ $(PREFIX) = /usr -o $(PREFIX) = /usr/local ]; then echo /etc; else echo $(PREFIX)/etc; fi)
```
Works on GNU make 4.1, too. Does it work on GNU make 3.81 and/or BSD make?

**Comment by jaimeMF** [comment]
No, `$(shell ...)` is only available in GNU make.
I can be changed to
```make
SYSCONFDIR = $$(if [ $(PREFIX) = /usr -o $(PREFIX) = /usr/local ]; then echo /etc; else echo $(PREFIX)/etc; fi)
```
but that means it gets executed each time you write `$(SYSCONFDIR)`.

**Comment by yan12125** [comment]
> but that means it gets executed each time you write ```$(SYSCONFDIR)```.

If we want to support GNU make 3.x as well as BSD make it's inevitable. And it seems harmless to youtube-dl as the Makefile is quite small.

**Comment by jaimeMF** [comment]
@jengelh it should just work, but could you check if it works with this change in GNU make 3.x?

**Comment by yan12125** [comment]
@bdeyal Could you change the offending line:
```
SYSCONFDIR != if [ $(PREFIX) = /usr -o $(PREFIX) = /usr/local ]; then echo /etc; else echo $(PREFIX)/etc; fi
```
To the new syntax proposed in https://github.com/rg3/youtube-dl/issues/9387#issuecomment-216954854 and check whether the old make on CentOS works or not?

**Comment by bdeyal** [comment]
Works OK.

I use master with  git hash 0a33bb2cb2ca401ffe88e520d7bbd7482d976cbc

changes 2 locations. First is the line you gave above (line 15) and second at line 93:
`_EXTRACTOR_FILES = $$(find youtube_dl/extractor -iname '*.py' -and -not -iname 'lazy_extractors.py')`

I tested a single download, works OK.

**Comment by yan12125** [comment]
Thanks. I'll check the changes on BSD make before commiting.

**Comment by bdeyal** [comment]
After the change It works fine with NetBSD make too (called bmake in Fedora)
No difference compared to GNU make.

**Comment by yan12125** [comment]
Oh thanks! Which Fedora version did you test with? And which version of make does CentOS comes with, 3.81 or 3.82?

**Comment by bdeyal** [comment]
CentOS 7.2 comes with make 3.82
NetBSD bmake was built on CentOS from a Fedora 24 source rpm. Tested on CentOS, not Fedora.

Took the source rpm from here:
http://koji.fedoraproject.org/koji/buildinfo?buildID=716769

**Comment by yan12125** [comment]
Thanks for helping on tests. Fixed.

**Comment by yan12125** [comment]
Reverted my last change as breaking lazy extractors. Sorry for not having checked everything well.

**Comment by jaimeMF** [comment]
Then I don't think it can be made to support both old gmake versions and bmake. I don't mind dropping support for bmake, I just thought it would be nice to have it.

**Comment by yan12125** [comment]
OK. Dropped BSD make support as installing gmake on *BSD systems seems quite easy.
