### ISSUE TITLE
Creating security context failed (0x80090300)

### ISSUE THREAD

**Issue by carks32** [rg3/youtube-dl#9392]
For some reason, this morning I tried running a normal youtube video on mpv with youtube-dl but it gave me that error line. With also this.

`[stream] Failed to open https://r8---sn-n2gpou-hp5e.googlevideo.com/videoplaybac
k?ipbits=0&requiressl=yes&mime=video%2Fmp4&ratebypass=yes&lmt=1461728596035258&e
xpire=1462401786&mn=sn-n2gpou-hp5e&mm=31&ip=190.77.118.228&pl=19&dur=369.847&mv=
m&mt=1462379938&ms=au&itag=22&initcwndbps=140000&sparams=dur%2Cid%2Cinitcwndbps%
2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequir
essl%2Csource%2Cupn%2Cexpire&fexp=9405981%2C9410706%2C9413139%2C9416126%2C941689
1%2C9422596%2C9428398%2C9429012%2C9429245%2C9429379%2C9431012%2C9431684%2C943268
4%2C9432861%2C9433096%2C9433850%2C9433859%2C9433946%2C9434289%2C9434344%2C943439
0%2C9434505%2C9435850&id=o-ACjQBLfv9pjdIOoW-xkcWrxn_928YioME8qONlTjZH5P&sver=3&s
ignature=60264CC54844279F0797959B4A360F8A9CE5D5C8.E33D68B5D65561040CC74AD38ACC3C
C4C3D59200&source=youtube&upn=xTfRhCyPJb4&key=yt6.`

I tried with different videos but the problem was still there.

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by smitelli** [comment]
I'm posting this comment for posterity. I had almost the exact same issue, except my code was `0x80090304`. There was precious little info out there to help me solve the issue.

In my case, I was on Windows using an FFmpeg binary from [BtbN](https://github.com/BtbN/FFmpeg-Builds/releases). It turned out that my FFmpeg binary was apparently compiled without TLS v1.2 support, and that was the lowest version allowed by the remote HTTPS server hosting the HLS files. Switching to a [gyan.dev build](https://www.gyan.dev/ffmpeg/builds/) fixed it.
