### ISSUE TITLE
ustream:channel download failure

### ISSUE THREAD

**Issue by kshpytsya** [rg3/youtube-dl#9407]
$ youtube-dl --version
2016.05.01
$ youtube-dl  http://www.ustream.tv/channel/sauces-cam
... 
 File "/home/uken/.local/lib64/python3.5/site-packages/youtube_dl/extractor/common.py", line 885, in _formats_key
    proto_preference = 0 if determine_protocol(f) in ['http', 'https'] else -0.1
  File "/home/uken/.local/lib64/python3.5/site-packages/youtube_dl/utils.py", line 2020, in determine_protocol
    if url.startswith('rtmp'):
AttributeError: 'NoneType' object has no attribute 'startswith'
$ curl -s https://api.ustream.tv/videos/86423931.json
..."media_urls":{"flv":null}...

**Comment by yan12125** [comment]
Are you trying to download http://www.ustream.tv/recorded/86423931? It works now:
```
$ youtube-dl -v "http://www.ustream.tv/recorded/86423931" 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.ustream.tv/recorded/86423931']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Git HEAD: 401d147
[debug] Python version 3.5.1 - Linux-4.5.1-1-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: avconv v12_dev0-2683-ge944310, avprobe v12_dev0-2683-ge944310, ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[ustream] 86423931: Downloading JSON metadata
[debug] Invoking downloader on 'http://tcdn.ustream.tv/video/86423931?preset_id=1&e=1462622529&h=ca2e64a4caac606a2adf4171dab6df5f&source=api'
[download] Destination: Sauces Eagles-86423931.flv
[download]   0.1% of 1.66GiB at 936.42KiB/s ETA 30:59^C
ERROR: Interrupted by user
```
Closing as it looks like a temporary UStream server-side issue. Please paste the full verbose log (not omitting anything) if the problem persists.

**Comment by kshpytsya** [comment]
Yes, I can download it now, but it has been an intermittent issue several days ago. Anyway, even if this is a server side failure, maybe it would deserve a better reaction on the side of yt-dl instead of just a stacktrace.

**Comment by yan12125** [comment]
I see. Please leave a comment if the problem appears again.

**Comment by kshpytsya** [comment]
I has been working great several days in a row, but now failed again.
 # youtube-dl --verbose --write-pages  http://www.ustream.tv/channel/sauces-cam 2>&1 | tee _log
 # zip -r youtube-dl--sauces-cam--failure.zip youtube-dl--sauces-cam--failure
[youtube-dl--sauces-cam--failure.zip](https://github.com/rg3/youtube-dl/files/262011/youtube-dl--sauces-cam--failure.zip)
