### ISSUE TITLE
youtube-dl claims VEVO video is geoblocked when it's not

### ISSUE THREAD

**Issue by nyuszika7h** [rg3/youtube-dl#9408]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
>youtube-dl -v --proxy=79.188.42.46:8080 "http://www.vevo.com/watch/undefined/Universo/IT88J1300002"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--proxy=79.188.42.46:8080', 'http://www.vevo.com/watch/undefined/Universo/IT88J1300002']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.05.01
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: ffmpeg N-79690-g78baa45, ffprobe N-79690-g78baa45
[debug] Proxy map: {'https': '79.188.42.46:8080', 'http': '79.188.42.46:8080'}
[Vevo] IT88J1300002: Downloading video info
WARNING: [Vevo] Video is geoblocked, trying with the YouTube video FBLI_6-JfB4
[youtube] FBLI_6-JfB4: Downloading webpage

ERROR: Interrupted by user
```

---

### Description of your *issue*, suggested solution and other information

Using an HTTP proxy from Poland, I can watch the video fine in my browser but using the same proxy with youtube-dl, it says it's blocked. This is not a DNS unblocker so I don't think there should be any "leak". I already got the videos from YouTube, but VEVO has a higher bitrate so it would be nice if I could get it working.

**Comment by nyuszika7h** [comment]
Actually, this may be the same thing as #9366, even though not exactly the same error.

**Comment by yan12125** [comment]
Thanks for the report. Georestriction will be correctly checked in the next version.
