### ISSUE TITLE
Unable to download Dorkly.com's videos.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#9411]
Example:

$ youtube-dl -v http://www.dorkly.com/video/78482/all-the-deadpool-easter-eggs-that-you-probably-missed
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.dorkly.com/video/78482/all-the-deadpool-easter-eggs-that-you-probably-missed']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.4
[debug] exe versions: ffmpeg 2.8.6-1, ffprobe 2.8.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] all-the-deadpool-easter-eggs-that-you-probably-missed: Requesting header
WARNING: Falling back on generic information extractor.
[generic] all-the-deadpool-easter-eggs-that-you-probably-missed: Downloading webpage
[generic] all-the-deadpool-easter-eggs-that-you-probably-missed: Extracting information
[download] Downloading playlist: All the Deadpool Easter Eggs that You Probably Missed! - Dorkly Video
[generic] playlist All the Deadpool Easter Eggs that You Probably Missed! - Dorkly Video: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:new] 4879715482001: Downloading webpage
[brightcove:new] 4879715482001: Downloading JSON metadata
[brightcove:new] 4879715482001: Downloading m3u8 information
[brightcove:new] 4879715482001: Downloading m3u8 information
[debug] Invoking downloader on 'https://bcsecure04-a.akamaihd.net/34/4244402466001/201605/1599/4244402466001_4879821481001_4879715482001.mp4?pubId=4244402466001&videoId=4879715482001'
ERROR: unable to download video data: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1174, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1230, in connect
    server_hostname=sni_hostname)
  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 577, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 804, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1640, in process_info
    success = dl(filename, info_dict)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1582, in dl
    return fd.download(name, info)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/home/ant/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1942, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 473, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/home/ant/bin/youtube-dl/youtube_dl/utils.py", line 859, in https_open
    req, **kwargs)
  File "/usr/lib/python3.4/urllib/request.py", line 1176, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>

Thank you in advance. :)

**Comment by yan12125** [comment]
https://bcsecure04-a.akamaihd.net/34/4244402466001/201605/1599/4244402466001_4879821481001_4879715482001.mp4?pubId=4244402466001&videoId=4879715482001 works for me. Could you try the following command:
```
$ curl -v -O "https://bcsecure04-a.akamaihd.net/34/4244402466001/201605/1599/4244402466001_4879821481001_4879715482001.mp4?pubId=4244402466001&videoId=4879715482001"
```

**Comment by antdude** [comment]
$ youtube-dl "https://bcsecure04-a.akamaihd.net/34/4244402466001/201605/1599/4244402466001_4879821481001_4879715482001.mp4?pubId=4244402466001&videoId=4879715482001"
[generic] 4244402466001_4879821481001_4879715482001: Requesting header
WARNING: Could not send HEAD request to https://bcsecure04-a.akamaihd.net/34/4244402466001/201605/1599/4244402466001_4879821481001_4879715482001.mp4?pubId=4244402466001&videoId=4879715482001: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
[generic] 4244402466001_4879821481001_4879715482001: Downloading webpage
ERROR: unable to download video data: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>

$ curl -v -O "https://bcsecure04-a.akamaihd.net/34/4244402466001/201605/1599/4244402466001_4879821481001_4879715482001.mp4?pubId=4244402466001&videoId=4879715482001"
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 173.223.52.203...
* Connected to bcsecure04-a.akamaihd.net (173.223.52.203) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS alert, Server hello (2):
} [data not shown]
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by yan12125** [comment]
As cURL also fails, it's likely that SSL on your system is broken. Closing as it's out of the scope of youtube-dl.
