### ISSUE TITLE
Suport site younow.com

### ISSUE THREAD

**Issue by Mioni** [rg3/youtube-dl#9432]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.05.01_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.01**
### Before submitting an _issue_ make sure you have:
- [ X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl.exe https://www.younow.com/judy_b_stone/106628835/21680919/345faf9t/b/May-7,-2016
[generic] May-7,-2016: Requesting header
WARNING: Could not send HEAD request to https://www.younow.com/judy_b_stone/106628835/21680919/345faf9t/b/May-7,-2016: HTTP Error 403: Forbidden
[generic] May-7,-2016: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] May-7,-2016: Extracting information
ERROR: Unsupported URL: https://www.younow.com/judy_b_stone/106628835/21680919/345faf9t/b/May-7,-2016

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.younow.com/judy_b_stone/106628835/21680919/345faf9t/b/May-7,-2016
- Single video: https://www.younow.com/judy_b_stone/106628835/

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.
```

**Comment by Tatsh** [comment]
Some but not all YouNow streams are actually done via YouTube. This can be seen in the JSON when requesting `https://api.younow.com/php/api/broadcast/info/curId=0/user={}` [Example](https://api.younow.com/php/api/broadcast/info/curId=0/user=MsMastaFoxx_CosmicFam). It shows the `ytBroadcastId` (will not be there if the video is hosted via YouNow's streaming).

Any contributors, how would one forward a call to the `YouTubeIE` class's `_real_extract()` method, or would the case of YouTube go directly in that file `youtube_dl/extractor/youtube.py`?

**Comment by Tatsh** [comment]
Watch the pull request #12436
