### ISSUE TITLE
can not find youtube-dl downloaded videos

### ISSUE THREAD

**Issue by rofl0r** [rg3/youtube-dl#9434]
.... because youtube-dl is the only program i know that stores files not with the *actual* timestamp, but prefers to fetch the timestamp of when a video was uploaded to youtube and then manipulates the timestamp of the file in fs to match that of youtube(!?).

so instead of doing
```
~/video-dump $ ls -lat | head
... displaying the 10 most recent videos downloaded
```
i have to maintain a list and save all the titles of the videos i downloaded recently so i can find them in the FS when i wanna watch them.

this counterintuitive behaviour should imo be disabled.
if there are some people that want the file creation date of their file on their hd to match the youtube publishing date, those can use --magic-switch-to-enable-that, but it should definitively not be on by default.

**Comment by dstftw** [comment]
youtube-dl does not use upload date as timestamp but `Last-Modified` HTTP header. `wget` does exactly the same way. This is expected behavior and can be disabled with `--no-mtime`.

**Comment by rofl0r** [comment]
ok: since i didn't find the option when searching for "date", may i suggest you add that term to the --help entry for --no-mtime ?

**Comment by dstftw** [comment]
It'a already there:
```
    --no-mtime                       Do not use the Last-modified header to set
                                     the file modification time
```

**Comment by rofl0r** [comment]
where ? i don't see "date" mentioned.
