### ISSUE TITLE
[ARD:mediathek]  HTTP error 403 Forbidden

### ISSUE THREAD

**Issue by cyhojoey** [rg3/youtube-dl#9437]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.01**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Hi,

I encountered a big problem when I'm using youtue-dl to download video from ardmediathek through a proxy in Germany.

Here is the debug report:

Z:\>youtube-dl -v   --audio-quality 0 --proxy 176.9.148.180:3128 --no-check-cert
ificate "http://www.ardmediathek.de/tv/Musiksendungen-im-Ersten/Europakonzert-de
r-Berliner-Philharmonike/Das-Erste/Video?bcastId=7021916&documentId=35049154"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--audio-quality', u'0', u'--proxy', u'176.9
.148.180:3128', u'--no-check-certificate', u'http://www.ardmediathek.de/tv/Musik
sendungen-im-Ersten/Europakonzert-der-Berliner-Philharmonike/Das-Erste/Video?bca
stId=7021916&documentId=35049154']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: avconv v12_dev0-2683-ge944310, avprobe v12_dev0-2683-ge944
310, ffmpeg N-79883-g38eeb85
[debug] Proxy map: {u'http': u'176.9.148.180:3128', u'https': u'176.9.148.180:31
28'}
[ARD:mediathek] 35049154: Downloading webpage
[ARD:mediathek] 35049154: Downloading media JSON
[ARD:mediathek] 35049154: Downloading m3u8 information
[debug] Invoking downloader on u'http://hls-geo.daserste.de/i/videoportal/Film/c
_620000/622873/format,716451,716457,716450,716458,716459,.mp4.csmil/index_4_av.m
3u8?null=0'
[download] Destination: Europakonzert der Berliner Philharmoniker 2016-35049154.
mp4
[debug] avconv command line: avconv -y -headers 'Accept-Language: en-us,en;q=0.5

Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/44.0
 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: _alid_=sjIaf2IAxF8hbD6GCjgWMQ==
' -i 'http://hls-geo.daserste.de/i/videoportal/Film/c_620000/622873/format,71645
1,716457,716450,716458,716459,.mp4.csmil/index_4_av.m3u8?null=0' -c copy -f mp4
-bsf:a aac_adtstoasc 'file:Europakonzert der Berliner Philharmoniker 2016-350491
54.mp4.part'
avconv version v12_dev0-2683-ge944310, Copyright (c) 2000-2016 the Libav develop
ers
  built on May  8 2016 20:52:15 with gcc 4.8.3 (Gentoo 4.8.3 p1.1, pie-0.5.9)
[http @ 0000000000ad8de0] HTTP error 403 Forbidden
http://hls-geo.daserste.de/i/videoportal/Film/c_620000/622873/format,716451,7164
57,716450,716458,716459,.mp4.csmil/index_4_av.m3u8?null=0: Input/output error

ERROR: ffmpeg exited with code 1
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 419, in main
  File "youtube_dl\__init__.pyo", line 409, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1732, in download
  File "youtube_dl\YoutubeDL.pyo", line 684, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 729, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 1378, in process_video_result
  File "youtube_dl\YoutubeDL.pyo", line 1640, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1582, in dl
  File "youtube_dl\downloader\common.pyo", line 350, in download
  File "youtube_dl\downloader\external.pyo", line 42, in real_download
  File "youtube_dl\downloader\common.pyo", line 161, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 547, in report_error
  File "youtube_dl\YoutubeDL.pyo", line 509, in trouble

**Comment by dstftw** [comment]
You have to setup `HTTP_PROXY` env variable to `http://176.9.148.180:3128`.
