### ISSUE TITLE
Unable to download webpage

### ISSUE THREAD

**Issue by rohitkumar07** [rg3/youtube-dl#9438]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl --verbose https://www.youtube.com/playlist?list=PL4sylQahxyeqyoREq2yFZrGpSuDghweSX
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/playlist?list=PL4sylQahxyeqyoREq2yFZrGpSuDghweSX']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.6 - Linux-3.13.0-85-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] PL4sylQahxyeqyoREq2yFZrGpSuDghweSX: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol> (caused by URLError(SSLError(8, '_ssl.c:510: EOF occurred in violation of protocol'),))
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 388, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1942, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 859, in https_open
    req, **kwargs)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

**Comment by yan12125** [comment]
Can you watch the playlist in browsers? And did you use any proxies/VPNs?

**Comment by rohitkumar07** [comment]
Yes I can watch the playlist in browsers. Not using any proxy/VPN.

**Comment by yan12125** [comment]
Could you try with newer Python versions? Python 2.7.11 or 3.x.

**Comment by yan12125** [comment]
Sorry mis-closing.

**Comment by nerethos** [comment]
I am also getting this error however youtube-dl was bundled with another application. How would I go about debugging this error?

**Comment by yan12125** [comment]
Does the problem occur with [a standalone installation](https://github.com/rg3/youtube-dl/blob/master/README.md#installation)?

**Comment by nerethos** [comment]
No it's being run through another python script. The script is a bot that plays music to a voice chat service https://github.com/SexualRhinoceros/MusicBot/tree/review

**Comment by yan12125** [comment]
In ```musicbot/downloader.py```, remove ```'quiet': True,``` and add ```'verbose': True,```

**Comment by nerethos** [comment]
`[Command] 156451338635575296/Nerethos (*play https://youtu.be/C1pQxz5wzjQ)
[youtube] C1pQxz5wzjQ: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable (caused b
y <HTTPError 503: 'Service Unavailable'>); please report this issue on https://y
t-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.or
g/update  on how to update. Be sure to call youtube-dl with the --verbose flag a
nd include its complete output.
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\youtube_dl\extractor\common.py", line 388, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\sit
e-packages\youtube_dl\YoutubeDL.py", line 1945, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\url
lib\request.py", line 471, in open
    response = meth(req, response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\url
lib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\url
lib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\url
lib\request.py", line 443, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\url
lib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\url
lib\request.py", line 471, in open
    response = meth(req, response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\url
lib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\url
lib\request.py", line 509, in error
    return self._call_chain(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\url
lib\request.py", line 443, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\url
lib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

<class 'musicbot.exceptions.CommandError'>: ERROR: Unable to download webpage: H
TTP Error 503: Service Unavailable (caused by <HTTPError 503: 'Service Unavailab
le'>); please report this issue on https://yt-dl.org/bug . Make sure you are usi
ng the latest version; see  https://yt-dl.org/update  on how to update. Be sure
to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by nerethos** [comment]
Sorry its not that easy to read, it's just a copy/paste of the cmd window

**Comment by yan12125** [comment]
"HTTP 503 Service Unavailable" is different from @rohitkumar07's case. (EOF occurred in violation of protocol) It looks like a temporary issue on YouTube-server side. Please open a new issue if the problem persists.

By the way, you can use code marks for raw texts. See https://guides.github.com/features/mastering-markdown/.

**Comment by nerethos** [comment]
Sorry I didn't notice his error code, just the thread title. I'll open a new issue if I'm still having problems in a few days.

Thanks for the markdown info, I created my account to post this issue so I'm not familiar with it!

**Comment by yan12125** [comment]
@rohitkumar07 Could you try:
```
curl -v "https://www.youtube.com/playlist?list=PL4sylQahxyeqyoREq2yFZrGpSuDghweSX"
```

**Comment by rohitkumar07** [comment]
I tried:
```
$ curl -v "https://www.youtube.com/playlist?list=PL4sylQahxyeqyoREq2yFZrGpSuDghweSX" > out.txt
```

The out.txt file is attached.
```
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 216.58.197.46...
* Connected to www.youtube.com (216.58.197.46) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using ECDHE-ECDSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: C=US; ST=California; L=Mountain View; O=Google Inc; CN=*.google.com
* 	 start date: 2016-05-04 09:05:56 GMT
* 	 expire date: 2016-07-27 08:39:00 GMT
* 	 subjectAltName: www.youtube.com matched
* 	 issuer: C=US; O=Google Inc; CN=Google Internet Authority G2
* 	 SSL certificate verify ok.
> GET /playlist?list=PL4sylQahxyeqyoREq2yFZrGpSuDghweSX HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.youtube.com
> Accept: */*
> 
< HTTP/1.1 200 OK
< Strict-Transport-Security: max-age=604800
< P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."
< X-XSS-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< X-Frame-Options: SAMEORIGIN
< Expires: Tue, 27 Apr 1971 19:44:06 EST
< Cache-Control: no-cache
< Date: Sat, 14 May 2016 16:34:57 GMT
* Server Ytfe_Worker is not blacklisted
< Server: Ytfe_Worker
< Set-Cookie: VISITOR_INFO1_LIVE=rrCnV1bQ1HM; path=/; domain=.youtube.com; expires=Fri, 13-Jan-2017 04:27:57 GMT; httponly
< Set-Cookie: PREF=f1=40000000; path=/; domain=.youtube.com; expires=Fri, 13-Jan-2017 04:27:57 GMT
< Set-Cookie: YSC=v5Qhi21MDNc; path=/; domain=.youtube.com; httponly
< Alternate-Protocol: 443:quic
< Alt-Svc: quic=":443"; ma=2592000; v="33,32,31,30,29,28,27,26,25"
< Accept-Ranges: none
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< 
{ [data not shown]
100  167k    0  167k    0     0   266k      0 --:--:-- --:--:-- --:--:--  266k
* Connection #0 to host www.youtube.com left intact

```
[out.txt](https://github.com/rg3/youtube-dl/files/264605/out.txt)

**Comment by yan12125** [comment]
Is youtube-dl still broken?

**Comment by rohitkumar07** [comment]
Seems to be working now. It was able to download the playlist.

**Comment by yan12125** [comment]
OK closing.
