### ISSUE TITLE
Broken urlhandle_detect_ext on Python 2.x

### ISSUE THREAD

**Issue by sunk818** [rg3/youtube-dl#9440]
## Please follow the guide below
E:\>youtube-dl --verbose https://hearthis.at/twitchsf/dj-jim-hopkins-totally-bitchin-80s-dance-mix/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://hearthis.at/twitchsf/dj-jim-hopkins-totally-bitchin-80s-dance-mix/']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.05.01
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {'ftp': 'ftp://127.0.0.1:8888', 'http': 'http://127.0.0.1:8888', 'https': 'https://127.0.0.1:8888'}
[HearThisAt] twitchsf - dj-jim-hopkins-totally-bitchin-80s-dance-mix: Downloading webpage
[HearThisAt] 811296: Downloading playlist
[HearThisAt] twitchsf - dj-jim-hopkins-totally-bitchin-80s-dance-mix: Determining extension
ERROR: An extractor error has occurred. (caused by KeyError(u'content-disposition',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\common.pyo", line 341, in extract
  File "youtube_dl\extractor\hearthisat.pyo", line 92, in _real_extract
  File "youtube_dl\utils.pyo", line 1969, in urlhandle_detect_ext
  File "youtube_dl\utils.pyo", line 1965, in <lambda>
  File "rfc822.pyo", line 393, in __getitem__
KeyError: u'content-disposition'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 673, in extract_info
  File "youtube_dl\extractor\common.pyo", line 347, in extract
ExtractorError: An extractor error has occurred. (caused by KeyError(u'content-disposition',)); please report this issue on https://yt-dl.org/bug . Make sure yo
u are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dylziez** [comment]
https://stream42.hearthis.at/be4472628f02e1fd4500dcafb0d6273a.mp3 is the URL I get by sniffing the request manually, doesn't look like soundcloud

**Comment by sunk818** [comment]
Oh, I guess this would be an enhancement request to support yet another domain?

**Comment by yan12125** [comment]
It's not HeartThisAt's fault but youtube-dl's. I'm trying to fix it.

**Comment by yan12125** [comment]
Thanks for the report. HearThis.at will function again in the next version.
