### ISSUE TITLE
Error 403 Forbidden on Soundcloud

### ISSUE THREAD

**Issue by cmehdy** [rg3/youtube-dl#9443]
Hello, I had apparently misunderstood one thing about the guidelines and my post got closed.
I fixed it now, let me know if anything else is required, Thank you.

- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.01**

And I have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of the *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---

### Description of your *issue*, suggested solution and other information

I have used youtube-dl to download from a playlist on soundcloud. The playlist contains 238 items of various sizes. After downloading 38 items, I received an error 403 forbidden.
I then switched to another wifi in a different location altogether and tried to resume the download at item 38, with the same error. At item 39, with the same error.
I am unable to download from that soundcloud playlist, even when I use the personal credentials of the person who made that list.

The command line I have tried using are (one on each line):

```
youtube-dl https://soundcloud.com/evurutin/likes --playlist-start 38
youtube-dl https://soundcloud.com/evurutin/likes --playlist-start 39
youtube-dl https://soundcloud.com/evurutin/likes --playlist-start 38 --extract-audio
youtube-dl https://soundcloud.com/evurutin/likes --playlist-start 38 -u (that person's username) -p (that person's password)
```

And in all cases I obtain the same error

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://soundcloud.com/evurutin/likes', '--playlist-start', '39', '--extract-audio', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.01
[debug] Python version 3.4.3 - Darwin-15.4.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[soundcloud:user] evurutin: Downloading user info
[soundcloud:user] evurutin: Downloading track page 1
[soundcloud:user] evurutin: Downloading track page 2
[soundcloud:user] evurutin: Downloading track page 3
[soundcloud:user] evurutin: Downloading track page 4
[soundcloud:user] evurutin: Downloading track page 5
[soundcloud:user] evurutin: Downloading track page 6
[download] Downloading playlist: EvUrutin (Likes)
[soundcloud:user] playlist EvUrutin (Likes): Collected 238 video ids (downloading 200 of them)
[download] Downloading video 1 of 200
[soundcloud] christineandthequeens/it-1: Resolving id
[soundcloud] christineandthequeens/it-1: Downloading info JSON
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 388, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1942, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Users/mehdy/anaconda/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/Users/mehdy/anaconda/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/mehdy/anaconda/lib/python3.4/urllib/request.py", line 501, in error
    result = self._call_chain(*args)
  File "/Users/mehdy/anaconda/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/Users/mehdy/anaconda/lib/python3.4/urllib/request.py", line 684, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Users/mehdy/anaconda/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/Users/mehdy/anaconda/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/mehdy/anaconda/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/Users/mehdy/anaconda/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/Users/mehdy/anaconda/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

Nothing from the database here shows me anything useful about what I can do to solve the issue.
I hope I am writing this correctly. Please let me know if any additional information is needed.
Thank you

**Comment by dstftw** [comment]
Can you watch it in browser when you receive 403 with youtube-dl in the first place?

**Comment by cmehdy** [comment]
It seems like the song is greyed out and unavailable in browser. I should have double checked that, because I used to load it fine before.
So considering the song isn't made available anymore on that playlist, it is not a bug from youtube-dl but a normal response from the site.
Sorry for bothering you, the problem can be considered as solved.
