### ISSUE TITLE
Download of playlist stops when one video is blocked

### ISSUE THREAD

**Issue by jerezim** [rg3/youtube-dl#9447]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

[download] Downloading video 7 of 126
[youtube] XYZ: Downloading webpage
[youtube] XYZ: Downloading video info webpage
ERROR: XYZ: YouTube said: This video contains content from SME, who has blocked it in your country on copyright grounds.
Traceback (most recent call last):
  File "/home/jz/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 673, in extract_info
    ie_result = ie.extract(url)
  File "/home/jz/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/home/jz/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1311, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: XYZ: YouTube said: This video contains content from YYY, who has blocked it in your country on copyright grounds.

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

When downloading a playlist, if *one* video is inaccessible (because copyright or blah), youtube-dl may continue and download the other ones, instead of failing. (I actually dont know how to download the remaining 100 videos...)

**Comment by yan12125** [comment]
Use ```--ignore-errors```.

**Comment by jerezim** [comment]
Oh man! So sorry I thought I looked for such an option.

Thanks for your amazingly prompt answer! <3

All glory to youtube-dl, one of my favourite free software to this day! ;)
