### ISSUE TITLE
ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by lenines** [rg3/youtube-dl#9456]
[youtube] FXLTgma90DQ: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by lenines** [comment]
I was using the version youtube-dl==2015.12.29 and everything worked well until about 4 days backwards the script is and next (I am using python2.7.6 and s3)

file_name_url = "/home/ubuntu/videos/"
video_id = " FXLTgma90DQ"
file_name ="{0}.mp4".format(video_id)
cli = "youtube-dl --format 18 -o '{0}{1}' http://www.youtube.com/watch?v={2}".format(file_name_url,file_name,video_id)
subprocess.call(cli, shell=True)

and I get the following error

[youtube] FXLTgma90DQ: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I upgraded to version youtube-dl==2016.05.10 and the problem persists
