### ISSUE TITLE
Unable to download cinemassacre.com's videos again as of 5/11/2016 1 PM PDT.

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#9457]
$ youtube-dl --verbose http://cinemassacre.com/2016/05/11/godzilla-resurgence-2016/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://cinemassacre.com/2016/05/11/godzilla-resurgence-2016/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.10
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.4
[debug] exe versions: ffmpeg 2.8.6-1, ffprobe 2.8.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[Cinemassacre] godzilla-resurgence-2016: Downloading webpage
ERROR: Unable to find player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/cinemassacre.py", line 102, in _real_extract
    raise ExtractorError('Unable to find player data')
youtube_dl.utils.ExtractorError: Unable to find player data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Thank you in advance. :)

**Comment by antdude** [comment]
FYI: http://www.reddit.com/r/TheCinemassacre/comments/4j2tro/new_video_player_and_how_you_can_help/

**Comment by yan12125** [comment]
Now Cinemassacre videos can be handled by the generic extractor. The old implementation should be removed so that the generic handler can extract the video correctly.

**Comment by antdude** [comment]
Thanks Yan12125. I just got 5/16/2016 version and now I can download again. It didn't work a few hours ago with 5/10/2016 version. :)
