### ISSUE TITLE
youtube-dl -g [url] does not load on other browser

### ISSUE THREAD

**Issue by electronee** [rg3/youtube-dl#9460]
Hi! Thank you for the great project. 

As I am trying to simulate youtube alike application for my project, I do fail to play a youtube video source URL on frontend (another IP than the backend) that is extracted on backend. When I play at the same machine that the URL extracted from, the same URL does not played at the another machine..

The issue is similar: https://github.com/rg3/youtube-dl/issues/897 and it is possibly because of --cookies . 

I could not find a solution at the above issue, therefore opening a new issue here. 

Any possible way to solve the problem?

**Comment by yan12125** [comment]
> another IP than the backend

There's no guarantee that the resolved URL can be played on different IPs. See [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#i-extracted-a-video-url-with--g-but-it-does-not-play-on-another-machine--in-my-webbrowser). https://github.com/rg3/youtube-dl/issues/9001#issuecomment-201991818 may help.

**Comment by electronee** [comment]
Thanks alot, redirector works.
