### ISSUE TITLE
[FXX] add support

### ISSUE THREAD

**Issue by TRox1972** [rg3/youtube-dl#9462]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.05.10
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.fxnetworks.com/video/678325827950
- Single video: http://www.fxnetworks.com/video/664163395617

---

### Description of your *issue*, suggested solution and other information

I am requesting site-support for FXX.com. As far as I can see, all the videos are georestricted to the US, and you do have to log in. But the first time you visit the site, you get a hour long preview-pass, i.e. you have free access (except georestriction) for one hour.

**Comment by TRox1972** [comment]
The site is using ThePlatform but most of the content requires an auth token (which you get by logging in or getting a preview pass). It's relatively to sniff out the request for the SMIL playlist, which contains the auth token, but it's harder to automate the process as I've yet to find exactly from where the request is sent and how it's created.

**Comment by remitamine** [comment]
> I've yet to find exactly from where the request is sent and how it's created.

i think it uses Adobe Pass to get the `auth` query param that will be passed in ThePlatform SMIL url(other sites use the same like natgeo,fox,ae network sites...).

**Comment by TRox1972** [comment]
@remitamine thanks for that info 😄
