### ISSUE TITLE
Question (Possible Feature Request) Regarding --match-title

### ISSUE THREAD

**Issue by wright546** [rg3/youtube-dl#9467]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

I'm using "ytsearchdate10:termA termB termC" in a script run every 48 hours via cron to download certain videos that are uploaded to Youtube on a daily/weekly basis.

From what I can tell --match-title works as logical "or", meaning that "--match-title term1|term2" will match a video with either term1 or term2 in the title.  Is there a way to make --match-title function as logical "and"?  So that a video would only download if term1 and term2 were both in the title?

Thank you for your help!

**Comment by dstftw** [comment]
`--match-title` accepts arbitrary regular expression, e.g. `term1.*term2`.

**Comment by phihag** [comment]
@dstftw is right, but `term1.*term2` requires term1 to come before term2. To match both ignoring order use positive lookaheads:
```
$ youtube-dl -e test:youtube:playlist --match-title 'youtube'
Download Youtube Playlist with Youtube-dl
Updating youtube-dl
37 youtube-dl - faster downloads with aria2 (Programothesis by emailatask.com)
$ youtube-dl -e test:youtube:playlist --match-title 'youtube.*download'
37 youtube-dl - faster downloads with aria2 (Programothesis by emailatask.com)
$ # ^^ youtube before download ^^    vv youtube AND download vv
$ youtube-dl -e test:youtube:playlist --match-title '^(?=.*youtube)(?=.*download)'
Download Youtube Playlist with Youtube-dl
37 youtube-dl - faster downloads with aria2 (Programothesis by emailatask.com)
```

**Comment by wright546** [comment]
That is very helpful, thank you both very much!
