### ISSUE TITLE
Hangs on ooyala video

### ISSUE THREAD

**Issue by sergei-sh** [rg3/youtube-dl#9468]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

From this page: http://www.afl.com.au/video/2015-10-28/forward-of-the-future-v-forward-of-the-past

youtube-dl http://bpmultihlsvod5257.ngcdn.telstra.com/hds/amlst:eyJkIjowLCJwIjoiaW5nZXN0X2FmbGZpbG1zX3ZvZC84MDA2ODYvVk9EX1NvdXJjZS8yMDE1LTEwLTI4XzEwLTMyLTM0LTk1NzAiLCJUYWciOiJoZHMiLCJ0IjoiZmxhc2giLCJ2cCI6W3siYiI6IjI0MDAiLCJoIjo3MjAsInciOjEyODB9LHsiYiI6IjE4MDAiLCJoIjo0MDYsInciOjcyMH0seyJiIjoiMTEwMCIsImgiOjQwNiwidyI6NzIwfSx7ImIiOiI3MDAiLCJoIjozNjAsInciOjY0MH0seyJiIjoiNDAwIiwiaCI6MjcwLCJ3Ijo0ODB9LHsiYiI6IjIzNiIsImgiOjE4MCwidyI6MjMwfSx7ImIiOiIxNjgiLCJoIjoxODAsInciOjMyMH1dfQ==/manifest.f4m?SIGV=2&IS=0&ET=1463066908&CIP=116.103.191.160&KO=1&KN=7&US=1cc48dd39c7e43c36adffa3189accd529dfd9e81

[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
[generic] manifest: Downloading f4m manifest
[generic] manifest: Downloading f4m manifest
[generic] manifest: Downloading f4m manifest
[generic] manifest: Downloading f4m manifest
[generic] manifest: Downloading f4m manifest
[generic] manifest: Downloading f4m manifest
[generic] manifest: Downloading f4m manifest

And stays in this state infinitely

**Comment by dstftw** [comment]
Works fine for me.
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by sergei-sh** [comment]
dsff

**Comment by yan12125** [comment]
You need to enclose URLs in single or double quotes. See [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command).

**Comment by sergei-sh** [comment]
Thanks a lot!


С уважением,
Сергей

2016-05-13 16:19 GMT+07:00 Yen Chi Hsuan <notifications@github.com>:
