### ISSUE TITLE
Can you change the default audio format for the -x option

### ISSUE THREAD

**Issue by DasCyka** [rg3/youtube-dl#9469]
[x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**
[x ] At least skimmed through [README](https://github.com/rg3/youtube-
[x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
[x] Question

I mostly use youtube-dl to download music to my server from my mobile phone, which is then syncthinged onto my phone for listening. If i pass -x it tends to download in an unusable format like opus or ogg. Call me lazy but being on the phone I find it cumbersome to specify _--extract-audio --audio-format mp3  --audio-quality  0_  every-time. Is it possible to change the default quality and container for the -x option?

**Comment by dstftw** [comment]
Add these options to [configuration file](https://github.com/rg3/youtube-dl#configuration).

**Comment by DasCyka** [comment]
Brilliant! Thank you! :)
