### ISSUE TITLE
[Site-support-request] Deutsche Welle TV

### ISSUE THREAD

**Issue by Wikinaut** [rg3/youtube-dl#9475]
Pls. support also dw.com pages like 

* http://www.dw.com/en/documentaries-the-rosetta-mission-2016-05-12/e-19203707-9798

For this specific page I determiend ```http://tv-download.dw.de/dwtv_video/flv/inf/inf20160512_rosetta7735_sd_sor.mp4``` as stream url.

**Comment by yan12125** [comment]
Now the video is this page is gone, and http://tv-download.dw.de/dwtv_video/flv/inf/inf20160512_rosetta7735_sd_sor.mp4 returns 404.

**Comment by Wikinaut** [comment]
uh, yes, They remove videos after 8 days or so.

take another fresh example:

http://www.dw.com/en/program/documentaries/s-3610-9798
==> Video
http://www.dw.com/en/documentaries-welcome-to-the-90s-2016-05-21/e-19220158-9798

Resulting Video stream Url appears to be

http://tv-download.dw.de/dwtv_video/flv/inf/inf20160521_hiphop7873_sd_sor.mp4

**Comment by Wikinaut** [comment]
pls. reopen

**Comment by yan12125** [comment]
> They remove videos after 8 days or so

Don't know that, sorry.

**Comment by yan12125** [comment]
Thanks for the report. DW documentaries will be supported in the next version.

Will the latest example get deleted in a few days, too?

**Comment by Wikinaut** [comment]
@yan12125 

I looked for a more "static" example, here something from 2013, where I expect that it will not be deleted in the near future, so you can take it as an example case

http://www.dw.com/en/classical-music-stars-in-the-film-the-highest-level/av-17166597 (Lang Lang and Berlin Philharmonic Orchestra...)

**Comment by yan12125** [comment]
http://www.dw.com/en/classical-music-stars-in-the-film-the-highest-level/av-17166597 is an ```av-*``` video, which was supported before my fix. Do you have a ```e-*``` example like http://www.dw.com/en/documentaries-welcome-to-the-90s-2016-05-21/e-19220158-9798?

**Comment by Wikinaut** [comment]
Uh, I did not dig into the page, and/or did not know what is essential. Now I know. I will look for such an example page in the next days.

**Comment by yan12125** [comment]
Thanks. I'm seeking for a long-term example so that [the integration test can use it](https://github.com/rg3/youtube-dl/blob/6c0376f/youtube_dl/extractor/dw.py#L38-L48). If there's no such an example is also fine. Just open a new issue here.
