### ISSUE TITLE
bestaudio webm remux to .opus/.ogg container

### ISSUE THREAD

**Issue by nwgat** [rg3/youtube-dl#9478]
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other
### Description of your _issue_, suggested solution and other information

when i run with `-f bestaudio`, the output format is webm, even when the stream is audio only 

i propose this
if stream is opus then remux to .opus container
if stream is vorbis then remux to .ogg container
if stream is m4a then keep m4a container

webm isnt supported on a whole lot of audio players, but both opus and vorbis are

**Comment by Skibicki** [comment]
Yes, please. This should be added to "correcting container" phase of postprocessing. Youtube has Opus now.

**Comment by ubone** [comment]
you're supposed to use -x flag for that

**Comment by ubone** [comment]
-xf bestaudio

**Comment by yan12125** [comment]
Thanks @ubone. The feature is indeed already there for a long time. There was something wrong in my head :D

**Comment by popek069** [comment]
-xf doesn't work for me, with bestaudio downloads aac, with 251 downloads opus but still in webm container. Here is my command:
youtube-dl https://www.youtube.com/user/NoCopyrightSounds -xf 251 -i -o "%(title)s.opus"

**Comment by yan12125** [comment]
The correct command is:
```
youtube-dl H81DzDMdCLI -xf 251 --audio-format opus -o "%(title)s.%(ext)s"
```
Feel free to ask on IRC if you've got other questions.
