### ISSUE TITLE
Feature request: Retry request after socket-timeout

### ISSUE THREAD

**Issue by spookyahell** [rg3/youtube-dl#9483]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### Description of your _issue_, suggested solution and other information

Issue is: I use a local proxy for requests that sometimes freezes and won't respond. Usually I have to execute a whole command again, even if it's already almost done. The option "--socket-timeout" only automatically quits the command, it doesn't retry the current request.

An option like "--socket-timeout-retry SECONDS" would be nice to have. It would need to do what socket-timout does and then continue where it left of.

**Comment by dstftw** [comment]
Isn't `--retries` enough? There is no such thing as "command almost done". In general extraction process is extractor specific and particular extractor may want to have own retry strategy or do not have such.

**Comment by spookyahell** [comment]
When does a retry trigger? Does ít trigger when nothing happens for a certain amount of time?  I kind of have the feeling that the extractor won't retry what it needs to finish. I meant sometimes it's only few requests to end but a lot if you restart the whole extraction process. Almost done: Nearly ready to create and execute ffmpeg command.

**Comment by ssokolow** [comment]
Is it possible that this is another manifestation of the "socket timeouts don't trigger retry" bug described in issue #8625?
