### ISSUE TITLE
[youtube] Can't fetch video id's from some playlists

### ISSUE THREAD

**Issue by davue** [rg3/youtube-dl#9485]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

##### Working:
`$ youtube-dl --yes-playlist --get-id https://www.youtube.com/watch?v=eVTXPUF4Oz4&list=RDeVTXPUF4Oz4`

##### Not Working:
```
$ youtube-dl --yes-playlist --get-id 'https://www.youtube.com/watch?v=pdoIs1jZbCY&list=RDEMWmnt7jMTTO8Kol5fcLtm-g' --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--yes-playlist', u'--get-id', u'https://www.youtube.com/watch?v=pdoIs1jZbCY&list=RDEMWmnt7jMTTO8Kol5fcLtm-g', u'--verbose']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.05.10
[debug] Python version 2.7.9 - Linux-2.6.32-43-pve-x86_64-with-debian-8.4
[debug] exe versions: ffmpeg N-79898-gaeefe01, ffprobe N-79898-gaeefe01
[debug] Proxy map: {}
ERROR: Kol5fcLtm-g: YouTube said: This video does not exist.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1311, in _real_extract
    expected=True, video_id=video_id)
ExtractorError: Kol5fcLtm-g: YouTube said: This video does not exist.
```
---

### Description of your *issue* and other information

If you try to fetch video id's from a YouTube playlist via `youtube-dl --get-id <playlist>` it works for some playlist and for some it doesn't.

**Note**: that the last 11 signs of working playlists ID's matches to a video inside the playlist, while it doesn't on non working playlists even though the latter playlist works on YouTube.

**Comment by dstftw** [comment]
As seen from the log video `Kol5fcLtm-g` does not exist thus technically `Kol5fcLtm-g` is not a valid videos id. Use `-i` to skip such errors.

**Comment by davue** [comment]
Oh, shame on me. I thought there was a problem with the playlist ID itself not just that he stopped because he couldn't get one video.
