### ISSUE TITLE
Automatic captions/subtitles still not being found

### ISSUE THREAD

**Issue by su** [rg3/youtube-dl#9489]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

**Debug log is *below* due to length.**

I've seen issue #8667 and its closure, but what was done there doesn't seem to be working. (Or not anymore. I was behind a few releases, though up to date now.) Was the patch in the previous issue tested? Against what URL? It would help for duplication purposes.

Using the same YouTube clip as the original issue, and others of my own finding, youtube-dl:

1. Says there are no (manual) subtitles, which is true.
2. Looks for automatic captions, then rattles off an impossible list of available(?) language formats.
3. Finally says again that there are no subtitles (Referring to automatic only? Hard to say, as they're referred to as "captions" before that.)

---
```
$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'--list-subs', u'--skip-download', u'https://www.youtube.com/watch?v=20LmZk1hakA']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.05.10
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-77883-gd7c75a5, ffprobe N-77883-gd7c75a5
[debug] Proxy map: {}
[youtube] 20LmZk1hakA: Downloading webpage
[youtube] 20LmZk1hakA: Downloading video info webpage
[youtube] 20LmZk1hakA: Extracting video information
WARNING: video doesn't have subtitles
[youtube] 20LmZk1hakA: Looking for automatic captions
[youtube] 20LmZk1hakA: Downloading MPD manifest
Available automatic captions for 20LmZk1hakA:
Language formats
gu       vtt, ttml
zh-Hans  vtt, ttml
zh-Hant  vtt, ttml
gd       vtt, ttml
ga       vtt, ttml
gl       vtt, ttml
lb       vtt, ttml
la       vtt, ttml
lo       vtt, ttml
tr       vtt, ttml
lv       vtt, ttml
lt       vtt, ttml
th       vtt, ttml
tg       vtt, ttml
te       vtt, ttml
fil      vtt, ttml
haw      vtt, ttml
yi       vtt, ttml
ceb      vtt, ttml
yo       vtt, ttml
de       vtt, ttml
da       vtt, ttml
el       vtt, ttml
eo       vtt, ttml
en       vtt, ttml
eu       vtt, ttml
et       vtt, ttml
es       vtt, ttml
ru       vtt, ttml
ro       vtt, ttml
bn       vtt, ttml
be       vtt, ttml
bg       vtt, ttml
uk       vtt, ttml
jv       vtt, ttml
bs       vtt, ttml
ja       vtt, ttml
xh       vtt, ttml
co       vtt, ttml
ca       vtt, ttml
cy       vtt, ttml
cs       vtt, ttml
ps       vtt, ttml
pt       vtt, ttml
pa       vtt, ttml
vi       vtt, ttml
pl       vtt, ttml
hy       vtt, ttml
hr       vtt, ttml
ht       vtt, ttml
hu       vtt, ttml
hmn      vtt, ttml
hi       vtt, ttml
ha       vtt, ttml
mg       vtt, ttml
uz       vtt, ttml
ml       vtt, ttml
mn       vtt, ttml
mi       vtt, ttml
mk       vtt, ttml
ur       vtt, ttml
mt       vtt, ttml
ms       vtt, ttml
mr       vtt, ttml
ta       vtt, ttml
my       vtt, ttml
af       vtt, ttml
sw       vtt, ttml
is       vtt, ttml
am       vtt, ttml
it       vtt, ttml
iw       vtt, ttml
sv       vtt, ttml
ar       vtt, ttml
su       vtt, ttml
zu       vtt, ttml
az       vtt, ttml
id       vtt, ttml
ig       vtt, ttml
nl       vtt, ttml
no       vtt, ttml
ne       vtt, ttml
ny       vtt, ttml
fr       vtt, ttml
ku       vtt, ttml
fy       vtt, ttml
fa       vtt, ttml
fi       vtt, ttml
ka       vtt, ttml
kk       vtt, ttml
sr       vtt, ttml
sq       vtt, ttml
ko       vtt, ttml
kn       vtt, ttml
km       vtt, ttml
st       vtt, ttml
sk       vtt, ttml
si       vtt, ttml
so       vtt, ttml
sn       vtt, ttml
sm       vtt, ttml
sl       vtt, ttml
ky       vtt, ttml
sd       vtt, ttml
20LmZk1hakA has no subtitles
```

**Comment by dstftw** [comment]
1. There is not subtitles only automatic ones for this video.
2. It's not impossible you can download any of the listed automatic captions without any problem.
3. Referring to regular subtitles only not automatic. For automatic it's already displayed a list of available ones and said that they are available as clearly seen from the log.

**Comment by su** [comment]
Weird. The next set of videos I tried later, it did grab the auto-captions. I think I restarted my shell in between, but given the new version was reported before that didn't seem necessary.
Anyway, sorry for the bad bug.
