### ISSUE TITLE
Site support request - Pornovore.fr

### ISSUE THREAD

**Issue by JohnMkaine** [rg3/youtube-dl#9490]
Pornovore link not supported :

youtube-dl -t http://www.pornovore.fr/Sexe-brutal/Video-5848-Heather-Night-a-le-feu-au-cul
[generic] Video-5848-Heather-Night-a-le-feu-au-cul: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Video-5848-Heather-Night-a-le-feu-au-cul: Downloading webpage
[generic] Video-5848-Heather-Night-a-le-feu-au-cul: Extracting information
ERROR: Unsupported URL: http://www.pornovore.fr/Sexe-brutal/Video-5848-Heather-Night-a-le-feu-au-cul

Thank you for considering my request.

**Comment by yan12125** [comment]
This looks like a copyrighted video - there's a "TEEN FIDELITY" watermark at the right bottom corner. Has PornoVore bought legal redistribution permissions from teenfidelity.com?

**Comment by hlaaftana** [comment]
lmfao what

**Comment by yan12125** [comment]
Closing as no response for a long time.
