### ISSUE TITLE
Anyway to 'Avoid' a format (make last choice?)

### ISSUE THREAD

**Issue by artphotodude** [rg3/youtube-dl#9494]
Hello am using **_-f 'best[width<=1280]/[height<=?1080]/best'_** and it works well most of the time, but my player is not hot for WebM (more and more common). Is there a way to mod the above to prefer like every other format before WebM??

Thanks!!

**Comment by dstftw** [comment]
Read [FAQ](https://github.com/rg3/youtube-dl#format-selection-examples).

**Comment by artphotodude** [comment]
My question is NOT covered in the FAQ.

**Comment by dstftw** [comment]
It does. You just don't bother reading as well as searching the bug tracker. Needless to say you didn't even filled the [new issue template](https://github.com/rg3/youtube-dl/issues/new).

>Also filtering work for comparisons `=` (equals), `!=` (not equals), `^=` (begins with), `$=` (ends with), `*=` (contains) and following string meta fields:
 - `ext`: File extension

...

>`!=` (not equals)

>`ext`: File extension

**Comment by artphotodude** [comment]
Forgive me, but NOBODY would ever see the connection you just mentioned (or that it could work in this case), without better clarification.  Thanks for the bloody-nose, as always.

**Comment by dstftw** [comment]
There is even an example for [this](https://github.com/rg3/youtube-dl#format-selection-examples) but sure who will bother reading.
