### ISSUE TITLE
MPD-File from Youtube

### ISSUE THREAD

**Issue by h0d3nt3uf3l** [rg3/youtube-dl#9496]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Question

---

Hi folks,
sorry for bothering you but I don't get to all that code without killing a lot of time.
I need a the code snippet for downloading the MPD-File from youtube. Only a sample request, something in that way. I googled a few days and everytime I come to your code and no one can give me an answer to this question "How to download the MPD file from youtube". In your code the answer is hidden, but I don't find it. Maybe one of you know where to search and can help me a little.

Thanks :)

**Comment by dstftw** [comment]
Key points:
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1215
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1276-L1285
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1228

**Comment by h0d3nt3uf3l** [comment]
Thanks, but this only give me the URL. I need a way to get the MPD-file from that URL.

**Comment by dstftw** [comment]
Follow relevant variable names to browse to this part of code.
