### ISSUE TITLE
"--playlist-reverse" does nothing, setting not propagated in 'options.py'

### ISSUE THREAD

**Issue by glenn-slayden** [rg3/youtube-dl#9497]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.10*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
E:\_temp>python D:\programming-others\youtube-dl-master\youtube_dl\__main__.py -v --ignore-config --playlist-reverse https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '--ignore-config', '--playlist-reverse', 'https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc']
[debug] Encodings: locale cp1252, fs mbcs, out utf-8, pref cp1252
[debug] youtube-dl version 2016.05.10
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube:playlist] PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc: Downloading webpage
[download] Downloading playlist: youtube-dl public playlist
[youtube:playlist] playlist youtube-dl public playlist: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading video info webpage
[youtube] BaW_jenozKc: Extracting video information
[youtube] BaW_jenozKc: Downloading MPD manifest
[debug] Invoking downloader on 'https://r9---sn-nx57yney.googlevideo.com/videoplayback?ratebypass=yes&ip=71.197.234.74&upn=Jym9E66Wxs4&itag=22&ms=au&fexp=9416126%2C9416891%2C9422596%2C9428398%2C9431012%2C9431118%2C9432683%2C9432826%2C9433096%2C9433223%2C9433946%2C9434343%2C9434767%2C9435223%2C9435253%2C9435484%2C9436446&mt=1463262197&mv=m&source=youtube&id=o-AK7w5ZXTsrEdUtMEaE05nBzBcwlHtAgbz5yTVepOyzhu&dur=9.891&requiressl=yes&mm=31&pl=17&mn=sn-nx57yney&ipbits=0&expire=1463284012&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&initcwndbps=2370000&lmt=1387961818043059&sver=3&nh=IgpwcjAyLnNlYTAzKgkxMjcuMC4wLjE&mime=video%2Fmp4&key=yt6&signature=45B80C0DBA966E0B0E3C0BCE742849404F052C73.5A8F47452764317178094A2C01293D38A1ED8018'
[download] Destination: youtube-dl test video ''_ä↭𝕐-BaW_jenozKc.mp4
[download] 100% of 1.53MiB in 00:00
[download] Finished downloading playlist: youtube-dl public playlist
E:\_temp>
```

---

---

### Description of your *issue*, suggested solution and other information

"--playlist-reverse" does not seem to work. 

This might be due to the following (options.py, line 427) where there is no 'dest' specified.

    downloader.add_option(
        '--playlist-reverse',
        action='store_true',
        help='Download playlist videos in reverse order')

**Comment by dstftw** [comment]
By default `dest` is derived from option string i.e. `--playlist-reverse` and it works perfectly.
