### ISSUE TITLE
Site support request - waaw.tv|hqq.tv(embed)

### ISSUE THREAD

**Issue by IDerr** [rg3/youtube-dl#9498]
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.05.10_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**
### Before submitting an _issue_ make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ youtube-dl -v http://waaw.tv/watch_video.php?v=MZprhXQUCmsM
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://waaw.tv/watch_video.php?v=MZprhXQUCmsM']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.10
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.3
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[generic] watch_video: Requesting header
WARNING: Could not send HEAD request to http://waaw.tv/watch_video.php?v=MZprhXQUCmsM: HTTP Error 503: Service Temporarily Unavailable
[generic] watch_video: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 388, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1946, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

---
### If the purpose of this _issue_ is a _site support request_ please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://waaw.tv/watch_video.php?v=MZprhXQUCmsM
- Embed video: http://hqq.tv/player/embed_player.php?vid=MZprhXQUCmsM&autoplay=no&embed_from=embed_from

---
### Description of your _issue_, suggested solution and other information

When the player is launched, it calls a php file : 
http://hqq.tv/player/get_md5.php?server=...%3D%3D&link=...&at=..&adb=..%2F&b=..&vid=...

The response is a json file : 

{"hash":"12e3d644b15f6ba902351ae83d20e103","file":"Vpw97lXY6GWNk2vTkSWGVGkhvGhD6fkYUS0T85kH7CZR69wHa5Ipvzapaf0zSb85v98RalDbg57Yz1H1xbnqSzFiVNauzNi94EWbVT9YizgGiTiRijQRiC0XUpiBxf0N6oiu6G8yxM0h72NY8fDy8oiYxfDN850T6TJRizvYilbYizgYizgGiTJsiz7eilbdOzE9PukYvGBDx=AA","html5_file":"#06807407407003a02f02f06e06403406603303502e07606b06306106306806502e06306f06d02f07306506306907002f03002f04406905506204706103504705606f05304904605606304607005403905404106702f04e07a06707504d06a04903104c06a04507704e04303407804e05406b03d02f03103403603303303003203803003002f06806c07302d07606f06402d07303702f06606c07602f06107006902f06606906c06507302f07606906406506f07302f03203003103602f03003502f03103402f03103403603303203203103703803003503103903103402e06d07003402e06d033075038"}

html5_file is what we need we have to do some manipulations : 
068 074 074 070... => %u0068%u0074%u0074%u0070...  => http...
unescaped with unescape() (js function can be done with http://www.tareeinternet.com/scripts/unescape.html ) 
And you have your m3u8 link.

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by Belderak** [comment]
Link modified

**Comment by Belderak** [comment]
I think we can add site-request tag ?

**Comment by jose1711** [comment]
this could help to sort out the issue: https://github.com/jose1711/script.module.stream.resolver/blob/50cc7515c947d0780726f35bfde9fe1a5f0142ab/lib/server/hqqresolver.py

**Comment by scfc** [comment]
Just for clarification: This request was never implemented, was it?

**Comment by IDerr** [comment]
Nope, never.
