### ISSUE TITLE
Allow removing fragments for incomplete HLS downloads (was: hls fragment downloader does not clean up after itself)

### ISSUE THREAD

**Issue by RealDolos** [rg3/youtube-dl#9512]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.10**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [X] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Not sure if it counts as a bug or a feature request, to me it is a small annoyance tho.

youtube-dl may download tons of fragments via the hls dowloader to individual files.
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/downloader/hls.py#L74-L88

If there is an unrecoverable error, e.g. when a stream is removed, then these files will never get removed; they are only ever removed once all fragments have been retrieved successfully, which will never happen once the stream is gone, no matter how hard one tries to resume.

To fix this properly, there needs to be a distinction between unrecoverable errors (e.g. stream is gone) and recoverable errors (e.g. user aborted, but may resume later).
And maybe even an option to remove fragment files always.

Since I personally use youtube-dl in an automated fashion, my local fix does not have to deal potentially resuming later, so I just moved the `os.remove`-loop into a `finally`.

**Comment by yan12125** [comment]
These files are kept in failure for restarting the download. I guess it's OK to always delete these files if ```--no-continue``` is specified.

**Comment by dstftw** [comment]
This is not actual now since fragments are not stored on disk anymore.
