### ISSUE TITLE
Playing the same raw url on different domains

### ISSUE THREAD

**Issue by electronee** [rg3/youtube-dl#9514]
Hi,

I have an issue regarding the youtube-dl -g [url] command. As the extracted information is only valid for the ip adresses that are in the same domain, I would like to know if there is anyway to use the same url in different ip domains? ,

I tried the cookies option and forwarded the cookie file to different ip domains but no luck.. Currently it seems that only ip is the barrier to share the url on different ips/machines.

**Comment by yan12125** [comment]
See https://github.com/rg3/youtube-dl/issues/9001#issuecomment-201991818.

**Comment by electronee** [comment]
Hi Yan12125, the problem is with the ip section at the URL.

Fx I have the following raw URL extracted by youtube-dl where the IP address is bold and underlined : 

https://redirector.googlevideo.com/videoplayback?ip=216.145.0.234

and I want to play this video at the 168.172.2.2

I dont think this is the issue for the redirector, at least as I try the redirector at the another IP it does not work..

**Comment by yan12125** [comment]
The redirector approach is just a workaround and some people _found it works_. Essentially there's no guarantee that the URL resolved from one IP is valid for another IP. If you want a valid URL for 168.172.2.2, run youtube-dl on 168.172.2.2, too.

Other options can be proxies, while they're far out of the scope of youtube-dl.

**Comment by nadermx** [comment]
Using the redirector and same ip is it still necessary to also have the cookie.  Or would it using the redirector and same IP be enough?
