### ISSUE TITLE
WDR Mediathek error when trying to download video

### ISSUE THREAD

**Issue by n2o** [rg3/youtube-dl#9517]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.16**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Bug report (encountered problems with youtube-dl)

---

### Description

Since the rework of the WDR website it is no longer possible to download from their "mediathek", for example this video: http://www1.wdr.de/mediathek/video/sendungen/lokalzeit-bergisches-land/video-lokalzeit-bergisches-land-vom--218.html 

I also tried to use the fix from this pull request #8843, but that does not solve the problem.

Here are some debug information:

```bash
n2o@host ~/youtube-dl % python youtube_dl/__main__.py --verbose http://www1.wdr.de/mediathek/video/sendungen/servicezeit/videoservicezeit560-videoplayer_size-L.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www1.wdr.de/mediathek/video/sendungen/servicezeit/videoservicezeit560-videoplayer_size-L.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.16
[debug] Git HEAD: 055f0d3
[debug] Python version 3.5.1 - Linux-4.5.3-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[WDR] mediathek/video/sendungen/servicezeit/videoservicezeit560: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/n2o/youtube-dl/youtube_dl/extractor/common.py", line 388, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/n2o/youtube-dl/youtube_dl/YoutubeDL.py", line 1946, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

In my opinion youtube-dl dies at this line: https://github.com/rg3/youtube-dl/blob/5886b38d73c54239c85c3e0d8e7c1585d1bbb7da/youtube_dl/extractor/wdr.py#L106

**Comment by yan12125** [comment]
Sorry for the late response. In Firefox the given URL indeed gives a 404 error. Can you still watch this video? Or do you have another example?

**Comment by n2o** [comment]
The video I wanted to download is no longer available.

Another video from this mediathek is: http://www1.wdr.de/mediathek/video/sendungen/lokalzeit-bergisches-land/video-lokalzeit-bergisches-land-vom--236.html

But the verbose output with the current version of youtube-dl gives another output:

```bash
n2o@host /path/to/youtube-dl (git)-[master] % python youtube_dl/__main__.py --verbose http://www1.wdr.de/mediathek/video/sendungen/lokalzeit-bergisches-land/video-lokalzeit-bergisches-land-vom--236.html                           :(
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www1.wdr.de/mediathek/video/sendungen/lokalzeit-bergisches-land/video-lokalzeit-bergisches-land-vom--236.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.21.2
[debug] Git HEAD: 6f748df
[debug] Python version 3.5.1 - Linux-4.5.4-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[WDR] mediathek/video/sendungen/lokalzeit-bergisches-land/video-lokalzeit-bergisches-land-vom--236: Downloading webpage
[download] Downloading playlist: mediathek/video/sendungen/lokalzeit-bergisches-land/video-lokalzeit-bergisches-land-vom--236
[WDR] playlist mediathek/video/sendungen/lokalzeit-bergisches-land/video-lokalzeit-bergisches-land-vom--236: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: mediathek/video/sendungen/lokalzeit-bergisches-land/video-lokalzeit-bergisches-land-vom--236
```

The behavior changed, but it is still not possible to download videos. Thanks for your help

**Comment by yan12125** [comment]
Partially fixed by #8843.

**Comment by Boris-de** [comment]
@n2o the pull request got merged, could you try again with the current master? Your links seems to be "depubliziert" again. Currently the link is redirecting improperly according to Firefox ("Location" is empty), this takes youtube-dl to the mainpage and it downloads the suggestions as a playlist. I'm not sure about that.

But I've tested with a current issue of Lokalzeit Bergisches Land and it works for me. If you find a link that still has problems with the current master, please let me know.

**Comment by yan12125** [comment]
This video was working fine 14 days ago with #8843. I guess similar videos can be downloaded correctly in the next version. Many thanks @Boris-de!

**Comment by n2o** [comment]
Yes, it is working with the current version from this repository. Thanks for your help! :+1:
