### ISSUE TITLE
option --use-tor

### ISSUE THREAD

**Issue by ilf** [rg3/youtube-dl#9520]
Thanks for implementing SOCKS proxy support #402!
How about adding an option `--use-tor` as shortcut for `--proxy "socks4a://127.0.0.1:9050/"`?
dirmngr(8) of GnuPG also has this.

**Comment by dstftw** [comment]
This shortcut does not make much sense since socks port is configurable and may be arbitrary.

**Comment by ilf** [comment]
@vitorgalvao: Why do you think it's not okay, to watch/download YouTube via Tor? All the Tor developers I know don't only think that's perfectly okay, they even do it themselves and encourage others to do the same. The times of Tor being slow and "maxed out" are long gone. See https://metrics.torproject.org/bandwidth.html

@dstftw: It does make sense, since it is indeed an encouragement to use Tor, if you have not changed the defaults. If you changed our SOCKS-port in the Tor-config, you can still set the proxy-details manually with youtube-dl. But adding an easy flag might make more people use it. That's why (and how) other software like GnuPG and mpop/msmtp are doing it.
