### ISSUE TITLE
Site Support Request: CBS Local

### ISSUE THREAD

**Issue by insarov** [rg3/youtube-dl#9522]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.16**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v "http://losangeles.cbslocal.com/2016/05/16/safety-advocates-say-fata
l-car-seat-failures-are-public-health-crisis"

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://losangeles.cbslocal.com/2016/05/16/safety-a
dvocates-say-fatal-car-seat-failures-are-public-health-crisis/', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.05.16
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-73010-gbb3703a, ffprobe N-73010-gbb3703a, rtmpdum
p 2.4
[debug] Proxy map: {}
[generic] safety-advocates-say-fatal-car-seat-failures-are-public-health-crisis:
 Requesting header
WARNING: Falling back on generic information extractor.
[generic] safety-advocates-say-fatal-car-seat-failures-are-public-health-crisis:
 Downloading webpage
[generic] safety-advocates-say-fatal-car-seat-failures-are-public-health-crisis:
 Extracting information
ERROR: Unsupported URL: http://losangeles.cbslocal.com/2016/05/16/safety-advocat
es-say-fatal-car-seat-failures-are-public-health-crisis/
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1394, in _real_extract
  File "youtube_dl\compat.pyo", line 280, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 269, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: undefined entity: line 6, column 92
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 676, in extract_info
  File "youtube_dl\extractor\common.pyo", line 341, in extract
  File "youtube_dl\extractor\generic.pyo", line 2081, in _real_extract
UnsupportedError: Unsupported URL: http://losangeles.cbslocal.com/2016/05/16/saf
ety-advocates-say-fatal-car-seat-failures-are-public-health-crisis/
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://cbsloc.al/22e7Rst
- Single video: http://losangeles.cbslocal.com/2016/05/16/safety-advocates-say-fatal-car-seat-failures-are-public-health-crisis/
- Single video (different city): http://cleveland.cbslocal.com/2016/05/16/indians-score-season-high-15-runs-in-blowout-win-over-reds-rapid-reaction/

---

### Description of your *issue*, suggested solution and other information

I've noticed that other CBS sites are supported, but all CBS Local sites that I've tried have failed.  Thank you for your consideration.

**Comment by yan12125** [comment]
Thanks for the report. CBS local sites will be supported in the next version.
