### ISSUE TITLE
Maintainer ignorance

### ISSUE THREAD

**Issue by hadmut** [rg3/youtube-dl#9535]
A maintainer called Sergey M. just closed my issue report  #9534 without understanding it. 

What's the point in having an issues web pages if the maintainers close the issues without understanding them?

This was not about downloading audio files. 

This was about downloading video files that are compatible with most devices and not some exotic lab codec. So I just wanted to have a video with AVC video codec, AAC audio codec, and both packed into mp4. 

a) How would one achieve that?

b) How would one get contact to a maintainer willing to listen to the problem?

**Comment by dstftw** [comment]
Read my posts closely.
