### ISSUE TITLE
md5 as own value or as description

### ISSUE THREAD

**Issue by TRox1972** [rg3/youtube-dl#9540]
On some of the extractors I've seen that in _TESTS, the md5 is sometimes written as `'md5': 'e43f2842df668f92870ea39d3304f1ee` while it is sometimes written as `'description': 'md5:e43f2842df668f92870ea39d3304f1ee'`. Which is better to use?

**Comment by yan12125** [comment]
```'md5': 'e43f2842df668f92870ea39d3304f1ee'``` is the MD5 of the downloaded video file (in tests only the first 10KiB of a file is downloaded) and ```'description': 'md5:e43f2842df668f92870ea39d3304f1ee'``` indicates the MD5 checksum of the ```description``` field is e43f2842df668f92870ea39d3304f1ee. They are used for different purposes.
