### ISSUE TITLE
Unable to download webpage: '' (caused by BadStatusLine("''",)) and HTTP Error 429: 

### ISSUE THREAD

**Issue by badrsh** [rg3/youtube-dl#9543]
Hi , i'm trying to download from youtube but i got an error 

> Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 
i tried to fix the problem by using the proxy but i got this : 

` http_proxy="117.136.234.8:82" youtube-dl http://www.youtube.com/watch?v=z4KV7e8kwbI --verbose`

> Unable to download webpage: '' (caused by BadStatusLine("''",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
>   File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 388, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1946, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 404, in open
>     response = self._open(req, data)
>   File "/usr/lib/python2.7/urllib2.py", line 422, in _open
>     '_open', req)
>   File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
>     result = func(*args)
>   File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 934, in https_open
>     req, **kwargs)
>   File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open
>     h.request(req.get_method(), req.get_selector(), req.data, headers)
>   File "/usr/lib/python2.7/httplib.py", line 979, in request
>     self._send_request(method, url, body, headers)
>   File "/usr/lib/python2.7/httplib.py", line 1013, in _send_request
>     self.endheaders(body)
>   File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
>     self._send_output(message_body)
>   File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
>     self.send(msg)
>   File "/usr/lib/python2.7/httplib.py", line 797, in send
>     self.connect()
>   File "/usr/lib/python2.7/httplib.py", line 1181, in connect
>     self._tunnel()
>   File "/usr/lib/python2.7/httplib.py", line 758, in _tunnel
>     (version, code, message) = response._read_status()
>   File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
>     raise BadStatusLine(line)
>

**Comment by dstftw** [comment]
Use proper proxy.

**Comment by badrsh** [comment]
what is that ? ? Im already had a proxy

**Comment by yan12125** [comment]
This proxy does not allow connections to www.youtube.com:
```
$ curl -v -x 117.136.234.8:82 "http://httpbin.org/ip"
*   Trying 117.136.234.8...
* Connected to 117.136.234.8 (117.136.234.8) port 82 (#0)
> GET http://httpbin.org/ip HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.48.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Fri, 20 May 2016 10:08:06 GMT
< Content-Type: application/json
< Content-Length: 32
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< 
{
  "origin": "117.136.234.8"
}
* Connection #0 to host 117.136.234.8 left intact

$ curl -v -x 117.136.234.8:82 "http://www.youtube.com/"
*   Trying 117.136.234.8...
* Connected to 117.136.234.8 (117.136.234.8) port 82 (#0)
> GET http://www.youtube.com/ HTTP/1.1
> Host: www.youtube.com
> User-Agent: curl/7.48.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```
So please choose another proxy.
