### ISSUE TITLE
Please help me to install youtube-dl to my server

### ISSUE THREAD

**Issue by CShehan** [rg3/youtube-dl#9547]
I'm new to python if anyone know to youtube-dl write php ? please help me

**Comment by Hrxn** [comment]
https://github.com/rg3/youtube-dl/blob/master/CONTRIBUTING.md

Also, this is an issue tracker. Not some kind of support forum.

**Comment by yan12125** [comment]
Thanks @Hrxn. This should help, too: https://github.com/rg3/youtube-dl/blob/master/README.md#installation
