### ISSUE TITLE
youtube-dl not works with python 3.5

### ISSUE THREAD

**Issue by MrDini123** [rg3/youtube-dl#9552]
Hi!

I'm using this nice tool since a half year ago for downloading ncs sounds. But a few days ago, I updated my python from the old 2.7 to the latest 3.5.1 version. After it I reinstalled the youtube-dl using pip tool. It worked, but the following error flood comes when I try to download sg:

https://asciinema.org/a/0azqkowjdflhaupj6tr48oh9f

What's wrong? Thanks!

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
