### ISSUE TITLE
Add support for gloria.tv

### ISSUE THREAD

**Issue by sebma** [rg3/youtube-dl#9553]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.05.16
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

---

Hi,

Can you add support for gloria.tv ?

In this example, `youtube-dl` only sees one available format instead of three available formats (check in the browser) :
```
$ youtube-dl -v -F https://gloria.tv/video/3Pbj23tumtY
[debug] System config: []
[debug] User config: [u'--no-warnings', u'--ignore-errors', u'--continue', u'-o', u'%(title)s__%(format_id)s__%(id)s.%(ext)s', u'-f', u'mp4/flv', u'--add-metadata', u'--embed-subs', u'--restrict-filenames', u'--embed-thumbnail', u'--all-sub', u'--prefer-ffmpeg']
[debug] Command-line args: [u'-v', u'-F', u'https://gloria.tv/video/3Pbj23tumtY']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.16
[debug] Python version 2.7.6 - Linux-3.19.0-59-generic-i686-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 9.18-6, avprobe 9.18-6, ffmpeg 3.0.2-1, ffprobe 3.0.2-1, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 3Pbj23tumtY: Requesting header
[generic] 3Pbj23tumtY: Downloading webpage
[generic] 3Pbj23tumtY: Extracting information
[info] Available formats for cg7id7ydbh0y4a5ghr0dl31u86wy5bpw2ye:
format code  extension  resolution note
0            mp4        unknown    

```

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by sebma** [comment]
Try this one : https://www.gloria.tv/video/byq2rWexM9H

**Comment by sebma** [comment]
It's a 3 minutes testimony which I don't think is copyrighted.

**Comment by dstftw** [comment]
There is a channel label. Provide example URL of user generated content.

**Comment by sebma** [comment]
OK, trying to find another, but I have question whose answer might help me : 
How can I tell if an url has a channel label ?

**Comment by dstftw** [comment]
It's in video not in URL.

**Comment by sebma** [comment]
How do I check this myself before submitting a new url to you ?

**Comment by sebma** [comment]
The `mediainfo` command does not show my any channel label.
Maybe I'm not looking in the right direction :)

**Comment by dstftw** [comment]
Huh? Watch the video with eyes and figure out the whether watermark in some of the corners of the vieo frame is affiliated with hoster website or not.

**Comment by sebma** [comment]
Sorry my english is not so good.
Are you're talking about a channel label inside the video frames ?
I don't understand what the inner content of the video has to do with fetching the url ?

**Comment by sebma** [comment]
Maybe you can try this one : https://www.gloria.tv/video/1TzkSUTdBAj

**Comment by dstftw** [comment]
Re-read my first post.

**Comment by sebma** [comment]
Oh, are you talking about copyright ?

**Comment by dstftw** [comment]
It's also copyrighted that is clearly indicated at the beginning of the video.
Closing upon non-copyrighted video is posted.

**Comment by sebma** [comment]
Try this one : https://www.gloria.tv/video/o3ZdDDjJn6v
