### ISSUE TITLE
Protocol not found with twitter videos

### ISSUE THREAD

**Issue by montanaflynn** [rg3/youtube-dl#9555]
```
youtube-dl "https://twitter.com/sergiogarcia_4/status/731246121150898176"
[twitter] 731246121150898176: Downloading webpage
[twitter:card] 731246121150898176: Downloading webpage
[download] Destination: Sr. G.O - So I went hiking today and I thought that this bear died for a second 🐻💀-731246121150898176.m3u8
avconv version 11.4, Copyright (c) 2000-2014 the Libav developers
  built on Oct 16 2015 09:05:58 with Apple LLVM version 7.0.0 (clang-700.0.72)
https://video.twimg.com/ext_tw_video/731246085738389504/pu/pl/5IRM5D5ymwAj7yBt.m3u8: Protocol not found
ERROR: ffmpeg exited with code 1
```

**Comment by dstftw** [comment]
Your ffmpeg is built without https support.

**Comment by montanaflynn** [comment]
Are you sure, my `ffmpeg` can take https input sources without a problem.

`ffmpeg -i "https://j.gifs.com/n5PQOE.mp4" out.gif`

**Comment by dstftw** [comment]
avconv not ffmpeg.

**Comment by montanaflynn** [comment]
I don't use avconv, even the error reported by youtube-dl is `ERROR: ffmpeg exited with code 1`

Furthermore the following command returns a valid `mp4`:

```
ffmpeg -i "https://video.twimg.com/ext_tw_video/731246085738389504/pu/pl/5IRM5D5ymwAj7yBt.m3u8" out.mp4
```

**Comment by dstftw** [comment]
See log.
>avconv version 11.4, Copyright (c) 2000-2014 the Libav developers
  built on Oct 16 2015 09:05:58 with Apple LLVM version 7.0.0 (clang-700.0.72)

**Comment by dstftw** [comment]
Then uninstall it if you don't use.

**Comment by montanaflynn** [comment]
After removing it the bug went away, is there a way to explicitly tell `youtube-dl` to use `ffmpeg`?

**Comment by dstftw** [comment]
Yes, `--prefer-ffmpeg`. You can also explicitly specify full path to ffmpeg/avconv (e.g. if not in `$PATH`) with `--ffmpeg-location`.

**Comment by djmix777** [comment]
Hi , please help, how may download this link?
https://t.co/CO2W6ZcmCE   **or**    https://pic.twitter.com/CO2W6ZcmCE
