### ISSUE TITLE
RFE: random sleep between downloads

### ISSUE THREAD

**Issue by zenonp** [rg3/youtube-dl#9561]
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.16**
- [x ] Feature request (request for a new functionality)

When bulk downloading, I often place a delay between individual downloads, partly to be polite and partly to avoid triggering bot detection mechanisms. Something like "for i in `cat urllist`; do youtube-dl $i; sleep 30; done". This would be nice to have as a built-in option, so that it (a) works with remote playlists, (b) can be used by windoze users and (c) can randomise the delay. A new option "--random-delay min max" coupled to random.randrange(min, max, 1) would easily do the trick. It doesn't even need to verify that it is being applied to a playlist, because adding a useless delay after a single video download works anyway.

**Comment by dstftw** [comment]
There is already an option for sleep between downloads `--sleep-interval` though without randomization.
