### ISSUE TITLE
Cannot Update on Windows?

### ISSUE THREAD

**Issue by danfiscus** [rg3/youtube-dl#9568]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.21.2*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ ] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**

**NO, I have not updated because I am unable to.**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
C:\Users\Dan Fiscus>youtube-dl -U -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-U', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.05.16
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
Updating to version 2016.05.21.2 ...
ERROR: no write permissions on youtube-dl
```

---

### Description of your *issue*, suggested solution and other information

I am not used to Windows, so perhaps I have set this up wrong somehow, but no matter what I try or what tutorial I follow, I cannot get youtube-dl to update because it does not have write permissions. I followed the installation guide on the documentation (simply put it in any folder in the path) but as I put in a previous bug report, it did not work in the folder I tried (`system32`) so I simply created a new folder `C:\youtube-dl` and put the .exe file in there.

**Comment by dstftw** [comment]
Obviously you don't have right to write in disk root. Place it anywhere else where you have right to write to.

**Comment by danfiscus** [comment]
@dstftw Okay, I've asked this before but I guess I did it wrong last time too, **where should the .exe file be**? I think at this point the instructions on the documentation are clearly not very helpful.

**Comment by dstftw** [comment]
It should be in any directory in path where you have write access to. Also when updating with `-U` you have to be in the same directory where it's located.

**Comment by danfiscus** [comment]
@dstftw I have write access to the folder it's in which is in the path, but I wasn't in the same directory. That information should all be in the documentation for users like myself.
