### ISSUE TITLE
Cannot pass --output option

### ISSUE THREAD

**Issue by tohmah** [rg3/youtube-dl#9577]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.21.2*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
youtube-dl -ciwv —-output '%(title)s-%(uploader)s.%(ext)s' https://www.youtube.com/playlist?list=PLEu1s4DvSsOYLtU07uKbsYZNP0Uowgecl
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-ciwv', u'\u2014-output', u'%(title)s-%(uploader)s.%(ext)s', u'https://www.youtube.com/playlist?list=PLEu1s4DvSsOYLtU07uKbsYZNP0Uowgecl']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.11 - Darwin-14.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
ERROR: u'\u2014-output' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:—-output" ) to search YouTube
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1303, in _real_extract
    % (url, url), expected=True)
ExtractorError: u'\u2014-output' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:\u2014-output" ) to search YouTube

ERROR: u'%(title)s-%(uploader)s.%(ext)s' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:%(title)s-%(uploader)s.%(ext)s" ) to search YouTube
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1303, in _real_extract
    % (url, url), expected=True)
ExtractorError: u'%(title)s-%(uploader)s.%(ext)s' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:%(title)s-%(uploader)s.%(ext)s" ) to search YouTube

[youtube:playlist] PLEu1s4DvSsOYLtU07uKbsYZNP0Uowgecl: Downloading webpage
[download] Downloading playlist: Kickback
[youtube:playlist] playlist Kickback: Downloading 94 videos
[download] Downloading video 1 of 94

...
<end of log>
```

---

### Description of your *issue*

I'm using the newest version of youtube-dl (2016.05.21.2) on OS X 10.10.5.

My problem is that is seems youtube-dl is interpreting my output option as a URL. I've tried both "-o" and "--output". Youtube-dl will then continue the download as though no output option had been entered. This problem occurred only after I installed this newest version. 
If my memory serves me correct, this command used to work for me. Not sure if I'm doing something wrong or if bug. Please help!

**Comment by yan12125** [comment]
```
—-output
```
The first character is not the minus sign.

**Comment by tohmah** [comment]
Thank you. Looked like a minus! But seeing isn't always believing. Turns out it was having had copy/pasted the command that gave me troubles.
Cheers!
