### ISSUE TITLE
Sites using youtube-dl

### ISSUE THREAD

**Issue by EnginePod** [rg3/youtube-dl#9580]
Does anyone know any sites that are powered with youtube-dl?

I thought it'd be handy to have when you don't have youtube-dl ready (like when I'm on my phone or university computer) and still want to download something.

**Comment by dstftw** [comment]
Offtopic.

**Comment by EnginePod** [comment]
I don't see how this is off-topic.
It's about youtube-dl and my issue is that I want to use it on devices that don't have youtube-dl installed.

There is literally no place better to ask this question than here.
