### ISSUE TITLE
Using wget or HTTrack with youtube-dl?

### ISSUE THREAD

**Issue by NickWinston123** [rg3/youtube-dl#9583]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.21.2*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

Hello, I was wondering if there was any easy way to connect youtube-dl to something like wget or HTTrack when downloading things like soundcloud songs or youtube pages. I would like to use something like wget to copy websites and when playing the song / video from the downloaded html page, I would like it to pull from whereever youtube-dl put the song (not pulling from online but from the download location).
If there isnt a way to do this, could I do this with something like bash or would I have to program something something entirely to do this?

**Comment by dstftw** [comment]
It's technically impossible since download URLs are dynamic and involve real communication with remote party not a mirrored copy.

**Comment by robmOz** [comment]
Hi just wondering if you made any progress on this? I am interested in getting HTTrack to use youtube-dl to download videos.
