### ISSUE TITLE
CBS manual content ID

### ISSUE THREAD

**Issue by spookyahell** [rg3/youtube-dl#9589]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of my feature request
CBS extractor's first step is fetching the content id. I have a content id from a video that won't auto-detect. (http://www.cbs.com/shows/star-trek-2017/) But I can extract it manually (UnACteDDxshm4ZuS_XsNTxvpMjzZtEaJ). I would think it would be good if one can give youtube-dl the URL "http://can.cbs.com/thunder/player/videoPlayerService.php?partner=cbs&contentId=UnACteDDxshm4ZuS_XsNTxvpMjzZtEaJ" (when activating print-traffic it will show that URL for all other videos) directly and it would take it from there.

**Comment by remitamine** [comment]
you will be able to pass the content id to youtube-dl like that:`youtube-dl cbs:content_id`
replace content_id with the content id you want.
