### ISSUE TITLE
Windows 10 and youtube-dl = huge delay caused by Windows Defender

### ISSUE THREAD

**Issue by esamo** [rg3/youtube-dl#9591]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.21.2*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

```
$ "E:/Dropbox/Script/youtube-dl.exe" --verbose --ignore-errors -f 18 --output "E:/Pobrane/_yt/%(title)s.%(ext)s" j5EK3ZGrqeE XtyeHZQ3tl4 IW0dqiPxjvE
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'--ignore-errors', u'-f', u'18', u'--output', u'E:/Pobrane/_yt/%(title)s.%(ext)s', u'j5EK3ZGrqeE', u'XtyeHZQ3tl4', u'IW0dqiPxjvE']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
...
<end of log>
```
---

### Description of your *issue*, suggested solution and other information

After upgrading to `Windows 10`, youtube-dl gets `5min (or more) delay` before doing anything. I noticed that for this time in the task manager entry `Antimalware Service Executable > Windows Defender Service` is taking one whole CPU thread (thread is 3.2 GHz). The OS I had before was Windows 8.1. I don't expect that devs will alter Windows behavior, but maybe figure out what in the youtube-dl is causing `defender scan to take so much time`.

Regards & respect

**Comment by dstftw** [comment]
[Add an exclusion for youtube-dl.exe](https://github.com/rg3/youtube-dl#youtube-dl-is-extremely-slow-to-start-on-windows).

**Comment by Hrxn** [comment]
Can't reproduce on Windows 10.

Did you try running it not from within the Dropbox folder? Or exit Dropbox to test?
