### ISSUE TITLE
unable to login udemy

### ISSUE THREAD

**Issue by muhasturk** [rg3/youtube-dl#9594]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**

- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

- [x] Bug report (encountered problems with youtube-dl)

---

```
➜  Udemy youtube-dl https://www.udemy.com/intermediate-ios/learn/v4/content -F -u "a@gmail.com" -p "a" --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.udemy.com/intermediate-ios/learn/v4/content', u'-F', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.11 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, rtmpdump 2.4
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Logging in as behlulkusaslan@gmail.com
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 340, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 334, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 134, in _real_initialize
    self._login()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/udemy.py", line 172, in _login
    raise ExtractorError('Unable to log in')
ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by dstftw** [comment]
Post the output of `youtube-dl https://www.udemy.com/intermediate-ios/learn/v4/content -F -u "login" -p "password" --verbose --dump-pages`.

**Comment by nlns** [comment]
`
youtube-dl https://www.udemy.com/beyaz-sapkal-hacker-egitim-seti/learn/v4/content -F -u "xxxx@xx.com" -p "xx" --verbose --dump-pages


ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version;
 see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its com
plete output.
Traceback (most recent call last):
  File "c:\users\fast34\appdata\local\programs\python\python35-32\lib\site packages\youtube_dl\YoutubeDL.py", line 676,in extract_info
    ie_result = ie.extract(url)
  File "c:\users\fast34\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 340, in extract
    self.initialize()
  File "c:\users\fast34\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\common.py", line 334, in initialize
    self._real_initialize()
  File "c:\users\fast34\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\udemy.py", line 134, in _real_initialize
    self._login()
  File "c:\users\fast34\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\udemy.py", line 172, in _login
    raise ExtractorError('Unable to log in')
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are
 using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbos
e flag and include its complete output.`

i have same bug. i try this output " youtube-dl https://www.udemy.com/beyaz-sapkal-hacker-egitim-seti/learn/v4/content -F -u "xxxx@xx.com" -p "xx" --verbose --dump-pages " but i cant fixed. Can u help me ?

**Comment by dstftw** [comment]
Post the **full** output as sugested.

**Comment by nlns** [comment]
`Windows PowerShell
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

PS C:\Users\fast34> youtube-dl https://www.udemy.com/beyaz-sapkal-hacker-egitimseti/learn/v4/content -F -u "xx@xx.com" -p "xxx" --verbose --dump-pages
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['https://www.udemy.com/beyaz-sapkal-hacker-egitim-seti/learn/v4/content', '-F', '-u', 'PRIVA
TE', '-p', 'PRIVATE', '--verbose', '--dump-pages']
[debug] Encodings: locale cp1254, fs mbcs, out cp857, pref cp1254
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 3.5.1 - Windows-8.1-6.3.9600-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[udemy:course] Downloading login popup
[udemy:course] Dumping request to https://www.udemy.com/join/login-popup/?displayType=ajax&showSkipButton=1
CgoKCgoKPCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuLXVzIiA+CiAgICA8aGVhZD4KICAg
CjwvZGl2PgoKICAgICAgICAKICAgIDwvYm9keT4KPC9odG1sPgo..........
[udemy:course] Logging in as enesenesenes@enes.com
[udemy:course] Dumping request to https://www.udemy.com/join/login-popup/
displayType=ajax&showSkipButton=1
CgoKCgoKPCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9InRyLXRyIiA+CiAgICA8aGVhZD4KICAgICAgICA8dGl0bGU+CiAgICAgICAgICAgI............
ERROR: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version;
 see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its com
plete output.
Traceback (most recent call last):
  File "c:\users\fast34\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 676,
in extract_info
    ie_result = ie.extract(url)
  File "c:\users\fast34\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\common.py", lin
e 340, in extract
    self.initialize()
  File "c:\users\fast34\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\common.py", lin
e 334, in initialize
    self._real_initialize()
  File "c:\users\fast34\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\udemy.py", line
 134, in _real_initialize
    self._login()
  File "c:\users\fast34\appdata\local\programs\python\python35-32\lib\site-packages\youtube_dl\extractor\udemy.py", line
 172, in _login
    raise ExtractorError('Unable to log in')
youtube_dl.utils.ExtractorError: Unable to log in; please report this issue on https://yt-dl.org/bug . Make sure you are
 using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbos
e flag and include its complete output.

PS C:\Users\fast34>`

this full post

**Comment by dstftw** [comment]
>CgoKCgoKPCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuLXVzIiA+CiAgICA8aGVhZD4KICAg
CjwvZGl2PgoKICAgICAgICAKICAgIDwvYm9keT4KPC9odG1sPgo..........

**Do not trim** any lines.

**Comment by nlns** [comment]
i try but github not supported long comment. ( Sorry! We couldn't save your comment — your comment is too long (maximum is 65536 characters). Please try again. )

**Comment by yan12125** [comment]
Save the log as a file and uploaf it.

**Comment by nlns** [comment]
okey. uploaded.

[https://drive.google.com/file/d/0B4L9Arm1Ga5yM01Ka0g3bjFraDQ/view](url)

**Comment by talktoprogrammers** [comment]
take udemy courses at [](http://www.todaycourses.com)  get job placement services

**Comment by talktoprogrammers** [comment]
[(http://www.todaycourses.com``)]
