### ISSUE TITLE
youtube-dl.exe not working at all

### ISSUE THREAD

**Issue by CaraCulen** [rg3/youtube-dl#9596]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.21.2*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
***was not able to get anything because youtube-dl.exe does not work at all***
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

My PC details:
Windows 10 64-bit
Used latest youtube-dl.exe as well as an older one of a few months ago.
Location: C:\Program Files (x86)\youtube-dl.exe

I do not understand because it was working last time I used it just a few days ago. Now there is only a blinking cursor. It is completely nonfunctional. I am guessing this is because of a Windows update?

Commands executed in cmd.exe:

C:\>cd %ProgramFiles(X86)%
C:\Program Files (x86)>youtube-dl.exe --list-formats https://www.youtube.com/watch?v=hL2sjkt1vE8

(There is only a blinking cursor; no text of any kind. Then, I press Ctrl+C and I get this:)

Traceback (most recent call last):
  File "__main__.py", line 16, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "youtube_dl\__init__.pyo", line 43, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "youtube_dl\extractor\__init__.pyo", line 9, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "youtube_dl\extractor\extractors.pyo", line 316, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "youtube_dl\extractor\ign.pyo", line 1, in <module>
KeyboardInterrupt

C:\Program Files (x86)>

**Comment by yan12125** [comment]
It's a Windows 10's issue. See [this FAQ entry](https://github.com/rg3/youtube-dl#youtube-dl-is-extremely-slow-to-start-on-windows).

**Comment by Hrxn** [comment]
Again, I am using youtube-dl on Windows 10, and I don't encounter this issue.
I've never added any exception to Windows Defender whatsoever..

So it has to be some other program that is running simultaneously.

**Comment by dstftw** [comment]
It's due to Windows Defender and it's not only youtube-dl affected.
