### ISSUE TITLE
Vimeo: ignore album in video URL

### ISSUE THREAD

**Issue by lexazloy** [rg3/youtube-dl#9603]
Hi.

https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/vimeo.py#L577 here some little bit wrong logic.

We have protected album, right?
But it not necessary we have protected video in protected album. :)

URL: `https://vimeo.com/album/[albumId]/video/[videoId]`.

`albumId` is some of protected albums, `videoId` is public. We should ignore album b/c we already know video ID: `https://vimeo.com/[videoId]`.

So album should be ignored in video URL.

**Comment by dstftw** [comment]
Post [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient).

**Comment by yan12125** [comment]
Closing as no response for a long time.
