### ISSUE TITLE
Force youtube-dl to use a certain ip address

### ISSUE THREAD

**Issue by vanilla38** [rg3/youtube-dl#961]
Hi i want to know if it is possible to assign an interface to youtube-dl even if not by an option, maybe somewhere in the code.

I espescially need to get video information with a certain ip adress (report_video_info_webpage_download)

only thing i cant actually do is to set proxy option as the ip i want to use but it's a bit hacky.

Thanks

**Comment by codaman** [comment]
@Elite  i couldnt find any pull request that have --bindip feature

**Comment by jaimeMF** [comment]
@codaman you should try the [`--source-address` option](https://github.com/rg3/youtube-dl/blob/741dd8ea65b276997f3eadae43b2879e9a229a80/README.md#network-options).

**Comment by codaman** [comment]
"youtube-dl.exe --source-address [IP] -g [url]" this implementation not working or wrong usage. i've read all documentation but there is no info about how to use "--source-address"

**Comment by phihag** [comment]
@codaman As @dstftw [told you already](https://github.com/rg3/youtube-dl/issues/721#issuecomment-158088475), we can and will not help you until you [open a new issue](https://github.com/rg3/youtube-dl/issues/new?title=problems+with+--source-address) where you describe your problem. See [our bug reporting guidelines](https://yt-dl.org/bup) for what that description should contain. Most important is the output you get when you run youtube-dl with the `-v` option. For debugging `--source-address`, it is also highly advisable to pass in `-C` as well.
