### ISSUE TITLE
MTV/VH1 not working

### ISSUE THREAD

**Issue by tchawes** [rg3/youtube-dl#9613]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.05.21.2_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.21.2**
### Before submitting an _issue_ make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -f "best[height<=720]" -A "http://www.vh1.com/full-episodes/uvodsd/love-and-hip-hop-atlanta-common-ground-season-5-ep-508" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-f', u'best[height<=720]', u'-A', u'http://www.vh1.com/full-episodes/uvodsd/love-and-hip-hop-atlanta-common-ground-season-5-ep-508', u'-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-79630-g9ac154d, ffprobe N-79630-g9ac154d, rtmpdump 2.3
[debug] Proxy map: {}
[generic] love-and-hip-hop-atlanta-common-ground-season-5-ep-508: Requesting header
WARNING: Falling back on generic information extractor.
[generic] love-and-hip-hop-atlanta-common-ground-season-5-ep-508: Downloading webpage
[generic] love-and-hip-hop-atlanta-common-ground-season-5-ep-508: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/uvodsd/love-and-hip-hop-atlanta-common-ground-season-5-ep-508
Traceback (most recent call last):
  File "youtube_dl\extractor\generic.pyo", line 1413, in _real_extract
  File "youtube_dl\compat.pyo", line 280, in compat_etree_fromstring
  File "youtube_dl\compat.pyo", line 269, in _XML
  File "xml\etree\ElementTree.pyo", line 1642, in feed
  File "xml\etree\ElementTree.pyo", line 1506, in _raiseerror
ParseError: not well-formed (invalid token): line 29, column 57
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 676, in extract_info
  File "youtube_dl\extractor\common.pyo", line 341, in extract
  File "youtube_dl\extractor\generic.pyo", line 2105, in _real_extract
UnsupportedError: Unsupported URL: http://www.vh1.com/full-episodes/uvodsd/love-and-hip-hop-atlanta-common-ground-season-5-ep-508
```
### Description of your _issue_, suggested solution and other information

I checked the supported sites tab and MTV and VH1 are listed, however I get an unsupported URL with the video above.  I also tried a couple of others across both VH1 and MTV sites.  I have a valid Cable Subscription Account I can use to login.

**Comment by StevenDTX** [comment]
This is the same issue I reported back in January.  That being said, MTV has changed their streaming again this week.

https://github.com/rg3/youtube-dl/issues/8169

**Comment by MrRobot12** [comment]
This is the method they are using now...

http://www.mtv.com/full-episodes/boj31q/are-you-the-one-perfect-match-at-first-sight-season-4-ep-401

Play the video and then search for mediagenerator with an url snooper. This will give you the first segment. 

http://media-utils.mtvnservices.com/services/MediaGenerator/mgid:arc:video:mtv.com:4a5bda08-3172-11e6-8a89-0026b9414f30?device=iPad&isEpisode=true&format=json

Paste the above link into your browser and then it will give another url for the video as well as links for subs below that.

https://cp107857-f.akamaihd.net/i/mtvnorigin/gsp.alias/mediabus/mtv.com/2016/06/27/11/33/15/dcdd637c077048638420a8b06cf3a95b/1203039/0uhCtoTVOs_6469690_1203039_20160627113315990_,384x216_278,512x288_498,640x360_1028,768x432_1528,960x540_2128,1280x720_3128,1920x1080_5128,.mp4.csmil/master.m3u8?hdnea=st%3D1468549996%7Eexp%3D1468564396%7Eacl%3D%2Fi%2Fmtvnorigin%2Fgsp.alias%2Fmediabus%2Fmtv.com%2F2016%2F06%2F27%2F11%2F33%2F15%2Fdcdd637c077048638420a8b06cf3a95b%2F1203039%2F0uhCtoTVOs_6469690_1203039_20160627113315990_%2C384x216_278%2C512x288_498%2C640x360_1028%2C768x432_1528%2C960x540_2128%2C1280x720_3128%2C1920x1080_5128%2C.mp4.csmil%2F*%7Ehmac%3Daaf436db085bff1cd2e83e063e7bcccf27c7bf99448b23c36e617d593aed5a5a&__a__=off&__b__=450&__viacc__=NONE

Once the 1st segment is done playing the next segment will show up on your url snooper. There are usually around 7-9 segments for a 42 minute show. This should be easy enough to implement. All the videos use the same method.

**Comment by MrRobot12** [comment]
Does this help guys? Adownloader is able to download the MTV segments/subs without a login, so I know it's possible.

Adownloader is buggy as hell though so I'd rather use youtube-dl.

**Comment by StevenDTX** [comment]
@MrRobot12 

I haven't really had a chance to mess with it since you posted. Hopefully I will be able to tomorrow.  Thanks.

**Comment by tchawes** [comment]
If you click on each segment in the video player timeline, you can get the mediagen url's much faster.

I also noticed that not all shows are on the "new" player.  It seems like shows that started their season with the "old" player are finishing out that way and shows that new seasons started recently are on the new player.

**Comment by MrRobot12** [comment]
Bump.

**Comment by dollabi11z** [comment]
Bump.

**Comment by MrRobot12** [comment]
So I see MTV is working now, but it downloads the 8 segments individually and doesn't mux them together into one file at the end. Is there anyway to get youtube-dl to do that?

**Comment by joetex72** [comment]
vh1.com still doesn't work. :(
```
C:\YouTubeDL>youtube-dl --verbose "http://www.vh1.com/full-episodes/b3c239/dating-naked-stripped-searching-season-3-ep-301" --write-sub
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', 'http://www.vh1.com/full-episodes/b3c239/dating-naked-stripped-searching-season-3-ep-301', '--write-sub']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.11.27
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82536-gc493a53, ffprobe N-82536-gc493a53, rtmpdump 2.4-20151223-gfa8646d-LibreSSL_2.5.0-i686-static
[debug] Proxy map: {}
[generic] dating-naked-stripped-searching-season-3-ep-301: Requesting header
WARNING: Falling back on generic information extractor.
[generic] dating-naked-stripped-searching-season-3-ep-301: Downloading webpage
[generic] dating-naked-stripped-searching-season-3-ep-301: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/b3c239/dating-naked-stripped-searching-season-3-ep-301
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi2nj3req\build\youtube_dl\extractor\generic.py", line 2449, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.vh1.com/full-episodes/b3c239/dating-naked-stripped-searching-season-3-ep-301
```
Is the problem due to the video being split into segments?
@MrRobot12 : ffmpeg can do it with the "-f concat" switch.

**Comment by joetex72** [comment]
The series using the new segmented player on mtv and vh1 are still giving errors.

MTV:
```
C:\>youtube-dl --update
youtube-dl is up-to-date (2016.12.01)

C:\>youtube-dl "http://www.mtv.com/full-episodes/xrxv4o/real-world-seattle-bad-blood-a-bloody-good-start-season-32-ep-3201" --verbose
[debug] System config: []
[debug] User config: ['-o', 'G:\\Video\\Audials Imported Movies\\%(title)s.%(ext)s', '--add-metadata', '--write-sub']
[debug] Command-line args: ['http://www.mtv.com/full-episodes/xrxv4o/real-world-seattle-bad-blood-a-bloody-good-start-season-32-ep-3201', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82721-g89092fa, ffprobe N-82721-g89092fa, rtmpdump 2.4-20151223-gfa8646d-LibreSSL_2.5.0-i686-static
[debug] Proxy map: {}
[mtv] real-world-seattle-bad-blood-a-bloody-good-start-season-32-ep-3201: Downloading webpage
ERROR: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\mtv.py", line 231, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\mtv.py", line 225, in _extract_mgid
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\common.py", line 660, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract mgid; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
VH1:
```
C:\>youtube-dl --update
youtube-dl is up-to-date (2016.12.01)

C:\>youtube-dl "http://www.vh1.com/full-episodes/ns2gw0/love-and-hip-hop-hollywood-california-dreaming-season-3-ep-301" --verbose
[debug] System config: []
[debug] User config: ['-o', 'G:\\Video\\Audials Imported Movies\\%(title)s.%(ext)s', '--add-metadata', '--write-sub']
[debug] Command-line args: ['http://www.vh1.com/full-episodes/ns2gw0/love-and-hip-hop-hollywood-california-dreaming-season-3-ep-301', '--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.12.01
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-82721-g89092fa, ffprobe N-82721-g89092fa, rtmpdump 2.4-20151223-gfa8646d-LibreSSL_2.5.0-i686-static
[debug] Proxy map: {}
[generic] love-and-hip-hop-hollywood-california-dreaming-season-3-ep-301: Requesting header
WARNING: Falling back on generic information extractor.
[generic] love-and-hip-hop-hollywood-california-dreaming-season-3-ep-301: Downloading webpage
[generic] love-and-hip-hop-hollywood-california-dreaming-season-3-ep-301: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/full-episodes/ns2gw0/love-and-hip-hop-hollywood-california-dreaming-season-3-ep-301
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\YoutubeDL.py", line 694, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\common.py", line 357, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6j6yd3lp\build\youtube_dl\extractor\generic.py", line 2433, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.vh1.com/full-episodes/ns2gw0/love-and-hip-hop-hollywood-california-dreaming-season-3-ep-301
```
Both episodes are free and require no account like the topic label says. You can test with these free links:

http://www.mtv.com/video-clips/z783wg/are-you-the-one-sneak-peek-trouble-in-the-boom-boom-room
http://www.vh1.com/video-clips/wekuo5/love-and-hip-hop-hollywood-nikki-and-teairra-catch-up

All the bonus clips on both sites are free to watch but youtube-dl supports none of them. Atresmedia Downloader (Adownloader) is doing the job for now, but that program always feels like it's going to crash my system and doesn't feel as clean as youtube-dl.

NO ACCOUNT is needed to watch the first episodes and bonus clips of the new series that use the segmented player.

**Comment by joetex72** [comment]
Anyone willing to tackle this if I provide a free account?

**Comment by StevenDTX** [comment]
MTV has been working for quite some time, but VH1 still gives an "Unsupported URL" error.

```
c:\support\youtube-dl.exe --download-archive D:\scripts\Auto-TV-Download\archive.txt --restrict-filenames --continue --no-check-certificate --ignore-errors --verbose -f "best[height=720]" -o "D:\scripts\Auto-TV-Download\TEMP\Love..Hip.Hop.Atlanta.S06E16.The.End.Is.Near-%(playlist_index)s.mp4" "http://www.vh1.com/episodes/z5wzin/love-and-hip-hop-atlanta-the-end-is-near-season-6-ep-616"

[debug] Command-line args: ['--download-archive', 'D:\\scripts\\Auto-TV-Download\\archive.txt', '--restrict-filenames', '--continue', '--no-check-certificate', 
'--ignore-errors', '--verbose', '-f', 'best[height=720]', '-o', 'D:\\scripts\\Auto-TV-Download\\TEMP\\Love..Hip.Hop.Atlanta.S06E16.The.End.Is.Near-%(playlist_index)s.mp4', 
'http://www.vh1.com/episodes/z5wzin/love-and-hip-hop-atlanta-the-end-is-near-season-6-ep-616']

[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252

[debug] youtube-dl version 2017.07.02

[debug] Python version 3.4.4 - Windows-10-10.0.14393

[debug] exe versions: ffmpeg N-82966-g6993bb4, ffprobe N-72383-g7206b94, rtmpdump 2.4

[debug] Proxy map: {}

[generic] love-and-hip-hop-atlanta-the-end-is-near-season-6-ep-616: Requesting header
WARNING: Falling back on generic information extractor.

[generic] love-and-hip-hop-atlanta-the-end-is-near-season-6-ep-616: Downloading webpage
[generic] love-and-hip-hop-atlanta-the-end-is-near-season-6-ep-616: Extracting information
ERROR: Unsupported URL: http://www.vh1.com/episodes/z5wzin/love-and-hip-hop-atlanta-the-end-is-near-season-6-ep-616

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\YoutubeDL.py", line 762, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\extractor\common.py", line 433, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcnuqbtg0\build\youtube_dl\extractor\generic.py", line 2824, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.vh1.com/episodes/z5wzin/love-and-hip-hop-atlanta-the-end-is-near-season-6-ep-616


```

**Comment by tchawes** [comment]
Looks like they are using a new player for the URL in the last comment that gets a playlist from somewhere with a master.m3u8 for each segment.

**Comment by StevenDTX** [comment]
Thanks @mhartkorn and @remitamine
