### ISSUE TITLE
Download from pluralsight - Avoid ban

### ISSUE THREAD

**Issue by lilleindi** [rg3/youtube-dl#9614]
Hi
Do i have to do anything other than --Sleep interval, and set it to fx 45
Is there anything else to do to avoid getting banned?

Regards
Lilleindi

**Comment by dstftw** [comment]
That's impossible to know. Read https://github.com/rg3/youtube-dl/issues/6090 for some hints.

**Comment by lilleindi** [comment]
Thanks a lot :-)
