### ISSUE TITLE
Site support request: Seeker

### ISSUE THREAD

**Issue by TRox1972** [rg3/youtube-dl#9619]
Example URL: http://www.seeker.com/who-was-ada-lovelace-the-worlds-first-computer-nerd-1824587801.html

**Comment by yan12125** [comment]
To developers: Prizma embed.

**Comment by TRox1972** [comment]
TestTube, which was supported under the Revision3 extractor have changed name to Seeker. The tests in the extractor for testtube.com are now either redirects or doesn't work anymore. Extending the `_VALID_URL` to include Seeker.com also produces some issues regarding the JSON metadata. I'll try to look into this, but any help would be good.

**Comment by TRox1972** [comment]
The URL layout seems to have changed, e.g. from
https://testtube.com/dnews/5-weird-ways-plants-can-eat-animals
to
http://www.seeker.com/5-weird-ways-plants-can-eat-animals-1792532082.html

**Comment by TRox1972** [comment]
The JSON can now be found at

http://api.seekernetwork.com/api/getPlaylist.json?api_key=ba9c741bce1b9d8e3defcc22193f3651b8867e62&codecs=h264,vp8,theora&video_id=75822&jsonp=parseResponse&_=1464446163531

**Comment by TRox1972** [comment]
thanks @remitamine! 👍
