### ISSUE TITLE
conflict between -A and -o 

### ISSUE THREAD

**Issue by adeebothman** [rg3/youtube-dl#9640]
i'm trying to give auto number for the downloaded videos as well as keeping the exact name without any extra character last ne could be done by -o "%(title)s.%(ext)s" 
but as you see the error there is a conflict 
**youtube-dl: error: using output template conflicts with using title, video ID or auto number**

**Comment by dstftw** [comment]
`-A` and `-o` **can't** be used together.

**Comment by phihag** [comment]
If you want to include an auto number in your filenames, simply include `%(autonumber)s` in your filename template. For instance, `-o "%(autonumber)s_%(title)s.%(ext)s"` may fit your needs.
