### ISSUE TITLE
Keeps getting "No video formats found" error

### ISSUE THREAD

**Issue by lilleindi** [rg3/youtube-dl#9641]
Hi
Im trying to download from Pluralsight, but keep getting errors. When batch download 6 courses, its only two courses that been downloaded.
Im using the latest version.
I have replaced the pluralsight url

Im using this command
--sleep-interval 360 -v --no-check-certificate -o '~/MyVideos/%(playlist)s/%(title)s.%(ext)s'

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--newline', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-i', u'-o', u'C:\\Users\\jakobjensen\\videoerPlu\\%(title)s.%(ext)s', u'--sleep-interval', u'360', u'-v', u'--no-check-certificate', u'-o', u"'~/MyVideos/%(playlist)s/%(title)s.%(ext)s'", u'PLURALSIGHT-URL']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.10 - Windows-2012Server-6.2.9200
[debug] exe versions: ffmpeg N-71883-geb9fb50, ffprobe N-71883-geb9fb50
[debug] Proxy map: {}
WARNING: Unable to download webpage: HTTP Error 429:
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 676, in extract_info
  File "youtube_dl\extractor\common.pyo", line 341, in extract
  File "youtube_dl\extractor\pluralsight.pyo", line 226, in _real_extract
  File "youtube_dl\extractor\common.pyo", line 862, in _sort_formats
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: 'NoneType' object has no attribute 'copy'
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 687, in extract_info
  File "youtube_dl\YoutubeDL.pyo", line 848, in process_ie_result
  File "youtube_dl\YoutubeDL.pyo", line 752, in process_ie_result

And the courses thats been downloaded fine shows this

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--newline', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-i', u'-o', u'C:\\Users\\jakobjensen\\videoerPlu\\%(title)s.%(ext)s', u'--sleep-interval', u'360', u'-v', u'--no-check-certificate', u'-o', u"'~/MyVideos/%(playlist)s/%(title)s.%(ext)s'", u'PLURALSIGHT-URL']
[debug] Encodings: locale cp1252, fs mbcs, out None, pref cp1252
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.10 - Windows-2012Server-6.2.9200
[debug] exe versions: ffmpeg N-71883-geb9fb50, ffprobe N-71883-geb9fb50
[debug] Proxy map: {}

**Comment by dstftw** [comment]
429 is an indication of overuse. Wait some time and try later.

**Comment by lilleindi** [comment]
How can i avoid this error?
Im waiting 360 Sec between each download?

**Comment by lilleindi** [comment]
Do i download one at a time?

**Comment by dstftw** [comment]
There are no concrete recipes.

**Comment by lilleindi** [comment]
Is it overuse from my computer or overuse from Pluralsight website?

**Comment by dstftw** [comment]
Overuse of pluralsight website by your IP decided by pluralsight.
