### ISSUE TITLE
dstftw - GPG Public Key

### ISSUE THREAD

**Issue by Nurple** [rg3/youtube-dl#9647]
@dstftw

Heya, your public key doesn't seem to be on any of the keys servers, I'd like to be able to check the sig of the Windows release.

Thanks.

**Comment by dstftw** [comment]
It's over [here](https://dstftw.github.io/keys/18A9236D.asc).

**Comment by phihag** [comment]
@dstftw Do you mind publishing it on a widely-used keyserver, like https://pgp.mit.edu ? That helps in a lot of setups.

**Comment by dstftw** [comment]
@phihag I'm fine with that.
