### ISSUE TITLE
is there any method to download all of videos uploaded by a user , from supported sites without this feature

### ISSUE THREAD

**Issue by siddht1** [rg3/youtube-dl#9648]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.30.2*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.30.2**

### Before submitting an *issue* make sure you have:
- [ ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.05.30.2
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

Hi there,

I would like to know how to download all the videos uploaded by a user or from a playlist from a non supported site ? I know that this things works for youtube user, youtube playlist, instagram user  , but how to do this from a non supported like pornhub , xvideos ,etc.  Where does the code reside for the working sites inside youtube-dl ?

**Comment by TRox1972** [comment]
You can find the code for the extractors at https://github.com/rg3/youtube-dl/tree/master/youtube_dl/extractor.

As of now, the only ways to download all videos from a user on a website where this is not currently supported by youtube-dl, is either to externally fetch the necessary links and then parse them to youtube-dl, or modify the extractor for the website in question to support this. If you do the latter, you are welcome to open a [pull request](https://github.com/rg3/youtube-dl/pulls). Read the [Developer Instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#developer-instructions) for more details.

**Comment by siddht1** [comment]
yes    ,  I understood your answer but i need help too     , 
eg:  youtube-dl https://www.youtube.com/user/SpaceAmbient/videos -f bestaudio -i
  would download and the audio files of the youtube user SpaceAmbient , this is an example of the supported site.  
 Where does this code resides in youtube-dl?

but how to do this for a non supported site eg : xvideos 
youtube-dl http://www.xvideos.com/profiles/alura-jenson-1    
would fail for youtube-dl


This is more of a feature request than new site support so how to work  on this.

**Comment by TRox1972** [comment]
@siddht1 The code for downloading all the videos from one user page on a specific page, resides in that sites extractor. E.g. the extractor for youtube.com has a [own class](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1912-L1984) that recongize YouTube channel URLs and tries to fetch all the video links from the channel.

The [extractor for the site in question](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/xvideos.py) currently only supports single videos, but can be expanded to support user pages too.

As this seems to be a request, the title should be changed to something more descriptive.

**Comment by dstftw** [comment]
As mentioned by @TRox1972 in general a separate extractor should be implemented to support playlists of particular site.
XVideos playlist support is [already requested](https://github.com/rg3/youtube-dl/issues/1395).
