### ISSUE TITLE
Some available formats missed on vertical videos

### ISSUE THREAD

**Issue by Hydronicx** [rg3/youtube-dl#9649]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.05.30.2*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.05.30.2**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
bleh
bleh bleh

bleh
```

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

Hey all.

Running -F on vertical videos misses some available formats. For example, -F on fL19VltKgbs misses 1080p60 mp4.

Cheers.

**Comment by yan12125** [comment]
It's there:
```
315          webm       1080x1920  1080p60 8091k , vp9, 60fps, video only, 187.95MiB
```

**Comment by Hydronicx** [comment]
That's webm, not mp4.

**Comment by yan12125** [comment]
It's webm on YouTube:
![screenshot_2016-05-31_20-42-49](https://cloud.githubusercontent.com/assets/1937689/15674618/548a8918-2770-11e6-8c6b-4e3e0cef7e5f.png)

**Comment by yan12125** [comment]
By the way, if you want an mp4 file, ```--recode-video``` should be useful.

**Comment by Hydronicx** [comment]
Oh, sorry for the confusion. Thanks!
