### ISSUE TITLE
--add-metadata has some weird behavior

### ISSUE THREAD

**Issue by TheSqrtMinus1** [rg3/youtube-dl#9650]
### Description of your *issue*, suggested solution and other information

M'kay, so apparently --add-metadata involves rewriting the ENTIRE FILE? 

```youtube-dl -iw --no-continue $URL -f bestvideo+bestaudio --add-metadata --merge-output-format mp4 -o "[%(upload_date)s] %(title)s" --prefer-ffmpeg --download-archive archive.txt --postprocessor-args "-strict -2 -threads 8 -c:v libx264 -crf 18 -preset veryslow -c:a aac -b:a 192k -movflags +faststart"``` gives me an output of example.mp4 , fully playable, without metadata. Then I see another copy, example.temp.mp4, that slowly grows to the size of example.mp4 and then replaces it. The output of youtube-dl during all of this is the standard ```[ffmpeg] Adding metadata to 'example.mp4'```

Any way to fix this?

**Comment by TRox1972** [comment]
That isn't possible with ffmpeg; it always needs to construct a new file with the applied changes.

**Comment by dstftw** [comment]
This behavior is explicitly requested by you: `--postprocessor-args` is passed to any postprocessor involved including one that adds metadata. Remove any re-encoding from `--postprocessor-args` and it will be as fast as adding metadata.
