### ISSUE TITLE
Unable to download from lynda.com site

### ISSUE THREAD

**Issue by amanaman118** [rg3/youtube-dl#9668]
Amans-MacBook-Pro:WordPress Ecommerce Easy Digital Downloads aman$ youtube-dl -u amanaman118@gmail.com www.lynda.com/WordPress-tutorials/WordPress-Ecommerce-Easy-Digital-Downloads/122465-2.html
Type account password and press [Return]: 
[lynda:course] Logging in as amanaman118@gmail.com

ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by guoyida** [comment]
Same here. What is wired is I downloaded another course a few hours ago and it was OK. I have no problem viewing this course online, but just not able to download.

**Comment by dstftw** [comment]
**Post the full output of youtube-dl when run with `-v`**, i.e. **add** `-v` flag to **your command line**, copy the **whole** output and post it in the issue body wrapped in \`\`\` for better formatting. It should look similar to this:
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2015.12.06
[debug] Git HEAD: 135392e
[debug] Python version 2.6.6 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
```
**Do not post screenshots of verbose log only plain text is acceptable.**

The output (including the first lines) contains important debugging information. Issues without the full output are often not reproducible and therefore do not get solved in short order, if ever.

**Comment by amanaman118** [comment]
Hi,

Below is what i have got with -v flag
Not sure password is not matching up. But i tried it several time and now it has started working with same password.

```
Amans-MacBook-Pro:WordPress Ecommerce Easy Digital Downloads aman$ youtube-dl -v -u amanaman118@gmail.com www.lynda.com/WordPress-tutorials/WordPress-Ecommerce-Easy-Digital-Downloads/122465-2.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-u', u'PRIVATE', u'www.lynda.com/WordPress-tutorials/WordPress-Ecommerce-Easy-Digital-Downloads/122465-2.html']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.02
[debug] Python version 2.7.10 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0.1, ffprobe 3.0.1
[debug] Proxy map: {}
WARNING: The url doesn't specify the protocol, trying with http
[lynda:course] Logging in as amanaman118@gmail.com
ERROR: Unable to download webpage: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 388, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1946, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by amanaman118** [comment]
Some trick found to get it working remove https from url and its working 
as soon as i put https it stops working and says unauthorised.

Mite can help to debug issue.

**Comment by guoyida** [comment]
I think this helps.
1. log out your account everywhere else (in you browser)
2. wait a few hours and try to download again
I manage to download the course I couldn't.
