### ISSUE TITLE
android version?

### ISSUE THREAD

**Issue by ghost** [rg3/youtube-dl#967]
I want to use my android phone to download youtube videos via public wi-fi and watch them later back home. Will you (plan to) release android version for youtube-dl?

**Comment by alseambusher** [comment]
Here is a simple way to run youtube-dl on android:
http://lifepluslinux.blogspot.in/2015/01/how-to-use-youtube-dl-on-android.html

@Adrianzo it seems that python is not able to find the libraries in its path. Follow Step1 in the above link

**Comment by BossG** [comment]
i know it's been a while since the last time someone posted but i'm just trying this out on my HTC one M9 without root and a terminal emulator, i have python(r5) installed on it which i got from the website the last poster commented here; It installs fine, i have the unzipped youtube-dl on my local sdcard (not external) and i'm getting permission denied for ./youtube-dl ; i've tried running several different chmod commands in different places, still all the same, can someone who has had the same problem who managed to fix it please help!!! thanks in advance.

**Comment by yan12125** [comment]
I've not tested it, while AFAIK either directly executing files or ```chmod``` is not allowed for SD cards. Try the following command:
```
/path/to/python ./youtube-dl
```

**Comment by BossG** [comment]
this is where ima sound like a complete n00b, i have no idea where my python is installed... i've looked on internal and external /android/. folders

**Comment by yan12125** [comment]
@BossG Sorry for the late response. In many cases the Python binary locates somewhere in /data/. However, you need root priviledge for reading all files in this folder.

**Comment by yan12125** [comment]
There's a command at http://stackoverflow.com/a/13780633/3786245. The author of that answer uses SL4A for the trick. I didn't try the command by my own, and I guess these parameters may not apply to the latest version of SL4A.

**Comment by codaman** [comment]
is there any way to use youtube-dl on android app. There is 2 possible way first; add executable youtube-dl file to android project and run it with command codes second way add scripts to android project and run it. i succeed second way as running scripts on ios project. and also i cant use youtube-dl executable file on android project. i am searching a native example project that can run python codes

**Comment by royale1223** [comment]
Here's an Android GUI: http://www.aviddapp.com/

**Comment by tristan-k** [comment]
@cprior Can your share this tasker project?

>  I confirm that with 2014-11-15.1 it is possible to link on an Android phone Tasker, AutoShare and Python into youtube-dl.

**Comment by yan12125** [comment]
Termux provides Python. You can ```apt-get install``` it and run youtube-dl following Linux/Mac ways.

**Comment by tristan-k** [comment]
Already did that. I'm interessted in the tasker project.

**Comment by bdovaz** [comment]
Any way to integrate it into an existing Android app? I mean, is there a way to run a python script from Java? I've been researching but haven't find anything useful yet.

**Comment by codaman** [comment]
i ran python scripts in ios. It must be possible to run python scripts in android. I am searching a good example. If i will find out, i will share from here

**Comment by YECAPP** [comment]
Final run ok for me, this is the code that running right

```
import sys,os
sys.path.append('/path/to/replace/this/ytdl')
import youtube_dl
os.chdir(r'/sdcard/Download')
youtube_dl.main(['sfR_HWMzgyc'])

```

Add os library to change directory if denied write permissions

Resume: 
1)Install Python SL4A
2)Install Qpython 
3)Add Script in Qpython 
4)type or copy this code 
```

import sys,os
sys.path.append('/path/to/replace/this/ytdl')
import youtube_dl
os.chdir(r'/sdcard/Download')
youtube_dl.main(['linkVideo'])

```
Where Link video is copy from youtube 
5)run it !

Use this method if you are not root user

**Comment by madacol** [comment]
Installing `youtube-dl` with Termux
https://www.reddit.com/r/Piracy/comments/baufql/youtubedl_the_easy_way_on_android/
