### ISSUE TITLE
syntax error near unexpected token `('

### ISSUE THREAD

**Issue by guoyida** [rg3/youtube-dl#9670]
I am using the latest build to download from Lynda on my Mac.
I know this is a bit silly, but I got this warning:
-bash: syntax error near unexpected token `('
I try to type the command serval times just to make sure I don't have funny '(' or ')'
This is the command I used:

`-o '%(id)s-%(title)s.%(ext)s' https://www.lynda.com/some-course --username usr --password pwd`

I suppose the error comes from the argument -o, but I just could not find the difference with the example except that I flip id and title. Please help!

**Comment by yan12125** [comment]
Could you try double quotes? For example:
```
-o "%(id)s-%(title)s.%(ext)s" https://www.lynda.com/some-course --username usr --password pwd
```

**Comment by guoyida** [comment]
It worked when I copy your command. I noticed that my " is different than yours, but I am using English as my input source. Thank you very much!
