### ISSUE TITLE
Downloading soundcloud tracks incorrectly.

### ISSUE THREAD

**Issue by NickWinston123** [rg3/youtube-dl#9672]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.02**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

When using youtube-dl to download soundcloud tracks, I notice that youtube-dl is messing up the entire track. It either downloads only half the song, or adds onto the song (downloading the real song then adding another half to the song)

Example: I do this to download a persons tracks and it messes up the song length and the song. As an example, I looked at the song "Gwallaboy" that was downloaded, but the song had half of it repearted at the end of its self  for some reason (picture attached) **A song once 2:20 minutes, which was downloaded as 3:21**
```
cd /files/anthony/Music/LoudLord/tracks
youtube-dl https://soundcloud.com/loudlordbitch/tracks --embed-thumbnail -o "%(title)s.%(ext)s" -f mp3 --prefer-ffmpeg --verbose -i
```

![image 2016-06-02 11-14-53](https://cloud.githubusercontent.com/assets/11579042/15750170/6ae78c44-28b3-11e6-8b97-7c9b2b245603.png)

https://soundcloud.com/loudlordbitch/loud-lord-gwallaboy-kush-krazy-coming-soon

Another example is this song:
https://soundcloud.com/loudlordbitch/loud-lord-sky-high
It only downloaded half the song. (picture attached) **A song that was 1:51, but downloaded as 1:19**.

![image 2016-06-02 11-20-13](https://cloud.githubusercontent.com/assets/11579042/15750322/fe6da3e0-28b3-11e6-86b0-f89251448437.png)

**Comment by dstftw** [comment]
All mentioned URLs downloaded exactly same as on the web for me thus I'm almost sure it's not youtube-dl who mess things.
Start with reading [new issue template](https://github.com/rg3/youtube-dl/issues/new) and providing all the requested. Then removing all `*.part` files and redownloading.
