### ISSUE TITLE
Cartoons 8

### ISSUE THREAD

**Issue by splendid25** [rg3/youtube-dl#9674]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.02**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:
```
C:\Temp>youtube-dl -v http://cartoons8.co/cartoon/4017/dragon-ball-super-2015
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://cartoons8.co/cartoon/4017/dragon-ball-super-2015']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.06.02
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] dragon-ball-super-2015: Requesting header
WARNING: Could not send HEAD request to http://cartoons8.co/cartoon/4017/dragon-ball-super-2015: HTTP Error 503: Service Temporarily Unavailable
[generic] dragon-ball-super-2015: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqoaker5v\build\youtube_dl\extractor\common.py", line 388, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpqoaker5v\build\youtube_dl\YoutubeDL.py", line 1946, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://cartoons8.co/watch/153780/dragon-ball-super-2015/episode-45
- Playlist: http://cartoons8.co/cartoon/4017/dragon-ball-super-2015
- RSS playlist : http://cartoons8.co/feedcartoon/4017/dragon-ball-super-2015

---

### Description of your *issue*, suggested solution and other information
Hello,

I would like to download videos from Cartoons 8.
There is no extractor to support it yet.

Thank you.

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.
