### ISSUE TITLE
output template support for %(channel_id)s

### ISSUE THREAD

**Issue by glenn-slayden** [rg3/youtube-dl#9676]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.06.02_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.02**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

The output template should have a way to reference the **YouTube channel id**, i.e.

`%(channel_id)s`

Currently,  `%(uploader_id)s` falls back to rendering the channel id if the uploader doesn't have a name, but there's no way to force this behavior if the uploader _does_ have a name.

_Note:_ If this feature is already available somewhere in youtube-dl, then I could not find it in the documentation, so documentation should be added or improved.

**Comment by Synetech** [comment]
You can use `%(uploader)s` to force it to use the uploader’s name rather than their ID (it’s the second item listed in the `--help`).

**Comment by Synetech** [comment]
You can use `%(uploader)s` to force it to use the uploader’s name rather than their ID (it’s the second item listed in the `--help`).

**Comment by Synetech** [comment]
You can use `%(uploader)s` to force it to use the uploader’s name rather than their ID (it’s the second item listed in the `--help`).

**Comment by Synetech** [comment]
You can use `%(uploader)s` to force it to use the uploader’s name rather than their ID (it’s the second item listed in the `--help`).

**Comment by Synetech** [comment]
You can use `%(uploader)s` to force it to use the uploader’s name rather than their ID (it’s the second item listed in the `--help`).

**Comment by Synetech** [comment]
You can use `%(uploader)s` to force it to use the uploader’s name rather than their ID (it’s the second item listed in the `--help`).

**Comment by Synetech** [comment]
You can use `%(uploader)s` to force it to use the uploader’s name rather than their ID (it’s the second item listed in the `--help`).

**Comment by glenn-slayden** [comment]
No, this request is for a way to force the YouTube **channel id** (such as "UCLqxVugv74EIW3VWh2NOa3Q"), when there is also an uploader name.

As noted above, when using %(uploader_id)s, and when the channel also has a user name, the name seems to have precedence over the channel id, and there doesn't appear to be a way to get the id ("UCLqxVugv74EIW3VWh2NOa3Q"). You get the uploader name instead of the id.

**Comment by Synetech** [comment]
`%(uploader_id)s` *is* the channel ID. For example, because Derek had already created *Veritasium* before, when he re-created it, he had to give it the ID [`1Veritasium`](http://youtube.com/user/1veritasium) since the original one was already used, but its shortcut is [`Veritasium`](http://youtube.com/Veritasium). Likewise, Tom Scott’s channel has his name, but its ID is [`enyay`](http://youtube.com/user/enyay), but its shortcut is [`tomscottgo`](http://youtube.com/tomscottgo).

Where are you getting that other string? Is that an internal Google ID? (And why would you want it anyway?)

**Comment by glenn-slayden** [comment]
Ok, but every channel on YouTube has an 'id' of the form "UCLqxVugv74EIW3VWh2NOa3Q", which is just as permanent as the 'uploader ID' your mention, and can be used interchangeably with it in URLs.

It is easy to find this string in any respective YouTube HTML page, even if originating with the human-readable value. Just search for "channelId" and note the 24-character string that starts with 'UC'.

As for why I want it, the 24-character format which starts with 'UC' is a consistent and predictable format which is identifiably associated with YouTube, for example when it appears as a folder name mixed with other types of strings. That is not true for the human-readable version of the "uploader ID".

And also, remember that **%(uploader_id)s** already does exactly what I'm asking for here -- but _only if there is no human-readable ID available_. What doesn't seem helpful to me is the inconsistency in youtube-dl; there's essentially no way to predict whether you'll get a 24-character ID or otherwise when using **%(uploader_id)s**. Hence I propose **%(channel_id)s** that would always return an 'id' of the form "UCLqxVugv74EIW3VWh2NOa3Q"

**Comment by Synetech** [comment]
Ah right, I know what you are referring to now. I get those IDs for the `/channel/` links in the subscription section of the menu.

I’m still not sure how it would be useful for downloaded videos. I for one would prefer to just see the uploaders’ names rather than some random string; that would make organization a lot easier, and is just as easy to sort. I debated whether even the named channel ID (e.g. `enyay` for Tom Scott’s channel) would be of any practical real-world use, and ended up taking it out of my template and using just `%(uploader)s`.

I’m sure if you really need, they could probably add it, but there’s probably some more useful things that could be added like the the individual timestamp fields for more customizable timestamps.

(Also, the `--help` docs need to be updated because apparently there are a bunch of fields like `%(duration)s` that are available which were not added.)

**Comment by glenn-slayden** [comment]
It's useful for downloaded videos because you can use the output template to specify folder names in the full path leading to the target filename.

You say that having the name "makes organization a lot easier," but as I noted above, I find exactly the opposite to be true for my application. When the downloaded files are managed by a file management program, it is better to have a unique folder identifier which has a well-understood fixed-width format, and is composed from a very limited ASCII character set (many channel names use e.g. Japanese, combining Unicode characters, etc.)

**Comment by glenn-slayden** [comment]
bump?

(apologies if doing so is considered rude; I don't know the culture here)

**Comment by glenn-slayden** [comment]
Actually, it looks like this feature request is mostly solved by the new **%(playlist_id)s** capability which was recently added to the output template. Although the aforementioned keyword in fact returns the 24-character "_playlist_ identifier" (UU...) of the channel, the "channel_id" is trivially obtained by changing the "UU" prefix to "UC."

Unless someone feels like fixing the remaining glitch by adding **%(channel_id)s** to the template syntax as well (should be easy now, eh?), I guess this issue could be marked resolved.

**Comment by glenn-slayden** [comment]
Sorry, looks like I spoke too soon. For operations on individual files, the playlist_id is returning "NA" a value which is not trivially converted to the channel_id value  :-(

youtube_dl --simulate --o "/%(uploader_id)s/%(id)s.%(ext)s" --get-filename http://www.youtube.com/watch?v=BaW_jenozKc

-->  \phihag\BaW_jenozKc.mp4

...whereas I was hoping for...

-->   \UCLqxVugv74EIW3VWh2NOa3Q\BaW_jenozKc.mp4

As far as I can tell, the latter remains impossible to specify with the current output template options.

**Comment by Ectomind1990** [comment]
I agree with the comments by glenn-slayden, and would like to see a `channel_id` field made available for the output template.

It is unsurprising, but probably still worth mentioning, that the `uploader_id` field in the optional JSON file (created if you invoke youtube-dl with `--write-info-json`) seems to behave the same as the `uploader_id` field in the output template, as described by glenn-slayden.  So it will be:
- either a channel ID like UCLqxVugv74EIW3VWh2NOa3Q (a string of length 24, apparently using the base64 "[URL and Filename Safe Alphabet](https://tools.ietf.org/html/rfc4648#section-5)", and always starting with "UC")
- or, effectively anything else (whatever the uploader has chosen as their username, if they have one?)

I guess adding the `channel_id` field to the JSON file would be done at the same time as making it available in the output template.  (If the developers want, I would be happy to create another issue for this.)

If the developers want people to do some testing of these change(s), I volunteer.  I could also help by writing documentation.  (I don't think much documentation will be needed, but if I'm wrong I'd be happy to write quite a lot.)

**Comment by Ectomind1990** [comment]
## Demo

### Actual
For a quick demonstration of the apparent inconsistency of `%(uploader_id)s`, try these 2 commands
`youtube-dl -o 'savedvids/%(uploader_id)s/%(id)s.%(ext)s' https://youtu.be/5THOUSvpCKk`
`youtube-dl -o 'savedvids/%(uploader_id)s/%(id)s.%(ext)s' https://youtu.be/UM96LYjO06E`
And
`ls -crR -w 1 savedvids/*/*`
Gives
`savedvids/1veritasium/5THOUSvpCKk.mkv`
`savedvids/UCBLGbNIdfHuY2UAA0hQ_ytw/UM96LYjO06E.mp4`

That inconsistency in directory naming is why I would like to have a new `%(channel_id)s` field.

### Desired
Here is what I would like to happen, if the feature is implemented:
`youtube-dl -o 'savedvids/%(channel_id)s/%(id)s.%(ext)s' https://youtu.be/5THOUSvpCKk`
`youtube-dl -o 'savedvids/%(channel_id)s/%(id)s.%(ext)s' https://youtu.be/UM96LYjO06E`
And
`ls -crR -w 1 savedvids/*/*`
Gives
`savedvids/UCHnyfMqiRRG1u-2MsSQLbXA/5THOUSvpCKk.mkv`
`savedvids/UCBLGbNIdfHuY2UAA0hQ_ytw/UM96LYjO06E.mp4`


## My Theory About YouTube "Channels"/"Users"

Every uploader is a "channel", and can be accessed at URLs like these:
https://www.youtube.com/channel/UCHnyfMqiRRG1u-2MsSQLbXA
https://www.youtube.com/channel/UCHnyfMqiRRG1u-2MsSQLbXA/videos
https://www.youtube.com/channel/UCHnyfMqiRRG1u-2MsSQLbXA/about
**Some** uploaders are **also** a "user", meaning that the same webpages can also be accessed at URLs like these:
https://www.youtube.com/user/1veritasium
https://www.youtube.com/user/1veritasium/videos
https://www.youtube.com/user/1veritasium/about

If an uploader is also a "user", then YouTube mostly prefers to give you links to the "user" form of URLs.  For example, even [this search](https://www.youtube.com/results?search_query=UCHnyfMqiRRG1u-2MsSQLbXA) gives you [this result](https://www.youtube.com/user/1veritasium).

The exception is when you are on a video page, the link back to the uploader (just above the Subscribe button) always seems to link to the "channel" form of URL.  For example, at [5THOUSvpCKk](https://www.youtube.com/watch?v=5THOUSvpCKk), the link is: "[Veritasium](https://www.youtube.com/channel/UCHnyfMqiRRG1u-2MsSQLbXA)".



## A Look at Some Example "Channels" That Are Not "Users"

The example I've already given was video UM96LYjO06E - from a random channel with just 2 subscribers, currently called [GTMA GTMA](https://www.youtube.com/channel/UCBLGbNIdfHuY2UAA0hQ_ytw).

At the other end of the scale is [The Weeknd - Topic](https://www.youtube.com/channel/UClYV6hHlupm_S_ObS1W-DYw) - a singer with 1/4 million subscribers.

Here is an Arabic channel: https://www.youtube.com/channel/UCrIy5XTmRPwZPOlilXDWacA
I don't know what youtube-dl does when `%(uploader)s` is in Arabic, a right-to-left language. But I think it would be difficult for someone like me to deal with.  That's perhaps another reason why I'd like to have a `%(channel_id)s` field.

**Comment by glenn-slayden** [comment]
I completely concur with _Ectomind1990_'s comments and I still remain quite eager to have this issue fixed in the manner (s)he has so nicely described.

**Comment by glenn-slayden** [comment]
Here is the complete code which fixes this issue if someone would like to propagate it to the master. All changes in 'extractor/youtube.py'. Line numbers are based on **youtube-dl-master** as of 12/23/2016, but should be obvious from context. The two changes (listed in reverse order in order to keep original line numbers valid) are as follows:

extractor/youtube.dl, INSERT at line 1716:
`
            'channel_id': video_channel_id,
`

extractor/youtube.dl, INSERT at line 1413:
` 
        # channel_id
        mobj = re.search(r'itemprop="channelId" content="(UC[-_A-Za-z0-9]{21}[AQgw])"', video_webpage)
        if mobj is not None:
            video_channel_id = mobj.group(1)
        else:
            self._downloader.report_warning('unable to extract channelId')
            video_channel_id = None
`

With this change, you can specify **%(channel_id)s** in your output template, and you will consistently get the "UC..." identifier for both single item and playlist-oriented downloads.

**Comment by Ectomind1990** [comment]
Some people who are interested in this feature request might also be interested in bug #12317 which affected the same area. Could it be worth checking that the proposed new **channel_id** field doesn't suffer from the same problem as the **uploader_id**?

**Comment by Piokaz** [comment]
I was having the same problem, glad to see i was not alone.

Will this be merged to master ? Having "channel_id" is more consistent than "uploader_id".

**Comment by glenn-slayden** [comment]
@Piokaz  The fix [seems to have been rejected](https://github.com/rg3/youtube-dl/pull/12939#issuecomment-298248044), so I am still privately using the [mod shown above](https://github.com/rg3/youtube-dl/issues/9676#issuecomment-269424506).

**Comment by KronK0321** [comment]
I'd like to pile onto this one. I have an indexer that pulls YouTube metadata based on the naming of my folder structure. 

The channel:
`Numberphile [numberphile]` is not correctly identified, while
`Numberphile [UCoxcjq-8xIDTYp3uz647V5A]' is.

**Comment by ianc125** [comment]
Please add this the channel ID is necessary for Plex plugins to properly scrape metadata from youtube. See here: https://github.com/ZeroQI/YouTube-Agent.bundle
