### ISSUE TITLE
Downloading through TOR partially bypasses TOR network.

### ISSUE THREAD

**Issue by zebusr** [rg3/youtube-dl#9677]
When using the following command to route the download through TOR... the initial part of the transfer that fetches file info still goes over the non-TOR network, i.e. it bypasses TOR.

youtube-dl --external-downloader /usr/local/bin/curl  --external-downloader-args '\''--socks5 127.0.0.1:9150'\''  URL

Verified using tcpdump.

**Comment by dstftw** [comment]
You did not specify `--proxy`.

**Comment by zebusr** [comment]
@dstftw  
Adding proxy _helps_ but there is still are multiple cookies being set.
Now using:
youtube-dl --proxy https://127.0.0.1:9150 --external-downloader /usr/local/bin/curl --external-downloader-args '\''--socks5 127.0.0.1:9150'\'' URL

**Comment by yan12125** [comment]
Use ```--proxy socks5://127.0.0.1:9150```.

**Comment by zebusr** [comment]
@yan12125 
OK I tried that. There are still 2 packets that appear to still be either DNS lookup or perhaps an HTTP redirect.

**youtube-dl --proxy socks5://127.0.0.1:9150 --external-downloader /usr/local/bin/curl  --external-downloader-args '\''--socks5 127.0.0.1:9150'\''**

**Comment by yan12125** [comment]
I'll test it later and reopen it if I can reproduce it.

**Comment by yan12125** [comment]
Confirmed. There's at least a DNS lookup not going through Tor but my local DNS server.

**Comment by yan12125** [comment]
Found the problem - the argument passed to curl is wrong. From curl 7.40's man page: (partial)
```
       --socks5-hostname <host[:port]>
              Use the specified SOCKS5 proxy (and let the proxy resolve the host name). If the port number  is  not specified, it is assumed at port 1080. (Added in 7.18.0)

              Since  7.21.7,  this  option  is  superfluous  since you can specify a socks5 hostname proxy with -x, --proxy using a socks5h:// protocol prefix.

       --socks5 <host[:port]>
              Use  the specified SOCKS5 proxy - but resolve the host name locally. If the port number is not specified, it is assumed at port 1080.

              Since 7.21.7, this option is superfluous since you can specify a socks5 proxy with -x, --proxy  using a socks5:// protocol prefix.
```
So a possible combination can be:
```
youtube-dl -v --proxy socks5://127.0.0.1:9050 --external-downloader /usr/local/bin/curl --external-downloader-args "--proxy socks5h://127.0.0.1:9050" <the URL>
```
Note that youtube-dl sends DNS lookup requests to SOCKS proxies for ```socks5://``` protocol while curl not. curl uses another protocol name ```socks5h://``` for that.
