### ISSUE TITLE
How to download pluralsight video with subtitle from playlist?

### ISSUE THREAD

**Issue by Kriptonium** [rg3/youtube-dl#9681]
### What is the purpose of your *issue*?
- Feature request (request for a new functionality)
- Question

Hi there! Great work and thank you youtube-dl developer. May I ask, Can I download video from pluralsight with subtitle ? 
```
$ youtube-dl --version
2016.05.16
```

I able to grab video via playlist:
` $ youtube-dl --username user@email.com --password password --list-subs "https://app.pluralsight.com/library/courses/play-by-play-laravel-5-getting-started"`

It tried with `--embed-subs `and `--write-sub` parameter but no subtitle was found.

**Comment by 0x25101994** [comment]
I have same problem with download video subtitles from Pluralsight.

**Comment by Kriptonium** [comment]
@0x25101994 does mean you can download subtitle before then?

**Comment by 0x25101994** [comment]
I have just try it yesterday, but it's can't download subtitle.

**Comment by jmvtrinidad** [comment]
Its seems the code for Pluralsight is not getting the substitles.
Please update.

**Comment by hlrd93** [comment]
I have the same issue!

**Comment by leocaseiro** [comment]
I believe it's a TODO for pluralsight still: https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/pluralsight.py#L228

I've analysed the API uses the https://app.pluralsight.com/player/retrieve-url to get the captions in a json format:

Eq:
```javascript
{
    "urls": [...]
    "captions": [
    {
        "displayTimeOffset": 5,
        "text": "Hello, my name is Example"
    },
    {
        "displayTimeOffset": 7.5,
        "text": "and I'd like to welcome you to my course,"
    },
    {
        "displayTimeOffset": 9.5,
        "text": "\"Example Course\", from Pluralsight."
    }]
}
```

Perhaps it needs to be converted to srt or vtt to be downloaded in a better way.

**Comment by jmvtrinidad** [comment]
Hope someone here found this helpful.
I use this snippet to extract srt content.
```
var subtitleAsSRT = o.map(function(sub, i) {
    function time(ms) {
       return new Date(ms).toISOString().slice(11, -1).replace('.',',');
    }
    var nextIndex = i + 1 == o.length ? o.length - 1 : i + 1;
    return (i + 1) + "\r\n" + time(sub.displayTimeOffset* 1000) + " --> " + time(o[nextIndex ].time * 1000) + "\r\n" + sub.text;
}).join("\r\n\r\n");
```
Where `o` is the caption key in json file.
`subtitleAsSRT` contains the srt content.

**Comment by lrushl** [comment]
@jmvtrinidad, thank you for the nice and useful snippet.

I would like to note that original snipped contains a small typo in your code (there should be time(o[nextIndex ].displayTimeOffset * 1000)  instead of "time(o[nextIndex ].time * 1000)").

Please find updated code [here](https://gist.github.com/lrushl/062a1685810ac0631626bee730e3b5e0)

**Comment by jmvtrinidad** [comment]
Hi @dstfw, Is this included in current exe for windows? Thanks

**Comment by dstftw** [comment]
Not included.

**Comment by jmvtrinidad** [comment]
Thanks, will wait for exe update.

**Comment by Kriptonium** [comment]
I be waiting for exe update too!

**Comment by dstftw** [comment]
Here you go then.

**Comment by leocaseiro** [comment]
Thanks for this PR! Working perfect on MAC!

**Comment by wkk5** [comment]
Is there a way to only download the subtitles without doing the videos?  If so, would someone mind sharing the method for doing so with the exe?  Thanks!

**Comment by dstftw** [comment]
@wkk5 `--skip-download`.

**Comment by wkk5** [comment]
@dstftw Thx!

**Comment by ilovelibertyfreedom** [comment]
To download pluralsight video with subtitle from playlist, you may also try this easy method: http://www.allavsoft.com/how-to/pluralsight-downloader.html

**Comment by HossamEldinMahmoud** [comment]
how can i do that?

**Comment by Rainyroad** [comment]
@HossamEldinMahmoud 
OK. Go and download youtube-dl.exe
• If you want download video+subtitle, replace XXXX your video's URL :
> youtube-dl --username user@email.com --password password all-subs  "XXXX"

• If you want to download subtitles only use this code : 
>  youtube-dl --username user@email.com --password password all-subs  "XXXX" --skip-download

**Comment by PhanDuc** [comment]
Hi, 
My friend use idm to download pluralsight video but pluralsight block his account.
Did i get block if i used youtube-dl to download video from pluralsight ?
Many thanks !

**Comment by Rainyroad** [comment]
@PhanDuc 
Yeah, you can download pluralsight courses  using yt-dl easily without any problem. Personally I have downloaded over 15 javascript courses since 2 month ago and I sure that you have no problem.

**Comment by hailuavitinh** [comment]
Hi @Rainyroad ,

I use your guide, but I don't see any file . please see my image

![cap yt](https://cloud.githubusercontent.com/assets/9606903/24539175/70860bc4-1617-11e7-98a5-a66871b64592.PNG)

**Comment by HossamEldinMahmoud** [comment]
@Rainyroad I have tried this, but it gave me
>  ERROR: 'all-subs' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:all-subs" ) to search YouTube

**Comment by yan12125** [comment]
There's an option ```--all-subs```. I guess it's a typo.

**Comment by rubgithub** [comment]
How to change subtitle language?

**Comment by yan12125** [comment]
@rubgithub ```--list-subs``` and ```--sub-lang``` are useful here

**Comment by rubgithub** [comment]
@yan12125 Fist option --list-subs

Language formats
en       srt, json
[download] 

What does this mean? Only english avaiable?

**Comment by yan12125** [comment]
> Only english avaiable?

Yep. If there are more languages but youtube-dl miss them, feel free to open a new issue for that. Don't forget to attach an example URL.

**Comment by HossamEldinMahmoud** [comment]
@Rainyroad  I did these steps and finally should download it, but I couldn't find the files in the directory
![screenshot 2](https://user-images.githubusercontent.com/12272548/30539358-4fda103c-9c72-11e7-8cd9-1becf7b10a71.png)

**Comment by bitsnaps** [comment]
@HossamEldinMahmoud to actually download subs files use `--all-subs` because `--list-subs` will only list (show) them in console. --all-subs works with me (v2017.09.15).

**Comment by HossamEldinMahmoud** [comment]
@bitsnaps Thanks, it works,
but another message that appeared after many downloads

> WARNING: Unable to download captions JSON: HTTP Error 429: Too Many Requests
How to resume the downloads?

**Comment by bitsnaps** [comment]
@HossamEldinMahmoud looks like you're using multiple account from the same machine, or you're viewing videos and downloading meanwhile, there are some restrictions from such usage. No idea how to resume downloads, I'm not sure even if downloads are resumable! you may need to include " --sleep-interval 10" to mimic video watching.

**Comment by Perinban** [comment]
@Rainyroad Can we download all the subs at one time?

**Comment by dhiaelhak47** [comment]
@hossameldinmi same error here !

**Comment by mshwf** [comment]
![captu5re](https://user-images.githubusercontent.com/10940379/39395657-47a959a4-4ae1-11e8-9c9b-795753be0cc4.PNG)
My password ends with `&**`, and it seems it sees `& `as especial character:

>  Invalid script resourceFATAL ERROR: Could not locate script'XV' is not recognized as an internal or external command
