### ISSUE TITLE
Download to /dev/null ?

### ISSUE THREAD

**Issue by FlorentCoppint** [rg3/youtube-dl#9682]
Hi everyone,

I have a little issue using Youtube-dl and downloading to /dev/null (black hole) on Ubuntu.

I use last pip packaged version : youtube-dl --version
2016.05.30.2

I run : youtube-dl --no-part --no-cache-dir -o '/dev/null' https://www.youtube.com/watch?v=e_I4i4whdXY

And it wants to create "/dev/null.f264" !

ERROR: unable to open for writing: [Errno 13] Permission denied: '/dev/null.f264'

On Windows, it works fine using "-o NUL".

Any hint on that issue ?

Thank you.
Florent

**Comment by TRox1972** [comment]
Does `-o /dev/null/` work?

**Comment by FlorentCoppint** [comment]
@TRox1972 no, 'null' is a character special file, not a directory. So youtube-dl tries to create "/dev/null/.f264"

**Comment by dstftw** [comment]
Specify single file format, e.g. `-f best`.

**Comment by FlorentCoppint** [comment]
@dstftw That's it, thank you ;)

**Comment by FlorentCoppint** [comment]
@dstftw But I don't understand, according to manual "best" is the default choice for format selection, isn't it ?

**Comment by dstftw** [comment]
No. `-f bestvideo+bestaudio/best` is the default.

**Comment by radioxoma** [comment]
yt-dlp --no-cache-dir https://youtu.be/Sagg08DrO5U -o - > /dev/null
