### ISSUE TITLE
Can I use existing / predownloaded files?

### ISSUE THREAD

**Issue by ChaosNicro** [rg3/youtube-dl#9684]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.02**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### Description of your *issue*, suggested solution and other information

Due to the restrictions where I live, I cannot use youtube-dl to download my videos without receiving an error. I can however use a different method to download the components from youtube in a similar fashion.

My current situation is that I have an mp4 video component and an mp4a audio component.
I would now like to use youtube-dl to merge the two components into a complete video as well as manipulate the naming scheme for the files.

Thus my question is: "How can I use pre-downloaded components in post-processing?

I know that the usual information available on the web-page cannot be used but a "hacky" solution for the merge and basic features might be using any URL and naming the existing components identical to the download results. The download would then be skipped and the existing files would be used instead.

Even if this is the most simple solution, I would still like some guidance on how to do this and what to name the files.

Thank you very much in advance,
-Nicro

**Comment by dstftw** [comment]
With only video and audio component that is not possible. You'll need info JSON as well obtained with `--write-info-json`. Then on restricted machine you can run youtube-dl with `--load-info path/to/info.json` and it will do muxing.
Or just [use ffmpeg/avconv](http://stackoverflow.com/a/12943003/4749894).
You can also workaround restrictions using `--proxy`.
