### ISSUE TITLE
Add support for rockstargames.com

### ISSUE THREAD

**Issue by antdude** [rg3/youtube-dl#9687]
Example:
$ youtube-dl http://www.rockstargames.com/videos/video/11544
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.rockstargames.com/videos/video/11544']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 3.4.2 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.4
[debug] exe versions: ffmpeg 3.0.2-2, ffprobe 3.0.2-2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 11544: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 11544: Downloading webpage
[generic] 11544: Extracting information
ERROR: Unsupported URL: http://www.rockstargames.com/videos/video/11544
Traceback (most recent call last):
  File "/home/ant/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/home/ant/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2139, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.rockstargames.com/videos/video/11544

Thank you in advance. :)

**Comment by Hrxn** [comment]
Not really surprising, considering that rockstargames.com is not listed as a [supported site](https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md).

**Comment by dracony** [comment]
Added:
https://github.com/rg3/youtube-dl/pull/9737

**Comment by dstftw** [comment]
RockstarGames support has been added in youtube-dl 2016.06.14.
