### ISSUE TITLE
UnicodeEncodeError on --extractor-descriptions

### ISSUE THREAD

**Issue by pLeBlanc93** [rg3/youtube-dl#9689]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.03**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

---
```cmd
C:\>youtube-dl --verbose --extractor-descriptions
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose', '--extractor-descriptions']
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\build\youtube_dl\__init__.py", line 421, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\build\youtube_dl\__init__.py", line 120, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpjletvtok\build\youtube_dl\compat.py", line 473, in compat_print
  File "C:\Python\Python34\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-5: character maps to <undefined>
```
---

### Description of your *issue*, suggested solution and other information

`UnicodeEncodeError` when trying to view supported sites.
```cmd
C:\>youtube-dl --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--verbose']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.03
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-71329-g235589e
```
Edit:
I don't actually have Python `3.4.4` installed on my computer; only `2.7.1` and `3.5.1`

**Comment by Hrxn** [comment]
> I don't actually have Python 3.4.4 installed on my computer; only 2.7.1 and 3.5.1

That is the version of the bundled Python env integrated into `youtube-dl.exe`

**Comment by pLeBlanc93** [comment]
@dstftw @Hrxn thanks both!
