### ISSUE TITLE
proplem is --match-filter 

### ISSUE THREAD

**Issue by garilla22** [rg3/youtube-dl#9693]
How to check the key?I write to the console youtube-dl --match-filter "!key" and youtube-dl --match-filter !key and youtube-dl --match-filter "key" and no result.List to check it does not show! What to do?
![2016-06-04 12-55-58](https://cloud.githubusercontent.com/assets/19745988/15799005/e176e83a-2a5e-11e6-99e9-1265ec8b490c.png)

**Comment by dstftw** [comment]
What are you trying to achieve in the first place?

**Comment by garilla22** [comment]
> What are you trying to achieve in the first place?
Learn how to find out how to get a list of all the keys. Which in turn will download youtube with the keys indicated in the --match-filter in the command line bash

**Comment by dstftw** [comment]
[Available keys](https://github.com/rg3/youtube-dl#output-template). Read `--help` on how to use `--match-filter`.
