### ISSUE TITLE
Additional fields in json/template output

### ISSUE THREAD

**Issue by blha303** [rg3/youtube-dl#9695]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.06.03_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.03**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Is it possible to get more fields in the json output (and -o template) for whether something is Youtube Red and season/episode number if applicable? I've copied the header html from a Youtube Red video that includes both of those things, I would write a PR but I'm not sure how I would go about adding this functionality. The specific classes are: "yt-badge standalone-collection-red-badge-renderer-icon" for whether a video is Youtube Red, and "standalone-collection-badge-renderer-text" which contains the text "S1 • E1". Thank you.

https://gist.github.com/blha303/0b279649bcafc374a4d06b492a1cd912

**Comment by yan12125** [comment]
Could you provide the URL of the pasted HTML?

**Comment by blha303** [comment]
https://www.youtube.com/watch?v=2QyzjYqkj2U

**Comment by yan12125** [comment]
I guess ```'vip_only'``` is a good name to indicate this video is available to YouTube Red subscribers.
