### ISSUE TITLE
Twitch VOD not downloading correctly

### ISSUE THREAD

**Issue by realnc** [rg3/youtube-dl#9696]
Some twitch VODs don't seem to be working. It will download the end of another VOD instead of the actual one. Example:

https://www.twitch.tv/barbarossasc2/v/70197995

When viewing on Twitch, it works. When downloading with youtube-dl, it downloads the last 3 seconds of some different VOD.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by realnc** [comment]
Why so much red tape?

**Comment by dstftw** [comment]
Reproducible on what youtube-dl version? What OS? Python version? Which hls backend: ffmpeg, avconv, hls native? Which version of it?
There are no telepathists here. We can't fix bugs without context.

**Comment by phihag** [comment]
@realnc I've added an [FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#why-do-i-need-to-go-through-that-much-red-tape-when-filing-bugs) for your question.

**Comment by realnc** [comment]
On 04/06/16 23:49, Sergey M. wrote:
> Reproducible on what youtube-dl version? What OS? Python version? Which
> hls backend: ffmpeg, avconv, hls native? Which version of it?
> There are no telepathists here. We can't fix bugs without context.

youtube-dl https://www.twitch.tv/barbarossasc2/v/70197995

**Comment by Hrxn** [comment]
@realnc `-v`

**Comment by realnc** [comment]
On 05/06/16 07:40, H R X N wrote:
> @realnc <https://github.com/realnc> |-v|

So does the command download past 4 seconds or video or not?
