### ISSUE TITLE
How to merge downloaded videos automatically(was: 如何自动合并下载的视频)

### ISSUE THREAD

**Issue by Token713** [rg3/youtube-dl#9707]
我下载了ffmpeg和youtube-dl，用youtube-dl下载视频后都是分成很多块，如何使用ffmpeg将这些视频自动合并起来？
之前一直在用you-get，使用windows版本https://github.com/soimort/you-get/releases/tag/v0.4.424
，运行you-get.bat下载视频结束后会自动合并，我注意到该文件夹下附带了ffmpeg，我试着将you-get.exe替换为youtube-dl.exe但没有成功，有没有高手弄个bat啥的，可以自动合并，先谢谢了。

**Comment by yan12125** [comment]
Please use English so that others can understand the situation.

For your question: this feature is currently not yet implemented in youtube-dl. See #995.

**Comment by yan12125** [comment]
> 有没有高手弄个bat啥的，可以自动合并，先谢谢了。
> (Is there a batch script for automatic merging? Thanks.)

Here's one, for BiliBili videos: https://github.com/rg3/youtube-dl/issues/9660#issuecomment-223354445

**Comment by Token713** [comment]
@yan12125 Thanks in advance for translate my title.
I use youtube-dl download videos from IQIYI but couldn't merging them,I know a lot of people are using youtube-dl，i was just wondering how you merged the video.
Thank you again for your reply.
