### ISSUE TITLE
Add support for RMC Découverte

### ISSUE THREAD

**Issue by Anarky** [rg3/youtube-dl#9709]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

```
$ youtube-dl -v "http://rmcdecouverte.bfmtv.com/mediaplayer-replay/?id=14387"                                                   
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://rmcdecouverte.bfmtv.com/mediaplayer-replay/?id=14387']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 3.5.1 - Linux-4.4.3-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0, ffprobe 3.0, rtmpdump 2.4
[debug] Proxy map: {}
[generic] ?id=14387: Requesting header
WARNING: Falling back on generic information extractor.
[generic] ?id=14387: Downloading webpage
[generic] ?id=14387: Extracting information
[generic] Brightcove video detected.
[download] Downloading playlist: Replay RMC Découverte: Toutes les émissions sur BFMTV.com
[generic] playlist Replay RMC Découverte: Toutes les émissions sur BFMTV.com: Collected 1 video ids (downloading 1 of them)
[download] Downloading video 1 of 1
[brightcove:legacy] 4926338935001: Downloading webpage
ERROR: brightcove said: Attempt to access player from an unauthorized URL.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/brightcove.py", line 262, in _real_extract
    videoPlayer[0], query, referer=referer)
  File "/usr/lib/python3.5/site-packages/youtube_dl/extractor/brightcove.py", line 285, in _get_video_info
    'brightcove said: %s' % error_msg, expected=True)
youtube_dl.utils.ExtractorError: brightcove said: Attempt to access player from an unauthorized URL.
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://rmcdecouverte.bfmtv.com/mediaplayer-replay/?id=14387&title=VINTAGE%20GARAGE%3A%20OCCAZ%20A%20TOUS%20PRIX
- Single video: http://rmcdecouverte.bfmtv.com/mediaplayer-replay/?id=14387

---

Hello,

Please add RMC Découverte as a supported site.
You can find all the videos available here: http://rmcdecouverte.bfmtv.com/mediaplayer-replay/

**Comment by Anarky** [comment]
Hello yan12125,
I saw you added the geo-restricted tag; if you want me to compile and try a special branch I'll gladly help you.

**Comment by yan12125** [comment]
I'm unable to write new codes without being able to watch this video. Are you in France?

**Comment by Anarky** [comment]
Yes I'm in France; I tried to use the network monitor from Firefox and there is no media transmitted in clear. But it seems to use a player from brightcove.com, if it can help.

**Comment by typhoe** [comment]
Hi, I encounter the same problem...
Also from France...

[debug] Command-line args: ['-v', 'http://rmcdecouverte.bfmtv.com/mediaplayer-replay/?id=14960&title=TRIANGLE%20DES%20BERMUDES%3AL%27ENIGME%20REVELEE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.01
[debug] Python version 3.5.2 - Linux-4.7.2-1-MANJARO-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.1.2, ffprobe 3.1.2, rtmpdump 2.4
[debug] Proxy map: {}
<...>
ERROR: brightcove said: Attempt to access player from an unauthorized URL.
<...>
youtube_dl.utils.ExtractorError: brightcove said: Attempt to access player from an unauthorized URL.

Any way to help you investigate the problem like giving you an ssh access to test from a french ip?

Thank you!
