### ISSUE TITLE
doc update request

### ISSUE THREAD

**Issue by thpublic** [rg3/youtube-dl#9717]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.03**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x ] Other

---
Passing youtube-dl variables from Windows command prompt requires double %.  
eg %(title)s must be %%(title)s

DOS strips first % it receives as a variable before youtube-dl receives it. 
eg%(title)s becomes (title)s to youtube-dl, which is not a variable.

Docs mention this vaguely.  Please clarify.
"To specify percent literal in output template use %%."

**Comment by dstftw** [comment]
Passing arguments from command prompt **does not** require doubling %. The only place where it should be doubled is a batch file.
>To specify percent literal in output template use %%

This is unrelated at all.
