### ISSUE TITLE
Create Folder Pluralsigth

### ISSUE THREAD

**Issue by leonardosoares** [rg3/youtube-dl#9729]
How do I automatically create a folder to save videos in a course and rename the videos of pluralsigth?

For rename:
youtube-dl --verbose  --username --password --rate-limit 500K --sleep-interval 60 -o "%(autonumber)s - %(title)s.%(ext)s" 

How to create folder based on name of courses ?

**Comment by dstftw** [comment]
Read [FAQ](https://github.com/rg3/youtube-dl#output-template-examples).
