### ISSUE TITLE
ERROR: content too short

### ISSUE THREAD

**Issue by dubis** [rg3/youtube-dl#9732]
Hi 
I'm trying to download video which is not from youtube.com"" an d sometime I've got this error:
[download]  55.5% of 216.37MiB at 471.18KiB/s ETA 03:29ERROR: content too short (expected 226878918 bytes and served 125875281)
[1]+  Finish 1               youtube-dl -o "Pasión y poder capitulo 095.mp4" http://ab0.cdn.vizplay.org/v2/ce4dd8375c5776497866da61cf

As I'm under Linux, I 've to rerun the last comment and the download is restarting from the stop point. My youtube-dl version is 2016.06.03.
I thought to put youtbe-dl inside a script to monitor the error and finish the download automatically.
May be you could fix something in waiting.
Thanks for your help

**Comment by dstftw** [comment]
This is usually either a server-side issue of the hoster or an issue with your network connection. It has been discussed a lot, use search.

**Comment by dubis** [comment]
Thanks to answer 
I've no doubt on this server-side issue.  I didn't express myself well apologies but my main question is : Are there many restart of the download  on this error planed in the youtube-dl python script?

Thanks

**Comment by heil-stalin** [comment]
@dstftw Is there ever going to be a fix for this where it restarts the downloaded from a known point?
