### ISSUE TITLE
Set Download destination Directory?

### ISSUE THREAD

**Issue by leegold-zz** [rg3/youtube-dl#974]
Could anyone give me a simple example of how to set the download destination directory? I think the -o is used but I can not see how to do it. It would be for windows system, please keep the example simple. Thank you sincerely.

**Comment by rudolphos** [comment]
This doesn't work for me..

It somehow downloads everything with messed up file names.
 They look like this:

(title)s ((ext)s
(title)s ((ext)s.f136.part
(title)s ((ext)s.en.vtt

This is my script, saved as .bat.
```
set /p input="Input URL: "
youtube-dl -ci --write-thumbnail --sub-format ass/srt/best --write-auto-sub -f bestvideo+bestaudio/best --output "C:\Users\COMPUTER\Desktop\ytdl\%(uploader)s - %(title)s (%(id)s).%(ext)s" %input%
```

**Comment by Starsam80** [comment]
@rudolphos https://github.com/rg3/youtube-dl#output-template-and-windows-batch-files

**Comment by rudolphos** [comment]
Everything working now, percentage signs were the problem.

**Comment by CodeKraft** [comment]
What about linux? 

I have been searching for an example that simply allows you to select a folder to dump all downloads to, however there is this thing with weird strings.

All I want to do is to save to /home/computer/videos/downloaded and I am not interested in any names or things other than what the downloaded name is. I like it simple.

So do I add -o /home/computer/videos/downloaded 
to the command line to have all the files downloaded in the batch file in to that location?

**Comment by dstftw** [comment]
`-o` is **not a directory** it's an output template.
