### ISSUE TITLE
playlist_description not written to info.json

### ISSUE THREAD

**Issue by TRox1972** [rg3/youtube-dl#9748]
Correct me if I'm wrong, but the `playlist_description` doesn't seem to be written to the `.info.json` file when extracted, though `playlist_title` is.

**Comment by dstftw** [comment]
It's not supposed to. `playlist_title` is only present in info_dict in order to be used in output template and generally should not appear in resulting JSON.

**Comment by TRox1972** [comment]
@dstftw Is there any way to write the `playlist_description` to disk?

**Comment by dstftw** [comment]
As field of video `info_dict` - not possible.

**Comment by TRox1972** [comment]
Then what would be the point of it then; is there something else it is used for?
