### ISSUE TITLE
couldn't download video from lesports.com

### ISSUE THREAD

**Issue by Token713** [rg3/youtube-dl#9750]
couldn't download video from lesports.com,such as http://sports.le.com/video/25737697.html

> >youtube-dl http://sports.le.com/video/25737697.html
[LePlaylist] 25737697: Downloading webpage
[download] Downloading playlist: 美洲杯-梅西替补戴帽阿圭罗破门 阿根廷5-0晋级
[LePlaylist] playlist 美洲杯-梅西替补戴帽阿圭罗破门 阿根廷5-0晋级: Collected 0 v
ideo ids (downloading 0 of them)
[download] Finished downloading playlist: 美洲杯-梅西替补戴帽阿圭罗破门 阿根廷5-
0晋级

>

**Comment by yan12125** [comment]
Thanks for the report. Le Sports URLs will be correctly recognized in the next version.

**Comment by Token713** [comment]
@yan12125 
I download  latest version 06.12，and download the video again，but.......
My operating system is win7，What should I do next？

> >youtube-dl http://sports.le.com/video/25737697.html
[Le] 25737697: Downloading webpage
[Le] 25737697: Downloading playJson data
[Le] 25737697: Download JSON metadata for format 350
[Le] 25737697: Downloading m3u8 information for format 350
[Le] 25737697: Download JSON metadata for format 1000
[Le] 25737697: Downloading m3u8 information for format 1000
[Le] 25737697: Download JSON metadata for format 1300
[Le] 25737697: Downloading m3u8 information for format 1300
[Le] 25737697: Download JSON metadata for format 720p
[Le] 25737697: Downloading m3u8 information for format 720p
[download] Destination: 美洲杯-梅西替补戴帽阿圭罗破门 阿根廷5-0晋级-25737697.mp4

ERROR: m3u8 download detected but ffmpeg or avconv could not be found. Please in
stall one.

>

**Comment by yan12125** [comment]
Add ```--hls-prefer-native```. The ffmpeg approach is currently broken due to bug #8588.

**Comment by Kimi-Arthur** [comment]
Hi,

This bug seems to happen again. I'm using version 2016-09-27.

I tried `youtube-dl -v http://www.lesports.com/match/1023203003.html`, which is original url. Output:

> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: ['-v', 'http://www.lesports.com/match/1023203003.html']
> [debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
> [debug] youtube-dl version 2016.09.27
> [debug] Python version 3.5.0 - Windows-post2012Server-6.3.9600
> [debug] exe versions: none
> [debug] Proxy map: {}
> [generic] 1023203003: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] 1023203003: Downloading webpage
> [generic] 1023203003: Extracting information
> ERROR: Unsupported URL: http://www.lesports.com/match/1023203003.html
> Traceback (most recent call last):
>   File "c:\program files\python 3.5\lib\site-packages\youtube_dl\YoutubeDL.py", line 694, in extract_info
>     ie_result = ie.extract(url)
>   File "c:\program files\python 3.5\lib\site-packages\youtube_dl\extractor\common.py", line 355, in extract
>     return self._real_extract(url)
>   File "c:\program files\python 3.5\lib\site-packages\youtube_dl\extractor\generic.py", line 2424, in _real_extract
>     raise UnsupportedError(url)
> youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.lesports.com/match/1023203003.html


I then tried to use `youtube-dl -v http://sports.le.com/match/1023203003.html`, which is similar to the pattern in this issue. Output is similar to this bug,

> [debug] System config: []
> [debug] User config: []
> [debug] Command-line args: ['-v', 'http://sports.le.com/match/1023203003.html']
> [debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
> [debug] youtube-dl version 2016.09.27
> [debug] Python version 3.5.0 - Windows-post2012Server-6.3.9600
> [debug] exe versions: none
> [debug] Proxy map: {}
> [LePlaylist] 1023203003: Downloading webpage
> [download] Downloading playlist: 拜仁慕尼黑,罗斯托夫,拜仁慕尼黑VS罗斯托夫,欧洲冠军联赛,足球
> [LePlaylist] playlist 拜仁慕尼黑,罗斯托夫,拜仁慕尼黑VS罗斯托夫,欧洲冠军联赛,足球: Collected 0 video ids (downloading 0 of them)
> [download] Finished downloading playlist: 拜仁慕尼黑,罗斯托夫,拜仁慕尼黑VS罗斯托夫,欧洲冠军联赛,足球

**Comment by yan12125** [comment]
@Kimi-Arthur Could you open a new issue for that?
