### ISSUE TITLE
[Instagram] video - WARNING: unable to extract uploader id (Video_by_None-NA.mp4)

### ISSUE THREAD

**Issue by CiscoPress** [rg3/youtube-dl#9763]
I have a video Video_by_None-NA.mp4 name.

WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

thank you very much for awesome work

```
> youtube-dl --version
2016.06.03
> youtube-dl -v https://www.instagram.com/p/BGKd-sFLqqP/
[debug] System config: [u'--restrict-filenames', u'--ignore-errors', u'--prefer-ffmpeg', u'-n', u'-o', u'~/Desktop/%(title)s-%(resolution)s.%(ext)s', u'-f', u'bestvideo[ext!=webm]+bestaudio[ext!=webm]/best[ext!=webm]']
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.instagram.com/p/BGKd-sFLqqP/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.03
[debug] Python version 2.7.11 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {'http': 'http://localhost:8118', 'https': 'http://localhost:8118'}
[Instagram] BGKd-sFLqqP: Downloading webpage
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Invoking downloader on u'http://scontent-frt3-1.cdninstagram.com/t50.2886-16/13384053_1159944337390659_1741147553_n.mp4'
[download] /Users/john/Desktop/Video_by_None-NA.mp4 has already been downloaded
[download] 100% of 380.10KiB
```

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by akdascode** [comment]
As of 2022, if you follow the instructions, youtube-dl returns this message when you invoke it:

/usr/bin/env: ‘python’: No such file or directory

And now: how do I uninstall it?

**Comment by rautamiekka** [comment]
> As of 2022, if you follow the instructions, youtube-dl returns this message when you invoke it:
> 
> /usr/bin/env: ‘python’: No such file or directory
> 
> And now: how do I uninstall it?

**Don't hijack threads, make your own.**


Py3 should already make a symlink to redirect Py2 to 3, but you can make it yourself, or make an `alias` to use Py3: `alias yt='python3 /path/to/youtube-dl '`, or, best yet, use `pip` to install ytdl  (would recommend yt-dlp instead) from PyPi: `sudo pip install youtube-dl` (`sudo` recommended to protect ytdl by installing into a protected area).

Uninstalling depends on how you installed. If you simply used the `wget`/`curl` method, simply delete the file, `pip uninstall youtube-dl` for `pip`, and whatever package manager your system uses has its own syntax (if you're on Debian or Ubuntu or the like, NEVER install ytdl from the standard repo).
