### ISSUE TITLE
Violation of Protocol on VPS

### ISSUE THREAD

**Issue by BillyHalley** [rg3/youtube-dl#9765]
I installed youtube-dl on my VPS on Digital Ocean
when i run it i get this:
```
[youtube] Setting language
WARNING: unable to set language: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>
[youtube] HMsnSK81els: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>
```

I saw some old issues like this but i couldn't figure it out. Can someone help me?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
