### ISSUE TITLE
config default-search in a dict to feed it into ytdl?

### ISSUE THREAD

**Issue by AraHaan** [rg3/youtube-dl#9766]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.12*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.12**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Ok so, I have this python code.
```py
class YTDLLogger(object):
    def debug(self, msg):
        pass

    def warning(self, msg):
        pass

    def error(self, msg):
        pass

# youtube_dl options
 ytdlo = {'quiet': True, 'no_warnings': True, 'ignoreerrors': True, 'logger': YTDLLogger(), 'default-search': "ytdlsearch"}
```
And when I try to search using a command in my Discord Bot. (yes I use Rapptz's Discord.py which uses ytdl for playing thigns from youtube in Discord's voice channels.)

But instead this is generated

```
ERROR: 'SIM Keygen PSXGamerPro1' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:SIM Keygen PSXGamerPro1" ) to search YouTube
```
I am not sure what is wrong. Could it be that ytdl ignored the option I put in the dict?

**Comment by dstftw** [comment]
It's `default_search` not `default-search`.

**Comment by AraHaan** [comment]
ah ty

**Comment by AraHaan** [comment]
sure it is in voice.py to decoraterbot-org / DecoraterBot-cogs. forgot the actual url though and cant find it much on my iphone.
