### ISSUE TITLE
Request: Add --write-comments option

### ISSUE THREAD

**Issue by TRox1972** [rg3/youtube-dl#9771]
Comments, if available, are currently written to the `.info.json`-file, but, especially for cases with large amounts of comments, it would be useful to store them in a separate file.

**Comment by dstftw** [comment]
I don't see much difference. What is the concrete use case for separate file for comments?

**Comment by TRox1972** [comment]
E.g. when doing analysis of comments, it would be simpler to have them stored in a separate file instead of accessing them from the `.info.json`. I agree that it wouldn't be much of a difference; it is still easy to get the comments from the `.info.json` file. But with respects to sorting, it would be more practical, much like `--write-description`.

**Comment by dstftw** [comment]
For analysis of comments using `.info.json` is just fine. `--write-description` has concrete use case of using in 3rdparty software that support `.description` files.

**Comment by TRox1972** [comment]
@dstftw OK. Thanks for answering
