### ISSUE TITLE
Problems with requests

### ISSUE THREAD

**Issue by edelin3** [rg3/youtube-dl#9775]
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at /root/bot2/cogs/audio.py:1604> exception=AttributeError("'NoneType' object has no attribute 'duration'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/root/bot2/cogs/audio.py", line 1635, in queue_manager
    song = await self._play(sid, url)
  File "/root/bot2/cogs/audio.py", line 680, in _play
    song = await self._guarantee_downloaded(server, url)
  File "/root/bot2/cogs/audio.py", line 484, in _guarantee_downloaded
    self.downloaders[server.id].duration_check()
  File "/root/bot2/cogs/audio.py", line 206, in duration_check
    log.debug("duration {} for songid {}".format(self.song.duration,
AttributeError: 'NoneType' object has no attribute 'duration'

**Comment by TRox1972** [comment]
Please post full output with the `-v` option.

**Comment by dstftw** [comment]
1. https://github.com/rg3/youtube-dl#http-error-429-too-many-requests-or-402-payment-required
2. #5138.
