### ISSUE TITLE
doesn't seem to call external downloader (aria2c) anymore

### ISSUE THREAD

**Issue by sheepdestroyer** [rg3/youtube-dl#9779]
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.14**

- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
---

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ $ youtube-dl --external-downloader aria2c --external-downloader-args '--min-split-size=1M --max-connection-per-server=16 --split=16 --max-concurrent-downloads=16' -v https://www.twitch.tv/xbox/v/72220716
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--external-downloader', u'aria2c', u'--external-downloader-args', u'--min-split-size=1M --max-connection-per-server=16 --split=16 --max-concurrent-downloads=16', u'-v', u'https://www.twitch.tv/xbox/v/72220716']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.14
[debug] Python version 2.7.11 - Linux-4.6.0+-x86_64-with-fedora-24-Twenty_Four
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1, rtmpdump 2.4
[debug] Proxy map: {}
[twitch:vod] 72220716: Downloading vod info JSON
[twitch:vod] 72220716: Downloading vod access token
[twitch:vod] 72220716: Downloading m3u8 information
[debug] Invoking downloader on u'http://vod.ak.hls.ttvnw.net/v1/AUTH_system/vods_3012/xbox_21831886816_469072441/chunked/index-dvr.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3212
[download] Destination: Xbox E3 2016 Media Briefing-v72220716.mp4
[download]   8.1% of ~2.81GiB at 235.43KiB/s ETA 11:42^C
ERROR: Interrupted by user
[sheepdestroyer@sheepora mozilla-central] $ 

```

### Description of your *issue*, suggested solution and other information

When using the arguments as noted, I usually had 16 dl streams through aria2. Now it seems the dl just goes through youtube-dl?

**Comment by yan12125** [comment]
Seems aria2 does not support HLS.

```
$ aria2c http://vod.ak.hls.ttvnw.net/v1/AUTH_system/vods_3012/xbox_21831886816_469072441/chunked/index-dvr.m3u8

06/14 11:16:24 [NOTICE] Download complete: /home/yen/Executables/Multimedia/youtube-dl/index-dvr.m3u8

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
8c025f|OK  |   547KiB/s|/home/yen/Executables/Multimedia/youtube-dl/index-dvr.m3u8

Status Legend:
(OK):download completed.
```

And from https://aria2.github.io/:

> It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink.

**Comment by sergeevabc** [comment]
@sheepdestroyer, there is [feature request][1] to make HLS possible in Aria2.

[1]: https://github.com/aria2/aria2/issues/1271
