### ISSUE TITLE
Download page flagged as deceptive site

### ISSUE THREAD

**Issue by tim-k** [rg3/youtube-dl#9780]
https://rg3.github.io/youtube-dl/download.html is flagged as a deceptive site by Google's Safe Browsing service.

> Deceptive site ahead
> 
> Attackers on rg3.github.io may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards).
> 
> Google Safe Browsing recently detected phishing on rg3.github.io. Phishing sites pretend to be other websites to trick you.
> 
> You can report a [detection problem](https://www.google.com/safebrowsing/report_error/?hl=en-US) or, if you understand the risks to your security, visit this unsafe site.

**Comment by yan12125** [comment]
Many thanks. Reported to Google.

**Comment by dstftw** [comment]
Seems to be unblocked now.

**Comment by slishnevsky** [comment]
Problem remains

**Comment by yan12125** [comment]
It works fine. Do you use updated browser? And could you attach a screenshot?
