### ISSUE TITLE
openload.io extractor not working

### ISSUE THREAD

**Issue by Mahmoud-Mardeni** [rg3/youtube-dl#9783]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```

C:\>youtube-dl --get-url --verbose  https://openload.co/embed/kUEfGclsU9o/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--get-url', '--verbose', 'https://openload.co/embed
/kUEfGclsU9o/']
[debug] Encodings: locale cp1256, fs mbcs, out cp1252, pref cp1256
[debug] youtube-dl version 2016.06.14
[debug] Python version 3.4.4 - Windows-8.1-6.3.9600
[debug] exe versions: none
[debug] Proxy map: {}
ERROR: Unable to extract video URL; please report this issue on https://yt-dl.or
g/bug . Make sure you are using the latest version; type  youtube-dl -U  to upda
te. Be sure to call youtube-dl with the --verbose flag and include its complete
output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\common.py", line 342, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\openload.py", line 112, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\bu
ild\youtube_dl\extractor\common.py", line 645, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video URL; please report
this issue on https://yt-dl.org/bug . Make sure you are using the latest version
; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose
flag and include its complete output.

```

**Comment by yan12125** [comment]
Duplicate #9706. Openload has deployed enhanced encryption and there's current no good solution to it.
