### ISSUE TITLE
[Dailymotion] Support password-protected videso (was: Dailymotion video 'title' extraction error)

### ISSUE THREAD

**Issue by rnoremacc** [rg3/youtube-dl#9789]
## Please follow the guide below
- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _issue_ (like that [x])
- Use _Preview_ tab to see how your issue will actually look like

---
### Make sure you are using the _latest_ version: run `youtube-dl --version` and ensure your version is _2016.06.14_. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.14**
### Before submitting an _issue_ make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
### What is the purpose of your _issue_?
- [x] Bug report (encountered problems with youtube-dl)

---
### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your _issue_

---
### If the purpose of this _issue_ is a _bug report_, _site support request_ or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
chris@zbox3:~$ youtube-dl -i -k --write-sub --sub-lang en --sub-format srt -u givemebaozi -p kyss http://www.dailymotion.com/video/x4gh4bl_eng-sub-yandai-byway-ep5-p2-2_fun --verbose
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-i', u'-k', u'--write-sub', u'--sub-lang', u'en', u'--sub-format', u'srt', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'http://www.dailymotion.com/video/x4gh4bl_eng-sub-yandai-byway-ep5-p2-2_fun', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.14
[debug] Python version 2.7.11+ - Linux-4.4.0-24-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 2.8.6-1ubuntu2, avprobe 2.8.6-1ubuntu2, ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[dailymotion] x4gh4bl: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 342, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 145, in _real_extract
    self._check_error(metadata)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 277, in _check_error
    '%s said: %s' % (self.IE_NAME, info['error']['title']), expected=True)
KeyError: u'title'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 348, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---

---
### Description of your _issue_, suggested solution and other information

Explanation of your _issue_ in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your _issue_ required an account credentials please provide them or explain how one can obtain them.

The Problem is reported as "ERROR: An extractor error has occurred."
User and password are as shown in the command line.
The video plays through the dailymotion website OK.

Thank you for looking at this problem.
Chris.

**Comment by yan12125** [comment]
Password-protected videos on Dailymotion are not supported yet.

**Comment by rnoremacc** [comment]
Hi,
I have user-name and password protected files that youtube-dl downloaded from Dailymotion in April 2015 still on my hard drive. This is why I didn't expect any problem downloading this file.
Has Dailymotion changed their setup so that youtube-dl is no longer able to access these sorts of files?
Regards,
Chris.

**Comment by yan12125** [comment]
> Has Dailymotion changed their setup

I'm not sure. Maybe you're right.

**Comment by Kaos-Industries** [comment]
Thanks for redirecting me to this issue, I understand the problem now. Is there any estimation of when or indeed whether password-protected Dailymotion videos are expected to be supported?
