### ISSUE TITLE
Hangs after first song of a youtube Mix

### ISSUE THREAD

**Issue by Rafkevs** [rg3/youtube-dl#9791]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.14**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

Youtube-dl stops/hangs on deleting files after the first song of a youtube mix without an error

$ [debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-x', u'-v', u'https://www.youtube.com/watch?v=iTwmVasMxCM']
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2016.06.14
[debug] Python version 2.7.6 - Linux-3.19.0-25-generic-x86_64-with-Ubuntu-14.04-trusty
[debug] exe versions: avconv 11.3-6, avprobe 11.3-6, ffmpeg 2.4.3-1ubuntu1, ffprobe 2.4.3-1ubuntu1
[debug] Proxy map: {}
[youtube] iTwmVasMxCM: Downloading webpage
[youtube] iTwmVasMxCM: Downloading video info webpage
[youtube] iTwmVasMxCM: Extracting video information
[youtube] {22} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {43} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {18} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {5} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {36} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {17} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {137} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {248} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {136} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {247} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {135} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {244} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {134} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {243} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {133} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {242} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {160} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {278} signature length 39.41, html5 player en_US-vfl9bYNJa
[youtube] iTwmVasMxCM: Downloading player https://s.ytimg.com/yts/jsbin/player-en_US-vfl9bYNJa/base.js
[youtube] {140} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {171} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {249} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {250} signature length 41.41, html5 player en_US-vfl9bYNJa
[youtube] {251} signature length 41.41, html5 player en_US-vfl9bYNJa
[debug] Invoking downloader on u'https://r7---sn-uxaxoxu-cg06.googlevideo.com/videoplayback?expire=1466010024&itag=251&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&fexp=9414823%2C9416126%2C9416891%2C9419451%2C9422596%2C9428398%2C9428742%2C9431012%2C9432683%2C9433096%2C9433223%2C9433720%2C9433946%2C9434805%2C9435527%2C9435876%2C9435991%2C9436302%2C9436814%2C9436958%2C9437066%2C9437227%2C9437553%2C9437666%2C9438558%2C9438564&pcm2cms=yes&source=youtube&keepalive=yes&mime=audio%2Fwebm&clen=4050856&lmt=1449593976467756&ms=au&mt=1465988069&mv=m&dur=234.481&mm=31&mn=sn-uxaxoxu-cg06&gir=yes&id=o-AKcNoAbm4BrJgbvs-46OQcbREosEIPfnRjdeT9zfD3xq&upn=XCy3Zz2NvmE&ipbits=0&key=yt6&ip=2a02%3A1810%3A8401%3Af100%3Afc25%3A2588%3Ad8cf%3A7ef&sver=3&requiressl=yes&pl=33&initcwndbps=2033750&signature=95DD2176A14B9D4B9A42F7B05E9CA26D2A6F1472.9F003C1AE0E78FBABA54AEA186BBDDF75A492C2F&ratebypass=yes'
[download] Destination: Lost Frequencies - Are You With Me (Kungs Remix)-iTwmVasMxCM.webm
[download] 100% of 3.86MiB in 00:01
[debug] avconv command line: avprobe -show_streams 'file:Lost Frequencies - Are You With Me (Kungs Remix)-iTwmVasMxCM.webm'
[ffmpeg] Destination: Lost Frequencies - Are You With Me (Kungs Remix)-iTwmVasMxCM.opus
[debug] ffmpeg command line: avconv -y -i 'file:Lost Frequencies - Are You With Me (Kungs Remix)-iTwmVasMxCM.webm' -vn -acodec copy 'file:Lost Frequencies - Are You With Me (Kungs Remix)-iTwmVasMxCM.opus'
Deleting original file Lost Frequencies - Are You With Me (Kungs Remix)-iTwmVasMxCM.webm (pass -k to keep)

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):

- Playlist: https://www.youtube.com/watch?v=iTwmVasMxCM&list=PLFkBv85YwPKtTozgU0Tfkt91e0DRVEjYy

---

### Description of your *issue*, suggested solution and other information

Youtube-dl stops/hangs on deleting files after the first song of a youtube mix without an error

**Comment by yan12125** [comment]
Seems you have forgotten the quotes. See [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)

**Comment by Rafkevs** [comment]
Doh, stupid. Fixed. Thanks!
