### ISSUE TITLE
How to extract only the  the URL of the video file ?

### ISSUE THREAD

**Issue by meiry** [rg3/youtube-dl#9792]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.14**

### Before submitting an *issue* make sure you have:
- [ x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.06.14
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

Question : 
How can i  extract the URL of the video file using API ?
Im using youtube-dl as embedded lib i couldn't not find any API for this .
i know it can be done as it shown here : 
http://askubuntu.com/questions/514578/getting-url-of-youtube-video-with-youtube-dl-is-slow-without-downloading-vide

**Comment by yan12125** [comment]
```extract_info()``` should work.

**Comment by meiry** [comment]
Can i execute it from code ? i dont see it as public API ...

**Comment by yan12125** [comment]
There's no comprehensive list of public APIs yet. Our convention is: in class ```YoutubeDL```, methods starting with underscores are considered private, and others are public.

**Comment by meiry** [comment]
Thanks! ( i just learning ) 
1. so how can i disable stdout printing  ? 
2. im running the lib from tornado server , and which downloading list i got error that looks like this : 
```
 File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 848, in process_ie_result
    extra_info=extra)
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 740, in process_ie_result
    extra_info=extra_info)
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 691, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 550, in report_error
    self.trouble(error_message, tb)
  File "C:\Python27\lib\site-packages\youtube_dl\YoutubeDL.py", line 520, in trouble
    raise DownloadError(message, exc_info)
DownloadError: ERROR: DvjYIrsqE2Y: YouTube said: "The Sisters of Mercy - ..."
The YouTube account associated with this video has been terminated due to multiple third-party notifications of copyright infringement.
ERROR:tornado.access:500 GET / (::1) 28596.00ms
```


i understand that i can't extract the data from this Youtube file ...but how i can NOT stop on error 
and just continue the processing ?

**Comment by yan12125** [comment]
1. pass ```'quiet': True``` when creating the ```YoutubeDL``` object
2. Currently errors are always reported at Python level. Use try and catch to capture errors.

**Comment by meiry** [comment]
Thanks 
i can see in the code that i can somehow define continue on error : 
```
class DownloadError(Exception):
    """Download Error exception.

    This exception may be thrown by FileDownloader objects if they are not
    configured to continue on errors. They will contain the appropriate
    error message.
    """

how can i trigger this option in my code ?
```

**Comment by yan12125** [comment]
I was wrong - with ```'ignoreerrors': True``` exceptions are no longer raised.

**Comment by meiry** [comment]
where i set it in this simple code : 
```
 ydl = youtube_dl.YoutubeDL({'outtmpl': '%(id)s%(ext)s'})

        with ydl:
            result = ydl.extract_info(
            'https://www.youtube.com/watch?v=IuezNswtRfo&list=PLCxxxxx925A9',
            download=False # We just want to extract the info
        )
```

**Comment by yan12125** [comment]
In the constructor. For example:
```Python
youtube_dl.YoutubeDL({'outtmpl': '%(id)s%(ext)s', 'ignoreerrors': True})
```

**Comment by meiry** [comment]
Thanks!
