### ISSUE TITLE
Cannot download Akamai video from: sportschau.de

### ISSUE THREAD

**Issue by flavenne** [rg3/youtube-dl#9799]
Hello,

When trying to download Akamai video from [sportschau.de](http://www.sportschau.de/uefaeuro2016/videos/video-dfb-team-geht-gut-gelaunt-ins-spiel-gegen-polen-100.html) I get this error:

> [Sportschau] -dfb-team-geht-gut-gelaunt-ins-spiel-gegen-polen-100: Downloading webpage
> [Sportschau] -dfb-team-geht-gut-gelaunt-ins-spiel-gegen-polen-100: Downloading media JSON
> ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug 

This video is from a playlist (m3u8) and restricted to Germany.
I already use Germany VPN to download this, but it still doesn't work.
Help?

**Comment by yan12125** [comment]
Please post the full log of the following command:
```
youtube-dl -v <the URL>
```

**Comment by flavenne** [comment]
youtube-dl -v http://www.sportschau.de/uefaeuro2016/videos/video-dfb-team-geht-gut-gelaunt-ins-spiel-gegen-polen-100.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.sportschau.de/uefaeuro2016/videos/video-dfb-team-geht-gut-gelaunt-ins-spiel-gegen-polen-100.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.21.2
[debug] Python version 2.7.10 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[Sportschau] -dfb-team-geht-gut-gelaunt-ins-spiel-gegen-polen-100: Downloading webpage
[Sportschau] -dfb-team-geht-gut-gelaunt-ins-spiel-gegen-polen-100: Downloading media JSON
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 388, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1946, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by yan12125** [comment]
Thanks for the report. Sportschau will be fixed in the next version.
