### ISSUE TITLE
Fix MTV and add MTV.ca

### ISSUE THREAD

**Issue by NoWay1911** [rg3/youtube-dl#9808]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.14*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.14**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
// MTV.ca //
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.mtv.ca/shows/the-shannara-chronicles/video/season-1/episode-1-2-chosen/782107/0/0']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.06.14
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[generic] 0: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 0: Downloading webpage
[generic] 0: Extracting information
ERROR: Unsupported URL: http://www.mtv.ca/shows/the-shannara-chronicles/video/season-1/episode-1-2-chosen/782107/0/0
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\build\youtube_dl\extractor\common.py", line 342, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\build\youtube_dl\extractor\generic.py", line 2140, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.mtv.ca/shows/the-shannara-chronicles/video/season-1/episode-1-2-chosen/782107/0/0

// MTV.com //
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.mtv.com/full-episodes/boj31q/are-you-the-one-perfect-match-at-first-sight-season-4-ep-401', '-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.06.14
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[generic] are-you-the-one-perfect-match-at-first-sight-season-4-ep-401: Requesting header
WARNING: Falling back on generic information extractor.
[generic] are-you-the-one-perfect-match-at-first-sight-season-4-ep-401: Downloading webpage
[generic] are-you-the-one-perfect-match-at-first-sight-season-4-ep-401: Extracting information
ERROR: Unsupported URL: http://www.mtv.com/full-episodes/boj31q/are-you-the-one-perfect-match-at-first-sight-season-4-ep-401
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\build\youtube_dl\extractor\common.py", line 342, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpa3ey2lj9\build\youtube_dl\extractor\generic.py", line 2140, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.mtv.com/full-episodes/boj31q/are-you-the-one-perfect-match-at-first-sight-season-4-ep-401
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

**Comment by dollabi11z** [comment]
Any progress on this I truly need mtv.ca to be fixed
