### ISSUE TITLE
download video files from SRF Player (state-run Swiss Radio and Television)

### ISSUE THREAD

**Issue by Lehrerin** [rg3/youtube-dl#981]
example videos:

http://www.srf.ch/player/tv/10vor10/video/snowden-beantragt-asyl-in-russland?id=28e1a57d-5b76-4399-8ab3-9097f071e6c5

http://www.srf.ch/player/tv/tagesschau/video/edward-snowden-lehnt-russisches-asyl-angebot-ab?id=832b156e-adf9-44ed-b346-ca35c1076eec

http://www.srf.ch/player/tv/schweiz-aktuell/video/christian-wanner-tritt-von-der-politischen-buehne-ab?id=793ce2ff-e35e-4638-a657-72ba51688cfd

**Comment by yan12125** [comment]
I've implemented the extractor. For the video mentioned by @yasoob
```
http://www.srf.ch/play/tv/top-gear/video/jaguar-xk120-shadow-und-tornado-dampflokomotive?id=677f5829-e473-4823-ac83-a1087fe97faa
```
I can't play the video in the browser but I can download it with
youtube-dl. The error message in the browser is "Aus rechtlichen Gründen stand dieses Video nur innerhalb eines bestimmten Zeitraums zur Verfügung". I can't find out where this message comes from, so I just ignore it. Note I'm in Taiwan, GMT+8

**Comment by MaEtUgR** [comment]
> "Aus rechtlichen Gründen stand dieses Video nur innerhalb eines bestimmten Zeitraums zur Verfügung"
just means you are officially not able to watch it anymore because it's too old now.

Thank you for integrating this feature! in some rare cases it's so useful to archive a video for private use.

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

**Comment by idotter** [comment]
Hey, 
Tried to download some audio examples like e.g. https://www.srf.ch/play/radio/popupaudioplayer?id=53ec7fd0-ed59-4ac5-98aa-4ca4bba85ca8  youtube-dl tells me "Unsupported URL" 
Any chance to have this working?

**Comment by jhuesser** [comment]
Sorry to dig out an old thread, but had the same problem. @idotter This is the URL of an embeded player. You need to click the "Play SRF" button on the lower right corner to get the actual URL. for your audio sample it's `https://www.srf.ch/play/radio/audio-srf-1/audio/lukas-gerber-wo-mir-als-buebe-emal?id=53ec7fd0-ed59-4ac5-98aa-4ca4bba85ca8&station=69e8ac16-4327-4af4-b873-fd5cd6e895a7`

It worked fine for me:
```
youtube-dl.exe "https://www.srf.ch/play/radio/audio-srf-1/audio/lukas-gerber-wo-mir-als-buebe-emal?id=53ec7fd0-ed59-4ac5-98aa-4ca4bba85ca8&station=69e8ac16-4327-4af4-b873-fd5cd6e895a7"
[SRGSSR] 53ec7fd0-ed59-4ac5-98aa-4ca4bba85ca8: Downloading JSON metadata
[download] Destination: Lukas Gerber - «Wo mir als Buebe emal»-53ec7fd0-ed59-4ac5-98aa-4ca4bba85ca8.mp3
[download] 100% of 1.40MiB in 00:00
```
