### ISSUE TITLE
[Site support request] javfor.me [Adult Content]

### ISSUE THREAD

**Issue by HASJ** [rg3/youtube-dl#9811]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.16**
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Site support request (request for adding support for a new site)

---

http://javfor.me/93618.html
http://javfor.me/93614.html

The actual download button doesn't work so I download using IDM video grabber when watching online.
The site uses Flash for the video player and simple (I assume) javascript to switch between video streams.
Most videos are split in three parts (second link is split into two) that could form a playlist and they are mirrored in three servers each with different quality and server speed.
Page title ```$(title)s```, Movie ID ```$(id)s```, Category and Actress ```$(uploader)s``` could serve as info for the downloaded filenames

**Comment by yan12125** [comment]
This movie is copyrighted. Has javfor.me bought redistribution rights from its copyright holder(s)?

**Comment by HASJ** [comment]
Most likely not.
