### ISSUE TITLE
Time to stop describing youtube-dl as "small"?

### ISSUE THREAD

**Issue by rrthomas** [rg3/youtube-dl#9814]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.16*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.16**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

---

### Description of your *issue*, suggested solution and other information

Is it time to stop describing youtube-dl as "small"? I counted the current version with cloc, as installed from the webupd8 PPA, and it comes to a shade under 80kLOC in just under 650 files. I don't think that qualifies as small, either in lines of code or in complexity of installation (e.g. cloc itself is about 10kLOC, but ships as a single Perl file, so it's sort of small).

Suggested change: remove the word "small" from the project description on GitHub, from https://rg3.github.io/youtube-dl/ and from any other corresponding places. I note that the README in particular does not seem (any more?) to describe youtube-dl as "small".

youtube-dl is great; thanks for working on it!

**Comment by yan12125** [comment]
Good idea!

**Comment by TRox1972** [comment]
Good point. On http://rg3.github.io/youtube-dl/ it says that

> *youtube-dl* is a small command-line program to download videos from YouTube.com and a few more sites.

Maybe change 'few' to 'many' or something.

**Comment by RingoTheDog** [comment]
change **small** to **awesome**  ;-)
