### ISSUE TITLE
[vk] Can't download videos marked as adult

### ISSUE THREAD

**Issue by Dilidonka** [rg3/youtube-dl#9822]
Can't download videos from vk.com marked as adult. 
---

$ youtube-dl -v "https://vk.com/video_ext.php?oid=-62344632&id=456240277&hash=9be8791d5389012d&__ref=vk.api&api_hash=14662613337ae028bc61"                
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://vk.com/video_ext.php?oid=-62344632&id=456240277&hash=9be8791d5389012d&__ref=vk.api&api_hash=14662613337ae028bc61']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.18.1
[debug] Python version 2.7.8 - Linux-3.16.0-31-generic-x86_64-with-Ubuntu-14.10-utopic
[debug] exe versions: none
[debug] Proxy map: {}
[vk] -62344632_456240277: Downloading webpage
ERROR: This video was marked as adult.
Embedding adult videos on external sites is prohibited.
...
<end of log>

**Comment by dstftw** [comment]
1. You should use direct link (https://vk.com/video-62344632_456240277) not embedded.
2. You must either provide credentials (`-u`/`-p`) or use authenticated cookie.
