### ISSUE TITLE
VPN users  face the reset problem....

### ISSUE THREAD

**Issue by songbaoqiang** [rg3/youtube-dl#9834]
$ youtube-dl http://www.cbsnews.com/videos/lost-in-the-bermuda-triangle-2/
[CBSNews] lost-in-the-bermuda-triangle-2: Downloading webpage
ERROR: Unable to download webpage: [Errno 54] Connection reset by peer (caused by error(54, 'Connection reset by peer')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
Please post the output of the following command:
```
$ youtube-dl -v http://www.cbsnews.com/videos/lost-in-the-bermuda-triangle-2/
```
And which VPN software are you using?

**Comment by songbaoqiang** [comment]
google lantern

**Comment by songbaoqiang** [comment]
youtube-dl -v http://www.cbsnews.com/videos/lost-in-the-bermuda-triangle-2/

[debug] System config: []

[debug] User config: []

[debug] Command-line args: [u'-v', u'
http://www.cbsnews.com/videos/lost-in-the-bermuda-triangle-2/']

[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8

[debug] youtube-dl version 2016.03.06

[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit

[debug] exe versions: ffmpeg 3.0, ffprobe 3.0, rtmpdump 2.4

[debug] Proxy map: {}

[CBSNews] lost-in-the-bermuda-triangle-2: Downloading webpage

ERROR: Unable to download webpage: [Errno 54] Connection reset by peer
(caused by error(54, 'Connection reset by peer')); please report this issue
on https://yt-dl.org/bug . Make sure you are using the latest version;
type  youtube-dl -U  to update. Be sure to call youtube-dl with the
--verbose flag and include its complete output.

  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line
358, in _request_webpage

    return self._downloader.urlopen(url_or_request)

  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1931, in
urlopen

    return self._opener.open(req, timeout=self._socket_timeout)

  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py",
line 431, in open

    response = self._open(req, data)

  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py",
line 449, in _open

    '_open', req)

  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py",
line 409, in _call_chain

    result = func(*args)

  File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 719, in
http_open

    req)

  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py",
line 1200, in do_open

    r = h.getresponse(buffering=True)

  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py",
line 1132, in getresponse

    response.begin()

  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py",
line 453, in begin

    version, status, reason = self._read_status()

  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py",
line 409, in _read_status

    line = self.fp.readline(_MAXLINE + 1)

  File
"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py",
line 480, in readline

    data = self._sock.recv(self._rbufsize)

**Comment by yan12125** [comment]
Seems Latern is a HTTP proxy. Could you add ```--proxy http://ip:port``` and try again?

**Comment by songbaoqiang** [comment]
http://ip:port  ？？ which ip？ which port？

**Comment by yan12125** [comment]
127.0.0.1:8787, according to some random lantern tutorials.

**Comment by songbaoqiang** [comment]
it's ok now  add --proxy http://ip:port
