### ISSUE TITLE
Unable to download playlist

### ISSUE THREAD

**Issue by Angel1015** [rg3/youtube-dl#9835]
Using 2016.06.19.1 build and trying to download playlist from lynda.com using organizational login.
`youtube-dl.exe --cookies cookies.txt https://www.lynda.com/Test.html`
When trying to download playlists, getting the following error. 
ERROR: 42834: Failed to parse JSON  (caused by ValueError('Expecting property name enclosed in double quotes: line 1 column 3 (char 2)',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Any suggestions?

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
