### ISSUE TITLE
How to use "--playlist-end" and "--playlist-items" values inside extractor?

### ISSUE THREAD

**Issue by TRox1972** [rg3/youtube-dl#9846]
Some extractors, e.g. `VineUser`, are built to always collect all videos from a playlist, not checking if the number of collected videos is larger than the `--playlist-end` value (if passed) or the largest element in `--playlist-items`. When downloading playlists via other extractors, like YouTube, however, these values are checked and the playlist extraction stops if the number of collected videos has surpassed one of the values.

Can anyone explain to me how I can implement such a feature in an extractor?

**Comment by yan12125** [comment]
Use ```PagedList```s.
