### ISSUE TITLE
I only want to download the subtitle,how to do it?

### ISSUE THREAD

**Issue by N1CEyk** [rg3/youtube-dl#9847]
youtube-dl.exe --subs-lang en,cn-TW https://www.youtube.com/watch?v=rSQNi5sAwuc&gl=CA
I try to download subs like this,but it's wrong I don't know why

**Comment by yan12125** [comment]
Add ```--write-sub``` besides ```--sub-lang```.

**Comment by N1CEyk** [comment]
In fact ,I only want to download the subtitle file!Can it come true?

2016-06-21 19:44 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
One more option. For example:
```
youtube-dl.exe --write-sub --sub-lang en,cn-TW --skip-download https://www.youtube.com/watch?v=rSQNi5sAwuc&gl=CA
```
The option ```--skip-download``` skips downloading videos while other assets (subtitles, thumbnails, etc.) are still downloaded.

**Comment by N1CEyk** [comment]
When command executes until downloading the subtitle,it stops and prompts
'gl' isn't internal or  external command ……

2016-06-21 19:55 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:

**Comment by yan12125** [comment]
Could you post the full log, including your command?

**Comment by yan12125** [comment]
Oh seems you need to enclose the URL with double quotes. See https://github.com/rg3/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command.

**Comment by N1CEyk** [comment]
Thanks for your help. As a chinese,I appreciate your work very much!

2016-06-21 20:13 GMT+08:00 Yen Chi Hsuan <notifications@github.com>:
