### ISSUE TITLE
facebook problem with file ID

### ISSUE THREAD

**Issue by afsharsafavi** [rg3/youtube-dl#9851]
Hello
There is a problem when I want to download from facebook with youtube-dl
I checked it with latest version.
When I add -o or -A or --id flags (one of them), each time I get different and irrelevant file with different file size!
This is an example link:
https://www.facebook.com/LADbible/videos/2749323991781440/
It download main video only when I use none of that flags!
Otherwise it download irrelevant files!
I faced this problem with many of videos!
Best Regards 

youtube-dl  "https://www.facebook.com/LADbible/videos/2749323991781440/" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.facebook.com/LADbible/videos/2749323991781440/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.20
[debug] Python version 2.7.10 - Linux-4.2.0-35-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1
[debug] Proxy map: {}
[facebook] 2749323991781440: Downloading webpage
[debug] Invoking downloader on u'https://video.xx.fbcdn.net/v/t43.1792-2/13411505_299862347015375_204050219_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=26bbad80365d7977038d4a399cbf3ce9&oe=5769F5B9'
[download] Destination: Facebook video #2749323991781440-2749323991781440.mp4
[download] 100% of 2.80MiB in 00:00
---
youtube-dl --id  "https://www.facebook.com/LADbible/videos/2749323991781440/" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--id', u'https://www.facebook.com/LADbible/videos/2749323991781440/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.20
[debug] Python version 2.7.10 - Linux-4.2.0-35-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1
[debug] Proxy map: {}
[facebook] 2749323991781440: Downloading webpage
[debug] Invoking downloader on u'https://video.xx.fbcdn.net/v/l/t43.1792-2/13432028_1874549476115423_850180439_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=adb4e02ed2beb6d4d285ca26168430a1&oe=5769F4E9'
[download] Destination: 2749323991781440.mp4
[download] 100% of 2.32MiB in 00:00
---
youtube-dl -o 1.mp4  "https://www.facebook.com/LADbible/videos/2749323991781440/" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-o', u'1.mp4', u'https://www.facebook.com/LADbible/videos/2749323991781440/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.20
[debug] Python version 2.7.10 - Linux-4.2.0-35-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1
[debug] Proxy map: {}
[facebook] 2749323991781440: Downloading webpage
[debug] Invoking downloader on u'https://video.xx.fbcdn.net/v/t43.1792-2/13411505_299862347015375_204050219_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=26bbad80365d7977038d4a399cbf3ce9&oe=5769F5B9'
[download] Destination: 1.mp4
[download] 100% of 2.80MiB in 00:00
----
youtube-dl -A  "https://www.facebook.com/LADbible/videos/2749323991781440/" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-A', u'https://www.facebook.com/LADbible/videos/2749323991781440/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.20
[debug] Python version 2.7.10 - Linux-4.2.0-35-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1
[debug] Proxy map: {}
[facebook] 2749323991781440: Downloading webpage
[debug] Invoking downloader on u'https://video.xx.fbcdn.net/v/l/t43.1792-2/13432028_1874549476115423_850180439_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InN2ZV9oZCJ9&oh=adb4e02ed2beb6d4d285ca26168430a1&oe=5769F4E9'
[download] Destination: 00001-2749323991781440.mp4
[download] 100% of 2.32MiB in 00:00
----
youtube-dl  "https://www.faceboom/LADbible/videos/2749323991781440/" 
[facebook] 2749323991781440: Downloading webpage
[download] Destination: Facebook video #2749323991781440-2749323991781440.mp4
[download] 100% of 1.60MiB in 00:00

**Comment by dstftw** [comment]
It's been some maintenance on Facebook side today. Can you reproduce with 2016.06.22?

**Comment by afsharsafavi** [comment]
I checked
No change in result.
I should reproduce log with -v ?

**Comment by dstftw** [comment]
Yes, with `--dump-pages -v`.

**Comment by afsharsafavi** [comment]
With --dump-pages github give me error : 
Sorry! We couldn't save your comment — your comment is too long (maximum is 65536 characters). Please try again.
without --dump-pages :
/home/generate/site/youtube-dl --id "https://www.facebook.com/LADbible/videos/2749323991781440/" -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--id', u'https://www.facebook.com/LADbible/videos/2749323991781440/', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.22
[debug] Python version 2.7.10 - Linux-4.2.0-35-generic-x86_64-with-Ubuntu-15.10-wily
[debug] exe versions: ffmpeg 2.7.6-0ubuntu0.15.10.1, ffprobe 2.7.6-0ubuntu0.15.10.1
[debug] Proxy map: {}
[facebook] 2749323991781440: Downloading webpage
[debug] Invoking downloader on u'https://video.xx.fbcdn.net/v/t42.1790-2/13511700_139312846489267_820177727_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InFmXzQyNndfY3JmXzIzX21haW5fMy4wX3AxaGNtdjRfc2QifQ%3D%3D&oh=f1d9b2ae429d3e2ff5c4828c33045fcc&oe=576B16FF'
[download] Destination: 2749323991781440.mp4
[download] 100% of 2.29MiB in 00:00

**Comment by afsharsafavi** [comment]
One thing about facebook.com, if it possible,please add supporting for caption. Sample link:
https://www.facebook.com/BillGates/videos/10153678831351961/

**Comment by yan12125** [comment]
@afsharsafavi Please open a new issue for captions.

**Comment by ohory** [comment]
Hi,

We have a similar issue : each time we want to download a facebook video, we get another one.
Is this issue currently investigated ?

Our command line:
youtube-dl -4 -o /var/tmp/testdebug.mp4 -f "mp4/best[height <=? 720]" "https://www.facebook.com/lacinephile/videos/758765960927544/"

Thanks for your help !

Regards,
Olivier

**Comment by Shudouken** [comment]
Hello,

I have the same issue, when trying to download any video from https://www.facebook.com/ZeitimBild/ I get a random video of theirs instead. I have to try a couple of times to get the correct video.

Hope this will be fixed soon.

**Comment by dehylton** [comment]
i also see the random video issue. download, delete, download, delete, download - 3 completely different videos.

**Comment by Neney22** [comment]
i am also having the same problem anybody came up with a solution yet? It keeps pulling random videos from one link.
