### ISSUE TITLE
Bug report：Cannot find video formats

### ISSUE THREAD

**Issue by JackieXie168** [rg3/youtube-dl#9854]
I use this program to download facebook video then got the following error message.

$ youtube-dl https://www.facebook.com/englishbad/videos/557269211145445/
[facebook] 557269211145445: Downloading webpage
ERROR: Cannot find video formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Note：I've already download and run the latest version of youtube-dl. It's no problem to  download facebook video yesterday, but today is not...

OS : Mac OS X - mountain lion v10.8.5

$ youtube-dl https://www.facebook.com/englishbad/videos/557269211145445/ -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.facebook.com/englishbad/videos/557269211145445/', u'-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.20
[debug] Python version 2.7.11 - Darwin-12.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[facebook] 557269211145445: Downloading webpage
ERROR: Cannot find video formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 290, in _real_extract
    webpage, info_dict = self._extract_from_url(real_url, video_id, fatal_if_no_video=False)
  File "/opt/local/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 261, in _extract_from_url
    raise ExtractorError('Cannot find video formats')
ExtractorError: Cannot find video formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by kotofond** [comment]
Exact same issue for https://www.facebook.com/video.php?v=274175099429670:

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.20*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
~> youtube-dl --verbose "https://www.facebook.com/video.php?v=274175099429670"
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/video.php?v=274175099429670']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.20
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-LinuxMint-2-betsy
[debug] exe versions: ffmpeg 2.6.9, ffprobe 2.6.9
[debug] Proxy map: {}
[facebook] 274175099429670: Downloading webpage
ERROR: Cannot find video formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/facebook.py", line 290, in _real_extract
    webpage, info_dict = self._extract_from_url(real_url, video_id, fatal_if_no_video=False)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/facebook.py", line 261, in _extract_from_url
    raise ExtractorError('Cannot find video formats')
ExtractorError: Cannot find video formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by hoonoh** [comment]
The download has been working fine until yesterday for me, except the downloaded video was most of the time different from what I was expecting. (was downloading different video)

**Comment by oplaza** [comment]
same here:

youtube-dl --verbose https://www.facebook.com/video/embed?video_id=1123523814353434
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/video/embed?video_id=1123523814353434']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.05.16
[debug] Python version 2.6.6 - Linux-2.6.32-042stab106.4-x86_64-with-centos-6.6-Final
[debug] exe versions: none
[debug] Proxy map: {}
[facebook] 1123523814353434: Downloading webpage
ERROR: Cannot find video formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/common.py", line 341, in extract
    return self._real_extract(url)
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/facebook.py", line 290, in _real_extract
    webpage, info_dict = self._extract_from_url(real_url, video_id, fatal_if_no_video=False)
  File "/usr/lib/python2.6/site-packages/youtube_dl/extractor/facebook.py", line 261, in _extract_from_url
    raise ExtractorError('Cannot find video formats')
ExtractorError: Cannot find video formats; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by shaicoleman** [comment]
It seems that beforehand Facebook returned an array of dicts, and now it returns just a dict if there only one result.

I've looked into it, the problem seems to be in extractor/facebook.py with the following lines:

    if not f or not isinstance(f, list):

                    src = f[0].get('%s_%s' % (quality, src_type))

            dash_manifest = f[0].get('dash_manifest')

**Comment by shaicoleman** [comment]
Pull request #9856 to fix

**Comment by jaimeMF** [comment]
It will be fixed in the next version thanks to @shaicoleman. Thanks for reporting the issue!

**Comment by JackieXie168** [comment]
It's happened again, but this time the error message is 'ERROR: Cannot parse data;...'

$ youtube-dl --verbose https://www.facebook.com/chinatimes.com.tw/videos/637872803059185/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.facebook.com/chinatimes.com.tw/videos/637872803059185/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.10.02
[debug] Python version 2.7.12 - Darwin-12.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.1.4, ffprobe 3.1.4
[debug] Proxy map: {}
[facebook] 637872803059185: Downloading webpage
[facebook] 637872803059185: Downloading webpage
ERROR: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/jackie/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/Users/jackie/bin/youtube-dl/youtube_dl/extractor/common.py", line 355, in extract
    return self._real_extract(url)
  File "/Users/jackie/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 352, in _real_extract
    video_id, fatal_if_no_video=True)
  File "/Users/jackie/bin/youtube-dl/youtube_dl/extractor/facebook.py", line 276, in _extract_from_url
    raise ExtractorError('Cannot parse data')
ExtractorError: Cannot parse data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by yan12125** [comment]
@JackieXie168 Seems the same problem as #10846
