### ISSUE TITLE
Release process and yt-dl.org

### ISSUE THREAD

**Issue by WassimAttar** [rg3/youtube-dl#9855]
Hello

It's not an issue, it's an observation.
I was looking to the release process devscripts/release.sh and i saw this
ssh ytdl@yt-dl.org "sh html/update_latest.sh $version"
The build is uploaded to yt-dl.org
Why do you need it since the latest build is available here ?
https://github.com/rg3/youtube-dl/releases/latest

May be i missed something.
If not, i can PR a fix so there there is no more dependencies to yt-dl.org for the builds.

++

**Comment by dstftw** [comment]
`update_latest.sh` is used to update https://yt-dl.org/latest_version, rewrite rules for https://yt-dl.org/latest and so on.

**Comment by WassimAttar** [comment]
I know the implications in https://yt-dl.org but why do you need https://yt-dl.org since you can get all the informations and the builds here https://github.com/rg3/youtube-dl/releases/latest ?
github provides everything, why do you still want a dependency to https://yt-dl.org ?

**Comment by dstftw** [comment]
So you suggest to just close yt-dl.org down breaking every service that depends on it for updating? Needless to say most of average users have no idea about GitHub.

**Comment by yan12125** [comment]
See #9690.

Before June 4, 2016, all binaries are hosted on yt-dl.org. Due to bandwidth limitations we _temporarily_ put binraries on Github. As per previous discussions, Github is not the long-term solution and we're going to move binaries to some other places again. Cleanup works on yt-dl.org should be postponed until we finally migrated binaries to their new home.

**Comment by WassimAttar** [comment]
If i understand, theoretically github is only used for versionning, but you are also using it to :
- solve issues
- pull requests
- host web site via https://rg3.github.io/youtube-dl/
- host binaries

It's a little bit confusing.
In fact, what you should do, is to close https://rg3.github.io/youtube-dl/ and hosting binaries.
Keep only github for versionning, solve issues and pull requests.

**Comment by WassimAttar** [comment]
I have read the #9690 
I am surprised that youtube-dl has this big success.
It's great !!
What do you thing about hosting binaries on several "free" hosting ?
For a beginning sharing the load between github and https://yt-dl.org/ should be enough, no ?

**Comment by WassimAttar** [comment]
I'm thinking about another solution to save bandwith :

**Comment by WassimAttar** [comment]
I'm thinking about another way for saving bandwidth :
Release weekly instead of daily.
You cut by 7.
youtube-dl is not so vital, people can wait.

**Comment by dstftw** [comment]
This will barely have any effect. There will be just more downloads per release.

**Comment by WassimAttar** [comment]
I update youtube-dl daily.
1.2Mb x 7 = 8.4Mb weekly for my own.
If you release weekly, it will be only 1.2Mb

**Comment by dstftw** [comment]
95% only update when experience some breakage.

**Comment by WassimAttar** [comment]
hum.
You are saying that bandwidth is explosing because youtube-dl is getting more popular everyday ?
Do you have any data about the number of users ?
Do you know who are the users ?
Because if you have 10% more users every month, it's a geometric growth and scaling the binaries hosting is a problem in itself.

Other question.
Do you think that youtube-dl is embedded in a another software which is popular ?
It may explain this growth.
