### ISSUE TITLE
TF1 broken ?

### ISSUE THREAD

**Issue by MichelLopez** [rg3/youtube-dl#9862]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.23*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.23**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
youtube-dl.exe -v http://lci.tf1.fr/jt-20h/videos/2016/le-20-heures-du-22-juin-2016-8752713.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://lci.tf1.fr/jt-20h/videos/2016/le-20-heures-du-22-juin-2016-8752713.html']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.23
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-55337-gb45b1d7
[debug] Proxy map: {}
[TF1] le-20-heures-du-22-juin-2016-8752713: Downloading webpage
[wat.tv] 11130442: Downloading JSON metadata
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi15lg598\build\youtube_dl\__init__.py", line 420, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi15lg598\build\youtube_dl\__init__.py", line 410, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi15lg598\build\youtube_dl\YoutubeDL.py", line 1740, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi15lg598\build\youtube_dl\YoutubeDL.py", line 687, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi15lg598\build\youtube_dl\YoutubeDL.py", line 740, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi15lg598\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi15lg598\build\youtube_dl\extractor\common.py", line 343, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi15lg598\build\youtube_dl\extractor\wat.py", line 56, in _real_extract
AttributeError: 'NoneType' object has no attribute 'get'

---

**Comment by remitamine** [comment]
will be fixed in the next version.

**Comment by sbouafif** [comment]
@remitamine not working again

**Comment by yan12125** [comment]
@sbouafif Works for me. Please post the full verbose log like this:
```
$ youtube-dl -v http://lci.tf1.fr/jt-20h/videos/2016/le-20-heures-du-22-juin-2016-8752713.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://lci.tf1.fr/jt-20h/videos/2016/le-20-heures-du-22-juin-2016-8752713.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.07
[debug] Git HEAD: b657816
[debug] Python version 3.5.2 - Linux-4.6.5-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[TF1] le-20-heures-du-22-juin-2016-8752713: Downloading webpage
[wat.tv] 13044241: Downloading JSON metadata
[wat.tv] 13044241: Extracting m3u8 url
[wat.tv] 13044241: Extracting http url
[wat.tv] 13044241: Downloading m3u8 information
[wat.tv] 13044241: Downloading f4m manifest
[debug] Invoking downloader on 'http://dnl.adv.tf1.fr/2/USP-0x0/42/41/13044241/ssm/13044241-2500-64k.mp4'
[download] Destination: Les titres du JT de 20h du mercredi 22 juin 2016-13044241.mp4
[download]   0.6% of 692.12MiB at 695.70KiB/s ETA 16:52^C

ERROR: Interrupted by user
```

**Comment by sbouafif** [comment]
It's odd. I tried it on a few videos and have a different output/error each time.

`s:~/ $ youtube-dl -v http://www.tf1.fr/tf1/ninja-warrior/videos/ninja-warrior-5-aout-2016.html             [12:16:07]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.tf1.fr/tf1/ninja-warrior/videos/ninja-warrior-5-aout-2016.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.07
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[TF1] ninja-warrior-5-aout-2016: Downloading webpage
[wat.tv] 13234582: Downloading JSON metadata
[wat.tv] 13234582: Extracting m3u8 url
[wat.tv] 13234582: Extracting http url
[wat.tv] 13234582: Downloading m3u8 information
[wat.tv] 13234582: Downloading f4m manifest
[debug] Invoking downloader on u'http://dnl.adv.tf1.fr/2/USP-0x0/45/82/13234582/ssm/13234582-2500-64k.mp4'
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1683, in process_info
    success = dl(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1625, in dl
    return fd.download(name, info)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/local/bin/youtube-dl/youtube_dl/downloader/http.py", line 58, in real_download
    data = self.ydl.urlopen(request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1985, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden

s:~/ $ youtube-dl -v http://www.tf1.fr/tf1/flash/videos/flash-episode-10-saison-02-course-ralenti.html     [12:16:20]
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.tf1.fr/tf1/flash/videos/flash-episode-10-saison-02-course-ralenti.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.07
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[TF1] flash-episode-10-saison-02-course-ralenti: Downloading webpage
[wat.tv] 13235543: Downloading JSON metadata
[wat.tv] 13235543: Extracting m3u8 url
ERROR: wat.tv said: Sorry, this video is not available from your country.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 682, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 347, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/wat.py", line 86, in _real_extract
    m3u8_url = extract_url('ipad/%s.m3u8', 'm3u8')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/wat.py", line 83, in extract_url
    expected=True)
ExtractorError: wat.tv said: Sorry, this video is not available from your country.

s:~/ $ youtube-dl -v http://www.tf1.fr/tf1/une-famille-formidable/videos/une-famille-formidable-l-enigme-papas-perdus-1.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.tf1.fr/tf1/une-famille-formidable/videos/une-famille-formidable-l-enigme-papas-perdus-1.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.08.07
[debug] Python version 2.7.10 - Darwin-15.6.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.1.1, ffprobe 3.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[TF1] une-famille-formidable-l-enigme-papas-perdus-1: Downloading webpage
[wat.tv] 13235312: Downloading JSON metadata
[wat.tv] 13235312: Extracting m3u8 url
[wat.tv] 13235312: Extracting http url
[wat.tv] 13235312: Downloading m3u8 information
[wat.tv] 13235312: Downloading f4m manifest
[debug] Invoking downloader on u'http://dnl.adv.tf1.fr/2/USP-0x0/53/12/13235312/ssm/13235312-2500-64k.mp4'
[download] Destination: Une famille formidable - L'énigme des papas perdus-13235312.mp4
[download]   0.1% of 1.73GiB at  2.02MiB/s ETA 14:38^C
ERROR: Interrupted by user`

**Comment by yan12125** [comment]
The got the same errors from youtube-dl. In browsers, both the first and the second video say:
```
Ce contenu ñ'est disponible depuis votre zone géographique
```
Did you use any proxy or VPN?

**Comment by sbouafif** [comment]
No proxy or vpn. I live in France where TF1 operates

**Comment by yan12125** [comment]
I've tried several France proxies and all give the same geolocation message. Anyway could you open a new issue for your problem?
