### ISSUE TITLE
WARNING: unable to extract * count; please report this issue

### ISSUE THREAD

**Issue by pkirk** [rg3/youtube-dl#9874]
MBP:~ paolo$ sudo youtube-dl -U
Password:
Updating to version 2016.06.23.1 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
MBP:~ paolo$ youtube-dl -v https://www.mixcloud.com/NTSRadio/floating-points-four-tet-21st-june-2016/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.mixcloud.com/NTSRadio/floating-points-four-tet-21st-june-2016/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.23.1
[debug] Python version 2.7.10 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg N-79129-gb3dc51d-tessus, ffprobe N-79800-g7b7c338-tessus
[debug] Proxy map: {}
[mixcloud] NTSRadio-floating-points-four-tet-21st-june-2016: Downloading webpage
**WARNING: unable to extract like count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.**
**WARNING: unable to extract play count; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.**
[debug] Invoking downloader on u'https://stream1.mixcloud.com/c/m4a/64/9/9/4/8/2e0f-0ee1-4102-b45c-63712e25b694.m4a'
[download] Resuming download at byte 8542519
[download] Destination: Floating Points & Four Tet - 21st June 2016-NTSRadio-floating-points-four-tet-21st-june-2016.m4a
[download]  17.9% of 60.21MiB at 368.47KiB/s ETA 02:17

**Comment by yan12125** [comment]
Thanks for the report. Will be fixed in the next version.
