### ISSUE TITLE
No more format 141 audio? 

### ISSUE THREAD

**Issue by dndlnx** [rg3/youtube-dl#9875]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.23.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x ] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.23.1**

### Before submitting an *issue* make sure you have:
- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ x] Question
- [ ] Other

---

### Description of your *issue*, suggested solution and other information

I can no longer get the 256k DASH  m4a, not a single link I try!  Someone confirmed on the IRC channel, but my question is -  this is something on YouTube's end?  There's no work around or fix?  Is it possible this will come back?   Very bummed about this if not.  :(

**Comment by dstftw** [comment]
I've already clarified that 141 is not served anymore by YouTube. At least on all example URLs I checked.

**Comment by dndlnx** [comment]
OK,   if you’re going to instantly close my report.

Could you tell me at least,  has this happened before?  Formats just disappearing? Did they come back?   I used 141 forever, to have it just be gone is terrible news.   People should at least be notified in the FAQ / guide, somewhere...
