### ISSUE TITLE
Cannot download from vbox7.com

### ISSUE THREAD

**Issue by uuencode** [rg3/youtube-dl#9876]
youtube-dl latest version  (June 23)

youtube-dl --verbose http://vbox7.com/play:671d467cad
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://vbox7.com/play:671d467cad']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.23.1
[debug] Python version 2.7.3 - Linux-4.1.19+-armv6l-with-debian-7.11
[debug] exe versions: none
[debug] Proxy map: {}
[Vbox7] 671d467cad: Downloading webpage
[Vbox7] 671d467cad: Getting session id
[Vbox7] 671d467cad: Downloading webpage
[Vbox7] 671d467cad: Getting session id
[Vbox7] 671d467cad: Downloading redirect page
[Vbox7] 671d467cad: Downloading info webpage
ERROR: Unable to download webpage: HTTP Error 500: Internal Server Error (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 390, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1950, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

**Comment by yan12125** [comment]
@uuencode Seems it's a temporary issue. It's working for me now:
```
$ youtube-dl -v "http://vbox7.com/play:671d467cad" 
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://vbox7.com/play:671d467cad']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.23.1
[debug] Git HEAD: c1ff6e1
[debug] Python version 3.5.1 - Linux-4.6.2-1-ARCH-x86_64-with-arch
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[Vbox7] 671d467cad: Downloading webpage
[Vbox7] 671d467cad: Getting session id
[Vbox7] 671d467cad: Downloading webpage
[Vbox7] 671d467cad: Getting session id
[Vbox7] 671d467cad: Downloading redirect page
[Vbox7] 671d467cad: Downloading info webpage
[debug] Invoking downloader on 'https://int2.vbox7.com/s/67/671d467cadrfb69015fc.mp4'
[download] Destination: Di Yan - Dsk (Audio)-671d467cad.mp4
[download] 100% of 24.22MiB in 00:24
```
Could you try again?

**Comment by dstftw** [comment]
Confirmed, works fine now.
