### ISSUE TITLE
Unable to download a respective playlist

### ISSUE THREAD

**Issue by vigneshtv** [rg3/youtube-dl#9880]
I tried downloading a playlist from this url: https://www.youtube.com/playlist?list=PL6gx4Cwl9DGBpuvPW0aHa7mKdn_k9SPKO

I was able to download 5 videos but the rest does not get downloaded. 

PS: This is only in case of this playlist. Others get downloaded. I also checked if video exists, and it does.

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.
