### ISSUE TITLE
youtube-dl causes"Unable to find a suitable output format for 'file:xyz/.mkv.temp'"

### ISSUE THREAD

**Issue by DeadSix27** [rg3/youtube-dl#9886]
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.23.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.23.1**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ ./youtube-dl https://www.youtube.com/watch?v=nZQQUShfdEs -o tdl/ -v -f bestvideo+bestaudio
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'https://www.youtube.com/watch?v=nZQQUShfdEs', u'-o', u'tdl/', u'-v', u'-f', u'bestvideo+bestaudio']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.23.1
[debug] Python version 2.7.11+ - Linux-4.4.0-24-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg N-80573-gbfbffbd-static, ffprobe N-80573-gbfbffbd-static, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] nZQQUShfdEs: Downloading webpage
[youtube] nZQQUShfdEs: Downloading video info webpage
[youtube] nZQQUShfdEs: Extracting video information
[youtube] nZQQUShfdEs: Downloading MPD manifest
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[debug] Invoking downloader on u'https://********'
[download] Resuming download at byte 74851129
[download] Destination: tdl/.f315
[download] 100% of 134.38MiB in 00:12
[debug] Invoking downloader on u'https://*********'
[download] Destination: tdl/.f140
[download] 100% of 913.21KiB in 00:00
[ffmpeg] Merging formats into "tdl/.mkv"
[debug] ffmpeg command line: ffmpeg -y -i file:tdl/.f315 -i file:tdl/.f140 -c copy -map 0:v:0 -map 1:a:0 file:tdl/.mkv.temp
ERROR: file:tdl/.mkv.temp: Invalid argument
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 1786, in post_process
    files_to_delete, info = pp.run(info)
  File "./youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 445, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "./youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 168, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
FFmpegPostProcessorError
...


FFMPEG Output:
[NULL @ 0x5071860] Unable to find a suitable output format for 'file:tdl/.mkv.temp'
file:tdl/.mkv.temp: Invalid argumen
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

youtube-dl does not tell ffmpeg the output format and ffmpeg can't tell by itself due to the ".temp" extension, running the ffmpeg command myself with -f mp4 works just fine, however I could not find any documentation on a command argument for youtube-dl anywhere, that tells it to "append" "-f XXX" to the output.

PS: If this is a dublicate then I couldn't find the first occurance, I've went through the issues and searched them for similliar ones, i found one but thats about mp4 and the ""solutions"" mentioned there, didn't fix my issue.

**Comment by yan12125** [comment]
Use:
```
youtube-dl https://www.youtube.com/watch?v=nZQQUShfdEs -o "tdl/%(title)s-%(id)s.%(ext)s" -v -f bestvideo+bestaudio
```

**Comment by DeadSix27** [comment]
Thanks! Didn't think about simply changing the actual filename it writes the files to...
