### ISSUE TITLE
Can't download Pluralsight playlist anymore

### ISSUE THREAD

**Issue by mintzaw** [rg3/youtube-dl#9888]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl-2016.06.25 --username xxx --password yyy --output "[SE-PM] Agile Requirements Process - From Idea to Minimum Viable Product/%(playlist_index)s-%(title)s.%(ext)s" --verbose --no-check-certificate --sleep-interval 180 https://app.pluralsight.com/library/courses/agile-requirements-process-idea-to-minimum-viable-product/table-of-contents --playlist-start 17
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--output', '[SE-PM] Agile Requirements Process - From Idea to Minimum Viable Product/%(playlist_index)s-%(title)s.%(ext)s', '--verbose', '--no-check-certificate', '--sleep-interval', '180', 'https://app.pluralsight.com/library/courses/agile-requirements-process-idea-to-minimum-viable-product/table-of-contents', '--playlist-start', '17']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.25
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[pluralsight:course] agile-requirements-process-idea-to-minimum-viable-product: Downloading course JSON
[pluralsight:course] agile-requirements-process-idea-to-minimum-viable-product: Downloading course data JSON
[download] Downloading playlist: Agile Requirements Process: From Idea to Minimum Viable Product
[pluralsight:course] playlist Agile Requirements Process: From Idea to Minimum Viable Product: Collected 38 video ids (downloading 22 of them)
[download] Downloading video 1 of 22
[pluralsight] Downloading login page
[pluralsight] Logging in as xxx
[pluralsight] agile-requirements-process-idea-to-minimum-viable-product-m3-3: Downloading webpage
ERROR: Unable to extract initial state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\extractor\common.py", line 343, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\extractor\pluralsight.py", line 120, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\extractor\common.py", line 646, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract initial state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl-2016.06.25 --username xxx --password yyy --output "[SE-PM] Agile Requirements Process - From Idea to Minimum Viable Product/%(playlist_index)s-%(title)s.%(ext)s" --verbose --no-check-certificate --sleep-interval 180 https://app.pluralsight.com/library/courses/agile-requirements-process-idea-to-minimum-viable-product/table-of-contents --playlist-start 17 --call-home
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['--username', 'PRIVATE', '--password', 'PRIVATE', '--output', '[SE-PM] Agile Requirements Process - From Idea to Minimum Viable Product/%(playlist_index)s-%(title)s.%(ext)s', '--verbose', '--no-check-certificate', '--sleep-interval', '180', 'https://app.pluralsight.com/library/courses/agile-requirements-process-idea-to-minimum-viable-product/table-of-contents', '--playlist-start', '17', '--call-home']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2016.06.25
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[debug] Public IP address: 103.25.77.185
[pluralsight:course] agile-requirements-process-idea-to-minimum-viable-product: Downloading course JSON
[pluralsight:course] agile-requirements-process-idea-to-minimum-viable-product: Downloading course data JSON
[download] Downloading playlist: Agile Requirements Process: From Idea to Minimum Viable Product
[pluralsight:course] playlist Agile Requirements Process: From Idea to Minimum Viable Product: Collected 38 video ids (downloading 22 of them)
[download] Downloading video 1 of 22
[pluralsight] Downloading login page
[pluralsight] Logging in as xxx
[pluralsight] agile-requirements-process-idea-to-minimum-viable-product-m3-3: Downloading webpage
ERROR: Unable to extract initial state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\extractor\common.py", line 343, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\extractor\pluralsight.py", line 120, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpdy42tioh\build\youtube_dl\extractor\common.py", line 646, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract initial state; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

$ youtube-dl-2016.06.25 --username xxx --password yyy --output "[SE-PM] Agile Requirements Process - From Idea to Minimum Viable Product/%(playlist_index)s-%(title)s.%(ext)s" --verbose --no-check-certificate --sleep-interval 180 https://app.pluralsight.com/library/courses/agile-requirements-process-idea-to-minimum-viable-product/table-of-contents --playlist-start 17 --call-home --dump-pages >log.txt 2>&1
[log.txt](https://github.com/rg3/youtube-dl/files/332869/log.txt)

...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://app.pluralsight.com/player?course=full-stack-dot-net-developer&author=mosh-hamedani&name=full-stack-dot-net-developer-m0&clip=0&mode=live
- Single video: https://app.pluralsight.com/player?course=sql-server-flyway-continuous-database-delivery&author=wes-mcclure&name=sql-server-flyway-continuous-database-delivery-m1&clip=0&mode=live
- Playlist: https://app.pluralsight.com/library/courses/sql-server-2008-database-development-pt1/table-of-contents

---

### Description of your *issue*, suggested solution and other information

Can't download Pluralsight playlist anymore. I used to download entire playlists from Pluralsight last month but it was in another country. Now I'm back in my country and can't download anymore. I'm not sure if it's due to country or to changes made by Pluralsight. 

I have included details of the commands and switches (three commands) that I used together with the log msgs. I used latest exe version (2016.06.25) from Windows 10 Home. xxx and yyy are not my real account and password. If you need to test more, pls reply and I'll test with my account.

Thanks.

**Comment by dstftw** [comment]
Post the output of `youtube-dl --username xxx --password yyy --verbose --dump-pages --no-check-certificate --playlist-items 17 https://app.pluralsight.com/library/courses/agile-requirements-process-idea-to-minimum-viable-product/table-of-contents`.

**Comment by mintzaw** [comment]
Hi, pls see output in [log.txt](https://github.com/rg3/youtube-dl/files/334044/log.txt)

**Comment by dstftw** [comment]
From your log:
>Because your IP address or billing address is associated with a country that is sanctioned by the United States, by U.S. law we are required to block your access to Pluralsight.com. If you believe you are receiving this message in error, please contact support@pluralsight.com.

**Comment by mintzaw** [comment]
Oh, thanks for the help and extracting out the message from the log!

It's strange as I can log in to the web site and view the videos just fine. Can even download using a tool like DownThemAll Firefox Add-On (together with DownThemAll Anti-Container).
