### ISSUE TITLE
Extra surrounding quotes being added to most file names - any way to suppress?

### ISSUE THREAD

**Issue by SanjeevKSharma** [rg3/youtube-dl#9895]
this is in the config

--output %(uploader_id)s.%(upload_date)s.%(title)s.%(id)s.%(ext)s

youtube-dl 'https://www.youtube.com/watch?v=xcXwxXL9o3M'

'LeagueOfNerdsPodcast.20160612.Consumed Review -TLoNs Podcast #132.xcXwxXL9o3M.f136.mp4.part'

That's not too bad but then I'm getting file names with multiple escaped quotes (the '\''  thing below, slightly different output config); --output %(upload_date)s.%(title)s.%(id)s.%(ext)s

'20160509.MEET DAVID SILVERMAN, REASON RALLY, AMERICAN ATHEISTS PREZ, BILLBOARD GUY, '\''TIDES GO IN'\'' MEME MAN!.soOtYMSZ5iU.mkv'

another complication - with this in the config
--output %(title)s.%(ext)s/%(title)s.%(ext)s

youtube-dl 'https://www.youtube.com/watch?v=xcXwxXL9o3M'

the directory also ends up with the all-enclosing quotes
ls -xR
.:
'Consumed Review -TLoNs Podcast #132.mp4'

'./Consumed Review -TLoNs Podcast #132.mp4':
'Consumed Review -TLoNs Podcast #132.f136.mp4.part'

**Comment by dstftw** [comment]
Carefully read [new issue template](https://github.com/rg3/youtube-dl/issues/new) and provide all requested information.

**Comment by SanjeevKSharma** [comment]
APOLOGIES, this is caused by the upgrade to Fedora 24 & new defaults for Gnu ls - 

they changed the defaults to add quotes when printing to a TERM if there are some special characters or ambiguities in the name
