### ISSUE TITLE
youtube-dl livestream lags

### ISSUE THREAD

**Issue by Joseph65** [rg3/youtube-dl#9907]
When i watch this livestream " https://www.youtube.com/watch?v=A8A1NVZHFtc" with mpv e.g. 
`mpv --ytdl https://www.youtube.com/watch?v=A8A1NVZHFtc`
 it lags alot this doesnt happen when i watch it with a browser in 720p

i am using the latest youtube-dl 2016.06.25

**Comment by dstftw** [comment]
Questions regarding mpv should be addressed to mpv developers. Most likely mpv by default tries to play 1080p that can't be handled by your hardware/network.

**Comment by Joseph65** [comment]
I just opened the same stream with livestreamer
`livestreamer https://www.youtube.com/watch?v=A8A1NVZHFtc 1080p`
with quality 1080p without any lag and with mpv so its not a hardware/network problem
it must be problem with youtube-dl

**Comment by yan12125** [comment]
Can you describe more about the "lag"? Both ```livestreamer https://www.youtube.com/watch?v=A8A1NVZHFtc 1080p``` and ```mpv --ytdl https://www.youtube.com/watch?v=A8A1NVZHFtc``` plays fine on my machine.

**Comment by Joseph65** [comment]
i use the format 95
which is 720p like this = mpv --ytdl-format 95 https://www.youtube.com/watch?v=A8A1NVZHFtc
i think it may be an issue with mpv because it plays fine on livestreamer.

**Comment by yan12125** [comment]
Yes got some lags with format 95. Seems like a problem of mpv of ffmpeg. Please forward it to https://github.com/mpv-player/mpv or http://ffmpeg.org/bugreports.html.
