### ISSUE TITLE
Specific video fails to download

### ISSUE THREAD

**Issue by igmar** [rg3/youtube-dl#9909]
## Please follow the guide below
---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [ X] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.25**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
$ youtube-dl -v https://www.youtube.com/watch?v=IyFw9YgsCFw
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.youtube.com/watch?v=IyFw9YgsCFw']
[debug] Encodings: locale US-ASCII, fs utf-8, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2016.06.25
[debug] Python version 2.7.11 - Darwin-15.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[youtube] IyFw9YgsCFw: Downloading webpage
[youtube] IyFw9YgsCFw: Downloading video info webpage
[youtube] IyFw9YgsCFw: Extracting video information
[youtube] IyFw9YgsCFw: Downloading MPD manifest
[youtube] IyFw9YgsCFw: Downloading MPD manifest
[debug] Invoking downloader on u'https://r9---sn-5hne6n76.googlevideo.com/videoplayback/id/232170f5882c085c/itag/137/source/yt_otf/requiressl/yes/pl/15/mm/31/nh/IgpwcjAyLmFtczE2KgkxMjcuMC4wLjE/mn/sn-5hne6n76/ms/au/initcwndbps/1131250/mv/m/ratebypass/yes/mime/video%2Fmp4/otfp/1/otf/1/lmt/1463190250552525/upn/3gIUDIbpv6k/key/dg_yt0/fexp/9416126,9416891,9419452,9422372,9422596,9428398,9431012,9431418,9433096,9433380,9433946,9435242,9435409,9435526,9435876,9436928,9437066,9437553,9437652,9437740,9438662,9438804,9439652,9439748,9439882,9439884,9439944/mt/1466927622/signature/7ACB9B8186774BFE97E7B9A6CD88514304A8C5AD.4D1F9B20FBAA4BC234F7C12A7A5EE489B8CB4105/sver/3/ip/92.109.33.90/ipbits/0/expire/1466949541/sparams/ip,ipbits,expire,id,itag,source,requiressl,pl,mm,nh,mn,ms,initcwndbps,mv,ratebypass,mime,otfp,otf,lmt/'
[dashsegments] Total fragments: 20
[download] Destination: Compliatie _ 4x Ambulance met spoed in Breda!-IyFw9YgsCFw.f137.mp4
```

### Description of your *issue*, suggested solution and other information

Download fails https://www.youtube.com/watch?v=IyFw9YgsCFw
The issue is specific to this video, I haven't seen it on other video's.
As an added info, also the Youtube app (iPad) doesn't play it. Mobile safari also doesn't play it.
It does play on OSX Chrome.

**Comment by dstftw** [comment]
It downloads fine according to your log and it plays fine by vlc, mpv, wmp.

**Comment by igmar** [comment]
Not, it doesn't : it hangs at the last line.

**Comment by dstftw** [comment]
Disable IPv6 with `-4`.
