### ISSUE TITLE
Support for oreilly.com

### ISSUE THREAD

**Issue by pixelrust** [rg3/youtube-dl#9911]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v https://www.oreilly.com/ideas/you-got-your-design-team-in-my-security-team
[debug] System config: []
[debug] User config: [u'-f', u'best']
[debug] Command-line args: [u'-v', u'https://www.oreilly.com/ideas/you-got-your-design-team-in-my-security-team']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.25
[debug] Python version 2.7.11+ - Linux-4.4.0-24-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] you-got-your-design-team-in-my-security-team: Requesting header
WARNING: Could not send HEAD request to https://www.oreilly.com/ideas/you-got-your-design-team-in-my-security-team: HTTP Error 404: Not Found
[generic] you-got-your-design-team-in-my-security-team: Downloading webpage
WARNING: Falling back on generic information extractor.
[generic] you-got-your-design-team-in-my-security-team: Extracting information
ERROR: Unsupported URL: https://www.oreilly.com/ideas/you-got-your-design-team-in-my-security-team
Traceback (most recent call last):
  File "/home/open/bin/youtube-dl/youtube_dl/extractor/generic.py", line 1440, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "/home/open/bin/youtube-dl/youtube_dl/compat.py", line 2524, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "/home/open/bin/youtube-dl/youtube_dl/compat.py", line 2513, in _XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: mismatched tag: line 76, column 2
Traceback (most recent call last):
  File "/home/open/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/home/open/bin/youtube-dl/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "/home/open/bin/youtube-dl/youtube_dl/extractor/generic.py", line 2140, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: https://www.oreilly.com/ideas/you-got-your-design-team-in-my-security-team

<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.oreilly.com/ideas/you-got-your-design-team-in-my-security-team
- Single video: https://www.oreilly.com/ideas/my-cloud-makes-pretty-pictures
- no playlists

---

### Description of your *issue*, suggested solution and other information

Please add support for O'Reilly videos at https://www.oreilly.com/ideas/

**Comment by TRox1972** [comment]
For developers: Kaltura embed

**Comment by pixelrust** [comment]
Thanks! Just tried with another video from the same website after building from the new sources, and I confirm it's now working.
