### ISSUE TITLE
Iqiyi: test regression

### ISSUE THREAD

**Issue by anisse** [rg3/youtube-dl#9912]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.25*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.25**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---
test_Iqiyi_2 test had a recently introduced regression:
https://travis-ci.org/anisse/youtube-dl/builds/140328781

This is the new test infrastructure discussed in #8496 that detected it (it has an auto-merge to trigger builds).

**Comment by anisse** [comment]
ping @yan12125

**Comment by yan12125** [comment]
test_Iqiyi_2 is a VIP-only video and I haven't fixed it yet.

**Comment by anisse** [comment]
Ah, so it's in fact failing (it's downloading the ad as said in the other bug ?)

**Comment by yan12125** [comment]
Yep it's falling. Unlike non-VIP videos, this one now returns nothing.

**Comment by anisse** [comment]
There's another regression, probably introduced by  2644e91. See https://travis-ci.org/anisse/youtube-dl/jobs/142021660

Is it another VIP video?

**Comment by yan12125** [comment]
Apparently Iqiyi serves different files to Travis CI and my machine.

**Comment by yan12125** [comment]
Fixed by 3a212ed.
