### ISSUE TITLE
soundcloud extractor metadata

### ISSUE THREAD

**Issue by duperray** [rg3/youtube-dl#9917]
Hi,

I cloned the master, and when downloading a soundcloud sound, I saw in pdb that the extractor could retrieve metadata about title, artist (json thing) ... however, the resulting mp3 has not id3 tags.

Cheers,

Pierre

**Comment by dstftw** [comment]
For embedding metadata `--add-metadata` must be used.

**Comment by duperray** [comment]
even with --add-metadata, it does not work

**Comment by duperray** [comment]
$ ~/src/youtube-dl/bin/youtube-dl --add-metadata https://soundcloud.com/losporcos/waterfalls
[soundcloud] losporcos/waterfalls: Resolving id
[soundcloud] losporcos/waterfalls: Downloading info JSON
[soundcloud] 107496060: Downloading track url
[soundcloud] 107496060: Checking fallback video format URL
[soundcloud] 107496060: Checking http_mp3_128_url video format URL
[download] Destination: Waterfalls-107496060.mp3
[download] 100% of 2.86MiB in 00:01
[ffmpeg] Adding metadata to 'Waterfalls-107496060.mp3'

$ mp3info Waterfalls-107496060.mp3 
Waterfalls-107496060.mp3 does not have an ID3 1.x tag

**Comment by duperray** [comment]
$ ffmpeg -version
ffmpeg version 3.0.2 Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 5.3.1 (Debian 5.3.1-17) 20160429
configuration: --prefix=/usr --extra-cflags='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security ' --extra-ldflags='-Wl,-z,relro' --cc='ccache cc' --enable-shared --enable-libmp3lame --enable-gpl --enable-nonfree --enable-libvorbis --enable-pthreads --enable-libfaac --enable-libxvid --enable-postproc --enable-x11grab --enable-libgsm --enable-libtheora --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libx264 --enable-libspeex --enable-nonfree --enable-libvpx --enable-libschroedinger --disable-encoder=libschroedinger --enable-version3 --enable-libopenjpeg --enable-librtmp --enable-avfilter --enable-libfreetype --disable-decoder=amrnb --enable-libvo-amrwbenc --enable-libtesseract --libdir=/usr/lib/x86_64-linux-gnu --disable-vda --enable-libbluray --enable-libcdio --enable-gnutls --enable-frei0r --enable-openssl --enable-libass --enable-libopus --enable-fontconfig --enable-libpulse --disable-mipsdsp --disable-mips32r2 --disable-msa --disable-mipsfpu --disable-mipsdspr2 --enable-libvidstab --enable-libzvbi --enable-avresample --enable-libutvideo --enable-libfdk-aac --enable-libx265 --enable-libbs2b --enable-libilbc --enable-libopenh264 --enable-libkvazaar --enable-libsnappy --enable-libsoxr --enable-libiec61883 --enable-vaapi --enable-opencl --enable-libdc1394 --disable-altivec --shlibdir=/usr/lib/x86_64-linux-gnu
libavutil      55. 17.103 / 55. 17.103
libavcodec     57. 24.102 / 57. 24.102
libavformat    57. 25.100 / 57. 25.100
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 31.100 /  6. 31.100
libavresample   3.  0.  0 /  3.  0.  0
libswscale      4.  0.100 /  4.  0.100
libswresample   2.  0.101 /  2.  0.101
libpostproc    54.  0.100 / 54.  0.100

**Comment by dstftw** [comment]
Read this https://github.com/rg3/youtube-dl/issues/new.
