### ISSUE TITLE
Pluralsight still ban

### ISSUE THREAD

**Issue by lilleindi** [rg3/youtube-dl#9919]
Hi
I have been downloading from Pluralsight for about a week. I set the interval to 360.. Then after a week and 15-20 courses they banned me for making to many request..
Then i started downloading only one course pr day. But after only one course they banned me a second time with the message
"This does mean a high volume of requests that are in the realm of a request every 10-30 seconds for a prolonged period of time"

How can that be when i set the interval to 360 (6min)?
And what can i do so it dont make request every 10-30 Sec?

Regards
Lilleindianer

**Comment by dstftw** [comment]
No concrete recipes. Use search for possible tips.
