### ISSUE TITLE
Site request: lenta.ru

### ISSUE THREAD

**Issue by nmr50** [rg3/youtube-dl#9926]
Hiya Authors !
I just met nice video on news site named as lenta.ru and I'd be glad to get this video on my hdd.
The url is: https://lenta.ru/news/2016/06/27/bad_boy/
- Note that this site offers 3 quality options - up to 720p.
Please add this lenta.ru video engine to your VERY NICE program!:)
Thanks in advance!
-t

**Comment by nmr50** [comment]
I just updated version to 2016.06.27 - still got no ability to dload videos from lenta.ru ... Should I wait for the next release ?

**Comment by dstftw** [comment]
It's not yet released.

**Comment by nmr50** [comment]
Ok, Thank you ppl !:) I'll be waiting.
