### ISSUE TITLE
Error when trying to install on web server Please help!

### ISSUE THREAD

**Issue by nekle** [rg3/youtube-dl#9927]
error: could not create '/usr/lib/python2.6/site-packages/youtube_dl_server': Read-only file  system

I am using a shared hosting so i could  not use sudo, any suggestions?

**Comment by jaimeMF** [comment]
Probably you are trying to install https://github.com/jaimeMF/youtube-dl-api-server, report the issue there.

**Comment by nekle** [comment]
it does the same thing when i use youtube-dl

error: could not create '/usr/lib/python2.6/site-packages/youtube_dl': Read-only file system

**Comment by jaimeMF** [comment]
Since you haven't post the command you are running and the full output, we can't provide full help. If you are using `pip install youtube-dl`, you either need to run it with `sudo` or use the `--user` option.

**Comment by nekle** [comment]
When I use the command `pip install youtube-dl` this is the full output i get: Downloading/unpacking youtube-dl
  Running setup.py egg_info for package youtube-dl
Installing collected packages: youtube-dl
  Running setup.py install for youtube-dl
    error: could not create '/usr/lib/python2.6/site-packages/youtube_dl': Read-only file system
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/home3/nekle/build/youtube-dl/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-GJTTWZ-record/install-record.txt:
    running install

running build

running build_py

running install_lib

creating /usr/lib/python2.6/site-packages/youtube_dl

error: could not create '/usr/lib/python2.6/site-packages/youtube_dl': Read-only file system

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/home3/nekle/build/youtube-dl/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-GJTTWZ-record/install-record.txt failed with error code 1 in /home3/nekle/build/youtube-dl
Storing complete log in /home3/nekle/.pip/pip.log

I cannot run sudo since its a shared hosting and is not letting me use it. How can i use the --user option?

**Comment by jaimeMF** [comment]
> I cannot run sudo since its a shared hosting and is not letting me use it. How can i use the --user option?

`pip install --user youtube-dl`?

**Comment by nekle** [comment]
Thank you so much !! it worked!! you saved my life :)
