### ISSUE TITLE
[Feature request] Colorized output

### ISSUE THREAD

**Issue by xtemp09** [rg3/youtube-dl#9936]
Could you add an option that makes the following output:
https://s32.postimg.org/a688bqipx/colorless.png

look like that:
https://s32.postimg.org/pqfm29sud/colorfull.png

?

(Color palette may be different)

**Comment by jaimeMF** [comment]
And what's the criteria for each color? Please explain in detail what you want, because I don't get it from just two images.

**Comment by xtemp09** [comment]
Any criterion, I'm sure, the developers will apply one they consider reasonable.

**Comment by jaimeMF** [comment]
Well, you are the one asking for it. If you can't provide a useful criterion, it means [that the bug report is incomplete](https://github.com/rg3/youtube-dl/blob/c1823c8ad9ca49f61ef15bbc126b0f95e4825d14/README.md#is-the-description-of-the-issue-itself-sufficient) and I'm closing it.

**Comment by xtemp09** [comment]
Ok, here is my criterion: different formats should be in different colors, so as resolution.

**Comment by jaimeMF** [comment]
So you want one colour for each  resolution? That doesn't to be the case in your images.

Do you think it's useful? I think it would be a bit confusing since it wouldn't be obvious why they are being coloured. And I don't see how it would help, at least in the case of colouring the `WARNING` and `ERROR` messages it helps you notice them.

**Comment by xtemp09** [comment]
The youtube-dl output is long and wide. The useful information is somewhere in the middle of the screen. Youtube-dl groups output, however, it’s still not enough to get it in short time. Every shell can output in color. Why do you not like the idea of making use of it? Other tools can be good too, like setting text in bold or italics.

**Comment by dstftw** [comment]
As seen from your screenshots useful information is right on the bottom for a single video not in the middle. Even if it's a playlist coloring each format in different color does not make any particular needless to say it may just complicating readability.

**Comment by xtemp09** [comment]
I wrote a wrapper using grep and perl. =/

**Comment by Hrxn** [comment]
Well, I agree it would be useful. For a start, the defaults could be highlighted, i.e. `bestvideo,bestaudio,best` and their entries from the format list.
