### ISSUE TITLE
[lothype] New Site Support Request

### ISSUE THREAD

**Issue by wright546** [rg3/youtube-dl#9938]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.27*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.27**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v http://www.lothype.com/bluecoats-2016-rehearsal-run-side/
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.lothype.com/bluecoats-2016-rehearsal-run-side/']
[debug] Encodings: locale US-ASCII, fs US-ASCII, out US-ASCII, pref US-ASCII
[debug] youtube-dl version 2016.06.27
[debug] Python version 2.7.9 - FreeBSD-10.3-RELEASE-amd64-64bit-ELF
[debug] exe versions: ffmpeg 2.6.3, ffprobe 2.6.3
[debug] Proxy map: {}
[generic] bluecoats-2016-rehearsal-run-side: Requesting header
WARNING: Falling back on generic information extractor.
[generic] bluecoats-2016-rehearsal-run-side: Downloading webpage
[generic] bluecoats-2016-rehearsal-run-side: Extracting information
ERROR: Unsupported URL: http://www.lothype.com/bluecoats-2016-rehearsal-run-side/
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 1464, in _real_extract
    doc = compat_etree_fromstring(webpage.encode('utf-8'))
  File "./youtube-dl/youtube_dl/compat.py", line 2524, in compat_etree_fromstring
    doc = _XML(text, parser=etree.XMLParser(target=_TreeBuilder(element_factory=_element_factory)))
  File "./youtube-dl/youtube_dl/compat.py", line 2513, in _XML
    parser.feed(text)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: undefined entity: line 40, column 0
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/generic.py", line 2161, in _real_extract
    raise UnsupportedError(url)
UnsupportedError: Unsupported URL: http://www.lothype.com/bluecoats-2016-rehearsal-run-side/...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
http://www.lothype.com/bluecoats-2016-rehearsal-run-side/
http://www.lothype.com/phantom-regiment-2016-rehearsal-run-voice-promise/
http://www.lothype.com/cadets-2016-awakening/
http://www.lothype.com/blue-devils-2016-show-run-lot-dci-west/
http://www.lothype.com/bluecoats-2016-side/
http://www.lothype.com/sacramento-mand/
http://www.lothype.com/blue-stars-2016-preview-standstill-full-show/
http://www.lothype.com/eleven-blue-devils-drumline-2016/
http://www.lothype.com/blue-devils-2016-lot/
http://www.lothype.com/blue-devils-drumline-stanford-lot-2016/
http://www.lothype.com/blue-devils-2016-show-run-lot-dci-west/
http://www.lothype.com/dreams-made-opener-blue-devils-drumline-2016/
http://www.lothype.com/carolina-crown-2016-hornline-quality-audio/
http://www.lothype.com/2016-carolina-crown-ostinato-series-a-dci-opening-night-4k/
http://www.lothype.com/carolina-crown-2016-fighting-choreography-preview/
http://www.lothype.com/cavaliers-2016-show-preview/
http://www.lothype.com/bluecoats-2016-rehearsal-run-side/
http://www.lothype.com/bluecoats-battery-dci-2016-tour-premiere/
http://www.lothype.com/bluecoats-2014-tilt/
http://www.lothype.com/bluecoats-2016-side/
http://www.lothype.com/blue-knights-2016-bkat/
http://www.lothype.com/blue-knights-2016-drumline-dci-west-gumby/
http://www.lothype.com/blue-knights-2016-drumline-sacramento-ca/
http://www.lothype.com/dci-2016-blue-knights-percussion-splitscreen/
http://www.lothype.com/cadets-drumline-2016/
http://www.lothype.com/cadets-2016-awakening/
http://www.lothype.com/2016-cadets-hornline-michigan-city-626/
http://www.lothype.com/phantom-regiment-2016-rehearsal-run-voice-promise/
http://www.lothype.com/phantom-regiment-dci-2016-tour-premiere/
http://www.lothype.com/santa-clara-vanguard-2016-in-4k-dci-west-the-force-of-nature/
http://www.lothype.com/santa-clara-vanguard-brass-2016-in-4k-dci-west-send-in-the-clowns/
http://www.lothype.com/santa-clara-vanguard-2016-drumline-lot-dci-west/
http://www.lothype.com/dci-2016-santa-clara-vanguard-drumline-multi-cam/
http://www.lothype.com/santa-clara-vanguard-percussion-2016-4k-dci-fresno-lot/

---

### Description of your *issue*, suggested solution and other information

This site compiles links for specific subjects from Youtube, Vimeo, etc.  They don't seem to be consistent though as youtube-dl seems to know how to handle about half of them.  I've pasted links to the ones where youtube-dl reports "Error: Unsupported URL"

**Comment by TRox1972** [comment]
Videos seems to be YouTube or Facebook embeds

**Comment by yan12125** [comment]
All Facebook and YouTube embedded videos found in URLs above will be recognized in the next version.
