### ISSUE TITLE
Downloading existing videos that youtube-dl might not see (not an issue)

### ISSUE THREAD

**Issue by JCAndresen** [rg3/youtube-dl#9939]
### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ x] Feature request (request for a new functionality)
- [ x] Question
- [x] Other

Is it possible to get youtube-dl to check the destination directory if a youtube video of the same title exists? I have a lot of .mp4 files since I didnt know about youtube-dl, most bestvideo+bestaudio downloads mkv files so it just downloads it since there is no existing mkv file. can I get it to check if mp4 exists? 

Also, is it possible to get it to download and merge on a local directory and then move it to a destination directory, say like a server ?

Thanks.

**Comment by dstftw** [comment]
1. Either write script or pass `--download-archive` a hand-crafted file with line `youtube video_id` for each downloaded video. Alternatively tell to [only download mp4](https://github.com/rg3/youtube-dl#format-selection-examples).
2. You can run arbitrary command on downloaded file with `--exec`.

**Comment by JCAndresen** [comment]
telling it to download mp4 still ends up creating a mkv file and it downloads it even though a file with the same name (but .mp4 extension) exists... 

I'll have to figure out the script.. 

Thanks for the quick reply!

**Comment by dstftw** [comment]
Post `--verbose` output.
Post the listing of files in directory.

**Comment by JCAndresen** [comment]
problem was the title, it was looking for the youtube id and the other file didnt have that. 

thanks for taking the time to look at it ! have a great day.

**Comment by dstftw** [comment]
You can specify output template `-o '%(title)s.%(ext)s'` to look for title only.

**Comment by JCAndresen** [comment]
can you verify how i can set it up to download in a local directory and then move it afterwards? im guessing it wouldnt be able to look in the destination directory if it is downlodaing it to the local one.. hmm

**Comment by dstftw** [comment]
What are you trying to achieve in the first place? Clearly explain the use case.

**Comment by JCAndresen** [comment]
My server holds all my video files. 
My ubuntu VM takes forever to download and merge videos if I do it in the remote directory. 
If it does it locally then it downloads with full speed and merges 10 times quicker than remote. 

Is there anyway I can, within youtube-dl, move a file to a remote location after it has been merged? 

Id would have to check the remote location before downloading.

**Comment by dstftw** [comment]
I've already pointed out using `--exec` for that with command that will do the move, like `--exec 'mv {} destination'`.

**Comment by JCAndresen** [comment]
Thanks! Really appreciate the time.
