### ISSUE TITLE
Youtube video that captured by youtube from a stream does not download

### ISSUE THREAD

**Issue by zerkms** [rg3/youtube-dl#9943]
- [x] Bug report (encountered problems with youtube-dl)

https://www.youtube.com/watch?v=nxnIpgHQ-Gw - this is the problem video 

The `ffmpeg` starts and freezes forever on frame 300:

    frame=  300 fps=114 q=-1.0 size=     437kB time=00:00:10.03 bitrate= 356.5kbits/s  

Selecting different formats using `-f` does not change anything: they all freeze on the frame `300`

I've tried bunch of other tools and services and none of them is capable of downloading it.

**Comment by yan12125** [comment]
Maybe a ffmpeg bug. Try adding ```--hls-prefer-native```.

**Comment by zerkms** [comment]
At least it progresses now - it downloads separated fragments and by the moment created 300+ files.

And every fragment is 150 frames long, so seems like the `ffmpeg`-based implementation could encode only 2 of them.

**Comment by yan12125** [comment]
Closing. This report should be forwarded to http://trac.ffmpeg.org/.

**Comment by zerkms** [comment]
Not sure how `ffmpeg` can be responsible for that - the video is chunked, there is no single url you can download and encode it from.
