### ISSUE TITLE
[anime-on-demand] Download videos with old player

### ISSUE THREAD

**Issue by kitokirisaki** [rg3/youtube-dl#9944]
If i want to download a video or movie with the current extractor he cant find any episode...see example:

youtube-dl -v -uUSER https://www.anime-on-demand.de/anime/88
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'-uUSER', u'https://www.anime-on-demand.de/anime/88']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.27
[debug] Python version 2.7.9 - Linux-3.16.0-4-amd64-x86_64-with-debian-8.5
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
[AnimeOnDemand] Downloading login page
[AnimeOnDemand] Logging in as USER
[AnimeOnDemand] 88: Downloading webpage
[AnimeOnDemand] 88: Activating HTML5 beta
[AnimeOnDemand] 88: Downloading webpage
[download] Downloading playlist: The Garden of Words
[AnimeOnDemand] playlist The Garden of Words: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: The Garden of Words

I think the reason for this is no support for the old Player. The other reason is no support for movies. I think the old player is the "jwplayer6".

To find out which type of anime the url is you can search the source-code for following strings:

```
"<h2 class="hide-for-display">Film-Inhalt</h2>" for Movies
"<h2 class="hide-for-display">Serien-Inhalt</h2>" for series.
```

to start the stream you have following code (buttons)

```
<div class="besides">
    <div class="besides-box">
        <form class="button_to" method="get" action="#"><input class="highlight streamstarter" title="SD-Stream starten" data-stream="/videomaterialurl/sd/1152" data-dialog-header="The Garden of Words" type="submit" value="SD starten" /></form>
    </div>
    <div class="besides-box">
        <form class="button_to" method="get" action="#"><input class="highlight streamstarter" title="HD-Stream starten" data-stream="/videomaterialurl/hd/1152" data-dialog-header="The Garden of Words" data-stream-quality="HD" type="submit" value="HD starten" /></form>
    </div>
</div>
```

If you need my login data i can give you that. But maybe private.

A example URL for a movie is: https://www.anime-on-demand.de/anime/88

**Comment by Timtam** [comment]
Want to bump this up. We got a similar issue here, following this url:
https://www.anime-on-demand.de/anime/12

Log follows:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-v', u'--all-subs', u'--sub-format', u'srt', u'--embed-subs', u'--ffmpeg-location', u'/var/packages/ffmpeg/target/bin/', u'https://www.anime-on-demand.de/anime/12']
[debug] Encodings: locale UTF-8, fs UTF-8, out None, pref UTF-8
[debug] youtube-dl version 2017.09.10
[debug] Python version 2.7.12 - Linux-3.2.40-i686-with-glibc2.0
[debug] exe versions: ffmpeg information, ffprobe information
[debug] Proxy map: {}
[AnimeOnDemand] Downloading login page
[AnimeOnDemand] Logging in as PRIVATE
[AnimeOnDemand] 12: Downloading webpage
[AnimeOnDemand] 12: Activating HTML5 beta
[AnimeOnDemand] 12: Downloading webpage
[download] Downloading playlist: Magister Negi Magi Negima!?
[AnimeOnDemand] playlist Magister Negi Magi Negima!?: Collected 28 video ids (downloading 28 of them)
[download] Downloading video 1 of 28
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://www.anime-on-demand.de/system/episodes/trailers/000/000/152/original/a726727b3a6e605aa968dfd70383537ba1332c47.mp4?1453391997'
[download] Magister Negi Magi Negima! _ Episode 1 (Teaser)-episode-1-teaser.mp4 has already been downloaded

[download] 100% of 3.74MiB
[ffmpeg] There aren't any subtitles to embed
[download] Downloading video 2 of 28
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://www.anime-on-demand.de/system/episodes/trailers/000/000/153/original/8ef85c259ce1bc92d42de9faf0956cb0438d57eb.mp4?1453391997'
[download] Magister Negi Magi Negima! _ Episode 2 (Teaser)-episode-2-teaser.mp4 has already been downloaded

[download] 100% of 4.14MiB
[ffmpeg] There aren't any subtitles to embed
...
[continues until episode 28]

So, he just finds the teasers, but not the actual episodes themselves. It seems they are still using some old player here. Any way to support this player too?

**Comment by Timtam** [comment]
@dstftw saw that you got mentioned earlier, maybe you got some sort of idea?
