### ISSUE TITLE
youtube-dl simply doesn't work on my pc

### ISSUE THREAD

**Issue by bkabchr** [rg3/youtube-dl#9946]
Hello, I desesperately need to download videos from ok.ru and found this cool software, but it just doesn't work on my pc. I'm running Win 10 with everything uptodate ( including vcredist ) , and it just launch and closes itself.

```
Usage: youtube-dl.exe [OPTIONS] URL [URL..]

youtube-dl.exe: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.
```

Thanks a lot for your help.

**Comment by dstftw** [comment]
```
youtube-dl.exe http://ok.ru/video/20079905452
```

**Comment by bkabchr** [comment]
Well, when I open the .exe, it just closes itself and I can't type anything.. I launched it in admin mode, compatibility mode, but nothing seems to work!

**Comment by dstftw** [comment]
https://github.com/rg3/youtube-dl/issues/1995#issuecomment-30741689
