### ISSUE TITLE
youtube-dl -U as Administrator makes the command prompt appear multiple times

### ISSUE THREAD

**Issue by sunk818** [rg3/youtube-dl#9948]
Thanks for even having the ability to update our youtube-dl from the command line.

Has anyone else noticed that the command prompt comes back, but youtube-dl is still working in the background to update the executable? Not sure what's going on, but it looks confusing...

![image](https://cloud.githubusercontent.com/assets/6989799/16462304/75a9459a-3de5-11e6-97c8-5723930fad42.png)

**Comment by dstftw** [comment]
That is expected behavior for now.
