### ISSUE TITLE
can't download vevo videos on youtube ??

### ISSUE THREAD

**Issue by azizjassar** [rg3/youtube-dl#9957]
hi, 
i tried to download this video "EPo5wWmKEaI" from youtube which is belong to vevo channel. but i can't download it. i guess the signature problem is coming back again.
please help

**Comment by dstftw** [comment]
You are using an outdated version of youtube-dl. Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by azizjassar** [comment]
youtube-dl is up-to-date (2016.06.27)

**Comment by dstftw** [comment]
Now prove that with correctly filled [new issue template](https://github.com/rg3/youtube-dl/issues/new).

**Comment by azizjassar** [comment]
ohh that was a mistake by me, i used a outdated version on my website, and instead i updated youtube-dl located in another folder that i use for debug.
thanks a lot :+1:
