### ISSUE TITLE
upgraded ubuntu to 16.04; youtube-dl no longer downloading from xtube

### ISSUE THREAD

**Issue by ski4everinvt** [rg3/youtube-dl#9961]
here is the output:
youtube-dl -v http://www.xtube.com/video-watch/German-Stud-s-Cumcontrol-Tolerance-Training-26396531
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.xtube.com/video-watch/German-Stud-s-Cumcontrol-Tolerance-Training-26396531']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.03.27
[debug] Python version 2.7.11+ - Linux-4.4.0-28-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2
[debug] Proxy map: {}
[XTube] German-Stud-s-Cumcontrol-Tolerance-Training: Downloading webpage
ERROR: Unable to extract player ops; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 669, in extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 321, in extract
    return self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/xtube.py", line 56, in _real_extract
    r'xt\.playerOps\s*=\s*({.+?});', webpage, 'player ops'),
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 622, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player ops; please report this issue on https://yt-dl.org/bug

**Comment by ski4everinvt** [comment]
note that when i use youtube dl -U --, it says my version is up to date but in the error line, it indicates a version from 3-27 is being used

**Comment by ski4everinvt** [comment]
follow-up: I now have the most recent version:
ki4evervt@ski4evervt-ThinkPad-T61:/bin$ youtube-dl http://www.xtube.com/video-watch/German-Stud-s-Cumcontrol-Tolerance-Training-26396531
[XTube] German-Stud-s-Cumcontrol-Tolerance-Training: Downloading webpage
ERROR: Unable to extract player ops; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ski4evervt@ski4evervt-ThinkPad-T61:/bin$ youtube-dl --verbose http://www.xtube.com/video-watch/German-Stud-s-Cumcontrol-Tolerance-Training-26396531
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://www.xtube.com/video-watch/German-Stud-s-Cumcontrol-Tolerance-Training-26396531']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.30
[debug] Python version 2.7.11+ - Linux-4.4.0-28-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.6-1ubuntu2, ffprobe 2.8.6-1ubuntu2, rtmpdump 2.4
[debug] Proxy map: {}
[XTube] German-Stud-s-Cumcontrol-Tolerance-Training: Downloading webpage
ERROR: Unable to extract player ops; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/xtube.py", line 56, in _real_extract
    r'xt\.playerOps\s*=\s*({.+?});', webpage, 'player ops'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 646, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract player ops; please report this issue on https://yt-dl.org/bug .

**Comment by yan12125** [comment]
Related: #9953
