### ISSUE TITLE
brightcove empty playlist for playlistTabs

### ISSUE THREAD

**Issue by alexus-m** [rg3/youtube-dl#9965]
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.30**
- [X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Bug report (encountered problems with youtube-dl)
- [X] Site support request (request for adding support for a new site)

---

$ ./youtube-dl --verbose "http://c.brightcove.com/services/json/experience/runtime/?command=get_programming_for_experience&playerKey=AQ~~,AAABXlLMdok~,NJ4EoMlZ4rZdx9eU1rkMVd8EaYPBBUlg"
[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'http://c.brightcove.com/services/json/experience/runtime/?command=get_programming_for_experience&playerKey=AQ~~,AAABXlLMdok~,NJ4EoMlZ4rZdx9eU1rkMVd8EaYPBBUlg']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.06.30
[debug] Python version 2.7.11 - Linux-4.5.7-300.fc24.x86_64-x86_64-with-fedora-24-Twenty_Four
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2
[debug] Proxy map: {}
[brightcove:legacy] AQ~~,AAABXlLMdok~,NJ4EoMlZ4rZdx9eU1rkMVd8EaYPBBUlg: Downloading playlist information
ERROR: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/brightcove.py", line 265, in _real_extract
    return self._get_playlist_info(player_key[0])
  File "./youtube-dl/youtube_dl/extractor/brightcove.py", line 302, in _get_playlist_info
    raise ExtractorError('Empty playlist')
ExtractorError: Empty playlist; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

Downloading from brightcove.com failed with "ExtractorError: Empty playlist;" if playlist is started with "playlistTabs" tag instead of "videoList". Format of playlist is also slightly modified.

**Comment by yan12125** [comment]
How did you get this link? For example from which web page?

**Comment by alexus-m** [comment]
The link have been got from an e-learning (hatacademy.com) web page accessible via paid subscription. I've downloaded the source web page via youtube-dl with help of cookies. Each training has two playlists mentioned on it's web page: the first one is "playlistTabs" which failed to download, while second "videoList" successfully downloaded by youtube-dl.

**Comment by yan12125** [comment]
Thanks. 'playlistTabs' should be correctly recognized in the next version. Please check that downloaded videos are what you expect then.

**Comment by alexus-m** [comment]
I've checked some brightcove playlists in both formats with youtube-dl 2016.07.07 - everything looks like working as expected.
Thanks a lot for great tool with strong and quick support!
