### ISSUE TITLE
Downloading vine videos no longer works.

### ISSUE THREAD

**Issue by orbea** [rg3/youtube-dl#9970]
- [ x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.01**

- [x ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

```
$ youtube-dl --verbose https://vine.co/v/iL2dF5FhnBx
[debug] System config: []
[debug] User config: ['--prefer-free-formats', '--format', 'webm/ogg/best']
[debug] Command-line args: ['--verbose', 'https://vine.co/v/iL2dF5FhnBx']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.01
[debug] Python version 3.5.1 - Linux-4.6.3-x86_64-AMD_FX-tm-6350_Six-Core_Processor-with-slackware-14.2
[debug] exe versions: ffmpeg 3.0.2, ffprobe 3.0.2, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: Unable to extract vine data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 676, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/common.py", line 343, in extract
    return self._real_extract(url)
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/vine.py", line 94, in _real_extract
    webpage, 'vine data'),
  File "/usr/lib64/python3.5/site-packages/youtube_dl/extractor/common.py", line 646, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract vine data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output
```
---

### Description of your *issue*, suggested solution and other information

Downloading videos with vine apparently has stopped working, this was working as of a few days ago according to a friend.

**Comment by TRox1972** [comment]
I get the same result, for other videos too. Relaxing/changing the regex for `vine data` solves the issue
