### ISSUE TITLE
HTTP 403: ERROR - general error, not Forbidden or anything

### ISSUE THREAD

**Issue by magumbasauce** [rg3/youtube-dl#9975]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X ] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.01**

### Before submitting an *issue* make sure you have:
- [ X] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```

Z:\>youtube-dl.exe -u <REMOVED> -p <REMOVED> https://www.twitch.tv/geekandsundry/v/75521325 --verbose --no-cache-dir -F

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.twitch.tv/geekandsundry/v/75521325', '--verbose', '--no-cache-dir', '-F']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2016.07.01
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: ffmpeg N-80129-ga1953d4
[debug] Proxy map: {}
ERROR: Failed to download m3u8 information: HTTP Error 403: ERROR (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcna42527\build\youtube_dl\extractor\common.py", line 390, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcna42527\build\youtube_dl\YoutubeDL.py", line 1950, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
...
<end of log>
```

---

### Description of your *issue*, suggested solution and other information

Each week I download Critical Role after their stream from Geek & Sundry from Twitch.tv. last night youtube-dl errored. It said to make sure I updated, so I did and it gave the same error. I researched some today and tried some tweaks to the command and nothing has worked. The other suggestion in the text was to post a bug here, so that's what i'm doing. 

Not totally sure it's a bug in youtube-dl or not, but at least there might be useful things to output since this just errors. The latest thing I tried to do was to get a specific format with the same command adding the -F option. I typically don't have the --no-cache-dir and just grab the video without issues.

**Comment by dstftw** [comment]
This video requires a subscription. Does you account valid and not expired? Can you watch it in browser at all?
When posting verbose log **do not** remove any non-sensible data - you've removed at least five lines.

**Comment by magumbasauce** [comment]
It does and I can view the video online as my subscription is up to date. What I do is after the stream I navigate to the video itself in the browser as if going to watch it in the browser to copy the link, then copy it to the batch file where I have the command saved. So i wouldn't even be able to get the URL without a valid subscription. 

My apologies. Here's what happened. I didn't intentionally remove anything from the --verbose debug. What i tried to do was send everything to a file with > debug.txt. What happened was that only those 5 lines went to that file, the rest went to the command window itself. When I posted, I didn't look carefully enough at the debug to notice that those 5 lines were missing from the last command I ran, which had the > debug.txt. Attached is a screenshot of the debug without the > debug.txt at the end of the command. I've only blacked out my user/pass from the command itself. not sure why trying to send everything to a file would have some go and some not unless not everything is going through the same pipe. 

![snag-0018](https://cloud.githubusercontent.com/assets/20244344/16525651/66d90978-3f7b-11e6-86ac-e04f3f1d9860.png)

**Comment by dstftw** [comment]
For any further investigations you'll have to provide account credentials since I don't have a subscription.

**Comment by magumbasauce** [comment]
email sent with credentials for testing.

**Comment by AraHaan** [comment]
hmm did you try updating to the 2016.07.01 build of ffmpeg?
