### ISSUE TITLE
gpg keys should be cross-signed

### ISSUE THREAD

**Issue by Blacker47** [rg3/youtube-dl#9977]
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

### Description of your *issue*, suggested solution and other information

Gpg keys used to sign the releases on http://rg3.github.io/youtube-dl/download.html should be cross-signed by other mentioned keys to build a minimal trust chain for users. Especially for the newer key 18A9236D Sergey M.

**Comment by phihag** [comment]
I apologize; we should have done this right from the start. The [certificate](http://pgp.mit.edu/pks/lookup?op=vindex&search=0x2C393E0F18A9236D) should be available at your keyserver of choice shortly.
