### ISSUE TITLE
Bug#632922 - revisited?

### ISSUE THREAD

**Issue by br0kenwrkflow** [rg3/youtube-dl#9983]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.02*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.02**

### Before submitting an *issue* make sure you have:
- [X ] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v sudo sudo youtube-dl -v --audio-format mp3 https://youtu.be/-_65t46eYJQ
[debug] System config: [u'--extract-audio', u'--audio-format=mp3']
[debug] User config: []
[debug] Command-line args: [u'-v', u'--audio-format', u'mp3', u'https://youtu.be/-_65t46eYJQ']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.07.02
[debug] Python version 2.7.3 - Linux-3.2.0-4-686-pae-i686-with-debian-7.11
[debug] exe versions: avconv 0.8.17-6, avprobe 0.8.17-6, ffmpeg N-79008-g15ef98a, ffprobe N-79008-g15ef98a
[debug] Proxy map: {}
[youtube] -_65t46eYJQ: Downloading webpage
[youtube] -_65t46eYJQ: Downloading video info webpage
[youtube] -_65t46eYJQ: Extracting video information
[youtube] -_65t46eYJQ: Downloading MPD manifest
[debug] Invoking downloader on u'https://r5---sn-qxo7sn7k.googlevideo.com/videoplayback?id=fbfeb9b78e9e6094&itag=251&source=youtube&requiressl=yes&initcwndbps=417500&mn=sn-qxo7sn7k&mm=31&ms=au&mv=m&gcr=us&nh=IgpwcjAxLmRlbjAyKgkxMjcuMC4wLjE&pl=17&ratebypass=yes&mime=audio/webm&gir=yes&clen=3928424&lmt=1449654476667643&dur=243.081&signature=626089B095D4FE58CEF8E45B23958A090B9E416A.945B05B4946288105FAFBE2C5815B92F9CC12168&sver=3&upn=reJ9GyaagHY&key=dg_yt0&mt=1467477098&fexp=9405348,9416126,9416891,9419451,9422596,9425184,9428398,9429608,9429742,9431012,9433096,9433221,9433782,9433946,9435526,9435693,9435876,9437066,9437552,9437681,9437742,9437919,9438557,9438784,9438870,9439415,9439652,9440266,9440376&ip=71.211.174.97&ipbits=0&expire=1467499209&sparams=ip,ipbits,expire,id,itag,source,requiressl,initcwndbps,mn,mm,ms,mv,gcr,nh,pl,ratebypass,mime,gir,clen,lmt,dur'
[download] Destination: Tritonal & Paris Blohm ft. Sterling Fox - Colors (Official Music Video)--_65t46eYJQ.webm
[download] 100% of 3.75MiB in 00:02
[debug] avconv command line: avprobe -show_streams 'file:Tritonal & Paris Blohm ft. Sterling Fox - Colors (Official Music Video)--_65t46eYJQ.webm'
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1786, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 232, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
PostProcessingError
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://youtu.be/-_65t46eYJQ

This video has a "-" in front of the title, may be causing the reason why the ffprobe has an error

---

### Description of your *issue*, suggested solution and other information
I think this is a problem seen 5 years ago where a '-' character of a given youtube link title fails, to extract the audio from youtube-dl witnessing the same symptoms on the 2016.07.02 version

Related thread:
http://linux.debian.bugs.dist.narkive.com/hDAF5aGe/bug-632922-fails-to-extract-audio-from-file-whose-name-begins-with-hyphen

Environment running on:
/etc/*release
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"

**Comment by dstftw** [comment]
It has nothing to do with leading `-`. Update to avconv 11 or use `--prefer-ffmpeg`.

**Comment by dstftw** [comment]
It has nothing to do with leading `-`. Update to avconv 11 or use `--prefer-ffmpeg`.
