### ISSUE TITLE
Usernames with blank spaces

### ISSUE THREAD

**Issue by WyRe** [rg3/youtube-dl#9985]
Hi all, I'm trying to download all videos from one chanel, I'm using that parameters

`youtube-dl.exe --audio-format mp3 --audio-quality 320k -x ytuser:<USER>`

But that only works if the username hasn't got spaces in his name, how can I specify spaces there? 

Thank you so much :)

**Comment by dstftw** [comment]
Use complete URL instead of `ytuser`.
