### ISSUE TITLE
New regression : national geographic channel

### ISSUE THREAD

**Issue by anisse** [rg3/youtube-dl#9991]
See this build:
https://travis-ci.org/anisse/youtube-dl/jobs/141912668

Maybe introduced by  a1f6f5c. Ping @remitamine

**Comment by remitamine** [comment]
the reason for changing to HLS formats: https://github.com/rg3/youtube-dl/commit/a1f6f5c768a506674928530990b7f95c605eac2c#commitcomment-18107168
