### ISSUE TITLE
How to make a subtitle file default?

### ISSUE THREAD

**Issue by SaikyoKid** [rg3/youtube-dl#9992]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.07.03*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.07.03**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [ ] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.07.03
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: http://www.crunchyroll.com/naruto-shippuden/episode-451-itachis-story-light-and-darkness-birth-and-death-696211

---

### Description of your *issue*, suggested solution and other information

I wanted to download all the subtitles for a video and now i see that the subtitle is not default marked. is there any way to make a particular language subtitle to be default?

**Comment by dstftw** [comment]
Add `--sub-lang` option to [config file](https://github.com/rg3/youtube-dl#configuration).

**Comment by SaikyoKid** [comment]
I am on windows and I use youtube-dl.exe and I can't find the config file on either of the locations : `%APPDATA%\youtube-dl\config.txt` or `C:\Users\<user name>\youtube-dl.conf` any guesses why?

**Comment by SaikyoKid** [comment]
I made the conf file and placed in the appropriate place. And executed the following command : 

`youtube-dl "http://www.crunchyroll.com/naruto-shippuden/episode-451-itachis-story-light-and-darkness-birth-and-death-696211"  -f 360p --all-subs --sub-format ass --recode-video mkv --postprocessor-args "-c copy"  --embed-subs --merge-output-format mkv`

It merged all the subtitle files in like I wanted. But, it did not mark the english subtitle as default.

**Comment by dstftw** [comment]
What do you mean by default in the first place?

**Comment by SaikyoKid** [comment]
You know, like make the video player play that particular subtitle file only.
Let's say I have 5 files in a video and I want the video player to load english subtitle by default.

**Comment by zackmark29** [comment]
> What do you mean by default in the first place?

Hello dev. since there is a issue about this.
Is there any fix to make the subtitle as default on mp4 output?
